### ISSUE TITLE
Do we open issues here?  Because easy.

### ISSUE THREAD

**Issue by epowell101** [openebs/openebs#1]
Hello everyone.  Cool project.

**Comment by kmova** [comment]
Thanks @epowell101!!

Yes, This is a good place to post the issues by users of the project. 

The contributors can also use the issues board on specific modules like openebs/maya, openebs/gotgt, etc., The consolidated list of issues can be accessed using this link:
https://github.com/issues?utf8=%E2%9C%93&q=user%3Aopenebs

**Comment by AmitKumarDas** [comment]
We might have the overall documentation & perhaps the site's source here.
