### ISSUE TITLE
Need to update the redirecting URL

### ISSUE THREAD

**Issue by maheshreddy7797** [openebs/openebs#100]
At the bottom of the home page of openEBS, in the contribute section when I click on slack icon it's not redirecting to http://slack.openebs.io/  instead it is redirecting to https://www.openebs.io/slack.openebs.io which is not a slack webpage.

**Comment by AmitKumarDas** [comment]
@deepakjayaprakash Can you look into it ?

**Comment by deepakjayaprakash** [comment]
Fixed it.
