### ISSUE TITLE
Create storage pool crd with client-go 5.0

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#1004]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

To create a storage pool(sp) crd with latest client-go(5.0) version of kubernetes, on receiving any resource event of spc

**Comment by kmova** [comment]
This will be now implemented as part of node-disk-manager.
