### ISSUE TITLE
Corrupted journal in filesystem

### ISSUE THREAD

**Issue by AndreasBomholtz** [openebs/openebs#1018]
## BUG REPORT

**What happened**:
The filesystem in my PV was marked as "read-only" and now my pod will not start.
My pod is using the disk a lot.

I get these error messages in kubernetes:
`Error: failed to start container "phabricator-phabricator": Error response from daemon: {"message":"SELinux relabeling of /var/lib/kubelet/pods/7c947923-dfea-11e7-a5ee-50465da1a343/volumes/kubernetes.io~iscsi/pvc-65ef4b10-cdc4-11e7-8de2-10bf487ee21f is not allowed: \"read-only file system\""}`

`MountVolume.SetUp failed for volume "pvc-aaddef3e-ce96-11e7-8de2-10bf487ee21f" : 'fsck' found errors on device /dev/disk/by-path/ip-10.3.0.127:3260-iscsi-iqn.2016-09.com.openebs.jiva:pvc-aaddef3e-ce96-11e7-8de2-10bf487ee21f-lun-1 but could not correct them: fsck from util-linux 2.25.2 /dev/sdf: recovering journal /dev/sdf: Superblock needs_recovery flag is clear, but journal has data. /dev/sdf: Run journal anyway /dev/sdf: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY. (i.e., without -a or -p options) .`

**What you expected to happen**:
That the file system was not corrupted or that it was automatic repaired. 
Or a guide on how to fix this.

**How to reproduce it (as minimally and precisely as possible)**:
I just had my pod running for around 14 days and then this happened. 
I don't know what happened or caused this issue.

**Anything else we need to know?**:
I'm running Kubernetes 1.7.5 on CoreOS 4.12.10.

The images that I'm using:
`openebs/m-apiserver:0.4.0`
`openebs/openebs-k8s-provisioner:0.4.0`

storageclass.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standard
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 8G
```

I ran this command "sudo e2fsck volume-head-001.img" and got this output:
```
e2fsck 1.42.13 (17-May-2015)
volume-head-001.img: recovering journal
Setting free inodes count to 734414 (was 786421)
Setting free blocks count to 2746977 (was 3055920)
volume-head-001.img: clean, 52018/786432 files, 398751/3145728 blocks
```

OS:
`NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.7.0
VERSION_ID=1465.7.0
BUILD_ID=2017-09-05-2043
PRETTY_NAME="Container Linux by CoreOS 1465.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"`

Kernel:
`Linux coreos3.seluxit.com 4.12.10-coreos #1 SMP Tue Sep 5 20:29:13 UTC 2017 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux`

Log messages from PVC pods:

```
time="2017-12-06T20:09:51Z" level=info msg="Creating volume /openebs, size 42949672960/512" 
time="2017-12-06T20:09:51Z" level=info msg="Listening on data 10.2.3.3:9503" 
time="2017-12-06T20:09:51Z" level=info msg="Listening on control 10.2.3.3:9502" 
time="2017-12-06T20:09:51Z" level=info msg="Listening on sync 10.2.3.3:9504" 
time="2017-12-06T20:09:59Z" level=info msg="Removing Replica" 
10.2.81.0 - - [06/Dec/2017:20:09:59 +0000] "POST /v1/replicas/1?action=start HTTP/1.1" 200 884
time="2017-12-06T20:09:59Z" level=info msg="New connection from: 10.2.81.0:33544" 
time="2017-12-06T20:09:59Z" level=info msg="Opening volume /openebs, size 42949672960/512" 
10.2.81.0 - - [06/Dec/2017:20:09:59 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 200 1429
time="2017-12-06T20:10:02Z" level=info msg="Snapshotting [24c7f601-6d68-4531-847c-4a6acc9d7f5c] volume, user created false, created time 2017-12-06T20:10:02Z" 
10.2.81.0 - - [06/Dec/2017:20:10:02 +0000] "POST /v1/replicas/1?action=snapshot HTTP/1.1" 200 1753
time="2017-12-06T20:10:02Z" level=info msg="Running ssync [ssync -host 10.2.18.2 -port 9700 volume-head-001.img.meta]" 
time="2017-12-06T20:10:02Z" level=info msg="Syncing volume-head-001.img.meta to 10.2.18.2:9700...\n" 
time="2017-12-06T20:10:02Z" level=info msg="source file size: 164, setting up directIo: false" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync client: exit code 0" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -host 10.2.18.2 -port 9700 volume-head-001.img.meta]" 
time="2017-12-06T20:10:03Z" level=info msg="Running ssync [ssync -host 10.2.18.2 -port 9701 volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img]" 
time="2017-12-06T20:10:03Z" level=info msg="Syncing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img to 10.2.18.2:9701...\n" 
time="2017-12-06T20:10:03Z" level=info msg="source file size: 42949672960, setting up directIo: true" 
time="2017-12-06T20:10:03Z" level=info msg="The file is a hole: [       0:10485760](10485760)" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync client: exit code 0" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -host 10.2.18.2 -port 9701 volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img]" 
time="2017-12-06T20:10:03Z" level=info msg="Running ssync [ssync -host 10.2.18.2 -port 9702 volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta]" 
time="2017-12-06T20:10:03Z" level=info msg="Syncing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta to 10.2.18.2:9702...\n" 
time="2017-12-06T20:10:03Z" level=info msg="source file size: 112, setting up directIo: false" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync client: exit code 0" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -host 10.2.18.2 -port 9702 volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta]" 
10.2.81.0 - - [06/Dec/2017:20:10:03 +0000] "POST /v1/replicas/1?action=updatepeerdetails HTTP/1.1" 200 1753
```

```
time="2017-12-06T20:09:53Z" level=info msg="Creating volume /openebs, size 42949672960/512" 
time="2017-12-06T20:09:53Z" level=info msg="Listening on data 10.2.18.2:9503" 
time="2017-12-06T20:09:53Z" level=info msg="Listening on control 10.2.18.2:9502" 
time="2017-12-06T20:09:53Z" level=info msg="Listening on sync 10.2.18.2:9504" 
time="2017-12-06T20:10:02Z" level=info msg="Removing Replica" 
time="2017-12-06T20:10:02Z" level=info msg="Adding replica tcp://10.2.18.2:9502 in WO mode" 
time="2017-12-06T20:10:02Z" level=info msg="New connection from: 10.2.81.0:38860" 
time="2017-12-06T20:10:02Z" level=info msg="Opening volume /openebs, size 42949672960/512" 
10.2.81.0 - - [06/Dec/2017:20:10:02 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 200 1443
time="2017-12-06T20:10:02Z" level=info msg="Snapshotting [24c7f601-6d68-4531-847c-4a6acc9d7f5c] volume, user created false, created time 2017-12-06T20:10:02Z" 
10.2.81.0 - - [06/Dec/2017:20:10:02 +0000] "POST /v1/replicas/1?action=snapshot HTTP/1.1" 200 1766
time="2017-12-06T20:10:02Z" level=info msg="Using replica tcp://10.2.3.3:9502 as the source for rebuild " 
time="2017-12-06T20:10:02Z" level=info msg="Using replica tcp://10.2.18.2:9502 as the target for rebuild " 
10.2.18.2 - - [06/Dec/2017:20:10:02 +0000] "POST /v1/replicas/1?action=setrebuilding HTTP/1.1" 200 1571
10.2.81.0 - - [06/Dec/2017:20:10:02 +0000] "POST /v1/replicas/1?action=setrevisioncounter HTTP/1.1" 200 1571
time="2017-12-06T20:10:02Z" level=info msg="Running ssync [ssync -port 9700 -daemon volume-head-001.img.meta]" 
time="2017-12-06T20:10:02Z" level=info msg="Creating Ssync service" 
time="2017-12-06T20:10:02Z" level=info msg="open: receiving fileSize: 164, setting up directIo: false" 
time="2017-12-06T20:10:02Z" level=info msg="Ssync server opened and ready" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync server exit(0)" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -port 9700 -daemon volume-head-001.img.meta]" 
time="2017-12-06T20:10:03Z" level=info msg="Synchronizing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img to volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img@10.2.18.2:9701" 
time="2017-12-06T20:10:03Z" level=info msg="Running ssync [ssync -port 9701 -daemon volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img]" 
time="2017-12-06T20:10:03Z" level=info msg="Creating Ssync service" 
time="2017-12-06T20:10:03Z" level=info msg="open: receiving fileSize: 42949672960, setting up directIo: true" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync server opened and ready" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync server exit(0)" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -port 9701 -daemon volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img]" 
time="2017-12-06T20:10:03Z" level=info msg="Done synchronizing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img to volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img@10.2.18.2:9701" 
time="2017-12-06T20:10:03Z" level=info msg="Synchronizing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta to volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta@10.2.18.2:9702" 
time="2017-12-06T20:10:03Z" level=info msg="Running ssync [ssync -port 9702 -daemon volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta]" 
time="2017-12-06T20:10:03Z" level=info msg="Creating Ssync service" 
time="2017-12-06T20:10:03Z" level=info msg="open: receiving fileSize: 112, setting up directIo: false" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync server opened and ready" 
time="2017-12-06T20:10:03Z" level=info msg="Ssync server exit(0)" 
time="2017-12-06T20:10:03Z" level=info msg="Done running ssync [ssync -port 9702 -daemon volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta]" 
time="2017-12-06T20:10:03Z" level=info msg="Done synchronizing volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta to volume-snap-24c7f601-6d68-4531-847c-4a6acc9d7f5c.img.meta@10.2.18.2:9702" 
time="2017-12-06T20:10:03Z" level=info msg="Reloading volume" 
10.2.18.2 - - [06/Dec/2017:20:10:03 +0000] "POST /v1/replicas/1?action=reload HTTP/1.1" 200 1571
10.2.81.0 - - [06/Dec/2017:20:10:03 +0000] "POST /v1/replicas/1?action=setrevisioncounter HTTP/1.1" 200 1571
10.2.81.0 - - [06/Dec/2017:20:10:04 +0000] "POST /v1/replicas/1?action=updatepeerdetails HTTP/1.1" 200 1571
10.2.18.2 - - [06/Dec/2017:20:10:04 +0000] "POST /v1/replicas/1?action=setrebuilding HTTP/1.1" 200 1766
```

```
time="2017-12-06T20:25:35Z" level=info msg="Accepting ..." 
time="2017-12-06T20:25:35Z" level=info msg="connection is connected from 10.2.81.1:48794...\n" 
time="2017-12-06T20:25:35Z" level=info msg="Listening ..." 
time="2017-12-06T20:25:35Z" level=warning msg="unexpected connection state: 8" 
time="2017-12-06T20:25:35Z" level=error msg=EOF 
time="2017-12-06T20:25:35Z" level=info msg="10.2.81.2:3260" 
time="2017-12-06T20:25:35Z" level=info msg="Accepting ..." 
time="2017-12-06T20:25:35Z" level=info msg="connection is connected from 10.2.81.1:48796...\n" 
time="2017-12-06T20:25:35Z" level=info msg="Listening ..." 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:35Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-06T20:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="10.2.81.2:3260" 
time="2017-12-07T08:24:40Z" level=info msg="Accepting ..." 
time="2017-12-07T08:24:40Z" level=info msg="connection is connected from 10.2.3.0:53296...\n" 
time="2017-12-07T08:24:40Z" level=info msg="Listening ..." 
time="2017-12-07T08:24:40Z" level=warning msg="unexpected connection state: 8" 
time="2017-12-07T08:24:40Z" level=error msg=EOF 
time="2017-12-07T08:24:40Z" level=info msg="10.2.81.2:3260" 
time="2017-12-07T08:24:40Z" level=info msg="Accepting ..." 
time="2017-12-07T08:24:40Z" level=info msg="connection is connected from 10.2.3.0:53298...\n" 
time="2017-12-07T08:24:40Z" level=info msg="Listening ..." 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:40Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:41Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:41Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:41Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:24:54Z" level=error msg=EOF 
time="2017-12-07T08:25:37Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:25:38Z" level=info msg="Service Action: report one no service action" 
time="2017-12-07T08:25:38Z" level=info msg="Service Action: report one no service action" 
```

**Comment by ksatchit** [comment]
Hi @AndreasBomholtz , thanks for trying OpenEBS !!  Can you help us with the following questions : 

- What is the application/workload you are using the OpenEBS PVC for ? If it is okay, can you share the pod/deployment spec ? 

- The controller/replica (openebs PVC pods) logs show a slightly old time-stamp - is the application pod in the same state ? Output of ```kubectl get pods``` & ```kubectl describe pods``` for the application & pvc pods can be helpful too 

- The OpenEBS PVC ctrl pod shows iSCSI login requests from two different IPs - was the application pod rescheduled/restarted - or did any node failures etc., occur ?

**Comment by payes** [comment]
Hi @AndreasBomholtz , thanks for the logs.
Logs at the controller show that it was unable to reach one of the replicas(10.2.81.12), because of which the volume was turned into read-only.

> time="2017-12-04T11:20:41Z" level=error msg="Write timeout on replica 10.2.81.12:9503 seq= 1259055 size= 44 (kB)" 
time="2017-12-04T11:20:41Z" level=error msg="Retry  1 on replica 10.2.81.12:9503 seq= 1259055 size= 44 (kB)" 
time="2017-12-04T11:20:46Z" level=error msg="Ping timeout on replica 10.2.81.12:9503 seq= 1259054" 
time="2017-12-04T11:20:46Z" level=error msg="Retry  1 on replica 10.2.81.12:9503 seq= 1259054 size= 0 (kB)"

To maintain quorum, we have a policy of making the volume as read-only if the online replica count becomes <=50% of the total number of replicas registered.

**Comment by AndreasBomholtz** [comment]
Should I change the replicas to minimum 3 to make better to handle network issues?
Thank you for helping me find an solution to this problem.

**Comment by ksatchit** [comment]
@AndreasBomholtz , I would suggest doing an fsck on the ```/dev/sd*``` device on the host to get the application pod back up running. Also, not sure doing the e2fsck on the sparse file (*.img) is recommended , @payes ? 

In case of a flaky network situation, it might actually be a good idea to have more than 2 replicas, but that would necessitate more nodes as well - the openebs volume replicas are designed to be scheduled on separate nodes in the interest of HA. 

Also, just as an aside, you could consider moving to the latest release (0.5) too.

**Comment by AndreasBomholtz** [comment]
@ksatchit will changing the replicas label in storageclass change the replicas for existing pvs or do I have to recreate them?
Also can I just upgrade to the new version without having to do anything? 
I'm still trying to get the fschk to work...

**Comment by AndreasBomholtz** [comment]
@ksatchit I have tried to run fsck but it could not check it because it is mounted. So I unmount it and then I could run fsck. It didn't find any errors. So I mounted it again as rw, but hen i tried to start the pod it failed and it is mounted as ro again.
Do you need some new logs?

**Comment by payes** [comment]
I think if there are no errors found by fsck and you are able to mount the filesystem as read-only filesystem the data is in good health. We can also try to logout of iscsi session from node and the relogin back. If even then we get it as a RO filesystem, implies the 2nd replica is again not reachable from controller. We can also check if there are packet drops. Because the logs showed that the pings from controller didn't reach the replica but a close http request reached after few sec.

Replica not reachable from controller till 2017-12-04T11:21:41
>time="2017-12-04T11:21:26Z" level=error msg="Ping timeout on replica 10.2.81.12:9503 seq= 1259063"
>time="2017-12-04T11:21:41Z" level=error msg="Write timeout on replica 10.2.81.12:9503 seq= 1259072 size= 44 (kB)"

A REST command reaches replica from controller at 04/Dec/2017:11:21:46
>10.2.3.0 - - [04/Dec/2017:11:21:46 +0000] "POST /v1/replicas/1?action=close HTTP/1.1" 200 954

If controller(ctrl-log) has logs similar to:
>time="2017-12-04T11:20:46Z" level=error msg="Ping timeout on replica 10.2.81.12:9503 seq= 1259054"

and

>time="2017-12-13T12:37:31Z" level=error msg="Mode: ReadOnly"


Implies the replica is again not reachable. Ideally, as soon as the connection between controller and replica can be established, the replica automatically registers itself at the controller and the volume becomes writable. There looks to be a bug in reconnection code when there is a packet drop.

To get out of this situation, current solution is to restart the controllers and replicas, and then restart the application pod.

As you have described above that this process has already been done, just make sure the packet drops are not there. We will be testing and fixing the scenarios for packet drops.

@ksatchit , Yes, it is not a good idea to do fsck on the backend files.

**Comment by AndreasBomholtz** [comment]
@payes It worked to restart the controllers and replicas. Now my pod can start again. 
I will recreate all my PVC to use a storageClass that has 3 replicas. 
Are there any danger in upgrading to 0.5.0?

**Comment by ksatchit** [comment]
@AndreasBomholtz , you can scale the replicas even without re-applying the storage classes and recreating the PVC (in case you need to maintain the data). Here are the steps : 

- Step-1 : Identify the replica deployment 

```karthik@MayaMaster:~$ kubectl get deploy
NAME                                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
maya-apiserver                                  1         1         1            1           1h
openebs-provisioner                             1         1         1            1           1h
percona                                         1         1         1            1           1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-ctrl   1         1         1            1           1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep    2         2         2            2           1h
```
- Step-2 : Scale the replicas to desired count

```
karthik@MayaMaster:~$ kubectl scale --current-replicas=2 --replicas=3 deployment/pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep
deployment "pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep" scaled
```

- Step-3 : Confirm that the desired number of replicas are running (may take a few sec for the new replica pod to initialize)

```
karthik@MayaMaster:~$ kubectl get deploy
NAME                                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
maya-apiserver                                  1         1         1            1           1h
openebs-provisioner                             1         1         1            1           1h
percona                                         1         1         1            1           1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-ctrl   1         1         1            1           1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep    3         3         3            3           1h
karthik@MayaMaster:~$
```

```
karthik@MayaMaster:~$ kubectl get pods
NAME                                                           READY     STATUS    RESTARTS   AGE
maya-apiserver-3416621614-bm9sp                                1/1       Running   0          1h
openebs-provisioner-4230626287-xx9t4                           1/1       Running   0          1h
percona-2503451898-thcsd                                       1/1       Running   0          1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-ctrl-35451586-8z403   1/1       Running   0          1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep-781620503-3kwgb   1/1       Running   0          2m
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep-781620503-53wv4   1/1       Running   0          1h
pvc-1ca6e4d6-e18e-11e7-8f29-000c298ff5fc-rep-781620503-749p9   1/1       Running   0          1h
```

**Comment by AndreasBomholtz** [comment]
@ksatchit Thanks, that worked just flawless. Can I also enable the monitoring without re-creating?

**Comment by ksatchit** [comment]
@AndreasBomholtz , monitoring is available as a feature in the 0.5 release. With this release, there are some manual (kubectl) steps involved in upgrade (we are working on making the upgrades seamless in future releases). We could help you with that on our slack channel, if you would like ! 

Another option is to upgrade the control plane (openebs-operator & storage-classes) and create new volumes enabled with monitoring. This should not affect existing pods.

**Comment by AndreasBomholtz** [comment]
I have joined Slack and I'm looking forward for a little help about how I should go about updating the pods...

**Comment by ksatchit** [comment]
The update procedure from 0.4 to 0.5 is available here : https://github.com/openebs/openebs/tree/master/k8s/upgrades

The main cause of this  situation, i,e, volume getting into RO state is something that is being tracked in #1260 , and the steps to overcome in #1236 

Therefore, closing this issue.
