### ISSUE TITLE
Serverless Architecture

### ISSUE THREAD

**Issue by Apollo9999** [openebs/openebs#1022]
Serverless architectures refer to applications that significantly depend on third-party services (knows as Backend as a Service or “BaaS”) or on custom code that’s run in ephemeral containers (Function as a Service or “FaaS”), the best known vendor host of which currently is AWS Lambda.

Despite the name, it does not actually involve running code without servers. The name “serverless computing” is used because the business or person that owns the system does not have to purchase, rent or provision servers or virtual machines for the back-end code to run on.

Serverless code can be used in conjunction with code written in traditional server style, such as microservices. For example, part of a web application could be written as microservices and another part could be written as serverless code. Alternatively, an application could be written that uses no provisioned servers at all, being completely serverless.

FaaS provides a platform allowing the developers to execute code in response to events without the complexity of building and maintaining the infrastructure. The 3rd party apps or services would manage the server-side logic and state.

four patterns that the Serverless Framework embraces perfectly:

1. Microservices Pattern

2. Services Pattern

3. Monolithic Pattern

4. Graph Pattern

Let’s explore how we can build our Serverless Social Network using each one of these patterns, while outlining the benefits and drawbacks of each along with the configuration required for each pattern.

1. Microservices Pattern
In the Microservices Pattern each job or functionality is isolated within a separate Lambda function. In the case of our example app, each Lambda function would also have a single http endpoint that serves as the entry point for that function.

service: serverless-social-network
provider: aws
functions:
  usersCreate:
    handler: handlers.usersCreate
    events:
      - http: post users/create
  commentsCreate:
    handler: handlers.commentsCreate
    events:
      - http: post comments/create
Benefits of Microservices Pattern:
Total separation of concerns. Each job/operation is in a separate unit of deployment (i.e., a separate Lambda function), allowing you to modify your application’s components individually, without affecting the system as a whole. This is a very agile and safe pattern, especially in production.
Each Lambda function handles a single event making your functions easy to debug, since there is usually only one expected outcome.
This separation of concerns is also great for autonomous teams. They can push functionality into production independently.
Drawbacks of Microservices Pattern:

You will end up with a lot of functions, which is harder to manage and can result in a lot of cognitive overhead. Lambda functions tend to be more granular than traditional microservices, so be ready for a lot of them!
Performance could be slower. When functions handle a single job, they are called less, resulting in more cold starts.
Deployments will be slower, since multiple functions have to be provisioned.
You could reach the CloudFormation template file size limit quickly, especially if you’re using custom resources.

2. Services Pattern
In the Services Pattern, a single Lambda function can handle a few (~4) jobs that are usually related via a data model or a shared infrastructure dependency. In our example app, all operations on the Users data model are performed in a single Lambda function, and multiple HTTP endpoints are created for all CRUD operations.

service: serverless-social-network
provider: aws
functions:
  users:
    handler: handler.users
      events:
        - http: post users
        - http: put users
        - http: get users
        - http: delete users
  comments:
    handler: handler.comments
      events:
        - http: post comments
        - http: put comments
        - http: get comments
        - http: delete comments
You can inspect the incoming HTTP request’s path and method by parsing the event body in your code, and then perform the correct operation in response. It’s like having a small router in the beginning of your Lambda code.

Benefits of Services Pattern:

This will result in less Lambda functions that you need to manage.
Some separation of concerns still exists.
Teams can still work autonomously.
Faster deployments.
Theoretically better performance. When multiple jobs are within a Lambda function, there is a higher likelihood that Lambda function will be called more regularly, which means the Lambda will stay warm and users will run into less cold-starts.
Drawbacks of Services Pattern:

Debugging gets slightly more complicated, since the Lambda function is handling multiple jobs, and has different outcomes.
Requires creating a router to call the right logic based on the request method or endpoint.
Bigger function sizes due to putting multiple operations within the same Lambda function.
3. Monolithic Pattern
In the Monolithic Pattern your entire application is crammed into a single Lambda function. In our example app, our entire app is in a single Lambda function, all HTTP endpoints point to that Lambda function.

service: serverless-social-network
provider: aws
functions:
  socialNetwork:
    handler: handler.socialNetwork
      events:
        - http: post users
        - http: put users
        - http: get users
        - http: delete users
        - http: post comments
        - http: put comments
        - http: get comments
        - http: delete comments
Benefits of the Monolithic Pattern:
A single Lambda function is much easier to comprehend and manage. It’s more of a traditional set-up.
Fast deployments, depending on the total code size.
Theoretically faster performance. Your single Lambda function will be called frequently and it is less likely that your users will run into cold-starts.
Drawbacks of the Monolithic Pattern:
Requires building a more complex router within your Lambda function and ensuring it always directs calls the appropriate logic.
It’s harder to understand performance. The Lambda function will run for a variety of durations.
You can easily hit the Lambda size limit in real world practical applications due to the larger function size.

4. The Graph Pattern
The Graph Pattern is similar to the Monolithic Pattern, but it allows you to take advantage of GraphQL to reduce your entire REST API and all of its endpoints into 1–2 endpoints. As a result, your entire application will be composed of a single function and a 1–2 endpoints that handle GraphQL queries. GraphQL will then fetch the correct data in any form you need.

service: serverless-social-network
provider: aws
functions:
  socialNetwork:
    handler: handler.socialNetwork
      events:
        - http: get query
Benefits of the Graph Pattern:
Very easy to manage with a single Lambda function and a single endpoint for the entire application.
Theoretically faster performance. Your single Lambda function will be called frequently and it is less likely that your users will run into cold-starts.
Blazing fast to deploy since you only have a single function and a single endpoint
A pay-per-execution, zero-administration, Graph API!!! It doesn’t get more efficient than that!
Drawbacks of the Graph Pattern:

we can easily hit the Lambda size limit in real world practical applications due to the massive function size.
have to learn GraphQL.

**Comment by Apollo9999** [comment]
- [ ] # #

**Comment by Apollo9999** [comment]
please make this issue to be pull request for Hackathon of openebs

**Comment by AmitKumarDas** [comment]
@Apollo9999 What is this all about?
