### ISSUE TITLE
Create an Ansible project for automating Continuous Integration.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#104]
This issue will track the feature implementation of automating CI using Ansible.

**Comment by ksatchit** [comment]
The basic ansible based e2e framework for now available at :  https://github.com/openebs/openebs/tree/master/e2e

A brief description and contributing guidelines are here: https://github.com/openebs/openebs/blob/master/contribute/CONTRIBUTING-TO-CI-AND-E2E.md
