### ISSUE TITLE
Support openebs PV to use different networks for traffic isolation

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1042]
FEATURE REQUEST

OpenEBS PVs comprise of controller and replica pods. The controller pod exposes the storage to the stateful pods like (databases, content stores etc.,) and saves the data by synchronously replicating them to replica pods. It will be good to isolate the traffic on the controller pods based on -- application and backend, with each kind of traffic possibly going through different network interfaces. 

To this effect, the controller pod needs to be configured with multiple pod IPs, which is not yet supported by kubernetes. However the following are some related threads that were provided in the kubernetes slack #sig-networking

- https://github.com/kubernetes/kubernetes/issues/27398#issuecomment-350969948
- https://github.com/Huawei-PaaS/CNI-Genie
- https://github.com/Intel-Corp/multus-cni
- https://groups.google.com/forum/#!topic/kubernetes-sig-network/ANAjTyqVosw

**Comment by gila** [comment]
Looking at this: https://ligato.github.io might which matches other plans/thinking we currently have.

**Comment by kmova** [comment]
Some more links related to intel - multus:
- https://networkbuilders.intel.com/network-technologies/container-experience-kits
- https://builders.intel.com/docs/networkbuilders/multiple-network-interfaces-support-in-kubernetes-feature-brief.pdf
- https://builders.intel.com/docs/networkbuilders/multiple-network-interfaces-in-kubernetes-application-note.pdf
