### ISSUE TITLE
openebs provisioner - support for adding block volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1045]
FEATURE REQUEST

Kubernetes 1.9 now supports attaching block devices to pods. This is issue is raised to support adding OpenEBS PVs as block devices to pods. 

Refer:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

Notes:
This may be tied into required block mode support for iscsi pv.

**Comment by kmova** [comment]
The support for this will depend on https://github.com/kubernetes/kubernetes/pull/54752

**Comment by kmova** [comment]
The change will be required in the provisioner code when creating the PV object at https://github.com/openebs/external-storage/blob/release/openebs/pkg/provisioner/cas_provision.go#L139

**Comment by vijayscsa** [comment]
Tested

**Comment by kmova** [comment]
Fixed in 0.7.1 via https://github.com/openebs/external-storage/pull/78
