### ISSUE TITLE
Add Snaphsot feature for OpenEBS in K8s snapshot API

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#1046]
FEATURE REQUEST

**Create:**
1. The user creates a VolumeSnapshot referencing a persistent volume claim bound to a persistent   volume          
2. The controller fulfils the VolumeSnapshot by creating a snapshot using the volume plugins.
3.  A new object `VolumeSnapshotData` is created to represent the actual snapshot binding the
`VolumeSnapshot` with the on-disk snapshot.

**List:**
1. The user is able to list all the `VolumeSnapshot` objects in the namespace

**Delete:**
1. The user deletes the `VolumeSnapshot`
2. The controller removes the on-disk snapshot. Note: snapshots have no notion of "reclaim policy" -       there is no way to recover the deleted snapshot.
3. The controller removes the `VolumeSnapshotData`object.

**Promote snapshot to PV:**
1. The user creates a persistent volume claim referencing the snapshot object in the annotation. The  PVC must belong to a `StorageClass` using the external volume snapshot provisioner. Note: the special annotation might get replaced by a dedicated attribute of the `PersistentVolumeClaim` in the future.
2. The provisioner will use the `VolumeSnapshotData` object to create a persistent volume using the   corresponding volume snapshot plugin.
3. The PVC is bound to the newly created PV containing the data from the snapshot.

**Comment by kmova** [comment]
Create, List and Delete API are supported with https://github.com/openebs/external-storage/pull/27

For implementing promotion of snapshot to PV, the following needs to be fixed:
https://github.com/openebs/openebs/issues/440
