### ISSUE TITLE
Merge namespace aware changes to maya:master

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1066]
## Why is this required?
- There were some namespace aware changes checked-in to maya:v0.5.1
- These changes needs to be merged into maya:master
- There are some merge conflicts that needs to be resolved
Refer - https://github.com/openebs/maya/pull/235

**Comment by dungeonmaster18** [comment]
Hey @AmitKumarDas I have fixed the merge conflicts for this issue but I guess I don't have permission to push to that branch.

**Comment by AmitKumarDas** [comment]
Thanks @dungeonmaster18 You can send a PR?

**Comment by kmova** [comment]
@dungeonmaster18 -- you can raise a new PR with the fixed changes. I will close this PR and accept the new one with the changes. Thanks for helping out!

**Comment by dungeonmaster18** [comment]
Yup I figured that out later. I will be creating the pr soon...

**Comment by AmitKumarDas** [comment]
@dungeonmaster18 @kmova @prateekpandey14 I guess this has been merged to maya:master
Probably we should close this!!

**Comment by dungeonmaster18** [comment]
Yes AmitKumarDas this has been fixed and merged by openebs/maya/pull#244
