### ISSUE TITLE
Change design to single workqueue on nodebot

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1070]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
Rate limiting workqueues were separate for created, updated, deleted events in spc crd watcher and only the spc resource name was sent on the queue.

**What you expected to happen**:
A single workqueue needs to be defined for all the events and at the same time need to pass the event type on the queue as well

**Comment by kmova** [comment]
This scenario need to be covered by node-disk-manager (https://github.com/openebs/node-disk-manager/pulls/1)
