### ISSUE TITLE
Replace GetHostName with go built-in tool in nodebot

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1078]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
While creating sp object, the GetHostName used uname tools and it is executed to retrieve the node name.

**What you expected to happen**:
The above mentioned step has more time complexity and os dependency. This needs to be replaced with golang built-in tool to get node name

**Comment by kmova** [comment]
Use the label kubernetes.io/hostname assigned to the node. 
https://github.com/openebs/node-disk-manager/pull/1
