### ISSUE TITLE
Implement IsDiskBeingUsed and IsDiskUnusedMounted - nodebot

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1079]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
If a disk is being used it may be deleted when delete crd event occurs.

**What you expected to happen**:
Corner case scenarios like avoid removing disks if being used or if disk is unused and mounted need to be handled.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl delete spc resource -> if disk in resource is being used, it should not delete.

**Comment by kmova** [comment]
Related to : https://github.com/openebs/node-disk-manager/pull/1

**Comment by akhilerm** [comment]
Disk/BlockDevice used status is now available via the claim state in BlockDevice resource. Also the blockdevice has a filesystem and mountpoint field which can be used to check if the device is mounted or not.
