### ISSUE TITLE
maya-nodebot daemonset yaml creation

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#1080]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
 maya-nodebot runs on every node and it supports only cli now.

**What you expected to happen**:
maya-nodebot should run as daemonset in all nodes of kubernetes with incluster config settings.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get ds should list maya-nodebot

**Comment by kmova** [comment]
This has been deprecated. node-disk-manager will cover this.
