### ISSUE TITLE
Option to manually launch a OpenEBS PV using an existing data directory. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1090]
FEATURE REQUEST

In case of disaster recovery scenarios, like all the nodes were shut down in cluster, it may be useful to launch OpenEBS volumes from a previously backed up data directory.

**Comment by Yaxian** [comment]
Dear, @kmova ,
Unfortunately, I met this problem. 
After  I run `kubeadm reset`,  I lost my openebs's deployment, pv and pvc. But I have some <pvc-name> folders in disk.
And I had googled some docs about recovering data from <pvc-name>. But They could not help me.
Could you help me about **how to manually launch a OpenEBS PV using an existing data directory**

**Comment by kmova** [comment]
@Yaxian - I apologize for the very late response. I used the following steps to launch a OpenEBS PV using an existing directory: https://github.com/kmova/bootstrap/tree/master/gke-openebs/jiva-recovery

**Comment by Yaxian** [comment]
@kmova Look great to me，Thank you very much！
