### ISSUE TITLE
Automate the installation of the openebs master and host installation along side k8s

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#11]
Developer should be able to bring up a setup with K8s and OpenEBS with a single vagrant file. Enhance the current k8s demo setup to include OpenEBS master and host.

**Comment by kmova** [comment]
@yudaykiran Thanks for resolving this via the pull request.

**Comment by akashshah26595** [comment]
Tried Vagrant up, to setup k8s cluster. Received the following **error**.

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
"
