### ISSUE TITLE
Create document for K8s on CentOS for GCE

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#1103]
Choose one:  FEATURE REQUEST

**What happened**: New feature to document the steps for K8s CentOS for GCE installation

**What you expected to happen**: steps to be documented to install k8s on CentOS

**Comment by vipulgupta2048** [comment]
@kmova I'll be taking this up. I have some experience with CentOs. I am looking to go for a little distro-hopping and documentation clean-up along the way. 
Do clarify what GCE is?

**Comment by kmova** [comment]
The intent here is to get a Kubernetes Cluster up and running on Google Cloud Platform (GCP) using Cent OS Google Compute Engine (GCE) instances. After K8s is running, install OpenEBS via helm and demonstrate launching one of the Stateful Pods.

**Comment by vipulgupta2048** [comment]
That's a mouthful to be very honest, I will be referring to a lot of googling and the documentation that I just fixed to see how to accomplish the above sentence. Will report back on it.
