### ISSUE TITLE
Support a sanity checker

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1106]
FEATURE REQUEST

This came up in the openebs-users slack channel, where there was a mis-configuration that went undetected. This issue is raised to track the development of a sanity checker that should detect such cases. the sanity checker should be extensible for users to add their own sanity checks and something that they could run before leaving the system to run by its own. -- this sanity checker is in addition to the alerts/monitoring modules that really work if everything was configured properly..

**Comment by AmitKumarDas** [comment]
@kmova Have a look at https://github.com/heptio/sonobuoy

**Comment by gila** [comment]
That first one looks pretty nice! Nothing is easy but perhaps we can extend it!

**Comment by AmitKumarDas** [comment]
@kmova @ksatchit Have a look at this https://github.com/openebs/openebs/issues/1216
