### ISSUE TITLE
Add a dashboard to show health status of OpenEBS volumes

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#1111]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST
As now we have already covered some of the aspects of monitoring, the need of health check is arising to see whether status of volume is good. Some microservices that decide the OpenEBS health can be :  
* maya-apiserver is up and running
* openebes-provisioner is up and running
* Desired no of replicas scheduled

Steps to follow : 
Just follow the steps given [here](https://github.com/openebs/openebs/tree/master/k8s/openebs-monitoring) and then go ahead with the following
* You can see the available pods in the target of prometheus's UI
* Check whether maya-apiserver pods/services are running
* Check whether openebs-provisioner pods/services are running
* Check whether jiva-replica pods/services are running

So you have to create a dashboard based on the PromQl and this dashboard contains the graph of the above three components.

**Comment by mhemrg** [comment]
I really like this. How can one help to start adding this feature?

**Comment by AmitKumarDas** [comment]
@utkarshmani1997 can openebs have this feature   as a mayactl and then over to Prometheus and UI. Can you provide some possible steps to help @mhemrg

**Comment by utkarshmani1997** [comment]
@mhemrg thanks for showing your interest into this issue, i have updated the issue with the steps to follow. Do let me know if you need any assistance. 
@AmitKumarDas yes we can have this feature as a mayactl.

Do join us [here](http://slack.openebs.io/) on slack for more queries.

**Comment by mhemrg** [comment]
@utkarshmani1997 I'm hoping you can assist me to start doing that. I have joined the channel.

**Comment by till** [comment]
@mhemrg @utkarshmani1997 Did this effort go anywhere? I am interested in this as well.

**Comment by utkarshmani1997** [comment]
Hi @till thanks for showing interest. This issue is still open for grab.

**Comment by muratkars** [comment]
As an alternative, would using Weave Scope to check volume health status work? You can visualize volume and replica health through Scope.
