### ISSUE TITLE
Support Docker Swarm

### ISSUE THREAD

**Issue by mhemrg** [openebs/openebs#1117]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: FEATURE REQUEST

Docker Swarm is an embedded orchestration solution and it's easy to use. I think OpenEBS should support it as a volume plugin.

**Comment by olivibernard** [comment]
I am looking for a solution like OpenEBS running on Docker Swarm ! 
+1

**Comment by zicklag** [comment]
I ***really, really*** want this for Docker Swarm. :grinning:

**Comment by port22** [comment]
Since there are so much problems with Rexray, I was looking for a decent alternative for AWS EBS volumes on Docker Swarm. So, I second this Feature Request.

**Comment by AmitKumarDas** [comment]
@port22 will it be possible to collaborate here. Current team has no bandwidth to look at Docker Swarm.

**Comment by port22** [comment]
@AmitKumarDas Oh I'm not that good in writing code, let alone to write a storage driver. If you mean that...

**Comment by naviat** [comment]
Any update from OpenEBS for this?

**Comment by jaschaio** [comment]
Any update on this? Looks like [rexray is no longer actively maintained](https://github.com/rexray/rexray/issues/1338).

**Comment by saulmmendoza** [comment]
any documentation I can read about how to code an implementation of openEBS within docker swarm?
