### ISSUE TITLE
DEFAULT_REPLICA_COUNT environment variable doesn't work anymore

### ISSUE THREAD

**Issue by mhemrg** [openebs/openebs#1118]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT

**What happened**:
I see there are 2 replicas.

**What you expected to happen**:
I expected to see 1 replica when I set `DEFAULT_REPLICA_COUNT` to `1`.

**How to reproduce it (as minimally and precisely as possible)**:
Just update `openebs-operator.yaml` as docs says:
>Note By default, OpenEBS launches OpenEBS Volumes with two replicas. To set one replica, as is the case with single-node Kubernetes cluster, specify the environment variable DEFAULT_REPLICA_COUNT=1. This is supported in OpenEBS version 0.4 onwards.

**Anything else we need to know?**:
There is another environment variable called `OPENEBS_IO_JIVA_REPLICA_COUNT`. You should use it instead of `DEFAULT_REPLICA_COUNT`. I think we should update the docs.

**Comment by utkarshmani1997** [comment]
@mhemrg thanks for pointing out that issue, we are working on it. can you please go ahead and raise a PR for that.
