### ISSUE TITLE
Document steps to setup OpenEBS on Containerized OpenShift cluster 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1134]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

The Containerized cluster is a popular deployment model for OpenShift, with all the platform services run as containers instead of RPMs on the master and host nodes. We need to document the steps to
create the above cluster and setup OpenEBS with sample applications on it. 

https://docs.openshift.com/container-platform/3.3/install_config/install/advanced_install.html

**Comment by mahebbar** [comment]
The steps are available at https://docs.openebs.io/docs/next/openshift.html

**Comment by ksatchit** [comment]
Re-opening this issue as the referenced steps are for baremetal service-based/package install of openshift. There may be minor changes/additions in case of containerized openshift clusters. This still needs dev docs - which is what the issue intends to track.
