### ISSUE TITLE
VSM is created in a degraded openebs-cluster (with single replica)

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#114]
The VSM was seen to get created successfully (in this case issued via the k8s flexvol plugin-openebs-iscsi driver) even when the osh-cluster was in a degraded mode , i.e., one of the hosts was powered off. 

While this is desirable in some ways (storage must be provision-able even with a single replica) , the behaviour needs to examined with regard to current logic /expectation

**Comment by kmova** [comment]
while the initial issue was raised against dedicated mode with flex-volume plugin, the same holds true for the hyper-converged as well. As of today, there are no restrictions on creating a volume - even when there is only one replica can be scheduled.
