### ISSUE TITLE
ImagePullPolicy should be different in local deployments

### ISSUE THREAD

**Issue by mhemrg** [openebs/openebs#1143]
## Is this a BUG REPORT or FEATURE REQUEST?
 
I really don't know! Just an opinion.

**What happened**:
When I turn on my computer, Kubernetes tries to start the pods. It seems OpenEBS monitoring stack needs to pull the images again because the `imagePullPolicy` has been set to `Always`.

**What you expected to happen**:
I expected to see the pods have been started without the need to pull the images again.

**How to reproduce it (as minimally and precisely as possible)**:
Just set up Minikube and then restart your machine.

**Anything else we need to know?**:
I think we should mention that in the docs for local installations.

**Comment by AmitKumarDas** [comment]
@mhemrg Do you think production should set it as `download if not available` whereas local should set it as `Always`? I felt local implies testing & hence these settings.

In addition, you have made a good point to have this as a volume policy.
