### ISSUE TITLE
Document steps to run OpenEBS on RancherOS-based Kubernetes cluster

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#1146]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
Document steps to run OpenEBS on RancherOS-based Kubernetes cluster.

**What you expected to happen**:
A user must be able to follow the steps provided in the document and easily setup openebs on RancherOS based Kubernetes cluster.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by sourabh1031** [comment]
Hello i would like to work on this issue.Can you please provide little more explanation that what is expected from me like which file i need to track and what i should do

**Comment by yudaykiran** [comment]
@sourabh1031 , The intention is get a Kubernetes Cluster up and running on Rancher OS and deploy OpenEBS on that cluster. Verify that OpenEBS is properly deployed and document the steps followed to achieve the same. It could initially start of with raising a PR for a README.md file containing the steps.

**Comment by muratkars** [comment]
We will update the instructions to address [RancherOS not persisting user volume](https://github.com/rancher/os/issues/2188). 
New instructions will be available [here](https://docs.openebs.io/prerequisites.html#rancher)

In the meantime here are the steps to run OpenEBS on RancherOS.
1) Install rancheros
2) Install open-iscsi support
  - `ros s enable open-iscsi`
  - `ros s up open-iscsi`
       - These two commands will basically bring iscsi binaries + kernel modules to the host, but on a separate system container, as everything runs in containers on RancherOS
3) Add default OpenEBS volumes as user-volumes. An example below:      
`ros config set rancher.services.user-volumes.volumes  [/home:/home,/opt:/opt,/var/lib/kubelet:/var/lib/kubelet,/etc/kubernetes:/etc/kubernetes,/var/openebs]`

4) `system-docker rm all-volumes`
5) Reboot
6) Install OpenEBS (+ SPC's, SC's, you know the job)
7) Create your PVC and your container!

**Comment by ranjithwingrider** [comment]
Added the information in docs. https://docs.openebs.io/docs/next/prerequisites.html#rancher

**Comment by travisghansen** [comment]
https://github.com/rancher/rke/issues/1846
