### ISSUE TITLE
maya omm-status command places the " m-apiserver listening at <http://ip:port>" output line in STDERR instead of STDOUT

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#115]
An ansible playbook command to print details of maya installation, when run with verbose logging showed the following : 

changed: [localhost -> None] => {
    "changed": true,
    "cmd": "source ~/.profile; maya omm-status",
    "delta": "0:00:00.033736",
    "end": "2017-05-29 11:53:07.946624",
    "invocation": {
        "module_args": {
            "_raw_params": "source ~/.profile; maya omm-status",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2017-05-29 11:53:07.912888",
    "stderr": "mesg: ttyname failed: Inappropriate ioctl for device\n\nm-apiserver listening at http://20.10.49.11:5656",
    "stderr_lines": [
        "mesg: ttyname failed: Inappropriate ioctl for device",
        "",
        "**m-apiserver listening at http://20.10.49.11:5656**"
    ],
    "stdout": "Name               Address      Port  Status  Leader  Protocol  Build  Datacenter  Region\nMayaMaster.global  20.10.49.11  4648  alive   true    2         0.5.5  dc1         global",
    "stdout_lines": [
        "Name               Address      Port  Status  Leader  Protocol  Build  Datacenter  Region",
        "MayaMaster.global  20.10.49.11  4648  alive   true    2         0.5.5  dc1         global"
    ]
}

Ideally, this should also be part of stdout

**Comment by prateekpandey14** [comment]
This was the part of checking the return status code but inside the Error print statement.
Now changed to 'Sprintf' which will be stdout result for the status command.

**Comment by kmova** [comment]
This code has been deprecated.
