### ISSUE TITLE
Testing Jenkins Usecase Documentation 

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1155]
Choose one: TESTING

What happened: Documentation requires testing for 0.5.1

What you expected to happen: Check if the procedures are working as expected

**Comment by ksatchit** [comment]
The jenkins setup with openebs PV described here : https://github.com/openebs/openebs/blob/master/k8s/demo/jenkins/README.md is seen to work with OpenEBS version 0.5.1 (verified by CI)
