### ISSUE TITLE
Testing CockroachDB Usecase Documentation

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1156]
Choose one: TESTING

What happened: Documentation requires testing for 0.5.1

What you expected to happen: Check if the procedures are working as expected

**Comment by ksatchit** [comment]
The cockroachDB setup with OpenEBS PV described here https://github.com/openebs/openebs/tree/master/k8s/demo/cockroachDB has been tested with OpenEBS vers. 0.5.1
