### ISSUE TITLE
Volume creation procedure (via maya cli) doesn't check whether name exists 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#117]
The volume creation procedure via "maya vsm-create -name <> -size <>" doesn't check whether there is a volume with same name/properties. The existing fe & be containers are destroyed and replaced by a new set of fe/be for the current instance 

We need to have this check, either at Maya or m-api server

<Executed on OSH before creation of volume with same name as current>

root@MayaHost01:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                    
e50ca63765ee        openebs/jiva:latest    "launch controller..."   30 minutes ago      Up 30 minutes             
62dd5a5a5895        openebs/jiva:latest    "launch replica --..."   30 minutes ago      Up 30 minutes             
70d36c9aad1c        openebs/jiva:latest    "launch replica --..."   31 minutes ago      Up 31 minutes             
                            
<Executed on OSH after creation of volume with same name as current>

root@MayaHost01:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                    
43ea531e3a71        openebs/jiva:latest    "launch controller..."   2 minutes ago       Up 2 minutes              
581ad68c3ef4        openebs/jiva:latest    "launch replica --..."   2 minutes ago       Up 2 minutes              
62dd5a5a5895        openebs/jiva:latest    "launch replica --..."   34 minutes ago      Up 34 minutes

**Comment by kmova** [comment]
Verify if the same issue is present on the latest version of mayactl with : maya volume create option.

**Comment by ashishranjan738** [comment]
@kmova I want to work on this issue . Can you give me more details how to achieve this ?
