### ISSUE TITLE
maya vsm-stop doesn't stop all containers associated with volume

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#118]
Volume deletion (?) via the maya vsm-stop command doesn't clean up (Stop) all containers associated with the volume, i.e., front-end controller & back-end replicas. There is always some residual containers running (mostly _be_ containers. In the 'docker ps -a' snippet below, for the volume 'demo-vsm1-vol1', the be0 replica is still running & for the volume 'volume', the be1 is still running )

Expected: Ideally, all containers should be stopped

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      NAMES
43ea531e3a71        openebs/jiva:latest      "launch controller..."   About an hour ago   Exited (1) 19 seconds ago   volume-fe0
581ad68c3ef4        openebs/jiva:latest      "launch replica --..."   About an hour ago   Exited (2) 23 seconds ago   volume-be0
62dd5a5a5895        openebs/jiva:latest      "launch replica --..."   2 hours ago         Up 2 hours                  volume-be1
20cba0ab42da        openebs/jiva:latest      "launch controller..."   24 hours ago        Exited (1) 22 hours ago     demo-vsm1-vol1-fe0
bca1075a9670        openebs/jiva:latest      "launch replica --..."   24 hours ago        Exited (2) 22 hours ago     demo-vsm1-vol1-be1
1678b6e56087        openebs/jiva:latest      "launch replica --..."   25 hours ago        Up 25 hours                 demo-vsm1-vol1-be0

**Comment by kmova** [comment]
This code has been deprecated. And with the latest changes which includes using Kubernetes, the volume delete, clears all the required objects.
