### ISSUE TITLE
Add support for dedicated storage node deployment

### ISSUE THREAD

**Issue by alwinmark** [openebs/openebs#1193]
## Is this a BUG REPORT or FEATURE REQUEST?
 
  BUG REPORT

**What happened**:

After replacing/restarting a container I get this error:

```
MountVolume.SetUp failed for volume "openebs/openebs-iscsi/ecfa0c08-076a-11e8-a490-02c35d847e20-demo-vsm1-vol1" (spec.Name: "de
mo-vsm1-vol1") pod "ecfa0c08-076a-11e8-a490-02c35d847e20" (UID: "ecfa0c08-076a-11e8-a490-02c35d847e20") with: invalid character 'm' looking for beginning of value
```

**What you expected to happen**:

I would have been expected, that the new container mounts the *demo-vsm1-vol1* volume.

**How to reproduce it (as minimally and precisely as possible)**:

Basically I just followed the tutorial:
* I checkout out the repository
* I went to: `k8s/demo`
* I ran `vagrant up`
* I verified if everything looks fine
* I started a percona server: `vagrant ssh kubemaster01 -- kubectl create -f /tmp/demo-mysql-openebs-plugin.yaml`
* I added a database, table and a row
* I replace the container with: `kubectl get pod mysql -o yaml | kubectl replace --force -f -`
* Then you can see the error:

```
Name:           mysql
Namespace:      default
Node:           kubeminion-01/172.28.128.3
Start Time:     Thu, 01 Feb 2018 17:14:18 +0000
Labels:         name=mysql
Status:         Pending
IP:
Controllers:    <none>
Containers:
  mysql:
    Container ID:
    Image:              mysql
    Image ID:
    Port:               3306/TCP
    Args:
      --ignore-db-dir
      lost+found
    Limits:
      cpu:      500m
    Requests:
      cpu:              500m
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/lib/mysql from demo-vsm1-vol1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-0qtjp (ro)
    Environment Variables:
      MYSQL_ROOT_PASSWORD:      k8sDem0
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
Volumes:
  demo-vsm1-vol1:
  <unknown>
  default-token-0qtjp:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-0qtjp
QoS Class:      Burstable
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  29s           29s             1       {kubelet kubeminion-01}                 Warning         FailedMount     MountVolume.SetUp failed for volume "openebs/openebs-iscsi/55968bf4-0773-11e8-8968-02c35d847e20-demo-vsm1-vol1" (spec.Name: "demo-vsm1-vol1") pod "55968bf4-0773-11e8-8968-02c35d847e20" (UID: "55968bf4-0773-11e8-8968-02c35d847e20") with: invalid character 'm' looking for beginning of value

```

**Anything else we need to know?**:

Git sha: `7db8fc943d80465289cb2aa46fbd04fa4fcea2e6`
Kubemaster images:
```
 sudo docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
weaveworks/weave-npc                                     2.2.0               765b48853ac0        2 days ago          46.55 MB
weaveworks/weave-kube                                    2.2.0               222ab9e78a83        2 days ago          93.98 MB
mysql                                                    latest              f008d8ff927d        2 weeks ago         408.5 MB
gcr.io/google_containers/kube-apiserver-amd64            v1.5.5              18c9bd8bd15d        10 months ago       125.9 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.5.5              3f9819d4efc8        10 months ago       102.8 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.5.5              66688d826177        10 months ago       54 MB
gcr.io/google_containers/kube-proxy-amd64                v1.5.5              5e6f37c0b77c        10 months ago       173.5 MB
weaveworks/weave-npc                                     1.9.4               e97ebd34f5e3        10 months ago       58.23 MB
weaveworks/weave-kube                                    1.9.4               77be5bc6f826        10 months ago       163.3 MB
gcr.io/google_containers/etcd-amd64                      3.0.14-kubeadm      856e39ac7be3        14 months ago       174.9 MB
gcr.io/google_containers/kubedns-amd64                   1.9                 26cf1ed9b144        14 months ago       47 MB
gcr.io/google_containers/dnsmasq-metrics-amd64           1.0                 5271aabced07        15 months ago       14 MB
gcr.io/google_containers/kube-dnsmasq-amd64              1.4                 3ec65756a89b        16 months ago       5.126 MB
gcr.io/google_containers/kube-discovery-amd64            1.0                 c5e0c9a457fc        16 months ago       134.2 MB
gcr.io/google_containers/exechealthz-amd64               1.2                 93a43bfb39bf        16 months ago       8.375 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        21 months ago       746.9 kB
```

kubernetesminon images:
```
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
weaveworks/weave-npc                                     2.2.0               765b48853ac0        2 days ago          46.55 MB
weaveworks/weave-kube                                    2.2.0               222ab9e78a83        2 days ago          93.98 MB
mysql                                                    latest              f008d8ff927d        2 weeks ago         408.5 MB
gcr.io/google_containers/kube-apiserver-amd64            v1.5.5              18c9bd8bd15d        10 months ago       125.9 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.5.5              3f9819d4efc8        10 months ago       102.8 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.5.5              66688d826177        10 months ago       54 MB
gcr.io/google_containers/kube-proxy-amd64                v1.5.5              5e6f37c0b77c        10 months ago       173.5 MB
weaveworks/weave-npc                                     1.9.4               e97ebd34f5e3        10 months ago       58.23 MB
weaveworks/weave-kube                                    1.9.4               77be5bc6f826        10 months ago       163.3 MB
gcr.io/google_containers/etcd-amd64                      3.0.14-kubeadm      856e39ac7be3        14 months ago       174.9 MB
gcr.io/google_containers/kubedns-amd64                   1.9                 26cf1ed9b144        14 months ago       47 MB
gcr.io/google_containers/dnsmasq-metrics-amd64           1.0                 5271aabced07        15 months ago       14 MB
gcr.io/google_containers/kube-dnsmasq-amd64              1.4                 3ec65756a89b        16 months ago       5.126 MB
gcr.io/google_containers/kube-discovery-amd64            1.0                 c5e0c9a457fc        16 months ago       134.2 MB
gcr.io/google_containers/exechealthz-amd64               1.2                 93a43bfb39bf        16 months ago       8.375 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        21 months ago       746.9 kB
````

also no matter what I do, the volumes are marked as offline in maya:
```
maya vsm-stats demo-vsm1-vol1             
------------------------------------                       

    IQN: iqn.2016-09.com.openebs.jiva:demo-vsm1-vol1       
 Volume: demo-vsm1-vol1      
 Portal: 172.28.128.133      
   Size: 5G                  

Replica         Status      DataUpdateIndex                
172.28.128.140  Offline     Unknown                        
172.28.128.134  Offline     Unknown                        
------------------------------------  
```

except I remove one node, then the other node becomes waiting.

**Comment by kmova** [comment]
Sorry @alwinmark. My mistake, I should have updated the docs. K8s/demo/Vagrantfile is pretty old version and is not supported anymore. I will clean up the repository to remove these deprecated files. 

The latest Vagrantfile are located at
https://github.com/openebs/openebs/tree/master/k8s/vagrant

**Comment by alwinmark** [comment]
@kmova could you please not only remove the old Vagrant file but also update the Documentation  at: [how to spin up an dedicated cluster](https://github.com/openebs/openebs/tree/master/k8s/dedicated).
I don't know if you changed the general architecture, but I personally like the Idea of having two k8s cluster.

So before I want to rely on this technology on production, I want to test it in a nearly real live scenario, so I'd like to spin up both clusters locally, do some chaosmonkey actions, watch if everything recovers and if not, rebuild everything.

I know there are Env Parameters where I can control how many nodes of which type should be spawned, but it would be nice to have the command written down in the docs somewhere.

Beside of that, this is a very interesting project and I hope it will meet my expectations :-)

**Comment by alwinmark** [comment]
So I'm really struggling to get the dedicated cluster up and running, even with the up to date vagrant environment.

I'm especially wondering, why the omm and osh nodes are not a kubernetes cluster themselves as I read this all the time in the install guides.
Also there I guess I've to tweak the storage classes for the dedicated cluster. Would be awesome if there would be sth. predefined.

So I'm keep messing arround until I get sth. to work, but it would be awesome if you could give me further hints and/or update the docs.

**Comment by kmova** [comment]
@alwinmark 

Post 0.3, we started moving towards a kubernetes hyper-converged clusters. So you will not notice any omm/osh nodes any more in the vagrant files or the install guides.

So currently the following is supported:
- Spin up a new kubernetes cluster (or use your own cluster)
- Run the openebs operator inside the same kubernetes cluster

**Comment by alwinmark** [comment]
Ok that would explain a lot, but: How do I configure my storage classes to connect to a different kubernetes cluster?

Or would you recommend running one big cluster with application and data nodes? I only see those flexdriver configs which seem not to be compatible with the storage class configurations:

```
  - name: demo-vsm1-vol1
    flexVolume:
      driver: "openebs/openebs-iscsi"
      options:
        name: "demo-vsm1-vol1"
        openebsApiUrl: "http://172.28.128.4:5656/latest"
        size: "5G"
```

or am I supposed to just add this like:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-percona
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
  openebs.io/ApiUrl: "http://172.28.128.4:5656/latest"
```

thanks

**Comment by kmova** [comment]
You will need to have a single cluster with application and data nodes. 

To support an external cluster, the iSCSI service needs to be exposed on an external IP. This piece is currently missing.

**Comment by alwinmark** [comment]
Thats a development direction I actually don't like.

I'd really prefer this kind of architecture: ![a seperate cluster](https://github.com/openebs/openebs/raw/master/documentation/source/_static/dedicated-with-podsv0.2.png)

because than I'm able to control in a more sophisticated way, hot to scale and what is running where. As you are also VP Engineer of http://www.cloudbyte.com/, how does this architecture fit into the appliances you provide there?

I thought those devices are acting as osh nodes but it seems to be not that way.

thank you for all the information

**Comment by kmova** [comment]
Thank you for the inputs and feedback @alwinmark 

The direction of this project is controlled by users like yourself! We have a weekly contributor meeting where we can discuss new usecases and take up new features for development. We are almost at the end of 0.6 milestone and in the early stages of 0.7 planning. 

It will be great to have on the planning meeting to help us take the right features forward. If you can send me your email id to (kiran.mova@openebs.io), I can add you to the meeting invite. 

Looking forward to collaborating with you.
