### ISSUE TITLE
pvc rep deployment should have disruption budget

### ISSUE THREAD

**Issue by clkao** [openebs/openebs#1195]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**:

1. create a pvc with 2 replicas
2. edit the pvc deployment pod, add nodeSelector
3. both rep pods get deleted and respawned, the pvc became unavailable

**What you expected to happen**:

1. the deployment spawns new pod while the at least one of the old replicas was kept alive
2. the new pod should become RUNNING only after the sync from the old rep pod is complete
3. replicas of the old deployment are removed 

**How to reproduce it (as minimally and precisely as possible)**:

1. create a pvc with 2 replicas
2. edit the pvc deployment pod, add nodeSelector

**Anything else we need to know?**:

- kubernetes v1.9.0+coreos.0 on baremetal installed with kubespray
- openebs-0.5.1 installed with helm

**Comment by clkao** [comment]
it seems the deployment already have:
```
RollingUpdateStrategy:  1 max unavailable, 1 max surge
```

So I think it's because the rep pod becomes RUNNING before the initial replication sync is done.

**Comment by AmitKumarDas** [comment]
@clkao Did you try the `kubectl patch` option or `kubectl edit` option

**Comment by clkao** [comment]
I did `kubectl edit`.

This was just to experiment moving the rep node but accidentally triggered the issue. But this can still happen if both rep pods got evicted from the nodes.

**Comment by AmitKumarDas** [comment]
@ashishranjan738 Do have a look at https://kubernetes.io/docs/tasks/run-application/configure-pdb/
