### ISSUE TITLE
NDM should check for partitions(/dev/sdc1) and create device CRs

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1210]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
The PR nodebot-cli checks for disk availability for /dev/sdc only. 

**What you expected to happen**:
It should be able to detect /dev/sdc1(partitions) as well.

**How to reproduce it (as minimally and precisely as possible)**:
Connect a disk with partition to any node in k8s cluster.

**Anything else we need to know?**:

**Comment by dunefro** [comment]
This is a right requirement and can be explained in the simple but interesting thing I noticed. 
Let's say I have a device /dev/xvdf and I have create three primary partitions.
```
ubuntu@aws04:~/workspace$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 89.1M  1 loop /snap/core/8268
loop1     7:1    0   18M  1 loop /snap/amazon-ssm-agent/1480
loop2     7:2    0 54.6M  1 loop /snap/core18/1288
loop3     7:3    0 89.1M  1 loop /snap/core/8213
loop4     7:4    0  9.3M  1 loop /snap/helm/176
sda       8:0    0   30G  0 disk 
sdb       8:16   0    4G  0 disk 
xvda    202:0    0  100G  0 disk 
└─xvda1 202:1    0  100G  0 part /
xvdf    202:80   0  100G  0 disk 
├─xvdf1 202:81   0   33G  0 part 
├─xvdf2 202:82   0   33G  0 part 
└─xvdf3 202:83   0   33G  0 part
```
I have allowed the matchfilters option in values.yaml for openebs to use /dev/xvdf as a disk. Now we list the blockdevices available
```
ubuntu@aws04:~/workspace$ kubectl get blockdevices -n openebs
NAME                                           NODENAME   SIZE           CLAIMSTATE   STATUS   AGE
blockdevice-e4694b0a5334cc5eba75e7912deb8e78   aws04      107374182400   Unclaimed    Active   16m
```
There is only one block device attached for this. It is also considerable that there is only one block device but there are multiple partitions available but on describing the block devices it shows that the block device is not partitioned.
```
ubuntu@aws04:~/workspace$ kubectl describe blockdevices -n openebs
Name:         blockdevice-e4694b0a5334cc5eba75e7912deb8e78
Namespace:    openebs
Labels:       kubernetes.io/hostname=aws04
              ndm.io/blockdevice-type=blockdevice
              ndm.io/managed=true
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         BlockDevice
Metadata:
  Creation Timestamp:  2020-01-08T17:19:50Z
  Generation:          1
  Resource Version:    5068126
  Self Link:           /apis/openebs.io/v1alpha1/namespaces/openebs/blockdevices/blockdevice-e4694b0a5334cc5eba75e7912deb8e78
  UID:                 a2fd4153-3350-44f3-9f35-064852e39143
Spec:
  Capacity:
    Logical Sector Size:   512
    Physical Sector Size:  0
    Storage:               107374182400
  Details:
    Compliance:         
    Device Type:        
    Firmware Revision:  
    Model:              
    Serial:             
    Vendor:             
  Devlinks:
  Filesystem:
  Node Attributes:
    Node Name:  aws04
  **Partitioned:  No**
  Path:         /dev/xvdf
Status:
  Claim State:  Unclaimed
  State:        Active
Events:         <none>
```
You can clearly see partitioning to NO. AM i missing something here or should I try for some other approach. Kindly refer to the part of the doc If I am missing something.

**Comment by akhilerm** [comment]
Support for partitions has been added via  a feature gate in NDM in [PR#386](https://github.com/openebs/node-disk-manager/pull/386)
