### ISSUE TITLE
Run a logging container to extract infrastructure and OpenEBS usage pattern 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1224]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

This issue will track the efforts to create a "logging container" that can run run alongside the application and OpenEBS pods and capture "current" information (OpenEBS-specific) on the infra details. This information will be filtered & "templatized" along with "usage" patterns (obtained from stern logs, say) to fit the e2e-template specified in : #1216 

This can then be used to spin-up similar environments and will be especially helpful in reproducing user issues.

In a way, this issue also extends #1151

**Comment by ksatchit** [comment]
This issue talks at length about the need for logs:  https://github.com/kubernetes/kubernetes/issues/24677

This PR provides some basic debug logging steps using stern: https://github.com/openebs/test-storage/pull/28

**Comment by kmova** [comment]
Keeping this issue open to get the Docs updated.
