### ISSUE TITLE
Make maya-apiservice a configurable value

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1227]
FEATURE REQUEST

The openebs provisioner assumes that the maya-apiserver runs within in the same cluster and its service name is "maya-apiserver-service". This hardcoding of the name could conflict with other services running in the cluster. 
https://github.com/kubernetes-incubator/external-storage/blob/2fd77da/openebs/pkg/v1/maya_api.go#L65

Expected change:
(a) Provide the service name as an ENV variable to the provisioner. 

The other alternatives could be:
(b) make the maya-apiserver details part of the storageclass
(c)  pass the maya-apiserver URL as env (so that provisioner can connect to an external maya-apiserver)

**Comment by AmitKumarDas** [comment]
@kmova having Maya API server URL in Storage Class is good to have. This will enable use of multiple apiservers in a cluster or talking to a apiservers across different cluster. However even labelselector  can be used in Storage Class to talk to a particular maya API server within a cluster. Label selector seems to be kubernetes way
