### ISSUE TITLE
Improve troubleshooting documentation to include section for volume Read-Only issues

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1236]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

The current troubleshooting section on the OpenEBS documentation at : http://openebs.readthedocs.io/en/latest/troubleshooting/troubleshooting.html needs to be improved to include details on steps to perform when faced with volume going into Read-Only mode (This is typically seen when there are network disruptions/resource issues causing a disconnect between the jiva controller and replica pods) 

**What you expected to happen**:

OpenEBS documentation should consist of steps to follow to debug and recover the OpenEBS and application pods upon facing volume read-only error.

**How to reproduce it (as minimally and precisely as possible)**:

n/a 

**Anything else we need to know?**:

The section should consider environments wherein kubelet runs as a container **&** as a binary on the node.

**Comment by ksatchit** [comment]
One set of steps which was used to recover OpenEBS PVC pods in a rancher environment is provided below (Pretty long) . Working on getting a-generic procedure which will eventually go into the troubleshooting doc : 

```
a/ Unmount disk from `/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/<target-portal:iqn>`

b/ Unmount disk from `/var/lib/kubelet/pods/<pvc>/

c/ Logout from the stale iSCSI session

d/ Re-login into the same target IQN (disk may come up w. a different scsi name)

e/ Re-mount the new disk into the mountpoints mentioned in a/ & /b

(Optional step : If the mount is still RO, we need a controller restart after confirming the ctrl logs)

f/ Get the app to use new mount by restarting it 
(i.e., if it is a deployment do a `kubectl delete pod` so that a new replica of the app is created OR if it is a pod, 
do a `sudo docker stop` of the app container so that kubelet brings it back up)

g/ Sometimes it is desirable to push the pod to a new node to ensure fresh login/mount - this can be done using
the kubectl cordon node <current node where app resides>

h/ If the kubelet is running in a container (as in w/ rancher/coreos etc.,) it needs to be restarted
```

**Comment by kmova** [comment]
Documented at https://staging-docs.openebs.io/docs/tsgpvs.html
