### ISSUE TITLE
OpenEBS K8s provisioner should push images with "ci" tag as part of travis build 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1240]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

To enable e2e runs on images with latest dev changes, the openebs/m-apiserver, openebs/openebs-k8s-provisioner and openebs/jiva images need to be pushed with a "ci" tag as part of the travis build. The ansible playbooks running in the ci suite will update the openebs-operator yaml from the release branch with the "ci" tags and deploy (refer #616 ) 

**What you expected to happen**:

openebs/m-apiserver and openebs/jiva already push the "ci" tag upon code changes, with "latest" & release-tags upon performing a major/minor release. 

This needs to be extended to openebs/openebs-k8s-provisioner

**Comment by xtaraim** [comment]
We can solve it.. 
tag the image & push the image to the registry. 
 - docker build -f Dockerfile -t $REPO:$COMMIT .
 — docker tag $REPO:$COMMIT $REPO:$TAG
 — docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
 — docker push $REPO
