### ISSUE TITLE
Want SCSI sense data monitoring to diagnose issues in IO path(s)

### ISSUE THREAD

**Issue by gila** [openebs/openebs#1241]
Feature request

To provide meaningful information to the user about why an openEBS volume is not in the desired operational state, we need to monitor in the IO path itself.

For example, the default mount parameters for Linux will remount the filesystem to RO when there are errors. It is debatable if this is the desired state but some IO errors will result in an unusable volume, regardless of the RO model.

To make matters more challenging, we can have these IO errors at several layers, namely at the target to the replica level and the replica to actual storage backend. 

To start, we first need to collect error telemetry of involved disks/replicas that constitute the actual openEBS volume; once we have obtained the error telemetry, we can go to the next stage and diagnose these errors to provide meaningful information to the users.

Note that, bombarding the user with errors themselves is not considered a solution rather, we need to provide a diagnosed output based on the telemetry. Which means that we need to tell the user the what, why, where and the operational impact in a format the user can comprehend. The errors that contributed to the state should be recorded and stored for later inspection. 

The suggestion is to collect (and store) SCSI sense data such that we can determine based on that information, why the disk/replica is failing.

**Comment by kmova** [comment]
This should be added to https://github.com/openebs/node-disk-manager/pull/1
