### ISSUE TITLE
Let maya api server fail explicitly rather than assume defaults for storage pool

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1242]
e.g. the logs has this warning & uses the default path i.e. /var/openebs instead.
This makes maya api server as a black box system than a whitebox/understood system by users.

W0216 16:34:29.576992       6 policy_jiva_k8s.go:254] storagepools.openebs.io "default" is forbidden: User "system:serviceaccount:store-openebs:openebs-operator" cannot get storagepools.openebs.io in the namespace "demo-static"

**Comment by kmova** [comment]
To maintain backward compatibility with earlier releases, code falls back to /var/openebs as default storage pool.
