### ISSUE TITLE
Contributor documentation w.r.t openebs/maya & openebs/external-storage

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1243]
Comment from an openebs user
>but i'd still like to try it. btw there doesn't seem to be doc about building and tagging all the components, pushing to private registry, and deploy a test storage class provisioned by the locally built version

**Comment by farhaanbukhsh** [comment]
Hey, if no one is working on this issue I would like to take it up? Can some one guide me with this?

**Comment by AmitKumarDas** [comment]
Please check the existing doc and run through it. You may send a PR if you feel changes need to be done.

**Comment by farhaanbukhsh** [comment]
hey sorry to stall so long I will give it a look :)
