### ISSUE TITLE
Want easier visibility in storage topology from maya CLI 

### ISSUE THREAD

**Issue by gila** [openebs/openebs#1248]
FEATURE REQUEST

When dealing with lots of PVC and controllers it becomes (rather quickly!) a challenge to extract information about how those PVC's interact with the application. 

The canonical way seems to match the output of different `kubectl` commands and plow your way through. Maya's CLI provides,  from a storage perspective, a little more insight as to what is what but it lacks the bigger picture that you can extract by using `kubectl`

The proposal is to extend the `maya` CLI tool to create a hierarchical picture of the containerized storage instances from controller to replica. The output should indicate what PODs its serving storage too and also, what replicas are involved and their status. Lastly, it should indicate how they are connected to the controller which glues them all together. 

This will also improve the troubleshooting experience -- if any.

**Comment by ashishranjan738** [comment]
I want to work on this issue
