### ISSUE TITLE
Update Readme to use kube-stat-metrics for monitoring kubernetes objects.

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#1249]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
Feature Request
- [kube-stat-metrics](https://github.com/kubernetes/kube-state-metrics) is deployed in kube-system namespace and it gives the stats of the kubernetes objects such as pods, services, deployments etc.
- It can be used for more intensive monitoring
- It is good to pack it along with the OpenEBS vagrant boxes or user can deploy it manually.

**Comment by Rupeshiya** [comment]
@utkarshmani1997  what you are expecting from contributors to do in issue #1249 ?.
Please explain it cleraly.

**Comment by utkarshmani1997** [comment]
@Rupeshiya you need to edit [this](https://github.com/openebs/openebs/blob/master/k8s/openebs-monitoring/README.md) file and provide the details to how to deploy kube-stat-metrics.

**Comment by utkarsh2102** [comment]
@kmova, I'd like to take up the issue.
If inferred correctly, I'll have to add deployment metric table to the README.md file.
I'll do the needful, if so?
CC: @NisantaSahoo

**Comment by kmova** [comment]
@utkarsh2102 : this is more of exploring the installation and monitoring of openebs components with kube-metrics server.
