### ISSUE TITLE
Update openebs-monitoring templates to use Prometheus v2.0

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#1250]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
Feature Request
- Prometheus and Grafana both has made significant changes in the latest stable versions wrt UI as well as the configurations.Latest version of prometheus decreases the memory/storage/cpu usage upto 10-40%. So it's good to have latest versions of prometheus and grafana.

**Comment by kmova** [comment]
@utkarshmani1997  what are the versions of the prometheus and grafana to be used?

**Comment by utkarshmani1997** [comment]
@kmova Prometheus > v2.0 and grafana v 4.6.3 can be preferred.
