### ISSUE TITLE
Handle exceptions better in the generate_inventory.py 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#126]
Currently, the script does an "except:pass" while creating a host details list from the machines.in input file. We also need to add better exception handling where applicable.

**Comment by cxong** [comment]
There's no "except:pass" anymore, seems to be fixed in https://github.com/openebs/openebs/commit/e4b5ece33f278c18612210e972689e5d30d32569#diff-030bdbaec8e2e33189b8b6ba38d76cb3

**Comment by vharsh** [comment]
Fixes: #136
