### ISSUE TITLE
Replica failed to register with controller. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1277]
This case was uncovered when running node down tests. In a kubernetes cluster with 3 worker nodes, an openebs volume was provisioned with 3 replicas. All the three replica's showed that they were in RW mode.  The controller was on node-2. 

node-1 and node-2 where shut-down one by one. 

The controller moved to node-3. (It was observed that the movement or scheduling of this controller to the node-3 took longer - more than 2 minutes). But eventually the controller was running on node-3.

Now, both controller and the remaining replica where on the node-3, but volume was offline. Looking at the logs for controller and replica - The replica never registered to the controller. And also there were no indications in the replica-logs of controller not reachable. 

**Controller logs**
```
mount: special device /host/dev does not exist
time="2018-02-23T15:08:47Z" level=info msg="Listening on :9501"
```

** Replica logs**
[rep3.node3.txt](https://github.com/openebs/openebs/files/1753049/rep3.node3.txt)

_Note: After waiting for 5/10 minutes, continued with the next test, which was to shut-down all the nodes. After node-3 was shutdown and all three were made online, the volume became online._

**Comment by AmitKumarDas** [comment]
@kmova We might need to set pod priority to controller.
However, this can lead to disruptions of other pods running on node-3.
These are alpha features & might work in K8s 1.9 onwards.

ref - https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by AmitKumarDas** [comment]
How was the time difference determined?
