### ISSUE TITLE
Enhance the openebs scheduler logic to pin the replica to the nodes & pin the controller to the workload app

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1279]
openebs scheduling logic should take care of below requirements:

- making the controller run on the same node as application workload (Refer #1257, #1308 )
- making the replica always sticky to the node where they were initially scheduled. ( Avoids flaky movements and long re-sync period) (Refer #1310 )

**Comment by kmova** [comment]
This was implemented in OpenEBS 0.9, with replicas pinned to the node where they get scheduled and controller can be pinned to the application pod using the targetAffinity feature. https://docs.openebs.io/docs/next/jivaguide.html#Target-Affinity-Policy
