### ISSUE TITLE
maya should enable update policies for volume

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1284]
This issue will look into the implementation of VolumeUpdatePolicy.

**Comment by kmova** [comment]
Only manual upgrade will be supported for 0.8.0 #2314

**Comment by kmova** [comment]
Upgrade is handled via the Kubernetes job. The progress of that feature is being tracked under. https://github.com/openebs/openebs/blob/master/contribute/design/1.x/upgrade/volume-pools-upgrade.md
