### ISSUE TITLE
Using cStor Engine for OpenEBS Volumes. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1296]
FEATURE REQUEST

cStor is the new storage engine that makes using COW based storage engine to write the data to the disks. This issue tracks the design and various implementation tasks involved in orchestrating the provisioning and management of cStor volumes by OpenEBS maya.

**Comment by ranjithwingrider** [comment]
Steps for provisioning cStor volume is given below:
1. Create a SPC which is a group of cStor pools: https://docs.openebs.io/docs/next/ugcstor.html#creating-cStor-storage-pools
2. Create a SC which will consume the SPC created in step 1: https://docs.openebs.io/docs/next/ugcstor.html#creating-cStor-storage-class
3. Mention the SC in application PVC spec. Example steps for provisioning an application is provided here: https://docs.openebs.io/docs/next/ugcstor.html#Provisioning-sample-application-with-cstor
