### ISSUE TITLE
Customize the readthedocs theme for OpenEBS docs

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#13]
OpenEBS docs auto-generated are available at:
http://openebs.readthedocs.io/en/latest/

This needs to be customized for coloring, ordering of pages, providing domain name etc.,

**Comment by vharsh** [comment]
Great starting points
- [List of popular read the docs themes](http://www.writethedocs.org/guide/tools/sphinx-themes/)

**Comment by kmova** [comment]
The documentation has moved to https://github.com/openebs/openebs-docs and doesn't uses readthedocs anymore.
