### ISSUE TITLE
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes 

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1301]
I get this error. This is a new laptop where I have installed vagrant & virtualbox for the first time.

```bash
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b06eddbf-70b1-43b6-aaeb-4a241c813a99", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by AmitKumarDas** [comment]
References:
- https://superuser.com/questions/22915/how-do-i-enable-vt-x

**Comment by AmitKumarDas** [comment]
![vt-1](https://user-images.githubusercontent.com/2794362/36890101-a8270fa6-1e22-11e8-9a44-9ab90284538f.jpg)
![vt-2](https://user-images.githubusercontent.com/2794362/36890102-a87ca5f6-1e22-11e8-9062-770d2292d192.jpg)

**Comment by vharsh** [comment]
One can check it if it is enabled by reading this file `/proc/cpuinfo`
More simply put,
```bash
cat /proc/cpuinfo| egrep -o "vmx|svm"
```
should show some matched lines

Ref: [StackOverflow](https://stackoverflow.com/questions/11116704/check-if-vt-x-is-activated-without-having-to-reboot-in-linux)

**Comment by ksatchit** [comment]
This content needs to be added to the troubleshooting section in : https://docs.openebs.io/docs/onpremise.html

**Comment by AmitKumarDas** [comment]
Upgrading the Vagrant & VirtualBox helped along with enabling BIOS settings on my laptop
- https://github.com/openebs/openebs/issues/30
- https://github.com/openebs/openebs/issues/32
