### ISSUE TITLE
VolumePolicy should support volume controller & application affinity

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1308]
It has been seen that side-effects of network issues are minimized when volume controller & application PODs are on the same K8s node.

It will be good to let VolumePolicy support this affinity.

**Comment by AmitKumarDas** [comment]
refer - https://github.com/openebs/community/tree/master/feature-demos/volumepolicies/ctrl-pinning

**Comment by kmova** [comment]
Need to look at the volume topology related changes to see if the scheduled node of the pod details can be obtained and passed as a policy to schedule the target pod onto the same node.
