### ISSUE TITLE
volume capacity stats are not working when total capacity is less than 1GB

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1312]
OpenEBS_size_of_volume query is not giving total size of volume for PostgreSQL application. it is giving zero.

**Comment by nsathyaseelan** [comment]
https://github.com/mayadata-io/maya-io/issues/247

**Comment by nsathyaseelan** [comment]
![grafana](https://user-images.githubusercontent.com/32131456/37014711-824bd5ec-2128-11e8-943d-4aeeeed016ca.png)

**Comment by nsathyaseelan** [comment]
maya volume stats pvc-55f1ca61-204d-11e8-9948-42010a800208
```
IQN     : iqn.2016-09.com.openebs.jiva:pvc-55f1ca61-204d-11e8-9948-42010a800208
Volume  : pvc-55f1ca61-204d-11e8-9948-42010a800208
Portal  : 10.19.243.211:3260
Size    : 400M

      Replica|   Status|   DataUpdateIndex|
             |         |                  |
   10.16.1.39|   Online|             30148|
             |         |                  |

----------- Performance Stats -----------

   r/s|   w/s|   r(MB/s)|   w(MB/s)|   rLat(ms)|   wLat(ms)|
     0|     0|     0.000|     0.000|      0.000|      0.000|

------------ Capacity Stats -------------

   Logical(GB)|   Used(GB)|
         0.085|      0.080|
```

**Comment by utkarshmani1997** [comment]
this is the bug in m-exporter, the size returns an integer value in GB but the requested query for PostgreSQL is provisioned with the size 400 mb that's why the value is zero.

**Comment by kmova** [comment]
@nsathyaseelan -- could you also please update the PVC yaml file associated with this issue.

**Comment by kmova** [comment]
this issue is fixed by https://github.com/openebs/maya/pull/343 which will be in 0.7 release.
