### ISSUE TITLE
libiscsi failure on iSCSI.iSCSIdatasn test with latest jiva/gotgt 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1319]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

**What happened**:

The libiscsi testsuite run as part of the CI is seen to fail on the latest jiva image, with the testcase iSCSI.iSCSIdatasn getting "stuck". The test logs are as shown below : 

```
ubuntu@hch-01:~/libiscsi_suite_logs$ cat iSCSI.iSCSIdatasn.log

     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/

Suite: iSCSIdatasn
  Test: iSCSIDataSnInvalid ...    [FAILED] WRITE10 command: failed with sense. SCSI command timed out
    [FAILED] WRITE10 command: failed with sense. SCSI command timed out
    [FAILED] WRITE10 command: failed with sense. SCSI command timed out
FAILED
    1. test_iscsi_datasn_invalid.c:86  - CU_ASSERT_NOT_EQUAL(ret,0)
```
The jiva controller log shows : 

```
time="2018-03-07T08:15:23Z" level=info msg="connection is connected from 10.44.0.0:40232...\n"
time="2018-03-07T08:15:23Z" level=info msg="Listening ..."
time="2018-03-07T08:15:23Z" level=info msg="New Session initiator name:iqn.2007-10.com.github:sahlberg:libiscsi:iscsi-test,target name:iqn.2016-09.com.openebs.jiva:pvc-311786d6-21df-11e8-8c96-02b983f0a4db,ISID:0x805c66940000"
time="2018-03-07T08:15:23Z" level=error msg="Cannot find iSCSI task with tag[2]"
```

**What you expected to happen**:

- This test suite should complete with supported tests passing successfully

**How to reproduce it (as minimally and precisely as possible)**:

- Run libiscsi test playbook against the openebs operator that uses "latest" jiva image

**Anything else we need to know?**:

ALL.CompareAndWrite
ALL.Inquiry
ALL.Mandatory
ALL.ModeSense6
ALL.NoMedia
ALL.OrWrite
ALL.Prefetch10
ALL.Prefetch16
ALL.PreventAllow
ALL.PrinReadKeys
ALL.PrinServiceactionRange
ALL.ProutRegister
ALL.ProutReserve
ALL.Read6
ALL.Read10
ALL.Read12
ALL.Read16
ALL.ReadCapacity10
ALL.ReadCapacity16
ALL.ReadOnly
ALL.ReadOnly.ReadOnlySBC
ALL.Reserve6
ALL.Sanitize
ALL.StartStopUnit
ALL.TestUnitReady
ALL.Unmap
ALL.Verify10
ALL.Verify12
ALL.Verify16
ALL.Write10
ALL.Write12
ALL.Write16
ALL.WriteVerify10
ALL.iSCSIcmdsn
ALL.iSCSIResiduals
SCSI.CompareAndWrite
SCSI.Inquiry
SCSI.Mandatory
SCSI.ModeSense6
SCSI.NoMedia
SCSI.OrWrite
SCSI.Prefetch10
SCSI.Prefetch16
SCSI.PreventAllow
SCSI.PrinReadKeys
SCSI.PrinServiceactionRange
SCSI.ProutRegister
SCSI.Read6
SCSI.ReadCapacity10
SCSI.ReadCapacity16
SCSI.ReadOnly
SCSI.Reserve6
SCSI.Sanitize
SCSI.StartStopUnit
SCSI.TestUnitReady
SCSI.Unmap
SCSI.Verify10
SCSI.Verify12
SCSI.Verify16
SCSI.WriteVerify10
SCSI.WriteVerify12
SCSI.WriteVerify16
iSCSI.iSCSIcmdsn
iSCSI.iSCSIdatasn
iSCSI.iSCSIResiduals

**Comment by dargasudarshan** [comment]
@payes Please find the attached file with tcpdump.
[dump1.txt](https://github.com/openebs/openebs/files/1788941/dump1.txt)

FYI: This issue is not seen with previous version of jiva:0.5.1

**Comment by dargasudarshan** [comment]
Tested with latest openebs/jiva:ci image.

Now the libiscsi test suite is running as expected.

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      1      1    n/a      0        0
               tests     10     10      0     10        0
             asserts    315    315    170    145      n/a

Elapsed time =    0.006 seconds
Tests completed with return value: 0

No of tests passed:146  No of tests failed:29

**Comment by payes** [comment]
This test, actually doesn't do what its supposed to do, but it had exposed a bug where we are sending an initial R2T even though, we had set it to no. Because of which libiscsi test suite was stalled in between. So as part of the fix initialR2T is set to yes during initial negotiations.
