### ISSUE TITLE
Should jiva controllers & replicas be started / re-started based on a sequence

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#132]
Maya api server with K8s as its orchestration provider launches with below sequence:
- jiva controller, 
- jiva service,
- jiva replica(s)

Should the same order be maintained during node maintenance, reboots, jiva patch/upgrades ?

**Comment by kmova** [comment]
During creation, we will need to following this order:

- jiva service (get the cluster ip from this service)
- jiva controller (provide the cluster ip for clusterIP)
- jiva replica (with the cluster ip as the frontendIP)

For deletion:
- delete the application using the VSM
- delete the jiva replica (deployment)
- delete the jiva controller (deployment)
- delete jiva service.

**Comment by kmova** [comment]
The above sequence has been implemented into openebs 0.4
