### ISSUE TITLE
mysterious provisioner error message: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by clkao** [openebs/openebs#1322]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**:

the provisioner pod stopped provisioning new pvcs, and shows error message:

`interface conversion: interface {} is nil, not map[string]interface {}`

Further diagnosis from maya-apiserver concluded that it was due to maya failure that it can't connect to the kubernetes api endpoint.  This might have been causedy by temporary networking failure of a particular node.

**What you expected to happen**:

error message that is meaningful and leads the user to investigate maya apiserver.

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by kmova** [comment]
@clkao - Just a thought.. would you like to raise a PR to fix this issue?

**Comment by kmova** [comment]
A lot can be improved w.r.t displaying proper messages. However, with 0.7.2 this cryptic message doesn't appear any more. m-apiserver doesn't start its http end-point, when it can't communicate with K8s. The provisioner logs the following message:

```
  Warning  ProvisioningFailed    3m (x12 over 3m)  openebs.io/provisioner-iscsi openebs-provisioner-654454fc7f-wvxrn c2b3d946-f388-11e8-a6b8-
0a580a2c0008  Failed to provision volume with StorageClass "jiva-1r": Get http://10.47.244.180:5656/latest/volumes/pvc-0813cbfa-f38b-11e8-93d
0-42010a80001d: dial tcp 10.47.244.180:5656: connect: connection refused
```
