### ISSUE TITLE
Update troubleshooting doc with steps for containerized kubelet - based clusters 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1328]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

As part of a recent debug session in an kubernetes environment running containerized kubelet(Rancher 1.6.x) , the following steps were performed as part of the recovery procedure for a Volume-Read Only issue

- Confirm that the OpenEBS target is not presented as RO device by the OpenEBS controller & that all replicas are in RW mode
- Unmount the iSCSI volume from the node in which the application pod is scheduled
- Perform the following iSCSI operations from *inside* the kubelet container
  - Logout 
  - Rediscover
  - Login
- Remount the iSCSI device (may appear with a new SCSI device name) on the node
- Verify if the application pod is able to start using/writing into the fresh mount 

**What you expected to happen**:

- Get the right set of minimal steps that will recover application data in case of volume read-only issues.

**How to reproduce it (as minimally and precisely as possible)**:

- Cause iSCSI timeouts on nodes hosting application pod in a kubernetes cluster running containerized kubelet.

**Comment by mahebbar** [comment]
Closing based on Updates to troubleshooting steps for clusters configured with containerized kubelet #77 which is closed.
https://docs.openebs.io/docs/next/tsgpvs.html#CrashLoopBackOff
