### ISSUE TITLE
Verify that PV which is under use can't be accidentally deleted. 

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#134]
Hopefully, it will be the K8s openEBS `volume provisioner` & `provider` who will work together to get the creation & deletion validation

**Comment by AmitKumarDas** [comment]
Should there be any validation token from `K8s OpenEBS volume provisioner` that lets maya api server create or delete a PV (`VSM in OpenEBS terms`)

**Comment by kmova** [comment]
This is fixed in K8s 1.10:
- https://github.com/kubernetes/features/issues/498
- https://github.com/kubernetes/features/issues/499
