### ISSUE TITLE
openebs.readthedocs.io/en/latest/ - broken

### ISSUE THREAD

**Issue by qmnonic** [openebs/openebs#1346]
documentation is missing on readthedocs.io .

**Comment by kmova** [comment]
Hi @qmnonic, the docs have moved to docs.openebs.io

**Comment by qmnonic** [comment]
Great.

Google and github ( https://github.com/openebs/openebs/tree/master/documentation ) reference openebs.readthedocs.io, so it's impossible to find that new link.
