### ISSUE TITLE
VolumePolicy should support apps/v1beta1 as apiversion for Deployment Kind

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1347]
The current support for Deployment Kind is with its apiversion as `extensions/v1beta1`.
Kubernetes has recently started supporting Deployment kind with apiversion as `apps/v1beta1`.

Since volume controller & replica are deployed as Deployment Kinds, this change is required.

**Comment by AmitKumarDas** [comment]
This will be implemented as part of https://github.com/openebs/openebs/issues/1310

**Comment by AmitKumarDas** [comment]
Some parts of this will be checked-in via #1310 .
However, user can not use apps/v1beta1 unless `VolumeDeletePolicy` is implemented.

NOTES:
- Currently, user makes use of VolumePolicy to provision a volume
- Deletion can be invoked by issuing API call to maya apiserver
  - Maya apiserver makes use of old deletion logic to delete
- VolumePolicy & older provisioning logic both make use of extensions/v1beta1 for Deployments
- If VolumePolicy starts making use of apps/v1beta1 for provisioning then older deletion logic needs to be modified, due to above invocation pattern
  - This modification in older deletion logic might impact existing usage.
- Hence, it is best to have `VolumeDeletePolicy` (i.e. some form of template) which can hint/suggest the deletion logic/tasks.

**Comment by prateekpandey14** [comment]
fixed in 1.3 openebs version
