### ISSUE TITLE
What a volume really is in OpenEBS

### ISSUE THREAD

**Issue by mhemrg** [openebs/openebs#1352]
I just wanna know what a volume really is in OpenEBS? And how OpenEBS defines the volume size? I think the jiva creates a file and truncates it to the specified length.
Am I right? Will it have any performance issues is a normal stateful application?

**Comment by kmova** [comment]
@mhemrg Your understanding is absolutely correct in terms of the IO path. It might interesting also to watch out for the cStor based OpenEBS volumes , which will directly write onto the block. I have just prepared the following slide-deck (https://docs.google.com/presentation/d/1GsI0Sw9sekOkeOhq25rtMFMQdXJ6fIuhMhNKLBUCHEY/edit?usp=sharing )to present in the contributors meeting, that explains the difference between Jiva and cStor based volumes. Hopefully this might give you some inputs. Feedback always welcome!

Also, please do share if you have any specific performance requirements and the type of stateful application that you are trying to deploy.

**Comment by mhemrg** [comment]
Thanks for your quick response, @kmova.
I'm trying to understand the source code located at `github.com/openebs/jiva/replica`. Sorry, if I ask, but I don't understand how it would be possible to use a truncated file as a volume. Is it possible to do it with some shell commands, as an example?

**Comment by payes** [comment]
Hi @mhemrg, iSCSI protocol does the trick.  gotgt([https://github.com/openebs/gotgt](url)), an iSCSI target implementation) acts as the frontend to jiva. It exposes the truncated sparse file as a block device.
