### ISSUE TITLE
VolumePolicy should support use of nodeAffinity to dedicate nodes for openebs pods

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1356]
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by AmitKumarDas** [comment]
This will be implemented as part of #1310

**Comment by AmitKumarDas** [comment]
https://github.com/openebs/maya/pull/285

**Comment by AmitKumarDas** [comment]
Will be fixed as part of https://github.com/openebs/openebs/issues/1318

**Comment by kmova** [comment]
With 0.7, ReplicNodeSelector and TargetNodeSelector policies are supported.
