### ISSUE TITLE
mayactl should list application pods using openebs volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1358]
FEATURE REQUEST

Refer #1248 

mayactl should be able to provide an end-to-end view into stateful applications. This requires mayactl to communicate with Kubernetes cluster via kube-config or using in-cluster(when running as a Pod within the cluster) and fetch the details from kubernetes api. 

mayactl apps
mayactl apps <app-name>

**Comment by sch00lb0y** [comment]
`mayactl` has to show stateful sets running on `openebs.io/provisioner-iscsi` right ?
`
