### ISSUE TITLE
Version number for cstor-base image

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1361]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
cstor-base image is created with "ci" tag. When the release is made for 0.7, the tag ci used in openebs/maya/buildscripts/cstor-pool-mgmt/Dockerfile should be changed.

**Comment by gkGaneshR** [comment]
0.7 tracking
