### ISSUE TITLE
Add unittests for inventory generation python scripts 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#137]
Need to add this as the ansible inventory generation scripts are scaling in size

The scripts can be found here : https://github.com/openebs/openebs/tree/master/e2e/ansible/roles/inventory/files

**Comment by vharsh** [comment]
Good starting points 
- https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it

**Comment by nikhil-bhat** [comment]
can i take this up

**Comment by ksatchit** [comment]
Sure @nikhil-bhat !

**Comment by ksatchit** [comment]
The intent of this python script is to generate the ansible inventory, i.e., "hosts"  file that is used by the playbooks to perform tasks on target machines. We take input from a simple template file called "machines.in" (which is essentially a csv) to generate the hosts file. You can read more about this input and the hosts file here : 

https://github.com/openebs/openebs/tree/master/e2e/ansible/inventory
