### ISSUE TITLE
Referring current doc in openebs helm chart

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#1373]
## Is this a BUG REPORT or FEATURE REQUEST?
 Still refers to readthedocs link.
 
**What happened**:
Installed OpenEBS using helm. After successful installation, below message gets displayed.
```
To use OpenEBS Volumes, your nodes should have the iSCSI initiator installed. ", "Please visit http://openebs.readthedocs.io/en/latest/getting_started/quick_install.html for instructions"]}"
```
**What you expected to happen**:
Should refer to docs.openebs.io

**Comment by kmova** [comment]
Fixed by https://github.com/openebs/openebs/pull/1532
