### ISSUE TITLE
Enhance the oebs_update.sh script to support more usecases

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1376]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

- Today, the oebs_update.sh (which upgrades the data plane OR OpenEBS volume) takes the PV name as argument and patches the controller & replica deployments corresponding to it. However, this works only in the default namespace. 

- Also, there are a couple of manual steps needed before executing this script : 
   - Deploying the openebs-operator yaml with desired version/image tags
   - Change the image tag in the .tpl.yml templates
   - Cordon nodes which do not host replicas

**What you expected to happen**:

To the extent possible, these steps have to be automated. For instance, these: 

- Take the namespace of the PV as argument
- Take the new image tag as argument 
- Include control plane upgrade in the same script based on a flag, i.e.., something like this : 

  `./oebs_update.sh --ns <namespace> --version <vers> --control-plane|--pv  <pv-name>`

Another *must* requirement is to version the oebs_update.sh for different upgrades from different versions. For example: 
 
- 0.4.0 - 0.5.0 includes label additions in controller deployment which needs step for removal for orphaned RS
- 0.5.0 - 0.5.1/2/3 doesn't need the above
- We may have similar changes from say, 0.5.3 to 0.6 

Today, we are asking the user to take the oebs_update.sh from the 0.4.0-0.5.0 directory and comment/edit it to use for other cases.  A versioned/dedicated scripts will help avoid confusion. 

With the above, there will still be a couple of "possible" requirements such as : 

- Identify which nodes don't host replica and cordon/uncordon via script itself for the upgrade process
- Identify "All" OpenEBS PVs in the given namespace and ask user inputs on ones to upgrade

While these two are good to have, they will need to be debated/don't look like immediate requirements, especially considering we have very less visibility into user environments - automating the cordon step w/o user knowing/doing it doesn't seem a great idea to me. Also, we will have the logic to pin replicas to nodes with scheduling logic enhancements in future releases. 

**How to reproduce it (as minimally and precisely as possible)**:

- Perform volume upgrades using oebs_update.sh 

**Anything else we need to know?**:

The oebs_update.sh was started as a simple temp solution to aid user updates until update policies are available. However, it would make sense to include these fixe/enhancements to improve user-experience until increased automation is available.

**Comment by ksatchit** [comment]
Please consider the above with this issue : https://github.com/openebs/openebs/issues/1222

**Comment by AmitKumarDas** [comment]
@ksatchit Will it be good to have a script or .go program to patch a volume deployment with something below:
```yaml
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - node_where_replica_pod_1_got_scheduled
        - node_where_replica_pod_2_got_scheduled
        - node_where_replica_pod_3_got_scheduled
```

Care needs to be taken that ensure existing nodeAffinity is present in not modified.
So the patch has to merge above options.

Above modularity ensures that the update script can be done via kubectl update/kubectl patch

**Comment by ksatchit** [comment]
Thanks for the comments @amitd. Using the method we are using in 0.6 to maintain replica nodeaffinity here is a good idea. It will remove the need to do cordon steps.

**Comment by ksatchit** [comment]
Thanks for the comments @AmitKumarDas. Using the method we are using in 0.6 to maintain nodeaffinity in this script is a good idea. It will remove the need to do cordon steps.
