### ISSUE TITLE
Kubernetes Operator "no matches for openebs.io"

### ISSUE THREAD

**Issue by maikotz** [openebs/openebs#138]
I was going through the k8s demo setup but couldn't find any documentation about which  TPR or runtime-config needs to be loaded. 

Am I missing something here? 

```
kubectl create -f openebs-config.yaml
error: unable to recognize "openebs-config.yaml": no matches for openebs.io/, Kind=Pool
```

**Comment by kmova** [comment]
@maikotz - the TPR is still under development. this is due for release by june 30th. 

Till then we only need to run:
```
kubectl create -f openebs-operator.yaml
kubectl create -f openebs-storageclasses.yaml
```

In the absence of the openebs-config.yaml, the volumes will be persisted in the /var/openebs (default) directory.

**Comment by maikotz** [comment]
Alright, thanks for your fast response. @kmova
