### ISSUE TITLE
volume policy should enable user to delete data after corresponding volume is deleted

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1424]
Volume Policy should enable user to mark a volume to be purged of its data once the PV is deleted.

> We have shared kubernetes cluster for many customers. And we implement local pv dynamic provisioning based on LVM. When the local pv is deleted and we want to clear the user data on the LV. Now we use the dd-zero command to  cleanup, but it is so slow, for example when we have a 1000G LV, we need several hours to clean it. How can we speed the dd command? or do we have other method?

Above is a discussion at sig-storage.

**Comment by AmitKumarDas** [comment]
Kubernetes PR that tries to solve this via a Job:
- https://github.com/kubernetes-incubator/external-storage/pull/711/

**Comment by kmova** [comment]
Covered as part of https://github.com/openebs/openebs/issues/1246
