### ISSUE TITLE
Add the way to restore persistent volumes from backup/copy

### ISSUE THREAD

**Issue by michalzxc** [openebs/openebs#1426]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - Assuming I have backup of  /var/openebs/ from nodes I would like to be able to restore persistent volumes after kubernetes cluster redeployment making sure at the same time that existing PVs will be claimed by pods in new cluster

On slack @kiranmova suggested using uuid:
 'the usecase for "If I would just backup storage directory and restore it on new cluster would persistent storage be claimed the same way, or it would just create new volumens?" is something that we could easily implement by adding an an annotation in the PVC with the directory details (the directory to be used instead of generating a new directory based on the volume uuid.) Would you like to put in an issue for this and we will discuss the implementation for this in the issue.'

**What happened**:
Investigating possibility of restoring PV after cluster redeployment (because it can fail, or be replaced with new version)

**What you expected to happen**:
n/a

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:
n/a

**Comment by AmitKumarDas** [comment]
Similar stuff in Kubernetes storage:
- https://github.com/kubernetes/kubernetes/issues/48677
