### ISSUE TITLE
Store imported pool-volume names locally

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#1429]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

The pool/volume imported should need to be stored in CStorPool controller and checked if a volumereplica event comes. This is to differentiate imported pool-vol and user trying to create a volume that is already present(duplication).

Reference:
#1366
https://docs.google.com/presentation/d/14pvUbfLG4wE8_NFI7uWOo8rdkqpt5eBh1N3djtASln0/edit#slide=id.p

**Comment by muratkars** [comment]
Is the solution merged @gkGaneshR? Can we close this?
