### ISSUE TITLE
Update openebs helm installation configurable parameters 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1445]
OpenEBS helm documentation is a bit out of date from the openebs charts from kubernetes/stable in terms of the parameters that can configured. 

openebs helm documentation:
https://docs.openebs.io/docs/next/installation.html#helm

kubernetes/stable openebs charts documentation
https://github.com/kubernetes/charts/tree/master/stable/openebs

Also review this document for typos -- like "stable" is spelt as "table"

Documentation can be edited by clicking on the "Edit" button on top of the changes and following the github PR flow.

**Comment by utkarsh2102** [comment]
Hi @kmova,
Even though the PR for this issue has been duly submitted and merged, the [openebs helm documentation](https://docs.openebs.io/docs/next/installation.html#helm) still seems to have some periods missing and the position of the chart seems to be incorrect when viewed.
How about I make the required changes by editing the changes in the above document? 
CC: @NisantaSahoo

**Comment by kmova** [comment]
sounds good @utkarsh2102, please feel free to go ahead and make the improvements.

**Comment by utkarsh2102** [comment]
Sure. Would submit a PR by EOD :)

**Comment by utkarsh2102** [comment]
@kmova, 
A PR has been made for the issue discussed above.
Kindly check the same.

**Comment by muratkars** [comment]
Instructions are updated with 0.6 release and original PR closed.
