### ISSUE TITLE
Enhance openebs-provisioner to support file-system other then Ext4

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#1454]
FEATURE REQUEST

**What happened**:
Openebs provisioner supports ext4 as default fstype for provisioning  openebs volume.
But for some application for example MongoDB, they strongly recommended to run on XFS.
https://docs.mongodb.com/manual/administration/production-notes/#mongodb-on-linux

> When running MongoDB in production on Linux, you should use Linux kernel version 2.6.36 or later, with either the XFS or EXT4 filesystem. If possible, use XFS as it generally performs better with MongoDB.
> 
> With the WiredTiger storage engine, using XFS is strongly recommended for data bearing nodes to avoid performance issues that may occur when using EXT4 with WiredTiger.
> 

**What you expected to happen**:
SystemAdmin should be able to change the supported fstype and benchmark it.

**Comment by ksatchit** [comment]
Fixed via https://github.com/openebs/external-storage/pull/38
