### ISSUE TITLE
Application data recovery steps from troubleshooting guide fails with XFS-based volumes 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1460]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

**What happened**:

- Node failures on a multi-node cluster caused applications using xfs-formatted openebs volumes to enter error states (CrashLoopBackOff) 

- The troubleshooting steps (available here: https://docs.openebs.io/docs/next/tsgpvs.html#CrashLoopBackOff) were attempted, but failed with following logs on the node (Step 6), leading to data unavailability. 

```

Events:
  Type     Reason                 Age                 From                 Message
  ----     ------                 ----                ----                 -------
  Normal   Scheduled              10m                 default-scheduler    Successfully assigned percona-5d9f64df78-gf5kn to mayahost02
  Normal   SuccessfulMountVolume  10m                 kubelet, mayahost02  MountVolume.SetUp succeeded for volume "default-token-z5k9s"
  Warning  FailedAttachVolume     10m (x25 over 10m)  attachdetach         Multi-Attach error for volume "pvc-b93689b2-52b8-11e8-8040-000c298ff5fc" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount            1m (x4 over 8m)     kubelet, mayahost02  Unable to mount volumes for pod "percona-5d9f64df78-gf5kn_default(f2d3687b-52bc-11e8-8040-000c298ff5fc)": timeout expired waiting for volumes to attach/mount for pod "default"/"percona-5d9f64df78-gf5kn". list of unattached/unmounted volumes=[mysql-snap]
  Warning  FailedSync             1m (x4 over 8m)     kubelet, mayahost02  Error syncing pod
```
```
May  8 18:22:51 MayaHost02 kubelet[857]: E0508 18:22:51.946635     857 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/iscsi/10.108.136.102:3260:iqn.2016-09.com.openebs.jiva:pvc-b93689b2-52b8-11e8-8040-000c298ff5fc:0\"" failed. No retries permitted until 2018-05-08 18:24:53.946594935 +0530 IST (durationBeforeRetry 2m2s). Error: MountVolume.WaitForAttach failed for volume "pvc-b93689b2-52b8-11e8-8040-000c298ff5fc" (UniqueName: "kubernetes.io/iscsi/10.108.136.102:3260:iqn.2016-09.com.openebs.jiva:pvc-b93689b2-52b8-11e8-8040-000c298ff5fc:0") pod "percona-5d9f64df78-gf5kn" (UID: "f2d3687b-52bc-11e8-8040-000c298ff5fc") : mount failed: exit status 32
May  8 18:22:51 MayaHost02 kubelet[857]: Mounting command: systemd-run
May  8 18:22:51 MayaHost02 kubelet[857]: Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.108.136.102:3260-iqn.2016-09.com.openebs.jiva:pvc-b93689b2-52b8-11e8-8040-000c298ff5fc-lun-0 --scope -- mount -t xfs -o defaults /dev/disk/by-path/ip-10.108.136.102:3260-iscsi-iqn.2016-09.com.openebs.jiva:pvc-b93689b2-52b8-11e8-8040-000c298ff5fc-lun-0 /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.108.136.102:3260-iqn.2016-09.com.openebs.jiva:pvc-b93689b2-52b8-11e8-8040-000c298ff5fc-lun-0
May  8 18:22:51 MayaHost02 kubelet[857]: Output: Running scope as unit run-rf00e17fe4915470d8de36dc37b2e8658.scope.
May  8 18:22:51 MayaHost02 kubelet[857]: mount: wrong fs type, bad option, bad superblock on /dev/sdc,
May  8 18:22:51 MayaHost02 kubelet[857]:        missing codepage or helper program, or other error
May  8 18:22:51 MayaHost02 kubelet[857]:        In some cases useful info is found in syslog - try
May  8 18:22:51 MayaHost02 kubelet[857]:        dmesg | tail or so.
```

**What you expected to happen**:

- Steps in the troubleshooting guide should successfully retrieve application data & place it in running state.

**How to reproduce it (as minimally and precisely as possible)**:

- Perform node failures OR volume replica failures with active load on the application

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Potential alternate recovery steps include :+1: 
- Unmount filesystem
- Perform `xfs_repair <filesystem_location` on the SCSI device where fs is located 
- If errors are fixed/no more errors are found, remount fs and restart application

**Comment by vishnuitta** [comment]
Steps as below seems to be working fine:
- Unmount k8s filesystem
- Mount the disk to a new directory
- Unmount the disk
- xfs_repair <device>
This fixes if any issues. Mount in step 2 is required to replay any pending logs.
One issue noticed is:
With step 1, application pod uses local directory of the node as mount point and gets into running state.
To make application pod to use the iSCSI disk, delete of application pod can be done. But, this leaves application pod in ContainerCreating state until the local directories at the k8s mount points are deleted.

**Comment by ksatchit** [comment]
Thanks @vishnuitta . Confirmed the above steps with few more trials. A few points to note: 

- The device unmount on the node may be need to be performed at multiple locations `/var/lib/kubelet/plugin/kubernetes.io/iscsi/<..> & /var/lib/kubelet/pods/<pod_id>/volumes/kubernetes.io~iscsi/<pvc-id>` (and sometimes, duplicate mounts of these. Check /proc/mounts for a list of all volume mount points). 

  Until the device is unmounted from all points:

  - xfs_repair fails w/ `ERROR: The filesystem has valuable metadata changes in a log`
  - App pod continues to stay in CrashLoopBackOff state. Once unmounted, it obtains this error: `lstat /var/lib/kubelet/pods/a94d026f-1408-11e9-a09b-02b983f0a4db/volumes/kubernetes.io~iscsi/pvc-a94562c8-1408-11e9-a09b-02b983f0a4db: input/output error` & enters running state uses the local directory at the same path

- The app delete post xfs_repair may also get stuck at `Terminating` until the pvc-folder is removed from the local directory.
