### ISSUE TITLE
mayactl should be available as a CLI command outside the m-apiserver pod 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1463]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Currently, the mayactl CLI is only available inside the m-apiserver pod. However, consider these following issues/feature requests: 

   - https://github.com/openebs/openebs/issues/1209 (Provide volume replica mode details in mayactl)
   - https://github.com/openebs/openebs/issues/1300 (mayactl should show if volume has multiple clients)
   - https://github.com/openebs/openebs/issues/1358 (mayactl should list application pods using an openebs volume) 
   - https://github.com/openebs/openebs/issues/1359 (mayactl should to provide node/disk used by openebs volume)
   - https://github.com/openebs/openebs/issues/1435 (mayactl CLI command to resize iSCSI volume) 
 
- Essentially, the developers/admins would tend to execute these on the control nodes/deployment harness machines as part of debug operations rather than exec into the pod to run them. 

**What you expected to happen**:

- mayactl should be available as CLI on the lines of kubectl 

**Anything else we need to know?**:

- Ex usage would be something like below:  `mayactl --apiserver=http://apiserverIP:5656 <cmd> ` 
- There may be conflicting capabilities like resize PV, or snap creation etc., - which will need to be handled.

**Comment by sonasingh46** [comment]
What I can understand from the above issue is : 
1. If mayactl needs to be available somewhere outside the maya api server pod then there must be a middleware live on that somewhere context that can really understand the mayactl and forward the request to maya server.
I dont think writing any code for maya server would help that.
Or
2. Do we want mayactl to be understood by k8s itself so as to forward the request to maya server? ( Meaning PR to k8s!!)
Or
3. Do we want to expose the api server outside the pod? (The best option.)
Please correct me if I am wrong or provide some comments to understand if it means something different.

**Comment by prateekpandey14** [comment]
@sonasingh46 best option : add the `apiserver` flag which will have maya-apiserver address  for example `mayactl --apiserver=http://apiserverIP:5656 <cmd>`

**Comment by sonasingh46** [comment]
@prateekpandey14 
But how does mayactl execute...
For example to use kubectl CLI  we should have the kubectl binary which then in turns communicates to the API.
We will be needing mayactl binary to execute, right?

**Comment by ashishranjan738** [comment]
mayactl should automatically get the mapi address if running anywhere inside the cluster . I want to work n that .
cc: @kmova @prateekpandey14 @AmitKumarDas .

**Comment by muratkars** [comment]
@sonasingh46 @ksatchit looks like `apiserver` flag solution wasn't merged. Is there another way to access mayactl? [Docs](https://docs.openebs.io/mayactl.html) still refer to locally accessing to maya-apiserver.
