### ISSUE TITLE
Add flag in maya-exporter to use cstor as storage engine.

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#1466]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:
maya-exporter does not support cstor as of now.
**What you expected to happen**:
maya-exporter should have options to select the storage engines according to their choice from command line.
- `./maya-exporter -e=cstor`
**How to reproduce it (as minimally and precisely as possible)**:
* `./maya-exporter --help` 

**Anything else we need to know?**:
no

**Comment by muratkars** [comment]
Merged
