### ISSUE TITLE
Fix Mix-Indent 

### ISSUE THREAD

**Issue by vipulgupta2048** [openebs/openebs#1474]
## BUG REPORT: Fix mix-indentation in openebs/k8s/lib/vagrant/test/k8s/1.6/Vagrantfile
**What happened**:
Refer to open issue #312 , this is a branch issue to fix mix indentation specifically for openebs/k8s/lib/vagrant/test/k8s/1.6/Vagrantfile, as part of #summerhack contribution.

**What you expected to happen:**
I will review the file and standardize indentation to 2 tabs.

**How to reproduce it (as minimally and precisely as possible)**:
Current file with mix indent: openebs/k8s/lib/vagrant/test/k8s/1.6/Vagrantfile

**Comment by sachinmukherjee** [comment]
Is this issue is open?

**Comment by vipulgupta2048** [comment]
@sachinmukherjee No, as you the PR related to them have already been merged. Closing it.
