### ISSUE TITLE
When deleting the pvc, I found that 4 new pods are created. And there is some err information in these new pods log! 

### ISSUE THREAD

**Issue by Danfeng-Wang** [openebs/openebs#1478]
**When deleting the pvc, I found that 4 new pods are created. And there is some err information in these new pods log!** 
@kmova 
**issue describe:**
1、 I created a pvc like this: 

_- 1. kind: PersistentVolumeClaim
- 2. apiVersion: v1
- 3. metadata:
- 4.   name: openebstest-claim
- 5.   annotations:
- 6.     volume.beta.kubernetes.io/storage-class: openebs-standard
- 7. spec:
- 8.   accessModes:
- 9.     - ReadWriteOnce
- 10.   resources:
- 11.     requests:
- 12.       storage: 20G_
- 

	  
	  
2、when I deleted the pvc , 4 new pods were created:

[root@localhost openebs]# kubectl get pod -n wangdanfeng5
_pvc-6885e523-572a-11e8-87e6-ac1f6b262706-ctrl-5547db7bdb-wkx98   2/2       Running   0          1m
pvc-6885e523-572a-11e8-87e6-ac1f6b262706-rep-b6c5db669-46b87     1/1       Running   0          1m
pvc-6885e523-572a-11e8-87e6-ac1f6b262706-rep-b6c5db669-5jk2c     1/1       Running   0          1m
pvc-6885e523-572a-11e8-87e6-ac1f6b262706-rep-b6c5db669-lcd5q     1/1       Running   0          1m_

[root@localhost openebs]# kubectl logs pvc-6885e523-572a-11e8-87e6-ac1f6b262706-ctrl-5547db7bdb-wkx98 -n wangdanfeng5
Error from server (BadRequest): a container name must be specified for pod pvc-6885e523-572a-11e8-87e6-ac1f6b262706-ctrl-5547db7bdb-wkx98, 
choose one of: [pvc-6885e523-572a-11e8-87e6-ac1f6b262706-ctrl-con maya-volume-exporter]

_openebs version: 0.5.3, 
Install tools: helm v2.9.0-rc3
OS kernel: 
CentOS Linux release 7.4.1708 (Core)
Linux A01-R20-I36-130-0964485.JD.LOCAL 4.15.11-1.el7.elrepo.x86_64 #1 SMP Mon Mar 19 11:46:06 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux_

If you need more information, pls let me know！

**Comment by Danfeng-Wang** [comment]
Sorry, the pvc yaml is here:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebstest-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: openebs-standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G

**Comment by Danfeng-Wang** [comment]
@amitd
 [root@localhost openebs]# kubectl describe pod registry-pd
Error from server (NotFound): pods "registry-pd" not found
[root@localhost openebs]# kubectl describe pod registry-pd -n wangdanfeng5
Name:         registry-pd
Namespace:    wangdanfeng5
Node:         10.196.36.164/10.196.36.164
Start Time:   Mon, 14 May 2018 14:43:14 +0800
Labels:       <none>
Annotations:  <none>
Status:       Running
IP:           20.0.213.131
Containers:
 test-container:
   Container ID:  docker://02f066e572cb2a31705d4f5ff6cb094d10b6250cb3c20826791fd24b43366fa9
   Image:         mirror.jd.com/ovs/registry:latest
   Image ID:      docker-pullable://mirror.jd.com/ovs/registry@sha256:3dc174da5caa90193d5789b6a43ba52c781bd4fd0e33d36741855c1298017a1f
   Port:          <none>
   Host Port:     <none>
   Command:
     sleep
   Args:
     99999d
   State:          Running
     Started:      Mon, 14 May 2018 14:43:40 +0800
   Ready:          True
   Restart Count:  0
   Environment:    <none>
   Mounts:
     /mnt from openebs-pvc (rw)
     /var/run/secrets/kubernetes.io/serviceaccount from default-token-g9944 (ro)
Conditions:
 Type           Status
 Initialized    True
 Ready          True
 PodScheduled   True 
Volumes:
 openebs-pvc:
   Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
   ClaimName:  openebstest-claim
   ReadOnly:   false
 default-token-g9944:
   Type:        Secret (a volume populated by a Secret)
   SecretName:  default-token-g9944
   Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                node.kubernetes.io/unreachable:NoExecute for 300s
Events:
 Type    Reason                 Age   From                    Message
 ----    ------                 ----  ----                    -------
 Normal  Scheduled              55s   default-scheduler       Successfully assigned registry-pd to 10.196.36.164
 Normal  SuccessfulMountVolume  55s   kubelet, 10.196.36.164  MountVolume.SetUp succeeded for volume "default-token-g9944"
 Normal  SuccessfulMountVolume  33s   kubelet, 10.196.36.164  MountVolume.SetUp succeeded for volume "pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706"
 Normal  Pulling                32s   kubelet, 10.196.36.164  pulling image "mirror.jd.com/ovs/registry:latest"
 Normal  Pulled                 30s   kubelet, 10.196.36.164  Successfully pulled image "mirror.jd.com/ovs/registry:latest"
 Normal  Created                30s   kubelet, 10.196.36.164  Created container
 Normal  Started                29s   kubelet, 10.196.36.164  Started container

**Comment by AmitKumarDas** [comment]
These are the additional info from @Danfeng-Wang env:

```bash
[root@localhost openebs]# kubectl get pod -n openebs
NAME                                                   READY     STATUS    RESTARTS   AGE
openebs-wdf3-openebs-grafana-5d765d6865-6n7kk          1/1       Running   0          4d
openebs-wdf3-openebs-maya-apiserver-577c7664d5-2vxhp   1/1       Running   0          4d
openebs-wdf3-openebs-maya-apiserver-577c7664d5-6pl8k   1/1       Running   0          4d
openebs-wdf3-openebs-prometheus-bfd7b8b89-vbdth        1/1       Running   0          4d
openebs-wdf3-openebs-provisioner-67cf9c7f44-445ww      1/1       Running   0          4d
openebs-wdf3-openebs-provisioner-67cf9c7f44-wll8m      1/1       Running   0          4d
```
```bash
[root@localhost openebs]# kubectl get pods -n wangdanfeng5
NAME                                                             READY     STATUS    RESTARTS   AGE
pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706-ctrl-869955469b-mmq9l   2/2       Running   0          7m
pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706-rep-56c9c748c5-h2n5p    1/1       Running   0          7m
pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706-rep-56c9c748c5-lbpzf    1/1       Running   0          7m
pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706-rep-56c9c748c5-xtnc6    1/1       Running   0          7m
````
These pods are created after the pvc is deleted.

**Comment by Danfeng-Wang** [comment]
maya api server logs:
461a462,473
> 2018/05/14 07:03:23.041896 [DEBUG] http: Request /latest/volumes/delete/pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706 (GET)
> [DEBUG] Processing GET request
> I0514 07:03:23.041945       7 volume_endpoint.go:196] Processing Volume delete request
> I0514 07:03:23.042017       7 util.go:1205] Will use env var 'DEFAULT_PVP_NAME: '
> I0514 07:03:23.042036       7 jiva.go:56] Building new instance of jiva persistent volume provisioner 'volumeprovisioner.mapi.openebs.io/name:jiva'
> I0514 07:03:23.042071       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_NAME: '
> I0514 07:03:23.042086       7 k8s.go:59] Building 'orchprovider.mapi.openebs.io/name':'kubernetes' orchestration provider
> I0514 07:03:23.042137       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
> I0514 07:03:23.043969       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
> I0514 07:03:23.045427       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
> I0514 07:03:23.691660       7 volume_endpoint.go:255] Processed Volume delete request successfully for 'pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706'
> 2018/05/14 07:03:23.691749 [DEBUG] http: Request /latest/volumes/delete/pvc-05fc2a20-5742-11e8-87e6-ac1f6b262706 (649.863414ms)

**Comment by Danfeng-Wang** [comment]
For your information, amit!



Neo!


2018-05-14 15:26 GMT+08:00 Amit Kumar Das <notifications@github.com>:
