### ISSUE TITLE
Typo in install openebs using helm charts document.

### ISSUE THREAD

**Issue by Swarnalatha-K** [openebs/openebs#1487]
**What happened**:
Instead of stable/openebs table/openebs is specified in the below command in openebs helm installation document.
helm install -f values.yaml table/openebs --name openebs --namespace openebs

**What you expected to happen**:
specify stable in helm install command.
helm install -f values.yaml stable/openebs --name openebs --namespace openebs

https://docs.openebs.io/docs/next/installation.html

**Comment by swetax** [comment]
@Swarnalatha-K I went through https://docs.openebs.io/docs/next/installation.html and found some typos apart from the one mentioned here. Can you please assign this to me ?

**Comment by muratkars** [comment]
Looks like issue in [docs](https://docs.openebs.io/docs/next/installation.html) was resolved.
