### ISSUE TITLE
Add "openebs.io/fstype:ext4" as default entry in storage class

### ISSUE THREAD

**Issue by ranjithwingrider** [openebs/openebs#1495]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG 
 
If this is a BUG REPORT, please:
From 0.5.4 onwards, introduced xfs  also a supported fstype. By default it is ext4. So we should now put "openebs.io/fstype:ext4" in the storage class yaml  as a default entry. And put the supported fstypes in the documentation also.

**What happened**:
Since we are supporting multiple fstype in OpenEBS, we should make an entry "openebs.io/fstype:ext4" as a default value in storage class.

**What you expected to happen**:
As a best practise, we should give default fstype entry in storage class yaml.

**Comment by devshiva619** [comment]
@ranjithwingrider Hey I would like work on this.
