### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rupeshiya** [openebs/openebs#1496]
## FEATURE REQUEST
In CONTRIBUTING.md instead of "Open Source" ,it is written like "OpenSource".

**What happened**:
In CONTRIBUTING.md ,"Open Source" is written like "OpenSource".

**What you expected to happen**:
It should be like "Open Source".
**How to reproduce it (as minimally and precisely as possible)**:
Just updation  is required.

**Comment by Rupeshiya** [comment]
@utkarshmani1997  Please review #1497

**Comment by Rupeshiya** [comment]
@NisantaSahoo  please review this #1497

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997 I have fixed this issue and many other issues in relation to the contribution docs in my PR #1511
