### ISSUE TITLE
Typing errors in CONTRIBUTING-TO-DEVELOPER-DOC.md  file

### ISSUE THREAD

**Issue by sachinmukherjee** [openebs/openebs#1498]
BUG REPORT

**What happened**: There are some tying error in CONTRIBUTING-TO-DEVELOPER-DOC.md file which resides inside the directory contribute. Few periods are missing at the end of the sentences and some unecessary periods are given in the heading section.

**What you expected to happen**: Remove those which are unecessary and add those which are required.

**Comment by RajatGarg97** [comment]
Hi guys
I am on this issue.

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997 I have fixed this issue and many other issues in relation to the contribution docs in my PR #1511

**Comment by sambhav2612** [comment]
Refer #1598
