### ISSUE TITLE
Evaluate the K8s volume drivers for connecting to OpenEBS volumes. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#15]
Related Issue - #14 

This issue is to track the pros/cons of using the different implementation options for connecting the OpenEBS storage to K8s.

- Custom/New Driver
- Flex Volume Driver
- EBS Driver

The preference is to re-use the existing driver (optionally, by adding a adapter on the maya api server).

**Comment by akashshah26595** [comment]
I'm going through FlexVolume documentation on https://github.com/akashshah26595/kubernetes/tree/master/examples/volumes/flexvolume

**Comment by kmova** [comment]
EBS Driver is tightly coupled with the aws-sdk. FlexVolume provides the required options for adding new storage vendor easily.
