### ISSUE TITLE
Remove the dependency of vagrant-triggers plugin for the Vagrantfiles

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#1502]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
ENHANCEMENT

The current Vagrantfiles rely on the vagrant-triggers plugin to perform some operations during the bootup of the VM instances. As of version 2.1.0 and above of vagrant, the triggers feature is integrated into the core of vagrant. The enhancement would be update the code to work with vagrant core trigger provision instead of the plugin and remove the dependency of the vagrant-triggers plugin.

**What happened**:
Vagrant 2.1.0 and above throws a warning stating to remove vagrant-triggers plugin as the triggers feature is now added as part of the core vagrant.
**What you expected to happen**:
Make necessary code changes to the Vagrantfiles and make it use the triggers feature from the core vagrant.
**How to reproduce it (as minimally and precisely as possible)**:
Install vagrant
Use our Vagrantfile
Run some vagrant command
vagrant installs the vagrant-triggers plugin and throws a warning about having the triggers feature added to the vagrant core features.
**Anything else we need to know?**:

**Comment by sachinmukherjee** [comment]
@yudaykiran please tell me which file i have to change and what changes should I make?

**Comment by yudaykiran** [comment]
@sachinmukherjee , it is applicable to all the vagrant files under https://github.com/openebs/openebs/tree/master/k8s/vagrant directory. If you can make it work for one file then you can reuse the same changes for the other files too.

**Comment by surana-mudit** [comment]
@yudaykiran, I want to work on this issue and I think that by removing "vagrant-triggers" from the following line, the issue will be resolved. Am i right? Should I go ahead with this.

required_plugins = %w(vagrant-cachier vagrant-triggers)

**Comment by yudaykiran** [comment]
@surana-mudit , I am not sure if removing just:

required_plugins = %w(vagrant-cachier vagrant-triggers)

will fix the problem, but you can go ahead and try it out, but make sure the code works the same way before and after removing dependency. Untested code will not be accepted.

**Comment by ashishranjan738** [comment]
I want to work on this issue

**Comment by yudaykiran** [comment]
@ashishranjan738 , sure you can take it up. Please raise a PR.

**Comment by RajatVaryani** [comment]
@ashishranjan738 Are you working in this issue? If not, I would love to contribute.
