### ISSUE TITLE
typing error in gokit.md file

### ISSUE THREAD

**Issue by sachinmukherjee** [openebs/openebs#1516]
BUG REPORT

**What happened**:
Some typing error in gokit.md file which resides under the directory `/documentation/techbits/gokit.md`. Current scenario `maya-apiserver` should be changed to `maya-api-server`.

**What you expected to happen**:
Add missing hyphens between `api` and `server`.

**Comment by kmova** [comment]
The software component is called - maya-apiserver or m-apiserver. This is not a typo.
