### ISSUE TITLE
typing error in quick-start-with-vim-go.md file

### ISSUE THREAD

**Issue by sachinmukherjee** [openebs/openebs#1518]
BUG REPORT

**What happened**:
- Inappropriate heading tags in quick-start-with-vim-go.md file which resides inside the directory `documentation/techbits/`. Current scenario most of the heading tags are `##` it should be changes to `###` to maintain the flow.

**What you expected to happen**: 
Replace the`##` with `###` heading tags.

**Comment by sachinmukherjee** [comment]
@utkarshmani1997 please review

**Comment by kmova** [comment]
@sachinmukherjee - can you please verify and close this issue if #1511 has made the expected changes.

**Comment by utkarsh2102** [comment]
Is it still open?
@kmova, can I take this up?

**Comment by utkarsh2102** [comment]
@NisantaSahoo @kmova, is the issue still open?
If yes, can I take up the task?

**Comment by kmova** [comment]
@utkarsh2102 .. Can you post on the above PR requesting to take this up. You can wait for a day for them to respond and take it up.

**Comment by utkarsh2102** [comment]
Sure, would do as asked :)
