### ISSUE TITLE
Maya travis builds should push branch specific "ci" images 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1555]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

- Currently, the travis builds for the `openebs/maya` repository push images (m-apiserver, m-exporter etc.,) with "ci" tag from all branches (mainly v0.5 & master - which are the functional branches). 

**What you expected to happen**:

- We need to push branch-specific ci images. `image:ci` should be dedicated for the master while `image:branch-ci` can be used for other release branches. 

**How to reproduce it (as minimally and precisely as possible)**:

This is seen at : https://github.com/openebs/maya/blob/v0.5.0/GNUmakefile

**Anything else we need to know?**:

Above changes have to be supplemented with :  e2e code maintenance in the branches also has to be done according to the feature - with jenkins CI maintaining a separate job for e2e of individual branches. Currently, the "ci" builds pushed from 0.5 branch fails due to tests that use "mayactl" instead of "maya".

**Comment by prateekpandey14** [comment]
Travis CI pushes the ci taged images for `master branch` and `<branch-name>-ci` tag images for branch specific builds
