### ISSUE TITLE
So much documentation inside k8s

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#157]
There is so much documentation within openebs/k8s.
The way these docs are arranged are different in each sub-folder of openebs/k8s.
This leads to confusion.

These are some of the questions that comes to my mind:
- Are all these .md files required ?
- Can k8s sub-folders have .yaml files with appropriate (maybe extensive) comments
  - This is more in tune with eliminate the docs
  - Probably generate docs from these comments when required
- Need to choose either .json or .yaml & definitely not both
- How does the yaml/json deal with different versions of K8s & OpenEBS ?
  - Should it rely on git version/tag ?

**Comment by kmova** [comment]
I have been experimenting with ways in which the theme can be customized. If we continue to host this on the read-the-docs, there is a hard limit on only one css being assigned to the pages - either the one provided by the them or the one provided via the html context. Having to duplicate the entire css and maintaining it will involve a huge effort. Still trying to find ways in which only parts of the css can be over-ridden.

**Comment by satyamz** [comment]
@kmova  Do we really want to go ahead with read-the-docs?

**Comment by kmova** [comment]
@satyamz -- what are the other alternatives, we can use this issue to evaluate the different options.

**Comment by kmova** [comment]
For now, 
- the user documentation is all being moved to [openebs/documentation](https://github.com/openebs/openebs/tree/master/documentation) which uses [readthedocs](http://openebs.readthedocs.io/en/latest/). 
- the developer documentation is being moved to : [openebs/contribute](https://github.com/openebs/openebs/tree/master/contribute)

Closing this bug. Further work will be carried on with:
- https://github.com/openebs/openebs/issues/563 is used to track the deletion/consolidation of the user documentation 
- https://github.com/openebs/openebs/issues/567 is used to move the e2e related developer documentation to openebs/contribute.
