### ISSUE TITLE
CI overview diagram doesn't show 

### ISSUE THREAD

**Issue by debck** [openebs/openebs#1571]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT 

**What happened**:
  The openebs CI overview workflow image ( here : https://github.com/openebs/openebs/blob/master/contribute/CONTRIBUTING-TO-CI-AND-E2E.md ) does not open.  
**What you expected to happen**:
It should show the proper image.
**How to reproduce it (as minimally and precisely as possible)**:
Just updation of URL.

**Anything else we need to know?**:
  The image is:

![error](https://user-images.githubusercontent.com/33368759/40840569-e743ca64-65c4-11e8-8c5a-597da7b12180.png)

**Comment by muratkars** [comment]
Diagram is fixed and issue resolved
