### ISSUE TITLE
migration path for moving from openebs/charts to kubernetes/stable chart

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1573]
OpenEBS can now be installed with kubernetes stable/openebs helm charts. In near future, we would like to deprecate the openebs/charts repository and just make use of the stable/openebs helm chart. During this deprecation, there has to be a clear documented migration steps for user to move towards stable/openebs charts.

**Comment by muratkars** [comment]
Latest OpenEBS Helm charts are now available under [Helm/stable repo](https://github.com/helm/charts/tree/master/stable/openebs)
