### ISSUE TITLE
Moving documentation from openebs/k8s to openebs/Documentation 

### ISSUE THREAD

**Issue by omi10859** [openebs/openebs#1577]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

**What happened**: Moving documentation from openebs/k8s to openebs/Documentation the commit made to this folder are picked up by readthedocs and hosted https://docs.openebs.io

**Anything else we need to know?**: more information: https://github.com/openebs/openebs/issues/563

**Files needed to be moved**: I will keep commenting on this issue about all the files which are needed to be moved after checking if they are not already moved.

**Comment by muratkars** [comment]
Moved under [https://github.com/openebs/openebs-docs](https://github.com/openebs/openebs-docs)
