### ISSUE TITLE
Can there be an easy way to fetch openebs-operators once the vagrant based K8s setup is up

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#158]

**Comment by ksatchit** [comment]
FYI: The Vagrantfiles here https://github.com/openebs/openebs/tree/master/k8s/vagrant bring up the K8s cluster of desired version. The OpenEBS CI applies the operator on this cluster using kubectl or helm using these ansible roles: 

- https://github.com/openebs/openebs/tree/master/e2e/ansible/roles/k8s-openebs-operator
- https://github.com/openebs/openebs/tree/master/e2e/ansible/roles/k8s-openebs-operator-helm

These fetch the operator yaml files located here: 

- https://github.com/openebs/openebs/blob/master/k8s/openebs-operator.yaml
- https://github.com/openebs/openebs/blob/master/k8s/openebs-storageclasses.yaml

Or helm charts from here : https://openebs.github.io/charts/

If it is desired for the vagrantfiles to come up/instantiate **with** the OpenEBS deployments, *Vagrant triggers* can be used to achieve the same: 

- http://www.rubydoc.info/gems/vagrant-triggers/0.2.1
- https://github.com/emyl/vagrant-triggers
