### ISSUE TITLE
UT - pkg/task/meta_test.go

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#1585]
Write Go Unit test for methods/functions in https://github.com/openebs/maya/blob/master/pkg/task/meta.go file
Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)
[Table Driven testing](
https://github.com/golang/go/wiki/TableDrivenTests)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **master** branch and once done raise a PR against the same.
3. Don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by Akash4927** [comment]
Join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/) for more information and help on this.
