### ISSUE TITLE
Automate the setting up of K8s cluster with OpenEBS on Cloud

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#159]
This issue is to track the development of an automation script (ansible or terraform) that can provision an k8s cluster on the preferred cloud vendor and enable openebs-operator on that cluster. This would require automating the following:
- granting of admin privileges to create openebs user
- launch openebs-operator
- install iscsi-initiator on minion nodes. 

The manual steps are detailed here:
https://github.com/openebs/openebs/blob/master/k8s/hyperconverged/tutorial-configure-openebs-gke.md

**Comment by muratkars** [comment]
This solution will be same as #158
