### ISSUE TITLE
Include the VSM template into the k8s-demo that can be made accessible from the openebs master.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#16]
The Vagrantfile must be able to create a VSM with a job file that will be run after the OpenEBS hosts have been created. This VSM should be later available for the K8s pods to use them.

**Comment by kmova** [comment]
It would suffice to ship an valid VSM spec file along with the demo. 

Once the setup is up, operator should be able to ssh into the openebs master and run the maya vsm-create with the shipped vsm spec file.

**Comment by yudaykiran** [comment]
The demo-vsm files that we have, create 1 frontend and 2 backend containers. All containers are created on the same host, do we have to make changes to template so that it spawns the 2nd backend container on a new host?
If we do, we will require 2 maya hosts.

**Comment by prateekpandey14** [comment]
Now vsm-spec file is part of the k8s-demo.
