### ISSUE TITLE
executable not found in path

### ISSUE THREAD

**Issue by maikotz** [openebs/openebs#160]
Hi, 

I was looking into openEBS again and thought I'll give 0.3 RC3 a try but on my coreOS k8s 1.6.6 cluster I can't get it to work. 

The Operator actually works and provisions the volumes but the containers can't mount them. 

Do I still need something else like the openebs flexvolume plugin? Or could this have something to do with my internal network being on eno2 instead on eno1 / eth0 ? 

The message I get is: 
```
Jul 12 18:22:14 n-10-10-23-50 kubelet-wrapper[2794]: E0712 18:22:14.525238    2794 iscsi_util.go:148] iscsi: could not read iface eno2 error:
Jul 12 18:22:14 n-10-10-23-50 kubelet-wrapper[2794]: E0712 18:22:14.525251    2794 disk_manager.go:50] failed to attach disk
Jul 12 18:22:14 n-10-10-23-50 kubelet-wrapper[2794]: E0712 18:22:14.525254    2794 iscsi.go:228] iscsi: failed to setup
Jul 12 18:22:14 n-10-10-23-50 kubelet-wrapper[2794]: E0712 18:22:14.525313    2794 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/iscsi/0545ce16-672f-11e7-9821-246e961c36a8-pvc-3e33a316-6727-11e7-9821-246e961c36a8\" (\"0545ce16-672f-11e7-9821-246e961c36a8\")" failed. No retries permitted until 2017-07-12 18:22:18.525296774 +0000 UTC (durationBeforeRetry 4s). Error: MountVolume.SetUp failed for volume "kubernetes.io/iscsi/0545ce16-672f-11e7-9821-246e961c36a8-pvc-3e33a316-6727-11e7-9821-246e961c36a8" (spec.Name: "pvc-3e33a316-6727-11e7-9821-246e961c36a8") pod "0545ce16-672f-11e7-9821-246e961c36a8" (UID: "0545ce16-672f-11e7-9821-246e961c36a8") with: executable file not found in $PATH
```

Hope someone could help me out here.

Thanks

**Comment by kmova** [comment]
@maikotz thank you for trying OpenEBS. 

you don't need the flexvolume plugin anymore with 0.3-RC3. 

However, the volumes are exposed via iSCSI and we would require the kubelet to connect to the volumes using iSCSI initiator. The error messages point towards the minion nodes not have the iscsi initiator installed. On my Google cloud setup, on the minion nodes, I had to do the following to get iscsi installed and volumes to work.

```
sudo apt-get update
sudo apt-get install open-iscsi
sudo service open-iscsi restart
```

Can you get iSCSI initiator installed on the core-os minion nodes?

**Comment by maikotz** [comment]
Thanks for your reply @kmova 

That pushed me in the right direction, I followed the CoreOS documentation and added iscsiadm and iscsid to the kubelet-wrapper script, don't know if the latter is really necessary but it's working now. 

```
          --volume iscsiadm,kind=host,source=/usr/sbin/iscsiadm \
          --mount volume=iscsiadm,target=/usr/sbin/iscsiadm \
          --volume etc-scsi,kind=host,source=/etc/iscsi/ \
          --mount volume=etc-scsi,target=/etc/iscsi \
          --volume iscsid,kind=host,source=/usr/sbin/iscsid \
          --mount volume=iscsid,target=/usr/sbin/iscsid \
```

**Comment by kmova** [comment]
Thank you @maikotz for posting the details for fixing on coreos.

**Comment by yudaykiran** [comment]
@maikotz did you use docker or rkt for the containers? Did you use Tectonic or some other tool to bring up your Kubernetes cluster?
