### ISSUE TITLE
Replica not registering with controller after sudden node restart

### ISSUE THREAD

**Issue by rgembalik** [openebs/openebs#1611]
## BUG REPORT
 

**What happened**:
After sudden node resteart some of my pvc replicas cannot connect to controller. 
One case (I left it for scientific purposes) won't listen on 3260 on controller. No errors are shown as of why that's the case. Replica has mounted `hostPath` and it is running on the same node. 

**What you expected to happen**:
After such restart replica should recover, or I should be able at least to see what is wrong with my pvc.

**How to reproduce it (as minimally and precisely as possible)**:
In my case hard restart (connected with power shortage) did it.

**Anything else we need to know?**:
It should be stated, that it's not the pvc I would miss, but I'd like to learn how to debug such cases. I'd be happy for next steps suggestions since I have no clues how to find the source of the problem. 

Also, there is only one replica on this pvc.

Controller logs:
```
STATE = dirty
10.233.87.34 - - [13/Jun/2018:13:49:06 +0000] "POST /v1/register HTTP/1.1" 200 0
STATE = dirty
10.233.87.34 - - [13/Jun/2018:13:49:11 +0000] "POST /v1/register HTTP/1.1" 200 0
STATE = dirty
10.233.87.34 - - [13/Jun/2018:13:49:16 +0000] "POST /v1/register HTTP/1.1" 200 0
STATE = dirty
10.233.87.34 - - [13/Jun/2018:13:49:21 +0000] "POST /v1/register HTTP/1.1" 200 0
STATE = dirty
...
```

Replica logs:
```
time="2018-06-13T14:06:12Z" level=info msg="Listening on data 10.233.87.13:9503" 
time="2018-06-13T14:06:12Z" level=info msg="Removing Replica" 
time="2018-06-13T14:06:12Z" level=info msg="Listening on control 10.233.87.13:9502" 
time="2018-06-13T14:06:12Z" level=info msg="Listening on sync 10.233.87.13:9504" 
```

**Comment by kmova** [comment]
@rgembalik - You must be hitting this issue https://github.com/openebs/jiva/pull/45

**Comment by rgembalik** [comment]
@kmova Maybe, but:
* For me restart of a controller (or replica for that matter) didn't do anything
* Controller's 3260 port isn't even listening
* Controller's API responds with an empty array when asked about replicas.

**Comment by kmova** [comment]
3260 gets opened only after a replica register's itself with the controller.

I agree when a replica is restarted, if we can get logs about replica attempting to connect with controller and its status would be good. ( cc @payes )

Just to eliminate the usuals: Can you check the kubectl describe pod <replica pod> to see if its ENV (clusterIP) is pointing to the corresponding kubectl get svc <pvc-..service> ?

**Comment by rgembalik** [comment]
@kmova There are repeating `POST /v1/register` calls on the controller - I'd assume that this is some sort of sign, that the replica tries to call the controller (please correct me if I am wrong). However, I am not sure why this call does not carry through to actually registering the replica.

And yes, the IP is the same in arguments and it points to the ClusterIP of the service, that seats in front of the controller.
