### ISSUE TITLE
One of the replica volume is showing pending status

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#162]
### Problem
I am in vagrant/test/k8s/1.6 directory and after creating the volume it shows volume created successfully but when you run vsm-stats ,it shows vol not reachable.
I checked the pods and one of the replica volume is showing pending status,
I checked the nodes also and they are showing Ready status.
##  Changes i made
Pulled the latest jiva image and changed the tag name from latest to 0.3-RC2
## Screenshot 
Here is the screenshot attached for more details
![screenshot from 2017-07-13 11-30-41](https://user-images.githubusercontent.com/19219723/28152879-4fe46410-67c0-11e7-9214-4c390f0db48b.png)
![screenshot from 2017-07-13 11-31-18](https://user-images.githubusercontent.com/19219723/28152880-4fe5e7f4-67c0-11e7-9f9e-6703b0975e6d.png)

**Comment by utkarshmani1997** [comment]
![screenshot from 2017-07-13 11-59-02](https://user-images.githubusercontent.com/19219723/28153372-afc73306-67c2-11e7-8b63-49e99891ef4c.png)

**Comment by yudaykiran** [comment]
It looks as though the volumes were not created properly, does deleting the pod and launching it again solve the problem? Also it is advisable to have 2 minions running to actually see the HA(high availability) working.

**Comment by utkarshmani1997** [comment]
Yes, actually i also delete the pods, services and deployments  every time whenever i face this issue.looks like if it is a bug?

**Comment by yudaykiran** [comment]
The behavior is if you have only 1 Minion, you should be able to see 1 controller pod and 1 replica pod launched. Your application must be able to use the volume provided by the single replica that was launched. Can you confirm whether your application was able to consume the volume that was provided by that single replica?

**Comment by AmitKumarDas** [comment]
This is a default provisioning feature via maya api server.
It will spread the replica in different minion hosts.

**Comment by utkarshmani1997** [comment]
@yudaykiran , yes it is able to consume the volume. i have tested it with dd command.

**Comment by utkarshmani1997** [comment]
You can close the issue now :)
