### ISSUE TITLE
update github  doc with different vagrant versions installations

### ISSUE THREAD

**Issue by mayavuser** [openebs/openebs#1638]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one:  FEATURE REQUEST

If this is a FEATURE REQUEST, please:
Currently it is installing vagrant version 1.6 . In github repo, we have several vagrant version files are included. Also some of latest OpenEBS features will work from 1.9.1 vagrant version. So we need to include the Vagrant file for 1.9.1 versions also.

**What happened**:
Update vagrant installation to support latest OpenEBS features.

**What you expected to happen**:
Update the doc frequently

**Comment by ashishranjan738** [comment]
@farhaanbukhsh sure go ahead
