### ISSUE TITLE
Improve formatting in README

### ISSUE THREAD

**Issue by DipanshKhandelwal** [openebs/openebs#1642]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT

**What happened**: Formatting is not correct in some parts of [README](https://github.com/openebs/openebs/blob/master/README.md)

**What you expected to happen**: Formatting can be improved in [README](https://github.com/openebs/openebs/blob/master/README.md)

**Comment by muratkars** [comment]
Fixed
