### ISSUE TITLE
Deploy OpenEBS Jiva volume related pods in a user specified namespace

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1661]
As a DevOps Architect, I would like to setup my cluster using OpenShift and designate some of the nodes (node-type=infra-storage) where the Replica pods have to be scheduled. Also another standard configuration in OpenShift is to create namespaces and grant access to some users to create pods in that namespace. The pods launched in the namespaces are scheduled to a specific set of nodes ( node-type=user-loads)

When users launch the pods via OpenShift in their namespace, the replica pods will be launched with the following nodeSelector (node-type=infra-storage) and OpenShift additionally injects the namespace specific label (node-type=user-loads). The combination of these labels will result in Replica pods not finding any node to schedule. 

To support the above configuration, OpenEBS must support taking a "Deploy" namespace where the storage controller/target and replica pods will be scheduled regardless of the namespace where the application pods are created. 

To support the above, the following needs to be done:
- provide an option to specify the namespace for storage ( could be openebs, where the control plane components are launched)
- modify the create - to use the provided namespace instead of pvc namespace
- list, get and delete to have similar changes
- clone and snapshot 
- make changes to mayactl 
- add e2e tests

An alternate configuration option could be provided to check if the following can be done: 
- service and controller/target pod can be in application pod namespace
- replica pods in the openebs namespace tied to storage nodes. 
This requires investigating the feasibility of access the pods across namespaces - target to replica pod. It may be useful to given an option to create all the service/pods

**Comment by kmova** [comment]
The following configuration parameter is being added in 0.6.1 that can be used for environments that prefer to tie a namespace with nodes. 
```
        # (Optional) STORAGE_NAMESPACE allows you to specify a dedicated
        # namespace for deploying OpenEBS Storage Pods for all PVCs.
        # If not specified, the OpenEBS Storage Pods will be will deployed
        # in the corresponding PVC namespace. This option is mainly added
        # for environments like OpenShift that have specific policies (labels)
        # injected into the pods deployed based on the namespace where they
        # are deployed.
        # This is supported for maya api server version 0.6.1 onwards
        #- name: STORAGE_NAMESPACE
        #  value: "openebs-storage"
```

**Comment by fgimenezm** [comment]
was this implemented? I couldn't find any other reference to this setting other than this issue.
I'm also interested in this capability so I can have a shared cluster with more restrictive pod security policies for the users (eg: not allowing hostpath).
If I block hostPath on the user's namespaces then the openebs replicas can't map /var/openebs/.
But if I could run those replicas on a different namespace where hostpath is valid then that would solve my problem.

**Comment by muratkars** [comment]
pinging @kmova for update on the issue.

**Comment by kmova** [comment]
@fgimenezm -- The above has been implemented for cStor Volumes. The cStor target and the pool/replica pods are installed in "openebs" namespace. The example of using the pod-security-policies for cStor volumes is available here: https://github.com/openebs/openebs-docs/issues/484
