### ISSUE TITLE
Mayactl show node status running even if physicaly removing files from /var/openebs

### ISSUE THREAD

**Issue by xpowerman** [openebs/openebs#1680]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**:
I have openebs pvc with replicas on 3 nodes. Mayactl stats show that all replicas of pvc running. After that I physicaly remove files from /var/openebs path on one of nodes for testing purposes. But mayactl stats still show that pvc replica on this pod is running with no errors.
**What you expected to happen**:
Mayactl stats show that one of replicas not running or some error. Or automatically recovery files of pvc on this replica node.
**How to reproduce it (as minimally and precisely as possible)**:
Physicaly delete replica files on one of nodes, and run mayactl volume stats --volname ...

**Comment by kmova** [comment]
This isssue is fixed in the latest release. @utkarsh2102 - can you link to this issue the PRs that handle this errors in Jiva.

**Comment by kmova** [comment]
This need to be handled as part of the health checker for jiva replica pods.
