### ISSUE TITLE
Update the setup-omm routine to set the "DEFAULT_ORCHESTRATOR_NAME" env variable in the profile

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#170]
The setup-omm  command to setup maya-master server in a dedicated-mode openebs deployment needs to be updated to add the DEFAULT_ORCHESTRATOR_NAME (nomad) environment variable in order to work with the latest changes in m-apiserver code.

Currently it adds these two env variables in the user .profile "NOMAD_ADDR" and "MAPI_ADDR"

**Comment by kmova** [comment]
omm and osh have been deprecated.
