### ISSUE TITLE
Need historical logs/metrics to be available for debug purposes

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#173]
Whenever the pods are restarted, either upon encountering certain error conditions , say ```error/crashloopbackoff``` or as a result of a scheduling policy where the pod comes upon on a different node , the pod logs are seen to get lost. By default, kubernetes allows fetching of logs from "last running container" (See https://github.com/kubernetes/kubernetes/issues/4526) , but we may need historical logs from previous instances, especially for the m-apiserver and openebs-provisioner pods - ideally it should be stored out to a separate location (logstash/fluentd etc.., ? )

**Comment by kmova** [comment]
The best way to get the logging for new project is to have them output the data to stdout and stderr. The log format itself need to be thought-out that can provide context when co-relating from multiple source. 

Using this stdout/stderr will allow for COs (like K8s) to take care of redirecting them to files, perform logrotation, integrated with logging agents (like fluent per node), to then collect and aggregate them on a centralized logging server. 

Checkout : 
https://kubernetes.io/docs/concepts/cluster-administration/logging/
https://github.com/fluent/fluentd
https://docs.fluentd.org/v0.12/articles/kubernetes-fluentd

**Comment by kmova** [comment]
From the context perspective, using opentracing/jaegar by the maya-components will help in tracking down requests that span across multiple containers -- like maya-apiserver, maya-provisioner, maya-mule, maya-agent etc., 

Also, jaegar comes with a couple of options that are very helpful:
- dynamically enabling higher level tracing - based on an alert or threshold condition
- includes non-intrusive instrumentation to get details on where the services are running within k8s environment. 

https://github.com/jaegertracing/jaeger
https://github.com/jaegertracing/jaeger-kubernetes
https://www.youtube.com/watch?v=fjYAU3jayVo&feature=youtu.be

**Comment by kmova** [comment]
https://github.com/draios/sysdig-inspect

**Comment by utkarshmani1997** [comment]
* Two approaches are available which has been used by most of the devops
  - https://github.com/pires/kubernetes-elasticsearch-cluster
  - https://github.com/upmc-enterprises/elasticsearch-operator
* 1st one seems promising and 2nd one is built on top of the first one and currently provides limited support to gke.
