### ISSUE TITLE
Need to tool/framework to simulate HTTP error response for negative tests

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#175]
Need to tool/framework to simulate HTTP error response for negative tests in the CI suite

**Comment by Apollo9999** [comment]
This is the approach we use for testing 404's and other errors like 401, 403, 409 and 422. Checking the spy should ensure that if the path responds with 20x status, the test should fail.

HTTP error  approach we use for testing 404's and other errors like 401, 403, 409 and 422. Checking the spy should ensure that if the path responds with 20x status, the test should fail.

'use strict';

const chai = require('chai');
const chaiHttp = require('chai-http');
const spies = require('chai-spies');

chai.should();
const { app } = require('../server');

chai.use(chaiHttp);
chai.use(spies);

describe('Wrong paths', function () {

  it('should respond with 404', function () {
    const spy = chai.spy();
    return chai.request(app)
      .get('/v1/foobar')
      .then(spy)
      .catch((err) => {
        const res = err.response;
        res.should.have.status(404);
      })
      .then(() => {
        spy.should.not.have.been.called();
      });
  });
  
});
