### ISSUE TITLE
Mayactl command fails intermittently

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1874]
## Is this a BUG REPORT or FEATURE REQUEST?
 
`mayactl volume list` command fails to fetch the volumes list.

Command executed:
kubectl exec -it maya-apiserver-b4ffc578d-jf6v5 -n openebs -- mayactl volume list
Error seen:
Unable to use a TTY - input is not a terminal or the right kind of file\nServer status error: Internal Server Error\ncommand terminated with exit code 1", "stderr_lines": ["Unable to use a TTY - input is not a terminal or the right kind of file", "Server status error: Internal Server Error.

```
fatal: [localhost -> None]: FAILED! => {"changed": true, "cmd": "source ~/.profile; kubectl exec -it maya-apiserver-b4ffc578d-jf6v5 -n [*******] -- mayactl volume list", "delta": "0:00:00.753509", "end": "2018-08-30 11:24:56.940738", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2018-08-30 11:24:56.187229", "stderr": "Unable to use a TTY - input is not a terminal or the right kind of file\nServer status error: Internal Server Error\ncommand terminated with exit code 1", "stderr_lines": ["Unable to use a TTY - input is not a terminal or the right kind of file", "Server status error: Internal Server Error", "command terminated with exit code 1"], "stdout": "", "stdout_lines": []}
```
out of 4 runs it failed twice.
Note:-
  Observed this issue on 0.7.0-RC-2 build

**Comment by nsathyaseelan** [comment]
Here is the log collected through stren.
[replica_quorum_failure_test.log](https://github.com/openebs/openebs/files/2334919/replica_quorum_failure_test.log)

**Comment by dargasudarshan** [comment]
[maya.log](https://github.com/openebs/openebs/files/2335098/maya.log)
@prateekpandey14 Please find the attached maya-server logs

**Comment by nsathyaseelan** [comment]
This issue will not be seen in 0.7.0.
