### ISSUE TITLE
kubectl delete -f openebs-operator.yaml is not deleting the SPC's, CSP's and SP's.

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/openebs#1896]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT

**What happened**:
- kubectl delete -f openebs-operator.yaml is not deleting the SPC's, CSP's and SP's.

**What you expected to happen**:
- The spc's csp's and sp's should be deleted on deleting the openebs-operator.yaml
- This is causing the next set of cstor sparse pool pods to remain in pending state.

**How to reproduce it (as minimally and precisely as possible)**:
- Apply openebs-operator.yaml
Once all the pods. spc's csp's and sp's are created.
- Delete the openebs-operator.yaml
**Anything else we need to know?**:

**Comment by dargasudarshan** [comment]
Possible Workaround:

Manually delete the spc's csp's and sp's

``` kubectl delete spc,csp,sp --all ```

**Comment by dargasudarshan** [comment]
@kmova Is there any plan for this issue to be fixed? 
I am still facing this issue on OpenEBS 0.7.1 on GKE cluster.

**Comment by KhoaNPA** [comment]
same issue with EKS
