### ISSUE TITLE
Support for ReadOnlyMany Access mode in openebs-iSCSI provisioner

### ISSUE THREAD

**Issue by ronakpandya7** [openebs/openebs#1899]
Hello,

We are using openebs(version 0.6) with  provisioner `iSCSI` and deployed it in kubernetes version 1.10.5.

We created one pvc with access mode "ReadWriteOnce", and it is working fine.
Now we want to read data from the same PVC that we created earlier, so we come to know under this [link](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) from the table of content, that iSCSI is supporting "ReadOnlyMany" access mode.

But when we trien to apply it on our another pod it gives the following error:

`<invalid> (x12 over <invalid>)  openebs.io/provisioner-iscsi openebs-provisioner-5569654c96-4rlsn 760ae66d-9ebc-11e8-97d4-823996605407  Failed to provision volume with StorageClass "openebs-standard": Invalid Access Modes: [ReadOnlyMany], Supported Access Modes: [ReadWriteOnce]`

So after googling this error we came across this [issue](https://github.com/openebs/openebs/issues/439).

So when will we expect support for `ReadOnlyMany` access mode?

Thanks.
Ronak

**Comment by kmova** [comment]
@ronakpandya7, You can use RWM now by running nfs provisioner on top of iSCSI block volume. More details can be found at: https://docs.openebs.io/docs/next/rwm.html

Would love to hear from you if the above solution works for you.
