### ISSUE TITLE
OpenEBS Namespace remains in 'Terminating' state intermittently due to stale cStor Volume Replicas (CVR)

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/openebs#1901]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT

**What happened**:
- During un-installation of OpenEBS, observed that OpenEBS Namespace remains in 'Terminating' state due to stale cStor Volume Replicas (CVR).
Note: This issue is seen intermittently. 

**What you expected to happen**:
- OpenEBS un-installation should be seamless all the stale cvr's should be deleted when application deployment is removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Observed this issue on OpenEBS 0.7.0 build.

**Comment by kmova** [comment]
0.9 removes the finalizers on the cStor Volume Replica resources, which should help with deletion of the openebs namespace.

**Comment by siegfriedhoellrigl** [comment]
Hi !
We had installed OpenEBS 0.9.0 from helm chart, and would like to remove it completely.

We followed the instructions from https://docs.openebs.io/docs/next/uninstall.html.
It was almost successful, but

when executing "kubectl delete crd blockdeviceclaims.openebs.io"
customresourcedefinition.apiextensions.k8s.io
-> "blockdeviceclaims.openebs.io" deleted
looks ok, but there is no prompt afterwards. So it looks like it does not really delete anything.

> kubectl get ns | grep openebs
openebs                     Terminating   47d

**Comment by kmova** [comment]
@siegfriedhoellrigl .. can you check on the `kubectl get crd | grep -i openebs`. It is possible that the finalizers on some of the resources are still present.

**Comment by siegfriedhoellrigl** [comment]
> kubectl get crd | grep -i openebs
blockdeviceclaims.openebs.io                      2019-07-29T16:15:39Z


> kubectl delete crd blockdeviceclaims.openebs.io
customresourcedefinition.apiextensions.k8s.io "blockdeviceclaims.openebs.io" deleted
... and this command "hangs" forever....

**Comment by kmova** [comment]
Can you check if there are any finalizers on the block devices and remove them please. 

`kubectl get bdc -n openebs`

**Comment by siegfriedhoellrigl** [comment]
kubectl get bdc -n openebs
NAME                                       BLOCKDEVICENAME                                PHASE   AGE
bdc-f1f6a563-8e95-11e9-a30c-0cc47a0e9cff   blockdevice-9eef5b8d91e602a27ef0d2e88ca4d66b   Bound   1d


kubectl delete bdc -n openebs bdc-f1f6a563-8e95-11e9-a30c-0cc47a0e9cff    
blockdeviceclaim.openebs.io "bdc-f1f6a563-8e95-11e9-a30c-0cc47a0e9cff" deleted
... was this command correct ? this hangs forever too ...

**Comment by kmova** [comment]
`kubectl edit bdc -n openebs bdc-f1f6a563-8e95-11e9-a30c-0cc47a0e9cff` ( Remove the finalizer section)

**Comment by siegfriedhoellrigl** [comment]
Ah ! Perfect. openebs namespace has gone now.
Do you know why this happened ?
Is it fixed in openebs 1.0.0 ?

Thanks a lot !

**Comment by kmova** [comment]
Finalizers are removed by the respective controllers in this case the finalizers on BDC should be removed by m-apiserver and NDM. However as part of delete namespace, if the m-apiserver and ndm-operator pods are terminated before they got a chance to delete the finalizers, we get into this state. This issue should not happen if all the objects are deleted before deleting the namespace. 

The fix for this via openebs-operator that can help with stale object deletion is currently planned for 1.2/1.3 release.
