### ISSUE TITLE
PV not provisioned with "xfs" filesystem.

### ISSUE THREAD

**Issue by vitalka200** [openebs/openebs#1907]
Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT

**What happened**:
PV not provisioned with "xfs" filesystem.

**What you expected to happen**:
PV provisioned with an "xfs" filesystem

**How to reproduce it (as minimally and precisely as possible)**:
Deploy latest openebs-operator (0.7.0) from "openebs-operator.yaml".
Deploy StorageClass with 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-mongodb
  annotations:
    cas.openebs.io/config: |
      - name: FSType
        value: "xfs"
provisioner: openebs.io/provisioner-iscsi
```
Provision volume with newly created storageclass.
Observe..

**Anything else we need to know?**:
From openebs-operator logs we can see that that CASVolume not received the "fsType" parameter from from the StorageClass

```
{"apiVersion":"v1alpha1","kind":"CASVolume","metadata":{"annotations":{"openebs.io/storageclass-version":"2141777"},"name":"test-test-xfs-216610947"},"spec":{"capacity":"1Gi","casType":"jiva","fsType":"","iqn":"iqn.2016-09.com.openebs.jiva:test-test-xfs-216610947","lun":0,"replicas":"3","targetIP":"\u003cno value\u003e","targetPort":"3260","targetPortal":"10.43.126.116:3260"},"status":{"Message":"","Phase":"","Reason":""}}
```

**Environment**:
- kubectl get sc
```
NAME                        PROVISIONER                                                AGE
openebs-cstor-sparse        openebs.io/provisioner-iscsi                               3d
openebs-jiva-default        openebs.io/provisioner-iscsi                               3d
openebs-mongodb             openebs.io/provisioner-iscsi                               2d
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   3d
openebs-standalone          openebs.io/provisioner-iscsi                               2d
openebs-standard            openebs.io/provisioner-iscsi                               2d

```
- kubectl get pv
```
NAME                                 CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS      REASON    AGE
test-test-xfs-216610947          1Gi        RWO            Delete           Bound     test/test-xfs         openebs-mongodb             7s
```
- kubectl get pvc
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux fsn-wrk1 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kmova** [comment]
Thank you @vitalka200 for finding this issue. There was indeed an issue with maya-apiserver fetching the value of FSType from storage class. 

maya-apiserver expected the FSType was expected to be available as volume (controller) pod annotation, but it was being set only as annotation on volume (controller) deployment. The fix will be to update the annotation in the correct place and will be taken up for 0.7.1

You can apply the following file to patch the YAML in your setup to get the fix:
```
kubectl apply -f https://raw.githubusercontent.com/openebs/charts/master/store/openebs-0.7.0-hf-1907.yaml
```
After applying the above patch, the logs in the provisioner will still show FSType as empty, but you can verify the exact FS type used using the following methods:

(a) Check the PV spec
```
kubectl get pv <mongo-pv> -o yaml
```

(b) Check the mount output from the node where the volume is mounted.
```
kiran_mova@gke-kmova-helm-default-pool-1fd5d008-kstf:~$ mount | grep jiva
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.47.243.27:3260-iqn.2016-09.com.openebs.jiva:default-mongo-persistent-storage-mongo-0-3274949689-lun-0 type xfs (rw,relatime,attr2,inode64,noquota)
```

**Comment by vitalka200** [comment]
Thank you @kmova. Working as expected. Is there any date when to expect the 0.7.1 release to be available?

**Comment by kmova** [comment]
Thank you for the quick confirmation  @vitalka200! 0.7.1 planned for end of this week.

**Comment by vitalka200** [comment]
Great. Thank you again.
Closing issue
