### ISSUE TITLE
cStor pool creation failing when there are partitions on the disk. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1910]
cStor pool creation failing with the following error message:
```
E0920 14:51:17.474702       8 pool.go:78] Unable to create pool: /dev/disk/by-id/ata-WDC_WD2500BPVT-00JJ5T0_WD-WX61E82TV818 is in use and contains a unknown filesystem.
```
sdb and sdc are used for pool. 

```
core@k8worker02 ~ $ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda           8:0    0 111.8G  0 disk
|-sda1        8:1    0   128M  0 part  /boot
|-sda2        8:2    0     2M  0 part
|-sda3        8:3    0     1G  0 part
| `-usr     254:0    0  1016M  1 crypt /usr
|-sda4        8:4    0     1G  0 part
|-sda6        8:6    0   128M  0 part  /usr/share/oem
|-sda7        8:7    0    64M  0 part
`-sda9        8:9    0 109.5G  0 part  /
sdb           8:16   0 111.8G  0 disk
sdc           8:32   0 232.9G  0 disk
|-sdc1        8:33   0     1G  0 part
`-sdc2        8:34   0 231.9G  0 part
 |-cl-swap 254:1    0   7.8G  0 lvm
 |-cl-home 254:2    0 174.1G  0 lvm
 `-cl-root 254:3    0    50G  0 lvm
```

**Comment by Pencerval** [comment]
I was able to fix this issue.
Previous state on sdb:
```
(parted) print
Error: /dev/sdb: unrecognised disk label
Model: ATA SAMSUNG MZ7LM120 (scsi)                                        
Disk /dev/sdb: 120GB

```
After running:
`(parted) mklabel gpt`

```
(parted) print                                                            
Model: ATA SAMSUNG MZ7LM120 (scsi)
Disk /dev/sdb: 120GB
```

On sdc:
```
Using /dev/sdc
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) mklabel gpt                                                      
Warning: The existing disk label on /dev/sdc will be destroyed and all data on this disk will
be lost. Do you want to continue?
Yes/No? Yes                                                               
Error: Partition(s) 2 on /dev/sdc have been written, but we have been unable to inform the
kernel of the change, probably because it/they are in use.  As a result, the old partition(s)
will remain in use.  You should reboot now before making further changes.
Ignore/Cancel? I                                                          
(parted) quit                                                             
Information: You may need to update /etc/fstab.
```
After rebooting the node, I can create a pool on those disk.

Thanks for the support.

**Comment by Pencerval** [comment]
I've faced the same issue in other node.
The approach and solution was different:

```
core@k8worker01 ~ $ sudo dmsetup info -C
Name             Maj Min Stat Open Targ Event  UUID                                                                
usr              254   0 L--r    1    1      0 CRYPT-VERITY-959135d6b3894b3b8125503de238d5c4-usr                   
centos-home      254   2 L--w    0    1      0 LVM-1kqWMeQWqH3qTsiHhYw3ygAzOvpfDL58dDmziWBI0panwOGRq2rp9PjpmE6qdf1V
centos-swap      254   1 L--w    0    1      0 LVM-1kqWMeQWqH3qTsiHhYw3ygAzOvpfDL58UIVFhLkzvE1mk7uCy2nePlktBHfTuTYF
centos-root      254   3 L--w    0    1      0 LVM-1kqWMeQWqH3qTsiHhYw3ygAzOvpfDL58WULaIYm0X7QmrwQaWYxz1hTwzWocAwYJ

core@k8worker01 ~ $ sudo dmsetup remove centos-home
core@k8worker01 ~ $ sudo dmsetup remove centos-swap
core@k8worker01 ~ $ sudo dmsetup remove centos-root

```
Cleaning those entries fixes the problem!
Thanks!

**Comment by heppstux** [comment]
it would be great, if it was possible to just use the remaining free space for the pool - any chance?

**Comment by kmova** [comment]
There is some ongoing work on this one for 0.9 - @heppstux. It will great, if you can provide more information about your use case/deployment.

**Comment by bryanlarsen** [comment]
@kmova I'm not sure that this is the same request as @heppstux, but it would be nice if openebs could use unused space in LVM volume groups.   For instance, here is what we see when we do `vgdisplay` on a node:

```
  Alloc PE / Size       119208 / <465.66 GiB
  Free  PE / Size       357468 / 1.36 TiB
```

**Comment by heppstux** [comment]
Hi @kmova, hi @bryanlarsen,
I hope, I can shed some light into this:

I have a couple of servers with two large SSDs that are mainly used to boot the OS and hold the root-fs (as mirrored MD) from some smaller partitions. The rest of the disks is "unpartitioned" – so to say "free" ;)
I tried building a cStor pool from these SSDs in the hope, that it would just use the remaining free space and create it's ZFS-Pools there. However, this gave me a message like "cannot partition disks, unknown partition exists" or something similar (sorry, I do not have the exact error anymore). I thought, thank you for not trying to delete my boot-partitions but couldn't you (cStor) just use the remaining free space on the disks — and that's where my message (https://github.com/openebs/openebs/issues/1910#issuecomment-463786219) came into existence.

I fiddled around with "giving cStor the impression" that it had created a pool successfully on the disks in the past (by creating them "by hand": taking over some cStor pool pods, just doing what hey should have done from my perspective in the first place with zpool) – it was kind of a timing-thing, but at some point I had it "running" — that is, until this pods had to restart — Not any good for production.

Was I missing something? From scanning the code a bit, it looks like it should already be possible to use the "unpartitioned" space of disks for cStor – but I could not get it to work.

For now, I did what's not best practice according to the manuals: I created a loop device from from the remaining free space and after lying to NDM that /dev/loop* are trustworthy fellows, cStore started to build pools on them happily. They survived the usual maintenance ups and downs over the passt weeks and all data is still there and happy. However, I do not thrust those little "fast" pools further than I can throw them (as we say here) and so far have not been using them for much (only disposable stuff).

best

**Comment by AmitKumarDas** [comment]
@heppstux Its great to know you have trying to make it work with all options possible. Working with partitions has been in our radar for sometime now. This data will certainly help us to implement a proper solution. cc @akhilerm @satbirchhikara

**Comment by akhilerm** [comment]
Alpha support for partitions has been added in openebs 1.10.  With this each separate partition is treated as separate block devices and can be used for different purposes. More details on enabling the feature can be found [here](https://github.com/openebs/openebs/wiki/Change-Summary-v1.10#alpha-feature-updates)
