### ISSUE TITLE
Bigger snapshot should not be allowed to restore into smaller PVC.

### ISSUE THREAD

**Issue by rgembalik** [openebs/openebs#1911]
## This is a BUG REPORT
**What happened**:
Following this guide: https://docs.openebs.io/docs/next/snapshots.html
I created volumesnapshot of PVC that which had 10Gi. Once data was available I restored it into a 5Gi PVC (simply by mistake). The data on the PVC was in total no more than 1Gb.
The PVC was created, but it didn't sync well and my test pod that tried to mount it was stuck in Creating state.

**What you expected to happen**:
I'd expect that pvc creation would fail, or that one of recreated pvc pods would fail and give me an error that I tried to restore into too small PVC.

**How to reproduce it (as minimally and precisely as possible)**:
Create VolumeSnapshot and restore it into smaller PVC.

**Anything else we need to know?**:
Next I recreated snapshot into a PVC tha thad exactly 10Gi. It was working well - it restored and mounted into another pod without any problems. 

The snapshot provisioner logs are below:
<details>
  <summary>
Click to expand
<pre>
ERROR: logging before flag.Parse: I0918 06:38:42.113126       1 maya_api.go:63] OpenEBS volume provisioner namespace openebs
...
</pre>
</summary>
<pre>
ERROR: logging before flag.Parse: I0918 06:38:42.113126       1 maya_api.go:63] OpenEBS volume provisioner namespace openebs
I0918 06:38:42.169249       1 snapshot-pv-provisioner.go:251] starting PV provisioner volumesnapshot.external-storage.k8s.io/snapshot-promoter
I0918 06:38:42.169291       1 controller.go:615] Starting provisioner controller 7bd9eb82-bb0d-11e8-99f3-dee58f05b8ad!
I0918 06:38:42.169317       1 controller.go:652] Started provisioner controller 7bd9eb82-bb0d-11e8-99f3-dee58f05b8ad!
I0919 13:17:09.156056       1 leaderelection.go:156] attempting to acquire leader lease...
I0919 13:17:09.245657       1 leaderelection.go:178] successfully acquired lease to provision for pvc minio/snap-vol-claim
I0919 13:17:09.281423       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"minio", Name:"snap-vol-claim", UID:"503683ad-bc0e-11e8-b3ba-525400451066", APIVersion:"v1", ResourceVersion:"32053958", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "minio/snap-vol-claim"
I0919 13:17:09.480144       1 processor.go:349] Source Volume is &v1.PersistentVolume{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pvc-b4fc6818-6ef8-11e8-bb8f-525400451066", GenerateName:"", Namespace:"", SelfLink:"/api/v1/persistentvolumes/pvc-b4fc6818-6ef8-11e8-bb8f-525400451066", UID:"b579a83b-6ef8-11e8-bb8f-525400451066", ResourceVersion:"15954959", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63664484311, loc:(*time.Location)(0x291d7c0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openEBSProvisionerIdentity":"kube2", "pv.kubernetes.io/provisioned-by":"openebs.io/provisioner-iscsi"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string{"kubernetes.io/pv-protection"}, ClusterName:""}, Spec:v1.PersistentVolumeSpec{Capacity:v1.ResourceList{"storage":resource.Quantity{i:resource.int64Amount{value:10737418240, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"10Gi", Format:"BinarySI"}}, PersistentVolumeSource:v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420600100), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}, AccessModes:[]v1.PersistentVolumeAccessMode{"ReadWriteOnce"}, ClaimRef:(*v1.ObjectReference)(0xc420159180), PersistentVolumeReclaimPolicy:"Delete", StorageClassName:"openebs-single-replica", MountOptions:[]string(nil), VolumeMode:(*v1.PersistentVolumeMode)(nil), NodeAffinity:(*v1.VolumeNodeAffinity)(nil)}, Status:v1.PersistentVolumeStatus{Phase:"Bound", Message:"", Reason:""}}
I0919 13:17:09.482167       1 processor.go:231] Using the Storage Class openebs-single-replica for dynamic provisioning
I0919 13:17:09.666528       1 maya_api.go:127] volume Successfully Created:
{"metadata":{"creationTimestamp":null,"labels":{},"name":"pvc-503683ad-bc0e-11e8-b3ba-525400451066"},"status":{"Message":"","Phase":"","Reason":""}}
I0919 13:17:09.744945       1 snapshot-pv-provisioner.go:91] snapshot &v1.VolumeSnapshotDataSpec{VolumeSnapshotDataSource:v1.VolumeSnapshotDataSource{HostPath:(*v1.HostPathVolumeSnapshotSource)(nil), GlusterSnapshotVolume:(*v1.GlusterVolumeSnapshotSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSnapshotSource)(nil), GCEPersistentDiskSnapshot:(*v1.GCEPersistentDiskSnapshotSource)(nil), CinderSnapshot:(*v1.CinderVolumeSnapshotSource)(nil), OpenEBSSnapshot:(*v1.OpenEBSVolumeSnapshotSource)(0xc420732190)}, VolumeSnapshotRef:(*v1.ObjectReference)(0xc420150230), PersistentVolumeRef:(*v1.ObjectReference)(0xc4201501c0)} to snap &v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420600300), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}
I0919 13:17:09.745048       1 snapshot-pv-provisioner.go:162] successfully created Snapshot share &v1.PersistentVolume{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pvc-503683ad-bc0e-11e8-b3ba-525400451066", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"snapshotProvisionerIdentity":"volumesnapshot.external-storage.k8s.io/snapshot-promoter"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.PersistentVolumeSpec{Capacity:v1.ResourceList{"storage":resource.Quantity{i:resource.int64Amount{value:5368709120, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"5Gi", Format:"BinarySI"}}, PersistentVolumeSource:v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420600300), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}, AccessModes:[]v1.PersistentVolumeAccessMode{"ReadWriteOnce"}, ClaimRef:(*v1.ObjectReference)(nil), PersistentVolumeReclaimPolicy:"Delete", StorageClassName:"", MountOptions:[]string(nil), VolumeMode:(*v1.PersistentVolumeMode)(nil), NodeAffinity:(*v1.VolumeNodeAffinity)(nil)}, Status:v1.PersistentVolumeStatus{Phase:"", Message:"", Reason:""}}
I0919 13:17:09.745392       1 controller.go:1079] volume "pvc-503683ad-bc0e-11e8-b3ba-525400451066" for claim "minio/snap-vol-claim" created
I0919 13:17:09.778133       1 controller.go:1096] volume "pvc-503683ad-bc0e-11e8-b3ba-525400451066" for claim "minio/snap-vol-claim" saved
I0919 13:17:09.778178       1 controller.go:1132] volume "pvc-503683ad-bc0e-11e8-b3ba-525400451066" provisioned for claim "minio/snap-vol-claim"
I0919 13:17:09.778469       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"minio", Name:"snap-vol-claim", UID:"503683ad-bc0e-11e8-b3ba-525400451066", APIVersion:"v1", ResourceVersion:"32053958", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-503683ad-bc0e-11e8-b3ba-525400451066
I0919 13:17:11.273964       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc minio/snap-vol-claim, task succeeded
I0920 08:51:56.460068       1 leaderelection.go:156] attempting to acquire leader lease...
I0920 08:51:56.477906       1 leaderelection.go:178] successfully acquired lease to provision for pvc minio/snapshot-minio-v2-pvc
I0920 08:51:56.482668       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"minio", Name:"snapshot-minio-v2-pvc", UID:"6cce5391-bcb2-11e8-b3ba-525400451066", APIVersion:"v1", ResourceVersion:"32223349", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "minio/snapshot-minio-v2-pvc"
I0920 08:51:56.537183       1 processor.go:349] Source Volume is &v1.PersistentVolume{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pvc-b4fc6818-6ef8-11e8-bb8f-525400451066", GenerateName:"", Namespace:"", SelfLink:"/api/v1/persistentvolumes/pvc-b4fc6818-6ef8-11e8-bb8f-525400451066", UID:"b579a83b-6ef8-11e8-bb8f-525400451066", ResourceVersion:"15954959", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63664484311, loc:(*time.Location)(0x291d7c0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"pv.kubernetes.io/provisioned-by":"openebs.io/provisioner-iscsi", "openEBSProvisionerIdentity":"kube2"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string{"kubernetes.io/pv-protection"}, ClusterName:""}, Spec:v1.PersistentVolumeSpec{Capacity:v1.ResourceList{"storage":resource.Quantity{i:resource.int64Amount{value:10737418240, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"10Gi", Format:"BinarySI"}}, PersistentVolumeSource:v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420728980), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}, AccessModes:[]v1.PersistentVolumeAccessMode{"ReadWriteOnce"}, ClaimRef:(*v1.ObjectReference)(0xc4204b8540), PersistentVolumeReclaimPolicy:"Delete", StorageClassName:"openebs-single-replica", MountOptions:[]string(nil), VolumeMode:(*v1.PersistentVolumeMode)(nil), NodeAffinity:(*v1.VolumeNodeAffinity)(nil)}, Status:v1.PersistentVolumeStatus{Phase:"Bound", Message:"", Reason:""}}
I0920 08:51:56.537412       1 processor.go:231] Using the Storage Class openebs-single-replica for dynamic provisioning
I0920 08:51:56.833751       1 maya_api.go:127] volume Successfully Created:
{"metadata":{"creationTimestamp":null,"labels":{},"name":"pvc-6cce5391-bcb2-11e8-b3ba-525400451066"},"status":{"Message":"","Phase":"","Reason":""}}
I0920 08:51:57.016294       1 snapshot-pv-provisioner.go:91] snapshot &v1.VolumeSnapshotDataSpec{VolumeSnapshotDataSource:v1.VolumeSnapshotDataSource{HostPath:(*v1.HostPathVolumeSnapshotSource)(nil), GlusterSnapshotVolume:(*v1.GlusterVolumeSnapshotSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSnapshotSource)(nil), GCEPersistentDiskSnapshot:(*v1.GCEPersistentDiskSnapshotSource)(nil), CinderSnapshot:(*v1.CinderVolumeSnapshotSource)(nil), OpenEBSSnapshot:(*v1.OpenEBSVolumeSnapshotSource)(0xc420773310)}, VolumeSnapshotRef:(*v1.ObjectReference)(0xc420150f50), PersistentVolumeRef:(*v1.ObjectReference)(0xc420150ee0)} to snap &v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420700080), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}
I0920 08:51:57.016439       1 snapshot-pv-provisioner.go:162] successfully created Snapshot share &v1.PersistentVolume{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pvc-6cce5391-bcb2-11e8-b3ba-525400451066", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"snapshotProvisionerIdentity":"volumesnapshot.external-storage.k8s.io/snapshot-promoter"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.PersistentVolumeSpec{Capacity:v1.ResourceList{"storage":resource.Quantity{i:resource.int64Amount{value:10737418240, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"10Gi", Format:"BinarySI"}}, PersistentVolumeSource:v1.PersistentVolumeSource{GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), HostPath:(*v1.HostPathVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), RBD:(*v1.RBDPersistentVolumeSource)(nil), ISCSI:(*v1.ISCSIPersistentVolumeSource)(0xc420700080), Cinder:(*v1.CinderPersistentVolumeSource)(nil), CephFS:(*v1.CephFSPersistentVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), FlexVolume:(*v1.FlexPersistentVolumeSource)(nil), AzureFile:(*v1.AzureFilePersistentVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOPersistentVolumeSource)(nil), Local:(*v1.LocalVolumeSource)(nil), StorageOS:(*v1.StorageOSPersistentVolumeSource)(nil), CSI:(*v1.CSIPersistentVolumeSource)(nil)}, AccessModes:[]v1.PersistentVolumeAccessMode{"ReadWriteOnce"}, ClaimRef:(*v1.ObjectReference)(nil), PersistentVolumeReclaimPolicy:"Delete", StorageClassName:"", MountOptions:[]string(nil), VolumeMode:(*v1.PersistentVolumeMode)(nil), NodeAffinity:(*v1.VolumeNodeAffinity)(nil)}, Status:v1.PersistentVolumeStatus{Phase:"", Message:"", Reason:""}}
I0920 08:51:57.016593       1 controller.go:1079] volume "pvc-6cce5391-bcb2-11e8-b3ba-525400451066" for claim "minio/snapshot-minio-v2-pvc" created
I0920 08:51:57.143977       1 controller.go:1096] volume "pvc-6cce5391-bcb2-11e8-b3ba-525400451066" for claim "minio/snapshot-minio-v2-pvc" saved
I0920 08:51:57.144019       1 controller.go:1132] volume "pvc-6cce5391-bcb2-11e8-b3ba-525400451066" provisioned for claim "minio/snapshot-minio-v2-pvc"
I0920 08:51:57.144242       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"minio", Name:"snapshot-minio-v2-pvc", UID:"6cce5391-bcb2-11e8-b3ba-525400451066", APIVersion:"v1", ResourceVersion:"32223349", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-6cce5391-bcb2-11e8-b3ba-525400451066
I0920 08:51:58.501713       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc minio/snapshot-minio-v2-pvc, task succeeded
</pre>
</details>

**Environment**:
- kubectl get nodes
```
NAME      STATUS                     ROLES     AGE       VERSION
kube1     Ready,SchedulingDisabled   master    181d      v1.11.2
kube2     Ready                      node      181d      v1.11.2
kube3     Ready                      node      181d      v1.11.2
kube4     Ready,SchedulingDisabled   node      162d      v1.11.2
kube5     Ready                      node      27d       v1.11.2
```
- kubectl -n minio get pvc
```
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
minio                   Bound     pvc-b4fc6818-6ef8-11e8-bb8f-525400451066   10Gi       RWO            openebs-single-replica   99d
snap-vol-claim          Bound     pvc-503683ad-bc0e-11e8-b3ba-525400451066   5Gi        RWO            snapshot-promoter        1d
snapshot-minio-v2-pvc   Bound     pvc-6cce5391-bcb2-11e8-b3ba-525400451066   10Gi       RWO            snapshot-promoter        21h
```
- kubectl -n minio get pod | grep pvc
```
pvc-503683ad-bc0e-11e8-b3ba-525400451066-ctrl-8c9bb4bcd-j6swg    2/2       Running   0          23h
pvc-503683ad-bc0e-11e8-b3ba-525400451066-rep-6fff55696c-fwkrn    1/1       Running   0          23h
pvc-6cce5391-bcb2-11e8-b3ba-525400451066-ctrl-694b646b48-mv7jg   2/2       Running   0          21h
pvc-6cce5391-bcb2-11e8-b3ba-525400451066-rep-5989d84658-ls494    1/1       Running   0          21h
pvc-b4fc6818-6ef8-11e8-bb8f-525400451066-ctrl-d8d4fcd58-5qgqx    2/2       Running   0          2d
pvc-b4fc6818-6ef8-11e8-bb8f-525400451066-rep-74f9d99f88-m6vq2    1/1       Running   0          2d
pvc-b4fc6818-6ef8-11e8-bb8f-525400451066-rep-74f9d99f88-vmrtr    1/1       Running   0          2d
```

**Comment by princerachit** [comment]
If the size of snapshot is less than pvc, shouldn't restoring be supported? @vishnuitta @kmova.

Alternative approach would be to error out as the user says.

**Comment by rgembalik** [comment]
@princerachit If you are referring to the data size on the PVC, then yes, I think that would be ideal. To be honest I kind of was hoping for it once I recognized my error.

**Comment by prateekpandey14** [comment]
This issue fixed in later releases via admission webhook validations
