### ISSUE TITLE
Write unit test for openebs/pkg/provisioner/cas_provision.go

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1914]
Write UT for [cas_provision.go](https://github.com/openebs/external-storage/blob/release/openebs/pkg/provisioner/cas_provision.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **release** branch and once done raise a PR against the same.
3. Don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by princerachit** [comment]
@swetax go ahead!

**Comment by princerachit** [comment]
This issue is available again. Please comment to get assigned.

**Comment by princerachit** [comment]
@sourabh1031 this issue has following functions that are required to be tested. 
`NewOpenEBSCASProvisioner` -> knowledge of kubernetes would be helpful, but not strictly required.
`GetAccessModes`
`Setlink`

See if this link helps with first function https://medium.com/@e_frogers/unit-testing-with-kubernetes-client-go-283b11aaa7db

**Comment by princerachit** [comment]
Would you like to take it?
@sourabh1031

**Comment by sourabh1031** [comment]
I am ready to work

**Comment by princerachit** [comment]
Sure go ahead. And let us know if you face problems. Also make sure you read contributors guide and DCO sign off your PR.

**Comment by sourabh1031** [comment]
@princerachit can you please give me more time as i have learnt about basics of  k8s and OpenEBS by now.

**Comment by princerachit** [comment]
Sure @saurabh1031

**Comment by sourabh1031** [comment]
@princerachit it will be better if someone can hack this issue because i am learning golang it will take me little time so if any just pings here you can assign this and sorry for my failure
