### ISSUE TITLE
Write unit test for openebs/pkg/volume/v1alpha1/volume.go

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1915]
Write UT for [volume.go](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/volume.go).

If you find it difficult to write ut for this file let us know. We will create another issue to refactor the file to make it testable.

Please comment if you want to be assigned for this issue.

Help links:
[contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)
[Unit Testing http client in golang](http://hassansin.github.io/Unit-Testing-http-client-in-Go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **release** branch and once done raise a PR against the same.

**Comment by princerachit** [comment]
@nawedx You can start working on this issue. And don't forget to join #hacktoberfest2018 channel on openebs slack for any help or discussions.

**Comment by RajatVaryani** [comment]
@nawedx Are you working on this?

**Comment by nawedx** [comment]
Yes. @RajatVaryani  I am working on this. If I can't make any significant progress by Oct 7, I will leave this issue.

**Comment by nawedx** [comment]
Hi @princerachit !. I am not able to make any significant progress on this issue. So, I am leaving this issue. 
@RajatVaryani you can take it up if you want.
