### ISSUE TITLE
Write UT for openebs/types/v1/env.go

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1916]
Write UT for [env.go](https://github.com/openebs/external-storage/blob/release/openebs/types/v1/env.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **release** branch and once done raise a PR against the same.
3. Don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by swetax** [comment]
@princerachit Can you please assign this to me ?

**Comment by princerachit** [comment]
@swetax are you still working on this?

**Comment by swetax** [comment]
@princerachit No. I gave up this issue along with the assigned one to me .

**Comment by armudgal** [comment]
Hi, I would like to take a look on this :)

**Comment by princerachit** [comment]
@armudgal thank you for showing interest. Please go ahead. If you face any difficulty reach to us on slack.

**Comment by armudgal** [comment]
Hi, I looked into the test and the docs you references, it's gonna take some time for me to get familiar with golang, so if this is a high-prioirity issue you can give to someone else, otherwise I might take couple of days :)
