### ISSUE TITLE
Add more unit tests in cmd/cstor-pool-mgmt/controller/replica-controller/handler_test.go

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1917]
Add missing UT for functions/methods in [handler.go](https://github.com/openebs/maya/blob/master/cmd/cstor-pool-mgmt/controller/replica-controller/handler.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **master** branch and once done raise a PR against the same.
3. Don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by sachinmukherjee** [comment]
I would like to work in this issue.

**Comment by princerachit** [comment]
Sure @sachinmukherjee you can work on this issue. Also do join slack channel(in description) for any help.
