### ISSUE TITLE
Add more unit tests in cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller_test.go

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1919]
Add missing UT for functions/methods in [new_replica_controller.go](https://github.com/openebs/maya/blob/master/cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **master** branch and once done raise a PR against the same.
3. Don't forget to join **hacktoberfest2018** channel on our [slack workspace](https://openebs-community.slack.com/).

**Comment by farhaanbukhsh** [comment]
Hey I would like to work on it how can I get started? Also it would be great if you can assign it to me.

**Comment by farhaanbukhsh** [comment]
Okay so I figured out the file I am just looking into how can write the test for the function.
