### ISSUE TITLE
Fix typo in volume_info.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1921]
Following is the go file which contains a typo : 

[volume_info.go](https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volume_info.go).
"received" is misspelt as "recieved"
Help Links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by cTxplorer** [comment]
Can you assign this issue to me?

**Comment by sonasingh46** [comment]
Great! You can go ahead and do it. @cTxplorer

**Comment by ulshell** [comment]
Please assign me the task to fix this issue

**Comment by sonasingh46** [comment]
@cTxplorer If you are taking up this issue, please give a heads up!
@ulshell Can you please take up another issue.

**Comment by cTxplorer** [comment]
@sonasingh46, generally speaking, +1 to the comment works? Or am I supposed to write thumbs up comment?

**Comment by cTxplorer** [comment]
I would make PR by tonight or latest by tomorrow morning :)

**Comment by sonasingh46** [comment]
A confirmation comment would be great.
Thanks @cTxplorer
