### ISSUE TITLE
Add UT for method Version(version string) version

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1922]
Add missing UT for  [method Version(version string) version
](https://github.com/openebs/maya/blob/master/pkg/install/v1alpha1/version.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **master** branch and once done raise a PR against the same.

**Comment by Pensu** [comment]
@ashishranjan738 I can take this up, will send  a PR. One clarification, there is already a version_test.go, so I will just add the TestVersion() to that file only, right?

**Comment by princerachit** [comment]
@Pensu you can take up this issue. You only have to add test function in the existing `_test` file.
