### ISSUE TITLE
Add UT for volume_list.go in mayactl

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1923]
Add missing UT for  [volume_list.go](https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volumes_list.go).

Please comment if you want to be assigned for this issue.

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[Guide to write unit tests in golang](https://blog.alexellis.io/golang-writing-unit-tests/)
[Reference on how we write UT](https://github.com/openebs/external-storage/blob/release/openebs/pkg/volume/v1alpha1/snapshot_test.go)

Note:
1. We only make use of standard "testing" library provided by go. Please do not add external dependency such as 'assert' etc
2. Checkout new branch from **master** branch and once done raise a PR against the same.

**Comment by Akash4927** [comment]
@knrt10 Sure, please go ahead
