### ISSUE TITLE
Fix lint for constant.go file

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1924]
Following file has a lint issue:
[maya/types/v1/constant.go](https://github.com/openebs/maya/blob/master/types/v1/constant.go#L22)

The lint  issue is : 
comment on exported const InfoAPI should be of the form "InfoAPI ..."

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by NaveenBellary** [comment]
@sonasingh46, I'll take this up
