### ISSUE TITLE
Fix go lint in iscsi.go 

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1925]
Following file has a lint issue:
[maya/cmd/maya-agent/app/command/iscsi.go](https://github.com/openebs/maya/blob/master/cmd/maya-agent/app/command/iscsi.go#L7)
The lint  issue is : 
 comment on exported function NewCmdIscsi should be of the form "NewCmdIscsi ..." 

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by yo-ga** [comment]
@sonasingh46 I would like to fix it.

**Comment by sonasingh46** [comment]
@yo-ga 
Sure!Go ahead.
