### ISSUE TITLE
Fix go lint in storagepool_template_engine.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1926]
Following file has a lint issue:
[maya/pkg/storagepool/storagepool_template_engine.go](https://github.com/openebs/maya/blob/master/pkg/storagepool/storagepool_template_engine.go#L17)

The lint  issue is : 
package comment should be of the form "Package storagepool ..."
Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by benkim0414** [comment]
DCO was failed in [openebs/maya#549](https://github.com/openebs/maya/pull/549) because of my wrong configuration.
I reopened a pull request [openebs/maya#550](https://github.com/openebs/maya/pull/550) to fix this issue.

Cheers!
