### ISSUE TITLE
Fix go lint in jiva.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1927]
Following file has a lint issue:
[maya/volume/provisioners/jiva/jiva.go](https://github.com/openebs/maya/blob/master/volume/provisioners/jiva/jiva.go#L1)

The lint  issue is : 
package comment should be of the form "Package jiva ..."

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by shindakun** [comment]
I'll grab this one.

**Comment by Akash4927** [comment]
@shindakun Thanks for the PR
