### ISSUE TITLE
Fix golint from util.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1928]
Following is the file with line numbers having lint error:
[maya/pkg/util/util.go](https://github.com/openebs/maya/blob/master/pkg/util/util.go)
[Line 32](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L32):  error var MAPIADDRNotSet should have name of the form ErrFoo 
[Line 33](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L33): error var InternalServerError should have name of the form ErrFoo
[Line 33](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L33):exported var InternalServerError should have comment or be unexported 
[Line 34](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L34):  error var ServerUnavailable should have name of the form ErrFoo 
[Line 35](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L35): error var ServerNotReachable should have name of the form ErrFoo 
[Line 36](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L36):  error var PageNotFound should have name of the form ErrFoo 
[Line 134](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L134): should omit 2nd value from range; this loop is equivalent to `for k := range ...` 
[Line 142](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L142):  comment on exported function ContainKeys should be of the form "ContainKeys ..."
[Line 150](https://github.com/openebs/maya/blob/master/pkg/util/util.go#L150): should omit 2nd value from range; this loop is equivalent to `for k := range ...` 

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by NaveenBellary** [comment]
@sonasingh46, I'll take this up
