### ISSUE TITLE
Fix golint in exporter.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1929]
Following is the link to file where lint error is present :
[maya/cmd/maya-exporter/app/command/exporter.go](https://github.com/openebs/maya/blob/master/cmd/maya-exporter/app/command/exporter.go#L1)

Lint Issue :
package comment should be of the form "Package command ..."

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by NaveenBellary** [comment]
@sonasingh46, Can you provide more info as to what the command package does so that I can include it in the package comment?

**Comment by glatteis** [comment]
Well, If I'm correct on this the comment is just wrong... It should just say "Package command" instead of "Package exporter", as the package is command and the file is called exporter.

**Comment by NaveenBellary** [comment]
I thought the same. But then wondered if the comment was written for exporter and package was added by mistake. Wanted to check if that was the case. Nevertheless, raised [#562](https://github.com/openebs/maya/pull/562)
