### ISSUE TITLE
Fix golint in cas_template_engine.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1930]
Following are lint issues : 
[Line 279](https://github.com/openebs/maya/blob/master/pkg/engine/cas_template_engine.go#L279): comment on exported method CASEngine.Create should be of the form "Create ..."
[Line 289](https://github.com/openebs/maya/blob/master/pkg/engine/cas_template_engine.go#L289):  comment on exported method CASEngine.Delete should be of the form "Delete ..." 
[Line 294](https://github.com/openebs/maya/blob/master/pkg/engine/cas_template_engine.go#L294):  comment on exported method CASEngine.List should be of the form "List ..." 

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by NaveenBellary** [comment]
@sonasingh46, I'll be taking this up. Will raise a PR in sometime

**Comment by Akash4927** [comment]
@NaveenBellary Thanks for the PR
