### ISSUE TITLE
Fix golint in from_yaml.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1931]
Following lint issues should be fixed : 
[Line 17](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L17): package comment should be of the form "Package k8s ..." 
[Line 38](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L38):  exported function NewDeploymentYml should have comment or be unexported 
[Line 81](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L81):  comment on exported type ServiceYml should be of the form "ServiceYml ..." (with optional leading article)
[Line 88](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L88):  exported function NewServiceYml should have comment or be unexported
[Line 136](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L136): exported function NewCStorPoolYml should have comment or be unexported
[Line 147](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L147): exported function NewStoragePoolYml should have comment or be unexported
[Line 158](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L158): exported function NewCStorVolumeYml should have comment or be unexported
[Line 224](https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go#L224): exported function NewCStorVolumeReplicaYml should have comment or be unexported 

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by rbo13** [comment]
@sonasingh46, can I take this issue buddy?

**Comment by ashishranjan738** [comment]
Ya sure @rbo13 go ahead.

**Comment by rbo13** [comment]
Thanks :)

**Comment by rbo13** [comment]
Created a PR for this issue: https://github.com/openebs/maya/pull/551
