### ISSUE TITLE
Fix typo in cstor_volume_0.7.0.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1932]
Following is the typo error in file : 
[Line 554](https://github.com/openebs/maya/blob/master/pkg/install/v1alpha1/cstor_volume_0.7.0.go#L554): "preceeding" is a misspelling of "preceding" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by gunjan01** [comment]
@sonasingh46 Can i take this up ? Please assign the issue to me.

**Comment by sonasingh46** [comment]
@gunjan01 
Sure... Please go ahead.

**Comment by gunjan01** [comment]
@sonasingh46  PTAL "https://github.com/openebs/maya/pull/569"

**Comment by hugovk** [comment]
This issue can be closed, it was fixed in PR https://github.com/openebs/maya/pull/569.
