### ISSUE TITLE
Fix typo in runtask_command.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1934]
Following is the tyhttps://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L407po error in file : 
[Line 171](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L171): "occured" is a misspelling of "occurred" (misspell)
[Line 407](url):  "occured" is a misspelling of "occurred" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by sark01** [comment]
Taking up this issue.

**Comment by sonasingh46** [comment]
@sark01 
Sure! Please go ahead.
