### ISSUE TITLE
Fix typo in template.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1935]
Following is the typo error: 
[Line 558](https://github.com/openebs/maya/blob/master/pkg/template/template.go#L558):  "overriden" is a misspelling of "overridden" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by fdmarcin** [comment]
Hi, I would like to fix this.

**Comment by sonasingh46** [comment]
@fdmarcin 
Thank you.
You can raise PR for one of the issue that we assigned to you and then you can take this up.

**Comment by theramis** [comment]
Hi, 
I would like to fix this
