### ISSUE TITLE
Fix typo in template_test.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1936]
Following typo error should be fixed: 
[Line 2136](https://github.com/openebs/maya/blob/master/pkg/template/template_test.go#L2136):  "seperator" is a misspelling of "separator" (misspell)
[Line 2141](https://github.com/openebs/maya/blob/master/pkg/template/template_test.go#L2141): "seperator" is a misspelling of "separator" (misspell)
[Line 2161](https://github.com/openebs/maya/blob/master/pkg/template/template_test.go#L2161):  "seperator" is a misspelling of "separator" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by fdmarcin** [comment]
Hi, I would like to fix this.

**Comment by sonasingh46** [comment]
@fdmarcin 
Thank you.
You can raise PR for one of the issue assigned to you and then you can take this up.
