### ISSUE TITLE
Fix typo in handler_test.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1937]
Following typo error should be fixed: 
[Line 224](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/handler_test.go#L224):"beacuse" is a misspelling of "because" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by fdmarcin** [comment]
Hi, I would like to fix this.

**Comment by sonasingh46** [comment]
@fdmarcin 
Sure. Please go ahead.
