### ISSUE TITLE
Fix typo in jiva_volume_0.7.0.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1938]
Following typo error should be fixed 
[Line 150](https://github.com/openebs/maya/blob/master/pkg/install/v1alpha1/jiva_volume_0.7.0.go#L150):"anythign" is a misspelling of "anything" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by ramitsawhney27** [comment]
@sonasingh46 Hi, I'd like to take this issue up.

**Comment by sonasingh46** [comment]
@ramitsawhney27 
Sure. Please go ahead.
