### ISSUE TITLE
Fix typo in util.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1939]
Following typo error should be fixed :
[Line 1301](https://github.com/openebs/maya/blob/master/types/v1/util.go#L1301): "substracted" is a misspelling of "subtracted" (misspell)
[Line 1320](https://github.com/openebs/maya/blob/master/types/v1/util.go#L1320): "substraction" is a misspelling of "subtraction" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by arshadkazmi42** [comment]
@sonasingh46 Taking this up. Will submit a PR in sometime.

**Comment by sonasingh46** [comment]
Thank you @arshadkazmi42 
Go ahead.

**Comment by arshadkazmi42** [comment]
Created a PR at [openebs/maya#539](https://github.com/openebs/maya/pull/539)

**Comment by arshadkazmi42** [comment]
@sonasingh46 How to enter in this? 
https://openebs.io/hackfests/hacktoberfest-2018

Is there some form I need to fill for this?
