### ISSUE TITLE
provide options for administrator to configure the storage used by openebs volumes. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#194]
The storage backend used for persisting the data from OpenEBS volumes should be made flexible and configurable. For example, in addition to supporting hostdirectory, additional options like - new disks, cloud disks etc., should be supported. 

as part of enabling the openebs, admin can run an additional command like below to specify/configure the storage backend. 

```
kubectl apply -f openebs-config.yaml
```

the configuration will be saved as "custom resource" objects in k8s. maya-storageagents (aka maya-agents) running on the minions will watch for these custom-resources and take appropriate actions - like creating/modifying/deleting storage backends for the openebs volumes. monitoring the storage-backends, capturing the usage metrics etc.,

**Comment by kmova** [comment]
The implementation is tracked under https://github.com/openebs/maya/issues/76

**Comment by kmova** [comment]
Adding on top of the openebs/maya#76, the following approach will be followed (that makes use of CRDs)

_- admin can attach the disks to the kube-minion nodes. (In the first version (0.5), the disk can be attached to all the minion nodes) - note the device name (like sdb, sdc)_

- maya-agent will be monitoring for the RSA (raw storage) - CRD will be added with the following details:
  - block device name (like sdb, sdc)
  - format type (default ext4)
  - mount directory ( /mnt/external-storage/storage-1)

- maya-agent will check for the existence of the device name, if it exists, it will format it with ext4 and mount it into the directory.

- maya-agent will then create an RS (with the directory name, size details) - CRD

_- admin can use the new directory, by specifying it in the storage classes, ._ 

--
TODO
- When a delete RSA - CRD is received, check for all the RS objects associated with the RSA CRD and initiate cleanup.

**Comment by AmitKumarDas** [comment]
@kmova How is the RSA monitoring triggered ?

**Comment by gkGaneshR** [comment]
The monitoring is triggered when maya-agent start command is given. The way to map RS in k8s context is CRD.

**Comment by kmova** [comment]
The functionality has moved to openebs/node-disk-manager. The naming conventions referred to in this issue have also changed. Please refer to https://github.com/openebs/node-disk-manager/pull/1
