### ISSUE TITLE
Fix typo in volume_info.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1940]
Following typo error should be fixed: 
[Line 109](https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volume_info.go#L109):  "recieved" is a misspelling of "received" (misspell)
[Line 259](https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volume_info.go#L259):  "avaiable" is a misspelling of "available" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by sonasingh46** [comment]
You need to raise PR against upstream. @ulshell

**Comment by cTxplorer** [comment]
@sonasingh46 How can I sign-off DOC from the website itself? Or do I need to do it from console itself?
