### ISSUE TITLE
Fix typo in util.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1941]
Following typo error should be fixed:
[Line 458](https://github.com/openebs/maya/blob/master/orchprovider/k8s/v1/util.go#L458): "targetted" is a misspelling of "targeted" (misspell)
[Line 462](https://github.com/openebs/maya/blob/master/orchprovider/k8s/v1/util.go#L462): "targetted" is a misspelling of "targeted" (misspell)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by Atul9** [comment]
@sonasingh46 I have opened up a PR for this - https://github.com/openebs/maya/pull/533

**Comment by sonasingh46** [comment]
Thank you @Atul9 
Reviewers will be on your PR soon.

**Comment by moogacs** [comment]
I have add the fixes without signed off , are that is ok ?

**Comment by ashishranjan738** [comment]
No @moocgas sign-off is required
