### ISSUE TITLE
Fix golint in json_path.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1942]
Following lint error should be fixed: 
[Line 23](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L23): should not use dot imports (golint)
[Line 36](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L36): exported function Selection should have comment or be unexported (golint)
[Line 65](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L65): exported type SelectionList should have comment or be unexported (golint)
[Line 71](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L71):  exported method SelectionList.ValuesByName should have comment or be unexported (golint)
[Line 80](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L80): exported method SelectionList.ValueByName should have comment or be unexported (golint)
[Line 88](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L88):exported method SelectionList.ValuesByPath should have comment or be unexported (golint)
[Line 97](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L97):  exported method SelectionList.ValueByPath should have comment or be unexported (golint)
[Line 113](https://github.com/openebs/maya/blob/master/pkg/jsonpath/v1alpha1/json_path.go#L113):  exported function JSONPath should have comment or be unexported (golint)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by rafa-acioly** [comment]
can i take this one @sonasingh46 ?

**Comment by sonasingh46** [comment]
@rafa-acioly 
That would be great. Go ahead.

**Comment by rafa-acioly** [comment]
done @sonasingh46 https://github.com/openebs/maya/pull/563
