### ISSUE TITLE
Fix golint in runtask_command.go

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#1943]
Following lint errors should be fixed: 
[Line 22](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L22): should not use dot imports (golint)
[Line 31](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L31): exported const DeleteCommandAction should have comment (or a comment on this block) or be unexported (golint)
[Line 46](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L46): exported const JivaCommandCategory should have comment (or a comment on this block) or be unexported (golint)
[Line 127](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L127): exported function NewRunCommandResult should have comment or be unexported (golint)
[Line 143](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L143):  exported method RunCommandResult.Result should have comment or be unexported (golint)
[Line 147](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L147): exported method RunCommandResult.Debug should have comment or be unexported (golint)
[Line 152](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L152): error var NotSupportedCategoryError should have name of the form ErrFoo (golint)
[Line 152](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L152): exported var NotSupportedCategoryError should have comment or be unexported (golint)
[Line 153](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L153): error var NotSupportedActionError should have name of the form ErrFoo (golint)
[Line 154](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L154):  error var InvalidCategoryError should have name of the form ErrFoo (golint)
[Line 155](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L155): error var CanNotRunDueToFailedConditionError should have name of the form ErrFoo (golint)
[Line 282](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/runtask_command.go#L282):  exported method RunCommand.Result should have comment or be unexported (golint)

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by knrt10** [comment]
I would like to work on this issue

**Comment by Akash4927** [comment]
@knrt10 
Sure, please go ahead.
