### ISSUE TITLE
Fix typo in handler_test.go

### ISSUE THREAD

**Issue by achiv** [openebs/openebs#1944]
Following typo errors should be fixed:
[Line 33](https://github.com/openebs/maya/blob/8db9da45ef236603fcd20672329f6f702f54d247/cmd/maya-apiserver/spc-watcher/handler_test.go#L33) : "wether" is a misspelling of "whether" (misspell)
[Line 48](https://github.com/openebs/maya/blob/8db9da45ef236603fcd20672329f6f702f54d247/cmd/maya-apiserver/spc-watcher/handler_test.go#L48) : "storagepoolcalim" is a misspelling of "storagepoolclaim" (misspell)
[Line 113](https://github.com/openebs/maya/blob/8db9da45ef236603fcd20672329f6f702f54d247/cmd/maya-apiserver/spc-watcher/handler_test.go#L113) : "storagepoolcalim" is a misspelling of "storagepoolclaim" (misspell)

I am taking up the task of solving this issue.

**Comment by kochurovro** [comment]
Kindly Check it https://github.com/openebs/maya/pull/567

**Comment by hugovk** [comment]
This file no longer exists, this issue can be closed.

https://github.com/openebs/maya/blob/8db9da45ef236603fcd20672329f6f702f54d247/cmd/maya-apiserver/spc-watcher/handler_test.go#L33

https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/handler_test.go
