### ISSUE TITLE
Fix grammatical issues in documentation of gokit.md

### ISSUE THREAD

**Issue by amiteshenoy** [openebs/openebs#1946]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 
 

**What happened**:
A few grammatical issues were found in gokit.md

**What you expected to happen**:
Grammatical issues to be fixed

**How to reproduce it (as minimally and precisely as possible)**:
openebs/contribute/general/gokit.md

**Anything else we need to know?**:

**Comment by amiteshenoy** [comment]
Fixing this issue

**Comment by sourabh1031** [comment]
@amiteshenoy i would like to take this up
