### ISSUE TITLE
Fix golint in math.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1952]
File: [math.go](https://github.com/openebs/maya/blob/master/types/v1/math.go)

```
Line 16: warning: package comment should be of the form "Package v1 ..." (golint)
Line 50: warning: comment on exported var MaxMilliValue should be of the form "MaxMilliValue ..." (golint)
```

**Comment by cTxplorer** [comment]
Sorry, @Akash4927, I forgot to ask fot assignment of the issue. Will make sure to confirm the same in future.

**Comment by Akash4927** [comment]
It's ok, but make sure from next time you ask to assign the issue.
