### ISSUE TITLE
Fix golint issues in pool.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1953]
File: [pool.go](https://github.com/openebs/maya/blob/master/cmd/cstor-pool-mgmt/pool/pool.go)

```
Line 38: warning: exported type PoolNamePrefix should have comment or be unexported (golint)
Line 41: warning: exported const PoolPrefix should have comment (or a comment on this block) or be unexported (golint)
Line 44: warning: exported var RunnerVar should have comment or be unexported (golint)
```

**Comment by debck** [comment]
I would like to work on this

**Comment by Akash4927** [comment]
Thanks @debck for picking the issue.

**Comment by tkivisik** [comment]
Hi, should this issue be closed?

**Comment by sarnava1** [comment]
@Akash4927 I want to work on this. Please assign this issue to me.

**Comment by sarnava1** [comment]
@Akash4927 I want to work on this. Please assign this issue to me.
