### ISSUE TITLE
Fix golint issue in resource.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1957]
File: [resource.go](https://github.com/openebs/maya/blob/master/pkg/client/k8s/v1alpha1/resource.go)

```
Line 17: warning: package comment should be of the form "Package v1alpha1 ..." (golint)
Line 59: warning: exported function Resource should have comment or be unexported (golint)
```

**Comment by albertogviana** [comment]
Sorry for the two pull requests, but I did not have the sign-off enabled before.

**Comment by Akash4927** [comment]
@albertogviana thanks for the PR, but please get issue assigned before raising PR
