### ISSUE TITLE
Fix golint issue in env_setter.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1958]
File: [env_setter.go](https://github.com/openebs/maya/blob/master/pkg/install/v1alpha1/env_setter.go)

```
Line 28: warning: exported const EnvSetSuccess should have comment (or a comment on this block) or be unexported (golint)
```

**Comment by Akash4927** [comment]
thanks @nhulongctk35 :+1:

**Comment by jamesa** [comment]
Is this still being worked on? If not I'd like to take it.

**Comment by Akash4927** [comment]
Sorry @jamesa, PR is already merged for this. Feel free to pick another issue.
