### ISSUE TITLE
Fix golint issue in signal_posix.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1964]
File: [signal_posix.go](https://github.com/openebs/maya/blob/master/pkg/signals/signal_posix.go)

```
Line 3: warning: package comment should be of the form "Package signals ..." (golint)
```

**Comment by ChrsMark** [comment]
I would like to fix this please.

**Comment by Akash4927** [comment]
@ChrsMark Thanks, please go ahead
