### ISSUE TITLE
Fix golint issue in doc.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1965]
File: [doc.go](https://github.com/openebs/maya/blob/master/types/doc.go)

```
Line 1: warning: package comment should be of the form "Package types ..." (golint)
```

**Comment by cpanato** [comment]
I will take this one, is that ok @Akash4927 ?

**Comment by cpanato** [comment]
PR: https://github.com/openebs/maya/pull/580

**Comment by Akash4927** [comment]
Thanks for the PR @cpanato
