### ISSUE TITLE
Fix golint issue in volume_template_engine.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1966]
File: [volume_template_engine.go](https://github.com/openebs/maya/blob/master/pkg/volume/volume_template_engine.go)

```
Line 17: warning: package comment should be of the form "Package volume ..." (golint)
```

**Comment by Akash4927** [comment]
@lologarithm Please get the issue assigned before raising PR. 
I am accepting this for now but please make sure you follow the procedure from next time.

**Comment by lologarithm** [comment]
Sorry about that -- ill make sure to do that next time.
