### ISSUE TITLE
Fix golint issue in jiva_volume_delete.go

### ISSUE THREAD

**Issue by qiell** [openebs/openebs#1967]
File: [jiva_volume_delete.go](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/jiva_volume_delete.go)

```
Line 21: warning: should not use dot imports (golint)
```

**Comment by knrt10** [comment]
@Akash4927 fixed via [#546](https://github.com/openebs/maya/pull/546)

**Comment by sourabh1031** [comment]
@qiell i will work on this

**Comment by vishnuitta** [comment]
Fix is available, hence closing
