### ISSUE TITLE
Fix golint issue in storage_pool_claim.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1969]
File: [storage_pool_claim.go](https://github.com/openebs/maya/blob/master/pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go)

```
Line 52: warning: comment on exported type StoragePoolClaimStatus should be of the form "StoragePoolClaimStatus ..." (with optional leading article) (golint)
```

**Comment by RajuKalidindi** [comment]
@Akash4927  I would like to work on this issue

**Comment by Akash4927** [comment]
@RajuKalidindi Sure, please go ahead
