### ISSUE TITLE
Format storagepool_template_engine.go file. 

### ISSUE THREAD

**Issue by RajatVaryani** [openebs/openebs#1973]
## Is this a BUG REPORT or FEATURE REQUEST?
Formatting change.  

 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
The formatting is not correct in pkg/storagepool/storagepool_template_engine.go of maya repository. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run make format. 

**Anything else we need to know?**:

**Comment by Pensu** [comment]
I can send a PR if it's still available.

**Comment by RajatVaryani** [comment]
@Pensu Go ahead!
