### ISSUE TITLE
self healing of jiva volumes after a K8s node/cluster failure

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#1977]
FEATURE REQUEST?

It is possible that K8s multiple worker nodes get into a faulty state due to disk-storage, memory or cpu pressure etc., depending on the application deployed. When cluster admin takes the corrective action, for example like adding additional disk space or deleting a pod that was causing memory/cpu hogging, the openebs pv backend pods should auto-recover. 

With 0.6, the replica pods have been provided with tolerations for the commonly known conditions. (however this might require the taintnodesbycondition - feature to be enabled by default in the cluster if using K8s 1.12 or earlier.)

While replica's are taken care of, the target pods is sometimes know to require a restart. It will be nice to have a liveness url provided by the target pods, that checks its own and its replica status. in case of an failed state, the liveness probe can trigger a restart of the pod.

**Comment by khushbuparakh** [comment]
If it's not closed. I would like to take this feature request up.

**Comment by utkarshmani1997** [comment]
@khushbuparakh thanks for showing interest in this issue. Please go ahead and let us know if you need any help.

Join us at [slack](https://openebs-community.slack.com/messages/C3NPGQ6G3) for more queries

**Comment by khushbuparakh** [comment]
@utkarshmani1997 possible to get an invite for slack?
