### ISSUE TITLE
oebs-cloud.sh script not allowiing me to create new bucket on AWS.

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#198]
I tried to create new bucket in AWS account using  **oebs-cloud.sh** script but it throughing an error. 

root@rafi-virtual-machine:~/openebs# ./oebs-cloud.sh --create-cluster-config
Creating Group on AWS for OpenEBS Users...
{
    "Group": {
        "Path": "/",
        "CreateDate": "2017-08-23T06:58:07.986Z",
        "GroupId": "AGPAJ4KQIS4QW6SRDJ4UW",
        "Arn": "arn:aws:iam::536403140708:group/openebsusers",
        "GroupName": "openebsusers"
    }
}
Creating S3 bucket to store cluster state...

**An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.**

In AWS account BUCKET name should be unique please modify the script to create a unique name for the new buckets.

**Comment by rafihnl** [comment]
After changing the script file  i'm able to create a new bucket with unique name.

But not able to create cluster configuration error as follow.

Creating Group on AWS for OpenEBS Users...
{
    "Group": {
        "Path": "/",
        "CreateDate": "2017-08-23T09:17:28.755Z",
        "GroupId": "AGPAIG5RPGSA27JZWF6H2",
        "Arn": "arn:aws:iam::536403140708:group/openebsusers",
        "GroupName": "openebsusers"
    }
}
Creating S3 bucket to store cluster state...
{
    "Location": "/openebs-k8s-hgtmrrk3dn-local-state-store"
}
Generating Public Key for Passwordless SSH
Generating public/private rsa key pair.
Your identification has been saved in /root/.ssh/id_rsa.
Your public key has been saved in /root/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:cszWEZ7TqmdEogKgvsLbhzygR40qxb06Wf66qumv9SI root@rafi-virtual-machine
The key's randomart image is:
+---[RSA 2048]----+
|.         .      |
|..       . +     |
|. .     . * .    |
|.  .   + + +     |
| o +. o S +      |
|..* +. + o       |
|o*o=..  . o      |
|=EB=+.   o       |
|=****=.          |
+----[SHA256]-----+
Generating terraform file(.tf)

**error reading cluster configuration "openebs.k8s.local": error reading s3://openebs-k8s-local-state-store/openebs.k8s.local/config: Could not retrieve location for AWS bucket openebs-k8s-local-state-store**
root@rafi-virtual-machine:~/openebs#

**Comment by rafihnl** [comment]
After updating the config file able to create instances on AWS account and running successfully.

**Comment by yudaykiran** [comment]
Fixed as part of the merge for PR #199
