### ISSUE TITLE
Mayactl volume list should show the storageclass to which the volume is pointing to

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1981]
FEATURE REQUEST
Currently mayactl volume list command has only four fields namespace,name,status and CAS type. Can one more field of storageclass can be added to this which can provide details of the volume size.
Current Format:
```
Namespace  Name                              Status   Type
---------  ----                              ------   ----
default    default-jiva-testvol-1-956581620  Running  jiva
```
Expected Format:
```
Namespace  Name                              Status   Type   StorageClass
---------  ----                              ------   ----   --------
default    default-jiva-testvol-1-956581620  Running  jiva   <StorageClass Name>
```
Resources:
-> File location: https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volumes_list.go
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Medium

**Comment by dreamerHarshit** [comment]
@ashishranjan738 i want try this issue

**Comment by mukeshmk** [comment]
@ashishranjan738 I want to work on this.

**Comment by mukeshmk** [comment]
@ashishranjan738  raised a [PR #637](https://github.com/openebs/maya/pull/637) fixing this issue.

**Comment by ashishranjan738** [comment]
added this
