### ISSUE TITLE
Add integration test to check successful creation,mount and deletion of a cstor volume

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1985]
*NOTE: BEFORE YOU PROCEED WITH THIS ISSUE PLEASE MAKE SURE THE CITF ISSUES ARE FIXED. The following issues are needed to be fixed: https://github.com/openebs/CITF/issues/38 , https://github.com/openebs/CITF/issues/37 , https://github.com/openebs/CITF/issues/36 , https://github.com/openebs/CITF/issues/35 , https://github.com/openebs/CITF/issues/34*

**Please comment if you want to work on this issue**
<hr>

**Assumptions**
* The test is going to be performed on <strike>minikube.</strike> a 3 node cluster. 
* OpeneEBS is assumed to be already setup i.e. the operator yaml is applied before executing test.
* Language: `golang`
* Framework: [CITF](https://github.com/openebs/CITF)
* Openebs version: `0.7.0`
<hr>

**Expected changes compared to the shell script tests**
1. The storage class should be <strike>renamed</strike> deleted after every test case.
2. Use a light weight image to test volume mount e.g. Busybox etc
<hr>

This test case corresponds to `test_1` [in this folder](https://github.com/openebs/maya/tree/master/hack/cstor_volume/test). Please read the `test_1/description` to know more about the test.
The `test-script.sh` script contains the actual logic to write test cases. This has to be converted.
The dependent resources such as storage class, pvc, and app yamls can be copied and modified if required.
<hr>

**Links to important resources**
* Refer to the file see how to [write an IT using CITF](https://github.com/openebs/maya/blob/master/integration-tests/cstor-pool/cstor_integration_test.go).
* [Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
* [CITF](https://github.com/openebs/CITF)
* [hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by geekyd** [comment]
I'm working on this :)

**Comment by geekyd** [comment]
PR https://github.com/openebs/maya/pull/765 :)
