### ISSUE TITLE
Mayactl cli should have bash auto completion

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1987]
FEATURE REQUEST
Currently there is no bash auto completion in mayactl cli. It would be a great enhancement if bash auto completion can be added. 

Resources:
-> File location: https://github.com/openebs/maya/blob/master/cmd/mayactl/
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Medium

**Comment by NerdyPepper** [comment]
### Suggestion

Since the program is completely written in Go, we can use https://github.com/posener/complete and make maya a self completing program.

[Here's](https://github.com/posener/complete/blob/master/example/self/main.go) a small example to go by.

**Comment by aswathkk** [comment]
I would like to work on this issue.

**Comment by princerachit** [comment]
@aswathkk sure go ahead.
