### ISSUE TITLE
Mayactl volume list should show the bound state of volumes

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1988]
FEATURE REQUEST
Currently mayactl volume list command has only four fields namespace,name,status and CAS type. Can one more field of bound state can be added to this which can provide details of the volume bound state.
Current Format:
```
Namespace  Name                              Status   Type
---------  ----                              ------   ----
default    default-jiva-testvol-1-956581620  Running  jiva
```
Expected Format:
```
Namespace  Name                              Status   Type   Bound State
---------  ----                              ------   ----   -----------
default    default-jiva-testvol-1-956581620  Running  jiva   <Volume state>
```
Resources:
-> File location: https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volumes_list.go
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Hard

**Comment by farhaanbukhsh** [comment]
Hey @ashishranjan738 I would like to take this up :)

**Comment by mptap** [comment]
@ashishranjan738 Have raised PR for this: https://github.com/openebs/maya/pull/638

**Comment by farhaanbukhsh** [comment]
I thought I was working on it 😅

**Comment by prateekpandey14** [comment]
Closing this as state of the volume comes from the kubectl , which can not be extracted using mayactl.
