### ISSUE TITLE
Mayactl info error message should be improved

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1991]
FEATURE REQUEST
Currently the mayactl volume info command gives error message something like this ```--volname is missing. Please specify a unique volumename``` can this be changed to ```error: --volname not specified.```.
Resources:
-> File location: https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volume_info.go
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by AdityaMisra** [comment]
Hi, Can I work on this issue?

**Comment by ashishranjan738** [comment]
Thanks for the PR @AdityaMisra
