### ISSUE TITLE
Mayactl stats error message should be improved

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#1992]
FEATURE REQUEST
Currently the mayactl volume stats command gives error message something like this ```--volname is missing. Please specify a unique volumename``` can this be changed to ```error: --volname not specified.```.
Resources:
-> File location: https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volume_stats.go
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by mukeshmk** [comment]
I would like to work on this.

**Comment by mukeshmk** [comment]
I have fixed this issue with the PR [maya/pull/620](https://github.com/openebs/maya/pull/620).
