### ISSUE TITLE
Fix cstyle error in src/assert.h

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#1996]
Repo: openebs/istgt
Branch: replication
File: src/assert.h
Steps to compile in: README.md
PR subject should be like: `fmt(cstyle): cstyle fixes in <filename>`

```
./src/assert.h: 109: preprocessor statement not in column 1
./src/assert.h: 113: preprocessor statement not in column 1
```

**Comment by avnish98** [comment]
I would like to work on this one

**Comment by vishnuitta** [comment]
Thanks for showing interest, and, please go ahead @avnish98

**Comment by avnish98** [comment]
@avnish98 Okay, I will open a work in progress pull request

**Comment by prateekpandey14** [comment]
As there is not activity related to this issue , making it `UpForGrabs` for other contributors
