### ISSUE TITLE
Remove passing resp http.ResponseWriter, req *http.Request objects

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1997]
**Please comment if you want to work on this issue**
<hr>

The file [snapshot_endpoint_v1alpha1.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/app/server/snapshot_endpoint_v1alpha1.go) uses `func (s *HTTPServer) snapshotRequest(resp http.ResponseWriter, req *http.Request) (interface{}, error)` as an http handler.

This method creates an object of `snapshotAPIOps`
```go
snapOp := &snapshotAPIOps{
		req:  req,
		resp: resp,
	}
```

It then invokes other methods `create,list,get,delete` for appropriate calls.
Since  `snapOp` already has `req,resp` objects we do not need to pass them explicitly to method.
It can be reused. Therefore, change the methods to use the `req,resp` property of `snapOps`.

```go
func (sOps *snapshotAPIOps) list(volName, namespace, casType string) (interface{}, error)
func (sOps *snapshotAPIOps) create() (interface{}, error)
func (sOps *snapshotAPIOps) get(snapName, volName, namespace, casType string) (interface{}, error)
func (sOps *snapshotAPIOps) delete(snapName, volName, namespace, casType string) (interface{}, error)
```

<hr>

**Links to important resources**
* [Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
* [hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by cfilby** [comment]
Hey, I'm potentially interested in resolving this issue and wanted to make sure I understood it. 

It sounds like a PR to resolve this issue would:

* Remove use of req/resp from the list, create, get and delete methods. 
* Update invocations of those functions to remove the req/resp responses. 

Is that correct? Thanks!

**Comment by pleum** [comment]
I would like to work on this.
