### ISSUE TITLE
Unset enviroment variables after every test

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#1999]
Address the review comment `https://github.com/openebs/maya/pull/527#discussion_r223043760` and `https://github.com/openebs/maya/pull/527#discussion_r223043928`

Use ```defer env.Unset("xxx")```
[File to be changed](https://github.com/openebs/maya/blob/master/pkg/snapshot/v1alpha1/snapshot_test.go)

**Please comment if you want to work on this issue**
<hr>

**Links to important resources**
* [Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
* [hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by rudbast** [comment]
Hi, i'd like to take this up if possible, some questions regarding the issue,
do we want to just unset the env var (as empty ?), or re-set the original value from before test started ?

**Comment by princerachit** [comment]
@rudbast you can work on this issue. Reset env to empty
