### ISSUE TITLE
A README inside k8s-demo folder

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#20]
This should contain info about various VMs that gets created by the Vagrantfile.
There should be explanation about each VM.
Info about typical operations carried out from each VM.

**Comment by yudaykiran** [comment]
Amit the Readme is ready, will submit it for a pull request.

**Comment by prateekpandey14** [comment]
Done

**Comment by prateekpandey14** [comment]
Thanks @yudaykiran
