### ISSUE TITLE
Change method name from getSnapshotObj() to casSnapshot()

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#2000]
Address comment https://github.com/openebs/maya/pull/527#discussion_r223024336

[File to be modified](https://github.com/openebs/maya/blob/master/pkg/task/v1alpha1/cstor_snapshot_command.go)
**Please comment if you want to work on this issue**
<hr>

**Links to important resources**
* [Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
* [hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by rishabhp99** [comment]
I would like to work on it.

**Comment by dreamerHarshit** [comment]
can i work on this?

**Comment by princerachit** [comment]
Yes please go ahead. @dreamerHarshit

**Comment by dreamerHarshit** [comment]
thanks @princerachit . Raised PR for this - https://github.com/openebs/maya/pull/621

**Comment by dreamerHarshit** [comment]
@princerachit PR of this issue is already merged, can we close this issue now?
