### ISSUE TITLE
Fix cstyle error in src/replication_log.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2001]
Repo: openebs/istgt
Branch: replication
File: src/replication_log.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/replication_log.h: 38: missing space between keyword and paren
./src/replication_log.h: 38: missing space after right brace
./src/replication_log.h: 40: #define followed by space instead of tab
./src/replication_log.h: 46: #define followed by space instead of tab
./src/replication_log.h: 52: #define followed by space instead of tab
./src/replication_log.h: 57: #define followed by space instead of tab
./src/replication_log.h: 64: #define followed by space instead of tab
./src/replication_log.h: 70: #define followed by space instead of tab

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by divyanshkul** [comment]
Working on this
