### ISSUE TITLE
Fix cstyle error in src/build.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2002]
Repo: openebs/istgt
Branch: replication
File: src/build.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/build.h: 29: #define followed by space instead of tab
./src/build.h: 31: #define followed by space instead of tab
./src/build.h: 32: #define followed by space instead of tab
./src/build.h: 33: #define followed by space instead of tab

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by Techievena** [comment]
Please assign me to this issue.
