### ISSUE TITLE
fix cstyle error src/istgt_conf.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2011]
Repo: openebs/istgt
Branch: replication
File: src/istgt_conf.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/istgt_conf.h: 29: #define followed by space instead of tab

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by vk2810** [comment]
I would like to work on this issue

**Comment by ashishranjan738** [comment]
sure @vk2810 go ahead

**Comment by vk2810** [comment]
Here is the PR for this : https://github.com/openebs/istgt/pull/97
