### ISSUE TITLE
fix cstyle error in ./src/ring_mempool.c

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2019]
Repo: openebs/istgt
Branch: replication
File: ./src/ring_mempool.c
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/ring_mempool.c: 16: line > 80 characters
./src/ring_mempool.c: 44: missing space between keyword and paren
./src/ring_mempool.c: 58: line > 80 characters
./src/ring_mempool.c: 68: unparenthesized return expression
./src/ring_mempool.c: 80: unparenthesized return expression
./src/ring_mempool.c: 99: unparenthesized return expression
./src/ring_mempool.c: 151: unneeded return at end of function
./src/ring_mempool.c: 157: unparenthesized return expression

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by aswathkk** [comment]
I would like to work on this one.

**Comment by hari4125862** [comment]
i would like to work on this issue
