### ISSUE TITLE
Styling and Typographical errors

### ISSUE THREAD

**Issue by NerdyPepper** [openebs/openebs#2023]
#### Avoid backtick ``` `` ```  substitution. Use `$( )` substitution instead
This permits easier nesting of commands.

#### qefs - Quote every f***ing substitution
This preserves the inner value of all characters.

#### Fix major typographical errors.
line 17 of `buildscripts/mayactl/build.sh`: `GIT_CIMMIT` -> `GIT_COMMIT`

**Comment by NerdyPepper** [comment]
I'm taking up this issue.

**Comment by ashishranjan738** [comment]
sure @NerdyPepper go ahead
