### ISSUE TITLE
fix cstyle error in ./src/mempool_test.c

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2030]
Repo: openebs/istgt
Branch: replication
File: ./src/mempool_test.c
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/mempool_test.c: 9: comma or semicolon preceded by blank
./src/mempool_test.c: 31: extra space between function name and left paren
./src/mempool_test.c: 31: space after cast
./src/mempool_test.c: 60: extra space between function name and left paren
./src/mempool_test.c: 60: space after cast
./src/mempool_test.c: 65: continuation should be indented 4 spaces
./src/mempool_test.c: 96: unparenthesized return expression
./src/mempool_test.c: 103: unparenthesized return expression

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by aswathkk** [comment]
I'm working on this

**Comment by ashishranjan738** [comment]
sure @aswathkk go ahead. Let me know if you need any help.

**Comment by aswathkk** [comment]
@ashishranjan738 
Here's my PR: https://github.com/openebs/istgt/pull/94

**Comment by ashishranjan738** [comment]
hey @aswathkk can you reference this issue in your PR

**Comment by aswathkk** [comment]
Just need to mention the issue number in the comment. Right?

**Comment by ashishranjan738** [comment]
yes
