### ISSUE TITLE
fix cstyle error in ./src/istgt_proto.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2031]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_proto.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/istgt_proto.h: 29: #define followed by space instead of tab
./src/istgt_proto.h: 60: #define followed by space instead of tab
./src/istgt_proto.h: 63: comma or semicolon followed by non-blank
./src/istgt_proto.h: 63: #define followed by space instead of tab
./src/istgt_proto.h: 66: comma or semicolon followed by non-blank
./src/istgt_proto.h: 66: #define followed by space instead of tab
./src/istgt_proto.h: 70: line > 80 characters
./src/istgt_proto.h: 71: line > 80 characters
./src/istgt_proto.h: 73: line > 80 characters
./src/istgt_proto.h: 80: line > 80 characters
./src/istgt_proto.h: 87: line > 80 characters
./src/istgt_proto.h: 88: line > 80 characters
./src/istgt_proto.h: 89: line > 80 characters
./src/istgt_proto.h: 91: line > 80 characters
./src/istgt_proto.h: 100: line > 80 characters
./src/istgt_proto.h: 107: line > 80 characters
./src/istgt_proto.h: 121: line > 80 characters
./src/istgt_proto.h: 125: line > 80 characters
./src/istgt_proto.h: 129: line > 80 characters
./src/istgt_proto.h: 145: line > 80 characters
./src/istgt_proto.h: 146: line > 80 characters
./src/istgt_proto.h: 160: line > 80 characters
./src/istgt_proto.h: 168: line > 80 characters
./src/istgt_proto.h: 169: line > 80 characters
./src/istgt_proto.h: 170: line > 80 characters
./src/istgt_proto.h: 171: line > 80 characters
./src/istgt_proto.h: 173: line > 80 characters
./src/istgt_proto.h: 176: line > 80 characters
./src/istgt_proto.h: 178: line > 80 characters
./src/istgt_proto.h: 178: unary * followed by space
./src/istgt_proto.h: 179: line > 80 characters
./src/istgt_proto.h: 179: unary * followed by space
./src/istgt_proto.h: 180: line > 80 characters
./src/istgt_proto.h: 182: line > 80 characters
./src/istgt_proto.h: 182: unary * followed by space
./src/istgt_proto.h: 186: line > 80 characters
./src/istgt_proto.h: 187: line > 80 characters
./src/istgt_proto.h: 189: line > 80 characters
./src/istgt_proto.h: 192: line > 80 characters
./src/istgt_proto.h: 201: line > 80 characters
./src/istgt_proto.h: 213: line > 80 characters
./src/istgt_proto.h: 237: unparenthesized return expression
./src/istgt_proto.h: 245: missing space after (void) cast
./src/istgt_proto.h: 253: extra space between function name and left paren
./src/istgt_proto.h: 260: unparenthesized return expression
./src/istgt_proto.h: 269: continuation should be indented 4 spaces
./src/istgt_proto.h: 270: extra space between function name and left paren
./src/istgt_proto.h: 282: unparenthesized return expression
./src/istgt_proto.h: 300: last line in file is blank

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by cbanupama** [comment]
I would like to work on this

**Comment by ashishranjan738** [comment]
sure @cbanupama go ahead. Let me know if you need any help.

**Comment by storymode7** [comment]
Hey, if nobody's working on it now, I'd like to take this up.
