### ISSUE TITLE
fix cstyle error in ./src/assert.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2032]
Repo: openebs/istgt
Branch: replication
File: ./src/assert.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>
```
./src/assert.h: 109: preprocessor statement not in column 1
./src/assert.h: 113: preprocessor statement not in column 1
```
Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by trinity0091** [comment]
let me take this?

**Comment by princerachit** [comment]
Sure @trinity0091
go ahead!
