### ISSUE TITLE
fix cstyle error in ./src/ring_mempool.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2033]
Repo: openebs/istgt
Branch: replication
File: ./src/ring_mempool.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/ring_mempool.h: 20: line > 80 characters
./src/ring_mempool.h: 21: line > 80 characters
./src/ring_mempool.h: 38: #define followed by space instead of tab

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by kkarth1k** [comment]
Please assign it to me

**Comment by ashishranjan738** [comment]
sure @kkarth1k go ahead. Let me know if you need any help.

**Comment by bharathpgp** [comment]
Assign to me if possible

**Comment by ashishranjan738** [comment]
I have removed the upforgrab label it means you are already assigned.

**Comment by vishnuitta** [comment]
@kkarth1k sorry that this issue is fixed with PR#100 itself. Hence, closing your PR.
