### ISSUE TITLE
fix cstyle error in ./src/istgt_ser_table.c

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2034]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_ser_table.c
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/istgt_ser_table.c: 1: improper first line of block comment
./src/istgt_ser_table.c: 1: missing blank after open comment
./src/istgt_ser_table.c: 2: extra space between function name and left paren
./src/istgt_ser_table.c: 23: extra space between function name and left paren
./src/istgt_ser_table.c: 26: extra space between function name and left paren
./src/istgt_ser_table.c: 30: missing blank after start comment
./src/istgt_ser_table.c: 31: line > 80 characters
./src/istgt_ser_table.c: 40: missing blank after open comment
./src/istgt_ser_table.c: 40: missing blank before close comment
./src/istgt_ser_table.c: 41: spaces instead of tabs
./src/istgt_ser_table.c: 42: spaces instead of tabs
./src/istgt_ser_table.c: 48: spaces instead of tabs
./src/istgt_ser_table.c: 49: spaces instead of tabs
./src/istgt_ser_table.c: 51: spaces instead of tabs
./src/istgt_ser_table.c: 52: spaces instead of tabs
./src/istgt_ser_table.c: 53: spaces instead of tabs
./src/istgt_ser_table.c: 54: missing blank after open comment
./src/istgt_ser_table.c: 54: missing blank before close comment
./src/istgt_ser_table.c: 86: #define followed by space instead of tab
./src/istgt_ser_table.c: 96: line > 80 characters
./src/istgt_ser_table.c: 96: missing blank after open comment
./src/istgt_ser_table.c: 96: missing blank before close comment
./src/istgt_ser_table.c: 97: line > 80 characters
./src/istgt_ser_table.c: 97: spaces instead of tabs
./src/istgt_ser_table.c: 97: missing blank after open comment
./src/istgt_ser_table.c: 97: missing space before left brace
./src/istgt_ser_table.c: 98: line > 80 characters
./src/istgt_ser_table.c: 98: missing blank after open comment
./src/istgt_ser_table.c: 98: missing space before left brace
./src/istgt_ser_table.c: 99: line > 80 characters
./src/istgt_ser_table.c: 99: missing blank after open comment
./src/istgt_ser_table.c: 99: missing space before left brace
./src/istgt_ser_table.c: 100: line > 80 characters
./src/istgt_ser_table.c: 100: missing blank after open comment
./src/istgt_ser_table.c: 100: missing space before left brace
./src/istgt_ser_table.c: 101: line > 80 characters
./src/istgt_ser_table.c: 101: missing blank after open comment
./src/istgt_ser_table.c: 101: missing space before left brace
./src/istgt_ser_table.c: 102: line > 80 characters
./src/istgt_ser_table.c: 102: missing blank after open comment
./src/istgt_ser_table.c: 102: missing space before left brace
./src/istgt_ser_table.c: 103: line > 80 characters
./src/istgt_ser_table.c: 103: missing blank after open comment
./src/istgt_ser_table.c: 103: missing space before left brace
./src/istgt_ser_table.c: 104: line > 80 characters
./src/istgt_ser_table.c: 104: spaces instead of tabs
./src/istgt_ser_table.c: 104: missing blank after open comment
./src/istgt_ser_table.c: 104: missing space before left brace
./src/istgt_ser_table.c: 105: line > 80 characters
./src/istgt_ser_table.c: 105: missing blank after open comment
./src/istgt_ser_table.c: 105: missing space before left brace
./src/istgt_ser_table.c: 106: line > 80 characters
./src/istgt_ser_table.c: 106: missing blank after open comment
./src/istgt_ser_table.c: 106: missing space before left brace
./src/istgt_ser_table.c: 107: line > 80 characters
./src/istgt_ser_table.c: 107: spaces instead of tabs
./src/istgt_ser_table.c: 107: missing blank after open comment
./src/istgt_ser_table.c: 107: missing space before left brace
./src/istgt_ser_table.c: 108: line > 80 characters
./src/istgt_ser_table.c: 108: missing blank after open comment
./src/istgt_ser_table.c: 108: missing space before left brace
./src/istgt_ser_table.c: 109: line > 80 characters
./src/istgt_ser_table.c: 109: missing blank after open comment
./src/istgt_ser_table.c: 109: missing space before left brace
./src/istgt_ser_table.c: 110: line > 80 characters
./src/istgt_ser_table.c: 110: missing blank after open comment
./src/istgt_ser_table.c: 110: missing space before left brace
./src/istgt_ser_table.c: 111: line > 80 characters
./src/istgt_ser_table.c: 111: missing blank after open comment
./src/istgt_ser_table.c: 111: missing space before left brace
./src/istgt_ser_table.c: 112: line > 80 characters
./src/istgt_ser_table.c: 112: missing blank after open comment
./src/istgt_ser_table.c: 112: missing blank before close comment
./src/istgt_ser_table.c: 112: missing space before left brace
./src/istgt_ser_table.c: 113: line > 80 characters
./src/istgt_ser_table.c: 113: missing blank after open comment
./src/istgt_ser_table.c: 113: missing space before left brace
./src/istgt_ser_table.c: 114: line > 80 characters
./src/istgt_ser_table.c: 114: missing blank after open comment
./src/istgt_ser_table.c: 114: missing space before left brace
./src/istgt_ser_table.c: 116: last line in file is blank

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by sushma-priyadharssini** [comment]
I would like to fix these.

**Comment by ashishranjan738** [comment]
sure @sushma-priyadharssini go ahead. Let me know if need any help.
