### ISSUE TITLE
fix cstyle error in ./src/istgt_integration_test.c

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2035]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_integration_test.c
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/istgt_integration_test.c: 27: indent by spaces instead of tabs
./src/istgt_integration_test.c: 28: indent by spaces instead of tabs
./src/istgt_integration_test.c: 29: indent by spaces instead of tabs
./src/istgt_integration_test.c: 30: indent by spaces instead of tabs
./src/istgt_integration_test.c: 31: indent by spaces instead of tabs
./src/istgt_integration_test.c: 32: indent by spaces instead of tabs
./src/istgt_integration_test.c: 33: indent by spaces instead of tabs
./src/istgt_integration_test.c: 95: space or tab at end of line
./src/istgt_integration_test.c: 184: line > 80 characters
./src/istgt_integration_test.c: 228: line > 80 characters
./src/istgt_integration_test.c: 229: line > 80 characters
./src/istgt_integration_test.c: 236: line > 80 characters
./src/istgt_integration_test.c: 243: line > 80 characters
./src/istgt_integration_test.c: 258: line > 80 characters
./src/istgt_integration_test.c: 285: extra space between function name and left paren
./src/istgt_integration_test.c: 288: extra space between function name and left paren
./src/istgt_integration_test.c: 317: space or tab at end of line
./src/istgt_integration_test.c: 402: line > 80 characters
./src/istgt_integration_test.c: 412: line > 80 characters
./src/istgt_integration_test.c: 416: line > 80 characters
./src/istgt_integration_test.c: 424: unparenthesized return expression
./src/istgt_integration_test.c: 444: line > 80 characters
./src/istgt_integration_test.c: 454: line > 80 characters
./src/istgt_integration_test.c: 458: line > 80 characters
./src/istgt_integration_test.c: 466: unparenthesized return expression
./src/istgt_integration_test.c: 482: line > 80 characters
./src/istgt_integration_test.c: 482: missing space between keyword and paren
./src/istgt_integration_test.c: 483: missing space between keyword and paren
./src/istgt_integration_test.c: 484: missing space between keyword and paren
./src/istgt_integration_test.c: 492: missing space between keyword and paren
./src/istgt_integration_test.c: 513: missing space between keyword and paren
./src/istgt_integration_test.c: 514: line > 80 characters
./src/istgt_integration_test.c: 514: missing space between keyword and paren
./src/istgt_integration_test.c: 515: missing space between keyword and paren
./src/istgt_integration_test.c: 515: whitespace before right paren
./src/istgt_integration_test.c: 516: missing space between keyword and paren
./src/istgt_integration_test.c: 524: missing space between keyword and paren
./src/istgt_integration_test.c: 564: line > 80 characters
./src/istgt_integration_test.c: 574: missing space between keyword and paren
./src/istgt_integration_test.c: 575: left brace starting a line
./src/istgt_integration_test.c: 609: unparenthesized return expression
./src/istgt_integration_test.c: 630: line > 80 characters
./src/istgt_integration_test.c: 640: missing space between keyword and paren
./src/istgt_integration_test.c: 641: left brace starting a line
./src/istgt_integration_test.c: 670: unparenthesized return expression
./src/istgt_integration_test.c: 692: line > 80 characters
./src/istgt_integration_test.c: 699: line > 80 characters
./src/istgt_integration_test.c: 721: unparenthesized return expression
./src/istgt_integration_test.c: 743: line > 80 characters
./src/istgt_integration_test.c: 750: line > 80 characters
./src/istgt_integration_test.c: 767: unparenthesized return expression
./src/istgt_integration_test.c: 795: missing space between keyword and paren
./src/istgt_integration_test.c: 798: line > 80 characters
./src/istgt_integration_test.c: 799: unparenthesized return expression
./src/istgt_integration_test.c: 804: line > 80 characters
./src/istgt_integration_test.c: 805: unparenthesized return expression
./src/istgt_integration_test.c: 808: unparenthesized return expression
./src/istgt_integration_test.c: 831: line > 80 characters
./src/istgt_integration_test.c: 835: missing blank after start comment
./src/istgt_integration_test.c: 836: line > 80 characters
./src/istgt_integration_test.c: 836: missing space between keyword and paren
./src/istgt_integration_test.c: 839: indent by spaces instead of tabs
./src/istgt_integration_test.c: 839: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 841: missing blank after start comment
./src/istgt_integration_test.c: 842: line > 80 characters
./src/istgt_integration_test.c: 842: missing space between keyword and paren
./src/istgt_integration_test.c: 865: space or tab at end of line
./src/istgt_integration_test.c: 880: missing space between keyword and paren
./src/istgt_integration_test.c: 900: line > 80 characters
./src/istgt_integration_test.c: 906: line > 80 characters
./src/istgt_integration_test.c: 912: line > 80 characters
./src/istgt_integration_test.c: 918: line > 80 characters
./src/istgt_integration_test.c: 935: line > 80 characters
./src/istgt_integration_test.c: 941: unparenthesized return expression
./src/istgt_integration_test.c: 973: space or tab at end of line
./src/istgt_integration_test.c: 990: line > 80 characters
./src/istgt_integration_test.c: 1104: space or tab at end of line
./src/istgt_integration_test.c: 1117: unparenthesized return expression
./src/istgt_integration_test.c: 1123: space or tab at end of line
./src/istgt_integration_test.c: 1141: missing space between keyword and paren
./src/istgt_integration_test.c: 1142: space or tab at end of line
./src/istgt_integration_test.c: 1143: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1143: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1148: space or tab at end of line
./src/istgt_integration_test.c: 1148: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1153: space or tab at end of line
./src/istgt_integration_test.c: 1155: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1155: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1157: line > 80 characters
./src/istgt_integration_test.c: 1162: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1162: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1165: line > 80 characters
./src/istgt_integration_test.c: 1171: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1171: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1172: spaces between tabs
./src/istgt_integration_test.c: 1176: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1176: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1178: spaces between tabs
./src/istgt_integration_test.c: 1178: spaces instead of tabs
./src/istgt_integration_test.c: 1178: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1184: line > 80 characters
./src/istgt_integration_test.c: 1189: space or tab at end of line
./src/istgt_integration_test.c: 1189: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1190: indent by spaces instead of tabs
./src/istgt_integration_test.c: 1190: non-continuation indented 4 spaces
./src/istgt_integration_test.c: 1193: line > 80 characters
./src/istgt_integration_test.c: 1203: unparenthesized return expression
./src/istgt_integration_test.c: 1230: unparenthesized return expression
./src/istgt_integration_test.c: 1241: unparenthesized return expression
./src/istgt_integration_test.c: 1256: unparenthesized return expression
./src/istgt_integration_test.c: 1266: unparenthesized return expression
./src/istgt_integration_test.c: 1277: unparenthesized return expression
./src/istgt_integration_test.c: 1280: line > 80 characters
./src/istgt_integration_test.c: 1291: line > 80 characters
./src/istgt_integration_test.c: 1300: line > 80 characters
./src/istgt_integration_test.c: 1319: line > 80 characters
./src/istgt_integration_test.c: 1325: unparenthesized return expression

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by cbanupama** [comment]
I would like to work on it

**Comment by ashishranjan738** [comment]
sure @cbanupama go ahead. Let me know if you need any help.

**Comment by rsiva911** [comment]
Hi, I would like to work on this if it is still open.
