### ISSUE TITLE
Correct the typo error "shhould" 

### ISSUE THREAD

**Issue by StanForever** [openebs/openebs#2038]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT
 Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT

**What happened**:
There was a typo error in README file on 2nd line at (https://github.com/openebs/maya/tree/master/hack/cstor-pool-test). 

**What you expected to happen**:
The correction should be "should" instead of "shhould". 

**How to reproduce it (as minimally and precisely as possible)**:
No need to reproduce. It's just a typo error.

**Anything else we need to know?**:
Nothing else.

I'd like to work on it. Can you please assign it me?

**Comment by sonasingh46** [comment]
Fixed as a part of PR
https://github.com/openebs/maya/pull/624/files
Thanks @StanForever
