### ISSUE TITLE
Each OpenEBS component should be labelled

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#204]
### Why?

- It helps in identification of OpenEBS components vs. Kubernetes components
- It helps in identification of OpenEBS components vs. 3rd-party components

### What are these components ?

- Maya API Service
- OpenEBS Volume Provisioner
- Maya Agent
- ??

##### Sample POD specs - TODO

```yaml
```

**Comment by kmova** [comment]
This is currently achieved if openebs is installed via helm charts or if the openebs components are installed within a namespace for openebs. 

If installed via kubectl, it makes sense to include some custom label.
