### ISSUE TITLE
fix cstyle error in ./src/mock_client.c

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2040]
Repo: openebs/istgt
Branch: replication
File: ./src/mock_client.c
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/mock_client.c: 34: line > 80 characters
./src/mock_client.c: 48: missing space between keyword and paren
./src/mock_client.c: 77: return type of function not on separate line
./src/mock_client.c: 82: unneeded return at end of function
./src/mock_client.c: 105: space or tab at end of line
./src/mock_client.c: 123: space or tab at end of line
./src/mock_client.c: 161: unparenthesized return expression
./src/mock_client.c: 184: space or tab at end of line
./src/mock_client.c: 240: unparenthesized return expression
./src/mock_client.c: 268: line > 80 characters
./src/mock_client.c: 290: unparenthesized return expression
./src/mock_client.c: 294: line > 80 characters
./src/mock_client.c: 318: line > 80 characters
./src/mock_client.c: 319: line > 80 characters
./src/mock_client.c: 341: line > 80 characters
./src/mock_client.c: 354: unneeded return at end of function
./src/mock_client.c: 365: indent by spaces instead of tabs
./src/mock_client.c: 365: non-continuation indented 4 spaces

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by NerdyPepper** [comment]
I will take up this issue.

**Comment by princerachit** [comment]
@NerdyPepper please go ahead!
