### ISSUE TITLE
fix cstyle error in ./src/istgt_log.h

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2041]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_log.h
Steps to compile in: README.md
PR subject should be like: fmt(cstyle): cstyle fixes in <filename>

./src/istgt_log.h: 29: #define followed by space instead of tab
./src/istgt_log.h: 37: #define followed by space instead of tab
./src/istgt_log.h: 41: #define followed by space instead of tab
./src/istgt_log.h: 44: #define followed by space instead of tab
./src/istgt_log.h: 47: spaces instead of tabs
./src/istgt_log.h: 47: #define followed by space instead of tab
./src/istgt_log.h: 48: #define followed by space instead of tab
./src/istgt_log.h: 49: #define followed by space instead of tab
./src/istgt_log.h: 50: spaces instead of tabs
./src/istgt_log.h: 50: #define followed by space instead of tab
./src/istgt_log.h: 51: #define followed by space instead of tab
./src/istgt_log.h: 52: #define followed by space instead of tab
./src/istgt_log.h: 53: spaces instead of tabs
./src/istgt_log.h: 53: #define followed by space instead of tab
./src/istgt_log.h: 54: spaces instead of tabs
./src/istgt_log.h: 54: #define followed by space instead of tab
./src/istgt_log.h: 55: spaces instead of tabs
./src/istgt_log.h: 55: #define followed by space instead of tab
./src/istgt_log.h: 56: #define followed by space instead of tab
./src/istgt_log.h: 57: #define followed by space instead of tab
./src/istgt_log.h: 58: #define followed by space instead of tab
./src/istgt_log.h: 65: #define followed by space instead of tab
./src/istgt_log.h: 66: #define followed by space instead of tab
./src/istgt_log.h: 67: #define followed by space instead of tab
./src/istgt_log.h: 68: #define followed by space instead of tab
./src/istgt_log.h: 70: #define followed by space instead of tab
./src/istgt_log.h: 74: spaces instead of tabs
./src/istgt_log.h: 78: line > 80 characters
./src/istgt_log.h: 78: tabs between spaces
./src/istgt_log.h: 78: #define followed by space instead of tab
./src/istgt_log.h: 79: line > 80 characters
./src/istgt_log.h: 79: #define followed by space instead of tab
./src/istgt_log.h: 80: line > 80 characters
./src/istgt_log.h: 80: tabs between spaces
./src/istgt_log.h: 80: #define followed by space instead of tab
./src/istgt_log.h: 81: line > 80 characters
./src/istgt_log.h: 81: tabs between spaces
./src/istgt_log.h: 81: #define followed by space instead of tab
./src/istgt_log.h: 83: #define followed by space instead of tab
./src/istgt_log.h: 86: line > 80 characters
./src/istgt_log.h: 91: #define followed by space instead of tab
./src/istgt_log.h: 98: #define followed by space instead of tab
./src/istgt_log.h: 103: line > 80 characters
./src/istgt_log.h: 104: line > 80 characters
./src/istgt_log.h: 105: line > 80 characters
./src/istgt_log.h: 106: line > 80 characters
./src/istgt_log.h: 107: line > 80 characters
./src/istgt_log.h: 113: line > 80 characters

Resources:
-> Countributers guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by kmjayadeep** [comment]
i will take this up

**Comment by ashishranjan738** [comment]
sure @kmjayadeep go ahead. Let me know if you need any help.
