### ISSUE TITLE
Use Github's recommended .gitignore files

### ISSUE THREAD

**Issue by NerdyPepper** [openebs/openebs#2042]
## Suggestion

Use [GitHub's `.gitignore` file templates](https://github.com/github/gitignore) instead of manually writing `.gitignore` files. They are more complete and serve as a good starting point for new projects.

### Golang's `.gitignore`
```
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, build with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out
```

**Comment by geekysrm** [comment]
I'd like to work on this.
