### ISSUE TITLE
Refactor build.sh in openebs/maya

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2045]
There are multiple components (or go binaries) being built from https://github.com/openebs/maya. Each of these component have their own build scripts located under:

```
#<maya-repo>/buildscripts/<component-name>/build.sh
#Example:
#<maya-repo>/buildscripts/mayactl/build.sh
#<maya-repo>/buildscripts/exporter/build.sh
#<maya-repo>/buildscripts/apiserver/build.sh
```

Much of the build.sh code is similar except for binary names and the main-go file. 

It will be good to have a refactored single build.sh file with the binary specific values pass as parameters to the script. A common build.sh file can be located under : `<maya-repo>/buildscripts/build.sh`

**Comment by salonirk11** [comment]
I would like to take this one up :D

**Comment by ashishranjan738** [comment]
sure @salonirk11 go ahead. Let me know if you need any help.

**Comment by salonirk11** [comment]
How do I test the refactored build.sh? I am unable to find commands in the installation guide which call the three different scripts.

**Comment by prateekpandey14** [comment]
@salonirk11  there is `GNUMakefile` targets which triggers individual buils.sh. You can run 
`make all` to run all of them in single shot or run single component using 
`make apiserver` to build Maya-Apiserver
 `make exporter` to build Maya volume exporter etc..

**Comment by salonirk11** [comment]
Please review PR [#643](https://github.com/openebs/maya/pull/643) for https://github.com/openebs/maya
