### ISSUE TITLE
Improve labels for openebs issues/PR

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#207]
OpenEBS need more labels which can elaborate issues and PR. It will help users to understand the priority and type. Contributors/Owners also need to tag the issues and PRs with appropriate labels. As of today, there are no labels on the issues! This should be followed across all the project repositories under OpenEBS org. 
Thanks!

**Comment by satyamz** [comment]
I have created the [list of labels](https://docs.google.com/document/d/1MQG-jNnW66PPOT7mnbUqy-6yAUksPd93OntNSxpq4HI/edit?usp=sharing). You add your suggestion as the comment.

**Comment by kmova** [comment]
@satyamz -- can you move the content from google-docs link to an file in this repository like ( say under - openebs/contribute/issues.md ). the community can then review and contribute towards the way issues are managed and maintained. 

some good reference:
- https://github.com/kubernetes/community/blob/master/contributors/devel/issues.md

**Comment by satyamz** [comment]
@kmova  Sure! I will do that. Thanks.
