### ISSUE TITLE
Not able to run Percona pod on AWS

### ISSUE THREAD

**Issue by vinayakbhat24** [openebs/openebs#208]
I am trying to deploy percona pod on AWS in hyperconverged mode. But getting an error "MountVolume.SetUp failed for volume "kubernetes.io/iscsi/49440e67-90fd-11e7-a7b1-02bd439d88ab-demo-vol1" (spec.Name: "demo-vol1") pod "49440e67-90fd-11e7-a7b1-02bd439d88ab" (UID: "49440e67-90fd-11e7-a7b1-02bd439d88ab") with: failed to get any path for iscsi disk".

**Comment by kmova** [comment]
It appears the minion hosts are missing the open-iscsi package. 

Also, could you provide the following details about your kubernetes cluster:
- What tools did you use to setup kubernetes?
- What is the host operating system for minion nodes?

**Comment by vinayakbhat24** [comment]
Yes. open-iscsi packages were missing in minion hosts.
Thanks for the help.  I am using Kops tool to setup kubernetes and Ubuntu OS.

**Comment by yudaykiran** [comment]
@vinayakbhat24 , did you use the OpenEBS cloud deployment script to set it up?

**Comment by vinayakbhat24** [comment]
Actually I am deploying kubernetes cluster by myself using kops. I am not using the script.

**Comment by yudaykiran** [comment]
Using the script its much simpler, it uses a image which already contains the iscsi packages, do join our slack channel, it much easier to discuss there.

**Comment by vinayakbhat24** [comment]
Ok. But I am testing it on already existing infrastructure.
