### ISSUE TITLE
Refactor duplicate code segments in in istgt_lu_ctl.c

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2083]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_lu_ctl.c
Steps to compile in: README.md
PR subject should be like: fmt(Refactor): Remove duplicate code segments in <filename>

Refactor following lines of code which are duplicated in the file istgt_lu_ctl.c:

([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L466-L494), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1907-L1936), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1347-L1376), [4](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1256-L1285), [5](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1833-L1862), [6](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1706-L1735))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1468-L1495), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1631-L1658), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1847-L1874), [4](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1921-L1948))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1347-L1388), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1907-L1948), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1256-L1297), [4](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1833-L1874))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1626-L1661), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1842-L1877), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1916-L1951))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1265-L1297), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1356-L1388), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1626-L1658))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1270-L1300), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1361-L1391), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_ctl.c#L1468-L1498))
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_disk.c#L4340-L4368), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_disk.c#L4438-L4466), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_disk.c#L4605-L4633))

Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating!

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖

**Comment by vardhanapoorv** [comment]
i would like to work on this

**Comment by ashishranjan738** [comment]
go ahead @vardhanapoorv . Let me know if you need any help.
