### ISSUE TITLE
Refactor duplicate code in istgtcontrol.c

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2084]
Repo: openebs/istgt
Branch: replication
File: ./src/istgt_lu_ctl.c
Steps to compile in: README.md
PR subject should be like: fmt(Refactor): Remove duplicate code segments in <filename>
control.c

Refactor following lines of code which are duplicated in the file istgtcontrol.c:
 ([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1323-L1354), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1228-L1259), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1278-L1310), [4](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1399-L1429), [5](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L969-L999), [6](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1443-L1474), [7](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1188-L1219), [8](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1136-L1168)).  
([1](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1323-L1351), [2](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1228-L1256), [3](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1278-L1306), [4](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1399-L1427), [5](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L969-L997), [6](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1443-L1471), [7](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1188-L1216), [8](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1136-L1164), [9](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgtcontrol.c#L1490-L1518))

Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating!

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖

**Comment by vardhanapoorv** [comment]
I would like to work on this

**Comment by manjusm** [comment]
I have done changes and compiled too.
