### ISSUE TITLE
Fix go lint in issue in maya/pkg/apis/openebs.io/v1alpha1/register.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2085]
File: [register.go](https://github.com/openebs/maya/blob/master/pkg/apis/openebs.io/v1alpha1/register.go)

```
Line 20: warning: comment on exported var SchemeBuilder should be of the form "SchemeBuilder ..." (golint)
Line 23: warning: exported var AddToScheme should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by mhutter** [comment]
Actually `golint ./cmd/... ./pkg/...` lists 168 problems, is there a reason this issue targets this file specifically?

**Comment by ashishranjan738** [comment]
These are easy first PR ones.

**Comment by cartinez** [comment]
I'd like to work on this.

**Comment by vishnuitta** [comment]
Not a valid bug anymore.. hence, closing this
