### ISSUE TITLE
Fix golint issue in register.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2086]
Following file has a lint issue:
[ maya/pkg/apis/openebs.io/register.go ](https://github.com/openebs/maya/blob/master/pkg/apis/openebs.io/register.go#L4)

The lint  issue is : 
```
Line 4: warning: exported const GroupName should have comment (or a comment on this block) or be unexported (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by bilal-mk** [comment]
I am working on this

**Comment by ashishranjan738** [comment]
go ahead @bilal-mk . Let me know if you need any help.
