### ISSUE TITLE
Fix golint issues in k8s/v1/doc.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2089]
Following file has a lint issue:
[maya/orchprovider/k8s/v1/doc.go](https://github.com/openebs/maya/blob/master/orchprovider/k8s/v1/doc.go#L1)

The lint  issue is : 
```
Line 1: warning: package comment should be of the form "Package v1 ..." (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by Pensu** [comment]
Sending a PR.

**Comment by ashishranjan738** [comment]
go ahead @Pensu . Let me know if you need any help.
