### ISSUE TITLE
Fix golint issue in maya/pkg/task/runner.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2090]
File: [maya/pkg/task/runner.go](https://github.com/openebs/maya/blob/master/pkg/task/runner.go)

```
Line 61: warning: exported function NewTaskGroupRunner should have comment or be unexported (golint)
Line 65: warning: exported method TaskGroupRunner.AddRunTask should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by abilash13** [comment]
I would like to grab this.

**Comment by ashishranjan738** [comment]
Thanxx @abilash13 for raising the PR.
