### ISSUE TITLE
Fix golint issues in signal.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2091]
Following file has a lint issue:
[maya/pkg/signals/signal.go](https://github.com/openebs/maya/blob/master/pkg/signals/signal.go#L1)

The lint  issue is : 
```
Line 1: warning: package comment should be of the form "Package signals ..." (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by bilal-mk** [comment]
I am working on this

**Comment by ashishranjan738** [comment]
go ahead @bilal-mk . Let me know if you need any help.
