### ISSUE TITLE
Fix golint issues in select_disk.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2092]
Following file has a lint issue:
[ maya/cmd/maya-apiserver/spc-watcher/select_disk.go ](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/select_disk.go)

The lint  issue is : 
```
Line 118: warning: error should be the last type when returning multiple items (golint)
Line 222: warning: error should be the last type when returning multiple items (golint)
Line 242: warning: error should be the last type when returning multiple items (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by damsehgal** [comment]
I am unable to fix the sign-off should I create another pull request?

**Comment by satyamz** [comment]
#707 fixed this!

**Comment by satyamz** [comment]
https://github.com/openebs/maya/pull/707 Fixes this!
