### ISSUE TITLE
Modularise istgt_lu_disk_execute(CONN_Ptr, ISTGT_LU_CMD_Ptr)

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2095]
Repo: openebs/istgt
Branch: replication
File: src/istgt_lu_disk.c
Steps to compile in: README.md
PR subject should be like: fmt(Refactor): Refactor <function_name> 

The following function istgt_lu_disk_execute(CONN_Ptr, ISTGT_LU_CMD_Ptr)
https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu_disk.c#L9072-L10923
can be refactored, which is a unit of **1537** lines of code.
Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖

**Comment by mittachaitu** [comment]
I would like to work on this issue.
