### ISSUE TITLE
Modularise istgt_lu_add_unit(ISTGT_Ptr, CF_SECTION)

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2096]
Repo: openebs/istgt
Branch: replication
File: src/istgt_lu.c
Steps to compile in: README.md
PR subject should be like: fmt(Refactor): Refactor <function_name> 

The following function istgt_lu_add_unit(ISTGT_Ptr, CF_SECTION)
https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu.c#L1372-L2285
can be refactored, which is a unit of **836** lines of code and **234** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating!  

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖

**Comment by kn-neelalohitha** [comment]
I would like to take up this issue.

**Comment by kn-neelalohitha** [comment]
@ashishranjan738 @vishnuitta  I need some help  regarding these lines `1855 to 2206` [here](https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu.c#L1372-L2285).Is it just updating and validating Logical Unit Numbers `(lu->lun)`details or doing something else enitirely different?
Thank you in advance!

**Comment by kn-neelalohitha** [comment]
@vishnuitta @payes Submitted PR:[#149](https://github.com/openebs/istgt/pull/149).
Please review and give feedback.
