### ISSUE TITLE
Fix lint issue in spc-watcher/handler.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2097]
Following file has a lint issue:
[maya/cmd/maya-apiserver/spc-watcher/handler.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/handler.go#L1)

The lint  issue is : 
```
Line 1: warning: package comment should be of the form "Package spc ..." (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by Pensu** [comment]
Sending a PR.
