### ISSUE TITLE
Fix go lint issues in amount.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2098]
Following file has a lint issue:
[ maya/types/v1/amount.go ](https://github.com/openebs/maya/blob/master/types/v1/amount.go)

The lint  issue is : 
```
Line 16: warning: package comment should be of the form "Package v1 ..." (golint)
Line 37: warning: exported const Nano should have comment (or a comment on this block) or be unexported (golint)
Line 49: warning: exported var Zero should have comment or be unexported (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by galihmelon** [comment]
I'd like to look into this

**Comment by ashishranjan738** [comment]
Thanxx @galihmelon for raising the PR.
