### ISSUE TITLE
Fix go lint issues in maya/cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2101]
File: [maya/cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go](https://github.com/openebs/maya/blob/master/cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go)

```
Line 1: warning: package comment should be of the form "Package poolcontroller ..." (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by nemaniarjun** [comment]
Taking this up!
