### ISSUE TITLE
Fix go lint issues in query.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2102]
Following file has a lint issue:
[maya/pkg/template/query.go](https://github.com/openebs/maya/blob/master/pkg/template/query.go)

The lint  issue is : 
```
        Line 44: warning: exported type JsonQuery should have comment or be unexported (golint)
        Line 53: warning: exported function NewJsonQuery should have comment or be unexported (golint)


```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by arijitAD** [comment]
I will take this.
