### ISSUE TITLE
Fix go lint issues in policy.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2106]
Following file has a lint issue:
[ maya/volume/policies/v1/policy.go ](https://github.com/openebs/maya/blob/master/volume/policies/v1/policy.go)

The lint  issue is : 
```
Line 63: warning: comment on exported function VolumeGenericPolicy should be of the form "VolumeGenericPolicy ..." (golint)
Line 79: warning: exported method Policy.Enforce should have comment or be unexported (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by ashishranjan738** [comment]
cool go ahead @arunvelsriram . Let me know if you need any help.
