### ISSUE TITLE
Fix golint issues in maya/cmd/maya-agent/app/command/device-format.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2108]
File: [maya/cmd/maya-agent/app/command/device-format.go](https://github.com/openebs/maya/blob/master/cmd/maya-agent/app/command/device-format.go)

```
Line 8: warning: comment on exported function NewSubCmdFormat should be of the form "NewSubCmdFormat ..." (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by Pensu** [comment]
Sending a PR.

**Comment by ashishranjan738** [comment]
@Pensu  go ahead. Let me know if you need any help.

**Comment by vishnuitta** [comment]
issue got fixed.. hence, closing the issue
