### ISSUE TITLE
Fix go lint issues in storagepool_delete.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2109]
Following file has a lint issue:
[ maya/cmd/maya-apiserver/spc-watcher/storagepool_delete.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/storagepool_delete.go)

The lint  issue is : 
```
Line 27: warning: exported function DeleteStoragePool should have comment or be unexported (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by Pensu** [comment]
Sending a PR.

**Comment by ashishranjan738** [comment]
@Pensu  go ahead. Let me know if you need any help.
