### ISSUE TITLE
Fix golint issues in util.go

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#2114]
Following file has a lint issue:
[ maya/types/v1/util.go ](https://github.com/openebs/maya/blob/master/types/v1/util.go)

The lint  issue is : 
```
Line 1016: warning: if block ends with a return statement, so drop this else and outdent its block (golint)
```

Help Links : 
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)

**Comment by MrWako** [comment]
I'll take a look at this one

**Comment by ashishranjan738** [comment]
sure @MrWako  go ahead. let me know if you need any help on [slack](http://slack.openebs.io).
