### ISSUE TITLE
Fix golint issues in maya/volume/provisioners/jiva/util.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2116]
File: [maya/volume/provisioners/jiva/util.go](https://github.com/openebs/maya/blob/master/volume/provisioners/jiva/util.go)

```
Line 1: warning: package comment should be of the form "Package jiva ..." (golint)
Line 18: warning: exported type JivaInterface should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by karthikramesh18** [comment]
i will try this one

**Comment by sachinmukherjee** [comment]
@ashishranjan738 anyone working on this issue?
