### ISSUE TITLE
Modularise istgt_lu_update_unit(ISTGT_LU_Ptr, CF_SECTION*)

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2118]
Repo: openebs/istgt
Branch: replication
File: src/istgt_lu.c
Steps to compile in: README.md
PR subject should be like: fmt(Refactor): Refactor <function_name> 

The following function istgt_lu_update_unit(ISTGT_LU_Ptr, CF_SECTION*) 
https://github.com/openebs/istgt/blob/62d20a1ae272b4604359d47af06c1ff701f65033/src/istgt_lu.c#L2329-L2858
can be refactored, which is a unit of **485** lines of code and **146** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖

**Comment by rsiva911** [comment]
Hi, can I take this up?

**Comment by sonasingh46** [comment]
Sure. Go ahead!
