### ISSUE TITLE
duplicate title in documentation 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#212]
The TOC at http://openebs.readthedocs.io/en/latest/, shows "Introducing OpenEBS" twice. It will be good to change to the following structure:

Getting Started
* Introducing OpenEBS
* Components and Architecture

**Comment by kmova** [comment]
The above PR #214 fixes the duplicate occurrence of "Introducing OpenEBS". 

However, the section headings still feel a bit out of flow/context. It might be a good idea to split the content from a single document to multiple documents and get to the following structure:

Getting Started
- Overview
- Components and Architecture
- Quick Install

Some comments on the content:
Overview: 
(At the end of the overview, point to the link to the Changelog / Project Tracker on GitHub)

Quick Install 
(We can assume that customer already have Kubernetes. Add the two steps that are sufficient to get openebs installed.
 - openiscsi install
 - running kubernetes operator
)
At the end of the Quick Install section, there can be references to using detailed tutorials from the next section, in case the customers don;t have kubernetes installed.

**Comment by adsrc** [comment]
@knova Is this issue still open? If yes, what exactly is the problem now?

**Comment by kmova** [comment]
@adsrc, the issue is still open.

Most of the changes are done, except for the following one:
- Change the title from Contributing to the OpenEBS Documentation -> OpenEBS Contribution Guide

The change is required in:
https://github.com/openebs/openebs/blob/master/documentation/source/contribute/contribute_openebs_doc.rst

Shall I assign this issue to you?

**Comment by adsrc** [comment]
@kmova yes please do. I'll finish it asap

**Comment by adsrc** [comment]
@kmova filed PR #447. Please review and let me know how I can follow up.

**Comment by kmova** [comment]
Thanks @adsrc. It looks good to me. We will have @mahebbar review before merging the PR.

**Comment by mahebbar** [comment]
Reviewed.
