### ISSUE TITLE
Fix golint issues in maya/volume/provisioners/registry.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2123]
File: [maya/volume/provisioners/registry.go](https://github.com/openebs/maya/blob/master/volume/provisioners/registry.go)

```
Line 1: warning: package comment should be of the form "Package provisioners ..." (golint)
Line 15: warning: exported type VolumeProvisionerFactory should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by m-nikhil** [comment]
Will work on this.

**Comment by m-nikhil** [comment]
Hey, What should I comment for this warning - Line 15: warning: exported type VolumeProvisionerFactory should have comment or be unexported (golint)

**Comment by vishnuitta** [comment]
not a valid issue anymore.. hence, closing this
