### ISSUE TITLE
Fix golint issues in maya/pkg/nethelper/ipcalc.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2125]
File: [maya/pkg/nethelper/ipcalc.go](https://github.com/openebs/maya/blob/master/pkg/nethelper/ipcalc.go)

```
Line 1: warning: package comment should be of the form "Package nethelper ..." (golint)
Line 71: warning: exported type Pong should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by diehard-coder** [comment]
I am working on this issue

**Comment by Axle7XStriker** [comment]
I would like to work on this one.

**Comment by ashishranjan738** [comment]
Hey @Axle7XStriker go ahead. Let me know if you need any help.
