### ISSUE TITLE
update the openebs repo - PR workflow 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#213]
openebs/openebs -- is an umbrella project for holding:
- documentation 
- e2e
- integration into container orchestrators 
  - install/setup scripts
  - example applications
- release management

making changes to each of the following might require the contributor to follow different guidelines. Explain how users can contribute by raising new PRs.

**Comment by kmova** [comment]
The following docs are not updated:
- e2e - https://github.com/openebs/openebs/blob/master/contribute/CONTRIBUTING-TO-CI-AND-E2E.md
- developer documentation - https://github.com/openebs/openebs/blob/master/contribute/CONTRIBUTING-TO-DEVELOPER-DOC.md
- user documentation 
 https://github.com/openebs/openebs/blob/master/documentation/source/contribute/contribute_openebs_doc.rst

Release Management and Application Folder contribution needs to be updated.

**Comment by kmova** [comment]
Now, that we have process in place for contributors to submit PRs, it is time to manage the submission process.

As soon as new PRs are submitted, the following are done:
- assign the PR to the submitter, so they have access to modify the labels or close the PR
- assign the Reviewers and set the status (label) as status/ready-for-review

The following is expected to happen with the PR based on the status:
- status/ready-for-review (has to be picked up by one of the reviewers and either move to approved or request changes. if changes are requested, then apply push it to status/work-in-progress)
- status/work-in-progress (the assignee of the PR is working on some changes requested by the reviewer. As soon as the changes are submitted, the status can be moved to - status/ready-for-review). 

The PR can be between the above two states, till it moves to Approval state by the reviewers. Once approved by the reviewer, it can be merged. 

Eventually an reviewbot (github-bot) can be in place that can take care of managing the review, approval and submission process. 

@AmitKumarDas -- any suggestions with the above process, before I put this into a flow chart in the contribute section.

**Comment by AmitKumarDas** [comment]
Where does one apply the status labels that are being talked about ?
Is it the issue corresponding to the PR

**Comment by kmova** [comment]
Till we have the bot, the status has to be added on the PR.. Once the bot is available, it can take the command through a comment.

**Comment by kmova** [comment]
All the docs are provided except for the release management. 

The release management scripts are undergoing changes as we consolidate the projects. The documentation will be tracked under : https://github.com/openebs/openebs/issues/209
