### ISSUE TITLE
Fix golint issues in maya/cmd/maya-apiserver/app/command/start.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2139]
File: [maya/cmd/maya-apiserver/app/command/start.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/app/command/start.go)

```
Line 97: warning: exported function NewCmdStart should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by Sagar2366** [comment]
Is this issue still open ?

**Comment by vishnuitta** [comment]
Not a valid one anymore.. hence closing
