### ISSUE TITLE
Fix golint issues in maya/cmd/maya-apiserver/app/server/server.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2140]
File: [maya/cmd/maya-apiserver/app/server/server.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/app/server/server.go)

```
Line 48: warning: comment on exported method MayaApiServer.BootstrapPlugins should be of the form "BootstrapPlugins ..." (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by md-yaseen** [comment]
I would like to solve this issue.

**Comment by ashishranjan738** [comment]
go ahea @md-yaseen . let me know if you need any help.
