### ISSUE TITLE
Fix golint issues in maya/cmd/maya-apiserver/app/server/http.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2142]
File: [maya/cmd/maya-apiserver/app/server/http.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/app/server/http.go)

```
Line 27: warning: exported const ErrGetMethodRequired should have comment (or a comment on this block) or be unexported (golint)
Line 294: warning: exported function CodedError should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by bilal-mk** [comment]
I would like to work on this

**Comment by ashishranjan738** [comment]
Hey @bilal-mk go ahead. let me know if you need any help.
