### ISSUE TITLE
Fix golint issues in maya/cmd/maya-apiserver/spc-watcher/start.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2143]
File: [maya/cmd/maya-apiserver/spc-watcher/start.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/start.go)

```
Line 41: warning: exported type QueueLoad should have comment or be unexported (golint)
Line 47: warning: exported function Start should have comment or be unexported (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by bharath-acchu** [comment]
I would try this

**Comment by ashishranjan738** [comment]
@bharath-acchu go ahead..let me know if you need any help

**Comment by vishnuitta** [comment]
Fixed already.. hence closing
