### ISSUE TITLE
Fix golint issues in maya/cmd/maya-agent/types/doc.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2148]
File: [maya/cmd/maya-agent/types/doc.go](https://github.com/openebs/maya/blob/master/cmd/maya-agent/types/doc.go)

```
Line 17: warning: package comment should be of the form "Package types ..." (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by bharath-acchu** [comment]
I would try this

**Comment by bharath-acchu** [comment]
im not doing this

**Comment by AishwaryaVarma** [comment]
i would like to work on it

**Comment by ashishranjan738** [comment]
cool @AishwaryaVarma go ahead as @bharath-acchu backed of. let me know if you need any help.
