### ISSUE TITLE
Fix golint issues in maya/pkg/template/template.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2154]
File: [maya/pkg/template/template.go](https://github.com/openebs/maya/blob/master/pkg/template/template.go)

```
Line 26: warning: should not use dot imports (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by kaustumbh7** [comment]
I would like to this issue
