### ISSUE TITLE
Fix golint issues in maya/orchprovider/orchestration.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2156]
File: [maya/orchprovider/orchestration.go](https://github.com/openebs/maya/blob/master/orchprovider/orchestration.go)

```
Line 1: warning: package comment should be of the form "Package orchprovider ..." (golint)
Line 13: warning: comment on exported type OrchestratorInterface should be of the form "OrchestratorInterface ..." (with optional leading article) (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by ABHIYANSHU** [comment]
I am interested in this issue.

**Comment by shahbazahmed1269** [comment]
@ABHIYANSHU, @ashishranjan738 Sorry for not informing, but I have already made required changes, making a PR in a bit.

**Comment by ABHIYANSHU** [comment]
I have committed the changes in the fix-docs branch
