### ISSUE TITLE
Fix golint issues in maya/cmd/maya-apiserver/spc-watcher/runner.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2158]
File: [maya/cmd/maya-apiserver/spc-watcher/runner.go](https://github.com/openebs/maya/blob/master/cmd/maya-apiserver/spc-watcher/runner.go)

```
Line 1: warning: package comment should be of the form "Package spc ..." (golint)

```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by AishwaryaVarma** [comment]
i would like to work on this

**Comment by ashishranjan738** [comment]
@AishwaryaVarma  go ahead. Let me know if you need any help.

**Comment by ABHIYANSHU** [comment]
Is anybody working on this.

**Comment by egurnov** [comment]
Fixed the issue, and a couple more linter problems.

**Comment by ABHIYANSHU** [comment]
Fixed linting issues on package. #717

**Comment by egurnov** [comment]
> Fixed linting issues on package. #717

@ABHIYANSHU Please pay attention to the links you post, your posts are misleading and create confusion between repositories. You may notice, that issues and actual development (and thus PRs) are located in different repos. This requires you to use cross-repository links. They need to include organization name, repo name and issue number in that repo.

You last post should have been `openebs/maya#717`: openebs/maya#717

If this seems too complex, please post full links, github will do the rest: `https://github.com/openebs/maya/pull/717` -> https://github.com/openebs/maya/pull/717

**Comment by AmitKumarDas** [comment]
This is no longer valid.

**Comment by mathagician** [comment]
@AmitKumarDas @ashishranjan738  The file spc-watcher/runner.go does not exist. The issue should be closed.
