### ISSUE TITLE
Fix golint issues in maya/pkg/task/fetch.go

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2160]
File: [maya/pkg/task/fetch.go](https://github.com/openebs/maya/blob/master/pkg/task/fetch.go)

```
Line 50: warning: comment on exported method K8sTaskSpecFetcher.Fetch should be of the form "Fetch ..." (golint)
```
Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Easy

**Comment by infiniteoverflow** [comment]
I would like to work on this

**Comment by ashishranjan738** [comment]
@infiniteoverflow  go ahead. Let me know if you need any help.

**Comment by ABHIYANSHU** [comment]
@infiniteoverflow I am also working on this. Please tell me if you have already completed it.

**Comment by infiniteoverflow** [comment]
Sorry i was about to finish it

**Comment by ABHIYANSHU** [comment]
Is this finished ?

**Comment by infiniteoverflow** [comment]
Sorry no...u can do it

**Comment by infiniteoverflow** [comment]
I am leaving this

**Comment by ABHIYANSHU** [comment]
I have completed this

**Comment by egurnov** [comment]
@ABHIYANSHU please provide a link back to this issue in your PR as openebs/openebs
#2160, this will reference the issue across repositories.

**Comment by ABHIYANSHU** [comment]
Completed #703

**Comment by egurnov** [comment]
I think you meant `openebs/maya#703` : openebs/maya#703
