### ISSUE TITLE
Create unit tests for bootstrapper.py

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#2162]
## Is this a BUG REPORT or FEATURE REQUEST?
  FEATURE REQUEST

**What happened**:

- Create unit tests for https://github.com/openebs/openebs/blob/master/e2e/ansible/files/bootstrapper.py

**Anything else we need to know?**:

- Refer: http://docs.gurock.com/testrail-api2/start

**Comment by ABHIYANSHU** [comment]
I am interested in this issue.

**Comment by mathagician** [comment]
@ksatchit The link  ` https://github.com/openebs/openebs/blob/master/e2e/ansible/files/bootstrapper.py` does not work
