### ISSUE TITLE
Create unit tests for testrail.py

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#2163]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Create unit tests for https://github.com/openebs/openebs/blob/master/e2e/ansible/files/testrail.py

**Anything else we need to know?**:

- Refer: https://github.com/openebs/openebs/blob/master/e2e/ansible/files/testrail.py

**Comment by ABHIYANSHU** [comment]
I am interested in this issue.

**Comment by surajkumarr12** [comment]
I like to work on this.

**Comment by mathagician** [comment]
@ksatchit the issue seems to be invalid as the file doe not exist.

**Comment by Physsix27** [comment]
Hey, @ksatchit is this use still valid or accurate, I can't find the file you are referring to. Can you update the description of it so I can work on it?
