### ISSUE TITLE
Create unit tests for updater.py

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#2164]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

- Create unit tests for https://github.com/openebs/openebs/blob/master/e2e/ansible/files/updater.py

**Anything else we need to know?**:

- Refer http://docs.gurock.com/testrail-api2/start

**Comment by ABHIYANSHU** [comment]
I am interested in this issue.

**Comment by rsiva911** [comment]
Can I take this up if this is open?

**Comment by cfreksen** [comment]
There did not seem to be any recent activity on this issue so I went ahead and tried to solve it in #2231
