### ISSUE TITLE
Add chaos test for istgt in ci/cstor_test.sh

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/openebs#2165]
Currently the test_cstor.sh test the working of istgt with docker images.It would be good to have some chaos tests like restarting the controller/replica in this script.

File: https://github.com/openebs/cstor/blob/master/ci/test_cstor.sh

Resources:
-> Contributors guide: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

Complexity: Medium

**Comment by farhaanbukhsh** [comment]
Hey @ashishranjan738 I would like to take this up, can you guide me how do I take it further?

**Comment by ashishranjan738** [comment]
go ahead @farhaanbukhsh. Let me know if you need any help.

**Comment by farhaanbukhsh** [comment]
what is meant by chaos testing?
