### ISSUE TITLE
Keep Unit Interfaces Small

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2167]
In openebs/jiva lot's of the unit interfaces such as parameters to the functions are more in the numbers. We can move the parameters into the proper structures and keep the unit interfaces smaller.
Guidelines (souce: Better code hub): 
- Keeping the number of parameters low makes units easier to understand and reuse.
- Limit the number of parameters per unit to at most 4.
- The number of parameters can be reduced by grouping related parameters into objects.
- Alternatively, try extracting parts of units that require fewer parameters.
 few of such functions are given in the image below: 
![image](https://user-images.githubusercontent.com/19219723/46917767-36969280-cfe8-11e8-8b40-18174a88f9fe.png)

Note :
- Create separate PR for each function

**Comment by kmjayadeep** [comment]
I would like to work on this

**Comment by kmjayadeep** [comment]
@utkarshmani1997 I will work on replica construct method first
The current header is :
 ```go
 func construct(readonly bool, size, sectorSize int64, dir, head string, backingFile *BackingFile, replicaType string) (*Replica, error)
```
I can think of two approaches, 
- Changing the entire parameters list to a new struct, ReplicaInfo
- Utilize the existing struct `Info` to change the function header to:
```go
func construct(readonly bool, dir string, info Info) (*Replica, error)
```
In this case only 4 params will be used from `Info` struct.

**Comment by kmjayadeep** [comment]
I've changed the construct method to take only one param, `dir` and it returns a replica object with dir and some empty params set. readOnly and replicaType are set from the caller functions `New` and `NewReadonly`
Remaining actions are moved to seperate struct method `Initialize`. I'm not sure this is a good practice or not. I've raised a pr anyway. Please review https://github.com/openebs/jiva/pull/137

**Comment by utkarshmani1997** [comment]
@kmjayadeep this is very quick. Really appreciate it.

**Comment by kmjayadeep** [comment]
Working on refactoring controller_client.Register
