### ISSUE TITLE
Refactor 21 lines occurring 3 times in process.go

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2168]
I've selected for refactoring 21 lines of code which are duplicated in 1 file(s) ([1](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/sync/agent/process.go#L338-L366), [2](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/sync/agent/process.go#L373-L401), [3](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/sync/agent/process.go#L412-L440)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by S4KH** [comment]
What I am thinking is to extract a function and put the logic that is duplicate.

**Comment by NaveenBellary** [comment]
@utkarshmani1997, @ashishranjan738 -- I'd like to take this up as part of Hacktoberfest

**Comment by NaveenBellary** [comment]
@utkarshmani1997, I'd like to take this up as part of hacktoberfest

**Comment by utkarshmani1997** [comment]
yeah @NaveenBellary please go ahead
