### ISSUE TITLE
Refactor 12 lines occurring 5 times in client.go

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2169]
I've selected for refactoring 12 lines of code which are duplicated in 1 file(s) ([1](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/replica/client/client.go#L261-L275), [2](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/replica/client/client.go#L371-L385), [3](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/replica/client/client.go#L226-L240), [4](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/replica/client/client.go#L337-L351), [5](https://github.com/openebs/jiva/blob/d57598c2c2506e79d6dbed410cae2a02fffde5ad/replica/client/client.go#L518-L532)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by codegagan** [comment]
will try to do

**Comment by codegagan** [comment]
Why is the issue on openebs project and not jiva ?

**Comment by utkarshmani1997** [comment]
Thanks @codegagan for picking up this issue. You can go ahead and let us know for any help.
We create the issues here to organise and manage the whole control and data plane from one place.

**Comment by m-nikhil** [comment]
@codegagan, hey are you working on this? if not, can I proceed with this issue.

**Comment by codegagan** [comment]
@m-nikhil I already have the PR for this.
