### ISSUE TITLE
Fix govet issues in maya/cmd/maya-apiserver/spc-watcher/

### ISSUE THREAD

**Issue by egurnov** [openebs/openebs#2172]
File: [openebs/maya/tree/master/cmd/maya-apiserver/spc-watcher](https://github.com/openebs/maya/tree/master/cmd/maya-apiserver/spc-watcher)

Fix the followinng govet issues:
```
maya/cmd/maya-apiserver/spc-watcher/handler.go:82::error: unreachable code (vet)
maya/cmd/maya-apiserver/spc-watcher/handler.go:88::error: unreachable code (vet)
maya/cmd/maya-apiserver/spc-watcher/handler.go:95::error: unreachable code (vet)
maya/cmd/maya-apiserver/spc-watcher/handler.go:104::error: unreachable code (vet)
maya/cmd/maya-apiserver/spc-watcher/storagepool_create.go:60::error: Info call has possible formatting directive %s (vet)
maya/cmd/maya-apiserver/spc-watcher/spc_lease_test.go:72::error: Errorf call has arguments but no formatting directives (vet)
```

As requested by @princerachit in openebs/maya#680

**Comment by pandyamarut** [comment]
please assign.

**Comment by egurnov** [comment]
I don't have permissions, could someone please assign this issue to me?

**Comment by AmitKumarDas** [comment]
@pandyamarut I have assigned to @egurnov mostly because @egurnov was not able to assign it while raising the issue.

**Comment by egurnov** [comment]
@AmitKumarDas This issue is already fixed and merged. I created it as requested by @princerachit to document changes introduced by openebs/maya#680 which were not covered by openebs/openebs#2158.

This issue can be closed now.
