### ISSUE TITLE
Secure the communication between istgt and zrepl in cStor

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2175]
Currently, cStor target (istgt) and cStor volume replica (zrepl) communicates by making a TCP connection, and read/writes data over this connection in plain text by following a protocol format.

This issue is to enable cStor target (istgt) to have secure communication between zrepl and itself.

**Comment by farhaanbukhsh** [comment]
@vishnuitta can you define secure connection? Do you want to encrypt the messages?

**Comment by vishnuitta** [comment]
Yes, we want to encrypt and decrypt the messages and the key management.
