### ISSUE TITLE
sync zfs repo to zfs-0.7.11 of upstream

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2182]
Currently, openebs zfs repo is on 0.7.9 of upstream.
This issue is to keep openebs zfs repo in sync with latest 0.7.x of upstream.

**Comment by bharathpgp** [comment]
Want to work on this

**Comment by ulshell** [comment]
I want to work on it

**Comment by payes** [comment]
@bharathpgp .. please go ahead.

**Comment by ulshell** [comment]
Where I will be getting this repo zfs

**Comment by bharathpgp** [comment]
openebs/zfs
