### ISSUE TITLE
Extend filters for cStor dynamic pool provisioning

### ISSUE THREAD

**Issue by tardich** [openebs/openebs#2183]
FEATURE REQUEST

cStor dynamic provisioning should be more flexible on filters for disk selection, as we may have many drives on an environment dedicated to different tasks. Such filters should include:

- Disk size
- device selection regex (like sd[e-n])
- disk labelling

that kind of thing, so subsequent disk addition would make cStor to assign the disk to the right pool

**Comment by AmitKumarDas** [comment]
I would love to see this feature as well. This might get into what openebs calls as automated pool provisioning _(i.e. knowledge of selecting disks versus forcing users to specify exact disk names)_.

**Comment by kmova** [comment]
With the change in NDM 0.4 to use the BlockDeviceClaim and BlockDevices, there is a mechanism to add the filters. In the current phase, the cstor schema is being changed as well and the focus is on getting the manual cstor provisioning to work. This requirement can be implemented along with the auto-cstor-provisioning schema.
