### ISSUE TITLE
Add comment in the function and fix linting issue

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#2192]
## FEATURE REQUEST?
 

**What you expected to happen**:

Add comments in the file and fix linting issue

Reference:- https://github.com/openebs/openebs/blob/master/e2e/ansible/files/bootstrapper.py

**Anything else we need to know?**:

**Comment by AdityaMisra** [comment]
I'll work on this.

**Comment by Sagar2366** [comment]
Is this issue still open ?
