### ISSUE TITLE
Add proper comment and fix linting issue

### ISSUE THREAD

**Issue by qiell** [openebs/openebs#2193]
## FEATURE REQUEST?

**What happened**:

-  Add comments and fix linting issue

https://github.com/openebs/openebs/blob/master/e2e/ansible/files/updater.py

**Anything else we need to know?**:

**Comment by nivedithapatil** [comment]
i would like to work on it .

**Comment by sonapraneeth-a** [comment]
Is it fixed by any chance Or else I would take it up?

**Comment by nivedithapatil** [comment]
No we are not working on it , you can go on with it
