### ISSUE TITLE
Refactor infoSnapshot(c *cli.Context)

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2194]
I've selected [**infoSnapshot(c *cli.Context)**](https://github.com/openebs/jiva/blob/a3c24b8889f9ddd8b75fa1b3665e36b124d38d58/app/snapshot.go#L195-L280) for refactoring, which is a unit of **76** lines of code and **16** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by geekyd** [comment]
I'll give this a GO :shipit:  :)

**Comment by flaixman** [comment]
Currently practicing GO. 

I will also try to make it :dancer:

**Comment by barthr** [comment]
Already have someone working on this? If not I could pick this up.
