### ISSUE TITLE
Refactor Controller.Start(addresses...string)

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2195]
I've selected [**Controller.Start(addresses...string)**](https://github.com/openebs/jiva/blob/a3c24b8889f9ddd8b75fa1b3665e36b124d38d58/controller/control.go#L713-L795) for refactoring, which is a unit of **74** lines of code and **17** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by RajatVaryani** [comment]
I can work on it.

**Comment by utkarshmani1997** [comment]
Closing this via openebs/jiva#236
