### ISSUE TITLE
Kubemaster-01 VM throws input/output error on machine restart.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#22]
Steps to Reproduce:

- vagrant up (inside the openebs/k8s-demo)
- master and minions are up and running
- reboot the machine ( with/without halting VMs)
- vagrant ssh kubemaster-01 fails with IO errors.

**Comment by kmova** [comment]
The issue seems to be with the virtualbox version used ( 5.0.24). 

Updated to 5.1.14 and restart resulted in bringing back the VMs with the K8s services running. 

https://www.pither.com/simon/blog/2017/01/09/virtualbox-disk-corruption
