### ISSUE TITLE
Hyperlink redirecting to github 

### ISSUE THREAD

**Issue by Sagar2366** [openebs/openebs#2207]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: FEATURE REQUEST

Clicking on here in Note section at https://docs.openebs.io/docs/next/supportedplatforms.html, it is redirecting to github link, please create another html page explaining same thing.

**Comment by Sagar2366** [comment]
Signed-off-by: Sagar Utekar sagarutekar2366@gmail.com

**Comment by farhaanbukhsh** [comment]
Can you please elaborate on it?

**Comment by Sagar2366** [comment]
Yes. You can see  [here](https://docs.openebs.io/docs/next/supportedplatforms.html) hyperlink on this page is redirecting to (github [link)](https://github.com/openebs/openebs-docs/blob/v0.5.3/docs/on_premise_solutions.md). Instead we can create another html page explaining all the steps mentioned in that doc which will looks good.
