### ISSUE TITLE
Add design to extract cas config using dedicated methods

### ISSUE THREAD

**Issue by princerachit** [openebs/openebs#2208]
This is not a code task. This is a design task. Once the design is accepted the same has to be implemented. The below description lacks complete design, some thought is required to come up with a solution.

A single CASConfig, a list of CASConfig should be treated as first-class citizens.
e.g.
pkg/casconfig/v1alpha1/casconfig.go
can have below
```go
type Options struct {}
type GetOptions {}

type casConfig struct {
  Key string
  Value string
}
type casConfigList []*casConfig

type GetCASConfig func(key string) casConfig

func CASConfig(fn []GetCASConfig, key string) casConfig {
    // iterate and execute all fn until a casConfig with given key is not found
    // return the casConfig as soon as you get one
}

// all below method are of type GetCASConfig
func CASConfigByENV(key string) casConfig {...}
func CASConfigBySC(key string) casConfig {...}
func CASConfigByLabels(key string) casConfig {...}
func CASConfigByAnnotations(key string) casConfig {...}
// ignore this method for now. More brain storming required for this: func CASConfigByCASType(..) casConfig {...}
```
Each above function
I assume all of the below as a single cas config:
- cas template name
- cas type
- any label or annotation key value pair used in openebs resources is a cas config

Refer comments on this PR https://github.com/openebs/maya/pull/753

Complexity: Medium

**Comment by ashishranjan738** [comment]
is this still available? seems like it is stale now.
