### ISSUE TITLE
Add output for `kubectl` commands in OpenEBS hyperconverged guide

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#223]
Add the outputs for `kubectl` given on `openebs on kubernetes` tutorial page.

**Comment by satyamz** [comment]
These two pages https://github.com/openebs/openebs/tree/master/k8s/hyperconverged

**Comment by kmova** [comment]
We will need to clear up some of these internal (initial) guides in favor of the documents at docs.openebs.io

**Comment by muratkars** [comment]
Addressed in the documentation:
https://docs.openebs.io/docs/next/onpremise.html#openebs-installation-hyperconverged-mode
