### ISSUE TITLE
Kubernetes dashboard not installed while installing OpenEBS with k8s on local machine

### ISSUE THREAD

**Issue by harisanker1780** [openebs/openebs#224]
Downloaded vagrant file from openebs/k8s/vagrant/1.7/ folder
After installing the cluster, logged in to kubemaster-01.

Execute below command:
kubectl get pods --all-namespaces

Output:
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   etcd-ubuntu-xenial                      1/1       Running   0          10m
kube-system   kube-apiserver-ubuntu-xenial            1/1       Running   0          10m
kube-system   kube-controller-manager-ubuntu-xenial   1/1       Running   0          10m
kube-system   kube-dns-2425271678-dpmb0               3/3       Running   0          12m
kube-system   kube-proxy-5gzgg                        1/1       Running   0          11m
kube-system   kube-scheduler-ubuntu-xenial            1/1       Running   0          10m
kube-system   weave-net-pt3qp                         2/2       Running   1          11m

This does not have dashboard installed.

**Comment by utkarshmani1997** [comment]
Just do `kubectl proxy` and dashboard will be launched on your machine.If you want to access it on your browser you need to do port forwarding or alternatively you can do `ssh -NL 8001:localhost:8001 ubuntu@ip_address` where ip_address is the ip of node and password is `ubuntu` . Now launch your browser on localhost:8001
