### ISSUE TITLE
Collection of anonymized usage data to understand OpenEBS usage

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#2257]
## Description:
- Collection of non user-identifying data to help OpenEBS core-developers understand cloud native storage usage patterns.
- OpenEBS version, k8s version, node arch, could be helpful in finding issues and building better feedback loops.
- This should be a voluntary feature for users.
- The data should be sent over a secure connection.

## Possible Solution
- Google Analytics should be a good starting point to get useful insight.

**Comment by kmova** [comment]
Basic implementation of collecting anonymous statistics is available. The details of the events and data sent in the events can be seen here: 
https://docs.google.com/document/d/1LrZH5HfTJ8IKl5I7abL5Y9b925DNeB3hjXoAAjKSm1M/edit?usp=sharing
