### ISSUE TITLE
Re-organize the documentation for Setup  

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#228]
How about we have the following structure:

- Overview -(describes how to pick the right solution for the user) similar to https://kubernetes.io/docs/setup/pick-right-solution/
- Cloud Solutions
  * Amazon Cloud
  * Google Cloud
- On-Premise Solution
  * Baremetal 
     - Vagrant - Install on a single host using VirtualBox
  * Multi-node setup using Ansible

**Comment by mahebbar** [comment]
The Overview and Cloud Solutions section headings are updated and On-Premise Solution section includes Using Vagrant and Using Ansible which as discussed with Kiran is a better heading. Hence, closing this issue.
