### ISSUE TITLE
(cStor sparse) Rescheduled application pod stuck in 'ContainerCreating' state when application pod is deleted 

### ISSUE THREAD

**Issue by mittachaitu** [openebs/openebs#2282]
## Description

Application pod stuck in 'ContainerCreating' state when application pod is deleted while performing write operations on mount point of application.

## Expected Behavior

When the application pod is deleted then application pod should reschedule on any of the nodes which are available. 

## Current Behavior

Application pod stuck in 'ContainerCreating' state, when the application pod is deleted while performing write operations on the application.

## Steps to Reproduce

- Deployed percona application on cstor-sparse disk with liveness check.
- Once the application pod is running with active IO.
- Exec into the pod and perform write operations using `dd` on mount point after that delete the application pod.
- Then new application pod which is created remains in 'ContainerCreating' state.
## Environment 
* `Cluster`: AWS(1 Master node and 3 worker nodes) 
Logs and kubectl command results are attached in below files:
[apply_load_del_pod_containercreating_bak.txt](https://github.com/openebs/openebs/files/2585595/apply_load_del_pod_containercreating_bak.txt)
[apply_load_del_pod_containercreating.txt](https://github.com/openebs/openebs/files/2585596/apply_load_del_pod_containercreating.txt)

**Comment by pawanpraka1** [comment]
IOs are slow on sparse disk as we have 3 filesystem in this case (client side fs(ext4) ---> zrepl side fs (zfs) ----> sparse file (ext4)). IOs are taking time in case of cstor-sparse pool so unmount is taking time.

**Comment by vishnuitta** [comment]
Below are observations after doing pod delete with 'dd' running:
- mysqld, which is with PID 1, goes into defunct state (probably after 30 seconds. If not, atleast much before the old pod gets terminated)
- 'dd if=/dev/urandom of=/var/lib/mysql/file1 bs=4k count=500k' command will be running and `ps` output shows its status as 'D', which means, its waiting on disk.
- Running 'dd' in a loop with count as 1 and with seek=$i, pod gets terminated faster.
- parent of 'dd' command will be a docker-shim process, and, is different from the parent of mysqld. But, parents of 'dd' and 'mysqld' have the same parent.
- Enabling logging at istgt to get the ongoing IO information shows that continuous 1MB length requests are coming to target (there are not many sync cache CDBs)
- Behavior is same with 1 luworker and also when the volume is in degraded mode (i.e., when all the replicas are in degraded mode)
- When replicas are in degraded mode, it takes much more time for the old pod to get terminated. This points to - slow serving of IOs is causing this issue.
