### ISSUE TITLE
Minimum amount of nodes

### ISSUE THREAD

**Issue by runningman84** [openebs/openebs#2286]
Is it possible to run openebs on a arm64 master node without any big disks and two amd64 nodes with local disks? The goal would be to withstand a single node outage. 

Right know it is quite difficult to understand what the hard requirements are.

**Comment by muratkars** [comment]
Hi @runningman84 - to be able have HA quorum you would need minimum 3 nodes. You can run OpenEBS  with local disks or even on sparse files on the SD card.

**Comment by runningman84** [comment]
But does the quorum needs the same size? For example my two amd64 nodes provide 100gb sad storage do I need the same size in my arm64 raspberry master?

**Comment by runningman84** [comment]
Which means all three nodes have to have the same storage space if you want to use all available space. It would be cool if the quorum would not need the same space. I don't think that every use case needs the whole data replicated three times.

**Comment by muratkars** [comment]
Closing this since there is no action needed at this time.
Here are some references and links to design considerations:
https://docs.openebs.io/k8supgrades.html#volume-replica-quorum-requirement
https://docs.openebs.io/docs/next/casengines.html
