### ISSUE TITLE
 Error: failed to start container "openebs-ndm": Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by JoeyX-u** [openebs/openebs#2287]
# helm install stable/openebs --name openebs --namespace openebs
[root@master1 openebs]# kubectl get pods -n openebs
NAME                                        READY   STATUS              RESTARTS   AGE
openebs-apiserver-b6b946f85-v5fnn           1/1     Running             0          10s
openebs-ndm-5pscb                                     0/1     RunContainerError   1          10s
openebs-ndm-789v2                                     0/1     RunContainerError   1          10s
openebs-provisioner-59d6798d7-xrgt6         1/1     Running             0          10s
openebs-snapshot-operator-f6cdd4b64-wrc8p   0/2     ContainerCreating   0          10s
[root@master1 openebs]# kubectl describe pod openebs-ndm-5pscb -n openebs

Events:
  Type     Reason     Age                From                    Message
  ----     ------     ----               ----                    -------
  Normal   Scheduled  31s                default-scheduler       Successfully assigned openebs/openebs-ndm-5pscb to kubernetes-19
  Warning  Failed     30s                kubelet, kubernetes-19  Error: failed to start container "openebs-ndm": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/proc/1/mounts\\\" to rootfs \\\"/data/docker/overlay2/38b29acfcd6edd34172b3d9b0a869d0760658ca615397f283174b91639170e15/merged\\\" at \\\"/data/docker/overlay2/38b29acfcd6edd34172b3d9b0a869d0760658ca615397f283174b91639170e15/merged/host/mounts\\\" caused \\\"permission denied\\\"\"": unknown
  Warning  Failed     29s                kubelet, kubernetes-19  Error: failed to start container "openebs-ndm": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/proc/1/mounts\\\" to rootfs \\\"/data/docker/overlay2/ade41dd07fe69628aa8d6057e31a50b31e4434f3d6bc3785a54973e15c2edeca/merged\\\" at \\\"/data/docker/overlay2/ade41dd07fe69628aa8d6057e31a50b31e4434f3d6bc3785a54973e15c2edeca/merged/host/mounts\\\" caused \\\"permission denied\\\"\"": unknown
  Warning  BackOff    22s                kubelet, kubernetes-19  Back-off restarting failed container
  Normal   Pulled     11s (x3 over 30s)  kubelet, kubernetes-19  Container image "quay.io/openebs/node-disk-manager-amd64:v0.2.0" already present on machine
  Normal   Created    11s (x3 over 30s)  kubelet, kubernetes-19  Created container
  Warning  Failed     11s                kubelet, kubernetes-19  Error: failed to start container "openebs-ndm": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/proc/1/mounts\\\" to rootfs \\\"/data/docker/overlay2/7f82d62c2ba71008d7937b4ff16e43eb02d4c01c92bc0ff80cfa1a77b144a609/merged\\\" at \\\"/data/docker/overlay2/7f82d62c2ba71008d7937b4ff16e43eb02d4c01c92bc0ff80cfa1a77b144a609/merged/host/mounts\\\" caused \\\"permission denied\\\"\"": unknown

**Comment by kmova** [comment]
@JoeyX-u - are you running on CentOS? Is selinux turned on?

**Comment by JoeyX-u** [comment]
> @JoeyX-u - are you running on CentOS? Is selinux turned on?
Yeah, it’s alright, thank you, I look so stupid.

**Comment by JoeyX-u** [comment]
> @JoeyX-u - are you running on CentOS? Is selinux turned on?
You are right, thank you, I look so stupid.

**Comment by useltmann** [comment]
does it mean i have to disable selinux in order to run openebs?

**Comment by akhilerm** [comment]
@useltmann. Yes, currently you will have to disable selinux, since openebs-ndm need to run in  privileged mode for accessing `/dev` and `/sys` directories.  
We are tracking this issue under [NDM privilege issue](https://github.com/openebs/node-disk-manager/issues/203)

**Comment by sebastien-prudhomme** [comment]
@akhilerm Mounting /proc inside the container works fine with Selinux.

If "/host/mounts" was not hardcoded in NDM, it should be possible to mount /proc in container /host/proc for instance and use /host/proc/1/mounts inside the container.

**Comment by akhilerm** [comment]
@sebastien-prudhomme  That's a good point. Thanks.  I will raise a PR to mount `/proc` as read only, and change the hard-coded path to `/host/proc/1/mounts`.
