### ISSUE TITLE
Memory consumption of jiva controller is increasing rapidly > 1G memory on Packet and GCP platforms

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/openebs#2308]
## Description

- Memory consumption of jiva controller is increasing rapidly > 1G memory on Packet and GCP platforms.
This behavior is observed on openebs.ci pipeline running on Packet
https://gitlab.openebs.ci/openebs/e2e-packet/pipelines/5176

Kibana logs:

https://e2elogs.openebs.ci/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:2232',display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-3h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'215dd610-a155-11e8-8b91-cb4b4edefe7f',key:commit_id,negate:!f,params:(query:e76f8ca8351991dc597cef5cdcccaf3c877646c2,type:phrase),type:phrase,value:e76f8ca8351991dc597cef5cdcccaf3c877646c2),query:(match:(commit_id:(query:e76f8ca8351991dc597cef5cdcccaf3c877646c2,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'215dd610-a155-11e8-8b91-cb4b4edefe7f',key:pipeline_id,negate:!f,params:(query:'5176',type:phrase),type:phrase,value:'5176'),query:(match:(pipeline_id:(query:'5176',type:phrase))))),index:'8d3d6950-ea9c-11e8-8cff-a161f7929609',interval:auto,query:(language:lucene,query:memcheck),sort:!('@timestamp',desc))

## Steps to Reproduce

- Deployed test pvc on jiva.
- Ran dd profile to consume ~3GB of data.

## Screenshots

Log Snippet:
```
TASK [Run python script for memory usage validation it takes couple of minutes] ***
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "python test-mem.py memleak 800", "delta": "0:03:30.023145", "end": "2018-11-29 09:04:42.815199", "failed_when_result": true, "rc": 0, "start": "2018-11-29 09:01:12.792054", "stderr": "", "stderr_lines": [], "stdout": "kubectl get pod -n memleak -l openebs.io/controller=jiva-controller --no-headers | awk '{print $1}'\npvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-con\nkubectl exec pvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-788cf9fff8-xqmpt -c pvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-con -n memleak -- pmap -x 1 | awk ''/total'/ {print $3}'\n984.2890625 MB\n984.2890625 MB\n984.2890625 MB\n984.2890625 MB\n984.2890625 MB\n984.2890625 MB\n1056.29296875 MB\n1056.29296875 MB\n1128.296875 MB\n1128.296875 MB\n[984.2890625, 984.2890625, 984.2890625, 984.2890625, 984.2890625, 984.2890625, 1056.29296875, 1056.29296875, 1128.296875, 1128.296875]\nFail", "stdout_lines": ["kubectl get pod -n memleak -l openebs.io/controller=jiva-controller --no-headers | awk '{print $1}'", "pvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-con", "kubectl exec pvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-788cf9fff8-xqmpt -c pvc-185509fd-f3b5-11e8-835b-0cc47ae5459a-ctrl-con -n memleak -- pmap -x 1 | awk ''/total'/ {print $3}'", "984.2890625 MB", "984.2890625 MB", "984.2890625 MB", "984.2890625 MB", "984.2890625 MB", "984.2890625 MB", "1056.29296875 MB", "1056.29296875 MB", "1128.296875 MB", "1128.296875 MB", "[984.2890625, 984.2890625, 984.2890625, 984.2890625, 984.2890625, 984.2890625, 1056.29296875, 1056.29296875, 1128.296875, 1128.296875]", "Fail"]}
```
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:
```
- name: OPENEBS_VERSION
          value: master
        - name: MAYA_APISERVER_IMAGE
          value: openebs/m-apiserver:b036e466
        - name: OPENEBS_PROVISIONER_IMAGE
          value: null
        - name: OPENEBS_SNAPSHOT_CONTROLLER_IMAGE
          value: null
        - name: OPENEBS_SNAPSHOT_PROVISIONER_IMAGE
          value: null
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: openebs/jiva:8fac39c
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: openebs/jiva:8fac39c
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: openebs/m-exporter:b036e466
```

**Comment by mittachaitu** [comment]
@gprasath @payes Is it still happening in the latest version of OpenEBS?
