### ISSUE TITLE
add support for kernel mode zfs

### ISSUE THREAD

**Issue by slpcat** [openebs/openebs#2309]
zfs is should be installed on host, and zfs.ko ,zfs, zpool,zrepl are always avilable on all hosts

cstor can run with uzfs or zfs.ko,but not the both.

**Comment by gila** [comment]
In order for us to do that, we need to make some changes to our target implementation such that it writes to the ZVOL layer. Right now we directly use the DMU API.

**Comment by mittachaitu** [comment]
Hi @slpcat, OpenEBS implemented kernel-mode zfs with storage engine **[zfs-localpv](https://github.com/openebs/zfs-localpv)** as name itself describe local. This issue can be re-open at any time for further discussions.
