### ISSUE TITLE
Replica fails to open after restart

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2311]
## Description

If we write the data randomly over > 2G, replica fails to open upon restart and controller get timeout intermittently.

## Expected Behavior

Replica should be opened after registration instantly

## Current Behavior

Replica failed to open on request from controller after restart.

## Possible Solution

This issue is arising due to PreloadLunMap function which generate offsets after reading extents by sending ioctl. We need to optimize the system call and opening process by setting some flags that preload is done upon restart.

## Steps to Reproduce

Added a ansible playbook in litmus project to reproduce this issue. openebs/litmus#384

**Comment by kmova** [comment]
Merged to 0.8.x for 0.8.1 release.
