### ISSUE TITLE
Update EFK stack demo with the latest changes

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2313]
## Description
In the current example, when [fluentd-ds.yaml](https://github.com/muratkars/openebs/blob/muratk-efkpatch/k8s/demo/efk/fluentd/fluentd-ds.yaml) is applied the pods gets into crashlooping due to read-only ConfigMap file.

Kubernetes team making ConfigMaps read only by default. 
In response to kubernetes/kubernetes#60814, they have pushed kubernetes/kubernetes#58720. This was patched into the latest versions of 1.7.x, 1.8.x, and 1.9.x. It made mounted ConfigMaps ready only by default.

## Expected Behavior
```
fluentd-8xv8m                                                       1/1     Running   0          3m4s
fluentd-qppmw                                                       1/1     Running   0          3m4s
fluentd-rp5tk                                                       1/1     Running   0          3m4s
```

## Current Behavior
```
kube-system   fluentd-7vpxj                                                       0/1     CrashLoopBackOff   6          9m27s
kube-system   fluentd-mksz4                                                       0/1     CrashLoopBackOff   6          9m27s
kube-system   fluentd-zr2dh                                                       0/1     CrashLoopBackOff   6          9m27s
```

## Possible Solution
Please update the EFK stack demo with the latest versions and update the yaml files.

## Workaround:
As a quick workaround I've added env variables suggested [here](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/90) and pods got deployed successfully.

**Comment by joshuacox** [comment]
@muratkars the [solution](https://gist.github.com/joshuacox/5ad88cacf44ddc10fae1c3cb74a6f336) you posted in the slack worked for me.
