### ISSUE TITLE
[cStor] Application went to RO state on performing target container (istgt) kill with gke

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#2319]
## Description
Application went to RO state on performing Target container (istgt) kill in gke. 

## Expected Behavior
Application should not go to RO state during Target container kill

## Current Behavior
Application went to RO state on performing target pod delete
## Steps to Reproduce
- Deploy Percona application with liveness Running.
- Once the applicatiion is up and running with active IO's.
- Performed Target pod istgt container kill. Wait 120s - 180s after target container kill

Kubectl version : -
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.10.6-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Note:
 - In Aws cluster the target Container (istgt) kill. The application pod will be remain in RW state only. Its not went to RO state

kubectl version of AWS :
```
ubuntu@ip-10-0-1-70:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
 ## Screenshots

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

[tgt-istgt.log](https://github.com/openebs/openebs/files/2656189/tgt-istgt.log)
[tgt-volume-mgmt.log](https://github.com/openebs/openebs/files/2656190/tgt-volume-mgmt.log)
[tgt-maya-volume-exporter.log](https://github.com/openebs/openebs/files/2656194/tgt-maya-volume-exporter.log)
[cstor-pool-1.log](https://github.com/openebs/openebs/files/2656196/cstor-pool-1.log)
[cstor-pool-1-mgmt.log](https://github.com/openebs/openebs/files/2656200/cstor-pool-1-mgmt.log)
[cstor-pool-2.log](https://github.com/openebs/openebs/files/2656201/cstor-pool-2.log)
[cstor-pool-2-mgmt.log](https://github.com/openebs/openebs/files/2656202/cstor-pool-2-mgmt.log)
[cstor-pool-3.log](https://github.com/openebs/openebs/files/2656203/cstor-pool-3.log)
[cstor-pool-3-mgmt.log](https://github.com/openebs/openebs/files/2656204/cstor-pool-3-mgmt.log)

**Comment by vishnuitta** [comment]
synretry count is usually 6, which takes > 2 minutes.
kernel retries syn at 1, 2, 4, 8, 16, 32 and 64 seconds.
Due to some reason, even if listener at tgt is available,
until these retransmissions are complete and start new connect
call, connection is not getting established, and this is causing
volume to get into RO state.
By reducing synretries to 3, next connect call is made in less
than 20 seconds.

**Comment by vishnuitta** [comment]
This fix is available with PR: https://github.com/openebs/zfs/pull/173
