### ISSUE TITLE
Support StatefulSet with >1 replicas and Pod/Target pod affinity

### ISSUE THREAD

**Issue by shturman** [openebs/openebs#2321]
## Description

We have a setup (6 nodes with ephemeral SSD connected in GKE k8s 1.10) and application `StatefulSet` with 6 replicas. 
The plan is to map 1 to 1 application pod to a node and use `target affinity` to keep jiva target pods on the same node as the application pod. 
Data replication/redundancy solved at an application layer so we need the only 1 replica setup for storage class.

Would be good to support such a scenario.
Possible applications: `Mongo` replica set, `Minio` in HA mode, etc.

**Comment by AmitKumarDas** [comment]
https://github.com/openebs/openebs/issues/2389

**Comment by ashishranjan738** [comment]
PR for this has been merged https://github.com/openebs/maya/pull/966.

**Comment by kmova** [comment]
The above PR helps achieve this for cStor volumes. Keeping this open to get this implemented for Jiva volumes.

**Comment by mittachaitu** [comment]
@payes is this issue still valid with the latest versions of OpenEBS? Can **[openebs/jiva-csi](https://github.com/openebs/jiva-csi)** solves this problem?
