### ISSUE TITLE
Does openebs support volume expansion?

### ISSUE THREAD

**Issue by BalaBalaYi** [openebs/openebs#2323]
## Description

For now the storage class which used by openebs is (AllowVolumeExpansion is unset):
```
Provisioner:           openebs.io/provisioner-iscsi
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

**Comment by rgembalik** [comment]
This is a great question! I'd love to see some official response to it. It would help me greatly to manage OpenEBS volumes with `allowVolumeExpansion`.

Anyone?

**Comment by mittachaitu** [comment]
OpenEBS supports volume expansion by editing the PVC size via CSI(for both cStor and jiva volumes).
For more information on how to expand volumes backed by cStor [click here](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/resize.md).
