### ISSUE TITLE
OpenEBS deployment on Azure Cloud.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#234]
Create workflow documentation and automation script for deploying OpenEBS on Azure cloud.

**Comment by ksatchit** [comment]
Good references : 

https://docs.microsoft.com/en-gb/azure/container-service/kubernetes/container-service-kubernetes-walkthrough

https://docs.microsoft.com/en-gb/azure/container-service/kubernetes/

**Comment by yudaykiran** [comment]
Azure Container Service (AKS) is still in its early stages and the while trying out OpenEBS deployment on the Kubernetes cluster, created using AKS, the following impediments were identified.
1. AKS web interface is not very user-friendly.
2. The documents for AKS are still not very descriptive.
3. Most of the tasks are easier to do only when using the Azure CLI.
4. The base operating system that is used in the VMs of the AKS Kubernetes Cluster is a bare minimal variant of Ubuntu/Jessie.
5. There is no way to define the size of the VMs that you would want the nodes to have.
6. By default ISCSI is not available in the VMs and installing ISCSI is also a problem as the sudo command is unavailable.

For now, based on my analysis, AKS needs more time to evolve as a good deployment option for OpenEBS.

**Comment by ksatchit** [comment]
Based on the analysis above, moving this issue out of the current milestone to be considered as a future item.

**Comment by kmova** [comment]
This is currently tracked under : https://github.com/openebs/openebs/issues/1335
