### ISSUE TITLE
OpenEBS operator && Monitoring by running applications on openebs

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#2343]
## What is OpenEBS operator?
A helper/tool for human operator. This operator manages the lifecycle of OpenEBS on a Kubernetes cluster.

It will automate the process of Install, Update, Upgrade, Probe / Checks, Self Healing, and more with respect to OpenEBS. It will work continuously to put the system into the desired state. A desired state is typically a list of desired specification(s) declared by the human operator to let OpenEBS function at its prime.

As part of helping the human operator, OpenEBS Operator should be able to accomplish following activities w.r.t to components required for proper functioning of OpenEBS:

- Install
- Reinstall i.e. Update with new configurations
- Upgrade 
- Downgrade
- Un-Install
- **Monitor** -- _Targeted_
- Self Heal
- Config Management (includes validation)

**Comment by AmitKumarDas** [comment]
### Use Case -- Resource Monitoring
As part of helping the human operator, openebs operator should notify if any component has been experiencing any issues. For example: Is volume provisioner component unable to provision volume, are there any errors experienced in api server, are openebs volumes getting into ReadOnly state, does the cluster nodes have required installations for openebs volume provisioning to execute successfully, and so on. Each of these features may be a different component (in kubernetes terminology it can be a specific controller). All these monitoring controllers can be a part of openebs operator.

#### Iscsi Monitor Use Case (Priority #1, Q1 2019):
As an admin I would like to know if my storage nodes in kubernetes cluster are fit to expose iscsi volumes.

As part of initial release of OpenEBS operator, it will have iscsi monitor controller. Iscsi monitor controller will initially have checks to find the presence or absence of iscsi tools in specific nodes of the kubernetes cluster.

**Comment by mittachaitu** [comment]
@prateekpandey14 do we need to look/enhance this issue?
