### ISSUE TITLE
Change Scrub job image location

### ISSUE THREAD

**Issue by jbrongtr** [openebs/openebs#2344]
## Description
When I delete a PVC, the scrub job launches as expected. The issue is that our environment is air-gaped and we need to load images beforehand into a docker repo. The pod job hangs waiting to pull the image from the internet.

## Expected Behavior
The ability to change the openebs-tools image location

## Current Behavior
Image is pulled from internet

## Possible Solution
Possibly allow ops to edit this image location along with the main images in the values.yaml.

## Steps to Reproduce
- Deploy stable helm chart
- Deploy jiva pvc
- Delete jiva pvc
- kubectl get pods (verify pod creating hangs at ImagePullBackOff)

**Comment by kmova** [comment]
@jbrongtr Thanks for raising this issue. Will bring this up in the upcoming contributor weekly meeting and schedule this for fixing.

**Comment by kmova** [comment]
Fixed in 0.8.2 

https://github.com/openebs/maya/commit/74756cab5fef79feaf5cdad9d1af108ddd84a652

**Comment by jbrongtr** [comment]
Thanks for your hard work guys!
