### ISSUE TITLE
Don't automatically email people who star OpenEBS on Github

### ISSUE THREAD

**Issue by t3hmrman** [openebs/openebs#2345]
## Description
[Someone on HN reported being emailed (at their personal email) immediately after starring the repository](https://news.ycombinator.com/item?id=18900439), in [a thread](https://news.ycombinator.com/threads?id=hardwaresofton#18900439) where I mentioned the benefits of using OpenEBS. 

## Expected Behavior
Emails should not have been used. 

## Current Behavior
Email is sent to people who star the project.

## Possible Solution
Don't spam people when they star openebs on Github

## Steps to Reproduce
0. Exist
1. Have a Github account
2. Star `openebs`

## Screenshots
This was discovered in [a thread on HackerNews](https://news.ycombinator.com/threads?id=hardwaresofton#18900439) (in a thread where I mentioned the benefits of OpenEBS).

**Comment by AmitKumarDas** [comment]
@t3hmrman We are looking into this. Sorry for all the trouble you have faced so far.

**Comment by umamukkara** [comment]
Thank you @t3hmrman for the alert. We have disabled the email trigger.

**Comment by t3hmrman** [comment]
Hey absolutely no problem guys -- I [am really happy with openebs](https://vadosware.io/post/kicking-the-tires-on-openebs-for-cluster-storage/) thanks so much for the hard work you're putting in, hate to see someone dismiss it out of hand because of something silly like a misplaced email. 

I wonder if moving the newsletter signup above the community page on https://openebs.io would help? If the landing page repo is open I could make the PR.

**Comment by t3hmrman** [comment]
Closing since the email trigger is removed!
