### ISSUE TITLE
newly created volume fails with fsck errors on centos 7.5

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2355]
As per the issue #1276 , there were some instances of fsck errors on centos 7.0 with jiva version < 0.7.0 , we have added support for SYNC_CACHE in jiva after that this issue was not observed on centos 7.0 . But since centos 7.5 is not available yet on GKE or AMAZON platforms, we were unable to test the same. So once its get available on these platforms we can test and verify whether volume is still mounting with fsck errors.

**Comment by mittachaitu** [comment]
@payes @gprasath Are we hitting this error with the latest versions of OpenEBS? Do we need to re-open this issue?
