### ISSUE TITLE
Need steps for configuring OpenEBS in offline mode ( without internete access on Kubernetes Cluster)

### ISSUE THREAD

**Issue by kasim457** [openebs/openebs#2356]
Hi Team,

I request you to provide detailed steps of how to configure openEBS in offline mode.

Thanks,
Kasim -/-

**Comment by mittachaitu** [comment]
Hi @kasim457, This has been addressed via https://github.com/openebs/charts/pull/57. Can you verify and re-open this issue if that doesn't fit the use case?
