### ISSUE TITLE
Upgrade to 0.8.1 involves setting a quorum property to true

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2357]
As part of supporting ephemeral disks with cStor volumes (related to bug https://github.com/openebs/openebs/issues/2271), there is need to take care of upgrade scenario to 0.8.1.

'quorum' property of existing volumes need to be set to 'true' after upgrading cstor-pool pods to 0.8.1

**Comment by AmitKumarDas** [comment]
Done
