### ISSUE TITLE
Support for zpool clear command.

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#2359]
Upon attaching the disk again to a pool, resilvering should be triggered. Restarting pool pod doesn't trigger resilvering.  zpool clear command should be executed for clearing the errors and start resilvering. Currently, this command is not supported.

zpool online command triggered resilvering but the errors are not getting cleared.

**Comment by mittachaitu** [comment]
This has been addressed via day-2-operations on cStor and related documents can be found [here](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/cspc/mirror/mirror.md#disk-replacement-by-removing-disk).
