### ISSUE TITLE
Automatic resilver in case of disk detach/attach in mirror/raid pools

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2363]
From 0.8.1, with this bug https://github.com/openebs/openebs/issues/2336 being fixed, resilvering can be triggered manually by doing 'zpool clear <poolname>' once the disks are attached back.

This feature request is to trigger pool resilvering automatically once the disks are attached back.

**Comment by kmova** [comment]
With  0.8.1, the following can occur when disks are detached and re-attached. 
(a) A liveness check has been added to the cstor pool pods. If the cstor pool is of type stripe and if the disk is unattached, the pool pod will continuously be restarted. The user will need to re-attach the disk. 
(b) In case of mirror and a single disk has failed, the IO will continue. After the disk is re-attached, the user will have to exec into the pod and issue a `zpool clear` command. 
(c) In case of mirror and both disks have failed, the pool pod will continuously be restarted. The user will need to re-attach the disk. 

In case of (a) and (c), after re-attaching the disk if the IOs don't continue - a manual `zpool clear` command will have to be issued.

**Comment by mittachaitu** [comment]
@vishnuitta will this happen with the latest versions of OpenEBS? @nsathyaseelan Can you help to validate this? Once the validation is done issue can be closed.
