### ISSUE TITLE
Day2 Operations -- Disk Replacement

### ISSUE THREAD

**Issue by ajeshbaby** [openebs/openebs#2366]
## Description

Disk Replacement Support is required in case of the following 
-- For failed disks in a RAID group (Faulted)
-- Proactive replacement for disks which can get failed (Based on error count / latency factors etc .. manual)

## Context

Disks replacement for a pool is must as part of Day2 Operations.  
Disks would go bad in a pool, the disk replacement is required for the pool  type as mentioned below
-- RAIDZx(1,2,3) 
-- Mirror 
For pool type Striped, Disk replacement support not required.

**Comment by mittachaitu** [comment]
This has been addressed via cstor-operators and further information can be found [here](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/cspc/mirror/mirror.md#disk-replacement-by-removing-disk).
