### ISSUE TITLE
Support for increase or decrease volume replication count

### ISSUE THREAD

**Issue by ajeshbaby** [openebs/openebs#2369]
## Usecase
Work flow to increase or decrease of volume replica count
This would be useful in scenarios where user will configure volume replica with less replica count say count=1 and increase number of replica in production to count-=3.
Other case wrongly configured higher replica can be reduced to lower number with out bringing down the application.

**Comment by mittachaitu** [comment]
This has been addressed via CSI-Volumes and user can increase and decrease the replication factor for cStor by following [scale-up-doc](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/migration.md#1-scale-the-cstorvolumereplicas-to-desired-node) and [scale-down-doc](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/migration.md#2-scale-down-the-cstorvolumereplicas-from-unwanted-nodes).

@payes Is it a valid use case for JIVA?

**Comment by adubkov** [comment]
How to increase replica counts for jiva?
I initially provisioned pvc with `replicationFactor: 1`. Now I add second instance in a cluster and bumber `replicationFactor: 2` in jivavolumepolicies, but only newly provisioned pvc have 2 replicas. App previously created volumes remained with single replica.

**Comment by adubkov** [comment]
Ok I think I got it. In openebs pvc backed by statefulset in openebs namespace, so I just bumped number of statefulsets replicas and it seems to help.

**Comment by adubkov** [comment]
Ah, I had to change `REPLICATION_FACTOR` envvar in associated pvc controller deployment... now seems to work.
