### ISSUE TITLE
Add content for Baremetal section under Setup section

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#237]
Add procedure for baremetal setup

**Comment by mahebbar** [comment]
@Rupeshiya You can add it under Setup - Installation section -"Installing OpenEBS on Bare Metal"

**Comment by mahebbar** [comment]
@Rupeshiya When will you be able to work on this?

**Comment by kmova** [comment]
No separate documentation is required for running OpenEBS as long as the common prerequisites are met. 

(This issue was created earlier, when the K8s install also was being documented as part of the OpenEBS installation.)
