### ISSUE TITLE
Ability to expand cStor pool when the underlying disk capacity is increased

### ISSUE THREAD

**Issue by ibreakthecloud** [openebs/openebs#2372]
## Description

When the uderlying GPD was resized to increase the capacity, cStor pool was not able to detect the changes.

## Context

I had an GPD of 10 GiB attached to one of the nodes in GKE cluster, spc pool was created. After expanding my GPD from 10GiB to 15GiB the new changes were not reflected in SPC pool capacity, although upon restarting NDM pods the disk value was updated but not the SPC pool value.

## Possible Solution

Tried some manual steps involving execing inside the spc pod and running `zpool` and `parted` command helped and was able to expand the pool size of utilize the extra space.

**Comment by prateekpandey14** [comment]
Steps to upgrade the single disk pool can be found [here](https://gist.github.com/prateekpandey14/f2a30b3f246fd5b44fdfb545185f78b4 ) . 
I will suggest to use first in your development setup to get familiar with the steps.

**Comment by kmova** [comment]
In case the sparse pools are full, the following workaround can be tried. Note that this works only if the pools are still online. 

Resize the sparse img, by executing the following in the ssh terminal to the nodes where cstor pool pods are running:
```
cd /var/openebs/sparse/
cp 0-ndm-sparse.img backup-0-ndm-sparse.img
ls -lh 
dd if=/dev/zero of=/var/openebs/sparse/0-ndm-sparse.img bs=1 count=0 seek=15G
ls -lh 
```

Once you confirm that the size has been extended, exec into each of the cstor pood and run the following commands:

```
kubectl exec -it -n openebs cstor-sparse-pool-8kyj-78dddc8d58-2cnp6 -c cstor-pool bash

root@cstor-sparse-pool-8kyj-78dddc8d58-2cnp6:/# zpool list
NAME                                         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
cstor-e01be1e8-21ba-11ea-9011-42010a8001d1  1008M   895M   113M         -    68%    88%  1.00x  ONLINE  -

root@cstor-sparse-pool-8kyj-78dddc8d58-2cnp6:/# ls -lh /var/openebs/sparse/
total 1.4G
-rw-r--r-- 1 root root  15G Dec 18 18:12 0-ndm-sparse.img

root@cstor-sparse-pool-8kyj-78dddc8d58-2cnp6:/# zpool set autoexpand=on cstor-e01be1e8-21ba-11ea-9011-42010a8001d1
root@cstor-sparse-pool-8kyj-78dddc8d58-2cnp6:/# zpool online -e cstor-e01be1e8-21ba-11ea-9011-42010a8001d1 /var/openebs/sparse/0-ndm-sparse.img

root@cstor-sparse-pool-8kyj-78dddc8d58-2cnp6:/# zpool list
NAME                                         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
cstor-e01be1e8-21ba-11ea-9011-42010a8001d1  15.0G   881M  14.1G         -     4%     5%  1.00x  ONLINE  -

```

**Comment by kmova** [comment]
Need to brainstorm on how to trigger the process. The scope can be to automate the steps and have the trigger via a change in the CSPI/CSPC (via adding an annotation

**Comment by mittachaitu** [comment]
I will rework on the design [doc](https://github.com/openebs/openebs/pull/3001) to address review comments.
