### ISSUE TITLE
Upgrade OpenEBS charts in Rancher Catalog

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2411]
OpenEBS is part of the [Rancher Catalog](https://github.com/rancher/charts) where a curated collection of Rancher 2.0 enhanced Helm charts are stored. 
Different from the Helm/Stable charts, a Rancher chart has two additional files an app-readme.md file that provides a high-level overview display in the Rancher 2.0 UI and a questions.yml file defining questions to prompt the user with.

Current chart [here](https://github.com/rancher/charts/tree/master/proposed/openebs/latest) is 0.8. Chart needs to be updated to the latest (currently 0.8.1).

**Comment by kmova** [comment]
Rancher openebs chart is located at : https://github.com/rancher/charts/tree/master/proposed/openebs/latest

**Comment by prateekpandey14** [comment]
PR to update OpenEBS charts in Rancher catalog https://github.com/rancher/charts/pull/133

**Comment by muratkars** [comment]
Merged (0.8.1)
