### ISSUE TITLE
Rename VSM to OpenEBS volume in Architecture document

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#242]
Rename VSM to OpenEBS Volumes in 
https://github.com/openebs/openebs/tree/master/contribute/design

**Comment by Rupeshiya** [comment]
@kmova  can not find VSM ,can you please explain what does it stands for?

**Comment by Rupeshiya** [comment]
@NisantaSahoo  Please close this issue since VSM is not there in the provided link
