### ISSUE TITLE
helm chart should have ndm.filters.includePaths

### ISSUE THREAD

**Issue by bryanlarsen** [openebs/openebs#2422]
I'm trying out OpenEBS and it's very scary.   For example, it appears that the default behaviour would overwrite my backup EFI System Partition, since it's not mounted!!

I would love to see documentation on how to install OpenEBS in a mode that does *not* scan for disks, and then corresponding instructions on how to manually add disks to the cstor pool.

Second best would be to have an exclude filter that filters out everything, and use an include filter instead.   So please add ndm.filters.includePaths to the helm chart.

**Comment by kmova** [comment]
@bryanlarsen Thanks for this request - adding the includePaths makes sense. 

The following is probably a lengthy work-around, but just thought of sounding it out. 
- You can setup the openebs install to run *without ndm*, by either deleting the NDM DS after it is installed or by setting the node-selector of NDM in a way that it doesn't get launched. (As we move to an operator based setup, it will be good to have NDM enable/disable) 
- A manual Disk CR can be created using the disks of interest. A sample is available here: 
   https://github.com/openebs/node-disk-manager/blob/master/samples/custom-disk.yaml
- A cStor SPC can then be created using the above manually created Disk CRs.

**Comment by akhilerm** [comment]
- Support for enable/disable of individual openebs components is now [available](https://github.com/helm/charts/pull/17320) in helm charts.
- Also, support for `includePaths` in NDM config map is made available in helm as part of [this](https://github.com/helm/charts/pull/14162) PR.
