### ISSUE TITLE
placement of target and replica related pods, custom resources in case of STS applications

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2429]
## Description
In case of STS applications using OpenEBS volumes, target and replica related resources need to have affinity with application. This means, for a given OpenEBS volume, target and replica related resources should be on the same node where application resides.
Also, this should be configurable, which means, user should be able to enable/disable affinity feature. 

## Context
In a K8s cluster of 3 nodes, consider there is an STS application with replicas as 3 and having AntiPodAffinity rules so that one node will have only one instance of STS application.
It is desirable to have target and replica related resources on the same node as that of the application instance that consumes volume.

## Possible Solution
**(Jiva and Cstor) Target pod affinity:**
User will set a label with key as `.metadata.labels.openebs\\.io/sts-target-affinity`, and, its value as application name of this STS.
For ex., if STS application name is mongo-prod, label would be `openebs.io/sts-target-affinity: mongo-prod`, and,
if STS application name is mongo-preprod, label would be `openebs.io/sts-target-affinity: mongo-preprod`

User should be able to give `sts-target-affinity` label in StorageClass as well.

**Replica pod affinity in jiva:**
In case of jiva, use the same label as above for application - replica pod affinity as well

**Cstor volume replica affinity:**
User will create StorageClass with setting `volumeBindingMode: WaitForFirstConsumer`.
This makes K8s creates PVC with `volume.kubernetes.io/selected-node` in `metadata.annotations` with value as node label on which this pod will be scheduled.
` volume.kubernetes.io/selected-node: node-ubuntu-test03`
Cstor Volume Replica is preferred to be created on the CSP  which is related to the node given in `volume.kubernetes.io/selected-node` annotation.

## Deployments
Related to deployments, same can be followed as given in PR https://github.com/openebs/maya/pull/802

**Comment by AmitKumarDas** [comment]
@vishnuitta Can we make use of `WaitForConsumer` for both target as well as replica pod affinity for both cstor as well as jiva? Do we need to consider labels at all?

**Comment by vishnuitta** [comment]
> @vishnuitta Can we make use of `WaitForConsumer` for both target as well as replica pod affinity for both cstor as well as jiva? Do we need to consider labels at all?

That makes sense @AmitKumarDas . Affinity can be developed based on the priority of labels.
All users may not use `WaitForFirstConsumer` as `volumeBindingMode`.

**Comment by vishnuitta** [comment]
cc: @kmova

**Comment by ashishranjan738** [comment]
closing this issue as PR has been merged

**Comment by vishnuitta** [comment]
Required merges are done. Closing the issue.
