### ISSUE TITLE
Add integration test to verify workflow for Cassandra DB in OpenEBS

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#243]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST
 

**What happened**:
OpenEBS can be used as a Persistant Volume for Apache Cassandra.

**What you expected to happen**:
Implement a test suite in ansible to deploy Apache Cassandra on Kubernetes using OpenEBS as volume.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ksatchit** [comment]
A sample ansible test where an application is deployed with openebs storage and a simple I/O-test is performed on it is available here: 

- https://github.com/openebs/openebs/tree/master/e2e/ansible/playbooks/hyperconverged/test-k8s-percona-mysql-pod

The cassandra loadgen job is available here: 
- https://github.com/openebs/openebs/blob/master/k8s/demo/cassandra/cassandra-loadgen.yaml
