### ISSUE TITLE
Latency for a volume shows very high in order 150+ms

### ISSUE THREAD

**Issue by ajeshbaby** [openebs/openebs#2432]
## Description
Prometheus volume running on cstor, Continuous alerts getting generated stating the latency is very high in the order of 200ms. The graphs are showing very high value on the latency part.
```
**Interval1**
 # curl localhost:9500/metrics | grep openebs_write
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9366  100  9366    0     0   914k      0 --:--:-- --:--:-- --:--:-- 1016k
# HELP openebs_write_block_count Write Block count of volume
# TYPE openebs_write_block_count gauge
openebs_write_block_count 2.92576752e+08
# HELP openebs_write_time Write time on volume
# TYPE openebs_write_time gauge
openebs_write_time 1.11847151825595e+14
# HELP openebs_writes Write Input/Outputs on Volume
# TYPE openebs_writes gauge
openebs_writes 281035
**Interval2**
# curl localhost:9500/metrics | grep openebs_write
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9360  100  9360    0     0   830k      0 --:--:-- --:--:-- --:--:--  830k
# HELP openebs_write_block_count Write Block count of volume
# TYPE openebs_write_block_count gauge
openebs_write_block_count 2.927066e+08
# HELP openebs_write_time Write time on volume
# TYPE openebs_write_time gauge
openebs_write_time 1.1187533721992e+14
# HELP openebs_writes Write Input/Outputs on Volume
# TYPE openebs_writes gauge
openebs_writes 281195

**((1.1187533721992e+14-1.11847151825595e+14)/(281195-281035))/1000000=176.15ms**
```

## Expected Behavior
Latency of SSD should be in order of 2ms or less

## Current Behavior
Latency showing higher value

## Possible Solution
Validate the metrics are correct, else we need to fix the code why its inducing higher latency.

## Steps to Reproduce
Configure a Prometheus volume on cStor
 
## Screenshots
![image](https://user-images.githubusercontent.com/22294158/53950053-58a4c480-40f1-11e9-8b0d-7cb5f2b35967.png)

## Your Environment
OpenShift 3.10
14 Node cluster with each pool having 3to5 SSDs configured in striped mode.

**Comment by vishnuitta** [comment]
Need other stats as well like cpu/ram/iscsi disks/disks/network latencies for that time period.

**Comment by ajeshbaby** [comment]
System is attached to MayaOnline, the latency is happening continuously.  User details provided on the slack.  
Didn't see much deviation on RAM/CPU utlilization except scope agent using 50% on one of the CPU.
