### ISSUE TITLE
Rebuild is triggered even with single replica cstor volume.

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/openebs#2437]
## Description
Rebuild is triggered even with single replica cstor volume.

## Expected Behavior
Rebuild should not happen on single replica cstor volume

## Current Behavior
Rebuild is triggered even with single replica cstor volume.

## Your Environment

* `kubectl get pv`:
pvc under test: ```pvc-45fe1751-3fee-11e9-a23b-0050569331ce```

Please find the attached cstor-pool pod logs.

[cstor-pool.txt](https://github.com/openebs/openebs/files/2961193/cstor-pool.txt)

**Comment by vishnuitta** [comment]
As part of OPEN opcode, replication_factor will sent from target to replica. Based on this value, replica sets the state of volumereplica as healthy.

cstor pr#216, istgt pr#243 fixes this issue
