### ISSUE TITLE
Unable to scale up cassandra statefulset application.

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#2467]
## Description

The below litmus book scales up the statefulset cassandra application replica. 

https://github.com/openebs/litmus/tree/master/apps/cassandra/functional/scale_replicas.

It deploys an application replica with 3 CVRs. Then it tries to scale the application replica to 2, thereby creating 6 CVRs.

This is observed to be failed in 0.8.2-RC2. This was working till 0.8.1. 

As we distribute the replicas of statefulset applications across storage pools, we ended up with the following issue.

```
  Normal   Provisioning          5s (x3 over 51s)  openebs.io/provisioner-iscsi_openebs-provisioner-58c87d9c64-6jqbx_df6893a2-512e-11e9-b54e-0a58ac170625  External provisioner is provisioning volume for claim "app-busybox-ns/openebs-busybox-busybox-1"
  Warning  ProvisioningFailed    4s (x3 over 50s)  openebs.io/provisioner-iscsi_openebs-provisioner-58c87d9c64-6jqbx_df6893a2-512e-11e9-b54e-0a58ac170625  failed to provision volume with StorageClass "openebs-cstor-sparse": Internal Server Error: failed to create volume 'pvc-9d1712c9-5150-11e9-bdf3-0050569866b9': response: template: MetaTaskSpecYamlTpl:22:126: executing "MetaTaskSpecYamlTpl" at <fail>: error calling fail: Not enough pools to provision replica: expected replica count 3 actual count 0
  Normal   ExternalProvisioning  2s (x6 over 51s)  persistentvolume-controller                                                                             waiting for a volume to be created, either by external provisioner "openebs.io/provisioner-iscsi" or manually created by system administrator
```

**Comment by vishnuitta** [comment]
In this case, 'replica-anti-affinity' is honored for cstor-volumes only from 0.8.2. Functionality is made similar to that jiva replicas.
User should start using preferred-replica-anti-affinity instead of replica-anit-affinity if number of nodes is less than (application_replica_count)*(# of pvcs in that appliation)*(replication_factor of each pvc of that application).
Here, things are working as expected.
