### ISSUE TITLE
Incorrect link in "Kubernetes Upgrades" docs

### ISSUE THREAD

**Issue by proegssilb** [openebs/openebs#2480]
The page [Advanced Topics > Kubernetes Upgrades](https://docs.openebs.io/docs/next/k8supgrades.html) has a link to "localhost:3000" with the text "detailed status of all the replicas". I don't think this is intended.

**Comment by ranjithwingrider** [comment]
@proegssilb Thank you for the pointing out the incorrect link issue. This has been already updated in staging branch. It will be reflected once it is merged with main branch. 
Please find the exact location: https://docs.openebs.io/docs/next/mayaonline.html#cstor-custom-resources-view
