### ISSUE TITLE
Get available and remaining disk space

### ISSUE THREAD

**Issue by davidq2q** [openebs/openebs#2505]
How to get remaining and available disk space for jiva and cstor storagepools?

**Comment by ranjithwingrider** [comment]
From 0.8.1 OpenEBS version, we enhanced the command to get the detail of cStor pool.volume using `kubectl get` command. These command will output  similar to the following only if Kubernetes version of both client and server are above 1.11.
Command:
```
kubectl get csp
```
Output:
```
NAME                     ALLOCATED   FREE    CAPACITY    STATUS    TYPE       AGE
sparse-claim-auto-lja7   125K        9.94G   9.94G       Healthy   striped    1h
```
Please check more from [FAQ](https://docs.openebs.io/docs/next/faq.html#more-info-pool-cvr-cv-disk)

If Kubernetes version of client or server are below 1.11, then you can get the details of cStor volume using the following command
```
 kubectl get cvr <cvr_name> -n openebs -oyaml
```

For Jiva, please use `mayactl volume stats ` command  to get the volume usage of Jiva volume.  More details are mentioned in [mayactl ](https://docs.openebs.io/docs/next/mayactl.html)section.
