### ISSUE TITLE
Jiva replica pod frozen at "Waiting on MonitorChannel"

### ISSUE THREAD

**Issue by rgembalik** [openebs/openebs#2512]
## Description

Few of my jiva pvc-s got stuck with logs ending on something like this:
```
time="2019-04-08T02:02:15Z" level=info msg="Closing replica"
time="2019-04-08T02:02:15Z" level=info msg="Addreplica tcp://10.233.66.170:9502"
time="2019-04-08T02:02:15Z" level=info msg="Get Volume info from controller"
time="2019-04-08T02:02:15Z" level=info msg="Register replica at controller"
time="2019-04-08T02:02:15Z" level=info msg="Received start from controller"
10.233.66.177 - - [08/Apr/2019:02:02:16 +0000] "POST /v1/replicas/1?action=start HTTP/1.1" 200 1080
time="2019-04-08T02:02:16Z" level=info msg="StartReplica with value add"
time="2019-04-08T02:02:16Z" level=info msg="Waiting on MonitorChannel"
```

In this case last messages are from two days ago. I have 2 replicas only, so one of them tried to register, but second didn't do anything, frozen at the message above.

Deleting pod (and therefore restarting replica) helped.

One important thing to note here is that, controller did crash 19 times due to the following segmentation violation:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x85c0e5]
```

This, however, has been addressed in 0.8.2-RC4 (which I am testing on other pvcs). The issue here is the fact, that replica got stuck and it didn't recover.

## Expected Behavior
1. Replica shouldn't be got stuck
2. If stuck, replica should be restarted to avoid PVC downtime.

## Current Behavior
One of replicas freezes, therefore second can't register and the controller is stuck without any replicas.

## Possible Solution
Maybe restart replica if it stops responding?

## Steps to Reproduce
No idea. I just pinged all apis under `/v1/replicas` and saw, that four of them have no replicas registered.

## Your Environment
* Nodes whitelisted as storage nodes:
```
kube2   Ready                      node     1y     v1.11.2   10.200.0.85   <none>        Ubuntu 16.04.4 LTS   4.4.0-143-generic   docker://18.6.3
kube3   Ready                      node     1y     v1.11.2   10.200.0.86   <none>        Ubuntu 16.04.4 LTS   4.4.0-145-generic   docker://18.6.3
```
* Openebs version 0.8.1
* kubernetes master running `v1.11.2`
* PVC serves as file storag (typical `uploads` directory), but I've seen the same happen to a mysql pvc.

**Comment by utkarshmani1997** [comment]
close via openebs/jiva#216
