### ISSUE TITLE
jiva pods should be deployed into openebs namespace

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2518]
## Description

Deploying jiva pods into openebs namespace

## Context

Having jiva-pods into openebs namespace makes the management of jiva volumes much easier. For example, user can directly search the jiva pods into openebs namespace rather than iterating into various namespace.

**Comment by kmova** [comment]
Fixed in 0.9: 

https://github.com/openebs/maya/pull/1183
https://github.com/openebs/maya/pull/1187
