### ISSUE TITLE
optimize resync in jiva replicas

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2521]
## Description

Currently we start one replica and let other replicas to sync with the healthy replica, and due to this replicas take too much time for the sync which is unnecessary since jiva controller sends the io's if quorum is met. Due to this time consuming operation controller go into RO state.

## Context

Optimizing sync will ensure that there will be less rebuild time and controller wouldn't go into RO state.

## Possible Solution

Send start signal to both the replicas who has same revision counter.

**Comment by utkarshmani1997** [comment]
Closing via openebs/jiva#204

**Comment by kmova** [comment]
Merged into 0.9
https://github.com/openebs/jiva/pull/204
