### ISSUE TITLE
Nodes in the cluster reboots frequently almost daily -- Setup with MicroOS, Rancher and OpenEBS.

### ISSUE THREAD

**Issue by ajeshbaby** [openebs/openebs#2525]
## Description
4 Node K8S cluster built with RKE on MicroOS and CNI Cilium.  Installed OpenEBS on the same. Ran few fio tests in a loop to check the reliability. Observed reboot of all/some nodes randomly almost daily.
Node1 -- Control Plane, ETCD, Worker
Node2 -- Control Plane, ETCD, Worker
Node3 -- ETCD, Worker
Node4 -- Worker

## Expected Behavior
System should not restart

## Current Behavior
Nodes in the cluster getting restarted. 
Day1, Node4 got rebooted
Day2, Node2, Node3 and Node4 got rebooted.

## Steps to Reproduce
Setup the cluster using RKE in MicroOS using CNI Plugin Cilium 
Install OpenEBS, create a PVC and allocate to a fio job/ busybox
Run FIO test on the same

## Your Environment
Setup with Total of 4 Nodes 
Each Node Config -- 8GB RAM, 4vCPU, 100GB OS Disk, 100GB Data Disks 
(All Virtual carved out of an SSD)
Node1 -- Control Plane, ETCD, Worker
Node2 -- Control Plane, ETCD, Worker
Node3 -- ETCD, Worker
Node4 -- Worker

Component | Version
-- | --
MicroOS | OpenSuSE Tumbleweed Kubic, 20190403
Rancher RKE | 0.2.1
Kubernetes | 1.13.5
Kubectl | 1.13.4
OpenEBS | 0.8.1
Docker | 18.09.03
cilium | v1.4.3
fio | fio-2.2.10

Some more details
https://docs.google.com/document/d/1U8oLx4W6Y3lQjVXhnrVMFZ9lnNrFOyOC9lKd21RfTDo/edit#

**Comment by ajeshbaby** [comment]
On looking into journalctl found that reboot is happening due to tranasctional-update
Excerpts of the log
```
Apr 12 00:21:01 mos2 transactional-update[7302]: /.snapshots/8/snapshot/root/.bash_history
Apr 12 00:21:01 mos2 transactional-update[7302]: /.snapshots/8/snapshot/var/run/reboot-needed
Apr 12 00:21:01 mos2 transactional-update[7302]: transactional-update finished - rebooting machine
Apr 12 00:21:01 mos2 systemd-logind[1045]: System is rebooting.
Apr 12 00:21:01 mos2 systemd[1]: transactional-update.service: Succeeded.
Apr 12 00:21:01 mos2 systemd[1]: Stopped Update the system.
```
```
01:44:19 mos3 transactional-update[17442]: other mounts and will not be visible to the system:
Apr 12 01:44:19 mos3 transactional-update[17442]: /.snapshots/8/snapshot/root/.bash_history
Apr 12 01:44:19 mos3 transactional-update[17442]: /.snapshots/8/snapshot/var/run/reboot-needed
Apr 12 01:44:19 mos3 transactional-update[17442]: transactional-update finished - rebooting machine
Apr 12 01:44:20 mos3 systemd-logind[1056]: System is rebooting.
Apr 12 01:44:20 mos3 systemd[1]: transactional-update.service: Succeeded.
Apr 12 01:44:20 mos3 systemd[1]: Stopped Update the system.
```
```
Apr 12 03:00:13 mos4 systemd[1]: snapper-timeline.service: Succeeded.
Apr 12 03:30:00 mos4 rebootmgrd[1612]: rebootmgr: reboot triggered now!
Apr 12 03:30:00 mos4 systemd[1]: rebootmgr.service: Succeeded.
Apr 12 03:30:00 mos4 systemd-logind[1064]: System is rebooting.
Apr 12 03:30:00 mos4 systemd[1]: Stopping open-vm-tools: vmtoolsd service for virtual machines hosted on VMware...
Apr 12 03:30:00 mos4 systemd[1]: Stopped target Timers.
Apr 12 03:30:00 mos4 systemd[1]: btrfs-scrub.timer: Succeeded.
Apr 12 03:30:00 mos4 systemd[1]: Stopped Scrub btrfs filesystem, verify block checksums.
Apr 12 03:30:00 mos4 systemd[1]: transactional-update.timer: Succeeded.
```

**Comment by ajeshbaby** [comment]
**One of the solution.** 
-- You can do the following on each nodes to stop the transactional update.
```
systemctl disable --now rebootmgr.service
systemctl disable --now transactional-update.timer
```

Other possible solution
-- Set the reboot timer schedule at different time i.e  staggered  at various interval of the day, so that only one nodes get rebooted at a time. I have not tried this.

More details --
https://en.opensuse.org/Kubic:Update_and_Reboot
https://kubic.opensuse.org/blog/2018-04-04-transactionalupdates/

You can get more details to see if the cause of reboot is due to transactional update using below command outputs
```
journalctl 
systemctl status rebootmgr
systemctl status transactional-update.timer
cat /etc/rebootmgr.conf
cat /usr/lib/systemd/system/transactional-update.timer
cat /usr/etc/transactional-update.conf
```

**Comment by prabhatkumarthakur** [comment]
I have a setup with only MicroOs installed. External package installed is the only docker. It reboots on default schedule time.
Steps to avoid the reboot is to disable below two services.
systemctl disable --now rebootmgr.service
systemctl disable --now transactional-update.timer
