### ISSUE TITLE
huge amount of unnecessary logs are generated in maya

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#2529]
2019/04/17 14:01:03.149036 [DEBUG] http: Request /latest/meta-data/instance-id (GET)
2019/04/17 14:01:03.149186 [DEBUG] http: Request /latest/meta-data/instance-id (150.046µs)
2019/04/17 14:01:56.250730 [DEBUG] http: Request /latest/meta-data/instance-id (GET)
2019/04/17 14:01:56.251105 [DEBUG] http: Request /latest/meta-data/instance-id (379.012µs)
2019/04/17 14:01:56.251734 [DEBUG] http: Request /latest/meta-data/instance-id (GET)
2019/04/17 14:01:56.251822 [DEBUG] http: Request /latest/meta-data/instance-id (91.708µs)

**Comment by sdelrio** [comment]
Same here. With openebs 0.8.2, each minute generates 4 log lines in each apiserver pod.

Also entering into the container itself doesn't seems to have any option to reduce logs

```
21:54 $ kubectl -n openebs exec -ti openebs-apiserver-86f6684769-8hq6x /bin/sh
/ # /usr/local/bin/maya-apiserver -h
CLI for managing maya-apiserver

Usage:
  maya-apiserver [command]

Available Commands:
  help        Help about any command
  start       start maya-apiserver
  version     Prints maya-apiserver version

Flags:
  -h, --help                           help for maya-apiserver
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)

Use "maya-apiserver [command] --help" for more information about a command.
/ # /usr/local/bin/maya-apiserver version
Version: 0.8.2-released
Git commit: b9efd8eaad9aa14d3ac3b04a772240b6e11a59b3
GO Version: go1.11.2
GO ARCH: amd64
GO OS: linux
```

**Comment by AmitKumarDas** [comment]
@shubham14bajpai any idea if this is fixed

**Comment by shubham14bajpai** [comment]
Yes this has been fixed.

**Comment by AmitKumarDas** [comment]
Closing this since this has been fixed in recent releases of OpenEBS
