### ISSUE TITLE
OpenEBS is using to much disc space

### ISSUE THREAD

**Issue by joergkiesewetter** [openebs/openebs#2530]
Our kubernetes cluster crashed, because the openEBS storages were taking to much disc space. While I was trying to figure out where all the disc space went, I found out, that whole openEBS environment on our nodes is taking much more space than expected.

We created a new deployment for Cassandra. We have 3 Cassandra pods each using an openEBS storage of 50GB. Each Storage has 3 replicas. The whole environment runs on a 3-node-cluster.

I was able to see the content of the volumes itself by analyzing the path ```/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default```. On each node I found a directory like this and each of the nodes had a proper cassandra node directory.

```
10.110.48.188:3260-iqn.2016-09.com.openebs.jiva:platform-cassandra-data-cassandra-0-3734881715-lun-0
10.96.62.37:3260-iqn.2016-09.com.openebs.jiva:platform-cassandra-data-cassandra-1-3832344926-lun-0
10.109.13.14:3260-iqn.2016-09.com.openebs.jiva:platform-cassandra-data-cassandra-2-551742433-lun-0
```

Each of the directories had a size of about 12 GB. When I had a deeper look into these directories I was able to see which files of cassandra were using which amount of disc space.

Now, there is the weird stuff. The openEBS replicas are stored in ```/var/openebs```. When I try to compare the size of the images with the content of the volume directories, there is a huge difference in used size.

node 1:
```
37G     /var/openebs/platform-cassandra-data-cassandra-0-3734881715
41G     /var/openebs/platform-cassandra-data-cassandra-2-551742433
52G     /var/openebs/platform-cassandra-data-cassandra-1-3832344926
```

node 2:
```
37G     /var/openebs/platform-cassandra-data-cassandra-0-3734881715
41G     /var/openebs/platform-cassandra-data-cassandra-2-551742433
52G     /var/openebs/platform-cassandra-data-cassandra-1-3832344926
```

node 3:
```
37G     /var/openebs/platform-cassandra-data-cassandra-0-3734881715
41G     /var/openebs/platform-cassandra-data-cassandra-2-551742433
52G     /var/openebs/platform-cassandra-data-cassandra-1-3832344926
```

So, at the moment, cassandra-0 is using 168GB storage through 3 nodes.

This brings some problems. When I create a new volume through openEBS with a size of 50GB, it means that I should have at least 200GB on disc space available in my cluster.
```
50GB in /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default
50GB for replica 1
50GB for replica 2
50GB for replica 3
```

Also, The amount of needed disc space is not clear. it seems like the openebs images can grow in size infinite. the cassandra-1 replicas have already exceeded the max size of 50GB. We have also another pod for postgres, where the usage data is about 80MB and the replica images are about 14GB in size.

So, my question is, what are we doing wrong? How can we ensure, that we have a predictable amount of used disc space and how much disc space should we have for a GB of kubernetes storage? Is this probably an outdated problem, because it is already solved?

## Your Environment
The cluster is not running, at the moment, so I'm not able to execute these commands.
* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Kernel (from `uname -a`):
```
Linux Ubuntu-1604-xenial-64-minimal 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Install tools:
* Others:
  * all images for maya, jiva, exporter stuff are using v0.5.3
  * kubernetes: v1.12.1

**Comment by muratkars** [comment]
Hi @jamesgeorge007 
With the most recent release v0.8.2 we have the space reclaim for jiva volumes. 
You can find the details on [release notes](https://github.com/openebs/openebs/releases) under Minor enhancements section.
The space reclaim is done by scheduling a Kubernetes Job. Therefore, 50G volumes really should take 50G (on each node) * n replicas after reclaim job is run.
