### ISSUE TITLE
[cmd/maya-exporter] The volume utilization metrics aren't representing the used capacity correctly

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#2534]
## Description

The `maya-exporter` container is deployed as a side-car to the target/controller pods and are responsible for exposing volume metrics. 
Example of such is `openebs_volume_status`, `openebs_actual_used`, `openebs_size_of_volume`, `openebs_volume_uptime`

## Expected Behavior

OpenEBS' storage engines viz Jiva and Cstor both have `maya-exporter` deployed as a sidecar container and it's metrics. Both the storage engines expose a common set of volume-metrics for clients which can be used by clients like Grafana to provide visualization. 
A typical use case is figuring out remaining space, which is `volume_used - volume_free`.
As of now there are some discrepancies and it isn't easy to get what is expected.

There's an `openebs_actual_used` and `openebs_size_of_volume`, which can be used to figure out the same.

## Current Behavior
At times the `openebs_actual_used` capacity has exceeded the `openebs_size_of_volume`, which isn't possible until the former is telling physical volume-size used.

## Steps to Reproduce
1. It has been seen in the openebs-workloads cluster, which also takes regular volume-snapshots.

**Comment by utkarshmani1997** [comment]
@vharsh can you please post the output, which you've got.
