### ISSUE TITLE
Disk pressure in one of the nodes of OpenShift cluster

### ISSUE THREAD

**Issue by sushma1118** [openebs/openebs#2535]
# Description
When I was working on Elasticsearch, I found out that one of the cstor-pool pod was not getting scheduled on one of the nodes(node 2). The status of the pool pod was 'pending'. After describing the pod I got to know that the node has disk pressure. 
```
 - lastHeartbeatTime: 2019-04-19T06:38:17Z
    lastTransitionTime: 2019-04-19T06:37:36Z
    message: kubelet has disk pressure
    reason: KubeletHasDiskPressure
    status: "True"
    type: DiskPressure
```

## Expected Behavior
The cstor-pool pod should get scheduled in the respective node.

## Current Behavior
Because of the disk pressure in the node the pod was not getting scheduled.
When I did 'df -h' I got to know that 81% is used.
```Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   50G   41G  9.9G  81% /
devtmpfs               3.9G     0  3.9G   0% /dev
tmpfs                  3.9G     0  3.9G   0% /dev/shm
tmpfs                  3.9G  5.9M  3.9G   1% /run
tmpfs                  3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1             1014M  206M  809M  21% /boot
/dev/mapper/rhel-home   39G   48M   39G   1% /home
tmpfs                  799M   12K  799M   1% /run/user/42
overlay                 50G   41G  9.9G  81% /var/lib/docker/overlay2/bd1d048f832b6438661967e95a2a241ed02a34036500f7bf948156f8838089f3/merged
overlay                 50G   41G  9.9G  81% /var/lib/docker/overlay2/37a77a2a2764ff1b0d4496f15b07b51c151c057d3344975e7aaeb768fe824035/merged
overlay                 50G   41G  9.9G  81% /var/lib/docker/overlay2/9144fc9bb8daca792d5047dc4d40697c78ad8f40278efd9da89cf0bfcd71db11/merged
```

## Possible Solution
The disk pressure is because as mentioned in the Kubernetes docs, nodefs.inodesFree<5%
imagefs.available<15%. Else the threshold is crossed. Here Filesystem 'overlay' is using 81%.
Go into the node having disk pressure and delete the core dump. 

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by mspyder** [comment]
Please also give the output of `df -i`

**Comment by vharsh** [comment]
@sushma1118 Please also share the output of `df -i`
