### ISSUE TITLE
RWX Native support

### ISSUE THREAD

**Issue by elishemer** [openebs/openebs#2537]
hey,

Are there plans to support Read-Write-Many (RWX) natively in CSTOR or in JIVA ? 

there's a blog post on how to enable RWX by leveraging NFS on top of OpenEBS
https://blog.openebs.io/setting-up-persistent-volumes-in-rwx-mode-using-openebs-142632244cb2

but this solution is very cumbersome
1. requires much more complicated configuration and setup
2. requires an additional provisioner
3. requires extra disk space
4. performance degradation is unclear

thanks

**Comment by muratkars** [comment]
Reopening this issue with additional requirement:

Current RWX solution ([here](https://docs.openebs.io/docs/next/rwm.html)) is based on the [Kubernetes nfs-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs) 

We need a solution that provides:
1) Standard Docker images with debugging tools
2) More than one provisioner instance - maybe through an Operator (Single provisioner is a point of failure)
3) Running NFS on LocalPV
4) Metrics exporter (adding Prometheus exporter for NFS-Ganesha as an option)

**Comment by muratkars** [comment]
Reopening this issue

**Comment by kmova** [comment]
OpenEBS has started to support NFS natively via the Dynamic NFS provisioner. For trying it out and providing feedback please visit - https://github.com/openebs/dynamic-nfs-provisioner
