### ISSUE TITLE
Add MAINTAINERS file

### ISSUE THREAD

**Issue by caniszczyk** [openebs/openebs#2544]
list maintainers, emails and affiliations

**Comment by kmova** [comment]
Thanks for this issue @caniszczyk .. on it!

**Comment by kmova** [comment]
Fixed this as part of the following PRs for this repo as well as other code repositories being submitted to CNCF. 

https://github.com/openebs/openebs/pull/2547
https://github.com/openebs/maya/pull/1144
https://github.com/openebs/jiva/pull/215
https://github.com/openebs/istgt/pull/251
https://github.com/openebs/libcstor/pull/6
https://github.com/openebs/node-disk-manager/pull/247
