### ISSUE TITLE
Add GOVERNANCE.md

### ISSUE THREAD

**Issue by caniszczyk** [openebs/openebs#2545]
How is the project governed?

See examples:
https://prometheus.io/governance/
https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md
https://github.com/containerd/project/blob/master/GOVERNANCE.md
https://github.com/envoyproxy/envoy/blob/master/OWNERS.md

**Comment by muratkars** [comment]
[GOVERNANCE.md](https://github.com/openebs/openebs/blob/master/GOVERNANCE.md) merged
