### ISSUE TITLE
Thin provisioning should not exceed the pool size

### ISSUE THREAD

**Issue by inyee786** [openebs/openebs#2571]
## Description

Thin provisioning of the application should not exceed the pool size 
 
log of the pool
https://mayadata-team.slack.com/files/U6X7NNVED/FJCL1C81G/cstor-disk-dlp1-logx.txt

**Comment by vishnuitta** [comment]
Thin provisioning will exceed the pool size if volume size is greater than pool size. Hence, closing this issue.
