### ISSUE TITLE
aborting storagepool create operation as no node qualified: no disk object found

### ISSUE THREAD

**Issue by dingsongjie** [openebs/openebs#2599]
**1 My custom Disk  yaml**

apiVersion: openebs.io/v1alpha1
kind: Disk
metadata:
  name: server01-device1
  labels:
    kubernetes.io/hostname: server01
    ndm.io/managed: "false" # for manual disk creation put false
    ndm.io/disk-type: partition
status:
  state: Active
spec:
  capacity:
    logicalSectorSize:  512
    storage:  406870912000
  devlinks:
  \- kind: by-id
    links:
    \- /dev/disk/by-id/ata-WDC_WD10EZEX-00WN4A0_WD-WCC6Y6PDA4DL-part4
  Partitioned: No
  path: /dev/sda4

**2 parted /dev/sda4 print**

Error: /dev/sda4: unrecognised disk label
Model: unknown                                                 
Disk /dev/sda4: 399GB
Sector size (logical/physical): 512B/4096B
Partition Table: unknown
Disk Flags: 

**3 After I create Disk use in 1  , Kubectl get disk, custom disk is available**

NAME                                      SIZE           STATUS   AGE
server01-device1                          406870912000   Active   38m

**4 Create StoragePoolClaim**

apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: comteck-default
  annotations:
    openebs.io/cas-type: cstor
spec:
  name: comteck-default
  type: disk
  maxPools: 1
  poolSpec:
    poolType: striped

**5 No Custom csp is created** 

[root@server01]# kubectl get csp
NAME                     ALLOCATED   FREE    CAPACITY   STATUS    TYPE      AGE
cstor-sparse-pool-f8lh   1.44M       9.94G   9.94G      Healthy   striped   3h7m

**6 MayaServer Logs**

I0530 06:35:12.668058       8 handler.go:176] Provisioning pool 1/1 for storagepoolclaim comteck-default
E0530 06:35:12.677596       8 handler.go:179] Pool provisioning failed for 1/1 for storagepoolclaim comteck-default: aborting storagepool create operation as no node qualified: no disk object found

**Comment by kmova** [comment]
`ndm.io/disk-type: partition` can you set this to : `ndm.io/disk-type: disk`

**Comment by dingsongjie** [comment]
it is works , thank you for help
