### ISSUE TITLE
Allow multiple paths for Jiva pool/class

### ISSUE THREAD

**Issue by vitobotta** [openebs/openebs#2621]
## Description
Currently Jiva supports one path only. My understanding is that in order to use other mounted disks I need to create separate pools and storage classes. It would be great if we could just use multiple paths with the same pool/storage class.

## Context

This would be useful to scale Jiva storage with multiple disks.

Thanks!

**Comment by kmova** [comment]
As part of migrating the Jiva provisioner to CSI, there are plans of converting the hostPath used by Jiva into a Local PV (hostpath). And of the enhancements planned for Local PV is to make use of multiple hostpaths with capacity based scheduling and so forth.
