### ISSUE TITLE
PVC with name longer than 63 chars fails to provision. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2630]
When a PVC is created with name longer than 63 chars, it fails with the following error:

```
Warning    ProvisioningFailed    14m (x7 over 29m)      openebs.io/provisioner-iscsi_openebs-provisioner-6fd9f66c6d-8vnmk_01eca347-8e58-11e9-ae31-624560802ecd  failed to provision volume with StorageClass "openebs-cstor-x3": Internal Server Error: failed to create volume 'pvc-313f14fc-915f-11e9-9579-f832e48ab7b7': response: Service "pvc-313f14fc-915f-11e9-9579-f832e48ab7b7" is invalid: metadata.labels: Invalid value: "prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0": must be no more than 63 characters
```

The above error is thrown by the m-apiserver, since as it tries to create a K8s service for Target and sets the metadata label `openebs.io/persistent-volume-claim=<pvc-name>`. 

Need to explore if the above label is still required or if it could be moved to metadata annotations.

**Comment by vharsh** [comment]
By what release are we planning to remove the PVC label? This label is useful and it has been used in various blogs, scripts and whatnot, we'd have to convey the alternative to end-users, and suggest an alternative jsonpath examples.

subscribe @vharsh

**Comment by prateekpandey14** [comment]
The issue still exists, as we use the pvc name as a label in volume service and other components.

**Comment by jadsy2107** [comment]
Issue still exists i'm having that problem now 

 Invalid value: "alertmanager-prometheus-alertmanager-db-alertmanager-prometheus-alertmanager-0": must be no more than 63 characters

**Comment by rraj-gautam** [comment]
This issue still persists, any workaround for it?
