### ISSUE TITLE
Allow to change default storage classes parameters

### ISSUE THREAD

**Issue by nike38rus** [openebs/openebs#2665]
## Description

Allow to tune parameters of default storage classes created by openebs-apiserver

## Context
After installing openebs into K8s cluster openebs-apiserver bootstraps the default SCs. If I want to change some of their parameters I have to duplicate them because apiserver will try to restore them on restart. 

## Possible Solution
* Add env variables/helm chart values for changing parameters of default SC resources
or
* Do not manage/restore SCs after bootstrapping. This may be achieved by creating SCs from helm chart or K8s manifests instead of  creating them by openebs-apiserver

**Comment by AmitKumarDas** [comment]
Thanks @nike38rus we are looking into it. I guess enabling or disabling of SC from apiserver seems doable for current release.

**Comment by kmova** [comment]
As part of 1.1, we have the ability to disable the installation/management of default storage configuration. Keeping this issue open, to be able to collect a few more details on the kind of parameters that users would like to customize and add them into the software. 

Here are some of the options that can be already configured:
- default storage path for jiva and local pv volumes
- enable/disable the cstor sparse pool creation and the local of the sparse files directory

Some of the items that would be good to have:
- storage class - retain policy
- storage class - binding mode
- cstor sparse pool - resource limits

In addition, there have also requests for some global defaults like:
- resource limits on the various storage components installed

**Comment by AmitKumarDas** [comment]
There were some discussions around keeping user changes on these default resources intact. Following is the Minutes of Meeting
- maya api server should avoid reapplying resources that has been modified by user via kubectl
- maya api server should avoid reapplying spc resource that has been modified by its controller
- maya api server will have a list of annotations, which when set against any resource is automatically avoided by maya api server

**Comment by AmitKumarDas** [comment]
https://github.com/openebs/maya/pull/1407 tackles this issue in a different way as of now.
Maya API Server avoids updating default SPC & StorageClass since it might be in use in the user's setup.
