### ISSUE TITLE
How to deal with full Disks

### ISSUE THREAD

**Issue by siegfriedhoellrigl** [openebs/openebs#2673]
We have installed OpenEBS 0.9.0 in Rancher/Kubernetes Cluster.

It is running on 14 Nodes. 7 of them have a 200GB SSD, the other 7 have a 2TB Harddisk.

Choosing different Pools for that purpose works fine.

But as soon, as a Disks is getting full, the workload which is using it, freezes.

I guess, this is an expected behaviour, since "overprovisioning=false" is not working at the moment, right ?

How shoud we deal with that, when we want to use it in production ?

**Comment by ranjithwingrider** [comment]
@siegfriedhoellrigl If the underlying disk can be expanded, then you can expand the cStor pool using the steps mentioned [here](https://docs.openebs.io/docs/next/ugcstor.html#expanding-size-of-a-cStor-pool-instance-on-a-node-add).
If you have some extra disks to be added to the Node, then cStor pool exapnsion can be done by the steps mentioned [here](https://docs.openebs.io/docs/next/ugcstor.html#expanding-size-of-a-cStor-pool-instance-on-a-node-add-disk).

**Comment by siegfriedhoellrigl** [comment]
Ususally on newer (hardware-highdensity-) servers, there are only 2 or 3 Slots for harddrives.
You would normally equip everything with disks initially.
So no chance to increase any disk capacity afterwards.

Is there any Roadmap, when "overprovisioning=false" will be working correctly ?

What else can be done, when a disk is getting full ?
Is it possible to "move" a volume from one disk to another ?

**Comment by kmova** [comment]
@siegfriedhoellrigl -- couple of questions on the setup: 
- When you require more space, do you have another node with additional disks. 
- Also say you are using replica count of 3, do you add nodes in multiples of 3.

**Comment by siegfriedhoellrigl** [comment]
At the moment there are only 7 Servers with a 2TB Disk and 7 Servers with a 200GB SSD.
Maybe more will follow in the future. But these will have different disks.
For most workloads an external ceph cluster is used.
But we would like to make sure, that nobody can create openebs volumes that require more disk space than availiable.
