### ISSUE TITLE
[Jiva] Pods (both ctrls and replicas) stuck in terminating state

### ISSUE THREAD

**Issue by rgembalik** [openebs/openebs#2675]
## Description
If there ever happens any instability with the node or network, it happens every now and then, that one of the controller containers is stuck and cannot be terminated fully. Usually, it'll show like this one:
```
kubectl get pod -owide | grep Terminating
jupyterhub                    pvc-c9806a11-6754-11e9-aeed-525400451066-ctrl-7bfd88f675-nggxw    1/2     Terminating         0          7d10h   10.233.66.218    kube2   <none>           <none>
```

It happens with replicas as well, but replicas are a bit more serious, as unterminated pod will newe let its replacement to be scheduled on this node until finished.

Now the curious part is that the container cannot be killed via docker CLIs `docker kill`. If I inspect the container via docker inspect, it'll show as running, but the PID it is supposed to be running doesn't exist under `ps aux`.

The only way to remove it is to `docker rm -f` on the node.

I am attaching kubelet logs filtered to the container. The issue happens only with the Jiva containers.

[kubelet-trying-to-stop-ctrl.log](https://github.com/openebs/openebs/files/3397138/kubelet-trying-to-stop-ctrl.log)

EDIT: I checked it and it happens on the `maya-exporter` containers and on the `pvc-...-ctrl-con` containers, but never on both in the same pod.

## Expected Behavior
The pods should terminate normally.

## Current Behavior
The pods need to be cleaned manually.

## Possible Solution
It's more of the workaround, but `docker rm -f` does help for the single pod.

## Steps to Reproduce
Not sure. The disappearing node will do that (either due to heavy load or network issues).

## Your Environment

* `kubectl get nodes`:
```
kube1   Ready,SchedulingDisabled   master   479d   v1.14.1
kube2   Ready                      node     479d   v1.14.1
kube3   Ready                      node     479d   v1.14.1
kube4   Ready                      node     460d   v1.14.1
kube6   Ready                      node     208d   v1.14.1
```
* OS (from `/etc/os-release`): `Ubuntu 16.04.4 LTS`
* Kernel (from `uname -a`): `4.15.0-47-generic`
* Install tools: `kubespray`
* Others:
Docker: `18.09.5, build e8ff056`
Openebs: `1.0.0` (chart installed)

**Comment by utkarshmani1997** [comment]
@rgembalik can we get the logs of controller as well, need to check where it's getting stuck while shutting down.

**Comment by rgembalik** [comment]
@utkarshmani1997 I'll see what can I do about logs, but I think it was already turned off because there was no process on the node with PID given by docker inspect. The meaning process was already turned off and docker didn't see that change.

**Comment by rgembalik** [comment]
[ctrl-logs-pre-stop.log](https://github.com/openebs/openebs/files/3405605/ctrl-logs-pre-stop.log)

@utkarshmani1997 Here are the ctrl logs, one hour back, before it was stopped. Not much of it hough.
