### ISSUE TITLE
backup documentation doesn't reflect current version 

### ISSUE THREAD

**Issue by hdnebat** [openebs/openebs#2692]
below section is obsolete, we are v1.0.

Roadmap
OpenEBS ARK storage plugin

The above backup and restore procedure is done using Restic, where the entire data is copied and restored in a bulk manner. More efficient backup and restore possible through incremental data snapshots using the OpenEBS ARK storage plugin which is planned for OpenEBS 0.9 release

**Comment by ranjithwingrider** [comment]
Thanks @hdnebat for reporting the problem.
Can you provide the corresponding doc link, please?   We can change it if it is pointing in the latest doc.

**Comment by hdnebat** [comment]
the topic doesn't exist in latest docs.
latest docs have it is 0.8.2:
https://docs.openebs.io/v082/backup.html

**Comment by ranjithwingrider** [comment]
Previous OpenEBS versions are accessed generally by https://docs.openebs.io/<version_representation>/<page.html>

Latest doc has come up with restructured contents and arranged in such a way that End user will get all User guide info of each OpenEBS engine from one page. The following page has the description of backup and restore for different OpenEBS engines.
1. https://docs.openebs.io/docs/next/ugcstor.html - For cStor
2. https://docs.openebs.io/docs/next/jivaguide.html - For Jiva
3. https://docs.openebs.io/docs/next/uglocalpv.html - For OpenEBS-LocalPV

**Comment by kmova** [comment]
Fixed as part of https://docs.openebs.io/docs/next/ugcstor.html#backup-and-restore
