### ISSUE TITLE
invalid bdc number

### ISSUE THREAD

**Issue by obeyler** [openebs/openebs#2693]
## Description
K8S with 3 master and 6 workers
6 nodes / 5 bdc

kubectl get bdc -n openebs
NAME                                       BLOCKDEVICENAME                           PHASE   AGE
bdc-4bb6b256-b460-11e9-99c4-fa163eca0551   sparse-c8b3baa69d1955b36718880ecd03e9bb   Bound   7m41s
bdc-4bc8d9eb-b460-11e9-a2c5-fa163e358428   sparse-fea47bbdeb1564149603515af1103da4   Bound   7m40s
bdc-4cb17b70-b460-11e9-84e3-fa163edf8ab4   sparse-7d8d7f3a4f2eb02f938288a64d4e8b91   Bound   7m42s
bdc-4cf0c8c1-b460-11e9-a2c5-fa163e358428   sparse-7ea185e636d4a77577e1ec1d7d0b22df   Bound   7m41s
bdc-4d989e73-b460-11e9-99c4-fa163eca0551   sparse-d8fe4ef07b2625abfa65f99a44566ace   Bound   7m40s## Expected Behavior

installed by helm chart 1.1.0 on CFCR (K8S 1.14.1)

**Comment by obeyler** [comment]
@kmova

**Comment by vishnuitta** [comment]
PR is merged and fix is available in 1.2. Hence, closing the issue
