### ISSUE TITLE
Creating reproducible k8s-openebs environment using kargo

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#27]
https://github.com/kubernetes-incubator/kargo

**Comment by AmitKumarDas** [comment]
Can be tracked under https://github.com/openebs/openebs/issues/28

**Comment by kmova** [comment]
As of 0.5.x release, k8s clusters are being created using kubeadm/kops. Also openebs doesn't mandate a certain way of creating the k8s clusters.

Closing this issue in favor of tracking the requirement under openebs/openebs#28
