### ISSUE TITLE
Operator yaml example to deploy localpv provisioner only

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2706]
This feature has been requested in the community.
Some of the OpenEBS users use OpenEBS orchestration, NDM and localpv provisioner only and would like to limit the number of components installed.

We need a limited version of the operator `openebs-operator-1.1.0.yaml` file with bare-minimum localpv requirements that deploys only the below four components:

openebs/provisioner-localpv
openebs/node-disk-manager
openebs/node-disk-operator
openebs/linux-utils
openebs/openebs-tools

**Comment by akhilerm** [comment]
For the `node-disk-manager`

**Comment by kmova** [comment]
Sample YAMLs to just install the components required for Local PV are available here: 

- https://openebs.github.io/charts/openebs-operator-lite.yaml
- https://openebs.github.io/charts/openebs-lite-sc.yam

If using helm, an example values.yaml is:
- https://openebs.github.io/charts/openebs-lite-helm-values.yaml

**Comment by vishnuitta** [comment]
does this mean - our upgrade compatibility matrix grows, i.e., whether user used lite or complete yaml?
and what if user wants to make the complete install later (or) vice versa? can he follow different paths for each one?
And, will we support various other lite versions as well?
(or) would it be possible to document to scale down to zero if user doesn't need any particular engines?

**Comment by kmova** [comment]
yes @vishnuitta -- as part of upgrades - we will have to maintain and test this lite version of yamls. 

the yamls and helm values are designed in such a way that they can be converted to full install later. since these are local PVs, the upgrades are only associated with control plane upgrades which are managed by users.
