### ISSUE TITLE
Automatically move replica from the failing node

### ISSUE THREAD

**Issue by ytsarev** [openebs/openebs#2718]
## Description
Currently in case of long term node failure jiva replicas have to be moved manually. It would be great if some automation(operator?) would detect node failure and move replica to the healthy node.

## Context
From time to time we experience node failures where jiva replicas do reside.
In that case we have to options - either recover the node or move replica to the healthy one.
In second case we have to manually edit node affinity of replica deployment so that it is scheduled on healthy node.

## Possible Solution
Operator/controller that detects node failure and moves replica to healthy node automatically.

This issue is reported for jiva due to recent operation experience but i believe the similar style move of `cstor-pool` pods will be also extremely useful

**Comment by utkarshmani1997** [comment]
Thanks @ytsarev for filing this feature request, we are targeting this feature in upcoming release.

**Comment by kmova** [comment]
Taking this up for 1.4 release. An alpha version is being targeted for 1.3
