### ISSUE TITLE
cstore metrics endpoint shows openebs_replica_status 0 for volumes that were long deleted

### ISSUE THREAD

**Issue by sbaryakov** [openebs/openebs#2741]
## Description
cstore metrics endpoint shows openebs_replica_status 0 for volumes that were long deleted
## Expected Behavior
Volumes that are deleted should not be visible in the metrics endpoint. There should be parity between the ```kubectl get pv``` and the metrics endpoint
## Current Behavior
Deleted volumes are shown as offline

**Comment by kmova** [comment]
With OpenEBS 1.2, there were fixes made to avoid having stale replicas. This issue should no longer be happening from the latest release. Please verify. 

Keeping this open for verification for some more time.
