### ISSUE TITLE
Support k8s v1.16+ for openebs components

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#2747]
## Description

As the k8s v1.16 release will stop serving the deprecated API versions
in favor of newer and more stable API versions, more info can be found here
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

## Context

- The k8s v1.16 release will stop serving the deprecated API versions
- User will be able to install/upgrade openebs and its data plane components in k8s version 1.16+
- This change will work in < 1.16 based k8s cluster as well ( tested till v1.12) 

## Possible Solution

Upgrade Maya installer templates to support `apps/v1` stable API's version for deployement resource.

**Comment by kmova** [comment]
Fixed with 1.3
