### ISSUE TITLE
Provide ability to control priorityClassNames of cstor/jiva deployments through SPC/SC

### ISSUE THREAD

**Issue by ytsarev** [openebs/openebs#2749]
## Description
Provide ability to control priorityClassNames for pods of cstor/jiva deployments through StoragePoolClaim and/or StorageClass

## Context
We want to control pod Preemption to prioritize openebs pods and avoid them to be evicted early from nodes

## Possible Solution
Currently the only way to do it is to patch cstor/jiva deployments manually after their creation.
It would be great to have this control in associated overarching resources as StoragePoolClaims and StorageClasses

**Comment by kmova** [comment]
This will be added to the new cstor schema being developed as part of the CSI driver implementation.

**Comment by kmova** [comment]
https://github.com/openebs/maya/pull/1566 - allows for configuring the priority class for cStor Pools provisioned with new schema.

**Comment by ytsarev** [comment]
It can be closed I guess
