### ISSUE TITLE
Remove duplication of content.

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#276]
Our docs are kind of stuck half way between Markdown and Restructured text.
Suggest if some documents would be better suited in other places, or if there exists a same or similar thing in more than one places.

**Comment by vharsh** [comment]
For example : https://github.com/openebs/openebs/blob/master/contribute/design/README.md

**Comment by brandy** [comment]
I'd be willing to help convert over the documentation to markdown! 😄 

Would you like the format to stay the same, or update it ?

**Comment by kmova** [comment]
Thanks @brandy for offering to help! All help or suggestions to improve the documentation are welcome!

We are hoping to have the documentation cleaned up and categorized as follows:
- OpenEBS user documentation 
  - written in rst 
  - content can be under openebs/documentation
  - readthedocs is setup to pick the changes on commit and publish 
- OpenEBS developer documentation
  - contains design, process, hacks, tips that will help developers/contributors 
  - written in md 
  - will be under openebs/contribute
- Local directory documentation
  - usually in the form or readme.md in a folder that explains the contents of the folder 
  - for detailed documentation/instructions can be linked to either user or developer documentation.

**Comment by kmova** [comment]
The docs are moved to github.com/openebs/openebs-docs in markdown format.
