### ISSUE TITLE
Revert changes done in cstor as part of new error logging format

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2762]
## Description

With this PR https://github.com/openebs/cstor/pull/266, lot of changes related to new error logging format has been added.
`cstor` repo deviating too much from upstream will make it difficult to keep cstor repo in sync with upstream.
This issue is created to remove the changed related to above mentioned PR.
New error logging format is handled at ZFS/ZPOOL client used in `maya` repo.

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by NaveenBellary** [comment]
@vishnuitta, I'd like to take this up as part of Hacktoberfest
