### ISSUE TITLE
break uzfs_zvol_rebuild_scanner into multiple functions

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2763]
## Description

`uzfs_zvol_rebuild_scanner` in libcstor repo is the rebuilding thread on healthy replica which serves the requested data to degraded replica.
This function has grown into multiple lines and having multiple branches.
This function can be broken into multiple functions following SOLID design principles.
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by amitsagargowda** [comment]
I would be working on this PR

**Comment by pawanpraka1** [comment]
thanks @amitsagargowda, let us know if you need any help. Please go through the uzfs_zvol_rebuild_scanner function in the libcstor repo (https://github.com/openebs/libcstor).
