### ISSUE TITLE
break `uzfs_zvol_rebuild_dw_replica` into multiple functions

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2764]
## Description

`uzfs_zvol_rebuild_dw_replica` in libcstor repo is the rebuilding thread on degraded replica which requests for data from healthy replica.
This function has grown into multiple lines and having multiple branches.
This function can be broken into multiple functions following SOLID design principles.

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by rv404674** [comment]
@vishnuitta Can I take this one??

**Comment by akhilerm** [comment]
@vishnuitta , @mynktl Keeping the issue open so that the refactoring can be tracked.

**Comment by 15bcs019** [comment]
is this issue still open?

**Comment by mynktl** [comment]
yes @15bcs019 , issue is in open state. Thanks for showing interest.

In `openebs/libcstor`, We have one function `uzfs_zvol_rebuild_dw_replica` to rebuild degraded replica. This function is too long, containing whole rebuild flow. This issue it to fragment this function into multiple functions.
As of now this function contains,
- connecting to remote replica https://github.com/openebs/libcstor/blob/master/src/data_conn.c#L709
- Initiate rebuilding handshake https://github.com/openebs/libcstor/blob/master/src/data_conn.c#L742
- Rebuild snapshot and data(AFS)  https://github.com/openebs/libcstor/blob/master/src/data_conn.c#L818
     -  This block is having a number of conditions and opcode handling. This can be moved to separate functions.
- Cleanup/status-update for rebuilding https://github.com/openebs/libcstor/blob/master/src/data_conn.c#L995

Let me know if you need more information.

Thanks.
