### ISSUE TITLE
Refactor startReplica(c *cli.Context)

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2774]
I've selected [**startReplica(c *cli.Context)**](https://github.com/openebs/jiva/blob/7fac4ee96fe379034c0affeffd8de3f3a420a943/app/replica.go#L159-L341) for refactoring, which is a unit of **165** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by agarwalrounak** [comment]
I will take this up.
