### ISSUE TITLE
Refactor 22 lines occurring 2 times in client.go

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2775]
I've selected for refactoring 22 lines of code which are duplicated in 1 file(s) ([1](https://github.com/openebs/jiva/blob/7fac4ee96fe379034c0affeffd8de3f3a420a943/replica/client/client.go#L244-L267), [2](https://github.com/openebs/jiva/blob/7fac4ee96fe379034c0affeffd8de3f3a420a943/replica/client/client.go#L508-L531)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by agarwalrounak** [comment]
I will give this a try! Please assign it to me.

**Comment by utkarshmani1997** [comment]
@agarwalrounak please go ahead
