### ISSUE TITLE
Show disk attach errors in output of kubectl get bd -n openebs

### ISSUE THREAD

**Issue by briankmatheson** [openebs/openebs#2777]
## Description & Context
The common workflow for installing openebs involves discovering block devices and choosing which devices to use for which classes of storage.  To make this process easier, I'd like us to add an ERRORS column to the output that represents the last error associated with that block device.  This could be a string from the logs, or it could be an enumerated list of conditions that the block device could be in (like tags that automatically get created based on log output associated with that device).

In addition to that, in situations where the *same* device id is seen on multiple hosts, I'd like to represent that by having multiple entries in the bd list (with appropriate hostnames listed) and a "Duplicate" entry for the errors.

## Screenshots
NAMESPACE   NAME                                           NODENAME                       SIZE           CLAIMSTATE   STATUS   AGE  ERRORS
openebs			blockdevice-00000000000000000000000000000001	 foo														1							 Unclaimed		Active	 5s		NotEmpty
openebs     blockdevice-7567bc6317a14b1ee331ed34dc0218b2   ip-10-0-130-168.ec2.internal   107374182400   Claimed      Active   41h	Duplicate
openebs     blockdevice-4367569c506a7b757738fdaa7d50030d   ip-10-0-129-7.ec2.internal     107374182400   Claimed      Active   41h  None
openebs     blockdevice-7567bc6317a14b1ee331ed34dc0218b2   ip-10-0-129-177.ec2.internal   107374182400   Claimed      Active   41h	Duplicate
openebs     blockdevice-8bf90bb7b0fc09345455a02dfe484e61   ip-10-0-130-168.ec2.internal   107374182400   Claimed      Active   41h	None
openebs     blockdevice-c6fe90dbb3847e4b6aafd21368d226d3   ip-10-0-129-177.ec2.internal   107374182400   Claimed      Active   24h	None
openebs     blockdevice-ca534d050ab5ae496ef453da3a3d6508   ip-10-0-130-168.ec2.internal   107374182400   Claimed      Active   24h  None
openebs     blockdevice-f2504cf77338ed627d1a3ace17dbd107   ip-10-0-129-7.ec2.internal     107374182400   Claimed      Active   24h  None
openebs     sparse-03e1e22d44920c227e13c3addba97dce        ip-10-0-129-7.ec2.internal     10737418240    Unclaimed    Active   41h  Mounted
openebs     sparse-194f6ec2ef83d4b190af5fc668de4ca1        ip-10-0-129-177.ec2.internal   10737418240    Unclaimed    Active   41h  Mounted
openebs     sparse-4f250c1ebd3e97388fd70d3f1f840fa4        ip-10-0-131-74.ec2.internal    10737418240    Unclaimed    Active   41h  Mounted
openebs     sparse-6f87133d72f57d8817aa920e1ff3cc2d        ip-10-0-130-168.ec2.internal   10737418240    Unclaimed    Active   41h  Mounted

**Comment by akhilerm** [comment]
Events are added to BlockDeviceClaims as per [#3039](https://github.com/openebs/openebs/issues/3039) which shows the errors.
Also, instead of showing disk errors in BD, the additional NDM exporter component will be showing the blockdevice metrics.
