### ISSUE TITLE
BDD test for incorrect number of block devices in CSPC

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#2787]
## Description
Raid groups in CSPC can have the following number of block devices only : 

stripe -- n where n >=1
mirror -- 2
raidz/raidz1 -- 3
raidz2 -- 6

A BDD test to verify for invalid block device count in CSPC can be written.

## References
See following for sample BDD test : 
https://github.com/openebs/maya/tree/master/tests/cstor/cspc/positive/provisioning

See following for design document and CSPC schema reference : 
https://github.com/openebs/openebs/blob/master/contribute/design/1.x/cstor-operator/doc.md

**Comment by yuvrajsingh79** [comment]
@sonasingh46 I am working on it.
