### ISSUE TITLE
Kubernetes YAML files for running ELK stack on OpenEBS

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#279]
OpenEBS v0.4.0 supports dynamically provisioning Kubrenetes PersistentVolumes - with access type "ReadWriteOnce". 

The configuration files for running these applications are provided under:
https://github.com/openebs/openebs/tree/master/k8s/demo

This issue is raised to seek help to:
- add a new storage class definitions for ELK stack volume needs under [openebs-storageclasses.yaml](https://github.com/openebs/openebs/blob/master/k8s/openebs-storageclasses.yaml)
-  add k8s configuration files for ELK stack - that uses PVCs referring to the above StorageClasses

**Comment by Hrishike** [comment]
I think you should also have an issue created for EFK specs. Did not find any. 
Fluentd allows cluster level logging as well so maybe that would be most used than Logstash in the context of k8s.

**Comment by kmova** [comment]
@Hrishike  thats a great suggestion. Could you go ahead and put in an issue for EFK specs please..

**Comment by Hrishike** [comment]
@kmova sure will do.

**Comment by ksatchit** [comment]
The EFK (which definitely seems the more popular solution for kubernetes) specifications are available here: 

- https://github.com/openebs/openebs/tree/master/k8s/demo/efk

However, there are some users still interested in Logstash. The following content should help with bringing this up: 
- https://crondev.com/elk-stack-kubernetes/

**Comment by muratkars** [comment]
There is an EFK stack example [here](https://github.com/openebs/openebs/tree/master/k8s/demo/efk).
