### ISSUE TITLE
BDD for resource and limit request passing from CSPC

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#2790]
## Description
After the creation of CSPC, CSPI(s) and corresponding pool deployments are created. ( Check design document in the Reference section to know more about this.)
We can pass the resource and limit requests to the pool deployment by specifying it on CSPC.
A BDD test can be written to verify this

## Context
See the following PR to know more about resource and limit request passing and create the test cases.
https://github.com/openebs/maya/pull/1444

## References
See following for sample BDD test :
https://github.com/openebs/maya/tree/master/tests/cstor/cspc/positive/provisioning

See following for design document and CSPC schema reference :
https://github.com/openebs/openebs/blob/master/contribute/design/1.x/cstor-operator/doc.md

**Comment by nikitaankita** [comment]
I can work on this issue !!

**Comment by akhilerm** [comment]
@sonasingh46  Where these tests included as part of making CSPC beta?
