### ISSUE TITLE
OpenEBS  on Rancher, volume mount issue during NodeDown 

### ISSUE THREAD

**Issue by WoodProgrammer** [openebs/openebs#2796]
Hello I'm running Kubeernetes at `v1.15.4` version on rancher . I have installed iscsi compoent and started services on all nodes (workers) . When I shutdown the node for nodeDown test kubernetes-scheduler assign pod to the another healthy node, everything looks OK until there .

But pod is returning `ContainerCreating` state forever , `describe` logs at below , 

`attachdetach-controller    Multi-Attach error for volume "default-demo-vol1-claim-AAAAA` and `Volume is already used by pod(s) percona-767db88d9d-t8d55`
 
After when I wait 5-6 minute some times Kubernetes schedule the pods with new volumes, but this success status is not determined . 

I can handle this `Watch()` the node events via custom-controller on and drain node maybe  ? But need officall and native solution suggestion handle this issue .

Thanks 

Notice : I'm draining nodes manually after shutdown on my test cases .

**Comment by dingsongjie** [comment]
This issue has stuck me a lot of time to really apply openebs to the production environment.

**Comment by WoodProgrammer** [comment]
@dingsongjie did you solve this issue ?

**Comment by prateekpandey14** [comment]
@WoodProgrammer please check if this helps https://github.com/openebs/openebs/issues/2536#issuecomment-530802086

**Comment by akhilerm** [comment]
@WoodProgrammer  Can you check if this helps. https://blog.mayadata.io/recover-from-volume-multi-attach-error-in-on-prem-kubernetes-clusters
