### ISSUE TITLE
OpenEBS is not working with Rancher 2.2.8 and 2.3.0 

### ISSUE THREAD

**Issue by cjohn001** [openebs/openebs#2799]
A discussion on slack can be found here:
 
https://app.slack.com/client/T3NU2A2UV/C3NPGQ6G3/thread/C3NPGQ6G3-1571165120.188500

The Setup is a single node installation for Rancher server and A Rancher provisioned cluster. 
HW is based on a virtual Server from Netcup. The server has RancherOS v1.5.4 installed. Rancher Server was started with 

```
docker run -d --restart=unless-stopped \
	-p 8080:80 -p 8443:443 \
	-v /home/rancher/certificates/rancher.my-nutri-diary.de.cert.pem:/etc/rancher/ssl/cert.pem \
	-v /home/rancher/certificates/rancher.my-nutri-diary.de.key.pem:/etc/rancher/ssl/key.pem \
	-v /home/rancher/certificates/cacert.pem:/etc/rancher/ssl/cacerts.pem \
 	-v /opt/rancher:/var/lib/rancher \
	rancher/rancher:v2.2.8
```

I also followed the description to enable iscsi on the OpenEBS website:
sudo ros s enable open-iscsi
sudo ros s up open-iscsi
ros config set rancher.services.user-volumes.volumes  [/home:/home,/opt:/opt,/var/lib/kubelet:/var/lib/kubelet,/etc/kubernetes:/etc/kubernetes,/var/openebs]
system-docker rm all-volumes
reboot

On the same server than a cluster was provisioned, etcd, Control Plane, Worker with the attached cloud-config extensions. Also following openebs website. The aim is to use LocalPV with hostpath. I tried out OpenEBS Version 1.2 and 1.3

[cloud-config.yml.txt](https://github.com/openebs/openebs/files/3731645/cloud-config.yml.txt)

As  the analysis in the channel shows, the pv and pvc are created, but the container gets stuck during provisioning, seems like the container cannot see/access the folder which openebs has created under /var/openebs/local/pvc-name

**Comment by akhilerm** [comment]
@cjohn001 Can you check if the issue still exist with latest version of Openebs (v2.1)
