### ISSUE TITLE
OpenEBS components deployment strategy / tracker

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#28]
This will act as a common placeholder to discuss & debate about deployment, maintenance, upgrade, rollback strategies of various OpenEBS components.

We should have clarity to questions like:
- Should OpenEBS components rely on systemd ?
- Should OpenEBS components run as containers & managed by some tool similar to kubelet ?
- Should OpenEBS components runs as containers or standalone binaries & managed by Nomad ?
  - *Here Nomad is being referred as tool for deployment & management of OpenEBS components*
- What happens if container runtime require an upgrade ?
- Can multiple versions of container runtime (*e.g. dockerd, rkt engine*) be used across hosts ?
- What happens if orchestrator engine requires an upgrade ?
- Can multiple versions of orchestrator engine be used across hosts ?

### Alternatively:

```yaml
- Can we just use tried & tested tools like Ansible:
  - https://github.com/openshift/openshift-ansible
  - https://www.ansible.com/tower
  - https://github.com/ansible-semaphore/semaphore
  - https://github.com/purpleidea/mgmt
  - https://github.com/dmsimard/ara
```

### Alternative:

```yaml
- http://operable.io/
```

### References:
- https://www.infoq.com/news/2017/02/common-kubernetes-fail-reasons
- [Lets find why deployment failed](https://github.com/rosskukulinski/k8s-scripts/blob/master/bin/debug-deployment)

**Comment by kmova** [comment]
The initial prototype was done with nomad till 0.3 and post 0.4, the containers are orchestrated with Kubernetes. The upgrade strategies follow the rolling-upgrade in most cases.
