### ISSUE TITLE
Add Ukrainian translation

### ISSUE THREAD

**Issue by daniloff200** [openebs/openebs#2812]
## Description
As a native Ukrainian & Russian speaker, I want to add translation in Ukrainian here (and also, spellcheck the Russian version)
## Context

I think, it's very cool for anyone, when you can find some doc / guide in your native language

## Possible Solution
If it's suitable, I can create a PR with these changes, as my Hacktoberfest contribution to OpenEBS

**Comment by AmitKumarDas** [comment]
This sounds good. Please go ahead.
Need to find someone to get this reviewed :) cc @muratkars @kmova

**Comment by muratkars** [comment]
Thank you @daniloff200 
You can find my first attempt to translate the README.MD to Russian [here](https://github.com/openebs/openebs/blob/master/translations/README.ru.md) which is out-dated and needs update as well as all other MD files. 
You can place them under `openebs/translations/` directory following the `FILENAME.ru.md` format.
