### ISSUE TITLE
EKS /dev/sda and /dev/xvda mismatch

### ISSUE THREAD

**Issue by KhojiZoda** [openebs/openebs#2814]
There's bug in PVC creation.
When you create a PVC on EKS, a virtual disk is created inside one of the nodes. Since the node creation respects a naming criteria `SD`+{letter_in_alphabetic_order}  the first PVC will never work since the `SDA` is in DEVLINKS of xvda which is root reserved.

```
# udevadm info /dev/xvda
P: /devices/vbd-51712/block/xvda
N: xvda
S: sda
E: DEVLINKS=/dev/sda
E: DEVNAME=/dev/xvda
E: DEVPATH=/devices/vbd-51712/block/xvda
E: DEVTYPE=disk
E: ID_PART_TABLE_TYPE=gpt
E: ID_PART_TABLE_UUID=95448c7f-0fc9-4174-88bf-0232c3194774
E: MAJOR=202
E: MINOR=0
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=1208
```

## Current Behavior
Warning  FailedMount  50s (x14 over 29m)   kubelet, ip-10-0-0-209.us-west-2.compute.internal  MountVolume.WaitForAttach failed for volume "pvc-8104e495-f3fc-11e9-ab79-02ddacdb84c0" : failed to get any path for iscsi disk, last err seen:
Could not attach disk: Timeout after 10s

## Possible Solution
The `/dev/sda` naming should be blacklisted since it's root reserved.

## My Environment
EKS cluster with 3 nodes. 
* `kubectl get nodes`:
```
➜  openebs kgn
NAME                                       STATUS   ROLES    AGE     VERSION
ip-10-0-0-117.us-west-2.compute.internal   Ready    <none>   7m26s   v1.14.7-eks-1861c5
ip-10-0-0-182.us-west-2.compute.internal   Ready    <none>   7m24s   v1.14.7-eks-1861c5
ip-10-0-1-174.us-west-2.compute.internal   Ready    <none>   7m21s   v1.14.7-eks-1861c5
```

**Comment by kmova** [comment]
@KhojiZoda - where you able to get this working by blacklisting /dev/sda? Can you provide the steps for it, please.

**Comment by kmova** [comment]
Thanks to @kaosmonk and @pawanpraka1 for debugging and finding a solution for this issue. 

### Cause

As per the [device mapping](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html) docs from EKS, it is expected to have the `xvda` mapped to `sda`, without really having the actual `/dev/sda` created on the node. This results in iscsid to pick up `sda` as the next available device to be used, but will fail to perform IO on that device. 

For example, on the following node with OS and and additional device attached, the udevadm info showed: 

```
# udevadm info /dev/xvda
P: /devices/vbd-51712/block/xvda
N: xvda
S: sda
E: DEVLINKS=/dev/sda
E: DEVNAME=/dev/xvda
E: DEVPATH=/devices/vbd-51712/block/xvda
<trunc>
```

```
# udevadm info /dev/xvdf
P: /devices/vbd-51792/block/xvdf
N: xvdf
S: sdf
E: DEVLINKS=/dev/sdf
E: DEVNAME=/dev/xvdf
E: DEVPATH=/devices/vbd-51792/block/xvdf
<trunc>
```

Even though udevadm shows that xvda and xvdf are mapped  `sda` and `sdf` respectively, there are no devices created for sda and sdf under `/dev`. This will lead the iscsi sub-system to pick the next available scsi device under the /dev/, which happens to be `/dev/sda`. This inconsistency in reference between the OS disk (xvda -> sda) and iscsi virtual disk also mapped to ( sda), causes the failed mounts. 

Note: The next iSCSI volume would succeed as it would pickup `/dev/sdb` as the device. 

### Solution

As suggested by @KhojiZoda, the solution is to blacklist the devices that virtio driver has a hold on. 

To black-list those devices from getting picked up, the worker nodes can be configured with udev rules. The udev rules should be configured at the boot time before the worker nodes join the cluster. This can be achieved by adding a user-data script that is executed at the boot time. The script can be something like: 

```
cat << 'EOF' > /etc/udev/rules.d/999-custom-blockdevice.rules
ACTION=="add|change", KERNEL=="xvda", ENV{ID_SERIAL_SHORT}="%E{ID_SERIAL}", SYMLINK="xda"
ACTION=="add|change", KERNEL=="xvdf", ENV{ID_SERIAL_SHORT}="%E{ID_SERIAL}", SYMLINK="xdf"
EOF

udevadm control --reload && udevadm trigger
```

The new configuration for the xvda and xvdf will look like: 

```
# udevadm info /sys/block/xvdf
P: /devices/vbd-51792/block/xvdf
N: xvdf
S: xdf
E: DEVLINKS=/dev/xdf
E: DEVNAME=/dev/xvdf
E: DEVPATH=/devices/vbd-51792/block/xvdf
```

```
# udevadm info /sys/block/xvdf
P: /devices/vbd-51792/block/xvdf
N: xvdf
S: xdf
E: DEVLINKS=/dev/xdf
E: DEVNAME=/dev/xvdf
E: DEVPATH=/devices/vbd-51792/block/xvdf
```

Also, corresponding block devices will be shown under `/dev/`

```
# ls -la /dev/x
xda    xdf    xen/   xvda   xvda1  xvdf   xvdf1  xvdf9
```

**Comment by pre** [comment]
I can confirm that this is still an issue with AWS EKS 1.17 as of September 2020.

**Comment by kmova** [comment]
@akhilerm is there any new information on this issue? Does the partition based UUID help here?

**Comment by pre** [comment]
@kmova From my testing (above) I can say that `/dev/disk/by-path` does not exist at all unless the given `999-custom-blockdevice.rules` is used. 

Hence, if the cStor EBS block device (iscsi mount) is searched from `/dev/disk/by-path` it will not be found regardless of UUID being used.

**Comment by pre** [comment]
Here are instructions for a repro:

1) Use the following Terraform to create an EKS Cluster using https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/basic

2) Edit main.tf and replace `worker_groups` with the following `worker_groups_launch_template`: 

```
  [..]
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v12.2.0"
  cluster_version = "1.17"
  [..]

  worker_groups_launch_template = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      additional_userdata           = "echo foo bar lolcat"
      asg_desired_capacity          = 1
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
    {
      name                          = "storage-1"
      instance_type                 = "t2.medium"
      kubelet_extra_args            = "--node-labels=openebs.io/nodegroup=storage-node"
      additional_userdata           = "echo foo bar doge"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 3
      asg_max_size                  = 3
      asg_min_size                  = 3
      additional_ebs_volumes = [
        {
          block_device_name     = "/dev/sdb"
          volume_size           = 98
          volume_type           = "gp2"
          encrypted             = false
          delete_on_termination = true
        }
      ]
    }
  ]
```

**Comment by akhilerm** [comment]
The above given workaround is still the way if the issue is encountered during provisioning.
