### ISSUE TITLE
Add OpenEBS operator to KUDO Operators

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2817]
Kubernetes Universal Declarative Operator (KUDO) is a operator framework for stateful application on Kubernetes. 
KUDO let’s you configure an operator’s lifecycle using a declarative spec, more information [here](https://kudo.dev/).

Proposal to roll-out OpenEBS KUDO operator:
**Phase 1:** Basic KUDO operator to deploy OpenEBS using the KUDO framework from KUDO repository based on the current Helm chart templates. Create the `params.yaml` file, create a single tasks to deploy and place all OpenEBS manifests into single deployment task.
**Phase 2:** Split installation of OpenEBS components such as NDM, Snapshot Provisioner, LocalPV, CSI or others into logical group and deploy under separate groups to give AppOps options to deploy functionality they consume.
**Phase 3+:** Improve 2nd day operations, upgrades and backups and deeper integration with KUDO operator framework to provide storage for other operators.

**Comment by akhilerm** [comment]
@muratkars Was OpenEBS added to KUDO operator.? If yes, can you provide any reference links.
