### ISSUE TITLE
The Headings on the page must need to highlighted.

### ISSUE THREAD

**Issue by shahidafrid526** [openebs/openebs#2818]
On the page, if the #heading and subheadings highlighted than it may look more attractive to the users.

![web open orgi](https://user-images.githubusercontent.com/28712196/67616471-e0614f80-f7f6-11e9-9080-e35de94c7e09.JPG)

**Comment by parammittal16** [comment]
Hi @shahidafrid526 I would be happy to do this

**Comment by parammittal16** [comment]
https://github.com/openebs/openebs-docs/pull/675
