### ISSUE TITLE
Kubernetes YAML files for running Minio using OpenEBS Volumes.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#282]
## Is this a BUG REPORT or FEATURE REQUEST?
  FEATURE REQUEST

**What happened**:
OpenEBS v0.4.0 supports dynamically provisioning Kubernetes PersistentVolumes - with access type "ReadWriteOnce".

The configuration files for running these applications are provided under:
https://github.com/openebs/openebs/tree/master/k8s/demo
https://github.com/openebs/openebs/blob/master/k8s/openebs-storageclasses.yaml

**What you expected to happen**:
Add k8s configuration files for Minio - that uses PVCs referring to the above StorageClasses

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Reference : https://linode.com/docs/applications/containers/deploy-minio-on-kubernetes-using-kubespray-and-ansible/
