### ISSUE TITLE
Add vulnerability scanner to github actions

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2834]
Automate the process of checking for the security vulnerabilities  by adding https://github.com/aquasecurity/trivy to travis.

**Comment by akhilerm** [comment]
Trivy check has been added to [linux-utils](https://github.com/openebs/linux-utils) repository. As we are now slowly migrating from travis to github actions, may need to find a vulnerability scanner to be used with github actions.

[CodeScanning](https://github.blog/2020-09-30-code-scanning-is-now-available/) from github is one option.

**Comment by panos** [comment]
Can I take this? @akhilerm

**Comment by panos** [comment]
Additionally, when should the workflow be triggered?

e.g. should it be triggered by a cronjob periodically (if so, how often?), or when someone pushes a new commit instead?

**Comment by akhilerm** [comment]
Sure @panos. I have assigned the issue to you.

> when should the workflow be triggered?

The workflow should be triggered for the following cases:
1. On every pull request to the repo.
2. Every commit to the default/master branch on the repo.

**Comment by panos** [comment]
I'm presuming that [this workflow](https://github.com/marketplace/actions/gp-security-scan) is fine? @akhilerm

**Comment by panos** [comment]
Excuse me, but what is the code analyzer specifically meant to analyze, considering that there's basically no source code or basically anything that can be directly compiled in this repository?

**Comment by akhilerm** [comment]
In the [linux-utils](https://github.com/openebs/linux-utils) repo we are using trivy to scan for any vulnerabilities in the image that is built. So we need to get that behaviour in github actions.

**Comment by panos** [comment]
Well, I guess there's [Kubetrivy](https://github.com/masahiro331/kube-trivy)...?

I'd (or someone else, in case this seems to go beyond my current skillset) have to come up with an entirely new GitHub Action for that. I'll see.

**Comment by akhilerm** [comment]
cc: @kmova , what is the current scope of this issue? Should we stick with just trivy or search for alternatives?

**Comment by prakhargurunani** [comment]
@akhilerm I can easily accomplish this. Can you please assign it to me ?

**Comment by panos** [comment]
@prakhargurunani I'm good, thanks.

**Comment by akhilerm** [comment]
For repos like [linux-utils](https://github.com/openebs/linux-utils), which do not have any code, only the container image scanning is required. For other repos like [maya](https://github.com/openebs/maya), [node-disk-manager](https://github.com/openebs/node-disk-manager)  . .etc, both image scanning and code scanning for vulnerabilities is needed.


@panos Will you be able to work on this?

**Comment by panos** [comment]
Will seek to it, just wasn't sure of what to do because I thought that the scope was limited within this repository itself.

Well, that makes much more sense now.

**Comment by panos** [comment]
Hi, I'm just giving notice that I know how to go around with this and am currently working on this, but I am currently a bit busier than usual. I'm trying my best.

**Comment by panos** [comment]
May still contribute some workflows if any of them are still missing by the time my schedule is clear, but I'm freeing this assignment in order to not prevent others from working on it.

**Comment by akhilerm** [comment]
@prakhargurunani, Do you want to take up this issue?

**Comment by prakhargurunani** [comment]
Yes...I would like to take up this issue.

**Comment by akhilerm** [comment]
@prakhargurunani I have assigned the issue to you.

**Comment by prakhargurunani** [comment]
@akhilerm My PR is ready...But I have removed codespell from it. Codespell was not initialising in Docker and was giving errors. I googled a lot, but none of the solutions worked. But we can use codespell through GitHub Actions. What do you think ?

**Comment by akhilerm** [comment]
Thanks @prakhargurunani . 

Sure, we can use it via github actions. 2 checks might not be required. Lets focus on gh actions for now. 
Also, can you tag me once you have raised the PR.

**Comment by akhilerm** [comment]
Trivy scanner has been added to [openebs/linux-utils](https://github.com/openebs/linux-utils) repo via https://github.com/openebs/linux-utils/pull/8
