### ISSUE TITLE
CI/CD and cloning - how to make use of?

### ISSUE THREAD

**Issue by SVronskiy** [openebs/openebs#2844]
## Description
Hello,

According to [What is OpenEBS?](https://www.youtube.com/watch?v=94SFY3xdjXs) it should be easy to realize  development->staging->production DEVOPS using OpenEBS. Indeed it is a problem.

We need to separate all development environments (about 20 envs) from each other and from staging and production environments. Currently we  do so by separating production env to "production" on-premises kubernetes cluster (located in company DMZ), staging and each of development environments - by separating to different namespaces in "development" on-premises kubernetes cluster (located in company internal network). We create separate namespaces with complete set of microservices, mssql, postgres, redis etc. All production pods store their data on production NFS server. We use daily copy of pod's data from production NFS server to ZFS pool on development NFS server. Then we make use of ZFS cloning feature and ZFS ShareFS feature to provide individual clones for each pod in each of development/staging namespaces. Everything works fine, but we have the single point of failure - if NFS server fails, everything stops. 

We are discussing how to make use of OpenEBS for our case and dealing with problem. According to [Introducing Volume Cloning Alpha for Kubernetes](https://kubernetes.io/blog/2019/06/21/introducing-volume-cloning-alpha-for-kubernetes/) we are not able to use PVC clones in another namespaces.

Can you recommend how to realize our DEVOPS scenario using OpenEBS?

## Possible Solution
We hope to make use of OpenEBS to provide HA for each of microservices, do not have single point of failure, be able to deploy new development environments in seconds/minutes by using CI/CD pipelines.

**Comment by kmova** [comment]
@SVronskiy - would you able to join the Slack to take the discussion forward. https://openebs.org/community

**Comment by SVronskiy** [comment]
Opened feature request at kubernetes: [cloning volumes across different namespaces feature](https://github.com/kubernetes/kubernetes/issues/85519)

**Comment by kmova** [comment]
OpenEBS currently support backup and restore via the openebs-velero plugin for the cstor  data engine. This plugin can be extended to support local snapshots - based on a setting passed via the backup command to the plugin. When the local flag is enabled, the task to copy data to remote S3 can be skipped. 

During restore, the data from the snapshot can be used to create the cloned volume.

**Comment by SVronskiy** [comment]
Thank you, @kmova! We will test Velero 1.2 [Clone PVs When Cloning a Namespace](https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0) feature, to be sure that cloned RabbitMQ, Redis, Posgres, MsSql etc works well in another namespace. Will back to here with results. Waiting for OpenEBS Velero Plugin to support "Clone PVs When Cloning a Namespace" on the basis of ZFS cloning to make cloning of 3Tb DB quick and do not take any additional HDD space.

**Comment by kmova** [comment]
The implementation for Local Snapshot and Clone into a new Namespace via velero plugin is being implemented via the following PRs: 
- https://github.com/openebs/maya/pull/1570
- https://github.com/openebs/maya/pull/1575
- https://github.com/openebs/maya/pull/1576
- https://github.com/openebs/velero-plugin/pull/46
- https://github.com/openebs/velero-plugin/pull/47

**Comment by mynktl** [comment]
Issue/PR created in velero to map PV with storage assets created by storage vendor.
https://github.com/vmware-tanzu/velero/pull/2216
https://github.com/vmware-tanzu/velero/issues/2215

**Comment by mynktl** [comment]
Closing this issue. Changes are merged and verified. cc: @shashank855

**Comment by mynktl** [comment]
Reference doc for volumesnapshotlocation to achieve local snapshot/restore feature, https://github.com/openebs/velero-plugin/blob/master/README.md
cc: @shashank855
