### ISSUE TITLE
Move the OpenEBS OperatorHub listing to upstream repo

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2848]
# Description
Move OpenEBS Helm Operator to [upstream](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators) repository location.

## Context
Currently OpenEBS is listed as a Community Operator under the OperatorHub https://github.com/operator-framework/community-operators/tree/master/community-operators repository.
When OpenShift is installed, first, it shows the upstream operator on its OperatorHub menu and it takes time for community operators to show up.
OpenEBS is a commercially supported CNCF project and it would be a better fit if it is listed under the https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators repository.

**Comment by ksatchit** [comment]
Closed on the basis of https://github.com/openebs/helm-operator/issues/6#issuecomment-574506648!
