### ISSUE TITLE
Share your go-programming karma in documentation/techbits

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#285]
Add to some helpful content for beginner gophers viz setting up a better go environment.
Have some cool blog, or a link to your opinionated dotfiles?
Send them [here](https://github.com/openebs/openebs/tree/master/documentation/techbits)

**Comment by vharsh** [comment]
Getting up to speed with [Vscode](https://www.youtube.com/channel/UCs5Y5_7XK8HLDX0SLNwkd3w).

**Comment by Apollo9999** [comment]
Programming a Text Adventure Game in Elixir  Elixir is built on top of Erlang  https://www.youtube.com/watch?v=2Dzwqr_prgU
