### ISSUE TITLE
Allow volumeExpansion also for XFS

### ISSUE THREAD

**Issue by davidkarlsen** [openebs/openebs#2851]
## Description
https://docs.openebs.io/docs/next/alphafeatures.html#expand-cstor-volume-created-using-csi-provisioner says volumeexpansion can only happen for extX filesystems - but it should be possible for XFS too.

## Context
We prefer XFS filesystems and this is default for our storage-classes - and would like the easy way to expand volumes.

## Possible Solution
I guess implementation would be similar to extX as xfs allows for online expansion when using `xfs_growfs` cmdline

## Screenshots
N/A

**Comment by ranjithwingrider** [comment]
Hello @davidkarlsen . This support is coming with 1.5 release which is aligned for this week. Details of PR is here- https://github.com/openebs/cstor-csi/pull/57

**Comment by prateekpandey14** [comment]
CStor csi driver support the resize for xfs , ext4 filesystem based volumes.
