### ISSUE TITLE
A (healthy) slow replica on cStor or Jiva can cause volume read-only. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2854]
## Description

Jiva/cStor Target replicates the writes to all the available replicas. The reads are served by reading from one of the healthy replica. In case of writes, the target waits for a response from all the replicas before sending a success response to the initiator(iSCSI client).

Consider a scenario where there are 3 healthy replicas. One of the replica is having a disk slowness or has huge network latency and the IO to that slow replica takes more than 15-30 seconds. 

Therefore even when we have 3 replicas and IO was successful on 2, we still wait for 15-30 seconds which might cause disconnection from initiator. This can cause the volumes to be marked as read-only and application can go into crashloop. 

## Expected Behavior
- The slow replica should be marked as unhealthy and taken out of the quorum. 
- Volume should not be going into read-only state when quorum is available with healthy replicas. 

## Current Behavior
- Volume gets into read-only.

**Comment by vishnuitta** [comment]
is this easily reproducible? if so, limits on waiting time can be reduced..
would like to know the highest latency from replica that the volume can tolerate

**Comment by akhilerm** [comment]
@kmova @vishnuitta Do we have an update or fix on this issue?

**Comment by payes** [comment]
A litmus test is required for this issue.
