### ISSUE TITLE
Upgrade of cstor pool fails due to image tag parsing

### ISSUE THREAD

**Issue by davidkarlsen** [openebs/openebs#2857]
## Description
Upgrade of cstor pool using job as described on https://github.com/openebs/openebs/blob/master/k8s/upgrades/README.md failed.
It seems to be due to parsing of image tag based on `:`
we run in an airgap env where we go through internal docker proxy, hence there will be two `:` in image: ourserver:port/openebs/theimagename:thetag

## Expected Behavior
Should set correct images and tags

## Current Behavior
image will be set to quay.io/openebs/fsdepot.evry.com:1.5.0

## Possible Solution
tried using - "--to-version-image-prefix=fsdepot.evry.com:8085/openebs/" arg
For the parsing of tag, rather split string on : and use last segment as tag. Leave elements left of last `:` as they were.

## Steps to Reproduce
have a cstor pool using images named as explained above

## Your Environment
N/A
OpenEBS 1.4.0 -> 1.5.0
control-plane was successfully upgraded with helm prior to attempting data-plane

See thread on slack https://openebs-community.slack.com/archives/C3NPGQ6G3/p1576341369008300

**Comment by kmova** [comment]
The 1.5 upgrade image was repushed with the above fix. Thanks @davidkarlsen for reporting this issue.
