### ISSUE TITLE
Support Hostpath PV backed by a shared mount. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2861]
### Scenario: 

In certain scenarios, the K8s cluster nodes are attached with a shared mount - either coming from a NFS or via ObjectFS or EFS and so forth. 

The users would like to create a PV either with RWO or RWM mode on this shared directory.  Each PV will get its own directory. 

Compared to Local PV, this shared PV will not be associated with any node.

It should be possible to move the Pod from one node to another node that has the shared mount and the PV should be accessible. 

### Proposed Solution

Extend the functionality of the OpenEBS hostpath to specify  addtional parameters required for provisioning PVs on shared path: 
- type: indicating it is shared 
- affinity: specifying the nodes on which the shared mount is mounted. the provisioner can use this information to launch the helper pod.

**Comment by rajibmitra** [comment]
@kmova  is it still open to work on ?

**Comment by rahulchheda** [comment]
@kmova Here is a design document and workflow, how would I approach this issue. Please take look: https://docs.google.com/document/d/1s6UBo_tMaU2RE4iaHoGgYxchier62DpgfQkAQ8a07Ew/

**Comment by akhilerm** [comment]
This will be implemented via kubernetes NFS provisioner. 
cc: @kmova For updates on the k8s NFS Provisioner work.
