### ISSUE TITLE
Airgapped installation scripts

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2863]
## Description
To be able to install OpenEBS into a airgapped environment we need scripts to create offline installation container image tarball files and script to save the images into a local registry from the tarball images.

**Comment by muratkars** [comment]
I'm suggesting to add these three files into release assets for 1.5 @kmova 

List of images:
https://github.com/muratkars/openebs/blob/airgap/scripts/openebs-images.txt
Script to create a tarball:
https://github.com/muratkars/openebs/blob/airgap/scripts/openebs-save-images.sh
Script to load images to a local registry location from the tarball
https://github.com/muratkars/openebs/blob/airgap/scripts/openebs-load-images.sh
SHA256 summary for the files above:
https://github.com/muratkars/openebs/blob/airgap/scripts/sha256sum.txt

**Comment by kmova** [comment]
Thanks for working on this @muratkars  - Can you push the code into https://github.com/openebs/charts under the scripts/airgapped folder.

**Comment by muratkars** [comment]
Addressed in https://github.com/openebs/charts/pull/57 @kmova

**Comment by briankmatheson** [comment]
Ideally these scripts would pull down all of the artifacts we publish as part of all (future?  tagged with a specific substring?  how do we want this to work?) releases of openebs, litmus, and director on-prem.  It should also support optional additional image names to be pulled via a command-line arg or env var (probably env var is better), and we should supply job yaml for pulling into a volume and pushing from a volume.  Docs for this should include manual operation for actually installing from usb media or the like, as well as using a kubernetes job to do this.

This way if they want to have a management cluster that hosts and has access to the registry for the cluster under test, they can update it easily (and test bug fixes easily I hope).

My 2c,
Brian

**Comment by muratkars** [comment]
Merged
