### ISSUE TITLE
Jiva controller pod not moved when Node in NotReady state.

### ISSUE THREAD

**Issue by atulabhi** [openebs/openebs#2870]
## Description

The jiva controller pod did not moved to new node after my node went into unknown state. Due to which the volume went into read only.
## Expected Behavior

The pod should move to new node within 1 minute if the node is not ready or in unknown state

## Current Behavior

I excpected the pod on the "crashed" node to be moved to the remaining node.
## Possible Solution

change the default toleration which is set to 0 to 30 sec
## Steps to Reproduce

create a new pvc 
stop the docker on which target pod is running.
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by akhilerm** [comment]
@prateekpandey14 @payes Does this issue still exist in jiva or is it fixed?
