### ISSUE TITLE
Support for Prometheus metrics for Local PV by maya exporter

### ISSUE THREAD

**Issue by stephenmoloney** [openebs/openebs#2884]
### Description
Support for Prometheus metrics for `Local PV` by maya exporter

Prometheus metrics are only exported to prometheus for `cstor` & `jiva` PV provisioners.
Related is that [mayactl](https://docs.openebs.io/docs/next/mayactl.html) isn't supported for `localPV` 

### Context
Useful for metrics analysis

**Comment by akhilerm** [comment]
The localPV metrics are made available using a separate monitoring service.
[Monitor-PV](https://github.com/openebs/monitor-pv) can be used for getting localPV metrics. Also [NDM exporter](https://github.com/openebs/node-disk-manager/blob/0baecdcae8929b6ddc6f850ca5c47eb9150af025/ndm-operator.yaml#L259) can be used for getting metrics of blockdevices used in localPV.

@stephenmoloney can you try out the above service and see if it solves your use-case.

cc: @kmova
