### ISSUE TITLE
CSPC compression off doesn't work

### ISSUE THREAD

**Issue by SVronskiy** [openebs/openebs#2885]
I followed scenario in [cStor Pool Operations via CSPC in OpenEBS blog](https://blog.mayadata.io/openebs/cstor-pool-operations-via-cspc-in-openebs). 

There is "compression: off" setting in CStorPoolCluster, but when I get into the pool pod and check "zfs get all | grep compression" compression is on. Why?

**Comment by mittachaitu** [comment]
Hi, @SVronskiy thanks for trying the cStor pool provisioning via CSPC some fields are not yet honored we will fix it in upcoming releases.

**Comment by sonasingh46** [comment]
Hi @SVronskiy -- The compression feature has made into the CSPC. 
Here are the relevant PRs: 
https://github.com/openebs/cstor-operators/pull/26
https://github.com/openebs/cstor-operators/pull/27

Please reopen the issue if you still are facing any issues.
