### ISSUE TITLE
Katakoda openEBS

### ISSUE THREAD

**Issue by SVronskiy** [openebs/openebs#2890]
Hello!

You have exellent [Stateful applications pages](https://docs.openebs.io/docs/next/): Prometheus, Minio, Gitlab, Percona, Elasticsearch, Cassandra, NuoDB, PostgreSQL, Redis, MongoDB, JIRA, NFS etc. You have good corresponding [youtube videos](https://www.youtube.com/channel/UC3ywadaAUQ1FI4YsHZ8wa0g),

It would be greate to create the same learning tutorial at [Katakoda Kubernetes](https://www.katacoda.com/courses/kubernetes) or [Katakoda CNCF](https://www.katacoda.com/courses/cloud-native-computing-foundation).

It looks like Murat Karslioglu tried to [create tutorials at Katakoda](https://www.katacoda.com/openebs) 2 years ago, but it doesn't work now.

Take a look for samples at your [competitors](https://www.katacoda.com/portworx).

Thanks.

**Comment by muratkars** [comment]
Thanks for pointing out @SVronskiy. @kmova is checking the eligibility to use Katacoda as CNCF project. I will update the current instructions for 1.7 release.
