### ISSUE TITLE
Document airgapped OpenEBS installation

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#2894]
Document the steps to deploy OpenEBS container images from tarball to local container registry:

Scripts are stored under https://github.com/openebs/charts/blob/master/scripts/airgapped/
Use the below script to load images from tarball:
https://github.com/openebs/charts/blob/master/scripts/airgapped/openebs-save-images-1.6.0.sh

Tarball binary is available on the release page:
https://github.com/openebs/openebs/releases/1.6.0

**Comment by akhilerm** [comment]
@muratkars are the airgapped installation scripts / docs available now. 
cc: @ranjithwingrider Can we update it with latest information.
