### ISSUE TITLE
Need to update install docs for helm v3.

### ISSUE THREAD

**Issue by ybnelson** [openebs/openebs#2895]
helm install --namespace openebs --name openebs stable/openebs --version 1.6.0
Error: unknown flag: --name

**Comment by ranjithwingrider** [comment]
Hi @ybnelson . Thes steps are added to the document. Please let us know if you find any issues with the steps.
https://docs.openebs.io/docs/next/installation.html#installation-through-helm

**Comment by akhilerm** [comment]
@ranjithwingrider @ybnelson Are there any further steps required on this issue?

**Comment by ranjithwingrider** [comment]
I think the given steps will address OpenEBS installation on different helm version. @akhilerm
