### ISSUE TITLE
Question: How openebs_actual_used metric is calculated

### ISSUE THREAD

**Issue by bbkgh** [openebs/openebs#2898]
Hi. I am using openebs with jiva backend storage. I've added a huge file to that volume and then removed it but this metrics (openebs_actual_used) didn't decreased. I also executed fstrim command on that volume and _ls -rlth_ shows right (decreased) size in total section. My question is how openebs_actual_used metric is calculated?
In below image actual used is about 6 Gig and openebs_size_of_volume is 50 Gig but openebs_actual_used returns about 49 Gig.
![Screenshot from 2020-01-27 11-18-21](https://user-images.githubusercontent.com/7341467/73157717-23350b00-40f7-11ea-9233-182eaa258149.png)

**Comment by utkarshmani1997** [comment]
Hi bbkgh. In this case a couple of things are happening: 
* data is written into ext4
* ext4 is mounted without unmap - which is what really recovers the deleted data. (Jiva doesn't yet support unmap feature). 
So as data is written and deleted, you will notice the following:
* du -h ( from within the application pod - will show the correct usage. kube-state metrics of used will reflect this size) 
* as ext4 doesn't reclaim the deleted blocks, jiva will continue to show them as used.
thanks for reporting the issue, this is a limitation with jiva. 

I have created an [issue](https://github.com/openebs/openebs/issues/2975) to track it.

**Comment by akhilerm** [comment]
@utkarshmani1997 @payes  Is this a documentation update?
