### ISSUE TITLE
kubectl plugin to check that nodes meet the openebs prerequisites

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#290]
For OpenEBS volumes to function, there is a dependency on having iscsi-initiator installed on the nodes. A CLI tool like mayactl or kubectl plugin - should have an option to verify if such pre-requisites are met. 

One way to implement this: CLI tool could identify the nodes that will run the stateful workloads and run the following test:
  * create a test volume 
  * run a test pod(job) on the nodes and make sure nodes are able to attach to the volume
  * also verify that attach/detach works by changing the node assigned to a test pod

**Comment by AmitKumarDas** [comment]
This is currently a WIP and can be tracked via following issue(s):
- https://github.com/openebs/openebs/issues/2343

**Comment by championshuttler** [comment]
Hey @kmova! I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?

Thanks
