### ISSUE TITLE
Support for Backup/Restore of CSI based cStor volumes.

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2905]
The current implementation is tightly coupled with SPC/CSP. The code needs to be improved to work with CSPC and CSPI objects. 

Operations to be supported:
- Remote snapshots/backup
- Restore

Observation:
- Backup/restore CRs are not being created
- Backup/restore is not working

In 1.7 release, @shashank855, manually tested the existing plugin to work with cstor alpha components and found that it needs more work.

**Comment by mittachaitu** [comment]
The following are the PR's that incorporate `backup and restore` support for cStor CSI based volumes.
velero-plugin:
- https://github.com/openebs/velero-plugin/pull/91
- https://github.com/openebs/velero-plugin/pull/93

cstor-csi:
- https://github.com/openebs/cstor-csi/pull/90

cstor-operaters:
- https://github.com/openebs/cstor-operators/pull/89
- https://github.com/openebs/cstor-operators/pull/88
- https://github.com/openebs/cstor-operators/pull/83
