### ISSUE TITLE
Share automated with Vagrant or Ansible to configure and install any OS on VmWare ESxi

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#291]
Good starting points
- https://www.ansible.com/vmware
- https://github.com/dougm/vagrant-esxi
- Found something even better? Post it down below :+1: 

If you have a ready to serve solution raise a PR in `documentation/techbits`.

**Comment by vharsh** [comment]
Looks like https://github.com/apcera/libretto is achieving similar goals.

**Comment by debojitkakoti** [comment]
@vharsh What about https://www.packer.io/ ? If it is related to creating images on different cloud including VirtualBox using the packer, I can take it up!

**Comment by vharsh** [comment]
@debojitkakoti Looks good. This one creates an ovf file on our machine which we can push to our servers through vsphere client or something similar.
Using the vagrant plugin will be any easier or more reliable.
