### ISSUE TITLE
cStor CSI Volume remains readonly after rebuilding all the replicas, if the application pod is scheduled on same node.

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#2913]
## Description
- Volume remains in readonly state after rebuilding all the replicas, if the application pod is scheduled on same node as previous one.

## Expected Behavior
- volume should be healthy

## Current Behavior
- volume remained in RO state.

## Steps to Reproduce
- Had created cstor CSI volume with 3 replicas.
- Scaled down two cspi deployments to 0.
- Scaled it up again to 1.
- All the CVR became healthy.
- Deleted the application pod. It scheduled on same node.
- Application kept crashing as the volume remained in RO state.

Attaching the log files of csi-volume-plugin and cstor-target container

**Comment by gprasath** [comment]
[openebs-csi-plugin_logs.txt](https://github.com/openebs/openebs/files/4198723/openebs-csi-plugin_logs.txt)

**Comment by gprasath** [comment]
[target.txt](https://github.com/openebs/openebs/files/4198730/target.txt)

**Comment by payes** [comment]
Kubernetes appears to have corrected the stage/unstage functionality.
In previous versions of kubernetes, volume was staged and unstaged every time a new pod was created even though on the same node which according to the definitions was not correct.
In the logs provided, volume is not restaged if the node is not changed on deleting the pod. We would have done an unmount and remount if unstage and stage request was sent by kubernetes.
 We will fix this by having a check for RO while publishing the volume. For now, you can enable the Remount feature which is turned off by default in cstor-csi.

**Comment by kmova** [comment]
Verify if this is still an issue.

**Comment by nsathyaseelan** [comment]
Verified this with openebs 2.9.0 and kubernetes version 1.20 Followed the below scenarios

- Scale down the two cspi deployment to `0` cstor opertaor brought up this deployments again to `1`
- Scale down the cstor operator deployment to `0` and scaled down the cspi deployment to `0` cvr's are in Healthy state. 
- Restarted the application pod, Application pod is Scheduled on the same node and running volumes are healthy able to create the database in application.
