### ISSUE TITLE
Error while applying - kubectl apply -f openebs-operator.yaml

### ISSUE THREAD

**Issue by harisanker1780** [openebs/openebs#292]
Getting below error while applying - kubectl apply -f openebs-operator.yaml

serviceaccount "openebs-maya-operator" created
error: error validating "config-operator.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by hari-sanker** [comment]
Used openebs-operator.yaml from https://github.com/openebs/openebs/blob/master/k8s/openebs-operator.yaml

**Comment by yudaykiran** [comment]
@hari-sanker , Can you please provide further details such as:

1. Environment Used: Vagrant, Bare-Metal, Cloud(AWS, GCE...).
2. Operating System: Ubuntu, CoreOS, RancherOS....In case of vagrant what's running inside VirtualBox.
3. RAM and CPU capacity of the machine being used.
4. Kubernetes Version

Appreciate your help.

**Comment by hari-sanker** [comment]
Environment Used: Vagrant 1.8.1
OS: Ubuntu 16.04.3 LTS
RAM: 5GB
CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz

Kubernetes: v1.6.3, https://github.com/kubernetes/dashboard

**Comment by harisanker1780** [comment]
This issue has resolved in K8S_VERSION="v1.7.5"

**Comment by yudaykiran** [comment]
@harisanker1780 thanks. Closing this issue based your comment about the issue not occurring in  K8S_VERSION="v1.7.5".
