### ISSUE TITLE
Security vulnerability issues against OpenEBS 1.7 snapshot controller and snapshot provisioner

### ISSUE THREAD

**Issue by ranjithwingrider** [openebs/openebs#2929]
## Description
While uploading OpenEBS1.7 into AWS market place, seeing security vulnerabilities are reported against snapshot provisioner and controller images.

## Expected Behavior
No security vulnerability errors

## Current Behavior
Throwing errors against these images

## Screenshots

![image](https://user-images.githubusercontent.com/22299743/74809779-fa79ed00-5313-11ea-9398-1b8c52bb7811.png)

![image](https://user-images.githubusercontent.com/22299743/74809792-05cd1880-5314-11ea-9dc0-febd537b1c69.png)

**Comment by prateekpandey14** [comment]
fixed with https://github.com/openebs/external-storage/pull/105
