### ISSUE TITLE
Link the Github search of easy issues in the usecase given in labels list 

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#293]
We need to add the link of the Github issues (which are simple, easy to fix, help/small) 
Example: Link to the labels like this `is:open label:help/small`

**Comment by vharsh** [comment]
We have recently organized issues on level of difficulty or the field as described in the [contrib/issues.md](https://github.com/openebs/openebs/blob/master/contribute/issues.md). 
It would make sense to have them organized by colours? Eg. having all the `kind/*` tags of a similar colour?
Or all easy looking tags with light colours.
The `kind/bug` with RED looks great for now.

**Comment by satyamz** [comment]
@vharsh Closing this as we have new labels added recently.
