### ISSUE TITLE
Grafana Dashboard for OpenEBS

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2947]
All the openebs components are deployed as Kubernetes native objects and support scraping of metrics via Prometheus. This is a feature request to implement Grafana dashboards for:
- Overall status of OpenEBS
- Volume Usage Dashboard
- Pool Usage Dashboard

You can find instructions on setting up Prometheus for OpenEBS and launching sample dashboard here: https://github.com/openebs/openebs/tree/master/k8s

**Comment by dizzy1021** [comment]
how do I get started to solve this problem, can you give me some suggestions?

**Comment by kmova** [comment]
Hi @dizzy1021 .. here is a good place to start. https://github.com/openebs/openebs/tree/master/k8s

**Comment by mukundmckinsey** [comment]
@kmova I have created a OpenEBS dashboard in our env. I have uploaded it on grafana.
https://grafana.com/grafana/dashboards/12171

**Comment by kmova** [comment]
Thank you @mukundmckinsey. Pure awesomeness!
