### ISSUE TITLE
Add unmap support for jiva volume

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2975]
## Description

When any data is written at the client side (iscsi) it is replicated to all the n no of jiva replicas. If the space is freed from the client side it is not freed at the replica side because jiva frontend (gotgt) doesn't support unmap.

## Context

Since replicas consume some storage space unnecessarily, it should also do cleanup at the replica side. 

## Possible Solution

Jiva replicas implement unmap but it is not enabled from the [frontend]  (https://github.com/gostor/gotgt) for remote backend. So implementation at frontend side is required to support this feature.

Also if this volume needs to be used for some other applications/databases, it is still usable and the data will be overwritten at the replica side and replica will reclaim the space.

**Comment by SeMeKh** [comment]
@utkarshmani1997 Is this issue related? https://github.com/longhorn/longhorn/issues/836

**Comment by kmova** [comment]
It is @SeMeKh
