### ISSUE TITLE
cStor volume replica scaledown should be restricted if there is only one replica

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#2981]
## Description

- When there is single replica, scale down process should not be allowed. 
## Expected Behavior
- Volume scaledown should not be allowed in such case

## Current Behavior
- It scales down and deletes the replica which leads to data loss

## Steps to Reproduce
- Create cstor csi volume with single replica
- Try to scale down the volume replica by removing cspi name from its respective cvc.
- It allows to scale down and deletes the replica.

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by mittachaitu** [comment]
@prateekpandey14 Can we add this under issue Hactoberfest list? Changes need to be validated [here](https://github.com/openebs/cstor-operators/blob/96760c38fa07f97f3d7073361dbe1e821962d5d3/pkg/webhook/cvc.go#L79).

**Comment by prateekpandey14** [comment]
Yes. admission webhook validation can be added as part of [replica scale validation](https://github.com/openebs/cstor-operators/blob/96760c38fa07f97f3d7073361dbe1e821962d5d3/pkg/webhook/cvc.go#L187)
