### ISSUE TITLE
enable execution of test cases for openebs/cstor arm image in travis

### ISSUE THREAD

**Issue by mynktl** [openebs/openebs#2984]
We have enabled arm builds for openebs/cstor (https://github.com/openebs/cstor/pull/296)
Due to some limitation in travis we have disabled the test case execution for arm images in travis.

**Comment by prateekpandey14** [comment]
@mynktl the limitations still exists ? can we put some infomation about the issues we have with travis.

**Comment by mynktl** [comment]
For `openebs/cstor` repo, we are validating code changes through script https://github.com/openebs/libcstor/blob/master/tests/cstor/script/test_uzfs.sh in [Travis build](https://github.com/openebs/cstor/blob/develop/.travis.yml).

In this script, test function [test_dup_zrepl](https://github.com/openebs/libcstor/blob/master/tests/cstor/script/test_uzfs.sh#L105) requires privileged access during execution. But in Travis, ARM containers are not having privileged access.  Due to this, Travis test will result into failure. To resolve this issue, `test_dup_zrepl` execution can be skipped in travis build for ARM architecture.
