### ISSUE TITLE
Stale BDC gets created if PVC is deleted before it is bound to PV. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2989]
Local PV (device) provisioner leaves a stale BDC in the following case:

- On PVC request, creates a BDC
- If the system doesn't have a matching BD, then PVC request keeps retrying, and so does the NDM operator that keeps retrying 
- Now if the user deletes the PVC, then Local PV (device) provisioner doesn't get the trigger to process delete, as there was no PVC. 

This causes the stale BDC to exist in the system, and NDM keeps on trying to process it. 

To recover from this the BDC needs to be manually edited and then deleted. 

```
Name:         bdc-pvc-4c887f9e-0a02-4cac-abf9-9f485ba8c39e
Namespace:    openebs
Labels:       <none>
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         BlockDeviceClaim
Metadata:
  Creation Timestamp:  2020-04-06T13:34:34Z
  Finalizers:
    local.openebs.io/finalizer
  Generation:        2
  Resource Version:  104120
  Self Link:         /apis/openebs.io/v1alpha1/namespaces/openebs/blockdeviceclaims/bdc-pvc-4c887f9e-0a02-4cac-abf9-9f485ba8c39e
  UID:               7f2c0d11-3206-4f8a-8382-28da5897666c
Spec:
  Block Device Node Attributes:
    Host Name:  gke-kmova-helm-default-pool-61dc2adc-1ppx
  Device Claim Details:
    Block Volume Mode:  Block
  Device Type:          
  Host Name:            
  Resources:
    Requests:
      Storage:  2Gi
Status:
  Phase:  Pending
Events:   <none>
```

**Comment by Icedroid** [comment]
Is bug be fixed?

**Comment by kmova** [comment]
Not yet, but I think I know how to get this fixed now. Looking for some help with contributions.

**Comment by supra08** [comment]
Hi @kmova, Is this open? I would like to give it a try.

**Comment by kmova** [comment]
Thanks @supra08. Yes this is still open. You can join our contributor channel on Kubernetes slack #openebs-dev and we can help you out with more details.

**Comment by supra08** [comment]
Sure! thanks

**Comment by maxisam** [comment]
well, I removed the finalizer and bdc is gone now but bd is still on claimed status

**Comment by kmova** [comment]
@maxisam - Is that BD associated with the BDC that was just deleted. If yes, as a workaround, you could delete the BD itself and restart the NDM pod on that node and the BD will be recreated. 

Also, can you describe what steps were performed to get into this state.

**Comment by maxisam** [comment]
The whole thing was from a misunderstanding. I thought one bd can serve more than 1 bdc. so I created multiple pods asking for storages. And that is how things started.

I realized most pc and pvc can't bind properly. I decided to remove them. And that parts works.

Both bind and unbind are removed. I removed the deployment as well.

and then the bdc is still there. one of them is bound with bd.

Removed the finalizer of bdc. and all of them were gone, but bd were still there, one of them is claimed.
Uninstalled openebs chart but it doesn't make any difference on bd.

Finally, I just removed bd, and most of them are gone now. but the one was claimed is still there.

**Comment by kmova** [comment]
As part of this fix, the following case also needs to be solved:
- Let the BD be bound to the BDC
- Delete the BDC after manually removing the finalizers
- Check if the BD is still pointing to the deleted BDC
- Delete BD and make sure it is getting deleted

**Comment by Nivedita-coder** [comment]
Hi, @kmova is this still open? I would like to work on this issue.

**Comment by niladrih** [comment]
@kmova -- Proposing a solution to this:
1. Error while trying to find a BD bound to a BDC ([link](https://github.com/openebs/dynamic-localpv-provisioner/blob/e57d0171280f6625528519d830c5a530c93a9281/cmd/provisioner-localpv/app/helper_blockdevice.go#L202))
2. Delete BDC
3. Return errors upwards to Provision method.
4. Control loop/sync handler invokes Provision again
5. Retry with a new BDC

**Comment by niladrih** [comment]
Alternatively, please also consider this solution:
1. Error while trying to find a BD bound to a BDC ([link](https://github.com/openebs/dynamic-localpv-provisioner/blob/e57d0171280f6625528519d830c5a530c93a9281/cmd/provisioner-localpv/app/helper_blockdevice.go#L202))
2. Run a PVC watcher sidecar container
3. Return error upwards to Provision method after container probe reports healthy status.
4. Watch for PVC delete
5. Delete BDC on PVC delete event
6. Exit sidecar

**Comment by niladrih** [comment]
Proposal (as discussed with @kmova):
1. Error while trying to find a BD bound to a BDC ([link](https://github.com/openebs/dynamic-localpv-provisioner/blob/e57d0171280f6625528519d830c5a530c93a9281/cmd/provisioner-localpv/app/helper_blockdevice.go#L202))
2. Increment counter for the number of tries
3. Check for BDC age
4. Continue to retry for DefaultFailedProvisionThreshold times.
5. Check for number of retries and BDC age. If a set threshold is reached in either, delete the BDC.
6. PV Provisioning is discarded from workqueue.

**Comment by FridayRU** [comment]
"To recover from this the BDC needs to be manually edited and then deleted."

What should I do after editing the BDC to delete it? Or will it be deleted of itself?
Which fields can be edited?
