### ISSUE TITLE
Third Replica sync takes time in Jiva

### ISSUE THREAD

**Issue by payes** [openebs/openebs#2999]
## Description
When jiva controller is restarted after scaling down the application,  2 replicas are immediately converted to RW state while the 3rd replica takes time.

## Expected Behavior
Since there are no IOs going on and all the 3 replicas had the same data before restarting the controller, 3rd replica also should not have taken time to convert to RW state.

**Comment by prateekpandey14** [comment]
@payes do we have any update on this issue ?
