### ISSUE TITLE
How to upgrade to VirtualBox 5.1 from older version on Ubuntu 16.04

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#30]
Some times, the upgrade can fail due to older version references. In case, you have an option to clean out earlier version, follow these steps:

(a) Remove an existing copy of VirtualBox
```
sudo apt-get remove --purge virtualbox
sudo rm ~/"VirtualBox VMs" -Rf
sudo rm ~/.config/VirtualBox/ -Rf
```

(b) Update the /etc/apt/sources.list, to add the following line at the end:
```
deb http://download.virtualbox.org/virtualbox/debian xenial contrib
```

(c) Upgrade:
```
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt update
sudo apt install virtualbox-5.1
```

**Comment by yudaykiran** [comment]
**Just a quick note**: 
I was having some issues with my virtualbox version 5.1. After debugging I figured out one of virtualbox files had gone missing. I wanted to reinstall virtualbox:

Running the below command did not work as it was unable to find virtualbox. 

`sudo apt-get remove --purge virtualbox`

So I appended the command with a " * " and it was able to detect virtualbox and prompted for removing it.

`sudo apt-get remove --purge virtualbox*`
