### ISSUE TITLE
Suggestions for new issue labels

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#300]
I feel we should also add a few more labels, some organizations have them tagged as `first-timers-only`, `low-hanging-fruits`, `easyfix`.
While it is good to follow existing trends, it is also adventurous to set new ones. 
Suggest some new ones to the [existing list](https://github.com/openebs/openebs/blob/master/contribute/issues.md)

**Comment by vharsh** [comment]
Is it okay to have both `area/maya` and `repo/maya`  issue tags, how different it are they supposed to be?

**Comment by kmova** [comment]
hmmm.. @vharsh you have a point there. maya is really taking on different meanings depending on the context. 
- area/maya refers to the orchestration functionality
- repo/maya refers to the code related to that functionality being checked in to repository/maya. However it is possible that the functionality could also be in other repositories like repo/kuberentes-incubator or repo/jiva. While the area/maya still holds good.
