### ISSUE TITLE
Stuck in Vagrant up

### ISSUE THREAD

**Issue by sivacheerla93** [openebs/openebs#301]
![vagrant up issue](https://user-images.githubusercontent.com/9480389/30311044-1ecc5bdc-97b1-11e7-9bf2-ff5c9b15d2d5.png)
on windows 8

**Comment by kmova** [comment]
Please update this issue with the vagrant version, virtualbox version and the steps execute prior to getting into this error.

**Comment by iamsivacheerla** [comment]
Vagrant version = 2.0.0
Virtual box version = 5.1.26 r117224 (Qt5.6.2)
Both are latest versions.
OS: Windows 8.1 64bit
RAM: 4GB
Processor: Intel Core i3-4010U CPU @ 1.70GHz

Steps taken prior to getting into this error.
vagrant init bento/ubuntu-16.04
vagrant up

**Comment by kmova** [comment]
After the vagrant init, open the Vagrantfile and try to set the gui=true. The instructions are in this link
https://www.vagrantup.com/docs/virtualbox/configuration.html

Once the gui is set to true, you can login to VirtualBox and see the VM console. It can help with identifying the reason for the above ssh connection issue.
