### ISSUE TITLE
feat(cStor): migrate the data from one pool to another pool seamlessly

### ISSUE THREAD

**Issue by mittachaitu** [openebs/openebs#3021]
##  Description

As an OpenEBS user, I should be able to migrate the data from one pool to another pool seamlessly(without much manual steps).

## Context

1. I have one SPC which consists of 3 cStor pools.
2. I added the new blockdevice which created the new cStor pool.

**Now to remove the existing disks/pool:**
1. I have to migrate all the volume replicas of the old pool to the new pool.
2. I have to remove the old pool & disk.

It is not at all feasible to perform manual migration of all the volume replicas from one pool to another(i.e more than 5 volume replicas in that pool).

## Possible Solution

- Making automation will make life easier.

**Comment by Perfect-Web** [comment]
indeed this is the case, a simple drain on the old cstor pool that would trigger creation of new cvr on the new pool would suffice.

**Comment by mittachaitu** [comment]
CVC operator exists to solve this issue to some extent by following [these](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/migration.md) steps but having automation around this will be a good idea
