### ISSUE TITLE
multiarch support for OpenEBS Docker official image

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#3023]
## Description
Support for Multi-architecture docker repository with "mutli-arch docker manifest" for OpenEBS images. 

## Context
OpenEBS Supports automated builds for amd64 and arm64. It will be good to make use of the "docker manifest" command to link different arch images into a single docker repository. This should allow kubernetes nodes to pull in the required container images.

**Comment by akhilerm** [comment]
Issue related to multiarch support for NDM has been raised [here](https://github.com/openebs/node-disk-manager/issues/379).

**Comment by Dhiraj240** [comment]
@kmova @akhilerm I would like to work on it during the community mentorship period.  Can you assign me a similar issue?

Also, may I know the common chat channel to discuss more?

**Comment by kmova** [comment]
Thanks @Dhiraj240 
You can reach us on slack channels or join one of the weekly hangouts. Details are here:
https://github.com/openebs/openebs/blob/master/community/README.md

**Comment by radicand** [comment]
Commenting from a Slack thread - for multiarch builds there are two approaches: one where the images are built separately for each platform and a manifest is created to "join" them together, and another method using `docker buildx` which takes care of everything for you automatically. If there are platform-specific tweaks and hacks where two separate Dockerfiles are a necessity, the former approach works well, but if the same Dockerfile can be used without issue, then the latter is often easier. `buildx` is experimental, but I've been using it for some time personally without any issues. From the thread:

- Manifest approach: https://www.docker.com/blog/multi-arch-all-the-things/
- Buildx approach: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
- Buildx example: `docker buildx build -f Dockerfile --platform linux/arm64/v8,linux/amd64 --progress plain --pull -t $IMAGE_TAG --push .`

**Comment by xUnholy** [comment]
I'm also happy to pick up this task as I've been involved heavily in making many popular tools multi-arch platform supported.

https://github.com/raspbernetes/multi-arch-images

Just point me to the correct repository I can work with and I can raise a PR.

**Comment by kmova** [comment]
That would be awesome @xUnholy!

Would you like to help with NDM ( https://github.com/openebs/node-disk-manager )

The builds are automated via travis: https://github.com/openebs/node-disk-manager/blob/master/.travis.yml

NDM pushes amd64, arm64 and ppc64le images. 

NDM also builds three container images: https://github.com/openebs/node-disk-manager/blob/master/Makefile#L119

Dockerfiles are under respective sub-directories here: https://github.com/openebs/node-disk-manager/tree/master/build

Feel free to suggest any improvements to the existing build files or refactor them as you see fit.

**Comment by Halytskyi** [comment]
> I just ran into this myself the other day after adding arm64 nodes to an existing amd64 cluster. The official openebs helm chart does not have an architecture node selector on any of the podSpecs, so it helpfully tried to run amd64 images on my new arm64 nodes.
> 
> It's also odd that some images currently have the architecture in the repository name for all platforms (quay.io/openebs/node-disk-operator-arm64 vs quay.io/openebs/node-disk-operator-amd64) while others assume amd64 as the default, and have only the architecture appended for arm64 (quay.io/openebs/m-apiserver vs quay.io/openebs/m-apiserver-arm64)

Have the similar issue described in https://github.com/openebs/openebs/issues/1295

**Comment by kmova** [comment]
@brandond - can you create a separate issue for:
> openebs helm chart does not have an architecture node selector

The helm chart can be fixed easily. 

We are in the process of getting the multi-arch support added in 1.11 release. Here is the initial PR from @xUnholy 
- https://github.com/openebs/node-disk-manager/pull/428

**Comment by dobegor** [comment]
@kmova is there any progress regarding ARM support?

**Comment by akhilerm** [comment]
@dobegor OpenEBS supports arm64. 
To deploy openebs on arm, the operator yaml is available [here](https://openebs.github.io/charts/openebs-operator-arm-dev.yaml)

The discussions regarding CI pipelines for arm platform are mentioned [here](https://github.com/openebs/openebs/issues/1295).

**Comment by dobegor** [comment]
@akhilerm thanks!

**Comment by akhilerm** [comment]
All the openebs components has multiarch images available now,

cc: @dobegor A separate operator.yaml file for different architecture wont be necessary now. You can use [this](https://openebs.github.io/charts/openebs-operator.yaml)

@brandond You can use the offical openebs helm charts available [here](https://openebs.github.io/charts/). Since the images specified in the charts are multiarch, you wont need to specify an arch specific node selector.

**Comment by akhilerm** [comment]
Closing the issue as multiarch images for openebs components are available now and all operator and helm charts are also migrated to use multiarch images.
