### ISSUE TITLE
Openebs with SAN storage, how best?

### ISSUE THREAD

**Issue by StefanSa** [openebs/openebs#3026]
Hi there,
we currently have three bare metal Server with FC and one SAN storage in operation.
Pacemaker Cluster with GFS2 is in operation on the SAN storage.
Several ELK nodes now use this construct.
We now want to migrate the ELK stack to kubernetes and continue to use the SAN storage.
Now my question about it:
How can OpenEBS help us to successfully use SAN storage in kubernetes?

Thanks for any help.

**Comment by kmova** [comment]
Hi @StefanSa,

Assuming you want to continue to use the Baremetal server and the SAN storage for the new Kubernetes cluster, one possible option is as follows:
- Create SAN volumes and connect with the Bare Metal servers. 
- Create a Kubernetes cluster with the bare metal servers. 
- Install OpenEBS
- You will notice that the SAN volumes that you have attached to Baremetal servers are shown as Kubernetes Block Devices. 
- You can then install the ELK stack making use of the `openebs-device` storage class. 

There are further customizations that could be done and so forth. The OpenEBS community can help with come up with additional best practices and support as you go through this setup. You can join the OpenEBS slack channels at: https://github.com/openebs/openebs/tree/master/community#contact

**Comment by StefanSa** [comment]
Hi @kmova 
thanks for the professional support here.
Murat has already been able to help me on the slack channel.

**Comment by Alceatraz** [comment]
> Hi @StefanSa,
> 
> Assuming you want to continue to use the Baremetal server and the SAN storage for the new Kubernetes cluster, one possible option is as follows:
> 
> * Create SAN volumes and connect with the Bare Metal servers.
> * Create a Kubernetes cluster with the bare metal servers.
> * Install OpenEBS
> * You will notice that the SAN volumes that you have attached to Baremetal servers are shown as Kubernetes Block Devices.
> * You can then install the ELK stack making use of the `openebs-device` storage class.
> 
> There are further customizations that could be done and so forth. The OpenEBS community can help with come up with additional best practices and support as you go through this setup. You can join the OpenEBS slack channels at: https://github.com/openebs/openebs/tree/master/community#contact

Hi, And I try follow those steps but I ran into some issue:

I config the iSCSI server and make sure k8s-master server connect the iscsi, Now I can mount it.

```shell
lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0 1000G  0 disk 
├─sda1   8:1    0    1G  0 part /boot/efi
├─sda2   8:2    0    1G  0 part /boot
└─sda3   8:3    0  998G  0 part /
sdb      8:16   0    2T  0 disk 
└─sdb1   8:17   0    2T  0 part

iscsiadm -m session -o show
tcp: [1] 10.188.180.249:3260,1 iqn.2003-01.org.linux-iscsi.storage.x8664:sn.2a6fc1fc0798 (non-flash)
```

But 
```shell
kubectl get bd --all-namespaces
No resources found
```

There is no SAN block device automatic show in kubectl bd, What did I missed ?

I'm using k8s 1.22.4 and openebs 3.0.0 by guide `kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml`

**Comment by shivpathakvw** [comment]
I need one help @kmova . I am getting VMs on baremetal nodes where san devices are connected. On the vms I need to create the k8s cluster . How VM will see the san device ? Again some virtual disk or Same san disk directly. 

One baremetal can have multiple vms as week how san storage LUN will be attached there . I will be Using openebs only as CSI 

Appreciate your guidance

**Comment by tiagolobocastro** [comment]
If you attach the disk to the VMs running OpenEBS then it will just see the raw block device and use it, just as if it were a local attached.
