### ISSUE TITLE
NDM Error Reporting: show reason for not allocating available BD

### ISSUE THREAD

**Issue by briankmatheson** [openebs/openebs#3039]
## Description

reporting on error conditions / error states should bubble up to the 'describe' event logs.  Ideally we'd have a list of error conditions like

- disk not found
- disk is partitioned
- disk is mounted
- disk is "claimed" by ndm for "PVC"
- unknown failure
etc.

...such that we can document the complete list of error conditions.

## Context

Especially when experimenting with different storage engines, reorganizing disks is difficult because of a lack of visibility into the orchestration process.

To get a cluster into this state, I:

1. connected to director online
2. installed openebs from director
3. created a cstor pool
4. deleted the cstor pool
5. manually tagged some BDs to use for openebs-device
6. tweaked the openebs-device sc to use the tags
7. tried to get any kind of bound pvc

## Screenshots

I0518 07:52:16.532457       1 provisioner_blockdevice.go:53] Initialize volume pvc-40ab92cd-98da-11ea-8654-063c1c64a66a failed: unable to find BD: for BDC:bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a associated with PV:pvc-40ab92cd-98da-11ea-8654-063c1c64a66a
2020-05-18T07:52:16.532Z	ERROR	app/provisioner_blockdevice.go:54		{"eventcode": "local.pv.provision.failure", "msg": "Failed to provision Local PV", "rname": "pvc-40ab92cd-98da-11ea-8654-063c1c64a66a", "reason": "Block device initialization failed", "storagetype": "device"}
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).ProvisionBlockDevice
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner_blockdevice.go:54
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).Provision
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner.go:129
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).provisionClaimOperation
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1290
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaim
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1026
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncClaimHandler
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:976
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem.func1
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:884
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextClaimWorkItem
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:905
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).runClaimWorker
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:858
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.Until
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
W0518 07:52:16.532614       1 controller.go:889] Retrying syncing claim "40ab92cd-98da-11ea-8654-063c1c64a66a" because failures 6 < threshold 15
E0518 07:52:16.532659       1 controller.go:908] error syncing claim "40ab92cd-98da-11ea-8654-063c1c64a66a": failed to provision volume with StorageClass "openebs-device": unable to find BD: for BDC:bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a associated with PV:pvc-40ab92cd-98da-11ea-8654-063c1c64a66a
I0518 07:52:16.533121       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"workstation-disk", UID:"40ab92cd-98da-11ea-8654-063c1c64a66a", APIVersion:"v1", ResourceVersion:"631360", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "openebs-device": unable to find BD: for BDC:bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a associated with PV:pvc-40ab92cd-98da-11ea-8654-063c1c64a66a
￼
...

 unable to find BD: for BDC:bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a associated with PV:pvc-40ab92cd-98da-11ea-8654-063c1c64a66a

...

bmath@timesink:~/maya/kops/test220.bob.bmath.nyc$ kubectl describe pvc 
Name:          workstation-disk
Namespace:     default
StorageClass:  openebs-device
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
               volume.kubernetes.io/selected-node: ip-172-20-58-172.us-east-2.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    workstation-7cd6d9f68f-zsnkt
Events:
  Type     Reason                Age                   From                                                                                               Message
  ----     ------                ----                  ----                                                                                               -------
  Normal   WaitForFirstConsumer  24m (x2 over 24m)     persistentvolume-controller                                                                        waiting for first consumer to be created before binding
  Normal   Provisioning          9m27s (x7 over 24m)   openebs.io/local_openebs-localpv-provisioner-c6cdf9dbd-tw88m_ab65e8ad-9d3c-4fe7-af9d-35b9d9b1cecc  External provisioner is provisioning volume for claim "default/workstation-disk"
  Warning  ProvisioningFailed    8m27s (x7 over 23m)   openebs.io/local_openebs-localpv-provisioner-c6cdf9dbd-tw88m_ab65e8ad-9d3c-4fe7-af9d-35b9d9b1cecc  failed to provision volume with StorageClass "openebs-device": unable to find BD: for BDC:bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a associated with PV:pvc-40ab92cd-98da-11ea-8654-063c1c64a66a
  Normal   ExternalProvisioning  4m27s (x83 over 24m)  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "openebs.io/local" or manually created by system administrator

...

{"level":"error","ts":1589789561.58245,"logger":"controller_deviceclaim","msg":"Error selecting device","Request.Namespace":"openebs","Request.Name":"bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a","error":"no devices found matching the criteria","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdeviceclaim.(*ReconcileBlockDeviceClaim).claimDeviceForBlockDeviceClaim\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go:179\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdeviceclaim.(*ReconcileBlockDeviceClaim).Reconcile\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go:124\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
￼
...

bmath@timesink:~/maya/kops/test220.bob.bmath.nyc$ kubectl get bd -A
NAMESPACE   NAME                                           NODENAME                                      SIZE           CLAIMSTATE   STATUS     AGE
openebs     blockdevice-54b5e9810a2d5f6601ca2a38d491a15e   ip-172-20-58-172.us-east-2.compute.internal   950000000000   Claimed      Active     2d
openebs     blockdevice-732ae786fb22fb7cd90813fc35bff3d3   ip-172-20-37-2.us-east-2.compute.internal     21474836480    Unclaimed    Active     2d
openebs     blockdevice-7ac8d2b9be37d7c3fa58e6aa41d2346a   ip-172-20-58-172.us-east-2.compute.internal   1073741824     Unclaimed    Inactive   47h
openebs     blockdevice-9c7c200b2f35a3e6c58b8c846f37c836   ip-172-20-52-39.us-east-2.compute.internal    950000000000   Claimed      Active     2d
openebs     blockdevice-aab6116beb36ca7d1c15f7ff38985d96   ip-172-20-54-76.us-east-2.compute.internal    950000000000   Claimed      Active     2d
openebs     blockdevice-c3a8e37971c48ccec065e8d06ce55d3f   ip-172-20-37-2.us-east-2.compute.internal     21474836480    Unclaimed    Active     2d
openebs     blockdevice-e2b817a7efa20692f6f17f42f6aaa9f5   ip-172-20-58-172.us-east-2.compute.internal   1073741824     Unclaimed    Inactive   47h
openebs     blockdevice-f08650cf430f8eda0345b7ac091d1841   ip-172-20-51-185.us-east-2.compute.internal   950000000000   Claimed      Active     2d
bmath@timesink:~/maya/kops/test220.bob.bmath.nyc$ kubectl get bdc -A
NAMESPACE   NAME                                           BLOCKDEVICENAME   PHASE     AGE
openebs     bdc-pvc-40ab92cd-98da-11ea-8654-063c1c64a66a                     Pending   39m
￼

**Comment by briankmatheson** [comment]
BTW, to successfully get out of this error condition, I did the following:

delete all the pvcs
delete all the bdcs
delete all the bds
wipefs all of the nvme drives
restart (delete all) ndm daemonset

Now it seems good.

**Comment by akhilerm** [comment]
Events are now added to BlockDevice and BlockDeviceClaim resources to show errors during claiming. 
Fixed in [#425](https://github.com/openebs/node-disk-manager/pull/425)
