### ISSUE TITLE
Refactor OpenEBS projects to use go-module

### ISSUE THREAD

**Issue by vaniisgh** [openebs/openebs#3040]
## Description
Go has included support for versioned modules and users are encouraged to migrate to modules from other dependency management systems. It is a relatively easier system for package management and would be nice to have. 

## Context
Here is the [wiki](https://github.com/golang/go/wiki/Modules) with the details on Go Modules 
an official go [blog post](https://blog.golang.org/migrating-to-go-modules)
and a [simple medium article](https://medium.com/@adiach3nko/package-management-with-go-modules-the-pragmatic-guide-c831b4eaaf31) to understand a bit better.

**Comment by kmova** [comment]
The following projects need help with refactoring to use go modules. 
- https://github.com/openebs/zfs-localpv
- https://github.com/openebs/node-disk-manager
- https://github.com/openebs/maya

Some of the projects that have already been refactored are: 
- https://github.com/openebs/cstor-operators
- https://github.com/openebs/velero-plugin
- https://github.com/openebs/cstor-csi
- https://github.com/openebs/upgrade
- https://github.com/openebs/jiva-operator
- https://github.com/openebs/jiva-csi
- https://github.com/openebs/jiva
- https://github.com/openebs/api

**Comment by vaniisgh** [comment]
Can we mark this a good first issue & can I try to resolve this on the Maya repository :)

**Comment by vaniisgh** [comment]
I think we can close this issue ?

**Comment by kmova** [comment]
yes! Thank you @vaniisgh
