### ISSUE TITLE
 Add detailed documentation on building mayactl

### ISSUE THREAD

**Issue by vaniisgh** [openebs/openebs#3041]
## Description
It would be nice to have all information regarding building and testing mayactl under the same header in possibly in the [developers guide](https://github.com/openebs/maya/blob/master/docs/developer.md).

- It would be nice to have subsections in the documentation on mayactl, the control plane elements, and sidecars separately.
- This would make it clear that mayactl can be built and tested standalone as well as with the rest of the elements

## Context

First-time contributors/users of OpenEBS would benefit from a more comprehensive guide on how to build and test Maya and it's components. A more detailed guide and defined test case in the same should encourage uniform standards and make things simpler for newbies or anyone interested and browsing the docs.

**Comment by prateekpandey14** [comment]
docs has been added in PR https://github.com/openebs/openebsctl/pull/9
