### ISSUE TITLE
Modify the styling of our readthedocs theme

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#305]
Random starting points
- https://docs.readthedocs.io/en/latest/
So orange is indeed our favourite colour :+1: 
Suggest some other stylistic changes additions to the docs.

**Comment by vharsh** [comment]
Similar resources
- http://www.mkdocs.org/user-guide/styling-your-docs/

**Comment by kmova** [comment]
Moved to docusaurus. https://github.com/openebs/openebs-docs
