### ISSUE TITLE
Status for BD changes periodically

### ISSUE THREAD

**Issue by wanfuuyu** [openebs/openebs#3051]
## Description

Feature GPTBasedUUID: Enabled

Status for BD changes from active to inactive while a disk has no partitions but with a partitionTable after ndm restart

## Expected Behavior

Nothing

## Current Behavior

Status for other BlockDevices changes between active and  inactive  periodically

## Steps to Reproduce

1. Attach Two disk(sda, sdb) into Ubuntu(VM) and then we  got two Active BlockDevices bdA,bdB
2. Use fdisk tool to delete the Partition auto created by NDM for sda, and then the bdA turns into inactive
3. delete the ndm pod and wait for a new pod creating
4. createSinglePartition for sda failed, status for dbB jumps from active to inactive time to time

## Screenshots

![2020-06-02 11 31 07](https://user-images.githubusercontent.com/8027958/83476972-a19a2300-a4c4-11ea-8e8c-56df2f307a74.gif)

## Your Environment

* OS (ubuntu 18.04.1 LTS):
* VMTool (Parallels Desktop)
* Kernel (4.15.0-101-generic):
* kubernetes (1.18.3)
* NodeDiskManager(quay.io/openebs/node-disk-manager-amd64:0.5.0)

**Comment by akhilerm** [comment]
NDM autocreate partitions on the disk, if it is unable to identify the disk uniquely. Therefore, in your case bdA, will be actually pointing to `/dev/sda1`. When the partition is deleted, bdA will become inactive.

Can you get the logs of the NDM pod ? 

Also, a question: why was the partition created by NDM for sda deleted?

**Comment by wanfuuyu** [comment]
[node-disk-manager.log](https://github.com/openebs/openebs/files/4714905/node-disk-manager.log)
```code
sdb      8:16   0    10G  0 disk 
├─sdb1   8:17   0 953.7M  0 part 
└─sdb2   8:18   0   8.4G  0 part 
sdc      8:32   0     2G  0 disk 
├─sdc1   8:33   0     1G  0 part 
└─sdc2   8:34   0  1023M  0 part 
sdd      8:48   0     5G  0 disk
```
emmm,, sdd is kind like sda metioned above, and I just delete sdd1 manually。。。

**Comment by akhilerm** [comment]
`sdd1` was created by NDM, to uniquely identify the disk. If you delete the partition, the GPT partition table still exists and further NDM won't be able to create partitions
```
E0602 05:15:27.875329       6 partition.go:127] disk /dev/sdd already contains a known partition table
E0602 05:15:27.875345       6 partition.go:128] partitioning will be aborted
```
This error shows the above case I mentioned.

Why was the partition manually deleted on `sdd`?

**Comment by wanfuuyu** [comment]
I have no questions about sdd issue, but what happend to other BlockDevices actual confused me..There shouldn't be a status changing.

**Comment by akhilerm** [comment]
yes, can you share the logs of the NDM daemonset pod from the node where `state` was changing?

**Comment by wanfuuyu** [comment]
`device(/dev/sdc1) is a partition, using partition UUID: 13748513-01` shows in  [logs](https://github.com/openebs/openebs/files/4714905/node-disk-manager.log) again and again in quite short duration

Probably it's because of the `rescan`  from the `udevProbe` when  `addBlockDevice` for `sdd` failed

**Comment by akhilerm** [comment]
> Probably it's because of the rescan from the udevProbe when addBlockDevice for sdd failed

Yes, everytime a rescan is performed, initially the state of all BlockDevices is marked as `Inactive`, and then they are marked as `Active` in the order in which they appear. 

Now that we have found the root cause, we need to know why the partition creation failed on sdd.

**Comment by wanfuuyu** [comment]
As mentioned above, an existing partition table makes `CreateSinglePartition` failed.

So delete the partitions created by NDM manually can be a unrecoverable disaster for NDM ? ?

**Comment by akhilerm** [comment]
> So deleting the partitions created by NDM manually can be a unrecoverable disaster for NDM ? ?

If you delete the partition and wipe the disk, then it won't be an issue, because the partition table labels also gets removed while wiping. Thus NDM will be able to create another partition on the disk. 

But if partition table exists, but without any partitions on the disk, NDM will continously error out.

**Comment by akhilerm** [comment]
@wanfuuyu Are there any updates on this issue? Were you able to resolve it?

**Comment by akhilerm** [comment]
@wanfuuyu We have now made the new GPT based UUID method default starting from openebs 2.0.

**Comment by prabhatkumarthakur** [comment]
@akhilerm  In case I am having 10 disks and only 1 disk is having a partition then the rest 9 disks should be detected and shown by ndm.
Currently if in a node 1 partition disk is present logs are getting flooded about that partitioned disk and the rest of the unused disks are not detected by ndm.

**Comment by Spiegie** [comment]
We had the issue, that rancher mounted a CD-Drive. 
Openebs had trouble scanning this device and rescanned everything.
I hope, this hint can help someone else.
