### ISSUE TITLE
OpenEBS is unable to delete SPC, SCP, SP, BlockDevice

### ISSUE THREAD

**Issue by KhoaNPA** [openebs/openebs#3056]
## Description
I created EKS with Terraform.
I mounted some EBS to some EC2 instances, then use Terraform to increase the number of nodes (old EC2 instances were terminated and new EC2 instances were added to the EKS cluster ,then I also enabled iSCSI client manually on nodes). So, previous EBS were unattached, but theirs BlockDevices still existed with Status **Active**.

I try to remove above BlockDevices by running `kubectl delete blockdevice blockdevice-xxxx -n openebs`. It said **blockdevice-xxxx is deleted** but it still there, nothing is deleted.

I do the same with other resources such as `kubectl delete spc,csp,sp --all`, it returns the same issue above.

However, when now I attach new EBSs, create new SPC with new BlockDevice, these new resources are removable.

## Expected Behavior
Successfully delete SPC, SCP, SP, BlockDevice

## Current Behavior
Command returns **DELETED** but nothing is deleted.

## Steps to Reproduce
`kubectl delete spc,csp,sp --all`
`kubectl delete blockdevice-xxxx`

## Your Environment
* `kubectl get nodes`:
```
NAME                                             STATUS   ROLES    AGE     VERSION
ip-20-0-14-59.ap-southeast-1.compute.internal    Ready    <none>   3h57m   v1.16.8-eks-e16311
ip-20-0-149-11.ap-southeast-1.compute.internal   Ready    <none>   3h57m   v1.16.8-eks-e16311
ip-20-0-169-47.ap-southeast-1.compute.internal   Ready    <none>   3h57m   v1.16.8-eks-e16311
ip-20-0-56-8.ap-southeast-1.compute.internal     Ready    <none>   3h57m   v1.16.8-eks-e16311
ip-20-0-70-254.ap-southeast-1.compute.internal   Ready    <none>   3h57m   v1.16.8-eks-e16311

```
* `kubectl get pods -n openebs`:
```
NAME                                           READY   STATUS    RESTARTS   AGE
openebs-admission-server-797469bcc9-7vsvc      1/1     Running   0          4h10m
openebs-apiserver-758db4cd67-qzpd9             1/1     Running   0          4h10m
openebs-localpv-provisioner-76f6d475cc-z4x8g   1/1     Running   0          4h10m
openebs-ndm-hkcwd                              1/1     Running   0          4h10m
openebs-ndm-kj6zt                              1/1     Running   0          4h10m
openebs-ndm-operator-665fb54cc7-qbhpg          1/1     Running   0          4h10m
openebs-ndm-pqwjt                              1/1     Running   0          4h11m
openebs-ndm-wfc7n                              1/1     Running   0          4h11m
openebs-ndm-znnsn                              1/1     Running   0          4h11m
openebs-provisioner-5759bd48d8-9swp2           1/1     Running   0          4h10m
openebs-snapshot-operator-6645579f6c-rlwk4     2/2     Running   0          4h10m
```

* `kubectl get services`:
```
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
admission-server-svc   ClusterIP   10.100.166.117   <none>        443/TCP    3d22h
openebs-apiservice     ClusterIP   10.100.188.216   <none>        5656/TCP   3d22h
```

* `kubectl get sc`:
```
NAME                        PROVISIONER                                                AGE
gp2 (default)               kubernetes.io/aws-ebs                                      28d
openebs-device              openebs.io/local                                           29h
openebs-hostpath            openebs.io/local                                           29h
openebs-jiva-default        openebs.io/provisioner-iscsi                               29h
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   29h

```
* `kubectl get pv`:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS   REASON   AGE
pvc-39311b0f-3356-4171-b9a2-85239417a550   8Gi        RWO            Delete           Bound    keycloak/data-keycloak-postgresql-0   gp2                     25d
pvc-912682d1-a8d9-427f-a18d-4386c9e36e39   10Gi       RWO            Delete           Bound    monitoring/grafana                    gp2                     25d

```
* `kubectl get pvc`:
```
NAMESPACE    NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
keycloak     data-keycloak-postgresql-0   Bound    pvc-39311b0f-3356-4171-b9a2-85239417a550   8Gi        RWO            gp2            25d
monitoring   grafana                      Bound    pvc-912682d1-a8d9-427f-a18d-4386c9e36e39   10Gi       RWO            gp2            25d
```

* Install tools:
Helm v3
* Others:
EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.16.8, docker:18.09.9ce-2.amzn2)
Above Grafana, Keycloak were installed by Helm, They existed before installing OpenEBS

**Comment by boxofcrates** [comment]
@KhoaNPA take a look at the `openebs-ndm-operator` logs. I had a similar issue: I don't think your issue is the same (I did not have an issue deleting any CRs other than `blockdevice`s), but wanted to point you to those logs.

OpenEBS installed via Helm. Block device manually created (with `ndm.io/managed: "false"`). Deleting the `blockdevice` CR with kubectl reported success, but the block device remained (or immediately remained). Did not have an issue with deleting blockdevices automatically discovered by NDM (after updating e.g., `vendor-filter` to stop NDM recreating the device).

NDM operator logs had `Error while cleaning blockdevice-ssd-2: Node "" not found` and indeed I had not specified `node.nodeName` on the `blockdevice`. A quick `kubectl edit` to add that and another `delete` successfully deleted the device.

**Comment by survivant** [comment]
I have a similar issue.  I'm not able to remove few ressources

```
root@test-pcl109:~# kubectl get spc,csp
NAME                                          AGE
storagepoolclaim.openebs.io/cstor-disk-pool   3h31m

NAME                                        ALLOCATED   FREE   CAPACITY   STATUS               READONLY   TYPE      AGE
cstorpool.openebs.io/cstor-disk-pool-8txr                                 PoolCreationFailed   false      striped   3h31m
cstorpool.openebs.io/cstor-disk-pool-vkk4                                 PoolCreationFailed   false      striped   3h31m
cstorpool.openebs.io/cstor-disk-pool-xum2                                 PoolCreationFailed   false      striped   3h31m
root@test-pcl109:~#

```

they won't die.  I'm waiting for hours and nothing change.

```
root@test-pcl109:~/test-openebs# kubectl delete spc,csp --all
storagepoolclaim.openebs.io "cstor-disk-pool" deleted
cstorpool.openebs.io "cstor-disk-pool-8txr" deleted
cstorpool.openebs.io "cstor-disk-pool-vkk4" deleted
cstorpool.openebs.io "cstor-disk-pool-xum2" deleted

```

**Comment by geeksterio** [comment]
I'm having the same issue:
`kubectl delete spc,csp --all
storagepoolclaim.openebs.io "cstor-disk-pool" deleted
storagepoolclaim.openebs.io "cstor-sparse-pool" deleted
cstorpool.openebs.io "cstor-disk-pool-fhj0" deleted
`
I've uninstalled the helm chart and i'm stuck with the spc, csp, bd, bdc..
Any recommendation ?
I uninstalled the

**Comment by survivant** [comment]
I created a guide
https://github.com/openebs/openebs-docs/issues/900

tell us if it works

**Comment by geeksterio** [comment]
@survivant it works. thank you very much!
