### ISSUE TITLE
Can claim more disk than the device block can support

### ISSUE THREAD

**Issue by kaitaklam** [openebs/openebs#3067]
## Description
created 6 disks on 2 worker-nodes (3 per worker-node) and let NDM to discover.
 each disk has 1 GB, so in total disksize: 6 GB
created StoragePoolClass cstor-raidz-pool using the 6 disks
created StorageClass openebs-sc-statefulset using the StoragePoolclass Cstor-raidz-pool
created a PersistenVolumeClaim cstor-pvc-mysql-large and request 60Gi

## Expected Behavior
I expect it would fail as the total blockdevice size is max 6 Gi

## Current Behavior
The PersistenVolumeClaim is successful.
I have created a pod to mount the PersistenVolumeClaim cstor-pvc-mysql-large.
On the PersistentVolume mounted directory, I was able to allocate indeed nearly 60 GB.

## Steps to Reproduce
# kubectl get bd -A | grep "Claimed"
kube-system   blockdevice-18ffdb266179601bb6169c147ea80d8a   k8s-worker-0   1073741824    Claimed      Active     20h
kube-system   blockdevice-2c0cb264995905286a290b999db1c8c5   k8s-worker-1   1073741824    Claimed      Active     21h
kube-system   blockdevice-8c8f6eeb1755b9850b63cd54edfed938   k8s-worker-0   1073741824    Claimed      Active     21h
kube-system   blockdevice-94c831b96381c660de4273f09470971d   k8s-worker-1   1073741824    Claimed      Active     21h
kube-system   blockdevice-94ec16a3253cccd0da373a0ff2fba4b3   k8s-worker-1   1073741824    Claimed      Active     21h
kube-system   blockdevice-ba7d9de981f34c9b730cadcef423bb06   k8s-worker-0   1073741824    Claimed      Active     21h

 kubectl get spc  cstor-raidz-pool -o ymal
error: unable to match a printer suitable for the output format "ymal", allowed formats are: custom-columns,custom-columns-file,go-template,go-template-file,json,jsonpath,jsonpath-file,name,template,templatefile,wide,yaml
dtag7-dm-xms-mgt-node-000 openebs# kubectl get spc  cstor-raidz-pool -o yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openebs.io/v1alpha1","kind":"StoragePoolClaim","metadata":{"annotations":{"cas.openebs.io/config":"- name: PoolResourceRequests\n  value: |-\n      memory: 2Gi\n- name: PoolResourceLimits\n  value: |-\n      memory: 4Gi\n"},"name":"cstor-raidz-pool"},"spec":{"blockDevices":{"blockDeviceList":["blockdevice-18ffdb266179601bb6169c147ea80d8a","blockdevice-2c0cb264995905286a290b999db1c8c5","blockdevice-8c8f6eeb1755b9850b63cd54edfed938","blockdevice-94c831b96381c660de4273f09470971d","blockdevice-94ec16a3253cccd0da373a0ff2fba4b3","blockdevice-ba7d9de981f34c9b730cadcef423bb06"]},"name":"cstor-raidz-pool","poolSpec":{"poolType":"raidz"},"type":"disk"}}
    openebs.io/spc-lease: '{"holder":"","leaderTransition":2}'
  creationTimestamp: "2020-06-22T10:24:56Z"
  finalizers:
  - storagepoolclaim.openebs.io/finalizer
  generation: 4
  name: cstor-raidz-pool
  resourceVersion: "3313745"
  selfLink: /apis/openebs.io/v1alpha1/storagepoolclaims/cstor-raidz-pool
  uid: 4920b83b-6bb9-4c09-a10b-600d90233a07
spec:
  blockDevices:
    blockDeviceList:
    - blockdevice-18ffdb266179601bb6169c147ea80d8a
    - blockdevice-2c0cb264995905286a290b999db1c8c5
    - blockdevice-8c8f6eeb1755b9850b63cd54edfed938
    - blockdevice-94c831b96381c660de4273f09470971d
    - blockdevice-94ec16a3253cccd0da373a0ff2fba4b3
    - blockdevice-ba7d9de981f34c9b730cadcef423bb06
  maxPools: null
  minPools: 0
  name: cstor-raidz-pool
  poolSpec:
    cacheFile: ""
    overProvisioning: false
    poolType: raidz
    roThresholdLimit: 0
    thickProvisioning: false
  type: disk
status:
  phase: Online
versionDetails:
  autoUpgrade: false
  desired: 1.9.0
  status:
    current: 1.9.0
    dependentsUpgraded: true
    lastUpdateTime: null
    state: ""

# kubectl get sc openebs-sc-statefulset -o yaml
allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-raidz-pool"
      - name: ReplicaCount
        value: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":false,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"cas.openebs.io/config":"- name: StoragePoolClaim\n  value: \"cstor-raidz-pool\"\n- name: ReplicaCount\n  value: \"2\"\n","openebs.io/cas-type":"cstor"},"name":"openebs-sc-statefulset"},"provisioner":"openebs.io/provisioner-iscsi"}
    openebs.io/cas-type: cstor
  creationTimestamp: "2020-06-22T10:26:48Z"
  name: openebs-sc-statefulset
  resourceVersion: "3384299"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/openebs-sc-statefulset
  uid: 8d653c66-d758-4beb-8ad4-9e71aa258969
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate

# kubectl get pvc cstor-pvc-mysql-large -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cstor-pvc-mysql-large","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"60Gi"}},"storageClassName":"openebs-sc-statefulset"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
  creationTimestamp: "2020-06-22T10:35:48Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: cstor-pvc-mysql-large
  namespace: default
  resourceVersion: "3317072"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/cstor-pvc-mysql-large
  uid: 12f124be-95ac-48ac-b4a6-e75802b9452b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: openebs-sc-statefulset
  volumeMode: Filesystem
  volumeName: pvc-12f124be-95ac-48ac-b4a6-e75802b9452b
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 60Gi
  phase: Bound

 kubectl get pod -o yaml busybox
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 172.16.1.82/32
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.16.1.82"
          ],
          "default": true,
          "dns": {}
      }]
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"busybox","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","date \u003e /mnt/store1/date.txt; hostname \u003e\u003e /mnt/store1/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;"],"image":"192.168.21.38:5000/busybox","imagePullPolicy":"Always","name":"busybox","volumeMounts":[{"mountPath":"/mnt/store1","name":"demo-vol1"}]}],"volumes":[{"name":"demo-vol1","persistentVolumeClaim":{"claimName":"cstor-pvc-mysql-large"}}]}}
  creationTimestamp: "2020-06-22T10:40:06Z"
  name: busybox
  namespace: default
  resourceVersion: "3318349"
  selfLink: /api/v1/namespaces/default/pods/busybox
  uid: 24264b77-91b3-414b-873c-66b555aa6f6f
spec:
  containers:
  - command:
    - sh
    - -c
    - date > /mnt/store1/date.txt; hostname >> /mnt/store1/hostname.txt; sync; sleep
      5; sync; tail -f /dev/null;
    image: 192.168.21.38:5000/busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/store1
      name: demo-vol1
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-65hbz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker-1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: cstor-pvc-mysql-large
  - name: default-token-65hbz
    secret:
      defaultMode: 420
      secretName: default-token-65hbz
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-06-22T10:40:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-06-22T10:40:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-06-22T10:40:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-06-22T10:40:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d271402795747adbe6ff77787ddd0908312aabf7bb78ed4180e9580a5021057c
    image: 192.168.21.38:5000/busybox:latest
    imageID: 192.168.21.38:5000/busybox@sha256:f85f18ab1af8469c9faef7c72899eaddc8648f6b15bc67cd20f0020f4cb2431f
    lastState: {}
    name: busybox
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-06-22T10:40:14Z"
  hostIP: 192.168.21.236
  phase: Running
  podIP: 172.16.1.82
  podIPs:
  - ip: 172.16.1.82
  qosClass: BestEffort
  startTime: "2020-06-22T10:40:06Z"

dtag7-dm-xms-mgt-node-000 openebs# kubectl exec -it busybox -- sh
/ # du -sh /mnt/store1/
58.9G   /mnt/store1/
/ # ls-l  /mnt/store1/
sh: ls-l: not found
/ # ls -l  /mnt/store1/
total 61726500
-rw-r--r--    1 root     root            29 Jun 22 10:40 date.txt
-rw-r--r--    1 root     root     63207903232 Jun 22 11:38 gentoo_root.img
-rw-r--r--    1 root     root            16 Jun 22 10:40 hostname.txt
drwx------    2 root     root         16384 Jun 22 10:36 lost+found

## Your Environment

# kubectl get nodes
NAME           STATUS   ROLES    AGE   VERSION
k8s-master-0   Ready    master   10d   v1.17.3
k8s-worker-0   Ready    <none>   10d   v1.17.3
k8s-worker-1   Ready    <none>   10d   v1.17.3

# kubectl get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  10d
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  10d
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  10d
openebs-sc-statefulset      openebs.io/provisioner-iscsi                               Delete          Immediate              false                  20h
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  10d
openebs-standalone          openebs.io/provisioner-iscsi                               Delete          Immediate              false                  10d
openebs-standard            openebs.io/provisioner-iscsi                               Delete          Immediate              false                  10d

# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                            STORAGECLASS             REASON   AGE
pvc-12f124be-95ac-48ac-b4a6-e75802b9452b   60Gi       RWO            Delete           Bound    default/cstor-pvc-mysql-large    openebs-sc-statefulset            20h
pvc-bd39bef6-f7d5-44e5-9567-b9bdff7e2b68   60Gi       RWO            Delete           Bound    default/cstor-pvc-mysql1-large   openebs-sc-statefulset            16h

# kubectl get pvc
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
cstor-pvc-mysql-large    Bound    pvc-12f124be-95ac-48ac-b4a6-e75802b9452b   60Gi       RWO            openebs-sc-statefulset   20h
cstor-pvc-mysql1-large   Bound    pvc-bd39bef6-f7d5-44e5-9567-b9bdff7e2b68   60Gi       RWO            openebs-sc-statefulset   16h
dtag7-dm-xms-mgt-node-000 openebs# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
# uname -a
Linux .......  3.10.0-1062.7.1.el7.x86_64 #1 SMP Wed Nov 13 08:44:42 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mittachaitu** [comment]
Hi @kaitaklam, By default, cStor operates on the concept of **thin provisioning**(We can claim more than what we have and it will mark applications volume as Read-Only once existing space is exhausted).

If you want to error out if requested claim storage is greater than existing storage(thick provisioing) then we have to set **thickProvisiong** field to **true** in spec of SPC 
```sh
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  ...
  ...
  ...
  name: cstor-sparse-pool
spec:
   ...
   ...
   ...
  poolSpec:
    cacheFile: /tmp/pool1.cache
    poolType: striped
    roThresholdLimit: 0
    thickProvisioning: false
  type: sparse
```
In the above output of we need to set **thickProvisioning** as **true**.

**Comment by kaitaklam** [comment]
Okay that works, thanks

**Comment by kaitaklam** [comment]
problem fixed thickProvisiong field to true

**Comment by kaitaklam** [comment]
Hi,

I have configured tickProvisionig: true and poolType: raidz.

I have 3 worker nodes, with each worker nodes 3 x 1G disk: 3 nodes x 3 disks x 1G = 9 G
The question that I want to answer is, what is the net disk available for the user?

The test-result:

  *   I can create a pvc up to 1.9 GB (more than 1.95 GB, openEBS gives error).
  *   But I am able to create 8 pvcs with 1.95 GB: 8 x 1.95 = 15.6 G, but I have only 9 G physical disk



# kubectl get pvc
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
cstor-pvc-mysql-large    Bound    pvc-1bdce479-17fb-48ac-9ae2-56c3bc868e64   1950Mi     RWO            openebs-cstor-sc   4m18s
cstor-pvc-mysql-large1   Bound    pvc-bdeb78c5-f834-46b7-be28-0d8ba023ffad   1950Mi     RWO            openebs-cstor-sc   4m4s
cstor-pvc-mysql-large2   Bound    pvc-6667a176-c33c-4e11-97d8-53f3dd00100b   1950Mi     RWO            openebs-cstor-sc   3m21s
cstor-pvc-mysql-large3   Bound    pvc-26aabf75-a4b4-4611-bc2d-86ddd640055c   1950Mi     RWO            openebs-cstor-sc   2m59s
cstor-pvc-mysql-large4   Bound    pvc-84f89529-fb7f-4d62-a17b-6b69e6129d6b   1950Mi     RWO            openebs-cstor-sc   2m33s
cstor-pvc-mysql-large5   Bound    pvc-0a024c2c-8924-4eb2-875a-dc6ec0f0b071   1950Mi     RWO            openebs-cstor-sc   2m8s
cstor-pvc-mysql-large6   Bound    pvc-581f5c8e-5493-4ee9-a5b8-8f9a747d1c9d   1950Mi     RWO            openebs-cstor-sc   90s
cstor-pvc-mysql-large7   Bound    pvc-b25bd863-dd7d-4d59-9e97-24c9d6a361f3   1950Mi     RWO            openebs-cstor-sc   6s

# kubectl get csp
NAME                    ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE    AGE
cstor-raidz-pool-iuy0   3.24M       2.95G   2.95G      Healthy   false      raidz   4m48s
cstor-raidz-pool-s1hk   3.24M       2.95G   2.95G      Healthy   false      raidz   4m48s
cstor-raidz-pool-yo22   3.35M       2.95G   2.95G      Healthy   false      raidz   4m49s

#  kubectl get bd -A
NAMESPACE     NAME                                           NODENAME       SIZE          CLAIMSTATE   STATUS   AGE
kube-system   blockdevice-21f0a80c8ac4319bcb33d5b5f0c28c2d   k8s-worker-0   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-3036a92092f6669e43d8a1d47a228c22   k8s-worker-2   1073741824    Claimed      Active   4d19h
kube-system   blockdevice-39f43a65cc1bb7de0e3bdbd8c2a30238   k8s-worker-2   1073741824    Claimed      Active   4d19h
kube-system   blockdevice-4b6215923c81883ff5b2eba02d411ff0   k8s-worker-1   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-4bdbdd33de7790189c08e83381518a20   k8s-worker-0   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-84cd05e0a5b74db0a0bf8703c7a4c83b   k8s-worker-1   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-94ec16a3253cccd0da373a0ff2fba4b3   k8s-worker-1   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-a51689191ae43ca219067deed3a5549d   k8s-worker-0   1073741824    Claimed      Active   5d1h
kube-system   blockdevice-faef7c0501d641b8dbe09f1ee8474831   k8s-worker-2   1073741824    Claimed      Active   4d19h
kube-system   sparse-2aae5c1ae32e2f533e072ffc87ed7b5c        k8s-worker-2   10737418240   Unclaimed    Active   4d19h
kube-system   sparse-aa73ef381020b82f33a01f40571d046d        k8s-worker-0   10737418240   Unclaimed    Active   5d1h
kube-system   sparse-ecaf82cb369be323ada118141ff21ff3        k8s-worker-1   10737418240   Unclaimed    Active   5d1h









From: Kai Lam
Sent: Monday, June 29, 2020 11:11 AM
To: openebs/openebs <reply@reply.github.com>; openebs/openebs <openebs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [E] Re: [openebs/openebs] Can claim more disk than the device block can support (#3067)

Just a curious question. If thin provisioning  is used and the volume is exhausted, it will put the volume in read-only mode. So this means that if we want to clear the exhausted volume by removing files, it failed, because the volume is in read-only mode. Is there a way for the user to get out from the read-only mode?
