### ISSUE TITLE
error Internal Server Error: failed to create volume 

### ISSUE THREAD

**Issue by kaitaklam** [openebs/openebs#3070]
## Description
// apply spc
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-raidz-pool1
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 1Gi
      - name: PoolResourceLimits
        value: |-
            memory: 1Gi
spec:
  name: cstor-raidz-pool
  type: disk
  poolSpec:
    poolType: raidz
    thickProvisioning: true
  blockDevices:
    blockDeviceList:
    - blockdevice-21f0a80c8ac4319bcb33d5b5f0c28c2d
    - blockdevice-3036a92092f6669e43d8a1d47a228c22
    - blockdevice-39f43a65cc1bb7de0e3bdbd8c2a30238
    - blockdevice-4b6215923c81883ff5b2eba02d411ff0
    - blockdevice-4bdbdd33de7790189c08e83381518a20
    - blockdevice-84cd05e0a5b74db0a0bf8703c7a4c83b
    - blockdevice-94ec16a3253cccd0da373a0ff2fba4b3
    - blockdevice-a51689191ae43ca219067deed3a5549d
    - blockdevice-faef7c0501d641b8dbe09f1ee8474831

// apply storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
#allowVolumeExpansion: false
metadata:
  name: openebs-cstor-sc
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-raidz-pool"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi

// check csp
# kubectl get csp
NAME                     ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE    AGE
cstor-raidz-pool1-26gt   166K        2.95G   2.95G      Healthy   false      raidz   7m47s
cstor-raidz-pool1-3f6m   166K        2.95G   2.95G      Healthy   false      raidz   7m48s
cstor-raidz-pool1-tuv9   166K        2.95G   2.95G      Healthy   false      raidz   7m48s

// apply pvc
apiVersion: v1
metadata:
  name: cstor-pvc-mysql-large
spec:
  storageClassName: openebs-cstor-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

// status pvc
# kubectl get pvc cstor-pvc-mysql-large
NAME                    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS       AGE
cstor-pvc-mysql-large   Pending                                      openebs-cstor-sc   2m18s

// error from describe pvc
# kubectl describe pvc cstor-pvc-mysql-large
Name:          cstor-pvc-mysql-large
Namespace:     default
StorageClass:  openebs-cstor-sc
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cstor-pvc-mysql-large","namespace":"default"},"spec...
               volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason              Age                From                                                                                                    Message
  ----     ------              ----               ----                                                                                                    -------
  Normal   Provisioning        29s (x3 over 74s)  openebs.io/provisioner-iscsi_openebs-provisioner-56d94d56f5-lccvf_63bf3fe3-b5f8-11ea-94d4-e61c7dc368cb  External provisioner is provisioning volume for claim "default/cstor-pvc-mysql-large"
  Warning  ProvisioningFailed  29s (x3 over 74s)  openebs.io/provisioner-iscsi_openebs-provisioner-56d94d56f5-lccvf_63bf3fe3-b5f8-11ea-94d4-e61c7dc368cb  failed to provision volume with StorageClass "openebs-cstor-sc": Internal Server Error: failed to create volume 'pvc-bb5e2d04-5806-43ac-9b25-404a06d475f2': response: failed to create volume:
casvolume {cloneSpec: {}
metadata:
  creationTimestamp: null
  labels:
    openebs.io/namespace: default
    openebs.io/persistentvolumeclaim: cstor-pvc-mysql-large
    openebs.io/storageclass: openebs-cstor-sc
  name: pvc-bb5e2d04-5806-43ac-9b25-404a06d475f2
  namespace: default
spec:
  accessMode: ""
  capacity: 1Gi
  casType: ""
  fsType: ""
  iqn: ""
  lun: 0
  replicas: ""
  targetIP: ""
  targetPort: ""
  targetPortal: ""
status:
  Message: ""
  Phase: ""
  Reason: ""
}: failed to execute volume engine: failed to execute runtask {cstor-volume-create-listcstorpoolcr-default-1.9.0}:
template values {CAST:
  castName: cstor-volume-create-default-1.9.0
  kubeVersion: v1.17.3
  version: 1.9.0
Config:
  AuxResourceLimits:
    enabled: ""
    value: none
  AuxResourceRequests:
    enabled: ""
    value: none
  FSType:
    enabled: ""
    value: ext4
  Lun:
    enabled: ""
    value: "0"
  OpenebsBaseDir:
    enabled: ""
    value: /var/openebs
  ReplicaCount:
    enabled: ""
    value: "3"
  ResyncInterval:
    enabled: ""
    value: "30"
  RunNamespace:
    enabled: ""
    value: kube-system
  ServiceAccountName:
    enabled: ""
    value: openebs-maya-operator
  StoragePoolClaim:
    enabled: ""
    value: cstor-raidz-pool
  TargetDir:
    enabled: ""
    value: /var/openebs
  TargetNodeSelector:
    enabled: ""
    value: none
  TargetResourceLimits:
    enabled: ""
    value: none
  TargetResourceRequests:
    enabled: ""
    value: none
  TargetTolerations:
    enabled: ""
    value: none
  VolumeControllerImage:
    enabled: ""
    value: 192.168.21.38:5000/openebs-cstor-volume-mgmt:1.9.0
  VolumeMonitorImage:
    enabled: ""
    value: 192.168.21.38:5000/openebs-m-exporter:1.9.0
  VolumeTargetImage:
    enabled: ""
    value: 192.168.21.38:5000/openebs-cstor-istgt:1.9.0
JsonResult: --redacted--
ListItems:
  pl:
  - ""
  rc: 3
TaskResult:
  creategetpvc:
    hostName: ""
    preferredReplicaAntiAffinity: ""
    replicaAntiAffinity: ""
    targetAffinity: none
    verifyErr: null
  creategetsc:
    storageClassVersion: "739744"
    verifyErr: null
  cvolcreatelistclonecvr:
    verifyErr: null
  cvolcreatelistpool:
    verifyErr: {}
  stsTargetAffinity: none
Volume:
  capacity: 1Gi
  isCloneEnable: "false"
  isRestoreVol: "false"
  owner: pvc-bb5e2d04-5806-43ac-9b25-404a06d475f2
  pvc: cstor-pvc-mysql-large
  runNamespace: default
  snapshotName: ""
  sourceVolume: ""
  sourceVolumeTargetIP: ""
  storageclass: openebs-cstor-sc
}: not enough pools available to create replicas
  Normal  ExternalProvisioning  1s (x6 over 74s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "openebs.io/provisioner-iscsi" or manually created by system administrator

## Expected Behavior
pvc created successfully

## Current Behavior
pvc gives errorr, status is in pending

## Steps to Reproduce
See above

## Your Environment
# kubectl get nodes
NAME           STATUS   ROLES    AGE   VERSION
k8s-master-0   Ready    master   46h   v1.17.3
k8s-worker-0   Ready    <none>   46h   v1.17.3
k8s-worker-1   Ready    <none>   46h   v1.17.3
k8s-worker-2   Ready    <none>   41h   v1.17.3

# kubectl get svc
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
http2c-server   ClusterIP   10.109.35.25   <none>        9990/TCP   17h
kubernetes      ClusterIP   10.96.0.1      <none>        443/TCP    46h

# kubectl get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-cstor-sc            openebs.io/provisioner-iscsi                               Delete          Immediate              false                  13m
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  46h
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  46h
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  46h
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  46h
openebs-standalone          openebs.io/provisioner-iscsi                               Delete          Immediate              false                  46h
openebs-standard            openebs.io/provisioner-iscsi                               Delete          Immediate              false                  46h

# kubectl get pv -A
No resources found

# kubectl get pvc
NAME                    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS       AGE
cstor-pvc-mysql-large   Pending                                      openebs-cstor-sc   4m36s

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"

**Comment by kmova** [comment]
The error indicates: `not enough pools available to create replicas`

Can you please check if there are 3 healthy cstor pools?

**Comment by kaitaklam** [comment]
I believe it is in the issue description.

#kubectl get csp
NAME ALLOCATED FREE CAPACITY STATUS READONLY TYPE AGE
cstor-raidz-pool1-26gt 166K 2.95G 2.95G Healthy false raidz 7m47s
cstor-raidz-pool1-3f6m 166K 2.95G 2.95G Healthy false raidz 7m48s
cstor-raidz-pool1-tuv9 166K 2.95G 2.95G Healthy false raidz 7m48s

**Comment by prateekpandey14** [comment]
@kaitaklam i think you have used the wrong name  of `StoragePoolClaim` in StorageClass annotations , the name should be `cstor-raidz-pool1` , can you verify once.

**Comment by kaitaklam** [comment]
Your are absolutely right!
Thanks

**Comment by kaitaklam** [comment]
typo error
