### ISSUE TITLE
After removing pvc ctsorevolumereplica's are still there or having error, how to remove them?

### ISSUE THREAD

**Issue by kaitaklam** [openebs/openebs#3071]
I just want to have a way to remove them, so that the black-devices become Unclaimed.

## Description
run kubectl delete -f pvc.yaml to delete pvcs.

For some unknown reason, There are still cstorevolumereplicas:
# kubectl get cvr -A
NAMESPACE     NAME                                                             USED   ALLOCATED   STATUS     AGE
kube-system   pvc-0a024c2c-8924-4eb2-875a-dc6ec0f0b071-cstor-raidz-pool-s1hk   6K     7.99K       Recreate   179m
kube-system   pvc-1bdce479-17fb-48ac-9ae2-56c3bc868e64-cstor-raidz-pool-s1hk   6K     7.99K       Recreate   3h1m
kube-system   pvc-581f5c8e-5493-4ee9-a5b8-8f9a747d1c9d-cstor-raidz-pool-iuy0   6K     7.99K       Error      178m
kube-system   pvc-581f5c8e-5493-4ee9-a5b8-8f9a747d1c9d-cstor-raidz-pool-s1hk   6K     7.99K       Recreate   178m
kube-system   pvc-581f5c8e-5493-4ee9-a5b8-8f9a747d1c9d-cstor-raidz-pool-yo22   6K     7.99K       Error      178m
kube-system   pvc-b25bd863-dd7d-4d59-9e97-24c9d6a361f3-cstor-raidz-pool-iuy0   6K     7.99K       Error      177m
kube-system   pvc-b25bd863-dd7d-4d59-9e97-24c9d6a361f3-cstor-raidz-pool-s1hk   6K     7.99K       Recreate   177m
kube-system   pvc-b25bd863-dd7d-4d59-9e97-24c9d6a361f3-cstor-raidz-pool-yo22   6K     7.99K       Error      177m

#  kubectl get pvc -A
No resources found

#  kubectl get csp -A
NAME                    ALLOCATED   FREE    CAPACITY   STATUS           READONLY   TYPE    AGE
cstor-raidz-pool-s1hk   6.09M       2.95G   2.95G      DeletionFailed   false      raidz   3h9m

#  kubectl get bd -A
NAMESPACE     NAME                                           NODENAME       SIZE          CLAIMSTATE   STATUS   AGE
kube-system   blockdevice-21f0a80c8ac4319bcb33d5b5f0c28c2d   k8s-worker-0   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-3036a92092f6669e43d8a1d47a228c22   k8s-worker-2   1073741824    Claimed      Active   4d23h
kube-system   blockdevice-39f43a65cc1bb7de0e3bdbd8c2a30238   k8s-worker-2   1073741824    Claimed      Active   4d23h
kube-system   blockdevice-4b6215923c81883ff5b2eba02d411ff0   k8s-worker-1   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-4bdbdd33de7790189c08e83381518a20   k8s-worker-0   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-84cd05e0a5b74db0a0bf8703c7a4c83b   k8s-worker-1   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-94ec16a3253cccd0da373a0ff2fba4b3   k8s-worker-1   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-a51689191ae43ca219067deed3a5549d   k8s-worker-0   1073741824    Claimed      Active   5d4h
kube-system   blockdevice-faef7c0501d641b8dbe09f1ee8474831   k8s-worker-2   1073741824    Claimed      Active   4d23h

#s# cat sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
#allowVolumeExpansion: false
metadata:
  name: openebs-cstor-sc
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-raidz-pool"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi

## Expected Behavior
csp and cvr should be removed

## Current Behavior
csp and cvr are not removed

**Comment by mittachaitu** [comment]
Hi @kaitaklam, Looks like tearing down the order is not followed. Can you list the steps performed to Teardown pools and volumes? Basically we need to follow:
- Delete PVC and wait till all the CStorVolume related resources to teardown(delete entries from etcd).
- Delete the SPC(StoragePoolClaim).

**Comment by kaitaklam** [comment]
I thinks I made the mistake that I didn’t check CStorVolume was removed after delete pvc.
I was forgotten to wait for CStorVolume Were completely removed and started deleting StorageClass and StoragePoolClaim.

My question is more, how to recover from this situation …

**Comment by mittachaitu** [comment]
> My question is more, how to recover from this situation …

- We can edit the CVR(CStorVolumeReplica) and remove the finalizers under metadata and it will take care of deleting from etcd.

Can I know the use case that you are performing?

**Comment by kaitaklam** [comment]
Here is the use case – 3 worker-nodes with 3 disks:

# kubectl get bd -A
NAMESPACE     NAME                                           NODENAME       SIZE          CLAIMSTATE   STATUS   AGE
kube-system   blockdevice-21f0a80c8ac4319bcb33d5b5f0c28c2d   k8s-worker-0   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-3036a92092f6669e43d8a1d47a228c22   k8s-worker-2   1073741824    Claimed      Active   4d23h
kube-system   blockdevice-39f43a65cc1bb7de0e3bdbd8c2a30238   k8s-worker-2   1073741824    Claimed      Active   4d23h
kube-system   blockdevice-4b6215923c81883ff5b2eba02d411ff0   k8s-worker-1   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-4bdbdd33de7790189c08e83381518a20   k8s-worker-0   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-84cd05e0a5b74db0a0bf8703c7a4c83b   k8s-worker-1   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-94ec16a3253cccd0da373a0ff2fba4b3   k8s-worker-1   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-a51689191ae43ca219067deed3a5549d   k8s-worker-0   1073741824    Claimed      Active   5d5h
kube-system   blockdevice-faef7c0501d641b8dbe09f1ee8474831   k8s-worker-2   1073741824    Claimed      Active   4d23h
kube-system   sparse-2aae5c1ae32e2f533e072ffc87ed7b5c        k8s-worker-2   10737418240   Unclaimed    Active   4d23h
kube-system   sparse-aa73ef381020b82f33a01f40571d046d        k8s-worker-0   10737418240   Unclaimed    Active   5d5h
kube-system   sparse-ecaf82cb369be323ada118141ff21ff3        k8s-worker-1   10737418240   Unclaimed    Active   5d5h

# cat spc.yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-raidz-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-raidz-pool
  type: disk
  poolSpec:
    poolType: raidz
    thickProvisioning: true
  blockDevices:
    blockDeviceList:
    - blockdevice-21f0a80c8ac4319bcb33d5b5f0c28c2d
    - blockdevice-3036a92092f6669e43d8a1d47a228c22
    - blockdevice-39f43a65cc1bb7de0e3bdbd8c2a30238
    - blockdevice-4b6215923c81883ff5b2eba02d411ff0
    - blockdevice-4bdbdd33de7790189c08e83381518a20
   - blockdevice-84cd05e0a5b74db0a0bf8703c7a4c83b
    - blockdevice-94ec16a3253cccd0da373a0ff2fba4b3
    - blockdevice-a51689191ae43ca219067deed3a5549d
    - blockdevice-faef7c0501d641b8dbe09f1ee8474831


# cat sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
#allowVolumeExpansion: false
metadata:
  name: openebs-cstor-sc
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-raidz-pool"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi

# cat pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-pvc-mysql-large
spec:
  storageClassName: openebs-cstor-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1950Mi

**Comment by kaitaklam** [comment]
Problem can be fixed 
 kubectl -n kube-system edit cvr  pvc-b25bd863-dd7d-4d59-9e97-24c9d6a361f3-cstor-raidz-pool-yo22


remove the flinalizers under metadata

Some for  kubectl edit csp cstor-raidz-pool-s1hk
remove the flinalizers under metadata

**Comment by mittachaitu** [comment]
@kaitaklam, Can we give a try(provisioning) using CSPC(enhanced version of SPC) and CSI volumes. With CSPC and CSI support Day-2-operations(disk replacement, volume expansion, pool expansion) can be achieved easily. 
- For creating CSPC based pools you can follow https://github.com/openebs/cstor-operators#project-status
- For creating CSI volumes you can follow https://github.com/openebs/cstor-csi

**Comment by kaitaklam** [comment]
Hi Sai,

I have 3 raidz pools:
NAME                    ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE    AGE
cstor-raidz-pool-a2jf   184K        2.95G   2.95G      Healthy   false      raidz   12m
cstor-raidz-pool-c0vy   184K        2.95G   2.95G      Healthy   false      raidz   12m
cstor-raidz-pool-hq8a   184K        2.95G   2.95G      Healthy   false      raidz   12m


According to https://docs.openebs.io/docs/next/ugcstor.html#deleting-a-cStor-volume 1 disk for parity and 2 disks are used for data.
So I assume that it should allow me to claim 2 x 2.95 GB = 5.9 GB

But the pvc claim failed with 5.5 GB
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-pvc-mysql-large
spec:
  storageClassName: openebs-cstor-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5500Mi

**Comment by mittachaitu** [comment]
> NAME                    ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE    AGE
cstor-raidz-pool-a2jf   184K               2.95G   2.95G           Healthy      false               raidz     12m
According to https://docs.openebs.io/docs/next/ugcstor.html#deleting-a-cStor-volume 1 disk for parity and 2 disks are used for data.
So I assume that it should allow me to claim 2 x 2.95 GB = 5.9 GB

Here, FREE represents available space without negotiating parity disk space(parity is distributed across all the disks). If we attach 3 1GB disks to the node then Total usable Capacity will be ~2GB because 1GB is for parity. So we can't provision volume having a capacity greater than 2G.

We fixed this kind of usability issue via CSPC in [PR](https://github.com/openebs/cstor-operators/pull/75#issue-419432063).

**Comment by kaitaklam** [comment]
Here, FREE represents available space without negotiating parity disk space(parity is distributed across all the disks). If we attach 3 1GB disks to the node then Total usable Capacity will be ~2GB because 1GB is for parity. So we can't provision volume having a capacity greater than 2G.
[KL] I agree that is per node, I get ~2G. But if I have 3 nodes. Wouldn’t the cStor pool adds up 3 node x ~2G = 6 G?

**Comment by mittachaitu** [comment]
>  I agree that is per node, I get ~2G. But if I have 3 nodes. Wouldn’t the cStor pool adds up 3 node x ~2G = 6 G?

OpenEBS is NOT distributed filesystem like CEPH.. with the emergence of microservices, we don't see the need for the same and all the complexity in maintaining distributed fs.. but, openebs allows your apps to run anywhere in the cluster.

**Comment by kaitaklam** [comment]
Sai,

Thanks for the explanations!

Regards

Kai
