### ISSUE TITLE
LVM support for Local PV (device and hostpath)

### ISSUE THREAD

**Issue by ThomasLohmann** [openebs/openebs#3078]
Hi everyone,

please support LVM for Local PV (device and hostpath) in order to resize a Local PV dynamically. It would be a big benefit to use e.g. ext4 + LVM. Because ZFS is not yet supported by the Linux kernel like ext4 and probably it never will be as Linus Torvalds mentioned a couple of months ago. Please, see the following link: 

https://www.phoronix.com/scan.php?page=news_item&px=Linus-Says-No-To-ZFS-Linux

TopoLVM could also serve as a good inspiration:

https://github.com/cybozu-go/topolvm

I'm really looking forward to LVM support as soon as possible. 

Thanks in advance!

**Comment by deveshk0** [comment]
@kmova Any plans to support this?

**Comment by kmova** [comment]
Hi @deveshk0 @ThomasLohmann Thanks for the issue. Will start looking into this for the august release. 

Would you like to participate in the design, implementation stages of this feature?

**Comment by deveshk0** [comment]
I kind of like the concept used in topoLVM Project, but dependency of running LVMd service on the nodes is an issue, Since openebs already runs the ndm on everyone to manage devices, It will be a good use if we can incorporate lvm groups topology in that and derive storage classes from that.

@kmova I will be happy to assist  in the design, implementation stages of this feature.

**Comment by SeMeKh** [comment]
Hi @ThomasLohmann 

I've been working on rawfile-localpv lately. It seems to me that it covers your requirements. Would you like to give it a try?

Let me know if you have any feedbacks too.

**Comment by deveshk0** [comment]
@SeMeKh Nice project. Can we assign on which drive the file should be created?

**Comment by SeMeKh** [comment]
@deveshk0 Right now, it stores the file in `/var/csi/rawfile`, but I'm planning to make it configurable.

**Comment by foldingbeauty** [comment]
@kmova Any news on the progress of this feature, would love to test it out.

**Comment by akhilerm** [comment]
Support to use DM devices (LVM, LUKS etc) as blockdevices has been merged and is available in openebs version 2.3.0

**Comment by foldingbeauty** [comment]
@akhilerm thanks. will try out soon. great work.

**Comment by kmova** [comment]
Just a quick update. We have started actively working on adding LVM support and we are trying to make an alpha version available by Jan 15th 2021.

**Comment by pawanpraka1** [comment]
Initial implementaion(alpha) of LVM driver has been done https://github.com/openebs/lvm-localpv/pull/1 and it is being actively developed.
