### ISSUE TITLE
[local setup] one of the minion nodes on reboot, shows NotReady - dockerd not running

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#308]
I have a local vagrant setup built using https://github.com/openebs/openebs/tree/master/k8s/vagrant/1.7.5, where I can see that one of the minion nodes is stuck in not ready state

```
ubuntu@kubemaster-01:~$ kubectl get nodes
NAME            STATUS     AGE       VERSION
kubemaster-01   Ready      49m       v1.7.5
kubeminion-01   NotReady   46m       v1.7.5
kubeminion-02   Ready      40m       v1.7.5
```

I logged into the node and checked the status of kubelet:

```
ubuntu@kubeminion-01:~$ service kubelet status
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2017-09-13 03:34:03 UTC; 11min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 1346 (kubelet)
    Tasks: 8
   Memory: 63.4M
      CPU: 1.396s
   CGroup: /system.slice/kubelet.service
           └─1346 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-p

Sep 13 03:34:03 kubeminion-01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 13 03:34:30 kubeminion-01 kubelet[1346]: I0913 03:34:30.255762    1346 feature_gate.go:144] feature gates: map[]
Sep 13 03:34:31 kubeminion-01 kubelet[1346]: I0913 03:34:31.649764    1346 client.go:72] Connecting to docker on unix:///var/run/docker.sock
Sep 13 03:34:31 kubeminion-01 kubelet[1346]: I0913 03:34:31.650417    1346 client.go:92] Start docker client with request timeout=2m0s
Sep 13 03:36:31 kubeminion-01 kubelet[1346]: E0913 03:36:31.651180    1346 kube_docker_client.go:99] failed to retrieve docker version: operation timeout: context deadline exceeded
Sep 13 03:36:31 kubeminion-01 kubelet[1346]: W0913 03:36:31.651237    1346 kube_docker_client.go:100] Using empty version for docker client, this may sometimes cause compatibility issu
Sep 13 03:36:32 kubeminion-01 kubelet[1346]: I0913 03:36:32.820393    1346 manager.go:143] cAdvisor running in container: "/system.slice/kubelet.service"
```

kubelet is running, but I am not able to access docker commands:

```
ubuntu@kubeminion-01:~$ sudo docker ps


^Cubuntu@kubeminion-01:~$ sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (start) since Wed 2017-09-13 03:34:01 UTC; 13min ago
     Docs: https://docs.docker.com
 Main PID: 1243 (docker)
    Tasks: 7
   Memory: 40.1M
      CPU: 222ms
   CGroup: /system.slice/docker.service
           └─1243 /usr/bin/docker daemon -H fd://

Sep 13 03:34:01 kubeminion-01 systemd[1]: Starting Docker Application Container Engine...
Sep 13 03:34:18 kubeminion-01 docker[1243]: time="2017-09-13T03:34:18.513020363Z" level=info msg="New containerd process, pid: 1645\n"
Sep 13 03:34:25 kubeminion-01 docker[1243]: time="2017-09-13T03:34:25.312847160Z" level=info msg="previous instance of containerd still alive (1645)"
ubuntu@kubeminion-01:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ubuntu@kubeminion-01:~$ sudo service docker start
^C
ubuntu@kubeminion-01:~$ ps -auxf | grep docker
root      1243  0.0  2.9 185324 29952 ?        Ssl  03:34   0:00 /usr/bin/docker daemon -H fd://
ubuntu    2410  0.0  0.0  12948   988 pts/0    S+   03:49   0:00              \_ grep --color=auto docker
ubuntu@kubeminion-01:~$ 

```

**Comment by kmova** [comment]
To bring back the node online, I did the following:

restart the minion node:
```
vagrant halt kubeminion-01
vagrant up kubeminion-01
```

Post the reboot, the docker commands were working:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@kubeminion-01:~$ sudo docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kube-apiserver-amd64            v1.7.5              33cecf00bef1        12 days ago         186.1 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.7.5              4d581c01252d        12 days ago         138 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.7.5              2aad6febbb16        12 days ago         77.2 MB
gcr.io/google_containers/kube-proxy-amd64                v1.7.5              1314eb3ac430        12 days ago         114.7 MB
weaveworks/weave-npc                                     2.0.4               a33806b1a7de        2 weeks ago         54.69 MB
weaveworks/weave-kube                                    2.0.4               3e2e9472eefc        2 weeks ago         100.7 MB
gcr.io/google_containers/kubernetes-dashboard-amd64      v1.6.3              691a82db1ecd        6 weeks ago         139 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.4              38bac66034a6        11 weeks ago        41.81 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.4              a8e00546bcf3        11 weeks ago        49.38 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.4              f7f45b9cb733        11 weeks ago        41.41 MB
openebs/jiva                                             0.3-RC2             ab153ccaa15e        11 weeks ago        265.9 MB
gcr.io/google_containers/etcd-amd64                      3.0.17              243830dae7dd        6 months ago        168.9 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        16 months ago       746.9 kB
```

However, the node was still showing - not ready and the kubelet logs were showing the following:

```
ubuntu@kubeminion-01:~$ sudo service kubelet status
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2017-09-13 03:50:31 UTC; 13min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 1266 (kubelet)
    Tasks: 16
   Memory: 94.0M
      CPU: 31.403s
   CGroup: /system.slice/kubelet.service
           ├─1266 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-p
           └─1855 journalctl -k -f

Sep 13 03:59:03 kubeminion-01 kubelet[1266]: E0913 03:59:03.658168    1266 kubelet.go:1621] Unable to mount volumes for pod "weave-net-22rz6_kube-system(c9e0991c-982e-11e7-afac-021c6f7
Sep 13 03:59:03 kubeminion-01 kubelet[1266]: E0913 03:59:03.659241    1266 pod_workers.go:182] Error syncing pod c9e0991c-982e-11e7-afac-021c6f7dbe9d ("weave-net-22rz6_kube-system(c9e0
Sep 13 04:01:07 kubeminion-01 kubelet[1266]: E0913 04:01:07.364529    1266 kubelet.go:1621] Unable to mount volumes for pod "weave-net-22rz6_kube-system(c9e0991c-982e-11e7-afac-021c6f7
Sep 13 04:01:07 kubeminion-01 kubelet[1266]: E0913 04:01:07.365282    1266 pod_workers.go:182] Error syncing pod c9e0991c-982e-11e7-afac-021c6f7dbe9d ("weave-net-22rz6_kube-system(c9e0
Sep 13 04:01:07 kubeminion-01 kubelet[1266]: E0913 04:01:07.364530    1266 kubelet.go:1621] Unable to mount volumes for pod "kube-proxy-st93v_kube-system(c9e0b24c-982e-11e7-afac-021c6f
Sep 13 04:01:07 kubeminion-01 kubelet[1266]: E0913 04:01:07.365878    1266 pod_workers.go:182] Error syncing pod c9e0b24c-982e-11e7-afac-021c6f7dbe9d ("kube-proxy-st93v_kube-system(c9e
Sep 13 04:03:11 kubeminion-01 kubelet[1266]: E0913 04:03:11.032972    1266 kubelet.go:1621] Unable to mount volumes for pod "weave-net-22rz6_kube-system(c9e0991c-982e-11e7-afac-021c6f7
Sep 13 04:03:11 kubeminion-01 kubelet[1266]: E0913 04:03:11.033037    1266 pod_workers.go:182] Error syncing pod c9e0991c-982e-11e7-afac-021c6f7dbe9d ("weave-net-22rz6_kube-system(c9e0
Sep 13 04:03:11 kubeminion-01 kubelet[1266]: E0913 04:03:11.032974    1266 kubelet.go:1621] Unable to mount volumes for pod "kube-proxy-st93v_kube-system(c9e0b24c-982e-11e7-afac-021c6f
Sep 13 04:03:11 kubeminion-01 kubelet[1266]: E0913 04:03:11.033091    1266 pod_workers.go:182] Error syncing pod c9e0b24c-982e-11e7-afac-021c6f7dbe9d ("kube-proxy-st93v_kube-system(c9e
ubuntu@kubeminion-01:~$ 
```

I restarted the kubelet and Node came online:
```
ubuntu@kubeminion-01:~$ sudo service kubelet restart
```
ubuntu@kubeminion-01:~$ sudo service kubelet status
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2017-09-13 04:04:33 UTC; 1min 30s ago
     Docs: http://kubernetes.io/docs/
 Main PID: 2696 (kubelet)
    Tasks: 14
   Memory: 37.0M
      CPU: 4.459s
   CGroup: /system.slice/kubelet.service
           ├─2696 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-p
           └─2731 journalctl -k -f

Sep 13 04:04:38 kubeminion-01 kubelet[2696]: I0913 04:04:38.584691    2696 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "weavedb" (UniqueName:
Sep 13 04:04:38 kubeminion-01 kubelet[2696]: I0913 04:04:38.788037    2696 kuberuntime_manager.go:457] Container {Name:weave Image:weaveworks/weave-kube:2.0.4 Command:[/home/weave/laun
Sep 13 04:04:38 kubeminion-01 kubelet[2696]: I0913 04:04:38.788191    2696 kuberuntime_manager.go:457] Container {Name:weave-npc Image:weaveworks/weave-npc:2.0.4 Command:[] Args:[] Wor
Sep 13 04:04:38 kubeminion-01 kubelet[2696]: I0913 04:04:38.790535    2696 kuberuntime_manager.go:457] Container {Name:kube-proxy Image:gcr.io/google_containers/kube-proxy-amd64:v1.7.5
Sep 13 04:04:42 kubeminion-01 kubelet[2696]: I0913 04:04:42.205284    2696 kuberuntime_manager.go:741] checking backoff for container "kube-proxy" in pod "kube-proxy-st93v_kube-system(
Sep 13 04:04:42 kubeminion-01 kubelet[2696]: I0913 04:04:42.251027    2696 kuberuntime_manager.go:741] checking backoff for container "weave" in pod "weave-net-22rz6_kube-system(c9e099
Sep 13 04:04:43 kubeminion-01 kubelet[2696]: W0913 04:04:43.016638    2696 pod_container_deletor.go:77] Container "28083140f9999754fb6556048679330ec9a611e27ba7507248fbe530f02b8070" not
Sep 13 04:04:51 kubeminion-01 kubelet[2696]: I0913 04:04:51.745014    2696 kuberuntime_manager.go:741] checking backoff for container "weave-npc" in pod "weave-net-22rz6_kube-system(c9
Sep 13 04:05:03 kubeminion-01 kubelet[2696]: W0913 04:05:03.945758    2696 conversion.go:110] Could not get instant cpu stats: different number of cpus
Sep 13 04:05:14 kubeminion-01 kubelet[2696]: W0913 04:05:14.010214    2696 conversion.go:110] Could not get instant cpu stats: different number of cpus
ubuntu@kubeminion-01:~$ sudo docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS              PORTS               NAMES
8bd74b5dd6b6        a33806b1a7de                               "/usr/bin/weave-npc"     About a minute ago   Up About a minute                       k8s_weave-npc_weave-net-22rz6_kube-system_c9e0991c-982e-11e7-afac-021c6f7dbe9d_1
e05dce85b9ec        3e2e9472eefc                               "/home/weave/launch.s"   About a minute ago   Up About a minute                       k8s_weave_weave-net-22rz6_kube-system_c9e0991c-982e-11e7-afac-021c6f7dbe9d_1
61c2b05d743f        1314eb3ac430                               "/usr/local/bin/kube-"   About a minute ago   Up About a minute                       k8s_kube-proxy_kube-proxy-st93v_kube-system_c9e0b24c-982e-11e7-afac-021c6f7dbe9d_1
28732708da8d        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 About a minute ago   Up About a minute                       k8s_POD_kube-proxy-st93v_kube-system_c9e0b24c-982e-11e7-afac-021c6f7dbe9d_1
28083140f999        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 About a minute ago   Up About a minute                       k8s_POD_weave-net-22rz6_kube-system_c9e0991c-982e-11e7-afac-021c6f7dbe9d_1
ubuntu@kubeminion-01:~$

**Comment by ksatchit** [comment]
The vagrantfile should consist of triggers to check if the cluster is in proper condition, i.e., required services are running and all nodes are in READY state.

**Comment by harshvkarn** [comment]
facing same issue
Vagrant setup using  https://github.com/openebs/openebs/tree/master/k8s/vagrant/1.10.0
```
ubuntu@kubemaster-01:~$ kubectl get nodes
NAME            STATUS     ROLES     AGE       VERSION
kubemaster-01   Ready      master    1d        v1.10.0
kubeminion-01   Ready      <none>    1d        v1.10.0
kubeminion-02   NotReady   <none>    1d        v1.10.0
```
