### ISSUE TITLE
Separate NIC card support for OpenEBS.

### ISSUE THREAD

**Issue by ChandanSagar** [openebs/openebs#3080]
The user has 2 NIC cards ( 10 Gig each, Bond-0, LACP) configured for the nodes.
Now the user wants to have another 2 NIC cards ( 10 Gig each, Bond-0, LACP) which will be used for OpenEBS, iSCSI, and storage communications. All other communication will happen through the 1st 2 NIC cards bond.

## Context
The user wants to have separate NIC cards for OpenEBS.

**Comment by cospotato** [comment]
Dose the team have any support?
