### ISSUE TITLE
Suggestions for colour coding of issue tags

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#309]
We have lots of issue tags. Some of them begin with `kind/` , it'll be good to group them as one different shades of a similar colour.

**Comment by vharsh** [comment]
Sanya suggests
- help = green
- kind = pink
- area = brown
- size = grey
- priority = red
- repo = yellow
- general = blue
Changes ?

**Comment by kmova** [comment]
Just thinking aloud. Number and type of labels that can be associated with issues can change depending on the community and how the project evolves. Having said that, let us see if we can associate some significance to the colors like:

anything informational = blue
anything related to approval = green
anything related to bugs, disapproval = red
anything related to book-keeping = brown 

repo and help related labels are good example for book-keeping / brown category, while the kind, size and priority related labels can take on different colors ranging from blue - yellow - orange and red.

**Comment by prateekpandey14** [comment]
We can also refers to [ kubernetes labels](https://github.com/kubernetes/kubernetes/labels).

**Comment by kmova** [comment]
@vharsh I updated the coloring scheme for the labels, with the following guidelines. 

- application related (brown)
- area related  ( blue) 
- dependency ( light purple)
- deployment (light blue)
- documentation ( light green, except when action is required) 
- issue closing labels - invalid, wont fix, duplicate (dark gray)
- trendy label - hacktoberfest, first-timers, pinned,  (dark purple)
- help ( teal)
- kind ( ranges from blue, yellow, orange and red)
- priority ( red - for highest priority and gray for house-keeping)
- repo tags ( brown)
- size ( ranges from green to red)
- status ( yellow)

If you are ok with the above scheme, can you submit a PR with a doc under the openebs/contribute. The doc can be used as a place-holder for future reviews from the community.

**Comment by vharsh** [comment]
Sounds perfect, it looks like a good `first-timers-only` PR :+1:

**Comment by vharsh** [comment]
Is it good to have [status/hacked-fix](https://github.com/openebs/openebs/issues?q=is%3Aissue+is%3Aopen+label%3Astatus%2Fhacked-fix) in cases where the exact cause isn't known?
This is something similar in spirit to *known-issues* and their workarounds.
For now I've tagged some problems which we have faced while making openEBS awesome.

**Comment by kmova** [comment]
how do we differentiate between status/hacked-fix and kind/technical-debt ?

**Comment by vharsh** [comment]
I think `status/hacked-fix` can be used for problems with our/others' systems and how we/they fixed it.
On the other hand `kind/technical-debt` can be used to represent a workaround in our code/config, which works for most people but isn't the best solution. 

'status/hacked-fix` can be a futurre common troubleshooting area.
