### ISSUE TITLE
Support for geo-replication

### ISSUE THREAD

**Issue by stevefan1999-personal** [openebs/openebs#3092]
## Description
What if we can do geo-replication like Azure, Google and AWS?

This is an extremely hard feature to add. And before that we may also need to implement availability zone too which is also hard to begin with.

## Context
So I have a k3s network that spans from AP to US, connected into a private flannel overlay via Wireguard. And because the latency from Korea/Hong Kong to US is quite high the iSCSI command is way too slow (I've recorded 8MB/s only, maybe I need to make some network optimization) so that most application deployed to my AP compute nodes are very very slow, for example the PostgreSQL master took 15 minutes to load and the liveness probe killed the app so on and on, which resulted in data corruption.

So I have this idea to replicate some data from US to a specific Asian storage node and then let the replication sort it out. Yet because OpenEBS doesn't assume geolocations I think the target pod distribution would be randomized?

## Possible Solution
We can leverage cStor snapshots to send the data to different data centers to different places on earth then we can chain them up like git merge if there's a split brain discrepancy due to latency/bandwidth issue.

Or should I just label the storage nodes on different side of the world, then let target pods run only on them that they will eventually sort the replication stuff out to have some degree of georeplication?

**Comment by muratkars** [comment]
Hi @stevefan1999-personal thanks for the details and taking time to report a feature request. 
Would one-to-many asynchronously restored backups work? We had similar requests and conversation with other users. One possible recommended solution was a streaming backup. As you may be aware of, there is product called [Kubera](https://mayadata.io/product) from MayaData, used by OpenEBS users to manage simplify OpenEBS operations, currently it is a work-in-progress feature on Kubera.
Let's say, Kubera would create scheduled incremental backup of your app and data from the cluster in Hong Kong and put it on a S3 compliant storage (could be AWS S3, MinIO, Cloudian, etc) then when a new backup is detected Kubera would again restore the incremental copy to your target clusters in US and different geo-locations.
Of course, this wouldn't work if you expect data to be updated in all locations and synced.
Happy to discuss this on [OpenEBS channel](https://kubernetes.slack.com/messages/openebs/)
