### ISSUE TITLE
follow Read-Write-Many PVC, got nsf mount failure

### ISSUE THREAD

**Issue by kaitaklam** [openebs/openebs#3093]
follow the deployment steps from https://docs.openebs.io/docs/next/rwm.html#setting-up-multiple-nfs-servers.

got nfs-server-provisioner running!
nsf-server-provisioner   nsf-server-provisioner-nfs-server-provisioner-0                   1/1     Running             0          23m    172.16.140.25    k8s-worker-2   <none>           <none>

got nfs pvc bound
kubectl get pvc -A
NAMESPACE                NAME                                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
default                  test-dynamic-volume-claim                              Bound    pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725   1Gi        RWO            nfs                      7m42s
nsf-server-provisioner   data-nsf-server-provisioner-nfs-server-provisioner-0   Bound    pvc-da406951-b464-4d5f-acc3-8809b156fd37   2Gi        RWO            openebs-sc-statefulset   48m

when deploy pod and use the pvc, I got mount failure
kubectl describe pod http2c-server-deployment-667c64dfc5-f7tr7
Events:
  Type     Reason            Age                From                   Message
  ----     ------            ----               ----                   -------
  Warning  FailedScheduling  48s (x2 over 48s)  default-scheduler      persistentvolumeclaim "test-dynamic-volume-claim" not found
  Warning  FailedScheduling  28s (x2 over 28s)  default-scheduler      error while running "VolumeBinding" filter plugin for pod "http2c-server-deployment-667c64dfc5-f7tr7": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         26s                default-scheduler      Successfully assigned default/http2c-server-deployment-667c64dfc5-f7tr7 to k8s-worker-2
  Warning  FailedMount       26s                kubelet, k8s-worker-2  MountVolume.SetUp failed for volume "pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/146365d2-1a05-4702-8b40-084574a3b73e/volumes/kubernetes.io~nfs/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725 --scope -- mount -t nfs -o vers=3 10.96.98.108:/export/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725 /var/lib/kubelet/pods/146365d2-1a05-4702-8b40-084574a3b73e/volumes/kubernetes.io~nfs/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725
Output: Running scope as unit run-14235.scope.
mount: wrong fs type, bad option, bad superblock on 10.96.98.108:/export/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
  Warning  FailedMount  25s  kubelet, k8s-worker-2  MountVolume.SetUp failed for volume "pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/146365d2-1a05-4702-8b40-084574a3b73e/volumes/kubernetes.io~nfs/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725 --scope -- mount -t nfs -o vers=3 10.96.98.108:/export/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725 /var/lib/kubelet/pods/146365d2-1a05-4702-8b40-084574a3b73e/volumes/kubernetes.io~nfs/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725
Output: Running scope as unit run-14270.scope.
mount: wrong fs type, bad option, bad superblock on 10.96.98.108:/export/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by kaitaklam** [comment]
pod.yaml   

     volumeMounts:
        - mountPath: /nfsdir
          name: nfsvolume
      volumes:
      - name: nfsvolume
        persistentVolumeClaim:
          claimName: test-dynamic-volume-claim


pvc.yaml:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs"

**Comment by kaitaklam** [comment]
found critical error log file /export/ganesha.log.
nfs-ganesha-21[main] claim_posix_filesystems :FSAL :CRIT :Could not stat directory for path /nonexistent

not sure if this is an issue.


 cat ganesha.log
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.2
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] claim_posix_filesystems :FSAL :CRIT :Could not stat directory for path /nonexistent
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] vfs_create_export :FSAL :CRIT :resolve_posix_filesystem(/nonexistent) returned No such file or directory (2)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL VFS
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/nonexistent) to (/nonexistent)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] export_commit_common :CONFIG :CRIT :Export id 0 can only export "/" not (/nonexistent)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:28): 1 validation errors in block FSAL
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:28): Errors processing block (FSAL)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:12): 1 validation errors in block EXPORT
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] config_errs_to_log :CONFIG :CRIT :Config File (/export/vfs.conf:12): Errors processing block (EXPORT)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/usr/local/var/run/ganesha) already exists
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:22)
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
31/07/2020 08:44:55 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
31/07/2020 08:46:25 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
31/07/2020 08:55:38 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[dbus_heartbeat] release_posix_file_system :FSAL :WARN :Filesystem /export is still claimed
31/07/2020 09:03:57 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[dbus_heartbeat] release_posix_file_system :FSAL :WARN :Filesystem /export is still claimed
31/07/2020 09:14:39 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[dbus_heartbeat] release_posix_file_system :FSAL :WARN :Filesystem /export is still claimed
31/07/2020 10:57:58 : epoch 5f23da07 : nsf-server-provisioner-nfs-server-provisioner-0 : nfs-ganesha-21[dbus_heartbeat] release_posix_file_system :FSAL :WARN :Filesystem /export is still claimed

**Comment by kaitaklam** [comment]
# cat /export/vfs.conf

###################################################
#
# EXPORT
#
# To function, all that is required is an EXPORT
#
# Define the absolute minimal export
#
###################################################

EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 0;

        # Exported path (mandatory)
        Path = /nonexistent;

        # Pseudo Path (required for NFS v4)
        Pseudo = /nonexistent;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        # Exporting FSAL
        FSAL {
                Name = VFS;
        }
}

NFS_Core_Param
{
        MNT_Port = 20048;
        NLM_Port = 32803;
        fsid_device = true;
}

NFSV4
{
        Grace_Period = 90;
}

EXPORT
{
        Export_Id = 1;
        Path = /export/pvc-f3ef269c-bea2-419f-bd56-3e2617733c84;
        Pseudo = /export/pvc-f3ef269c-bea2-419f-bd56-3e2617733c84;
        Access_Type = RW;
        Squash = no_root_squash;
        SecType = sys;
        Filesystem_id = 1.1;
        FSAL {
                Name = VFS;
        }
}

**Comment by kmova** [comment]
Could be related to: https://github.com/openebs/dynamic-nfs-provisioner/issues/46

**Comment by mittachaitu** [comment]
> mount: wrong fs type, bad option, bad superblock on 10.96.98.108:/export/pvc-a6e2534d-fe7e-4b3e-adc6-b09f6dd01725,
missing codepage or helper program, or other error
(for several filesystems (e.g. nfs, cifs) you might
need a /sbin/mount. helper program)

Hi @kaitaklam , Sorry for delayed response.. Mostly above error looks like `nfs-utils` are not installed on the node. To export volume over NFS `nfs-utils` are required on the node. Can you install [prerequisites](https://github.com/openebs/dynamic-nfs-provisioner#prerequisites) and try to run the application?

**Comment by mittachaitu** [comment]
Closing this issue as there is no response from as well as assuming installing `nfs-util` will fix the issue. Please feel free to re-open if the suggestion didn't work.
