### ISSUE TITLE
NDM block device cleanup Job failing

### ISSUE THREAD

**Issue by kumar-mayadata** [openebs/openebs#3099]
After we installed OpenEBS it was found that the block devices were in  "Released" and "Active" state.
It was observed that block device cleanup jobs were failed with an error:
`invalid argument /dev/dm-0`

When checked further, the observation was this that, partprobe was getting failed for /dev/dm-0. However, the same command `partprobe /dev/dm-0` was working successfully when executed from the worker nodes.

PS: we are using encrypted disks using LUKS methodology.

**Comment by akhilerm** [comment]
Support for DM devices has been added to NDM in https://github.com/openebs/node-disk-manager/pull/495. This includes support for LVM, Luks device etc. Cleanup is also now supported for DM devices.
