### ISSUE TITLE
Why openebs is shown under kubernetes-retired?

### ISSUE THREAD

**Issue by calvinyv** [openebs/openebs#3100]
## Description

openebs is found under kuberentes-retired, is this project going to retire?

https://github.com/kubernetes-retired/external-storage/tree/master/openebs

**Comment by kmova** [comment]
Hi @calvinyv - the repository kubernetes-incubator has been retired. All the provisioners have moved to CSI and new indepenent repositories. 

for example cStor is now moved to: https://github.com/oenebs/cstor-operators

**Comment by calvinyv** [comment]
got it, thx.
