### ISSUE TITLE
Backup OpenEBS local PV Hostpath with Velero don't restore files

### ISSUE THREAD

**Issue by Titof974** [openebs/openebs#3106]
Hello,

I followed this https://docs.openebs.io/docs/next/uglocalpv-hostpath.html, but when I restored my backup, I didn't get my greet.txt file back. Is it a bug or Velero doesn't support PV hostpath ?

My velero command:
```
./velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0 \
    --bucket test \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://192.168.48.153:9000 \
    --use-restic
```
I'm using restic.

Thanks,
Titof

**Comment by kmova** [comment]
Hi @Titof974 - can you help with the output of `velero backup get` and also the details of the backup to check if the volume was really backed-up.
