### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by harridu** [openebs/openebs#3118]
Would you mind to add Debian to https://docs.openebs.io/docs/next/prerequisites.html ?

I am not sure, why open-iscsi is needed on the host at all. Ain't this iscsi stuff supposed to happen in the containers? All you would need is the iscsi-tcp module.

**Comment by prateekpandey14** [comment]
> Would you mind to add Debian to https://docs.openebs.io/docs/next/prerequisites.html ?

@harridu the installation  steps will be similar to Ubuntu.

> am not sure, why open-iscsi is needed on the host at all. Ain't this iscsi stuff supposed to happen in the containers? All you would need is the iscsi-tcp module.

I think you are using rancher based k8s cluster, where kubelet runs inside the container. Rancher suggest to install the iscsi in hosts instead of inside the container and bind mount inside the container, you can read more about here https://github.com/openebs/cstor-operators/blob/master/docs/troubleshooting/rancher_prerequisite.md

**Comment by harridu** [comment]
Where do I have to look for error messages indicating that the bind mounts are missing?

**Comment by prateekpandey14** [comment]
if ISCSI installation is missing (or missed to bind mount) the application pod will struck in container creating state , complaining about iscsi bin is missing .

**Comment by harridu** [comment]
There are no pods stuck in "creating", even though there are no bind mounts. ???

**Comment by harridu** [comment]
Sample:
~~~
% cat <<EOF | kubectl apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-pvc-sample1
spec:
  storageClassName: sc-repl1-pool2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
EOF
persistentvolumeclaim/cstor-pvc-sample1 created
% cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-pod
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 8080
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: cstor-pvc-sample1
EOF
% kubectl get pods
NAME       READY   STATUS    RESTARTS   AGE
test-pod   1/1     Running   0          30s
~~~

**Comment by harridu** [comment]
This looks weird:
~~~
% kubectl exec test-pod -- sh -c "grep /data /proc/self/mounts"           
/dev/sdd /data ext4 rw,relatime,stripe=256 0 0
~~~
Doesn't look like an iscsi volume to me.

**Comment by harridu** [comment]
Apparently Rancher 2.x clusters include iscsi initiator support: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/iscsi-volumes/. In case of incompatibilities between initiator and target on the node these bind mounts should be applied, AFAICS.
