### ISSUE TITLE
what is meant by "it results into eviction"?

### ISSUE THREAD

**Issue by harridu** [openebs/openebs#3119]
About: https://docs.openebs.io/docs/next/installation.html: What is meant by "if any containers does not set its resource requests & limits values, it results into eviction"? This sounds like something bad, but is it? Please elaborate.

Maybe its just me, but this is extremely hard to understand, if English is not your mother's language.

**Comment by prateekpandey14** [comment]
>"if any containers does not set its resource requests & limits values, it results into eviction"

When a node in a Kubernetes cluster is running out of memory or disk, it activates a flag signaling that it is under pressure. This blocks any new allocation in the node and starts the eviction process.

At that moment, kubelet starts to reclaim resources, killing containers and declaring pods as failed until the resource usage is under the eviction threshold again.

Guaranteed pods with QOS set (having request and limits set) are supposed to be safe in case of eviction. so its better practice to set requests and limits in your pods. Setting those values properly can protect you from unexpected outages.

check out k8s docs https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ to understand more about this.
