### ISSUE TITLE
Fix mix-indent in Vagrantfile openebs repo

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#312]
Some Vagrantfiles across our repos have mixed indentation.
Find them and fix them. One per commit and one per PR.

Prerequisites:
- some working knowledge of git & vagrant

Helpful points
- Run `vagrant validate` to see if the `Vagrantfile` is okay.

Congratulations on your :1st_place_medal: PR.

**Comment by lisaychuang** [comment]
Hey @vharsh , do you have preference for standardization - double spaces or tab indent?  For example the [Vagrantfile](https://github.com/openebs/openebs/blob/74aaee06d5b737b21145834958608150ecfa48df/k8s/demo/Vagrantfile) in k8s/demo . I'd like to work on this issue for #Hacktoberfest

**Comment by kmova** [comment]
@lisaychuang thanks for pitching in. Can you raise a new issue for fixing the k8s/demo/Vagrantfile. We will tag it with hacktoberfest. Our preference for indentation is 2 tabs.

**Comment by lisaychuang** [comment]
Hi @kmova , I've just raise a new issue #456

**Comment by kmova** [comment]
Thanks @lisaychuang. Here is a good reference for fixing styles of ruby code: https://github.com/bbatsov/ruby-style-guide

**Comment by vharsh** [comment]
@me `vagrant validate` is not present in **1.9.1**

**Comment by vipulgupta2048** [comment]
I have some experience using Vagrant and Vagrant files. I am taking this up. Will report on the same.
Confirming details 
Indent - 4 spaces right 
Tabs or spaces. My editor can fix that too, if you like.

**Comment by sayak119** [comment]
Hi I am taking up 1.7.5 indentation. Will submit a PR soon.

**Comment by palash16** [comment]
Hi I want to work on 1.8.2 indentation standardization

**Comment by Kanav-7** [comment]
I would like to work on 1.8.8 indentation.

**Comment by vipulgupta2048** [comment]
@kmova Pretty sure, there is no vagrant file left to be fixed now. Do consider the issue for closing.
