### ISSUE TITLE
"Set cluster-admin user context and RBAC" doesn't really tell

### ISSUE THREAD

**Issue by harridu** [openebs/openebs#3120]
https://docs.openebs.io/docs/next/installation.html#set-cluster-admin-user-context-and-rbac shows how to set a new context, but except for the headline it doesn't mention RBACs at all. Whats the story here?

**Comment by prateekpandey14** [comment]
@harridu thanks for pointing this. steps are only for set the context, will update the docs and remove the RBAC from the heading.

**Comment by prateekpandey14** [comment]
@harridu will you be able to raise a PR in openebs-docs repo to fix this, you have to just click on the `EDIT` button in top right corner of the [page link](https://docs.openebs.io/docs/next/installation.html#set-cluster-admin-user-context-and-rbac) , make the changes and raise a PR.

**Comment by Someshbose** [comment]
I want to work on this. Should I raise a PR for the same @prateekpandey14 ?

**Comment by Someshbose** [comment]
please review the PR https://github.com/openebs/openebs/issues/3120

**Comment by prateekpandey14** [comment]
@Someshbose thanks for the PR . it will be great if you can go through the [contributing guidelines PR details](https://github.com/openebs/openebs/blob/master/contribute/git-commit-message.md) and change the PR commit and description according to that.

**Comment by Someshbose** [comment]
@prateekpandey14  have done the changes, please review again.

**Comment by Someshbose** [comment]
Hi @prateekpandey14 can you please look into it

**Comment by kmova** [comment]
Thanks @Someshbose . Merged!
