### ISSUE TITLE
Cannot override the registry from where to pull 'linux-utils' helper image used

### ISSUE THREAD

**Issue by mzur-hv** [openebs/openebs#3122]
## Description

Overriding the `helper.image` value of the openebs helm chart is not honored by the local host provisioner. The 'init-pvc' pod created is always using the `quay.io` registry, which ends up with a failure to pull the image on dark sites and/or from a non public registry (e.g. with auth).

`helper:
  image: "quay.io/openebs/linux-utils"`

## Expected Behavior
helper image (linux-utils) should be pulled from the specified registry.

## Current Behavior
the helper image is always and only pulled from `quay.io`

## Possible Solution

Despite having the helper image environment `OPENEBS_IO_HELPER_IMAGE` variable set in the pod, the `hostpath` provisioner seems to **not** be passing the `helper.image` value to the PV pod init creation (similar to _serviceAccountName_):

    `podOpts := &HelperPodOptions{
		cmdsForPath:        initCmdsForPath,
		name:               name,
		path:               path,
		nodeHostname:       nodeHostname,
		serviceAccountName: saName,
		selectedNodeTaints: taints,
	}
	iErr := p.createInitPod(podOpts)`

On the other hand, it looks like the base provisioner is using the `getDefaultHelperImage()`  to set the `helperImage`

         `p := &Provisioner{
		stopCh: stopCh,

		kubeClient:  kubeClient,
		namespace:   namespace,
		helperImage: getDefaultHelperImage(),
		defaultConfig: []mconfig.Config{
			{
				Name:  KeyPVBasePath,
				Value: getDefaultBasePath(),
			},
		},
	}
	p.getVolumeConfig = p.GetVolumeConfig`

And it is the `helperImage` that is used to launch the pod...

       `func (p *Provisioner) launchPod(config podConfig) (*corev1.Pod, error) {
	// the helper pod need to be launched in privileged mode. This is because in CoreOS
	// nodes, pods without privileged access cannot write to the host directory.
	// Helper pods need to create and delete directories on the host.
	privileged := true

	helperPod, err := pod.NewBuilder().
		WithName(config.podName + "-" + config.pOpts.name).
		WithRestartPolicy(corev1.RestartPolicyNever).
		WithNodeSelectorHostnameNew(config.pOpts.nodeHostname).
		WithServiceAccountName(config.pOpts.serviceAccountName).
		WithTolerationsForTaints(config.taints...).
		WithContainerBuilder(
			container.NewBuilder().
				WithName("local-path-" + config.podName).
				WithImage(p.helperImage).`

However via search of the repo code it does not seem there is any other place where `imageHelper` is set to the non default value.

So, the `imageHelper` property has to be populated from the env.

## Steps to Reproduce

- Deploy openebs char it a manner similar to this:

`
openebs_helm_args=(--set-string apiserver.image="$registry/openebs/m-apiserver" \
    --set-string provisioner.image="$registry/openebs/openebs-k8s-provisioner" \
    --set-string localprovisioner.image="$registry/openebs/provisioner-localpv" \
    --set-string localprovisioner.helperImage="$registry/openebs/openebs-tools" \
    --set-string snapshotOperator.controller.image="$registry/openebs/snapshot-controller" \
    --set-string snapshotOperator.provisioner.image="$registry/openebs/snapshot-provisioner" \
    --set-string ndm.image="$registry/openebs/node-disk-manager-amd64" \
    --set-string ndmOperator.image="$registry/openebs/node-disk-operator-amd64" \
    --set-string webhook.image="$registry/openebs/admission-server" \
    --set-string helper.image="$registry/openebs/linux-utils" \

`
where `registry` is set to a value different than `quai.io` 
- Create a PVC using the hostPath storage class
- Note the init-pvc... pod created by openebs is using an image that is pulling from `quay.io` still. ImagePullErr will be shown for the pod status

**Comment by kmova** [comment]
@mzur-hv - which version of openebs are you using?

**Comment by mzur-hv** [comment]
Sorry - (human) operator error here... what I was observing on our build server was due to a for some reason some type of a caching issue in kubernetes. Recycling the cluster now all works as expected.
Of course, I did not read the code correctly .... learning go "on the go" 😉  Applogies 🙇‍♂️

**Comment by kmova** [comment]
Awesome @mzur-hv! Thanks for updating the issue!
