### ISSUE TITLE
openebs storageclass cascading deletion

### ISSUE THREAD

**Issue by allenhaozi** [openebs/openebs#3128]
I'm using openebs-localpv-provisioner to manage my local pv

openebs-localpv-provisioner support  cascading deletion pvc when I delete associated storageclass ?

**Comment by kmova** [comment]
Hi @allenhaozi, just to confirm - do you want to delete all the OpenEBS Local PVs - if the corresponding storage class is deleted? 

Usually StorageClass is only used for creating the PV. After the PV is created, it doesn't care if the storageclass is changed or deleted.

**Comment by allenhaozi** [comment]
> Hi @allenhaozi, just to confirm - do you want to delete all the OpenEBS Local PVs - if the corresponding storage class is deleted?
> 
> Usually StorageClass is only used for creating the PV. After the PV is created, it doesn't care if the storageclass is changed or deleted.

in my scenario, one application will create a StorageClass, one application include statefset,Ingress,storageclass
I set ownerReferences to the sub resource, such as Ingress, storageclass
but pvc and pv are created automatically,  so I can not set ownerReferences to them

[https://github.com/kubernetes/kubernetes/issues/55045](https://github.com/kubernetes/kubernetes/issues/55045)

I would  like to know if OpenEBS supports it

**Comment by kmova** [comment]
Hi @allenhaozi - the support for auto-removing the PVCs as part of the Statefulset deletion is being worked on in Kubernetes. https://github.com/kubernetes/enhancements/pull/1915

Is there anyway that the operator can be enhanced to check for the PVCs created for a given storageclass and delete them before deleting the storageclass itself?

**Comment by allenhaozi** [comment]
thank u @kmova 

a temporary scheme that in my operator I will watch the Deletion of StorageClass then trigger to delete pvc

I will close this issue
