### ISSUE TITLE
Support for ReadWriteMany without using NFS

### ISSUE THREAD

**Issue by pre** [openebs/openebs#3132]
I was very surprised that `ReadWriteMany` is not possible at all with cStor. All the nice keywords, such as HA and synchronous replication, are present. But the OpenEBS website has only a sidenote that cStor is great for "stateful workloads" and the mention about needing NFS for `ReadWriteMany` is at the very bottom of everything.

Are there plans for `ReadWriteMany` with cStor? 

I'm wondering whether OpenEBS + cStor could really be an alternative for Ceph + Rook - without RWM it can't be. 

Discussion in Kubernetes Slack #openebs 
https://kubernetes.slack.com/archives/CUAKPFU78/p1600670862024400 

** 

Our use case is that we want to migrate existing VM based workloads to Kubernetes. Many workloads involve applications such as Wordpress and Drupal. These are designed and implemented in such a way that they need write access to storage from each application pod.

For example: A Wordpress end-user may install a Wordpress Plugin from the Wordpress Admin UI. Installing a plugin writes PHP code to disk. Later on, using the site with all the WP plugins involves thousands of sequential `require()` :s which needs low latency from the disk. Using an object store, CDN or even bundling stuff into a Docker image would all be nice. But we don't have control over the end-users and our focus is in the lift-and-shift from traditional VMs to Kubernetes.

Ceph + Rook provides RWM + low latency with near disk performance without NFS involved: https://docs.ceph.com/en/latest/cephfs/mount-using-kernel-driver/

Requiring NFS for `ReadWriteMany` will introduce latency for sequential small reads and there will be no way around it. 
Having `ReadWriteMany` for cStor with low latency needs a solution which does not involve NFS.

**Comment by pre** [comment]
Discussion in Kubernetes Slack #openebs 
https://kubernetes.slack.com/archives/CUAKPFU78/p1600670862024400

**Comment by kenotsolutions** [comment]
workaround for this issue use StatefulSet instead of Deployment. Use volumeClaimTemplates for the StatefulSet so it would create many PVC for each node.

**Comment by pre** [comment]
> workaround for this issue use StatefulSet instead of Deployment.

That is a solution for another problem, however, it is not a workaround to this issue. 

This issue about having a *shared* writable volume mounted as `ReadWriteMany`  for multiple Pods. Given Pod A and Pod B, any write to the shared volume by Pod A must be immediately available to Pod B (and vice-versa). 

Using a StatefulSet with multiple PersistentVolumeClaims means that each Pod has a volume of its own. Hence, writing to that volume by Pod A is not available to Pod B.

**Comment by ifalex** [comment]
Interested also in the same use case scenario. In order to be a good alternative for ceph/rook ReadWriteMany is a necessity.

**Comment by kmova** [comment]
Working on a prototype to provide a provisioner that helps with RWX volumes on top of OpenEBS RWO volumes. Will be sharing the details shortly.

**Comment by jnsrikanth** [comment]
Hi  Kiran @kmova do you have any further updates with regards to the ReadWriteMany for OpenEBS + cStor ? Is there an option for doing RWM using OpenEBS + Local Persistent Volumes? 
What other options do we have to do ReadWriteMany (RWM) under the OpenEBS basket especially for a single Node K8S Cluster? Any inputs will be highly appreciated.

Let me know.

-Srikanth

**Comment by kmova** [comment]
@jnsrikanth -- for single node k8s, you can use the RWO volume and it works with all the pods. RWO actually means access from a single node.

**Comment by kmova** [comment]
Still developing the dynamic provisioner. The draft code I am working on is at : https://github.com/kmova/dynamic-nfs-provisioner

**Comment by kmova** [comment]
In the recent releases, the https://github.com/openebs/dynamic-nfs-provisioner has gained traction as a simplified way of setting up NFS over any type of OpenEBS block volumes. 

However, as mentioned in the issue description above, there may be need for supporting RWX without NFS. 

Keep this issue open to be considered for the Mayastor engine for future.

**Comment by kmova** [comment]
https://github.com/openebs/dynamic-nfs-provisioner has been tested with Mayastor as well.
