### ISSUE TITLE
Add support to fetch block size and drive type of partitions from parent device

### ISSUE THREAD

**Issue by akhilerm** [openebs/openebs#3134]
## Description

Currently, NDM fetches the logical / physical blocksize and hardware sector size of the disks from sysfs. But this is applicable only for parent disks as partitions does not have a `<syspath>/queue` directory with the block sizes and drive types. But for partitions this data will be equal to that of the parent disk. Therefore the [sysfs probe](https://github.com/openebs/node-disk-manager/blob/287edbe59a6a9a48d897799c204822aa79afe29d/cmd/ndm_daemonset/probe/sysfsprobe.go#L92), should be modified to fetch the details of partitions from the parent disk.

## Context

Availability of block sizes and drive type on the blockdevice resource for partitions helps user to determine and group the devices that should be used for a pool for optimal performance.

## Possible Solution

If the `deviceType` of a blockdevice is partition, then sysfs probe should try to fetch the blocksize of the parent disk from sysfs rather than information of the partition.

**Comment by divya144** [comment]
@akhilerm  I would like to work on this issue.

**Comment by akhilerm** [comment]
Thanks @divya144 for taking this up.

[This](https://github.com/openebs/node-disk-manager/blob/0baecdcae8929b6ddc6f850ca5c47eb9150af025/cmd/ndm_daemonset/probe/sysfsprobe.go#L85) is the method that need to be changed to get the relevant information.

**Comment by akhilerm** [comment]
@divya144 I have assigned the issue to you.

**Comment by akhilerm** [comment]
@divya144 Did you get a chance to look into this issue.

If you need any help on this, you can find the developers in the openebs-dev channel in [kubernetes workspace](https://openebs.io/community/).

**Comment by akhilerm** [comment]
@divya144 Are there any updates on this issue?

**Comment by akhilerm** [comment]
@divya144 Will it be possible for you to work on this issue. If not, I can unassign and free up the issue for others to take up.

**Comment by Z0Marlin** [comment]
@akhilerm is anyone currently working on this? If not, I would like to give this issue a try.

**Comment by akhilerm** [comment]
Sure @Z0Marlin . you can take it up. I will assign this issue to you.
