### ISSUE TITLE
Add support for updating mountpoint and capacity of blockdevices without NDM pod restart

### ISSUE THREAD

**Issue by akhilerm** [openebs/openebs#3135]
## Description

BlockDevice resource have fields for mountPoint and capacity. These fields are updated either when the resource is created or the NDM pod is restarted. If the device is mounted while NDM pod is running, the blockdevice resource does not get updated with the new mounpoint. 

Similar, is the case with device capacity. . Change in capacity is not reflected on the blockdevice resource unless the NDM pod is restarted or the device is disconnected and reconnected. 

These fields should also be updated whenever there is a change on the host machine.

## Context

Cloud disks can be easily resized, but the size will not be reflected immediately. This causes issue with provisioning as the blockdevice will have the older size and NDM operator may not claim the device due to insufficient capacity.  This issue can be resolved if the capacity / mountpoint changes are immediately propagated to the blockdevice resource

## Possible Solution

The fields are not updated because NDM relies on udev events for changes to the disks. But udev events are not generated for capacity change and when a device is mounted.

Two possible solutions:
1. Create a parser for dmesg, and notify NDM whenever a capacity change or mountpoint change occurs on the system and update it to etcd
2. Use inotify on `procfs` (for mountpoint change) and `sysfs`(for capacity change). Thus NDM can know of changes to the filesystem and update it accordingly to the blockdevice resource.

**Comment by harshthakur9030** [comment]
@akhilerm we cannot use inotify on procfs and sysfs. https://linux-fsdevel.vger.kernel.narkive.com/u0qmXPFK/inotify-sysfs . 

Polling is the other way to do it.

**Comment by akhilerm** [comment]
@harshthakur9030  What about the dmesg parsing ?  There are no libraries that does it at the moment, but we have to check feasibility on all options.
Have to see the pros and cons for:
1. Polling procfs and sysfs
2. dmesg parsing

**Comment by akhilerm** [comment]
kmesg parser used in node-problem-detector can be used for detecting mountpoint and capacity changes.

**Comment by Z0Marlin** [comment]
Seems like messages aren't generated in `dmesg` when mounts change (tried locally on Ubuntu 20.10, Linux 5.8.0-45-generic, x86_64) .
For monitoring changes to mounts, `epoll` on the mounts file in procfs can be used. Here is [ sample code](https://gist.github.com/Z0Marlin/b68bf83c15378afff585f7104ae7456e) to do the same.

**Comment by RealHarshThakur** [comment]
Weird about the `dmesg` . I think the polling method is easier and we should go with it provided :
* There are no other uses cases for which we need the `kmesg` library of node-problem-detector
* Polling interval should be made configurable and it should be able to poll on demand with CLI.
* Would also be useful to check resource consumption of polling with pprof

**Comment by Z0Marlin** [comment]
> Weird about the `dmesg` . I think the polling method is easier and we should go with it provided :
> 
> * There are no other uses cases for which we need the `kmesg` library of node-problem-detector
> * Polling interval should be made configurable and it should be able to poll on demand with CLI.

Wouldn't waiting for change events be better than continuously polling in a set interval?

> * Would also be useful to check resource consumption of polling with pprof

Definitely agree with this. In fact, we should try this for the alternatives too and compare the results.

**Comment by RealHarshThakur** [comment]
@Z0Marlin I looked at the gist and the `EpollWait` function takes milliseconds as an arg, so we're still polling I guess?

**Comment by Z0Marlin** [comment]
> @Z0Marlin I looked at the gist and the `EpollWait` function takes milliseconds as an arg, so we're still polling I guess? 

The milliseconds arg is for the timeout. Basically how long we should wait for events to occur before continuing. It can be set to -1 if we want to block the thread till we recieve any event. Even if we do give a timeout, I would still not consider this as polling.
I also get a little bit clarity on how polling would work. Specifically, if we were polling in fixed intervals, how exactly would we know that the mounts have changed? By reading the the mounts again? Or is there a different way to go about it?

**Comment by RealHarshThakur** [comment]
Ah, thanks for clarifying that. I read more about [epoll](https://man7.org/linux/man-pages/man7/epoll.7.html) here and got a clear picture now. Definitely, picking event based over polling is the way to go so please discard that :smile:  . Also, it MIGHT be valuable to other storage engines if NDM produced a Kubernetes events about the change in block device size(or more cases). From implementation perspective, I understand that we're watching for any changes in `/proc/mounts` ,   so can we differentiate if the filesystem has changed or block device size? The ideal end goal would be for us to have a standalone package in NDM which  would send an event over a channel based on the what exactly happened to block devices(size change or filesystem change. etc)  I think

**Comment by Z0Marlin** [comment]
Leveraging Kubernetes events sounds interesting. But I'm still trying to find out how we can detect changes to blockdevice capacity. While using `epoll` on `/proc/mounts` works for detecting changes in mount points, it can't be used to detect disk capacity changes. One way to go about it, as mentioned in previous comments, is to parse messages in `dmesg`. Unfortunately, I haven't been able to find any other way to achieve this. 
Polling the queue sysfs files for every blockdevice is probably another way we can check for changes. This wouldn't be as expensive as polling `/proc/mounts` as these files return single line values which will be quite easy to parse, as compared to the large list of mounts in `/proc/mounts`. Also this way, we can detect changes in not just the capacity but other attributes too. @akhilerm @RealHarshThakur what do you think? Also, are guys aware of any alternatives for this?

**Comment by RealHarshThakur** [comment]
I think we can just check ` /proc/partitions` for size changes. But the bigger problem to solve might be, we would get an event back on any change in `/proc/mounts`, so how would we determine if it was  because of mount point change or filesystem change?
Maybe, we can do some sort of combination of all this, for instance: if there's a change in `/proc/partitions`, we get an event back, so we can now run cases : check the size of block devices in sysfs ( `/sys/class/block/sdX/size`  )  or check if there's a new partition for a particular block device in sysfs. Essentially , just using the `epoll` as an event mechanism instead of polling sysfs and then only checking sysfs when we know for sure that there's a change

**Comment by akhilerm** [comment]
> Specifically, if we were polling in fixed intervals, how exactly would we know that the mounts have changed? By reading the mounts again? Or is there a different way to go about it?

@Z0Marlin If you think in terms of how NDM is coded currently, we have an internal cache kind of structure for each device. This struct contains all the information about the device in memory. May be you can compare the mountpoint and filesystem for the device with this struct and thus you will be able to identify what has changed, and update only those fields in the BlockDevice kubernetes resource. 
Another idea would be to just update the mountpoint and filesystem of every device with whatever is present in `/proc/mounts`, but that will be an expensive operation and will involve too many API calls if the host has large no of disks connected.


> it MIGHT be valuable to other storage engines if NDM produced a Kubernetes events about the change in block device size

@RealHarshThakur Definitely yes. Whenever we find that something has changed on the device, we can update it in the blockdevice resource and at the same time, generate a kubernetes event for the blockdevice. So , when a particulat blockdevice resource is described we can see events like `size changed from 1Gi to 2Gi` , `device mounted at /var/lib`, `device unmounted` etc.


One caveat with using epoll on sysfs directory is, we will have to create `epoll` on `size` file of all disks. This issue is not present in case of checking mountpoints as there will always be only one file.  


> The ideal end goal would be for us to have a standalone package in NDM which would send an event over a channel based on the what exactly happened to block devices(size change or filesystem change. etc)

@RealHarshThakur @Z0Marlin Yes, This is the ultimate goal. Just like how our udev package sends info on a channel about which blockdevice was added or removed, this standalone package should send info over a channel about which blockdevice was mounted/unmounted/formatted with a filesystem etc.


WDYT if we use epoll for all mount/filesystem changes and dmesg for the size changes?

**Comment by RealHarshThakur** [comment]
@akhilerm for size changes, we can use epoll on  `/proc/partitions` instead . If we use this, we'll only receive event if change in partitions or change in size. What we can do is : we check the size of block device  in sysfs only when we receive an event. This is better than us polling sysfs .

**Comment by Z0Marlin** [comment]
@RealHarshThakur  Is checking `/proc/partition` the correct way to look for changes to device capacity? IMO if we were only concerned with partitions it would work, but since we also have blockdevices for parent disks, `/proc/partition` wouldn't change if the disk size increases. Please do correct me here if I'm missing something.

**Comment by Z0Marlin** [comment]
I agree. For checking size changes, epoll on `/proc/partitions` would be a better approach.

**Comment by akhilerm** [comment]
@Z0Marlin Can you verify that `/proc/partitions` reflects size changes for all types of blockdevices  that are [supported](https://github.com/openebs/node-disk-manager/blob/master/blockdevice/blockdevice.go#L207-L225) by NDM.

**Comment by Z0Marlin** [comment]
@akhilerm @RealHarshThakur So `/proc/partitions` did get updated when a changed the size of a disk on my machine. But before I could continue to check for the remaining supported devices, I found out that we cant use `epoll` on `/proc/partitions`. When polling the mounts file, [this function](https://elixir.bootlin.com/linux/latest/source/fs/proc_namespace.c#L21) is called at some point which returns the events `EPOLLERR` and `EPOLLPRI` when the mounts have changed. But in the case of `/proc/partitions` its a bit different. Polling this file the function that gets triggered is [pipe_poll](https://elixir.bootlin.com/linux/latest/source/fs/pipe.c#L636). This function is for Linux pipes. It always returns `EPOLLIN` and `EPOLLOUT` for `/proc/partitions` and doesn't have any mechanism to check if there have been any changes. 

I think parsing `dmesg` would be the way to go. The other way will be to poll the sysfs files, but this will have to be done for each and every blockdevice detected by the ndm, which may turn out to be a bit costly.

**Comment by RealHarshThakur** [comment]
Ah..that's sad. So in the above conversation, we were talking about this [library](https://github.com/kubernetes/node-problem-detector/tree/master/pkg/systemlogmonitor) . It seems to be standalone . I don't think you can pass `/dev/sdX` though.

**Comment by akhilerm** [comment]
@RealHarshThakur For the library in node-problem-detector, you dont need to pass the device path, it parses the complete dmesg.

**Comment by RealHarshThakur** [comment]
@akhilerm how would we know about a change in particular block device? I mean , how would we filter out the results ?

**Comment by akhilerm** [comment]
Based on the path, suppose the library will give all capacity changes for all devices, and whenever we get an event for capacity change, we will check if the device is something that we are interested in and process it. Similar in ways how to we check on device add/remove.
