### ISSUE TITLE
Add meta information to openebs created partitions

### ISSUE THREAD

**Issue by akhilerm** [openebs/openebs#3136]
## Description

OpenEBS NDM, as part of unique identification creates a partition on the disk, if its virtual. But this partition does not contain any information about who created the partition. 
A label or partition name should be added to the GPT Table while creating the partition so that it becomes easier to identify NDM created partitions.

## Context

For debugging purpose and to maintain some identifiable information on the disk, that the partition table was written by OpenEBS NDM.

## Possible Solution

One solution is to add a partition name while creating GPT table. The name can be added [here](https://github.com/openebs/node-disk-manager/blob/287edbe59a6a9a48d897799c204822aa79afe29d/pkg/partition/partition.go#L108).

Another possible solution would be to add any labels to the partition table. For this the partition table structure needs to be explored and check if there are any blocks reserved for random data.

**Comment by avats-dev** [comment]
@akhilerm I want to work on this. I'm still studying the codebase as much as I can get by. I might need some help along the way, thanks:tada:.

**Comment by akhilerm** [comment]
Sure @avats-dev . You can work on it.

**Comment by akhilerm** [comment]
@avats-dev [This](https://github.com/openebs/node-disk-manager/blob/287edbe59a6a9a48d897799c204822aa79afe29d/pkg/partition/partition.go#L108) is the code block that deals with partition. The label for meta information can be added here

**Comment by akhilerm** [comment]
@avats-dev I have assigned this issue to you.

**Comment by avats-dev** [comment]
Thanks @akhilerm , will open a PR with changes soon. :tada:
