### ISSUE TITLE
Flaky Test: replace reflect.DeepEqual with "github.com/google/go-cmp/cmp"

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3143]
## Description

The existing test in `cspc_generator_test.go`, try to replace `reflect.DeepEqual()` with "github.com/google/go-cmp/cmp" package to fix the flaky test.

Here on line number L187 tests uses the reflect.DeepEqual() which can be replaced with  `cmp.Equal(...)` to handle the comparison of interface types , once changes are done PR should be raised in https://github.com/openebs/upgrade repo.

https://github.com/openebs/upgrade/blob/2eb9a3d3e3c707f34ff1939312d6bea2e5c1efac/pkg/migrate/cstor/cspc_generator_test.go#L187

for example :
https://github.com/openebs/upgrade/blob/2eb9a3d3e3c707f34ff1939312d6bea2e5c1efac/pkg/migrate/cstor/cstorvolumepolicy_test.go#L203

## Expected Behavior
Above change should fix the flaky test

## Current Behavior
Tests gets failed in some test runtimes to above mentioned issue.

**Comment by infiniteoverflow** [comment]
I would like to work on this issue :)

**Comment by ShubhamSood1406** [comment]
@prateekpandey14 Can I contribute to it?

**Comment by prateekpandey14** [comment]
@infiniteoverflow  are you still intrested to work in this issue.

**Comment by infiniteoverflow** [comment]
Yes i am interested. Thank you 💯

**Comment by infiniteoverflow** [comment]
@prateekpandey14 I have raised a PR for the same : https://github.com/openebs/upgrade/pull/58

**Comment by shubham14bajpai** [comment]
This issue was addressed in the PR https://github.com/openebs/upgrade/pull/58
