### ISSUE TITLE
Add PULL REQUEST and ISSUE TEMPLATES for the "openebs/upgrade" repo 

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3144]
## Description
Add PULL REQUEST and ISSUE TEMPLATES for the https://github.com/openebs/upgrade repo

## Possible Solution
Check templates https://github.com/openebs/cstor-csi/tree/master/.github for the idea for configuring the templates.

**Comment by Hard-Coder05** [comment]
@prateekpandey14 I would like to work on this issue!

**Comment by prateekpandey14** [comment]
Great @Hard-Coder05 , assigned  :+1:

**Comment by Hard-Coder05** [comment]
@prateekpandey14 I have made the PR. Do review it once!

**Comment by shubham14bajpai** [comment]
This issue was addressed in the PR https://github.com/openebs/upgrade/pull/54
