### ISSUE TITLE
Update the main README with info and link upgrade & migration docs

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3145]
## Description
Update the main README with info and link upgrade & migration docs in  https://github.com/openebs/upgrade repo.

Create links for the required Upgrade and Migrations docs from the [docs](https://github.com/openebs/upgrade/tree/master/docs) folder from the [Upgrade](https://github.com/openebs/upgrade) repo

## Possible Solution
Refer https://github.com/openebs/openebs/blob/master/k8s/upgrades/README.md for some ideas

**Comment by Naveenkhasyap** [comment]
Hi @prateekpandey14 , interested to take this up, 
one query do we need to have all the info from upgrade & migration docs or can we give overview for them and give hyperlink which points to these docs readme.

**Comment by prateekpandey14** [comment]
We can given overview and give hyperlink

**Comment by ShubhamSood1406** [comment]
@prateekpandey14 Can I also contribute to it?

**Comment by HarshalGoyal** [comment]
@prateekpandey14 I would like to like to work on this .

**Comment by Naveenkhasyap** [comment]
> 
> 
> thanks @Naveenkhasyap , we can given overview and give hyperlink

working on it.

**Comment by shubham14bajpai** [comment]
@ShubhamSood1406 if you are still interested you can take up this issue https://github.com/openebs/openebs/issues/3158

**Comment by ShubhamSood1406** [comment]
> @ShubhamSood1406 if you are still interested you can take up this issue #3158

Yes I can do that, can you assign me that.

**Comment by shubham14bajpai** [comment]
> > @ShubhamSood1406 if you are still interested you can take up this issue #3158
> 
> Yes I can do that, can you assign me that.

@ShubhamSood1406 Another contributor has already raised a PR. I will try to find some other issue for you.

**Comment by ShubhamSood1406** [comment]
> > > @ShubhamSood1406 if you are still interested you can take up this issue #3158
> > 
> > 
> > Yes I can do that, can you assign me that.
> 
> @ShubhamSood1406 Another contributor has already raised a PR. I will try to find some other issue for you.

Yes please consider me if you find some other issue.

**Comment by jayeshmann** [comment]
this is still open?

**Comment by shubham14bajpai** [comment]
> this is still open?

The PR is already raised by another contributor.

**Comment by shubham14bajpai** [comment]
This issue was addressed by the PR openebs/upgrade#57
