### ISSUE TITLE
Support for multi-arch docker builds in openebs/jiva repo

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3146]
## Description
Support for muti-arch container images for https://github.com/openebs/jiva repo using docker [buildx docs](https://docs.docker.com/buildx/working-with-buildx/)
[buildx CLI](https://github.com/docker/buildx)

## Context
To support different arch

## Possible Solution
Refer PR https://github.com/openebs/upgrade/pull/32/files for more details.

**Comment by ronaldyuwandika** [comment]
Hello, @prateekpandey14 I would try work on this issue :)
