### ISSUE TITLE
NDM Seachest probe works only on SCSI devices

### ISSUE THREAD

**Issue by akhilerm** [openebs/openebs#3147]
## Description

OpenEBS NDM uses [openSeachest](https://github.com/seagate/openseachest) to get some disk information like disk temperature, total read/write bytes, percentage endurance etc. But this is working only for SCSI devices within NDM. The cgo implementation of getting the device information [here](https://github.com/openebs/node-disk-manager/blob/287edbe59a6a9a48d897799c204822aa79afe29d/pkg/seachest/seachest.go#L74) does not handle cases of SATA and NVMe drives (these are handled separately in seachest)

## Expected Behavior

While using the `openSeachest_Basics` binary directly to query the information of a SATA SSD, the following information is retrieved 
```
$ sudo ./openSeaChest_Basics -d /dev/sda -i
/dev/sg0 - CT500MX500SSD1 - 1926E2105248 - ATA
	Model Number: CT500MX500SSD1
	Serial Number: 1926E2105248
	Firmware Revision: M3CR023
	World Wide Name: 500A0751E2105248
	Drive Capacity (GB/GiB): 500.11/465.76
	Native Drive Capacity (GB/GiB): 500.11/465.76
	Temperature Data:
		Current Temperature (C): 38
		Highest Temperature (C): 52
		Lowest Temperature (C): 0
	Power On Time:  62 days 9 hours 
	Power On Hours: 1497.00
	MaxLBA: 976773167
	Native MaxLBA: 976773167
	Logical Sector Size (B): 512
	Physical Sector Size (B): 4096
	Sector Alignment: 0
	Rotation Rate (RPM): SSD
	Form Factor: 2.5"
	Last DST information:
		Time since last DST (hours): 718.00
		DST Status/Result: 0x0
		DST Test run: 0x1
	Long Drive Self Test Time:  30 minutes 
	Interface speed:
		Max Speed (Gb/s): 6.0
		Negotiated Speed (Gb/s): 6.0
	Annualized Workload Rate (TB/yr): 17.68
	Total Bytes Read (TB): 1.95
	Total Bytes Written (TB): 1.07
	Encryption Support: Full Disk Encryption
	Cache Size (MiB): Not Reported
	Percentage Used Endurance Indicator (%): 7.00000
	Read Look-Ahead: Enabled
	Write Cache: Enabled
	SMART Status: Good
	ATA Security Information: Supported, Frozen
	Firmware Download Support: Full, Segmented, Deferred, DMA
	Specifications Supported:
		ACS-3
		ACS-2
		ATA8-ACS
		ATA/ATAPI-7
		ATA/ATAPI-6
		ATA/ATAPI-5
		ATA/ATAPI-4
		SATA 3.2
		SATA 3.1
		SATA 3.0
		SATA 2.6
		SATA 2.5
		SATA II: Extensions
		SATA 1.0a
		ATA8-AST
	Features Supported:
		Sanitize
		SATA NCQ
		SATA Device Sleep Preservation
		SATA Software Settings Preservation [Enabled]
		SATA Device Initiated Power Management [Enabled]
		Power Management
		Security
		SMART [Enabled]
		48bit Address
		APM [Enabled]
		GPL
		SMART Self-Test
		SMART Error Logging
		AMAC
		TRIM
		SCT Feature Control
		SCT Data Tables
		Host Logging
```
This is the actual data reported by the disk

## Current Behavior

While using the library via NDM, the following output is obtained.
```
I0924 14:54:25.993546   24421 seachest.go:223] Device is : /dev/sda
I0924 14:54:25.993588   24421 seachest.go:224] Current temperature is 0
I0924 14:54:25.993611   24421 seachest.go:225] Lowest temperature is 0
I0924 14:54:25.993634   24421 seachest.go:226] Highest temperature is 0
I0924 14:54:25.993656   24421 seachest.go:227] Capacity is 500107861504
I0924 14:54:25.993708   24421 seachest.go:228] Total bytes read is 0
I0924 14:54:25.993733   24421 seachest.go:229] Total bytes written is 0
I0924 14:54:25.993747   24421 seachest.go:230] Device utilization rate is 0
I0924 14:54:25.993760   24421 seachest.go:231] Endurance used is 0
I0924 14:54:25.993778   24421 seachest.go:141] metrics data obtained from seachest library
```
Only capacity is reported, all other fields are either 0, or marked as `Not Reported`.

## Possible Solution

The [`SeachestBasicDiskInfo()`](https://github.com/openebs/node-disk-manager/blob/287edbe59a6a9a48d897799c204822aa79afe29d/pkg/seachest/seachest.go#L74) method currently fetches only SCSI Information. This should be modified such that appropriate method is called depending on the device type. [This](https://github.com/openebs/opensea-operations/blob/3f0e4490152e5f56a75e21560a351fdc0dddacef/src/drive_info.c#L7029) is how `openSeachest_Basics` binary fetches the information. A similar logic should be added to NDM- seachest pkg to query devices based on the device type.

## Steps to Reproduce

- Use a k8s cluster with non SCSI drives (SATA disks) attached to the node.
- Run OpenEBS NDM 2.1, with seachest probe enabled in the [configmap](https://github.com/openebs/charts/blob/c3351b3ac95b4105f069d44ee59ac4f7d5498240/openebs-operator.yaml#L432).
The NDM daemon logs will show that seachest is not reporting values for the SATA disk

## Your Environment

* `kubectl get nodes`:
```
NAME         STATUS   ROLES    AGE    VERSION
master-ak1   Ready    master   145d   v1.18.3
worker-ak1   Ready    <none>   145d   v1.18.0
worker-ak2   Ready    <none>   145d   v1.18.0
```
* OS (from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (from `uname -a`):
```
Linux Worker1 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by avinashdhinwa** [comment]
@akhilerm I would like to pick this issue

**Comment by akhilerm** [comment]
Thanks @avinashdhinwa for taking this up. I will assign this issue to you.

If you have any queries or doubts regarding the implementation of this or in general, you can get in touch with the developers in the [`#openebs-dev`](https://kubernetes.slack.com/archives/C015124PVTL) in [kuberentes slack](https://openebs.io/community)

**Comment by akhilerm** [comment]
Hi @avinashdhinwa , is there an update on this issue?

**Comment by akhilerm** [comment]
@avinashdhinwa I have unassigned the issue due to inactivity.

The issue is now free to take up.

**Comment by akhilerm** [comment]
This issue is still open and need to include non--SCSI devices also while fetching information

**Comment by dhess** [comment]
Any plans to resurrect this work?
