### ISSUE TITLE
OpenEBS plugin for Spotify Backstage

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#3148]
[Backstage](https://backstage.io/docs/overview/what-is-backstage) is an open platform for building developer portals. Powered by a centralized service catalog, Backstage restores order to your microservices and infrastructure. So your product teams can ship high-quality code quickly — without compromising autonomy.

It allows portals to be built for managing any kind of underlying infra/components/services. It looks like it has a growing ecosystem of plugins being built.

Proposal here is to build a plugin for OpenEBS plugin for Backstage, allowing users to manage and observe OpenEBS configuration, persistent volumes along with applications backed by OpenEBS, monitor health and perform second day operations.

**Comment by siddhi523** [comment]
**Proposal here is to build a plugin for OpenEBS plugin for Backstage** What's the meaning of this line? Can you elaborate a bit I researched about Backstage but that wasn't enough to get started.
