### ISSUE TITLE
Cannot create CSPC on private GKE cluster

### ISSUE THREAD

**Issue by wataruian** [openebs/openebs#3149]
Hi All,

I was attempting to create a `CStorPoolCluster` in a private GKE cluster. I was able to create one with the public cluster. But when trying to create on private cluster I am getting:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded
```

Is private cluster not currently supported?

**Comment by prateekpandey14** [comment]
@wataruian can you check if there need to add any firewall rules https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules

**Comment by prateekpandey14** [comment]
@wataruian does adding firewall rules helped you to run the admission webhook in Private GKE cluster ?

**Comment by wataruian** [comment]
Yes. I just finished doing what you suggested. It works. Thanks!

**Comment by wataruian** [comment]
Closing this now. Thank you very much @prateekpandey14
