### ISSUE TITLE
[developer documentation] provide instructions for community to suggest new labels

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#315]
https://github.com/openebs/openebs/blob/master/contribute/issues.md

Update the above document with instructions on how community can suggest new labels or categories.

**Comment by thepriefy** [comment]
Hi,
Do you have any detail about how to suggest new labels or categories?

**Comment by kmova** [comment]
Enumerating all the labels doesn't sound like a great idea. Instead we should focus on the main categories.
