### ISSUE TITLE
stable/nfs-server-provisioner doesn't exist anymore

### ISSUE THREAD

**Issue by briankmatheson** [openebs/openebs#3150]
stable repo is long gone.  Can we update this doc to point to the new nfs server we maintain?

bmath@timesink:~/maya/kops/test350.bob.bmath.nyc$ helm install nfs stable/nfs-server-provisioner
Error: failed to download "stable/nfs-server-provisioner" (hint: running `helm repo update` may help)

**Comment by kmova** [comment]
The earlier stable/nfs-server-provisioner has moved to: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

Also, there is an option now within OpenEBS to use NFS via: https://github.com/openebs/dynamic-nfs-provisioner
