### ISSUE TITLE
Support for multi-arch docker builds in openebs/jiva-csi and openebs/jiva-operator repo

### ISSUE THREAD

**Issue by payes** [openebs/openebs#3151]
## Description
Support for muti-arch container images for https://github.com/openebs/jiva-csi and https://github.com/openebs/jiva-operator repo using docker [buildx docs](https://docs.docker.com/buildx/working-with-buildx/)
[buildx CLI](https://github.com/docker/buildx)

## Context
To support different arch

## Possible Solution
Refer PR https://github.com/openebs/upgrade/pull/32/files for more details.

**Comment by ronaldyuwandika** [comment]
Hello, @payes I would try to work on this :)

**Comment by prateekpandey14** [comment]
Sure @ronaldyuwandika
