### ISSUE TITLE
RawFile LocalPV: allow to change default mount path using an ENV

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3152]
## Description
Enhance [RawFile LocalPV repo](https://github.com/openebs/rawfile-localpv/)  CSI driver to change the default data-dir mount path using an ENV or chart template parameter to make it configurable. 

The data directory used for creating the sparse file is hardcoded to "/var/csi/rawfile" in the task template.
https://github.com/openebs/rawfile-localpv/blob/master/templates/task.yaml#L14

Similar to image_tag and image_repository, the data-dir also should be configurable via the env variable.

Note: If you want to get started on setting up rawfile and checking how it works, you can follow the helm3 instructions in the repo or use the YAML instructions available here:

https://github.com/kmova/bootstrap/blob/master/openebs-localpv/rawfile/setup.md

**Comment by ronaldyuwandika** [comment]
i would try to fix this issue :)

**Comment by prateekpandey14** [comment]
Sure thanks @ronaldyuwandika
