### ISSUE TITLE
Add badges to the openebs/upgrade README

### ISSUE THREAD

**Issue by shubham14bajpai** [openebs/openebs#3158]
## Description

Add the following badges to the https://github.com/openebs/upgrade  repo README.
- Build Status 
- Go Report 
- codecov 
- Slack 

## Possible Solution

You can take reference from the README of https://github.com/openebs/node-disk-manager/blob/master/README.md

**Comment by sparkingdark** [comment]
Want to work assign this to me

**Comment by sparkingdark** [comment]
Thanks for assigning this to me.

**Comment by sparkingdark** [comment]
Hello I think the upgrade project has no codecov account link.So that's it is showing unknown.

**Comment by shubham14bajpai** [comment]
> Hello I think the upgrade project has no codecov account link.So that's it is showing unknown.

It is okay. The codecov is still not enabled it will get updated once we enable it. Thanks a lot for the PR.

**Comment by sparkingdark** [comment]
Awesome love to collaborate.

**Comment by adithyaakrishna** [comment]
@prateekpandey14 Would love to work on this!

**Comment by 3scava1i3r** [comment]
is this issue completed or can i work on this one?

**Comment by SahilSayani** [comment]
HI I AM STARTING OUT ON OPEN SOURCE AND ID LIKE TO TRY THIS ISSUE , can I please work on it?

**Comment by shubham14bajpai** [comment]
This issue was addressed by the PR https://github.com/openebs/upgrade/pull/55
