### ISSUE TITLE
Suggest better format for commit messages as post commit hooks

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#316]
Starting a culture is an easy thing, maintaining it for years to come is difficult.
As we try to formalize our commit messages with issue #289 ensure that if a poorly formatted commit gets removed.
Take a look at some awesome github integrations which can make it happen. 
It should ideally be suggestive for first few months and later become enforcing.
After #289 is fixed, it'll be great if we can force a consistent styling by 2018.

**Comment by prateekpandey14** [comment]
We have added the contributor docs for better commit message.. so closing this
