### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by lambda2** [openebs/openebs#3161]
## Description
As a native French speaker, I would like to add a french translation of the README and the contributing guide.

## Context
I think it would be great for french speakers to have at least a README in their native language. Also, several translation in other languages already exists.

## Possible Solution
If it's okay, I can open a PR for french translations of the README and the contributing guide.

**Comment by KarenEfereyan** [comment]
I'd love to see what you end up with. Maybe I can add a Yoruba translation

**Comment by romain325** [comment]
Can I be assigned on this on ? 
I can do it as a native french speaker :)
