### ISSUE TITLE
Adding Hindi translation

### ISSUE THREAD

**Issue by iamrajiv** [openebs/openebs#3163]

**Comment by ShubhamSood1406** [comment]
@iamrajiv Can you explain what I have to do I this issue?

**Comment by Aarush-Goyal** [comment]
@iamrajiv Hi can I work on this?

**Comment by iamrajiv** [comment]
@ShubhamSood1406 @Aarush-Goyal I am working on it and have already made PR #3165 on this.

**Comment by prateekpandey14** [comment]
Not an valid issue, closing this

**Comment by Sumindar** [comment]
Is this issue valid?

**Comment by gargeesuresh** [comment]
Can I work on this?

**Comment by prateekpandey14** [comment]
@gargeesuresh PR has been raised by the Rajiv and its under review.
