### ISSUE TITLE
DOCS: Add gujarati translations

### ISSUE THREAD

**Issue by aryanrawlani28** [openebs/openebs#3171]
## Description
Add translations for the Gujarati language.

## Context
There are several translations already available. Gujarati has 50M+ users, so I think this is a good language to get translations to support.

## Possible Solution
PR: https://github.com/openebs/openebs/pull/3172

**Comment by divyhshah** [comment]
Hey can you please assign this to me

**Comment by prateekpandey14** [comment]
Not an valid issue, closing this

**Comment by aryanrawlani28** [comment]
@prateekpandey14 I saw a contribution being made for the french language, so I followed. That was merged too. Any particular reason why localisations are not "valid"?

**Comment by prateekpandey14** [comment]
@aryanrawlani28 there is no particular reason, adding all the local languages is bit of overwhelming for the user to read.
Hacktoberfest is all about making a valid contribution, so i will suggest please pick the issue from the [List](https://github.com/openebs/openebs/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest+label%3A%22good+first+issue%22) for a good contribution.
For any help you can join the #openebs [slack](https://openebs.io/community) channel as well.

**Comment by aryanrawlani28** [comment]
@prateekpandey14 Overwhelming for the user to read? The inverse is actually true, a user who is overwhelmed by the project size can find the introductory docs in their native language. Well, not really up to me to decide. If you didn't want localizations, you should've mentioned it earlier so everyone wouldn't have wasted time, including me. And you did accept french, so I don't know what to say.

**Comment by kmova** [comment]
I tend to agree with @aryanrawlani28 on adding missing translations.
