### ISSUE TITLE
Adding Nepali language 

### ISSUE THREAD

**Issue by AshishMhrzn10** [openebs/openebs#3198]
## Description
I want to add Nepali language .
I added files CONTRIBUTING.np.md and README.np.md where I added the Nepali language translations for both CONTRIBUTING.md and README.md.

**Comment by AshishMhrzn10** [comment]
#3185

**Comment by AshishMhrzn10** [comment]
> ## Description
> I want to add Nepali language .
> I added files CONTRIBUTING.np.md and README.np.md where I added the Nepali language translations for both CONTRIBUTING.md and README.md.

I already created a pull request on this issue. Please check #3185

**Comment by prateekpandey14** [comment]
Not an valid issue , closing this
