### ISSUE TITLE
How to upgrade to Vagrant 1.9.1 from any older version on Ubuntu 16.04

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#32]
### Note: First remove the older version of vagrant.
1. `sudo apt-get remove --auto-remove vagrant`
2. `rm -r ~/.vagrant.d` 

### Install instructions
```
1. wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
2. sudo dpkg -i vagrant_1.9.1_x86_64.deb 
3. vagrant version
```

**Comment by sukurcf** [comment]
Does this process remove the files or VMs of old version?

**Comment by AmitKumarDas** [comment]
- These are the steps to remove existing vagrant installation:

1. sudo apt-get remove --auto-remove vagrant
2. rm -r ~/.vagrant.d

_NOTE: Above steps does not remove machines available under workingdir/.vagrant/ folder_

- These are the steps to install vagrant 2.0.2:

1. wget https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb
2. sudo dpkg -i vagrant_2.0.2_x86_64.deb
3. vagrant version

**Comment by elangovanshanthi** [comment]
These are the steps to remove existing vagrant installation:
```
1. sudo apt-get remove --auto-remove vagrant
2. rm -r ~/.vagrant.d
```
These are the steps to install vagrant 2.0.3:
```
1. wget https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb
2. sudo dpkg -i vagrant_2.0.3_x86_64.deb
3. vagrant version
```
**Ref Link :** https://www.vagrantup.com/downloads.html

**Comment by PululuK** [comment]
These are the steps to remove existing vagrant installation:

1. sudo apt-get remove --auto-remove vagrant
2. rm -r ~/.vagrant.d

These are the steps to install vagrant X.X.X:

1.Download your version here : https://releases.hashicorp.com/vagrant/
or `wget https://releases.hashicorp.com/vagrant/X.X.X/vagrant_X.X.X_x86_64.deb`
2. sudo dpkg -i vagrant_X.X.X_x86_64.deb
3. vagrant version

Ref Link : https://releases.hashicorp.com/vagrant/
