### ISSUE TITLE
Sri - Lankan Malay language support

### ISSUE THREAD

**Issue by Aryankpoor** [openebs/openebs#3202]
## Description
Hi. If the sri - lankan translation of readme is not there I might be of help. If there is already a translation for malay, pls comment so I can close the PR.

## Context

This is the malay translation of readme for sri-lankan users-
OpenEBS
Melancarkan saluran Slack #openebs Twitter PR Selamat Datang FOSSA Status CII Amalan Terbaik

https://openebs.io/

OpenEBS adalah penyelesaian penyimpanan sumber terbuka yang paling banyak digunakan dan mudah digunakan untuk Kubernetes.

OpenEBS adalah contoh sumber terbuka utama bagi kategori penyelesaian penyimpanan yang kadang-kadang dipanggil Container Attached Storage. OpenEBS disenaraikan sebagai contoh sumber terbuka dalam Kertas Putih Landskap Penyimpanan CNCF di bawah penyelesaian penyimpanan yang terlalu tinggi.

Beberapa aspek utama yang menjadikan OpenEBS berbeza berbanding penyelesaian storan tradisional lain:

Dibangun menggunakan seni bina perkhidmatan mikro seperti aplikasi yang dilayaninya. OpenEBS sendiri digunakan sebagai satu set kontena pada nod pekerja Kubernetes. Menggunakan Kubernetes sendiri untuk mengatur dan mengurus komponen OpenEBS
Dibina sepenuhnya di ruang pengguna menjadikannya sangat mudah alih untuk berjalan di mana-mana OS / platform
Sepenuhnya didorong oleh niat, mewarisi prinsip yang sama yang mendorong kemudahan penggunaan dengan Kubernetes
OpenEBS menyokong pelbagai enjin penyimpanan sehingga pembangun dapat menggunakan teknologi penyimpanan yang sesuai dengan objektif reka bentuk aplikasi mereka. Aplikasi yang diedarkan seperti Cassandra dapat menggunakan enjin LocalPV untuk penulisan latensi terendah. Aplikasi monolitik seperti MySQL dan PostgreSQL dapat menggunakan mesin ZFS (cStor) untuk ketahanan. Aplikasi streaming seperti Kafka dapat menggunakan mesin NVMe Mayastor untuk prestasi terbaik di persekitaran yang canggih. Di sebilangan jenis enjin, OpenEBS menyediakan rangka kerja yang konsisten untuk ketersediaan tinggi, tangkapan gambar, klon dan pengurusan.
OpenEBS sendiri digunakan sebagai wadah lain di hos anda dan membolehkan perkhidmatan storan yang boleh ditentukan pada tahap per pod, aplikasi, kelompok atau kontena, termasuk:

Mengautomasikan pengurusan storan yang dilampirkan pada nod pekerja Kubernetes dan membenarkan storan digunakan untuk penyediaan OpenEBS PV atau PV Tempatan secara Dinamik.
Kekekalan data merentasi node, secara dramatiknya mengurangkan masa yang dihabiskan untuk membina semula cincin Cassandra misalnya.
Penyegerakan data merentasi zon ketersediaan dan penyedia awan meningkatkan ketersediaan dan menurunkan masa lampiran / melepaskan misalnya.
Lapisan biasa jadi sama ada anda menggunakan AKS, atau logam kosong, atau GKE, atau AWS - pengalaman pendawaian dan pembangun anda untuk perkhidmatan penyimpanan adalah serupa.
Pengurusan peringkat ke dan dari S3 dan sasaran lain.
Kelebihan tambahan untuk menjadi penyelesaian asli Kubernetes ialah pentadbir dan pembangun dapat berinteraksi dan mengurus OpenEBS menggunakan semua alat hebat yang tersedia untuk Kubernetes seperti kubectl, Helm, Prometheus, Grafana, Weave Scope, dll.

Visi kami sederhana: biarkan perkhidmatan penyimpanan dan penyimpanan untuk beban kerja berterusan disatukan sepenuhnya ke dalam persekitaran sehingga setiap pasukan dan beban kerja mendapat keuntungan dari keperitan kawalan dan tingkah laku asli Kubernetes.

Baca ini dalam bahasa lain.
de ru tr ukraine cn fr

Skalabiliti
OpenEBS dapat membuat skala untuk memasukkan sebilangan besar pengawal penyimpanan kontena. Kubernetes digunakan untuk menyediakan kepingan asas seperti menggunakan etcd untuk inventori. Skala OpenEBS sejauh mana skala Kubernetes anda.

Pemasangan dan Permulaan
OpenEBS dapat disiapkan dalam beberapa langkah mudah. Anda boleh meneruskan kluster Kubernetes pilihan anda dengan memasang open-iscsi pada nod Kubernetes dan menjalankan operator openebs menggunakan kubectl.

Mulakan Perkhidmatan OpenEBS menggunakan pengendali

# sapukan yaml ini
kubectl berlaku -f https://openebs.github.io/charts/openebs-operator.yaml
Mulakan Perkhidmatan OpenEBS menggunakan helm

helm repo kemas kini
helm install --namespace openebs --name openebs stable / openebs
Anda juga boleh mengikuti Panduan Pantas Kami.

OpenEBS dapat digunakan di mana-mana kluster Kubernetes - sama ada di awan, komputer riba atau komputer riba (minikube). Perhatikan bahawa tidak ada perubahan pada kernel yang diperlukan kerana OpenEBS beroperasi di ruang pengguna. Sila ikuti dokumentasi Persediaan OpenEBS kami. Juga, kami memiliki lingkungan Vagrant yang tersedia termasuk contoh penggunaan Kubernetes dan beban sintetik yang dapat anda gunakan untuk mensimulasikan prestasi OpenEBS. Anda mungkin juga menarik menarik projek berkaitan yang disebut Litmus (https://litmuschaos.io) yang membantu dengan kejuruteraan kekacauan untuk beban kerja yang bernas di Kubernetes.

Status
OpenEBS adalah salah satu infrastruktur penyimpanan Kubernetes yang paling banyak digunakan dan diuji dalam industri ini. Projek Kotak Pasir CNCF sejak Mei 2019, OpenEBS adalah sistem storan pertama dan satu-satunya yang menyediakan satu set keupayaan penyimpanan yang ditentukan perisian secara konsisten pada pelbagai backend (tempatan, nfs, zfs, nvme) di kedua-dua sistem di premis dan awan, dan yang pertama membuka sumber Kerangka Kejuruteraan Chaos sendiri untuk Beban Kerja yang Berguna, Projek Litmus, yang bergantung kepada masyarakat untuk secara automatik kesediaan menilai irama bulanan versi OpenEBS. Pelanggan perusahaan telah menggunakan OpenEBS dalam pengeluaran sejak 2018 dan projek ini menyokong 2.5M + docker seminggu.

Status pelbagai stora

## Possible Solution

Given above

**Comment by prateekpandey14** [comment]
Not a valid issue , closing this.
