### ISSUE TITLE
Add Brazilian Portuguese translations

### ISSUE THREAD

**Issue by lucasqueiroz** [openebs/openebs#3203]
## Description

There's no Brazilian Portuguese translation of the README and CONTRIBUTING guides.

## Context

Many Brazilians don't speak English, mostly because they have no access to the courses as they're expensive and could take a long time to complete.
Adding the translation opens up the access to the Brazilian developers to use and contribute to this project.

**Comment by Akshay-Nagle** [comment]
I want to work on this issue. Please kindly assign me.

**Comment by lucasqueiroz** [comment]
Hi @Akshay-Nagle I actually already opened a pull-request but forgot to mention this issue. The pr is the https://github.com/openebs/openebs/pull/3205

**Comment by prateekpandey14** [comment]
Not an valid issue, closing this
