### ISSUE TITLE
Add Troubleshooting content

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#321]
point to slack channel issues and github issues

**Comment by vharsh** [comment]
@kmova It'll be helpful to point them to pain points we have discovered to the issues tagged with `status/hacked-fix` as we discussed earlier?

**Comment by kmova** [comment]
some items to be included:
https://github.com/openebs/openebs/labels/status%2Fhacked-fix

**Comment by mahebbar** [comment]
Documented both issues in https://github.com/openebs/openebs/labels/status%2Fhacked-fix at the following doc URLs:

https://staging-docs.openebs.io/docs/next/tsg_install.html#MinikubeStartError
https://staging-docs.openebs.io/docs/next/tsg_install.html#KubeminionError
