### ISSUE TITLE
Hindi translation needed

### ISSUE THREAD

**Issue by sarthakvdev** [openebs/openebs#3213]
As we know, people from all over the world come here, see your documentation and gain benefit from your service.

Hence, as an Indian, I wanted Hindi translations for README to be added in your project, So much more people from India could gain benefit from it.

I want to add those translated files, please check my further added pull request and merge it.

**Comment by AdityaJ7** [comment]
@sarthakvdev you should close this issue as someone else has made a similar issue before you and have also made a submission .

Thanks

**Comment by sarthakvdev** [comment]
Hey Aditya, I think his PR didn't got merged. Can I work on it and add a PR because I was already working on it?

**Comment by AdityaJ7** [comment]
> Hey Aditya, I think his PR didn't got merged. Can I work on it and add a PR because I was already working on it?

It will get merged, I would suggest that you should not continue working on it

**Comment by sarthakvdev** [comment]
Ok, thanks.
