### ISSUE TITLE
Indonesian Translation of Readme.md and Contributing.md

### ISSUE THREAD

**Issue by sharur7** [openebs/openebs#3219]
## Description
Adding Indonesian translation of Readme.md and contributing.md

## Context
The Indonesian language is among the Top 10 spoken languages in the world. As many of the translations of Readme.md and Contributing.md are available in different languages in repo, Indonesian is missing. This translation would help people who speak Indonesian language better to understand.

## Possible Solution
Adding documentation of Readme.md and Contributing.md in the Indonesian language.

**Comment by sharur7** [comment]
Hey, @prateekpandey14 Can you please check this issue and add appropriate labels to it?

**Comment by prateekpandey14** [comment]
Not an valid issue @sharur7 , closing this. Please pick the issue having `Hactoberfest` label on it.

**Comment by prateekpandey14** [comment]
As we decided to consider the translation PR , re-opening the issue

**Comment by sam-2200** [comment]
@prateekpandey14  I am a beginner I want to take up this issue

**Comment by hnifmaghfur** [comment]
bro @prateekpandey14 can you review my PR about this issue and also add appropriate labels on it ?

**Comment by Solomon98** [comment]
@hnifmaghfur are you working on this issue? I can't see this issue assigned to anyone.

**Comment by hnifmaghfur** [comment]
@Solomon98 i think this issue open for all, so i work in this issue.

**Comment by sharur7** [comment]
> @Solomon98 i think this issue open for all, so i work in this issue.

I actually opened this issue for myself and I have already created a PR #3224 😅

**Comment by hnifmaghfur** [comment]
no one assigned for this issue so i think this issue free for all 😅
