### ISSUE TITLE
Punjabi Translation of Readme.md and Contributing.md

### ISSUE THREAD

**Issue by archit041198** [openebs/openebs#3227]
## Description
Adding Punjabi translation of Readme.md and contributing.md

## Context
The Punjabi language is an Indo-Aryan language with more than 125 million native speakers in the Indian subcontinent and around the world. This is native to India and Pakistan. As many of the translations of Readme.md and Contributing.md are available in different languages in the repo, Punjabi is missing. This translation would help people who speak the Punjabi language better to understand.

## Possible Solution
Adding documentation of Readme.md and Contributing.md in the Punjabi language.

**Comment by archit041198** [comment]
I would like to take up this issue

**Comment by archit041198** [comment]
@prateekpandey14 Can you please add relevant labels to this issue? I will open a PR soon.

**Comment by manpreetrathore** [comment]
Can you please assign me this issue. Punjabi is my mother tongue and i'm very fluent in it. I can do it more efficiently and at the earliest possible.

**Comment by archit041198** [comment]
@manpreetrathore currently, I have worked on Punjabi translation, I would be great if you try for any other language.
