### ISSUE TITLE
Add dependencies to build the docs on Linux

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#325]
Wonder how docs go from [Github](https://github.com/openebs/openebs/tree/master/documentation) to [ReadTheDocs](https://openebs.readthedocs.io/en/latest/)?
Want to build them locally but don't know where to begin?

Some ideas to begin with
- Install python (already there if you are on a popular Linux distro)
- Install docutils, readthedocs theme (using pip).
- Ensure that you have `GNUmake`.

**Comment by codevbus** [comment]
I'll take a look at this.

**Comment by codevbus** [comment]
@vharsh 

So the documentation, and requirements/Make need to be updated for Linux?

**Comment by vharsh** [comment]
Hi @codevbus
move the `requirements.txt` from the root of the repository to the `documentation` folder.
Also update the `.travis.yml` folder to update the path of the same.

**Comment by Naman-Bhalla** [comment]
Hi ! If no one is taking this issue, can I ? I guess it requires just the steps mentioned by @vharsh , right ? Am I also required to update the documentation ?

**Comment by kmova** [comment]
This is outdated. the docs have moved to docusaurus https://github.com/openebs/openebs-docs
