### ISSUE TITLE
PersistentVolumeClaim local-device-pvc failed to provision volume with StorageClass "openebs-device": unable to find BD

### ISSUE THREAD

**Issue by jnsrikanth** [openebs/openebs#3263]
## Description
Step 1: Installed OpenEBS in a Single Node MicroK8S Cluster.
Step 2: Installed the below PVC and Pod to make use of the default storage class "openebs-device" as part of the OpenEBS installation
kubectl apply -f https://openebs.github.io/charts/examples/local-device/local-device-pvc.yaml
kubectl apply -f https://openebs.github.io/charts/examples/local-device/local-device-pod.yaml

## Expected Behavior
Expected allocation of BD to the PVC and bind the PVC to the pod with the mount volume made available to the Pod

## Current Behavior
However, both the PVC and Pod are shown as status "Pending" with the below error.

Warning   ProvisioningFailed     persistentvolumeclaim/local-device-pvc   failed to provision volume with StorageClass "openebs-device": unable to find BD: for BDC:bdc-pvc-ed281118-f8a1-4bcd-b48f-70378816e87c associated with PV:pvc-ed281118-f8a1-4bcd-b48f-70378816e87c

## Your Environment

* `kubectl get nodes`:

NAME                   STATUS   ROLES    AGE    VERSION
vm-gwtesting-srikant   Ready    <none>   2d6h   v1.19.2-34+1b3fa60b402c1c

* `kubectl get pods --all-namespaces`:

* `kubectl get services`:

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
kubernetes                     ClusterIP   10.152.183.1     <none>        443/TCP                                 2d6h
my-release-rabbitmq-headless   ClusterIP   None             <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   2d6h
my-release-rabbitmq            ClusterIP   10.152.183.24    <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   2d6h
gw-release-mongodb             ClusterIP   10.152.183.251   <none>        27017/TCP                               2d6h

* `kubectl get sc`:
NAME                          PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
microk8s-hostpath (default)   microk8s.io/hostpath                                       Delete          Immediate              false                  2d6h
openebs-jiva-default          openebs.io/provisioner-iscsi                               Delete          Immediate              false                  9h
openebs-snapshot-promoter     volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  9h
openebs-hostpath              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  9h
openebs-device                openebs.io/local                                           Delete          WaitForFirstConsumer   false                  9h

* `kubectl get pv`:
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                STORAGECLASS        REASON   AGE
pvc-6d87d41b-0737-4c8c-94d1-b252d5959350   8Gi        RWO            Delete           Bound    default/data-my-release-rabbitmq-0   microk8s-hostpath            2d6h
pvc-e018012f-f211-4359-a33c-30611c778013   8Gi        RWO            Delete           Bound    default/gw-release-mongodb           microk8s-hostpath            2d6h

* `kubectl get pvc`:

NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
data-my-release-rabbitmq-0   Bound    pvc-6d87d41b-0737-4c8c-94d1-b252d5959350   8Gi        RWO            microk8s-hostpath   2d6h
gw-release-mongodb           Bound    pvc-e018012f-f211-4359-a33c-30611c778013   8Gi        RWO            microk8s-hostpath   2d6h

* OS (from `/etc/os-release`): Ubuntu 18.04 LTS
* Kernel (from `uname -a`):5.4.0-1026-azure
* Install tools: 
* Others: Please note that I have deleted the PVC and the Pods as they were not launching and hence you will not be able to see them listed above with the kubectl commands.

**Comment by AndiDog** [comment]
When `kubectl describe`ng the BlockDeviceClaim, you should see something like

```text
Warning  SelectionFailed  4m15s (x62 over 9m18s)  blockdeviceclaim-operator  no blockdevices found
```

OpenEBS requires you to [have a block device created](https://docs.openebs.io/docs/next/uglocalpv-device.html#prerequisites) in order to use storage class `openebs-device`. See also "Specify the list of block devices for which BlockDevice CRs must not be created" [here](https://docs.openebs.io/docs/next/uglocalpv-device.html#customize-ndm-and-install) to notice that loop and ramdisk devices (useful for local testing, right?!) aren't picked up automatically since that would be highly surprising in production. The configured filters determine which BDs get created automatically, and if you have one available, it can be bound to the BDC.

**Comment by maxisam** [comment]
I have the same problem. I have a blockdevice created beforehand. But It seems like it only can be claim by one pvc. So if I have 2 pods needs 2 pvc on one node but I only have 1 block device. It seems like it won't work even the block device has sufficient space.

**Comment by kmova** [comment]
@maxisam = For sharing the block device here are some options that are supported via the latest versions:

Partition the block device. This will let NDM create multiple partitions. (If there is interest in this, we can actually work towards automating the creation of partition. Now one disadvantage with partitions is that it can create fragments on the disk that can't be easily re-used. This approach is best suited, when the size of the partitions are pre-determined and can be recycled for new pods.) To avoid the fragmentation limitation, you can either use the ZFS Local PV or LVM Local PV on top of the device.

**Comment by kmova** [comment]
https://github.com/openebs/device-localpv is not available for use-cases where OpenEBS can provide the PVs by partitioning the block devices on demand.
