### ISSUE TITLE
Jiva Volumes on OpenShift 4.x Cannot be Provisioned Without Manual Intervention

### ISSUE THREAD

**Issue by zach-robinson** [openebs/openebs#3295]
## Description

When using OpenEBS on OpenShift 4 (installed via the operator), when Jiva PVCs are provisioned in non-system (user-created) namespaces, the pvc-*-rep pods will fail to be created causing the provisioning to fail. These pods seem to be assigned to the default serviceaccount of whatever namespace they are running in (the same namespace as the PVC that they are assigned to). By default these default serviceaccounts do not have permission to run privileged (root-user) containers under OpenShift's system of SecurityContextConstraints (SCC). This causes the replicaset to fail to provision these pods with this error:
```
  Warning  FailedCreate  13s (x13 over 33s)  replicaset-controller  Error creating: pods "pvc-b469786f-2014-4779-a3e5-8dce7dd5e00a-rep-56cf9c6b74-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

## Expected Behavior

Provisioning of Jiva volume succeeds without manual intervention.

## Current Behavior

Jiva provisioning fails due to the described issue. Can be worked around by manually adding the proper SCC to the default serviceaccount of the namespace containing the PVCs and then restarting the pvc-*-rep replicasets.

## Possible Solution

Jiva operator should create its own serviceaccount for each namespace with Jiva PVCs and assign its pods to those serviceaccounts. These serviceaccounts should be assigned automatically to an appropriate SCC by the operator.

## Steps to Reproduce

Install OpenEBS on OpenShift 4 using operator. Create a new namespace. Create a Jiva PVC in that namespace.

**Comment by kim0** [comment]
Just to be clear, this is how to apply the workaround
```
$ oc adm policy add-scc-to-user privileged -z default -n myproject
```

Can someone from openebs please fix this annoying bug. Thanks!
