### ISSUE TITLE
intermittently minion fails to configure and gets stuck with Connection to 127.0.0.1 closed

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#33]
During the "vagrant up", the minion fails to configure with the following errors on the screen:
Connection to 127.0.0.1 closed

The following errors are seen in the /var/log/syslog:

Feb 24 11:10:35 ubuntu-xenial kubelet[6485]: I0224 11:10:35.265645    6485 feature_gate.go:181] feature gates: map[]
Feb 24 11:10:35 ubuntu-xenial kubelet[6485]: error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
Feb 24 11:10:35 ubuntu-xenial systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 11:10:35 ubuntu-xenial systemd[1]: kubelet.service: Unit entered failed state.
Feb 24 11:10:35 ubuntu-xenial systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by electricsrini** [comment]
Here is the log where it failed for me.

==> kubeminion-01: Setting up the Minion using Token: 0c775e.60b76678134c5c66
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/platform.rb:24: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Connection to 127.0.0.1 closed.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

kubeadm join --token=0c775e.60b76678134c5c66 _____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 The unknown environment variables are:
   LC_CTYPE=UTF-8 LC_ALL=
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

172.28.128.3

Stdout from the command:

[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Running pre-flight checks
Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
[preflight] Some fatal errors occurred:
:6443: invalid character "\r" in host name_________________________________________________
:9898: invalid character "\r" in host name________________________________________________
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
bash: line 4: WARNING!: command not found
bash: line 5: The: command not found
bash: line 6: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
): No such file or directorycale: LC_ALL: cannot change locale (
bash: line 7: This: command not found
bash: line 8: ability: command not found
bash: line 9: $'\r': command not found
E: Unable to locate package language-pack-UTF-8
bash: line 11: $'or\r': command not found
' is not a supported language or locale
bash: line 13: $'\r': command not found
bash: line 14: To: command not found
bash: line 16: To: command not found
bash: line 18: $'_____________________________________________________________________\r': command not found
bash: line 19: $'\r': command not found
bash: line 20: 172.28.128.3: command not found


Please ignore the error that reads "warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777"
