### ISSUE TITLE
"admission-webhook.openebs.io" does not support dry run

### ISSUE THREAD

**Issue by mpartel** [openebs/openebs#3303]
## Description
When running `kubectl diff` or `kubectl apply --dry-run` I get this error:
`admission webhook "admission-webhook.openebs.io" does not support dry run`

## Possible Solution
You can mark the [ValidatingWebhook](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#validatingwebhook-v1beta1-admissionregistration-k8s-io) resource that OpenEBS installs in `webhook/configuration.go` as `sideEffects: None` or `NoneOnDryRun`, assuming the webhook indeed has no side-effects.

## Steps to Reproduce
With OpenEBS installed, run `kubectl diff` or `kubectl apply --dry-run` on a config that defines a `PersistentVolumeClaim`.

**Comment by kmova** [comment]
@mpartel -- just in case you want to take this up for making the change. The charts are here: https://github.com/openebs/charts

**Comment by mpartel** [comment]
Ah, sorry, I filed this in the wrong repo :man_facepalming: 
The `webhook/configuration.go` I mentioned was in openebs/maya.
Refiled as https://github.com/openebs/maya/issues/1771
