### ISSUE TITLE
Unable to mount jiva volumes (maybe from libcrypto.so.10 not found in kubelet)

### ISSUE THREAD

**Issue by KevinWhalen** [openebs/openebs#3304]
## Description

Host-path bind-mounting works and jiva did initially. When I told it to redeploy to a different node, it never managed to mount the volume. Has never mounted a jiva volume since then.

At first, I thought it was from the mistake of using a deployment workload, instead of being a stateful set (have mostly ever only used deployments before this). I threw that away and created a stateful set, but that did not work. Next I threw away everything and made sure the VMs, Rancher, and Kubernetes were up-to-date.

I have watched the logs ([attached](https://github.com/openebs/openebs/files/5585935/interal-cluster-jiva-related-logs.txt)) in the apiserver, admissionserver, and ctrl and replica pvc pods without seeing anything that I have been able to see as root issues to be fixed.

## Expected Behavior

Jiva volumes should mount to the containers they are attached to.

## Current Behavior

**iscsiadm: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory**

`kubectl describe pv pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749`

    Name:            pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749
    Labels:          openebs.io/cas-type=jiva
                     openebs.io/storageclass=data-jiva-4replica
    Annotations:     openEBSProvisionerIdentity: kinstweb1
                     openebs.io/cas-type: jiva
                     pv.kubernetes.io/provisioned-by: openebs.io/provisioner-iscsi
    Finalizers:      [kubernetes.io/pv-protection]
    StorageClass:    data-jiva-4replica
    Status:          Bound
    Claim:           default/jiva-gis-map-service-config-claim-5
    Reclaim Policy:  Delete
    Access Modes:    RWO
    VolumeMode:      Filesystem
    Capacity:        1Gi
    Node Affinity:   <none>
    Message:
    Source:
        Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
        TargetPortal:       10.43.53.187:3260
        IQN:                iqn.2016-09.com.openebs.jiva:pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749
        Lun:                0
        ISCSIInterface      default
        FSType:             xfs
        ReadOnly:           false
        Portals:            []
        DiscoveryCHAPAuth:  false
        SessionCHAPAuth:    false
        SecretRef:          nil
        InitiatorName:      <none>
    Events:                 <none>

`kubectl describe pod jiva-gis-map-service-5-0`

* AttachVolume.Attach succeeded for volume "pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749"
* Unable to attach or mount volumes: unmounted volumes=[jiva-gis-map-service-config-claim-5], unattached volumes=[default-token-68vc9 jiva-gis-map-service-config-claim-5]: timed out waiting for the condition
* MountVolume.WaitForAttach failed for volume "pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749" : exit status 127

## Possible Solution

Ticket #2243 seems related, but nothing there helped, so (along with that original post being two years old) I am opening a new issue.

## Steps to Reproduce

Open-iSCSI installation procedure followed on every node.

    sudo yum install iscsi-initiator-utils
    sudo firewall-cmd --permanent --add-service=iscsi-target
    sudo firewall-cmd --reload
    sudo systemctl enable iscsid
    sudo systemctl start iscsid
    sudo modprobe iscsi_tcp
    echo -e "# Needed for OpenEBS.\niscsi_tcp\n" | sudo tee /etc/modules-load.d/iscsi-openebs.conf

Plus, the cluster's kubelet modification.

    services:
        ...
        kubelet:
          extra_binds:

For the extra binds, tried both:

            - "/etc/iscsi:/etc/iscsi"
            - "/sbin/iscsiadm:/sbin/iscsiadm"
            - "/var/lib/iscsi:/var/lib/iscsi"
            - "/lib/modules"

and

            - "/etc/iscsi:/etc/iscsi"
            - "/sbin/iscsiadm:/sbin/iscsiadm"

* helm chart app (official catalog https://openebs.github.io/charts)
* name: openebs
* namespace: openebs
* version: 2.3.0

    defaultStorageConfig.enabled=false
    image.pullPolicy=Always
    jiva.replicas=4

`kubectl apply -f storage-pool_data.yml`

    # https://docs.openebs.io/docs/next/jivaguide.html#create-a-pool
    # storage-pool_data.yml
    apiVersion: openebs.io/v1alpha1
    kind: StoragePool
    metadata:
      name: data-hostdir
      type: hostdir
    spec:
      path: "/data/volumes"

`kubectl apply -f storage-class_data.yml`

    # https://docs.openebs.io/docs/next/jivaguide.html#create-a-sc
    # storage-class_data.yml
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: data-jiva-4replica
      annotations:
        openebs.io/cas-type: jiva
        cas.openebs.io/config: |
          - name: ReplicaCount
            value: "4"
          # Options are ext4 and xfs.
          - name: FSType
            value: "xfs"
          # Name from storage-pool.yml.
          - name: StoragePool
            value: data-hostdir
          #- name: TargetNodeSelector
          #  value: |-
          #      storage: true
          #- name: ReplicaNodeSelector
          #  value: |-
          #      storage: true
          # Keeps pods for the persistent volume claim in the OpenEBS namespaces (e.g.
          # openebs), so they do not clutter the claiming resource's namespace nor cause
          # duplicate pods when restoring from Velero backups.
          - name: DeployInOpenEBSNamespace
            enabled: "true"
    provisioner: openebs.io/provisioner-iscsi

## Your Environment

* `kubectl get nodes`:
    * ```
        NAME            STATUS   ROLES                      VERSION
        kinstweb1       Ready    controlplane,etcd,worker   v1.18.12
        kinstweb2       Ready    controlplane,etcd,worker   v1.18.12
        kinstweb4       Ready    controlplane,etcd,worker   v1.18.12
        kmittradedev1   Ready    worker                     v1.18.12
        ```
* `kubectl get pods --all-namespaces`:
    * ```
        NAMESPACE  NAME                                                              READY   STATUS              RESTARTS
        default    jiva-gis-map-service-5-0                                          0/1     ContainerCreating   0
        openebs    openebs-admission-server-76f6b4f5c4-6p86k                         1/1     Running             0
        openebs    openebs-apiserver-7bf9589f86-kldkg                                1/1     Running             0
        openebs    openebs-localpv-provisioner-df595d94b-5qknp                       1/1     Running             0
        openebs    openebs-ndm-6k266                                                 1/1     Running             0
        openebs    openebs-ndm-hfn62                                                 1/1     Running             0
        openebs    openebs-ndm-n5nbn                                                 1/1     Running             0
        openebs    openebs-ndm-operator-d4c8b979d-k4zlr                              1/1     Running             0
        openebs    openebs-ndm-vgr7v                                                 1/1     Running             0
        openebs    openebs-provisioner-db45f6b7c-rgxpv                               1/1     Running             0
        openebs    openebs-snapshot-operator-95db8f86b-pwsdp                         2/2     Running             0
        openebs    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749-ctrl-68cd97585d-9ndtg    2/2     Running             0
        openebs    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749-rep-1-7ccd66d768-chlzr   1/1     Running             0
        openebs    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749-rep-2-57bd997f6c-47sd4   1/1     Running             2
        openebs    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749-rep-3-f5796964b-z2kd8    1/1     Running             0
        openebs    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749-rep-4-5df46fcf4d-sj2qz   1/1     Running             1
        ```
* `kubectl get services`:
    * ```
        NAME                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)
        jiva-gis-map-service-5            ClusterIP   10.43.10.43   <none>        8080/TCP
        jiva-gis-map-service-5-nodeport   NodePort    10.43.165.5   <none>        8080:30475/TCP
        kubernetes                        ClusterIP   10.43.0.1     <none>        443/TCP
        ```
* `for x in sp sc spc pv pvc; do echo "${x}"; kubectl get "${x}"; echo ""; done`:
    * ```
        sp
        NAME
        data-hostdir

        sc
        NAME                           PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION
        data-jiva-4replica (default)   openebs.io/provisioner-iscsi                               Delete          Immediate           false
        openebs-snapshot-promoter      volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate           false

        spc
        No resources found

        pv
        NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                         STORAGECLASS         REASON
        pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749   1Gi        RWO            Delete           Bound    default/jiva-gis-map-service-config-claim-5   data-jiva-4replica

        pvc
        NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS
        jiva-gis-map-service-config-claim-5   Bound    pvc-e2c9666c-f189-460e-b07e-7bb0ed47f749   1Gi        RWO            data-jiva-4replica
        ```
* Versions:
    * Rancher 2.5.2 (custom cluster)
    * Kubernetes 1.18.12
    * Docker 19.3.13, CentOS 7.9 3.10.0-1160.6.1.el7.x86_64 (three VM)
    * Docker 18.9.1, CentOS 8.2 4.18.0-193.28.1.el8_2.x86_64 (one VM)
        * Upgrades of the bare-metal production machines will be rotated through slowly, so having a 7 and 8 hybrid clusters is of some importance, but could be removed for this test cluster.
* Install tools:
    * Rancher installed from Docker (Docker Compose)
    * Kubernetes installed from docker command copied from Rancher

---

Verification.

`sudo yum info iscsi-initiator-utils # looking for installed.`

>     Installed Packages
>     Name        : iscsi-initiator-utils
>     Arch        : x86_64
>     Version     : 6.2.0.874
>     Release     : 19.el7
>     Size        : 2.4 M
>     Repo        : installed
>     ...

`sudo firewall-cmd --zone=public --list-services # looking for iscsi-target.`

>     dhcpv6-client http https iscsi-target rancher ssh

sudo systemctl status iscsid # looking for enabled and started.`

>     ● iscsid.service - Open-iSCSI
>        Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; vendor preset: disabled)
>        Active: active (running) since Thu 2020-11-19 12:31:34 EST; 4 days ago
>     ...

`cat /etc/iscsi/initiatorname.iscsi # looking for InitiatorName=...`

>     InitiatorName=iqn.1994-05.com.redhat:8858e3977fd6

`docker exec kubelet iscsiadm --version # looking for version output.`

> **`iscsiadm: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory`**
> >     locate libcrypto.so.10
> > >     /usr/lib64/.libcrypto.so.10.hmac
> > >     /usr/lib64/libcrypto.so.10
> > > >     docker exec -i -t kubelet ls /usr/lib /usr/lib64 | grep -i "crypto"
> > > > *Nothing.*
> 
> `docker exec -i -t kubelet bash`
>     root:/# apt-get update
>     root:/# apt-cache search libcrypto
>     ...
>     libcrypto++-dev - General purpose cryptographic library - C++ development
>     libcrypto++6 - General purpose cryptographic library - shared library
>     ...
>     root:/# apt show libcrypto++-dev
>     Package: libcrypto++-dev
>     Version: 5.6.4-8
>     Priority: optional
>     Section: libdevel
>     Source: libcrypto++
>     Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
>     Installed-Size: 81.6 MB
>     Depends: libcrypto++6 (= 5.6.4-8)
>     Homepage: http://www.cryptopp.com
>     ...
>     root:/# apt-get install libcrypto++-dev
>     ...
>     The following additional packages will be installed:
>       libcrypto++6
>     The following NEW packages will be installed:
>       libcrypto++-dev libcrypto++6
>     ...
>     Do you want to continue? [Y/n] n
>     Abort.

`iscsiadm --version # looking for a version output.`

>     iscsiadm version 6.2.0.874-19

`lsmod | grep -i "iscsi" # looking for iscsi_tcp.`

>     iscsi_tcp              18333  0
>     libiscsi_tcp           25146  1 iscsi_tcp
>     libiscsi               57233  2 libiscsi_tcp,iscsi_tcp
>     scsi_transport_iscsi    99909  3 iscsi_tcp,libiscsi

**Comment by KevinWhalen** [comment]
brings the main error to the "current behavior" section.

**Comment by ATalkingHead** [comment]
@KevinWhalen 

We just encountered this issue with the same setup - Jiva on RKE.

By adding the following to the extra_binds section in cluster.yml specified in the OpenEBS docs for RKE installations we managed to get it working.

```
    - "/usr/lib64/libssl.so.10:/usr/lib/libssl.so.10"
    - "/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10"
```

Hope this helps!

**Comment by KevinWhalen** [comment]
@ATalkingHead, adding those seems to have done it. I will report back after more testing and if, kicking off from there, I find a more generic solution.

For CentOS, those lib files are in package... TODO.

**Comment by KevinWhalen** [comment]
Continues to have issues.

The application with the volume claim ran alright as a stateful set and as a deployment. The S3 MinIO instance it needs does not. I will need some time to step through debugging that. It was working with LocalPV and since it does its own replication will be LocalPV in the end, but I wanting to try a second application. The jiva replicas for MinIO seem to start fine and everything, but they will not mount.

For testing, I also had the application assigned to one specific node. When it deployed, I went into it, made some edits, then redeployed it to a different node (redeploy with stateful set and scaled down then up with the deployment). In both cases, the changes did not persist. When I changed it back to the original node, the changes were also gone there.

**Comment by surajssd** [comment]
The documentation for `iscsi` is kinda confusing to me here: 

> If an iSCSI initiator is already installed on your node, check that the initiator name is configured and iSCSI service is running using the following commands.

[Source](https://docs.openebs.io/v100/docs/next/prerequisites.html_

What should the initiator file look like? What should I expect in the file?

**Comment by prateekpandey14** [comment]
@surajssd i will just contains the Initiator Name

```sh
$ sudo cat /etc/iscsi/initiatorname.iscsi 
## DO NOT EDIT OR REMOVE THIS FILE!
## If you remove this file, the iSCSI daemon will not start.
## If you change the InitiatorName, existing access control lists
## may reject this initiator.  The InitiatorName must be unique
## for each iSCSI initiator.  Do NOT duplicate iSCSI InitiatorNames.
InitiatorName=iqn.1993-08.org.debian:01:c2e0adb76678
```

**Comment by niladrih** [comment]
I'm able to recreate this issue.

Cluster hosts:
3 CentOS 7.9.2009 VMs 
```
[centos@ip-172-31-25-32 ~]$ uname -r
3.10.0-1160.6.1.el7.x86_64
```
1 CentOS 8.3.2011 VM
```
[centos@ip-172-31-28-91 ~]$ uname -r
4.18.0-240.1.1.el8_3.x86_64
```
Installed iscsi-initiator-utils-6.2.0.874-20.el7_9.x86_64 on the CentOS 7 VMs
Installed iscsi-initiator-utils-6.2.0.878-5.gitd791ce0.el8.x86_64 on the CentOS 8 VM

**kubectl describe pod demo-0**
```
Warning  FailedMount  11m (x372 over 12h)    kubelet  MountVolume.WaitForAttach failed for volume "pvc-976718d9-b5d6-472c-8b18-fc42afb70fb2" : exit status 127
  Warning  FailedMount  5m40s (x245 over 12h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[demo-jiva-vol], unattached volumes=[demo-jiva-vol default-token-s28ng]: timed out waiting for the condition
```

**docker exec kubelet iscsiadm --version** on the node where the pod is scheduled
```
[centos@ip-172-31-25-32 ~]$ docker exec kubelet iscsiadm --version
iscsiadm: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
```
**iscsiadm --version** on the node where the pod is scheduled
```

**Comment by niladrih** [comment]
Faced the issue in for the follow versions as well.
Rancher Server v2.5.2, v2.3.5
k8s v1.18.12 (Rancher v2.5.2), v1.16 (Rancher v2.5.2), v1.15 (Rancher v2.3.5)
Docker-ce v19.03.13
openebs-operator v2.4.0, v2.3.0, v2.2.0, v2.1.0

**Comment by KevinWhalen** [comment]
Looks like you are narrowing in on Docker CE v19.03 being a source of issue. CentOS 7 has 19.03, 18.09, 18.06, and 18.03. CentOS 8 has 20.10 and then the same as CentOS 7. Off-hand, I am not sure why most of my nodes with 19.03 and one is 18.09. I will roll them all  back to 18.09, test that, then bring them all back to 19.03 and try again.

Hopefully, I can do that today and report back.

**Comment by niladrih** [comment]
@KevinWhalen Not the case. Testing with other docker versions as well. Docker version seems to not be an issue.

**Comment by KevinWhalen** [comment]
@niladrih, alright. Thanks.

I did find why the CentOS 8 instances was using docker-ce v18.09.1 instead of the latest of v18 (18.09.9) or even v19. The module defaults were blocking the containerd version from changing.

    sudo dnf module disable container-tools
    sudo dnf install docker-ce-18.09.9 docker-ce-cli-18.09.9

Either way, I have all instances at Docker v18.09.9 now. Let me know if you would like me look at anything on my end.

**Comment by niladrih** [comment]
The mount succeeds with the bind
```
- "/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10"
```

**Comment by KevinWhalen** [comment]
Interesting. ~~It has been a few months now, but I thought I had tried that (or similar) at one point.~~ I might have tried it as lib64 -> lib64. Instead going lib64 -> **lib** for this make sense.

However, going back to it today and I see that the `containerd.io` upgrade allowed the most recent test workload, that had been sitting as failed for weeks, to finish mounting. Maybe the newer `containerd.io` aligned whatever was mismatched with libcrypto?

I will try clearing that workload out and doing it from scratch again before trying to add the kubelet mount `/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10`.

**Comment by KevinWhalen** [comment]
No, it was not specifically the containerd.io upgrade. Maybe something with the versions was holding it back, but I did already have the following in kubelet extra_binds. I had been restarting the docker daemon on the nodes when testing, but maybe I did not after making the change. The cluster edit should have forced kubelet to deploy again.

        - '/etc/iscsi:/etc/iscsi'
        - '/sbin/iscsiadm:/sbin/iscsiadm'
        - '/usr/lib64/libssl.so.10:/usr/lib/libssl.so.10'
        - '/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10'

So binding `/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10` is the fix. I cannot find where I found reference to `/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10` in the past.

I will reopen this, if after beating it up, I find `/usr/lib64/libcrypto.so.10:/usr/lib/libcrypto.so.10` is not enough.

**Comment by KevinWhalen** [comment]
I also had to add `"/usr/lib64/libopeniscsiusr.so.0.2.0:/usr/lib/libopeniscsiusr.so.0.2.0"` when deploying a testing, standalone instance of MinIO with Jiva.

    docker exec kubelet iscsiadm --version

> iscsiadm: error while loading shared libraries: libopeniscsiusr.so.0.2.0: cannot open shared object file: No such file or directory

MinIO (RELEASE.2020-12-03T05-49-24Z) installed as a Rancher app with Helm chart (8.0.9) from https://helm.min.io/.

    accessKey=test
    ingress.enabled=true
    ingress.hosts={map-store.test.local,}
    mode=standalone
    persistence.size=10Gi
    replicas=1
    secretKey=test
    service.port=9000
    service.type=NodePort
