### ISSUE TITLE
Support for downgrading of OpenEBS

### ISSUE THREAD

**Issue by lenko-d** [openebs/openebs#3307]
## Description

Please implement the ability to downgrade OpenEBS to a previous version. 

## Context

There is a need for a rollback because in a complex cluster with multiple upgrade steps something may fail and we should be able to restore the cluster to the same state that it was before the upgrade.  

Example rollback scenario:
Task: upgrade application X running in a Kubernetes cluster that is using OpenEBS.
Upgrade steps:
1. Upgrade OpenEBS from 1.7.0 to 2.3.0. This step succeeds.
2. Upgrade application X from version 7 to 8. For some reason this step fails and cannot be completed at this time. Now there is a requirement to do a rollback as described below.

Rollback steps:
1. Downgrade application X to version 7
2. Downgrade OpenEBS from 2.3.0 to 1.7.0

### Rollback of control plane
```
$ kubectl apply -f https://openebs.github.io/charts/1.7.0/openebs-operator.yaml
```
### Rollback of dataplane
```
$ kubectl apply -f  downgrade-cstor-vol-2.3.0-1.7.0.yaml
```
NOTE: 
This is not a specific request to support the downgrade path from 2.3.0 to 1.7.0. This is just an example path that is not currently needed but some other path may be needed in the future.

**Comment by kmova** [comment]
As per the [slack conversation](https://kubernetes.slack.com/archives/CUAKPFU78/p1605241340243900), this feature may be required in the future and is not a blocker at the moment. Will revisit this later.
