### ISSUE TITLE
openebs-localpv-provisioner pull linux-utils no basic auth credentials

### ISSUE THREAD

**Issue by allenhaozi** [openebs/openebs#3320]
is there a way to pass docker secret into init-pvc pod ?

**Comment by kmova** [comment]
Not at the moment. Will add this fix. Thanks @allenhaozi for bringing this up.

**Comment by allenhaozi** [comment]
> Not at the moment. Will add this fix. Thanks @allenhaozi for bringing this up.

I can send a pr for this

**Comment by kmova** [comment]
@allenhaozi .. that would be awesome!!

**Comment by allenhaozi** [comment]
已merge `https://github.com/openebs/dynamic-localpv-provisioner/pull/22`
