### ISSUE TITLE
Grafana dashboards for OpenEBS Storage Engines

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#3333]
All the OpenEBS components are deployed as Kubernetes native objects and support scraping of metrics via Prometheus. This is a feature request to implement Grafana dashboards for different Storage Engines, Control Plane and a Consolidated overall status:

- Overall status of OpenEBS
- Volume Usage Dashboard
- Pool Usage Dashboard

Here are some sample dashboards that have been developed and used by the community. The following can be taken up as an inspiration to build new and improved dashboards. 

- https://grafana.com/grafana/dashboards/12171
- https://github.com/openebs/openebs/tree/master/k8s
- https://github.com/openebs/zfs-localpv/blob/master/docs/grafana-dashboard.md

A cool way to implement this is by adding a package with default charts like. 
- https://github.com/scylladb/scylla-monitoring

**Comment by rahul799** [comment]
Hey @kmova ,
I will like to take this issue up for LFX mentorship.
Should I start drafting my proposal?

**Comment by Ab-hishek** [comment]
We have drafted a raw document stating the high-level goals and requirements for the OpenEBS monitoring add-on. Here is the document link for the same: https://docs.google.com/document/d/1vPB7u2TrdCr8UfERG8G_M5sVNIUWJtkFcB-ZWq0cJB8/edit#

**Comment by kmova** [comment]
With OpenEBS 2.10 and OpenEBS 2.11 - we have default dashboards for Jiva, cStor and LVM Local PV. More are being added. The progress is tracked under https://github.com/orgs/openebs/projects/41
