### ISSUE TITLE
openebs on GKE question

### ISSUE THREAD

**Issue by wataruian** [openebs/openebs#3342]
Hi all, 

I am running openebs on GKE cluster and I have created a cspc resource, blockdevices are attached to 3 nodes say (`node1` , `node2`, `node3`)

For GKE cluster node maintenance; cluster nodes will need to be upgraded once every three months or so.

Say `node1` is being upgraded, will I encounter data loss from `node1`?

Also for node failure, say `node1` fails/died and with cluster autoscaler `node4` got created, did I just lost data from `node1` too?

I am new to openebs and would like to know the behavior for node upgrades/failures from GKE.

Thanks!

**Comment by kmova** [comment]
Hi @wataruian, are you planning to use the Local SSDs on the GKE node or GPDs? what application do you plan to run on top of openebs?

**Comment by wataruian** [comment]
Hi @kmova, I am planning to use `GPDs` and would like to run `Redis Cluster` and `Postgresql`
