### ISSUE TITLE
inconsistency between Prometheus-Granafa docs

### ISSUE THREAD

**Issue by survivant** [openebs/openebs#3348]
there is lot of documentation about Prometheus and Grafana in the web site.  But the documentation is not consistent.  There are differences between them.  The information should be consolidated in one place and a little cleanup is required.

here some differences between the Grafana dashboard in https://github.com/openebs/charts/tree/gh-pages/grafana-charts and the older into : https://github.com/openebs/openebs/tree/master/k8s    

also that guide : https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/prometheus-monitoring.md 

there is also discussion here : https://github.com/openebs/charts/issues/196

**Comment by survivant** [comment]
@kmova there are other places where that information is duplicate ?  (probably also in zfs , jiva ...)

could it be possible to regroup all that information into one section and for specific subject like ZFS.. a different section in the guide... something like that ?

**Comment by kmova** [comment]
Sounds good @survivant. Will take this up.

**Comment by niladrih** [comment]
Posting the monitoring docs/blogs we have on OpenEBS volumes:
1. https://docs.openebs.io/docs/next/prometheus.html#configuration-workflow
2. https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/prometheus-monitoring.md
3. https://blog.mayadata.io/openebs/how-to-monitor-cstor-pools

**Comment by survivant** [comment]
I could add this search :   https://github.com/search?l=Markdown&q=org%3Aopenebs+prometheus&type=Code
