### ISSUE TITLE
Unable to delete orphan jiva volume with mayactl

### ISSUE THREAD

**Issue by vildek** [openebs/openebs#3355]
Kubernetes version -  1.19.6
Node OS - Ubuntu 18.04

$ k get no
NAME   STATUS   ROLES    AGE   VERSION
km01   Ready    master   56d   v1.19.6
km02   Ready    master   56d   v1.19.6
km03   Ready    master   34d   v1.19.6
kw01   Ready    <none>   56d   v1.19.6
kw02   Ready    <none>   56d   v1.19.6
kw03   Ready    <none>   33d   v1.19.6

Openebs instalation config default - kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml
cstor volumes works fine but for whatever reason local path jiva volume didn't get properly deleted after the PVC was deleted. 
The pv doesn't exist, but OpenEBS ir creating target pods for it. Tried deleting them, still OpenEBS recreates the pods.
$ k get pv -n openebs | grep pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d
$ k get po -n openebs | grep pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl-5f9d7f8b55-wx7jn    2/2     Running   0          28d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-1-6b96d7c86b-7xsjr   1/1     Running   0          19h
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-2-5fddb8dc44-sdwlg   1/1     Running   0          19h
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-3-79d4dd4f65-7s5bk   1/1     Running   1          19h

Tried deleting the volume from maya-apiserver pod via mayactl, but it says the volume doesn't exist.
bash-5.0# mayactl volume list
Namespace  Name                                      Status   Type   Capacity  StorageClass            Access Mode
---------  ----                                      ------   ----   --------  -------------           -----------
openebs    pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d  Running  jiva   10Gi      <none>                  <none>

bash-5.0# mayactl volume delete --volname=pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d -n openebs
Executing volume delete...
Volume deletion failed: Server status error: Not Found

It also gives metrics about the volume to prometheus. Shows up as 100 % free.

Is there a way to delete the volume manually?

**Comment by kmova** [comment]
@vildek - can you check there may be a deploments associated with the `53e5a8b3-d0ec-4998-845c-d1ec8051610d`? 

When the PV was deleted, there may be a chance that apiserver failed to delete it and left this stale entry. 

Check for `53e5a8b3-d0ec-4998-845c-d1ec8051610d` under:
- `kubectl get deployment -n openebs` 
- `kubectl get jobs - n openebs` 
- `kubectl get svc -n openebs`

**Comment by vildek** [comment]
@kmova Looks like it. I tried to delete the pods for it, but it recreates them. What is the correct procedure to delete them pernamently?

kubectl get deployment -n openebs
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
cstor-disk-pool-7gkq                              1/1     1            1           42d
cstor-disk-pool-hat7                              1/1     1            1           42d
cstor-disk-pool-wc4k                              1/1     1            1           42d
maya-apiserver                                    1/1     1            1           47d
openebs-admission-server                          1/1     1            1           47d
openebs-localpv-provisioner                       1/1     1            1           47d
openebs-ndm-operator                              1/1     1            1           47d
openebs-provisioner                               1/1     1            1           47d
openebs-snapshot-operator                         1/1     1            1           47d
pvc-17ea199c-2710-4c74-a4a4-a7f71dce5e94-target   1/1     1            1           22d
pvc-2006e052-4b29-47a6-9f37-ba99eb333197-target   1/1     1            1           42d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl     1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-1    1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-2    1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-3    1/1     1            1           43d
pvc-6871a0d9-853a-4679-a12c-2e09dad587bc-target   1/1     1            1           14d
pvc-790224b2-a1c1-422c-8aa7-a127bcba8b00-target   1/1     1            1           14d

kubectl get jobs -n openebs
No resources found in openebs namespace.

kubectl get deployment -n openebs
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
cstor-disk-pool-7gkq                              1/1     1            1           42d
cstor-disk-pool-hat7                              1/1     1            1           42d
cstor-disk-pool-wc4k                              1/1     1            1           42d
maya-apiserver                                    1/1     1            1           47d
openebs-admission-server                          1/1     1            1           47d
openebs-localpv-provisioner                       1/1     1            1           47d
openebs-ndm-operator                              1/1     1            1           47d
openebs-provisioner                               1/1     1            1           47d
openebs-snapshot-operator                         1/1     1            1           47d
pvc-17ea199c-2710-4c74-a4a4-a7f71dce5e94-target   1/1     1            1           22d
pvc-2006e052-4b29-47a6-9f37-ba99eb333197-target   1/1     1            1           42d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl     1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-1    1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-2    1/1     1            1           43d
pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-3    1/1     1            1           43d
pvc-6871a0d9-853a-4679-a12c-2e09dad587bc-target   1/1     1            1           14d
pvc-790224b2-a1c1-422c-8aa7-a127bcba8b00-target   1/1     1            1           14d

**Comment by prateekpandey14** [comment]
@vildek mostly statefulset specific volumes will not get deleted once you delete the PVC and PV ( its by k8s design), you have to manaully clean them up , here you can just delete the deployments to get rid off the pods .
```sh
kubectl delete deploy -n openebs pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl 
kubectl delete deploy -n openebs pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-1
kubectl delete deploy -n openebs pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-2
kubectl delete deploy -n openebs pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-rep-3
```

**Comment by vildek** [comment]
@prabhatkumarthakur ok. Deleted the deployments and svc, but know mayactl doesn't work:
bash-5.0# mayactl volume list
Volume list error: failed to list volumes:
casvolumelist {items: null
metadata:
  creationTimestamp: null
metalist: {}
}: failed to execute volume engine for CAST=jiva-volume-list-default-2.5.0: failed to execute output task:: failed to generate output:
task executor {MetaExec: {}
Runtask:
  metadata:
    creationTimestamp: "2021-02-05T15:39:19Z"
    generation: 1
    labels:
      version: 2.5.0
    managedFields:
    - apiVersion: openebs.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:version: {}
        f:spec:
          .: {}
          f:meta: {}
          f:task: {}
      manager: maya-apiserver
      operation: Update
      time: "2021-02-05T15:39:19Z"
    name: jiva-volume-list-output-default-2.5.0
    namespace: openebs
    resourceVersion: "5624105"
    selfLink: /apis/openebs.io/v1alpha1/namespaces/openebs/runtasks/jiva-volume-list-output-default-2.5.0
    uid: 89160806-b589-4d37-9bbb-a38e0c981d4c
  spec:
    meta: |
      id : listoutput
      action: output
      kind: CASVolumeList
      apiVersion: v1alpha1
    post: ""
    task: |-
      kind: CASVolumeList
      items:
      {{- $pvList := .ListItems.pvList }}
      {{- range $pkey, $map := .ListItems.volumeList }}
      {{- $capacity := pluck "capacity" $map | first | default "" | splitList ", " | first }}
      {{- $clusterIP := pluck "clusterIP" $map | first }}
      {{- $controllerIP := pluck "controllerIP" $map | first }}
      {{- $controllerStatus := pluck "controllerStatus" $map | first }}
      {{- $replicaIP := pluck "replicaIP" $map | first }}
      {{- $replicaStatus := pluck "replicaStatus" $map | first }}
      {{- $name := $pkey | splitList "/" | last }}
      {{- $ns := $pkey | splitList "/" | first }}
      {{- $pvInfo := pluck $name $pvList | first }}
        - kind: CASVolume
          apiVersion: v1alpha1
          metadata:
            name: {{ $name }}
            namespace: {{ $ns }}
            annotations:
              openebs.io/storage-class: {{ $pvInfo.storageClass | default "" }}
              vsm.openebs.io/controller-ips: {{ $controllerIP }}
              vsm.openebs.io/cluster-ips: {{ $clusterIP }}
              vsm.openebs.io/iqn: iqn.2016-09.com.openebs.jiva:{{ $name }}
              vsm.openebs.io/replica-count: {{ $replicaIP | default "" | splitList ", " | len }}
              vsm.openebs.io/volume-size: {{ $capacity }}
              vsm.openebs.io/replica-ips: {{ $replicaIP }}
              vsm.openebs.io/replica-status: {{ $replicaStatus | replace "true" "running" | replace "false" "notready" }}
              vsm.openebs.io/controller-status: {{ $controllerStatus | replace "true" "running" | replace "false" "notready" | replace " " "," }}
              vsm.openebs.io/targetportals: {{ $clusterIP }}:3260
              openebs.io/controller-ips: {{ $controllerIP }}
              openebs.io/cluster-ips: {{ $clusterIP }}
              openebs.io/iqn: iqn.2016-09.com.openebs.jiva:{{ $name }}
              openebs.io/replica-count: {{ $replicaIP | default "" | splitList ", " | len }}
              openebs.io/volume-size: {{ $capacity }}
              openebs.io/replica-ips: {{ $replicaIP }}
              openebs.io/replica-status: {{ $replicaStatus | replace "true" "running" | replace "false" "notready" }}
              openebs.io/controller-status: {{ $controllerStatus | replace "true" "running" | replace "false" "notready" | replace " " "," }}
              openebs.io/targetportals: {{ $clusterIP }}:3260
          spec:
            accessMode: {{ $pvInfo.accessModes | default "" }}
            capacity: {{ $capacity }}
            iqn: iqn.2016-09.com.openebs.jiva:{{ $name }}
            targetPortal: {{ $clusterIP }}:3260
            replicas: {{ .TaskResult.readlistrep.podIP | default "" | splitList " " | len }}
            casType: jiva
            targetIP: {{ $clusterIP }}
            targetPort: 3260
      {{- end -}}
Values:
  CAST:
    castName: jiva-volume-list-default-2.5.0
    kubeVersion: v1.19.6
    version: 2.5.0
  Config: {}
  JsonResult: --redacted--
  ListItems:
    currentRepeatResource: runNamespace=::owner=::objectName=::options=::retry=::disable=false
    volumeList:
      openebs/pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d:
        clusterIP: 10.103.230.153
  TaskResult:
    listlistctrl:
      verifyErr: null
    listlistpv:
      verifyErr: null
    listlistrep:
      verifyErr: null
    listlistsvc:
      verifyErr: null
  Volume:
    runNamespace: ""
}: template: outputYamlTpl:27:74: executing "outputYamlTpl" at <"running">: invalid value; expected string

**Comment by prateekpandey14** [comment]
did you deleted the service as well `kubectl delete svc -n openebs pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl-svc` ?

**Comment by vildek** [comment]
Yes,
kubectl delete svc -n openebs -f pvc-53e5a8b3-d0ec-4998-845c-d1ec8051610d-ctrl-svc

**Comment by prateekpandey14** [comment]
@vildek in above command `-f` not required, did it deleted the service correctly ? can you get the `kubectl get svc -n openebs` o/p.

**Comment by vildek** [comment]
@prabhatkumarthakur yes, sorry, haven't got my coffee yet :D -f is specifying manifest file. Deleted the svc and the mayactl doesn't show the stale volume anymore. Thanks. 
bash-5.0# mayactl volume list
Namespace  Name                                      Status   Type   Capacity  StorageClass            Access Mode
---------  ----                                      ------   ----   --------  -------------           -----------
openebs    pvc-17ea199c-2710-4c74-a4a4-a7f71dce5e94  Running  cstor  8G        openebs-sc-statefulset  ReadWriteOnce
openebs    pvc-2006e052-4b29-47a6-9f37-ba99eb333197  Running  cstor  10G       openebs-sc-statefulset  ReadWriteOnce
openebs    pvc-6871a0d9-853a-4679-a12c-2e09dad587bc  Running  cstor  80G       openebs-sc-statefulset  ReadWriteOnce
openebs    pvc-790224b2-a1c1-422c-8aa7-a127bcba8b00  Running  cstor  20G       openebs-sc-statefulset  ReadWriteOnce
