### ISSUE TITLE
NFS provisioner helm 3 setup documentation

### ISSUE THREAD

**Issue by tampler** [openebs/openebs#3360]
Hello 

Could anyone pls update the NFS provisioner docs for Helm 3? I'm unable to execute that example from docs [here](https://docs.openebs.io/docs/next/rwm.html)

Thanks!

**Comment by mittachaitu** [comment]
Hi tampler, This issue has been fixed via PR [#20](https://github.com/openebs/dynamic-nfs-provisioner/pull/20) in `openebs/dynamic-nfs-provisioner` repo.

**Installation**: 
- For detailed instructions about installation of OpenEBS NFS provisioner please refer this [doc](https://github.com/openebs/dynamic-nfs-provisioner/tree/develop/deploy/helm/charts#openebs-nfs-provisioner)

**Comment by mittachaitu** [comment]
Closing this issue since it has been addressed via [#20](https://github.com/openebs/dynamic-nfs-provisioner/pull/20). Please feel free to re-open if there are any issues.
