### ISSUE TITLE
Documentation: Jiva replica-node StoragePools picking/negotiation methodology

### ISSUE THREAD

**Issue by t3hmrman** [openebs/openebs#3371]
## Description
I'd like to know how Jiva decides which `StoragePool`s on other nodes 

I was pretty surprised to find that [`StoragePool`s only allow one local disk](https://github.com/openebs/openebs/issues/2621). I installed Jiva on a different cluster back @ 0.8.0, and somehow I remembered it differently -- thinking back on it now, I think I may have picked Jiva because RAID was in place on the disks below.

The [Jiva guide documentation](https://docs.openebs.io/docs/next/jivaguide.html) gets close but doesn't really go into it. The [FAQ gets tantalizingly close]():

> An OpenEBS Jiva volume is a controller deployed during OpenEBS installation. Volume replicas are defined by the parameter that you set. The controller is an iSCSI target while the replicas play the role of a disk. The controller exposes the iSCSI target while the actual data is written. The controller and each replica run inside a dedicated container. An OpenEBS Jiva volume controller exists as a single instance, but there can be multiple instances of OpenEBS Jiva volume replicas. Persistent data is synchronized between replicas. OpenEBS Jiva volume high availability is based on various scenarios as explained in the following sections.

But I still don't know exactly how the `StorageClass` gets picked there. Do all the disks/filesystems (represented by `StoragePool`s) on all the nodes have to be mounted at the same paths? When a replica goes to another node but can't find a filesystem at the folder that the `StoragePool` indicates, what happens? I assume it crashes but some documentation on this would be nice.

Also, completely unrelated, but the section links on the right hand side of the documentation website are not detailed enough -- not being able to jump to the sections of the page that are relevant (every time I go to the Jiva guide I have to scroll to where the StoragePool instructions are) is a little painful.

## Context

This change should help make it clearer how Jiva works for myself and other users

## Possible Solution

Update the documentation, maybe the FAQ, with some technical details.

[EDIT] - For example right now, it's unclear to me (right now at least) to get disk failure domain level replication working on one node, without using RAID or LVM underneath OpenEBS Jiva. I expected that I'd be able to get pool-level redundancy, would both replicas get made on the same `StoragePool` or another `StoragePool`? How would it pick which one?

**Comment by wibed** [comment]
could this be reopened?
or has this been answered

**Comment by t3hmrman** [comment]
Well I stopped using Jiva but as this is a question about adding documentation, I'm not sure it was addressed.

Looking at the docs I only see [CSTOR documentation mentions](https://openebs.io/docs/user-guides/cstor/advanced) any sort of related volume balancing (via replica affinity)...

The [Jiva docs](https://openebs.io/docs/user-guides/jiva-guide#replicatolerations-policy) mention affinity, but only in the sense of workload & data.
