### ISSUE TITLE
Dynamic Local PV provisioner doesn't work according to the documentation when you create your own StorageClass where StorageType is hostpath and NodeAffinityLabel is "openebs.io/custom-node-unique-id"

### ISSUE THREAD

**Issue by igorkatz** [openebs/openebs#3375]
What happened:
PV provisioning failed with error:
![image](https://user-images.githubusercontent.com/16424945/114312052-f3a2d080-9af9-11eb-9ea2-75b44448f565.png)

What you expected to happen:
PV provisioned successfully

How to reproduce it:
Install OpenEBS **2.7.0** by helm 3 on k8s cluster and follow instruction how to create and use your own StorageClass on:  (https://docs.openebs.io/docs/next/uglocalpv-hostpath.html)

Workaround:
define your own StorageClass without to define
![image](https://user-images.githubusercontent.com/16424945/114312608-de2ea600-9afb-11eb-80db-99a56ea0708f.png)

Kubernetes version:
v1.19.7

**Comment by kmova** [comment]
Thanks @igorkatz - Just updated the docs with removing the above options of custom node from the default class. Please let me know if this helps. 

https://docs.openebs.io/docs/next/uglocalpv-hostpath.html#create-storageclass

**Comment by igorkatz** [comment]
Yes, This works w/o above options, but it will be great to have an explanation how to use these options

**Comment by igorkatz** [comment]
Yes, much better

**Comment by pawanpraka1** [comment]
Closing this issue.
