### ISSUE TITLE
GitHub Actions build/release criteria modifications

### ISSUE THREAD

**Issue by niladrih** [openebs/openebs#3376]
Multiple GitHub actions (workflows) are setup on repository - like a release, build, pr. Update the Github actions to trigger the right workflows.  Example:
  - Release Tag - is triggering release and build. Need to only run release workflow
  - Branch Creation - is triggering release and build. Need to only trigger build
  - Modifications to code were triggering both helm and code builds. Based on the path - trigger the right workflow. 

@niladrih
- [x] [cstor-csi](https://github.com/openebs/cstor-csi/pull/151)
- [x] [dynamic-localpv-provisioner](https://github.com/openebs/dynamic-localpv-provisioner/pull/41)
- [x] [jiva](https://github.com/openebs/jiva/pull/350)
- [x] [jiva-operator](https://github.com/openebs/jiva-operator/pull/66)
- [x] [libcstor](https://github.com/openebs/libcstor/pull/85)
- [x] [lvm-localpv](https://github.com/openebs/lvm-localpv/pull/42)
- [x] [maya](https://github.com/openebs/maya/pull/1797)
- [x] [m-exporter](https://github.com/openebs/m-exporter/pull/14)
- [x] [upgrade](https://github.com/openebs/upgrade/pull/104)
- [x] [velero-plugin](https://github.com/openebs/velero-plugin/pull/151)

@shubham14bajpai
- [x] [istgt](https://github.com/openebs/istgt/pull/354)
- [x] [cstor-operators](https://github.com/openebs/cstor-operators/pull/281)
- [x] [zfs-localpv](https://github.com/openebs/zfs-localpv/pull/315)

@akhilerm
- [x] [cstor](https://github.com/openebs/cstor/pull/330)
- [x] [node-disk-manager](https://github.com/openebs/node-disk-manager/pull/566)

**Comment by akhilerm** [comment]
@niladrih For node-disk-manager, its not yet complete as still we are facing troubles with build workflow getting triggered along with release.

**Comment by niladrih** [comment]
The relevant PRs are included in the hyperlinks in the opening post of this issue.

**Comment by akhilerm** [comment]
The release criteria has one bug:

release workflows are getting triggered for helm chart releases. 

The tags section in

https://github.com/openebs/node-disk-manager/blob/e8d7bfd4d4c37066d494405e2933fd94858e70a1/.github/workflows/release.yml#L16-L21

is not working. Release workflow is getting triggered for helm chart releases also. Ref. [ndm](https://github.com/openebs/node-disk-manager/actions/workflows/release.yml), [zfs](https://github.com/openebs/zfs-localpv/actions/workflows/release.yml).

**Comment by shubham14bajpai** [comment]
The above bug can be fixed by using a simple if condition mentioned in this issue : https://github.com/actions/create-release/issues/14#issuecomment-555379810
Will be verifying and fixing the release in following repos:
- [ ] jiva-operator https://github.com/openebs/jiva-operator/pull/106
- [ ] cstor-operator
- [ ] ndm
- [ ] zfs-localpv
- [ ] lvm-localpv
- [ ] dynamic-localpv
- [ ] nfs

**Comment by akhilerm** [comment]
Closing issue as all PRs in repositories with helm charts have been merged. cc: @shubham14bajpai
