### ISSUE TITLE
webhook-cleanup Job in helm chart uses deprecated hyper-kube image with an older version of kubernetes

### ISSUE THREAD

**Issue by abhiTamrakar** [openebs/openebs#3383]
## Description

webhook-cleanup Job in helm chart uses hyper-kube image with an older version of kubernetes (May contain lot of vulnerabilities as well) to run kubectl delete on validation webhook configuration, while it is already deprecated https://github.com/kubernetes/kubernetes/pull/85094.
This was also discussed here https://kubernetes.slack.com/archives/CUAKPFU78/p1619181692086800

## Expected Behavior

helm delete must delete all the created resources in a defined order.

## Current Behavior

Webhook cleanup job is using a deprecated and vulnerable image for hyperkube.

## Possible Solution

We shall look for a proper fix either by calling `AdmissionregistrationV1().ValidatingWebhookConfigurations().Delete()` APIs directly or handling deletion of resources in combination with finalizers and helm hooks weight, if it is possible.
(Another simpler solution (may not be good, though) would be calling a curl to the DELETE API for the object using CA and token, only that it requires everyone to have CA and token mounted via controller manager.) 

## Steps to Reproduce

1. install openebs/cstore helm chart
2. try delete, the helm pre-delete hook will call the cleanup job which would in turn calls the vulnerable image to run kubectl.

## Your Environment
* Kubernetes version: v1.19.8
* OS (from `/etc/os-release`): CentOS 7
* Kernel (from `uname -a`): 3.10.0-1127.8.2.el7.x86_64

**Comment by kmova** [comment]
The above fixes involve directly pulling in the latest image. for air-gapped environments, we need a mechanism to override from a custom repository.

**Comment by prateekpandey14** [comment]
fixed in linked PR , closing this now.
