### ISSUE TITLE
NEW REPO: openebs/openebs-monitoring

### ISSUE THREAD

**Issue by Ab-hishek** [openebs/openebs#3384]
# Description
The `openebs-monitoring` repository will contain the monitoring-related tools (Prometheus, grafana, etc,), packaging them with charts and code for OpenEBS component monitoring. The goal of this repository is to provide easy to install monitoring artifacts or provide a single repository from which users can pick up the monitoring artifacts and integrate them into their observability stack.

### Container images produced
None

### Initial Maintainers
- @kmova 
- @avishnu 

### Initial Reviewers
- @Ab-hishek
- @rajaSahil
- @Sanjay1611
- @rahul799

**Comment by kmova** [comment]
Repo is available at https://github.com/openebs/monitoring

Related to #3333
