### ISSUE TITLE
Default Kyverno policies for OpenEBS 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#3385]
OpenEBS cStor and Jiva projects involve managing K8s custom resources via the engine operators. 

OpenEBS currently uses: 
- webhook admission controller for performing custom validations 
- PSP for setting some default security policies. 

PSP is getting deprecated in the upcoming K8s releases and webhook admission controller has a number of gotchas w.r.t certificate and policy management. 

This feature is to track the adoption of Kyverno for performing enforcing security and validation policies. 

Kyverno also can be extended for pushing image pull secrets into the pods that are launched by OpenEBS operators.

**Comment by RealHarshThakur** [comment]
Another policy engine to consider is [KubeWarden](https://www.kubewarden.io/) . There is already a policy[ hub](https://hub.kubewarden.io/) which has most PSPs implemented. Writing the policy is fairly simple too: https://docs.kubewarden.io/writing-policies/go/04-validation.html

**Comment by kmova** [comment]
Pushing this from slack thread. 

Jim Bugwadia  27 minutes ago @kiranmova - thanks for asking!
Is PSP replacement the only use case? There was a mention of synchronizing secrets as well (https://kyverno.io/policies/other/sync_secrets/?policytypes=generate).
I would suggest list requirements and the key criteria to help decide on the best solution. Some of the relevant items may be:

- CNCF project, OSS license, etc.
- PSP support
- Mutate support
- Validate support
- Generate support
- Ease of use
- Extensibility
- Observability
- HA
- Ability to customize by cluster admins

The last one may be important, as its critical to allow flexibility.


Jim Bugwadia  25 minutes ago
One other thought, the policy engine the end user selects can be different. Kyverno is designed to work with Gatekeeper/OPA, etc. as its possible different admission controllers are used to address different problems.
As an example, here is how Flux2 is using Kyverno to address multi-tenancy:
https://github.com/fluxcd/flux2-multi-tenancy#enforce-tenant-isolation

**Comment by Nivedita-coder** [comment]
Here is the screenshot of the policies testing.
![1st](https://user-images.githubusercontent.com/56059682/122857214-bf3b6400-d335-11eb-866d-52e42e2b0619.png)

![2](https://user-images.githubusercontent.com/56059682/122857239-cbbfbc80-d335-11eb-92a7-749087e12ef8.png)
