### ISSUE TITLE
Cstorvolume stuck in Offline state

### ISSUE THREAD

**Issue by tho861998** [openebs/openebs#3396]
## Expected Behavior
 cstorvolume  Warning  Offline  17m   pvc-bbf02b86-e7b9-407c-98cd-26668e01031f-target-7c84ff9d6f7nbft, kworker2  Volume is in Offline state.
cvr failed to sync CVR error: unable to update snapshot list details in CVR: failed to get the list of snapshots: Output: failed listsnap command for cstor-1d008afb-21ea-4160-a971-d4cda2786160/pvc-bbf02b86-e7b9-407c-98cd-26668e01031f with err 11
 

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by prateekpandey14** [comment]
@tho861998 can you share the following details as well.

- `kubectl get pods -n openebs` 
- `kubectl get cspc,cspi -n openebs`

**Comment by tho861998** [comment]
I work on centos 7 cluster
but doesn’t work on ubuntu 20.04

**Comment by prateekpandey14** [comment]
Never mind , i can see the screenshot attached to the issue, but somehow not visible in github issue.

I can see you have 2 cspi instance with 2 replicas , out of which one replica is in `offline` state and other is in `Degraded` state, hence the quorum is not met and `CstorVolume` ended up in `Offline` state.

 Also verify the network is reachable across the nodes , looks like this is the case here , target pod is not able to reach from the `kworker1` node

We can check the pool container logs of pod `cstor-storage-fm2r-###` using the below commands to know more details.

- `kubectl logs  cstor-storage-fm2r-### -c cstor-pool -n openebs`
- `kubectl logs  cstor-storage-fm2r-### -c cstor-pool-mgmt -n openebs`

**Comment by tho861998** [comment]
hello ,sorry for late reply. I am on my way back to home.
here is how i deployed cstor with ss

**Comment by tho861998** [comment]
can you help me? previously, i used glusterfs/heketi dynamic provision as
storage solution, Now, I want to try OpenEbs cstor. But I am in trouble ,
Help me

**Comment by tho861998** [comment]
here is logs file

**Comment by tho861998** [comment]
another pods logs file

**Comment by prateekpandey14** [comment]
Closing this issue, resolved in [slack discussion](https://kubernetes.slack.com/archives/CUAKPFU78/p1621441829035700) , related to cluster networking issue across the nodes.
