### ISSUE TITLE
bug(rebuild): cStor replica remains in rebuilding state infinitely

### ISSUE THREAD

**Issue by mittachaitu** [openebs/openebs#3398]
## Description

cStor replica remains in rebuild state infinitely due to helper replicas failovers.

## Expected Behavior

cStor replica rebuilding should get succeeded.

## Current Behavior

cStor replicas remain in `Rebuild state` infinitely due to misbehavior of helper replicas.

## Possible Solution

Before getting into workaround I would like to give very high details on how rebuild happens in cStor.
**Background**:
- Whenever quorum no.of replicas connect to the iSTGT target, the target will send a START REBUILD request to
   replica with a higher IO_SEQUENCE number.
- Once the replica gets a rebuild request it also receives the helper replicas details as a payload with the START REBUILD request. 
   **Note**: Replica which receives the REBUILD request is called as `Degraded Replica`
- Degraded replica will send a request to helper replicas to start a rebuild, once helper replicas responded with success 
  then degraded replicas will request for missing data in the range of offset(i.e something like sending the missing data between 0 to 10GB offset, send missing data between 10GB to 20GB offset).
  **Missing data**: Data that is higher than the particular checkpointed_io_sequence_number of the degraded replica.

**Actual Issue**:
Here, In this case, the helper replica is not able to scan the dataset and closing the rebuild connection due to this replica remains in rebuild state infinitely.

**Workaround**:
- Figured out the replica which is causing problem for a rebuild from `cstor-pool` container logs of pool pod and
   scaled-down the pool pod.
```sh
kubectl scale deploy <deploy_name> -n openebs --replicas=0
```
- After the other two replicas marked as Healthy scaled up the pool deployment which has an issue and deleted the internal snapshots & clones(**This is not at all recommended**) after that it underwent rebuild and marked as healthy after a long time.

## Steps to Reproduce

Not sure this issue was observed in OpenEBS 0.9 version(**Which is a very old version**).

## Screenshots

Adding logs of all three pool pods.

[oep-ci-pool-udh6-578d8c88d4-qhlgr-27may.log](https://github.com/openebs/openebs/files/6582912/oep-ci-pool-udh6-578d8c88d4-qhlgr-27may.log)
[oep-ci-pool-9pku-bfc64cfdf-6gpxf-27may.log](https://github.com/openebs/openebs/files/6582913/oep-ci-pool-9pku-bfc64cfdf-6gpxf-27may.log)
[oep-ci-pool-z9nh-75488f65d-b7k97-27may.log](https://github.com/openebs/openebs/files/6582914/oep-ci-pool-z9nh-75488f65d-b7k97-27may.log)

`oep-ci-pool-udh6-578d8c88d4-qhlgr` pool pod which is causing rebuild failure and it is failing continuously after 40GB offset.
```sh
2021-05-27/08:07:50.694 Checkpointed IO_seq: 900858265, Rebuild Req offset: 42949672960, Rebuild Req length: 10737418240 for zvol(cstor-01a1c4a7-d812-11ea-ba3b-42010a8000db/pvc-f2e873ef-d8a7-11ea-ba3b-42010a8000db)
2021-05-27/08:07:50.694 ERROR [cstor-01a1c4a7-d812-11ea-ba3b-42010a8000db/pvc-f2e873ef-d8a7-11ea-ba3b-42010a8000db:20]Rebuild scanning failed err:22
```

**Observation**:
- Pool which is has a problem observed that it has an internal snapshot of 4oGB but the actual main volume size is 70GB.

**Note**: OpenEBS is running in depricated version i.e **0.9**
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by pawanpraka1** [comment]
@mittachaitu do we need to do something here?

**Comment by mittachaitu** [comment]
@pawanpraka1 We didn't see this type of issues with releases >= `1.0.0`(and not able to reproduce). So for now we can close this issue and re-open when we observe issue either in user setup/pipelines.
