### ISSUE TITLE
Ability to use a volume restored from a cStor snapshot without any application storage reconfiguration

### ISSUE THREAD

**Issue by kthommandra** [openebs/openebs#3403]
## Description

Consider following sequence of events

1. application is using a volume
2. prior to upgrade1, snapshot1 created
3. upgrade1 successful
4. snapshot1 can be deleted since its of no use
5. app continues to use original volume
6. prior to upgrade2, snapshot2 created
7. upgrade application runs for sometime
8. upgrade2 deemed a failure and the intent is to go back to the storage state as in snapshot2

So the admin would restore snapshot2 and would like to be able to deploy the app so that it uses the restored volume without any application volume reconfiguration.

Currently, the original volume cannot be deleted and so the restored volume will have a different name and application needs to be reconfigured to use the new volume name. Would like to avoid the application reconfiguration.

**Comment by Amishakumari544** [comment]
hi @kmova just small observation in the project that it uses the outdated version of react. Kindly, Update this.
Thanks.
![image](https://user-images.githubusercontent.com/49230384/130119991-50a7bc3a-5ef0-4b43-8b10-40c9cd2dd76d.png)

**Comment by kmova** [comment]
@Amishakumari544 - can you please create a new issue for above under openebs/website repo. I will delete the comment from this thread once you have had a chance to create there as this comment is not helping this issue.
