### ISSUE TITLE
Deleting a dynamic PVC of openebs-jiva-default class does not empty the pods in openebs namespace.

### ISSUE THREAD

**Issue by turowicz** [openebs/openebs#3418]
I have originally asked this question on microk8s repo (https://github.com/ubuntu/microk8s/issues/2434), as it is what I'm using, but they claim I should ask you guys here.

When I create a pod with an OpenEbs storage requirement, except for the PVCs, microk8s also spins up pods on each node. These pods remain even after the deployment has been deleted and I need to go through them and delete them manually.

Is this the correct behaviour and I should delete them manually, or is this a bug in openebs?

![image](https://user-images.githubusercontent.com/1055391/126163881-4ecd393d-c514-4fd8-ad9d-441e443869bd.png)

**Comment by turowicz** [comment]
cc @kmova @Ab-hishek @vishnuitta @shubham14bajpai

**Comment by shubham14bajpai** [comment]
Hi @turowicz These volume related deployments should get deleted when the PVC is deleted. 
> These pods remain even after the deployment has been deleted 

Are you deleting the PVC as well when the deployment is deleted?

**Comment by turowicz** [comment]
Yes because I `helm uninstall` a release, so everything should be gone.

**Comment by shubham14bajpai** [comment]
Can you please once try uninstall and check if the PVC gets deleted or not

**Comment by prateekpandey14** [comment]
@turowicz is it StatefulSet based volumes ?.

**Comment by turowicz** [comment]
@shubham14bajpai yes the PVC are deleted on `helm uninstall`, only openebs pods remain for each node.

@prateekpandey14 yes this is connected to stateful sets. `Delete` is the reclaim policy.

**Comment by prateekpandey14** [comment]
@turowicz can you share the `openebs-apiserver` pods logs here, wanted to check if there are any errors , also what is the k8s version ?

**Comment by turowicz** [comment]
K8S: microk8s 1.21

openebs-apiserver:
```
+ MAYA_API_SERVER_NETWORK=eth0
+ ip -4 addr show scope global dev eth0
+ grep inet
+ awk '{print $2}'
+ cut -d / -f 1
+ CONTAINER_IP_ADDR=10.1.167.118
+ exec /usr/local/bin/maya-apiserver start '--bind=10.1.167.118'
I0713 21:41:15.150762 1 start.go:148] Initializing maya-apiserver...
I0713 21:41:15.214979 1 start.go:279] Starting maya api server ...
W0713 21:41:15.278331 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.296687 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.302111 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.308734 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.315719 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.322711 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.328128 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.335605 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.340637 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.347689 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.352659 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.359746 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0713 21:41:15.364637 1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by turowicz** [comment]
[openebs-provisioner-855f4d7598-4zdlr.log](https://github.com/openebs/openebs/files/6842234/openebs-provisioner-855f4d7598-4zdlr.log)

**Comment by prateekpandey14** [comment]
In the provisioner logs there are no PVC Delete request for the newly provisioned PVCs. for example `pvc-09ce295b-ce5a-4db0-b45f-5f4384f241f4` only have provisioned logs, no delete request have been made. what is the pvc status, are they deleted from the cluster ? what `kubectl get pvc --all-namespace` says ?

**Comment by turowicz** [comment]
Yes, the PVCs from uninstalled releases are gone.

**Comment by turowicz** [comment]
@prateekpandey14 @shubham14bajpai can you send me an example helm template that should have this working correctly? Perhaps I am missing something in my definitions.

**Comment by prateekpandey14** [comment]
@turowicz you can install any application helm charts like prometheus, mongo etc from their stable charts repo, or you can check out some example statefulset example [here](https://docs.openebs.io/docs/next/mongo.html) in openebs docs.

**Comment by turowicz** [comment]
@prateekpandey14 I am using these charts:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

helm upgrade --wait -f values/Database/cql.openebs.yaml my-database-cql bitnami/cassandra --version 7.6.1
```
cql.openebs.yaml:
```
replicaCount: 2
cluster:
  endpointSnitch: GossipingPropertyFileSnitch
image:
  registry: surveily.azurecr.io
  repository: cassandra
  tag: "20210414.1"
  pullSecrets:
    - s-dev-repo
dbUser:
  user: sa
  forcePassword: true
  password: [redacted]
persistence:
  size: 100Gi
  enabled: true
  storageClass: openebs-jiva-default
metrics:
  serviceMonitor:
    enabled: true
    interval: 15s
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 4000m
    memory: 8Gi
```

So as you can see nothing out of the ordinary. Deleting that release keeps the pods in openebs namespace.

**Comment by prateekpandey14** [comment]
@turowicz i just tried installing the bitnami/cassandra chart in my local cluster, since its a Statefulset, uninstalling a chart, will not delete the PVC automatically [its by design in k8s](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations), and you have to delete the pvc using a kubectl command.

Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources.

**Comment by turowicz** [comment]
@prateekpandey14  Well that is not what I am experiencing:

PVCs:

![image](https://user-images.githubusercontent.com/1055391/126449780-4f053298-382a-49b2-ba26-da0dc371d0c9.png)

134 pods in openbs namespace:

![image](https://user-images.githubusercontent.com/1055391/126449824-5e74e6ca-2fb3-43a4-b5f5-140b716b4d7b.png)

**Comment by turowicz** [comment]
also PVs:

![image](https://user-images.githubusercontent.com/1055391/126449969-8c118e01-de08-4356-b2b5-544d07dc0013.png)

**Comment by turowicz** [comment]
On cassandra example:

1. Deployment creates a PVC that automatically gets a PV with a GUID.
2. OpenEbs creates a pod for that GUID PV.
3. Uninstalling removes the PVC and PV, but the pod remains.

**Comment by prateekpandey14** [comment]
>Uninstalling removes the PVC and PV, but the pod remains.

But PVC/PV exists in above screenshot, is that they are not the deleted one ?

So basically just to see the behavior, i tried below steps
1. install charts with  1 Replica count in SC
```
helm install cassandra --set persistence.storageClass=openebs-jiva bitnami/cassandra
```
2. pod and pvc
```
$ kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
cassandra-0   0/1     Running   0          30s

$ kubectl get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-cassandra-0   Bound    pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6   8Gi        RWO            openebs-jiva   2m8s


$ kubectl get pods -n openebs -l openebs.io/persistent-volume=pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6
NAME                                                              READY   STATUS    RESTARTS   AGE
pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6-ctrl-7668c87cd4-465vr    2/2     Running   0            45s
pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6-rep-1-58c8d8c87f-hxk7n   1/1     Running   0          45s

```
3. Uninstall charts will remove the charts only not the PVC (as expected)
```
$ helm uninstall cassandra 
release "cassandra" uninstalled

$ kubectl get pods
NAME          READY   STATUS        RESTARTS   AGE
cassandra-0   1/1     Terminating   0          2m

kubectl get pods
No resources found in default namespace.

kubectl get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-cassandra-0   Bound    pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6   8Gi        RWO            openebs-jiva   7m23s

kubectl get pods -n openebs -l openebs.io/persistent-volume=pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6
NAME                                                              READY   STATUS    RESTARTS   AGE
pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6-ctrl-7668c87cd4-465vr    2/2     Running   0          9m55s
pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6-rep-1-58c8d8c87f-hxk7n   1/1     Running   0          9m48s
```
4. Delete the PVC to delete the Jiva pods
```
$ kubectl delete pvc data-cassandra-0
persistentvolumeclaim "data-cassandra-0" deleted

$ kubectl get pods -n openebs -l openebs.io/persistent-volume=pvc-9ff5b909-f607-4f65-ac28-f12ab6d310e6
No resources found in openebs namespace.

```

**Comment by turowicz** [comment]
I will test the above. 

> But PVC/PV exists in above screenshot, is that they are not the deleted one ?

There are 27 PVs and 134 pods in openebs namespace. For 3 nodes there should be 27x3 pods. This means there are phantom pods for PVs/PVCs that no longer exist.

**Comment by turowicz** [comment]
There is a difference here, on microk8s the storage class is called `openebs-jiva-default`

So I need to deploy with:

```
helm install cassandra --set persistence.storageClass=openebs-jiva-default bitnami/cassandra
```
After `helm uninstall` and deleting the PVC I still have **deployments** and **pods** remaining.

```
kubectl get deployment -n openebs
NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
openebs-apiserver                                1/1     1            1           7m13s
openebs-provisioner                              1/1     1            1           7m13s
openebs-localpv-provisioner                      1/1     1            1           7m13s
openebs-admission-server                         1/1     1            1           7m13s
openebs-snapshot-operator                        1/1     1            1           7m13s
openebs-ndm-operator                             1/1     1            1           7m13s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-2   0/1     1            0           2m6s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-3   0/1     1            0           2m6s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-1   1/1     1            1           2m6s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-ctrl    1/1     1            1           2m6s
```
```
kubectl get pod -n openebs
NAME                                                              READY   STATUS    RESTARTS   AGE
openebs-ndm-rfrlh                                                 1/1     Running   0          7m16s
openebs-apiserver-76494788bc-t5phx                                1/1     Running   0          7m16s
openebs-provisioner-7cb669f466-2xlp8                              1/1     Running   0          7m16s
openebs-localpv-provisioner-66b9f8ff98-qw2sq                      1/1     Running   0          7m16s
openebs-admission-server-84bd769954-mvj54                         1/1     Running   0          7m16s
openebs-snapshot-operator-669696cd5d-5rdlc                        2/2     Running   0          7m16s
openebs-ndm-operator-79d596bd67-p7g72                             1/1     Running   0          7m16s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-2-6497f4b58b-ldtxx   0/1     Pending   0          2m9s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-3-6497f4b58b-2pshx   0/1     Pending   0          2m9s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-rep-1-6497f4b58b-d42rm   1/1     Running   0          2m9s
pvc-39d66aa2-0896-4508-b305-63c11cabec99-ctrl-5bfb7686d8-5s8rm    2/2     Running   0          2m9s
```

**Comment by turowicz** [comment]
Steps to reproduce:

1. `sudo snap install microk8s --channel 1.21/latest --classic`
2. sudo microk8s enable openebs
3. `helm install cassandra --set persistence.storageClass=openebs-jiva-default bitnami/cassandra`
4. `helm uninstall cassandra`
5. `kubectl delete pvc ...` (drop all cassandra pvcs)

**Comment by niladrih** [comment]
@turowicz -- Able to reproduce the issue.

This seems to happen only when all of the replicas (in this case replicass =3, and 1/3 are available) are not available and the PVC is not bound. This might be because you have insufficient nodes in the cluster. You'll need at least 3 to schedule all 3 replicas.

When all the replicas are available, and the PVC is bound, the volume is made available to the application pod. On delete, cleanup occurs successfully.

Tested on Ubuntu 18.04
Microk8s channel 1.21/stable (classic)
OpenEBS version 2.11.0

cc: @prateekpandey14

**Comment by turowicz** [comment]
My cluster has 3 nodes, all available:

![image](https://user-images.githubusercontent.com/1055391/126477589-a5d2d091-a11c-4660-98bd-b455f3fd950c.png)

**Comment by turowicz** [comment]
Each node has 48 cores and 128GB RAM

**Comment by niladrih** [comment]
For the case where all of the replica controller are scheduled, and not pending, the cleanup seems to work as expected, for me.

@turowicz -- Can we jump into a meeting so I may be able to take a closer look at your system over a screen-share? For a meeting, it will be convenient if you joined the Kubernetes workspace. You can use these links to join:
- Join Kubernetes workspace -- https://slack.k8s.io
- OpenEBS channel in the Kubernetes workspace -- https://kubernetes.slack.com/messages/openebs

**Comment by turowicz** [comment]
@niladrih how about just a Google Meet? We use Discord at work instead of Slack.

**Comment by niladrih** [comment]
Sure @turowicz. A Google Meet is good for me. I am at +5:30 UTC (IST). When is a good time for you?

**Comment by niladrih** [comment]
@turowicz -- 11:30 - 12:30 (CEST) tomorrow? Drop me your email address, I'll send you an invite.

**Comment by turowicz** [comment]
Sounds good. info@surveily.com

**Comment by niladrih** [comment]
ADOPTERS.md over at [openebs/openebs](https://github.com/openebs/openebs) --> https://github.com/openebs/openebs/blob/master/ADOPTERS.md

You can add your Adopters' entry by dropping comment here --> https://github.com/openebs/openebs/issues/2719

**Comment by turowicz** [comment]
Thank you for the call, it helped me a lot.

The solution is to never delete PV manually and just remove the PVC. The framework will automatically handle the deletion of PV and the pods.

**Comment by turowicz** [comment]
You can use the following script to get rid of the clutter pods. USE AT OWN RISK.

```
#!/bin/bash

set -e

readarray -t volumes < <(kubectl get pv --no-headers -o custom-columns=":metadata.name")

for fn in `kubectl get deployment -n openebs --no-headers -o custom-columns=":metadata.name"`; do
    if  [[ $fn == pvc-* ]] ;
    then
        target=${fn:0:40}

        if  [[ ! ${volumes[@]} =~ ${target} ]] ;
        then
            kubectl delete deployment $fn -n openebs
        fi
    fi
done

echo "End"
```
