### ISSUE TITLE
Application pod not scheduled to new node when forcefully moved after the node reboot

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#3431]
- After did the poweroff and power on the nodes forcefully moved the application pod to the new node application pod says volume still mount on old node.
- Nodes where powered off
- Powered on the nodes.
- seeing that all application pods are imagepullbackoff state and some of the pods openebs namespace
- scaled down the application pods still it's in imagepullbackoff state
- Force deleted all the pods (including  pods in openebs namespace)
- After that also most of the pods are in imagepullbackoff (most of the pods openebs namespace )
- then checked the NAT rule was disabled enabled the NAT rule
- Most of the application pods came into running state only one application pod stuck in a Container creating state.

Application pod describe 
```
  Events:
  Type     Reason       Age                   From                                   Message
  ----     ------       ----                  ----                                   -------
  Normal   Scheduled    <unknown>             default-scheduler                      Successfully assigned default/gitlab-postgresql-7d55d4bf85-vdp8l to gitlab-k8s-node3.mayalabs.io
  Warning  FailedMount  4m3s                  kubelet, gitlab-k8s-node3.mayalabs.io  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data password-file default-token-v8vk5]: timed out waiting for the condition
  Warning  FailedMount  113s (x10 over 6m6s)  kubelet, gitlab-k8s-node3.mayalabs.io  MountVolume.MountDevice failed for volume "pvc-45dd46a9-1792-4d33-ad21-a851a16bb2b0" : rpc error: code = Internal desc = Volume pvc-45dd46a9-1792-4d33-ad21-a851a16bb2b0 still mounted on node gitlab-k8s-node4.mayalabs.io
  Warning  FailedMount  109s                  kubelet, gitlab-k8s-node3.mayalabs.io  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-v8vk5 data password-file]: timed out waiting for the condition
  ```
  ```
  root@gitlab-k8s-master:~# kubectl get cva -n openebs
NAME                                                                    AGE
pvc-11252e32-61a9-4c68-9c75-0036cde3749a-gitlab-k8s-node1.mayalabs.io   50m
pvc-14ce5cac-2ba3-4ef4-974e-2fdef07fef6b-gitlab-k8s-node5.mayalabs.io   3h32m
pvc-45dd46a9-1792-4d33-ad21-a851a16bb2b0-gitlab-k8s-node4.mayalabs.io   3h50m
pvc-a1b7f35c-c0b2-421c-ba7c-fe8526d381af-gitlab-k8s-node4.mayalabs.io   3h52m
pvc-ad3c659d-493a-4a97-a20e-629647c57947-gitlab-k8s-node6.mayalabs.io   50m

```

**Comment by MBcom** [comment]
We have the same problem after a node is lost. Is there a way to reset this wrong entry?  
```
MountVolume.MountDevice failed for volume "pvc-4806a88c-b866-41b2-8a85-689604b9ad1e" : rpc error: code = Internal desc = Volume pvc-4806a88c-b866-41b2-8a85-689604b9ad1e still mounted on node kube-node-14
```

**Comment by mittachaitu** [comment]
Hi @MBcom , Is kube-node-14 still marked as Ready? Can you share the following output `kubectl get cva -n openebs -l Volname=pvc-4806a88c-b866-41b2-8a85-689604b9ad1e -o yaml`

**Comment by mittachaitu** [comment]
Hi all, In cStor, if we force delete application pod then there will be no chance to cleanup foorprints of the node where the application is previously mounted so it is expected behavior. If the node is no longer available or not part of a cluster deleting `cva` resource associated with the volume will be a workaround. 

CMD: `kubectl delete cva -n openebs <volume-id>` (Where volume-id will be \<pv-name>-\<previous-hostid>).

**Comment by dongsupkim-onepredict** [comment]
> Hi all, In cStor, if we force delete application pod then there will be no chance to cleanup foorprints of the node where the application is previously mounted so it is expected behavior. If the node is no longer available or not part of a cluster deleting `cva` resource associated with the volume will be a workaround.
> 
> CMD: `kubectl delete cva -n openebs <volume-id>` (Where volume-id will be <pv-name>-<previous-hostid>).


Thanks! Btw Is there a way deleting pod to prevent this from happening again? @mittachaitu
