### ISSUE TITLE
OpenEBS csi-node component restarts with error- "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by jj-2020** [openebs/openebs#3433]
## Description

While performing load tests using https://github.com/kubernetes/perf-tests, we observed that the openEBS pod- "openebs-cstor-csi-node" restarts few times. When checking the logs of the container "cstor-csi-plugin", we saw the below error-

fatal error: concurrent map writes

The above load test tries to create few statefulset objects (20-25 pvc at once). The size of the PVC created is around 100Mi.

Below are the environment details-
k8s version: 1.20.10
openebs version: 2.11.0

We wanted to understand why this is happening.

## Expected Behavior

The pod should not restart

## Current Behavior

The pod restarts few times

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by prateekpandey14** [comment]
@jj-2020 can you share the full logs of `cstor-csi-plugin` container.  Any specific use case to create a 100Mi size volume ?

**Comment by jj-2020** [comment]
The logs generated is huge. Adding a part of it-

`fatal error: concurrent map writes

goroutine 134 [running]:
runtime.throw(0x17d1867, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0000215f8 sp=0xc0000215c8 pc=0x4356b2
runtime.mapassign_faststr(0x15b8960, 0xc0002a2210, 0xc000132210, 0x28, 0x0)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc000021660 sp=0xc0000215f8 pc=0x415017
github.com/openebs/cstor-csi/pkg/utils.WaitForVolumeToBeReady(0xc000132210, 0x28, 0xc000db8f00, 0x49)
	/go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:206 +0xec fp=0xc0000216d0 sp=0xc000021660 pc=0x1445dbc
github.com/openebs/cstor-csi/pkg/utils.WaitForVolumeReadyAndReachable(0xc000d58b40, 0x49, 0xc000d58b40)
	/go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:439 +0x42 fp=0xc000021748 sp=0xc0000216d0 pc=0x1446e72
github.com/openebs/cstor-csi/pkg/driver.(*node).NodeStageVolume(0xc0004e2420, 0x1a07c60, 0xc0004921e0, 0xc0000da1e0, 0x0, 0x0, 0x0)
	/go/src/github.com/openebs/cstor-csi/pkg/driver/node.go:158 +0x487 fp=0xc0000219c0 sp=0xc000021748 pc=0x1452787
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1(0x1a07c60, 0xc0004921e0, 0x16fbb80, 0xc0000da1e0, 0xc000963ad8, 0x3, 0x3, 0x40e234)
	/go/src/github.com/openebs/cstor-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5558 +0x86 fp=0xc000021a08 sp=0xc0000219c0 pc=0x8f72c6
github.com/openebs/cstor-csi/pkg/utils.logGRPC(0x1a07c60, 0xc0004921e0, 0x16fbb80, 0xc0000da1e0, 0xc00000e2a0, 0xc00000e2e0, 0xc00062bb78, 0x4ff73d, 0x16b9420, 0xc0004921e0)
	/go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:134 +0x104 fp=0xc000021b18 sp=0xc000021a08 pc=0x1445544
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler(0x173c5c0, 0xc0004e2420, 0x1a07c60, 0xc0004921e0, 0xc0000da180, 0x187c328, 0x1a07c60, 0xc0004921e0, 0xc00095c240, 0x113)
	/go/src/github.com/openebs/cstor-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5560 +0x14b fp=0xc000021b88 sp=0xc000021b18 pc=0x8f50fb
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000702300, 0x1a1cce0, 0xc000621980, 0xc000954000, 0xc0004e2660, 0x25f79c0, 0x0, 0x0, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:1024 +0x501 fp=0xc000021e38 sp=0xc000021b88 pc=0x8c7181
google.golang.org/grpc.(*Server).handleStream(0xc000702300, 0x1a1cce0, 0xc000621980, 0xc000954000, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:1313 +0xd3f fp=0xc000021f68 sp=0xc000021e38 pc=0x8cb26f
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000048ca0, 0xc000702300, 0x1a1cce0, 0xc000621980, 0xc000954000)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:722 +0xa1 fp=0xc000021fb8 sp=0xc000021f68 pc=0x8d8931
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000021fc0 sp=0xc000021fb8 pc=0x464ca1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:720 +0xa1

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0004a20c8)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0004a20c0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/openebs/cstor-csi/pkg/utils.(*nonBlockingGRPCServer).Wait(0xc0004a20c0)
	/go/src/github.com/openebs/cstor-csi/pkg/utils/server.go:72 +0x2d
github.com/openebs/cstor-csi/pkg/driver.(*CSIDriver).Run(0xc00010e370, 0xc00010e370, 0x180b74c)
	/go/src/github.com/openebs/cstor-csi/pkg/driver/service.go:121 +0xab
main.run(0xc0002f4120)
	/go/src/github.com/openebs/cstor-csi/cmd/main.go:92 +0x2f6
main.main.func1(0xc000274000, 0xc000514100, 0x0, 0x4)
	/go/src/github.com/openebs/cstor-csi/cmd/main.go:40 +0x2a
github.com/spf13/cobra.(*Command).execute(0xc000274000, 0xc00010e060, 0x4, 0x4, 0xc000274000, 0xc00010e060)
	/go/src/github.com/openebs/cstor-csi/vendor/github.com/spf13/cobra/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000274000, 0xc0002f4130, 0x17bffbb, 0x6)
	/go/src/github.com/openebs/cstor-csi/vendor/github.com/spf13/cobra/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openebs/cstor-csi/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/go/src/github.com/openebs/cstor-csi/cmd/main.go:70 +0x363

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x260da20)
	/go/src/github.com/openebs/cstor-csi/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/go/src/github.com/openebs/cstor-csi/vendor/k8s.io/klog/v2/klog.go:417 +0xdd

goroutine 20 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x260d840)
	/go/src/github.com/openebs/cstor-csi/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/src/github.com/openebs/cstor-csi/vendor/k8s.io/klog/klog.go:411 +0xd6

goroutine 212 [IO wait]:
internal/poll.runtime_pollWait(0x7f41370927e8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00051ea18, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00051ea00, 0xc000a28000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00051ea00, 0xc000a28000, 0x8000, 0x8000, 0x800010601, 0x0, 0x106010000002e)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000306030, 0xc000a28000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
bufio.(*Reader).Read(0xc00047f800, 0xc00024d618, 0x9, 0x9, 0xc00069fd40, 0x4562d3, 0x7ae71f5fa297d)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x19cb380, 0xc00047f800, 0xc00024d618, 0x9, 0x9, 0x9, 0xc04255f43a115ad9, 0x2138ed2cf, 0x260d360)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00024d618, 0x9, 0x9, 0x19cb380, 0xc00047f800, 0x0, 0x0, 0xc00038e5c0, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/golang.org/x/net/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00024d5e0, 0xc00038e5c0, 0x260d360, 0x0, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc000621980, 0xc00053ee40, 0x187c8f0)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/internal/transport/http2_server.go:458 +0x98
google.golang.org/grpc.(*Server).serveStreams(0xc000702300, 0x1a1cce0, 0xc000621980)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:718 +0xdb
google.golang.org/grpc.(*Server).handleRawConn.func1(0xc000702300, 0x1a1cce0, 0xc000621980)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:679 +0x3f
created by google.golang.org/grpc.(*Server).handleRawConn
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/server.go:678 +0x562

goroutine 73 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0003040f0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:395 +0x122
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0004c4840, 0x0, 0x0)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:513 +0x1cd
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc000702480)
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/internal/transport/http2_server.go:296 +0xcb
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	/go/src/github.com/openebs/cstor-csi/vendor/google.golang.org/grpc/internal/transport/http2_server.go:293 +0x10c1`

**Comment by jj-2020** [comment]
@prateekpandey14 , the pvc of 100Mi were created as part of the perf-tests.

**Comment by pawanpraka1** [comment]
@mittachaitu Can we close this one?

**Comment by mittachaitu** [comment]
It has been fixed via [cstor-csi#168](https://github.com/openebs/cstor-csi/pull/168) and available in OpenEBS 3.1 release.
