### ISSUE TITLE
CustomResourceDefinition Issue

### ISSUE THREAD

**Issue by tayloreisman16** [openebs/openebs#3436]
Hey,

I'm trying to run this command: `kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml` However, it throws an error for CustomResourceDefinitions related to the apiextension for k8s.io.

Is there a version of kubernetes that works? This issue didn't happen at the start of the week.

**Comment by kmova** [comment]
@tayloreisman16 - what is the version your K8s cluster?  The latest operator requires K8s 1.18 or above. 

Older operators are available at: https://github.com/openebs/charts/tree/gh-pages/versioned

**Comment by tayloreisman16** [comment]
I am using 1.15.12. I'll try 1.18.

**Comment by tayloreisman16** [comment]
@kmova I am getting this error still.

![image](https://user-images.githubusercontent.com/18565850/132106216-9183584a-1005-48b8-915d-4c86236eb811.png)

**Comment by kmova** [comment]
@tayloreisman16 - what is the URL you are using to download the required yaml. 

For example to download 2.11.0 operator yaml, you have to either use:
* https://raw.githubusercontent.com/openebs/charts/gh-pages/versioned/2.11.0/openebs-operator.yaml (or)
* https://openebs.github.io/charts/versioned/2.11.0/openebs-operator.yaml

**Comment by pawanpraka1** [comment]
@tayloreisman16 closing this issue. Please reopen if you are still facing the issue.
