### ISSUE TITLE
Single node k8s with OpenEBS

### ISSUE THREAD

**Issue by turowicz** [openebs/openebs#3440]
I know OpenEBS requires 3 replicas to operate but can they all reside on a single node? The reason I'm asking is because I really like the data backup workflow with OpenEBS and Velero. Some of our clients are running single node k8s and we would need that to work in that scenario too.

**Comment by turowicz** [comment]
If I select storageclass `openebs-device` or `openebs-hostpath` would that work?

![image](https://user-images.githubusercontent.com/1055391/133570333-9a6e8c39-cd62-4b75-8d0f-e32a4cb087df.png)

**Comment by kmova** [comment]
Yes, it is a good usecase to work with openebs-device and openebs-hostpath. 

In case you want to run more than one workload on the same node - please use openebs-hostpath.

**Comment by kmova** [comment]
Backup / restore docs with openebs-hostpath and device are here: https://github.com/openebs/dynamic-localpv-provisioner/tree/develop/docs/tutorials/backup_and_restore

**Comment by turowicz** [comment]
@kmova thanks for the answers. What is the overall advantage of this setup in contrast with VolumeSnapshot (GA since 1.20)?

**Comment by turowicz** [comment]
Actually this post gives some insight: https://github.com/ubuntu/microk8s/issues/1686#issuecomment-822061383

**Comment by turowicz** [comment]
@kmova can we put snapshots on network disks? I see MinIO, G3 and AWS options only.

**Comment by turowicz** [comment]
and Azure: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure

**Comment by kmova** [comment]
`VolumeSnapshot` is a feature that is enabled at the per PVC object and is available on storages that support CSI drivers. Depending on the storage provider the implementation details vary on how the snapshots are taken and where they are stored.

By using velero backup and restore - you actually take the backup of the application yamls, pvc and corresponding data into a S3 compatible storage. 

velero provides hooks for storages to do optimized snapshots (on incremental snapshot diff) or actually perform full backups. 

With OpenEBS ZFS which is referenced in the above issue you mentioned - you can use either optimized backups or full backups (restic). With OpenEBS Local PV and Device which are much simpler in implementation - you can only use full backups.

**Comment by turowicz** [comment]
Thanks for the info @kmova!
