### ISSUE TITLE
Grammar Mistakes

### ISSUE THREAD

**Issue by TechSpiritSS** [openebs/openebs#3451]
## Description
I checked Roadmap.md file and it contains some grammatical errors. I would like to fix those.

## Expected Behavior
I expected near perfect grammar in repo maintain by so many people

## Current Behavior
There are many grammatical mistakes I found in the markdown file

## Possible Solution
I would like to fix all those grammatical errors, if you like my work I can help with other files as well.

## Steps to Reproduce
Here is the score of Grammarly after fixing those errors
![image](https://user-images.githubusercontent.com/76687985/136045566-9db0db36-7d00-4571-8be3-6c8db0a29c9b.png)

## Screenshots
This is the score of original markdown file without any changes.
![image](https://user-images.githubusercontent.com/76687985/136045727-e22c6678-843b-4691-8d65-20745d14237a.png)

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by askalik** [comment]
I would like to work on this. 

Is this part of hacktoberfest 2021 efforts?

**Comment by kambojshalabh35** [comment]
May I work on this issue?

**Comment by TechSpiritSS** [comment]
Should I start working on the issue or wait for assign?

**Comment by luharuka** [comment]
@TechSpiritSS can you assign it to me
