### ISSUE TITLE
OpenEBS apiserver CrashLoopBackOff

### ISSUE THREAD

**Issue by buble-gum** [openebs/openebs#3470]
## Description

Status of OpenEBS apiserver is CrashLoopBackOff constantly.
kubectl logs openebs-apiserver-64df4fb57c-876kn -n openebs show error bellow:
+ MAYA_API_SERVER_NETWORK=eth0
+ ip -4 addr show scope global dev eth0
+ grep inet
+ awk '{print $2}'
+ cut -d / -f 1
+ CONTAINER_IP_ADDR=192.168.58.217
+ exec /usr/local/bin/maya-apiserver start '--bind=192.168.58.217'
I1013 14:15:42.305078       1 start.go:149] Initializing maya-apiserver...
I1013 14:15:42.324170       1 start.go:280] Starting maya api server ...
E1013 14:17:12.920638       1 start.go:285] failed to apply resources: [Put "https://10.96.0.1:443/apis/openebs.io/v1alpha1/namespaces/openebs/runtasks/jiva-volume-delete-listreplicapod-default-2.12.1": http2: client connection lost
failed to update resource 'openebs.io/v1alpha1, Resource=runtasks' 'jiva-volume-delete-listreplicapod-default-2.12.1' at 'openebs'
github.com/openebs/maya/pkg/client/k8s/v1alpha1.(*resource).Update
        /go/src/github.com/openebs/maya/pkg/client/k8s/v1alpha1/resource.go:160
github.com/openebs/maya/pkg/client/k8s/v1alpha1.(*ResourceCreateOrUpdater).Apply
        /go/src/github.com/openebs/maya/pkg/client/k8s/v1alpha1/resource.go:279
github.com/openebs/maya/pkg/install/v1alpha1.(*simpleInstaller).Install
        /go/src/github.com/openebs/maya/pkg/install/v1alpha1/installer.go:139
github.com/openebs/maya/cmd/maya-apiserver/app/command.(*CmdStartOptions).setupMayaServer
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:283
github.com/openebs/maya/cmd/maya-apiserver/app/command.Run
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:167
github.com/openebs/maya/cmd/maya-apiserver/app/command.NewCmdStart.func1
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:112
github.com/spf13/cobra.(*Command).execute
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:864
main.main
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/main.go:28
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373 Get "https://10.96.0.1:443/apis/openebs.io/v1alpha1/namespaces/openebs/runtasks/cstor-volume-delete-listcstorvolumecr-default-2.12.1": http2: client connection lost
failed to get resource 'openebs.io/v1alpha1, Resource=runtasks' 'cstor-volume-delete-listcstorvolumecr-default-2.12.1' at 'openebs'
github.com/openebs/maya/pkg/client/k8s/v1alpha1.(*resource).Get
        /go/src/github.com/openebs/maya/pkg/client/k8s/v1alpha1/resource.go:133
github.com/openebs/maya/pkg/client/k8s/v1alpha1.(*ResourceCreateOrUpdater).Apply
        /go/src/github.com/openebs/maya/pkg/client/k8s/v1alpha1/resource.go:268
github.com/openebs/maya/pkg/install/v1alpha1.(*simpleInstaller).Install
        /go/src/github.com/openebs/maya/pkg/install/v1alpha1/installer.go:139
github.com/openebs/maya/cmd/maya-apiserver/app/command.(*CmdStartOptions).setupMayaServer
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:283
github.com/openebs/maya/cmd/maya-apiserver/app/command.Run
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:167
github.com/openebs/maya/cmd/maya-apiserver/app/command.NewCmdStart.func1
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/app/command/start.go:112
github.com/spf13/cobra.(*Command).execute
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:864
main.main
        /go/src/github.com/openebs/maya/cmd/maya-apiserver/main.go:28
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373]
failed to apply resources

## Expected Behavior

OpenEBS apiserver status is Running 
## Current Behavior

Status of OpenEBS apiserver is CrashLoopBackOff
## Your Environment

* `kubectl get nodes`:NAME           STATUS   ROLES    AGE    VERSION    INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-master01   Ready    master   27d    v1.18.20   192.168.100.110   <none>        Ubuntu 20.04.3 LTS   5.4.0-84-generic   docker://19.3.15
k8s-node01     Ready    <none>   27d    v1.18.20   192.168.100.111   <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   docker://19.3.15
k8s-node02     Ready    <none>   27d    v1.18.20   192.168.100.112   <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   docker://19.3.15
k8s-node03     Ready    <none>   5d2h   v1.18.20   192.168.100.113   <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   docker://19.3.15
* 
* `kubectl get pods --all-namespaces`:
NAMESPACE     NAME                                             READY   STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-86bccb9544-flbmr         1/1     Running            0          27d
kube-system   calico-node-f7psz                                1/1     Running            0          27d
kube-system   calico-node-p4nvd                                1/1     Running            0          5d2h
kube-system   calico-node-qnd88                                1/1     Running            3          27d
kube-system   calico-node-slnmv                                1/1     Running            2          27d
kube-system   coredns-66bff467f8-g2g89                         1/1     Running            0          27d
kube-system   coredns-66bff467f8-h4chv                         1/1     Running            0          27d
kube-system   etcd-k8s-master01                                1/1     Running            0          27d
kube-system   kube-apiserver-k8s-master01                      1/1     Running            0          27d
kube-system   kube-controller-manager-k8s-master01             1/1     Running            0          27d
kube-system   kube-proxy-5jb62                                 1/1     Running            0          5d2h
kube-system   kube-proxy-bnknt                                 1/1     Running            0          27d
kube-system   kube-proxy-ffzc5                                 1/1     Running            3          27d
kube-system   kube-proxy-pxrqx                                 1/1     Running            2          27d
kube-system   kube-scheduler-k8s-master01                      1/1     Running            0          27d
openebs       cstor-disk-pool-o4rv-6948b7d5cb-xf4hk            3/3     Running            0          5d1h
openebs       openebs-admission-server-79df45cddb-k8hbn        1/1     Running            3          27d
openebs       openebs-apiserver-64df4fb57c-876kn               0/1     CrashLoopBackOff   445        2d
openebs       openebs-cstor-admission-server-7cf6fc45b-zkjl2   1/1     Running            2          27d
openebs       openebs-cstor-csi-controller-0                   6/6     Running            18         27d
openebs       openebs-cstor-csi-node-69w9w                     2/2     Running            6          27d
openebs       openebs-cstor-csi-node-hzlns                     2/2     Running            4          27d
openebs       openebs-cstor-csi-node-sxr84                     2/2     Running            0          5d2h
openebs       openebs-cstor-cspc-operator-b9997cd56-x7rt4      1/1     Running            2          27d
openebs       openebs-cstor-cvc-operator-856dbbbb77-79g5l      1/1     Running            2          27d
openebs       openebs-localpv-provisioner-b4df858c5-hbpxg      1/1     Running            2          27d
openebs       openebs-ndm-94tl6                                1/1     Running            0          5d2h
openebs       openebs-ndm-jdhrp                                1/1     Running            6          27d
openebs       openebs-ndm-mfb4z                                1/1     Running            4          27d
openebs       openebs-ndm-operator-65f47cd87-qbv2t             1/1     Running            2          27d
openebs       openebs-provisioner-78c5d5767d-4dbqt             1/1     Running            2          27d
openebs       openebs-snapshot-operator-d4486ff5-lr4b7         2/2     Running            6          27d

* `kubectl get services`:
*default       kubernetes                       ClusterIP   10.96.0.1        <none>        443/TCP                  27d
kube-system   kube-dns                         ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   27d
openebs       admission-server-svc             ClusterIP   10.111.2.162     <none>        443/TCP                  27d
openebs       openebs-apiservice               ClusterIP   10.105.189.231   <none>        5656/TCP                 27d
openebs       openebs-cstor-admission-server   ClusterIP   10.102.117.110   <none>        443/TCP                  27d
openebs       openebs-cstor-cvc-operator-svc   ClusterIP   10.104.223.205   <none>        5757/TCP                 27d

* `kubectl get sc`:
* NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
cstor-csi-disk              cstor.csi.openebs.io                                       Delete          Immediate              true                   26d
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  27d
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  27d
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  27d
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  27d

* `kubectl get pv`:
* 
* `kubectl get pvc`:
* 
* OS (from `/etc/os-release`):
* NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* Kernel (from `uname -a`):
* Linux k8s-master01 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Install tools:
* Others:

**Comment by vharsh** [comment]
@buble-gum You are installing a component which has reached it's end of life, we are in the middle of moving our docs from https://docs.openebs.io/ to https://openebs.io/docs/ do share your storage requirements so that we can suggest some other way to install & use OpenEBS.

👋🏼 Aside, we hang out in #openebs-dev & #openebs in the K8s Slack, where we get deep and discuss, do drop in to say hi.
