### ISSUE TITLE
Provisioner Broken In K8S 1.21+ Due to SelfLink Removal

### ISSUE THREAD

**Issue by zach-robinson** [openebs/openebs#3482]
## Description
Provisioner is broken from k8s versions 1.21 onward when clusters are configured with default settings.

## Expected Behavior
Provisioner should be able to provision volumes.

## Current Behavior
In clusters running k8s 1.21 and above, the `metadata.selfLink` field that used to be present in all k8s resource [has been removed](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink). Since the Provisioner relies on this field it is broken in clusters running newer stable versions of k8s.

## Possible Solution
Instead of relying on the selfLink field that no longer exists, links can be built manually from the `APIVersion`, `Kind`, `Name`, and `Namespace` of the resource, or if all that is needed is a cluster-wide UID, the `metadata.uid` field can be used instead.

## Steps to Reproduce
Provision a PVC on a k8s 1.21+ cluster (Jiva is where I encountered this, but it may affect other drivers as well).

## Screenshots

![image](https://user-images.githubusercontent.com/62120488/140961222-8b95e325-5a6e-4d0c-a61c-6f30f299a26a.png)

**Comment by pawanpraka1** [comment]
@shubham14bajpai I think we have fixed this issue, can you confirm?

**Comment by shubham14bajpai** [comment]
@pawanpraka1  This seems to be an old external provisioned jiva engine which got deprecated in 3.0.0 release. 
This should not occur in the latest version of jiva CSI provisioner.

@zach-robinson Can you please mention the version of Openebs deployed? Is this jiva same as https://github.com/openebs/jiva-operator?
