### ISSUE TITLE
Where can I find documentation for v3.0.0

### ISSUE THREAD

**Issue by javiku** [openebs/openebs#3486]
## Description

I can't seem to find documentation for v3.0.0 (only up to 2.21.x), even in the website mentioned in the v3.0.0 release notes (https://openebs.io/docs).

Any hints?

**Comment by kmova** [comment]
Hi @javiku, the docs are being worked on in the engine-specific repositories, to keep the documentation closer to the engines. 

Any specific engine you are looking at?

**Comment by javiku** [comment]
Hi  @kmova , we are integrating several engines in our PaaS: **cStor** for persistence and **local LVM/Hostpath** (depending on the scenarios) for ephemeral storage.

We have been experiencing problems using cStor v2.11.x with what seem to be race conditions that end up blocking a Pod creation/deletion, so we decided to test v3.0.0, but couldn't find any documentation on the website for v3. Following your instructions, I see there is documentation in https://github.com/openebs/cstor-operators/blob/v3.0.x/docs/ ; I'll follow these.

Thank you!
