### ISSUE TITLE
NDM stuck in container creating mode on WSL2

### ISSUE THREAD

**Issue by pukanszkypeter** [openebs/openebs#3487]
Hey, i am really new to this, so can somebody help me?

I am trying to use OpenEBS on my WSL2 on Windows 10, but it is stuck in container creating mode.
The error it gives: "MountVolume.SetUp failed for volume "udev" : hostPath type check failed: /run/udev is not a directory".
And here are my values for it: `https://github.com/pukanszkypeter/progressive-architecture/blob/main/clusters/my-cluster/openebs.yaml`

Everything else is running perfectly:
![kép](https://user-images.githubusercontent.com/44146599/143611823-f1bdb6fc-4648-4a9a-afac-d1a5c9c35d93.png)

Is it a problem with the Windows WSL2 or what am i missing?

Thanks in advance!

**Comment by akhilerm** [comment]
NDM uses udev for fetching the devices connected to the machine. I think WSL2 does not support udev. May be you can try it on a linux VM on your machine.
