### ISSUE TITLE
Add how storage HA works under Getting Started

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#349]
Add an overview for how storage HA works.

**Comment by kmova** [comment]
@AmitKumarDas -- can you provide some pointers into documenting how the HA works with the current code. Specifically what are the aspects of k8s that OpenEBS depends on, etc.,  This will go into the main documentation in a section for High Availability.

**Comment by AmitKumarDas** [comment]
### HA based on various scenarios

#### OpenEBS Jiva Volume with 2 or more replicas and single controller (WIP)

#### OpenEBS Jiva Volume with single replica and single controller (WIP)

- OpenEBS volume controller POD dies/crashes:
- or K8s node that hosts OpenEBS volume controller becomes offline:
  - The controller gets re-scheduled as a new Kubernetes POD. Policies are in place that ensures this is a fast operation. In case of Kubernetes node unavailability, the controller will get scheduled on one of the available node.

- OpenEBS volume replica POD dies/crashes:
  - The replica gets re-scheduled as a new Kubernetes POD on the same K8s node. Policies are in place that does not allow re-scheduling of replica (as replica is tied to a node's resources) to any other node.

- K8s node that hosts OpenEBS volume replica becomes offline:
  - This results in a storage downtime. Policies are in place that does not allow re-scheduling of replica (as replica is tied to a node's resources) to any other node.

```go
// Ensure the replicas stick to its placement node even if the node dies
// In other words DO NOT EVICT these replicas
Tolerations: []k8sApiV1.Toleration{
	k8sApiV1.Toleration{
		Effect:   k8sApiV1.TaintEffectNoExecute,
		Key:      "node.alpha.kubernetes.io/notReady",
		Operator: k8sApiV1.TolerationOpExists,
	},
	k8sApiV1.Toleration{
		Effect:   k8sApiV1.TaintEffectNoExecute,
		Key:      "node.alpha.kubernetes.io/unreachable",
		Operator: k8sApiV1.TolerationOpExists,
	},
},
```
