### ISSUE TITLE
Cannot find any block devices when running command "kubectl get bd -n openebs"

### ISSUE THREAD

**Issue by namnp081296** [openebs/openebs#3490]
Hi Guys,

I'm currently being deployed OpenEBS using cStor as a Data Engine, but after I run **"kubectl apply -f https://openebs.github.io/charts/cstor-operator.yaml"**, I check all the pod in openebs namespace is running, but when I run "kubectl get bd -n openebs" to check the output of Block Device, the output is "No resources found in openebs namespace". 

![problem_about_blockdevice](https://user-images.githubusercontent.com/52060668/145363742-4a6d1877-4724-4794-9db8-5c662275ade6.png)

I don't know the root cause, If anyone has any solutions for my case, please show me how to do it. I'm so appreciated.

Best Regards!

**Comment by mittachaitu** [comment]
Hi @namnp081296, Blockdevices will be listed only if the node has external devices attached to them. Can you share logs of ndm-daemon pod(Pod name starts with openebs-ndm-XYZA? Ex: `kubectl logs  openebs-ndm-vs4mn -n openebs`?

**Comment by namnp081296** [comment]
> Hi @namnp081296, Blockdevices will be listed only if the node has external devices attached to them. Can you share logs of ndm-daemon pod(Pod name starts with openebs-ndm-XYZA? Ex: `kubectl logs openebs-ndm-vs4mn -n openebs`?

Hi @mittachaitu! Thank you for your response, here is my ndm daemon pod log.

![1log](https://user-images.githubusercontent.com/52060668/145380831-d921fba7-1d81-427b-97f2-7ef49325fb29.png)
![2log](https://user-images.githubusercontent.com/52060668/145380856-baa22510-1d87-4c44-9016-4e9b253811fd.png)
![3log](https://user-images.githubusercontent.com/52060668/145380869-19b6ca3b-2db2-4fa6-89ac-15f71c7dcffc.png)
![4log](https://user-images.githubusercontent.com/52060668/145380883-f412cc41-8e5b-4adc-96b2-371af47d43e1.png)

**Comment by akhilerm** [comment]
@namnp081296 Can you also share the output of the following commands
```
$ lsblk
$ udevadm info /dev/sdb
$ udevadm info /dev/sdb1
```

It seems like NDM is not able to detect the UUID of the newly created partition.

**Comment by namnp081296** [comment]
@akhilerm . Sure! Here you go. 
![1log](https://user-images.githubusercontent.com/52060668/145502907-b4f25ea9-3ce0-4b9c-99e3-e127fe51512f.png)
![2log](https://user-images.githubusercontent.com/52060668/145502914-1b489ce9-b2d2-49ce-98c9-2349e852b96c.png)

**Comment by akhilerm** [comment]
Is the host machine CentOS 7, I think you are hitting the issue mentioned [here](https://github.com/openebs/node-disk-manager/blob/develop/cmd/ndm_daemonset/probe/blkidprobe.go#L66-L70). i.e udev not being able to identify `ID_PART_TABLE_UUID` and `ID_PART_ENTRY_UUID`

**Comment by namnp081296** [comment]
@akhilerm. Thank you for your help, so what should I do next now?

**Comment by akhilerm** [comment]
@namnp081296 Raised  a [PR](https://github.com/openebs/node-disk-manager/pull/657) to fix this issue in CentOS 7
