### ISSUE TITLE
[Security] Workflow stale.yml is using vulnerable action actions/stale

### ISSUE THREAD

**Issue by akulpillai** [openebs/openebs#3492]
The workflow stale.yml is referencing action actions/stale using references v1. However this reference is missing the commit [af4072615903a8b031f986d25b1ae3bf45ec44d4](https://github.com/actions/stale/commits/af4072615903a8b031f986d25b1ae3bf45ec44d4) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by kmova** [comment]
Hi @akulpillai -- would you like to go ahead and contribute the fix?

**Comment by vharsh** [comment]
@akulpillai Thanks for creating an issue regarding the same, the OpenEBS community takes security very seriously, do let us know how you keep yourself abreast with all things security(viz some scanners, or just a loose set of channels like mailing-lists, Reddit, HackerNews, etc)


👋🏼 Aside, we hang out in [#openebs-dev](https://kubernetes.slack.com/archives/CUAKPFU78/) in the K8s Slack, where we get deep and discuss, do drop in to say hi.
