### ISSUE TITLE
Unable to deploy a pod on Kubernetes cluster

### ISSUE THREAD

**Issue by akashshah26595** [openebs/openebs#35]
Gives following error on kubectl describe pods:

**Warning**: FailedSync Error syncing pod, skipping: failed to "SetupNetwork" <pod_name> with SetupNetworkError: "Failed to setup network for pod using network plugins \"cni\

**Comment by yudaykiran** [comment]
The issue has been resolved in the latest Vagrantfile.

**Comment by akashshah26595** [comment]
Did you recently update the Vagrantfile? I was working on the version which was merged today(Pull request #29) .

**Comment by kmova** [comment]
Check the output of the command from k8s master:

kubectl get pods --all-namespaces

In case the weave is showing crashing (Issue #26), The fix is merged with Pull Request #31

**Comment by kmova** [comment]
Doesn't have enough information to go on. The latest boxes have been seen to bring up the cluster fine. 
If you see the issue again, provide the logs from the installation.
