### ISSUE TITLE
How do I view the SC/PV data synchronization status

### ISSUE THREAD

**Issue by Ericra95** [openebs/openebs#3501]
I want to see SC/PV different disk data sync status,

Now I don't know where I can see SC/PV disk data synchronization status

can I see openebs-cstor-csi-node-xxxx pod log?

kubectl describe cspc -n openebs

Spec:
  Pools:
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-cbda52e04a23ff12860d113abb45d93e
    Node Selector:
      kubernetes.io/hostname:  node1
    Pool Config:
      Data Raid Group Type:  stripe
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-46ef37bf1843ee543f00937a79237246
    Node Selector:
      kubernetes.io/hostname:  node2
    Pool Config:
      Data Raid Group Type:  stripe
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-e6285c4a328dae104a43ff506e41998e
    Node Selector:
      kubernetes.io/hostname:  node3
    Pool Config:
      Data Raid Group Type:  stripe

**Comment by mittachaitu** [comment]
Hi @Ericra95, You can see data sync status via following kubectl command
- kubectl get cspi -n <openebs_namespace> (Per pool level health, disk usage stats & no.of replicas)
- kubectl get cvr -n <openebs_namespace> (Per volume level health, data occupied on pool)

You can refer to the [blog ](https://blog.mayadata.io/demystifying-disk-usage-in-cstor-pools) for more information about various fields.

**Comment by Ericra95** [comment]
Thanks, I don't want see data occupied 
I want see SC Disk replication progress of different servers

For example, cstor-csi-disk SC replica is 3，I can see different server disk replication percentages，Avoid disk data inconsistency on different servers

kubectl describe sc cstor-csi-disk  -n openebs
Name:            cstor-csi-disk
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"cstor-csi-disk"},"parameters":{"cas-type":"cstor","cstorPoolCluster":"cstor-disk-pool","fsType":"xfs","replicaCount":"3"},"provisioner":"cstor.csi.openebs.io"}

Provisioner:           cstor.csi.openebs.io
Parameters:            cas-type=cstor,cstorPoolCluster=cstor-disk-pool,fsType=xfs,replicaCount=3
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

**Comment by mittachaitu** [comment]
@Ericra95, cStor only supports **synchronous replication** i.e if there is an IO from the application cStor will make sure that IO has been successfully replicated in quorum no.of replicas(here quorum is (3/2)+1 i.e 2) then only it will respond success to application. Currently, we don't have any mechanism to visualize the replication process but it can easily understand by looking at CVR capacity details (`kubectl get cvr -n openebs`), if the used size is same across all CVRs then replication is happening and if you see any inconsistency then status will be `Rebuilding` and subsequently it reaches to `Healthy`.

**Comment by Ericra95** [comment]
@mittachaitu thanks，happy new year

I understand that it is similar to the ratf protocol election, the  cstor-csi-disk SC replica is 3, and the data write is （3/2+1=2）, which means that the data is successfully written.

**Comment by mittachaitu** [comment]
Yes, Not exactly as RAFT algorithm but you can assume in similar lines, here we have target in place of leader to decide success.
