### ISSUE TITLE
orphaned pvc keeps spawning

### ISSUE THREAD

**Issue by albertkohl-monotek** [openebs/openebs#3505]
hello, i HOPE this is a simple issue, i have a jiva PV i setup in a namespace (tds)
i created a deployment (registry specifically) eventually blew it up due to testing. when i blew it up, i just deleted the namespace tds

that caused a bunch of pods to hang terminating, eventually i force deleted it. now the pvs that were being created by it keep lunching as pods in the openebs namespace, and i cant figure out how to remove them.

any adivce would be helpful.

**Comment by pawanpraka1** [comment]
@albertkohl-monotek check this doc https://docs.openebs.io/v1120/docs/next/uninstall.html.
