### ISSUE TITLE
Documentation incorrect for creating Jiva backups

### ISSUE THREAD

**Issue by adamcharnock** [openebs/openebs#3510]
## Description

The Jiva User Guide [states](https://openebs.io/docs/user-guides/jiva-guide#creating-and-managing-backups) the following command can be used to create a backup manually:

    velero backup create <backup_name> --selector '!openebs.io/controller,!openebs.io/replica'

However, the labels used by the `--selector` are not present on the Jiva replica or controller pods. These pods actually use the label `openebs.io/component` with a value of either `jiva-controller` or `jiva-replica`.

## Possible Solution

I suggest the documentation be updated as follows:

    velero backup create <backup_name> --selector 'openebs.io/component notin (jiva-controller, jiva-replica)'

## Screenshots

<img width="1011" alt="Screenshot 2022-01-15 at 13 24 53" src="https://user-images.githubusercontent.com/138215/149623318-e4a9504d-48e7-47a3-b32a-2d6482dfbc69.png">

**Comment by aidapsibr** [comment]
In the latest version of documentation, not even the "bad" documentation exists.
