### ISSUE TITLE
cStor volumes offline, cStor volume replicas are offline or degraded, not possible to mount volumes to PODS.

### ISSUE THREAD

**Issue by OlafHappyson** [openebs/openebs#3534]
Hi,

I'm looking for help. I have small cluster build with Rancher. Latests current versions of OpenEBS and cStor installed via helm charts.

After the installation I was trying to use the cstor storage class to mount some test pod like grafana or empty nginx. Unfortunently Im getting from Kubelet message like: 
**"Unable to attach or mount volumes: unmounted volumes=[task-pv-storage], unattached volumes=[kube-api-access-kdm5 task-pv-storage[]: timed out waiting for the condition"** 
and
**"MountVolume.MountDevice failed for volume "pvc-c20bcaac-acd8-4ce3-8e76-79e46ba9526c" : rpc error: code = Internal desc = Volume pvc-c20bcaac-acd8-4ce3-8e76-79e46ba9526c is not ready: Replicas yet to connect to controller"**

Do you have any idea why it's happening ? I did not find any similar topic, only information that I should contact community for help on OpenEBS page (https://openebs.io/docs/troubleshooting/cstor)

**Comment by mittachaitu** [comment]
Hi @OlafHappyson, Looks like cStor Volume is Unhealthy(This might be because replicas are not yet connected to target). Can you share the following outputs:
- kubectl get cv -n openebs
- kubectl get cvr -n openebs
- kubectl get po -n openebs
- kubectl logs <cstor_pod_name_where_volume_replica_exist> -c cstor-pool -n openebs
- kubectl logs <cstor_pod_name_where_volume_replica_exist> -c cstor-pool-mgmt -n openebs

I may request few other outputs if unable to figure out the issue from above outputs

**Comment by OlafHappyson** [comment]
Hello @mittachaitu ,
Thanks for reply, here are the outputs:
`➜  ~ kubectl get cv -n openebs
NAME                                       CAPACITY   STATUS   AGE
pvc-e168a51b-aeea-47ab-8f74-905cfb427809   0          Init     45s`
`➜  ~ kubectl get cvr -n openebs
NAME                                                            ALLOCATED   USED   STATUS    AGE
pvc-e168a51b-aeea-47ab-8f74-905cfb427809-cstor-disk-pool-mx7f   6K          6K     Offline   58s
pvc-e168a51b-aeea-47ab-8f74-905cfb427809-cstor-disk-pool-sj68   6K          6K     Offline   58s`
`➜  ~ kubectl get po -n openebs
NAME                                                              READY   STATUS    RESTARTS      AGE
cstor-disk-pool-mx7f-6d7d9477c9-gc4lx                             3/3     Running   0             6m39s
cstor-disk-pool-sj68-88b48dd59-wrfvr                              3/3     Running   0             6m39s
cstor-disk-pool-vszg-7f57dfdfd8-zwp8f                             3/3     Running   0             6m38s
openebs-cstor-admission-server-7fcb956884-tdlwj                   1/1     Running   1 (10m ago)   11m
openebs-cstor-csi-controller-0                                    6/6     Running   0             11m
openebs-cstor-csi-node-4hck2                                      2/2     Running   0             11m
openebs-cstor-csi-node-xsrlc                                      2/2     Running   0             11m
openebs-cstor-csi-node-zbgv4                                      2/2     Running   0             11m
openebs-cstor-cspc-operator-767457978c-8gs5k                      1/1     Running   0             11m
openebs-cstor-cvc-operator-559d96bf8b-dz8h5                       1/1     Running   0             11m
openebs-localpv-provisioner-7698c49bbf-nv4bl                      1/1     Running   0             11m
openebs-ndm-29jv9                                                 1/1     Running   0             11m
openebs-ndm-ddb5c                                                 1/1     Running   0             11m
openebs-ndm-ncv9w                                                 1/1     Running   0             11m
openebs-ndm-operator-69b5fcf66b-j76rz                             1/1     Running   0             11m
pvc-e168a51b-aeea-47ab-8f74-905cfb427809-target-f84d7ddcc-nswq9   3/3     Running   0             64s`

About the logs Im not sure if this is correct output:
`➜  ~ kubectl logs cstor-disk-pool-vszg-7f57dfdfd8-zwp8f -c cstor-pool -n openebs
Disabling dumping core
sleeping for 2 sec
2022-05-04/08:30:18.552 disabled auto import (reading of zpool.cache)
physmem = 16467102 pages (62.82 GB)`

`➜  ~ kubectl logs cstor-disk-pool-vszg-7f57dfdfd8-zwp8f -c cstor-pool -n openebs
Disabling dumping core
sleeping for 2 sec
2022-05-04/08:30:18.552 disabled auto import (reading of zpool.cache)
physmem = 16467102 pages (62.82 GB)
➜  ~ kubectl logs cstor-disk-pool-vszg-7f57dfdfd8-zwp8f -c cstor-pool-mgmt -n openebs
+ rm /usr/local/bin/zrepl
+ pool_manager_pid=8
+ trap _sigint INT
+ trap _sigterm SIGTERM
+ wait 8
+ /usr/local/bin/pool-manager start
E0504 08:30:19.264523       8 pool.go:112] zpool status returned error in zrepl startup : exit status 1
I0504 08:30:19.264670       8 pool.go:113] Waiting for pool container to start...
I0504 08:30:19.276998       8 controller.go:109] Setting up event handlers for CSPI
I0504 08:30:19.277438       8 controller.go:118] will set up informer event handlers for cvr
I0504 08:30:19.277802       8 new_restore_controller.go:106] Setting up event handlers for restore
I0504 08:30:19.293769       8 controller.go:111] Setting up event handlers for backup
I0504 08:30:19.299538       8 runner.go:38] Starting CStorPoolInstance controller
I0504 08:30:19.299563       8 runner.go:41] Waiting for informer caches to sync
I0504 08:30:19.306997       8 common.go:263] CStorPool found: [cannot open 'name': no such pool ]
I0504 08:30:19.307057       8 run_restore_controller.go:38] Starting CStorRestore controller
I0504 08:30:19.307066       8 run_restore_controller.go:41] Waiting for informer caches to sync
I0504 08:30:19.307076       8 run_restore_controller.go:53] Started CStorRestore workers
I0504 08:30:19.307099       8 runner.go:38] Starting CStorBackup controller
I0504 08:30:19.307126       8 runner.go:41] Waiting for informer caches to sync
I0504 08:30:19.307098       8 runner.go:39] Starting CStorVolumeReplica controller
I0504 08:30:19.307140       8 runner.go:53] Started CStorBackup workers
I0504 08:30:19.307150       8 runner.go:42] Waiting for informer caches to sync
I0504 08:30:19.307169       8 runner.go:47] Starting CStorVolumeReplica workers
I0504 08:30:19.307189       8 runner.go:54] Started CStorVolumeReplica workers
I0504 08:30:19.399816       8 runner.go:45] Starting CStorPoolInstance workers
I0504 08:30:19.399873       8 runner.go:51] Started CStorPoolInstance workers
I0504 08:30:19.420382       8 handler.go:442] Added Finalizer: cstor-disk-pool-vszg, c036ed9b-59a4-44c4-b770-7dd703a46d9d
I0504 08:30:19.434975       8 import.go:73] Importing pool c036ed9b-59a4-44c4-b770-7dd703a46d9d cstor-cd9e6c7c-2c85-4e1c-9703-daed6d26d91d
E0504 08:30:19.442111       8 import.go:94] Failed to import pool by reading cache file: cannot import 'cstor-cd9e6c7c-2c85-4e1c-9703-daed6d26d91d': no such pool available
 : exit status 1
E0504 08:30:19.463121       8 import.go:114] Failed to import pool by scanning directory: 2022-05-04/08:30:19.448 Iterating over all the devices to find zfs devices using blkid
2022-05-04/08:30:19.454 Iterated over cache devices to find zfs devices
cannot import 'cstor-cd9e6c7c-2c85-4e1c-9703-daed6d26d91d': no such pool available
 : exit status 1
I0504 08:30:19.483806       8 create.go:41] Creating a pool for cstor-disk-pool-vszg cstor-cd9e6c7c-2c85-4e1c-9703-daed6d26d91d
I0504 08:30:19.818143       8 event.go:282] Event(v1.ObjectReference{Kind:"CStorPoolInstance", Namespace:"openebs", Name:"cstor-disk-pool-vszg", UID:"c036ed9b-59a4-44c4-b770-7dd703a46d9d", APIVersion:"cstor.openebs.io/v1", ResourceVersion:"1953602", FieldPath:""}): type: 'Normal' reason: 'Created' Pool created successfully`

**Comment by OlafHappyson** [comment]
Anyway I saw another action happend. After I created the poolcluster I have new Blockdevices available. Should I also set them to the poolcluster ? 

➜  ~ kubectl get blockdevice -n openebs
NAME                                           NODENAME   SIZE            CLAIMSTATE   STATUS     AGE
blockdevice-013502c52aa5140a292cff54fb07a7e5   node3      5397163278336   Claimed      Active     23m
blockdevice-15c3ce20a1981bd2bd15c9921282e839   node1      3599451029504   Claimed      Active     23m
blockdevice-433352992577e922bfd83ad51de5676e   node3      5397152792576   Unclaimed    Active     18m
blockdevice-c74bce22d236ef2a406fad5c0384f1f2   node2      3599451029504   Claimed      Active     23m
blockdevice-f139c908b809a7d2db31a081b15436a0   node2      3599440543744   Unclaimed    Inactive   17m
blockdevice-fc069971412a2e0746986fa55714a424   node1      3599440543744   Unclaimed    Inactive   17m

**Comment by OlafHappyson** [comment]
In a description of CVR  is this: 
Warning  SyncFailed  105s (x254 over 126m)  CStorVolumeReplica  failed to sync CVR error: unable to update snapshot list details in CVR: failed to get the list of snapshots: Output: failed listsnap command for cstor-cd9e6c7c-2c85-4e1c-9703-daed6d26d91d/pvc-e168a51b-aeea-47ab-8f74-905cfb427809 with err 11
Error: exit status 11

**Comment by Ab-hishek** [comment]
Hi @OlafHappyson. I am suspecting it to a network issue. Can you confirm whether the output of the following from above are still the same of not?
- kubectl get cv -n openebs
- kubectl logs <cstor_pod_name_where_volume_replica_exist> -c cstor-pool -n openebs(Is there just the above 2-3 lines of logs present?)
- kubectl logs <cstor_pod_name_where_volume_replica_exist> -c cstor-pool-mgmt -n openebs

Also, to just cross confirm you can ping `pvc-c20bcaac-acd8-4ce3-8e76-79e46ba9526c-target-XXX`  pod IP(present inside openebs namespace) from inside any cstor-disk-pool pod container?

**Comment by OlafHappyson** [comment]
Yes, I came to the same conclusion. The issue combined access rights and network configuration.

**Comment by Ab-hishek** [comment]
Can you just mention the steps that you performed to resolve the issues so that it can benefit others who encounter the same issue. After that we can close the issue.

**Comment by OlafHappyson** [comment]
Don't remember exact steps, but I reviewed the network configuration of Rancher and configured correct interface and IP settings. After that, I assigned ownership of the docker processes to the account which were working with the docker and RKE cluster. 
After that it started working.

**Comment by pachecux** [comment]
I'm facing the same situation,  any ideia to fix it ?

**Comment by bnaigaonkar** [comment]
I'm facing same issue; but sometimes I have seen cstor volumes are Healthy when I delete the **pvc** pod. 
It looks like the intermittent issue.
What could be the reason and any idea to fix this issue?

**Comment by bnaigaonkar** [comment]
> I'm facing same issue; but sometimes I have seen cstor volumes are Healthy when I delete the **pvc** pod. It looks like the intermittent issue. What could be the reason and any idea to fix this issue?

In my case issue is because of nft rules, issue fix by removing/flush nft rules.
