### ISSUE TITLE
can local-provisioner specifies some nodes provide disk but else not via nodeAffinityLabels feature in hostpathClass at values.yaml?

### ISSUE THREAD

**Issue by regain0001** [openebs/openebs#3539]

**Comment by regain0001** [comment]
that is,I have just applied the openebs in my clusters.now I want to specifies some nodes in my k8s cluster provide localPV via hostpath function but else not.For example,there are 3 nodes in my cluster, just called A,B,C, now I want to apply some application(e.g. strimzi kafka) using localPV. but I just want the localPVs in node A,B,not C.What should I do?

**Comment by regain0001** [comment]
I just modify the nodeAffinityLabels in values.yaml at jsonpath(localprovisioner.hostpathclass.nodeAffinityLabels),then specify the key "openebs.io/fit-kafka".  Then I just label node A "openebs.io/fit-kafka:yes",label node B "openebs.io/fit-kafka:yes2",and not label node C. Then I create a strimzi kafka cluster which zookeeper relicas is 2. I expect that the localPV provisioner can create hostpath and localPV just in node A and node B,therefore the kafka cluster can be created normally.But one of the pvcs which  have "volume.kubernetes.io/selected-node:node C" annotations,and the pvc keep the pending status.
the log of the openebs-localpv-provisioner :
I0608 03:06:36.653060       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test", Name:"data-kafkatest-zookeeper-1", UID:"c8199ed9-51b4-42ad-9698-7b3d52963724", APIVersion:"v1", ResourceVersion:"1668815", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "local-storage": [failed to build Pod object: missing node label values

**Comment by niladrih** [comment]
@regain0001 -- Hi, I'm a bit late to this issue. That is not the intended use for NodeAffinityLabels. You can read more here:
- https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/hostpath/nodeaffinitylabels.md

What you're looking for is AllowedTopologies:
- https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/hostpath/allowedtopologies.md

This should unblock you if you're still blocked on this. Feel free to reopen this if you need more help with this.
