### ISSUE TITLE
No. of OpenEBS volume replica(s) should be determined based on the environment K8s is running

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#354]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Details

NOTE - OpenEBS volume can be created with one or more no of replicas. 
NOTE - Each OpenEBS  replica is tied to a K8s minion.

A K8s cluster can have one or more minions. Hence, it is desirable to create a OpenEBS volume 
with one replica incase the cluster has single minion. 

This feature can be first tried with Kubeminion which comprises of single node only.
Eventually, this feature can be tried with K8s clusters comprising of single minion.

OpenEBS volume will create 2 replicas by default in a K8s cluster comprising of more than 1 minion.

**Comment by kmova** [comment]
The replicas are made configurable via the StorageClass - ReplicaCount policy. There are currently no plans to auto detect and configure  the replica count.

**Comment by junneyang** [comment]
set replicaCount = 0 is ok?

**Comment by kmova** [comment]
valid values for replicaCount is 1 or higher. 

To provide high availability and protection against node failures, it is recommended to have at least 3 worker nodes in the cluster and set the replicaCount =3. 

(The default value is 3)
