### ISSUE TITLE
Can't active disk on centos 8

### ISSUE THREAD

**Issue by typro33333** [openebs/openebs#3566]
Hi,
Os: centos 8
Version openebs: lastest
I have problem about my block device not active and i have used command `watch -n  1 kubectl get bd -n openebs` i see it loop active and inactive. I'm using helm to deploy openEBS use technical cstor . i have already research all documents about cstor and ndm on openEBS to resolve this problem. 
![Screen Shot 2022-09-06 at 10 43 54](https://user-images.githubusercontent.com/62330937/188542722-67375a69-6f78-40ba-9b8f-782f9f2d1d7f.png)
Thanks

**Comment by typro33333** [comment]
I fixed it.

**Comment by NicoG60** [comment]
> I fixed it.

Hi @typro33333 How have you fixes it? I have a similar issue

**Comment by typro33333** [comment]
@NicoG60  I remember i res issue it follow by: 
1. All block device on all node can't in partition boot and root.
2. All block need format disk and no have include any file system on it.
