### ISSUE TITLE
 Make OpenEBS provisioner CSI Complaint 

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#357]
OpenEBS provisioner should be CSI complaint. Specification can be found here https://github.com/container-storage-interface/spec

**Comment by shirkevich** [comment]
CSI specification ver 0.1.0 is available for some time already.
https://github.com/container-storage-interface/spec/blob/master/spec.md
And initial CSI support are shipped to k8s as alpha from 1.9, and as experimental to mesos from 1.5
Want it badly!

**Comment by jayunit100** [comment]
any progress on this ?  kube 1.13 makes CSI GA,

**Comment by muratkars** [comment]
Hi @jayunit100 CSI is priorities in the roadmap and it's planned for the OpenEBS 0.9 release, which is the next big release.
