### ISSUE TITLE
Binding to 2 different pods with the same class and pvc+pv have different content for folders

### ISSUE THREAD

**Issue by goodidea-kp** [openebs/openebs#3574]
data from pod1

```
/videos/13 # ls -la
total 1731068
drwxr-xr-x    2 root     root          4096 Sep 22 19:07 .
d---------    3 root     root          4096 Sep 22 18:50 ..
-r--------    1 root     root     1749335740 Sep 22 19:00 Glenelg1663891186515.webm
-r--------    1 root     root      23264043 Sep 22 19:07 how-to-cut1663891658916.webm
```
data from pod2

```
root@av-reader-d9b95fbc4-s88xk:/videos/13# ls -la
total 22728
drwxr-xr-x 2 root root     4096 Sep 21 23:34 .
drwxr-xr-x 4 root root     4096 Sep 21 23:34 ..
-r-------- 1 root root 23264043 Sep 21 23:34 how-to-cut1663803267024.webm
root@av-reader-d9b95fbc4-s88xk:/videos/13# 
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openebs-pv-video
spec:
  capacity:
    storage: 9Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: cstor-csi      #
  hostPath: #we can use this only ib debug mode
    path: "/videos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: openebs-pvc-video
spec:
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  storageClassName: cstor-csi  #must match with pv storage class
  volumeMode: Filesystem
  resources:
    requests:
      storage: 9Gi
```

## Description

Not sure what I am doing wrong, I used to have Ceph and don't see problems like that.
Later I made both pv and PVC the same `ReadWriteMany` and after scaling 'ag' I can see the same files...but from another deployment 'av' pods, still empty...After scaling other deployments 'av' up to 2 one pods can see files, other is still empty

## Expected Behavior

Files systems must be synchronized. Please fix it asap. I need to start service on October 1

## Your Environment

* `kubectl get nodes`:
* NAME         STATUS                     ROLES           AGE    VERSION
fromkos-01   Ready,SchedulingDisabled   control-plane   33d    v1.24.4
fromkos-02   Ready                      <none>          33d    v1.24.4
fromkos-04   Ready                      <none>          5d8h   v1.24.3
fromkos-05   Ready                      <none>          33d    v1.24.4
fromkos-06   Ready                      <none>          30d    v1.24.4
fromkos-07   Ready                      <none>          33d    v1.24.4
* `kubectl get pods --all-namespaces`:
* default         ag2-77d7f54fc7-nk5sf                                              1/1     Running            0                 52m
default         av-reader-d9b95fbc4-s88xk                                         1/1     Running            0                 13m
default         fromkos-lb-7b4f9888cf-8zr2z                                       1/1     Running            0                 22m
default         fromkos1-75f64974f4-zqrz6                                         1/1     Running            0                 2d1h
default         fromkos2-5b98cf8c65-qlfnh                                         1/1     Running            0                 2d2h
default         postgres-database-0                                               1/1     Running            0                 5d3h
default         rsyslog-8598b8df69-jhxkz                                          1/1     Running            11                5d9h
ingress-nginx   ingress-nginx-admission-create-f2pm6                              0/1     Completed          0                 33d
ingress-nginx   ingress-nginx-controller-6dc865cd86-8lz89                         1/1     Running            11                5d9h
kube-system     coredns-df887664c-m6tkq                                           1/1     Running            3                 35h
kube-system     coredns-df887664c-rx5kx                                           1/1     Running            0                 35h
kube-system     etcd-fromkos-01                                                   1/1     Running            14                33d
kube-system     kube-apiserver-fromkos-01                                         1/1     Running            93                33d
kube-system     kube-controller-manager-fromkos-01                                1/1     Running            3                 33d
kube-system     kube-proxy-89jbv                                                  1/1     Running            10                5d8h
kube-system     kube-proxy-8nshv                                                  1/1     Running            17                33d
kube-system     kube-proxy-dvf5r                                                  1/1     Running            8                 30d
kube-system     kube-proxy-swjqk                                                  1/1     Running            26                33d
kube-system     kube-proxy-v74lf                                                  1/1     Running            1                 33d
kube-system     kube-proxy-z2jvt                                                  1/1     Running            1                 33d
kube-system     kube-scheduler-fromkos-01                                         1/1     Running            3                 33d
kube-system     weave-net-6f42z                                                   2/2     Running            34                33d
kube-system     weave-net-bd99q                                                   2/2     Running            3 (25d ago)       33d
kube-system     weave-net-f9qkn                                                   2/2     Running            53                33d
kube-system     weave-net-rpjqm                                                   2/2     Running            19 (5d8h ago)     28d
kube-system     weave-net-wxkss                                                   2/2     Running            3                 33d
kube-system     weave-net-x8q76                                                   2/2     Running            21                5d8h
openebs         cspc-operator-9c5b677fd-fb9f9                                     1/1     Running            1                 32d
openebs         cstor-storage-mtbs-7d4775b475-5d8x6                               3/3     Running            0                 5d9h
openebs         cstor-storage-x8d7-d88dc9c6-gbfk9                                 3/3     Running            3                 64m
openebs         cvc-operator-79ff448f8-sd2bj                                      1/1     Running            1                 32d
openebs         openebs-cstor-admission-server-54d66cd75d-2z6rb                   1/1     Running            1                 32d
openebs         openebs-cstor-csi-controller-0                                    6/6     Running            7                 32d
openebs         openebs-cstor-csi-node-78z7l                                      2/2     Running            2                 33d
openebs         openebs-cstor-csi-node-8klvq                                      2/2     Running            34                33d
openebs         openebs-cstor-csi-node-p7fsx                                      2/2     Running            16                30d
openebs         openebs-cstor-csi-node-t5grp                                      2/2     Running            20                5d8h
openebs         openebs-cstor-csi-node-vhmrq                                      2/2     Running            52                33d
openebs         openebs-localpv-provisioner-dd977fdd5-zbm5w                       1/1     Running            50                32d
openebs         openebs-ndm-6mq68                                                 1/1     Running            19 (40m ago)      5d8h
openebs         openebs-ndm-cluster-exporter-768c998b94-bx5lq                     1/1     Running            11                5d9h
openebs         openebs-ndm-fr7tq                                                 1/1     Running            13 (5d8h ago)     30d
openebs         openebs-ndm-gqstb                                                 1/1     Running            8 (38m ago)       44h
openebs         openebs-ndm-jnnvs                                                 1/1     Running            2 (25d ago)       33d
openebs         openebs-ndm-node-exporter-2tbcn                                   1/1     Running            17                33d
openebs         openebs-ndm-node-exporter-6lpdp                                   0/1     CrashLoopBackOff   235 (2m23s ago)   43h
openebs         openebs-ndm-node-exporter-6snd2                                   1/1     Running            1                 33d
openebs         openebs-ndm-node-exporter-95dgc                                   1/1     Running            26                33d
openebs         openebs-ndm-node-exporter-k4djv                                   1/1     Running            8                 30d
openebs         openebs-ndm-operator-6b4dc87588-wwtk4                             1/1     Running            1                 27d
openebs         openebs-ndm-tbmdd                                                 1/1     Running            10 (40m ago)      41h
openebs         pvc-397b45d8-e2da-48cd-a108-962adb18cd7b-target-754cdd8dcbgrkll   3/3     Running            0                 5d
openebs         pvc-40184bf4-341d-4d64-82af-d99e0fa3e134-target-7bf7787f676pcvr   3/3     Running            0                 5d4h
openebs         pvc-495cc235-1107-45b0-bd33-0aec5bf4c14e-target-85699c8c4fk2fgk   3/3     Running            0                 5d
openebs         pvc-c11fa256-8bc4-48e2-bfba-e0574c756804-target-7cc5d9d97df5xgf   3/3     Running            0                 35h
openebs         pvc-f3824b12-e035-441d-9219-cebb8f5d8000-target-fff5bb6d-9gbmt    3/3     Running            0                 5d
* `kubectl get services`:
* NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
ag2-service             ClusterIP      10.101.227.191   <none>         8080/TCP                     35h
av-reader-service       ClusterIP      10.110.226.210   <none>         8000/TCP                     14m
fromkos-lb              LoadBalancer   10.97.121.247    192.168.1.99   443:31697/TCP,80:31311/TCP   27d
fromkos1                ClusterIP      10.101.163.45    <none>         80/TCP                       27d
fromkos2                ClusterIP      10.108.173.167   <none>         80/TCP                       27d
kubernetes              ClusterIP      10.96.0.1        <none>         443/TCP                      33d
postgres-loadbalancer   ClusterIP      10.102.134.218   <none>         5432/TCP                     5d3h
rsyslog-service         ClusterIP      10.107.101.238   <none>         514/TCP,514/UDP              28d

* `kubectl get sc`:
* cstor-csi (default)   cstor.csi.openebs.io   Delete          Immediate              true                   33d
openebs-device        openebs.io/local       Delete          WaitForFirstConsumer   false                  33d
openebs-hostpath      openebs.io/local       Delete          WaitForFirstConsumer   false                  33d
* `kubectl get pv`:
* NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                  STORAGECLASS   REASON   AGE
openebs-pv-video                           9Gi        RWX            Retain           Available                                          cstor-csi               31m
pvc-40184bf4-341d-4d64-82af-d99e0fa3e134   1Gi        RWO            Delete           Bound       default/pvc-data-postgres-database-0   cstor-csi               5d4h
pvc-c11fa256-8bc4-48e2-bfba-e0574c756804   9Gi        RWO            Retain           Bound       default/openebs-pvc-video              cstor-csi               36h
* `kubectl get pvc`:
* NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
openebs-pvc-video              Bound    pvc-c11fa256-8bc4-48e2-bfba-e0574c756804   9Gi        RWO            cstor-csi      36h
pvc-data-postgres-database-0   Bound    pvc-40184bf4-341d-4d64-82af-d99e0fa3e134   1Gi        RWO            cstor-csi      5d4h
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* different pods have Linix or Ubuntu different versions
* Install tools: kubeadm
* Others: I am using 'crio'

**Comment by pawanpraka1** [comment]
@goodidea-kp readwrite many is not supported by cstor storage engine.

**Comment by goodidea-kp** [comment]
[https://openebs.io/docs/concepts/rwm](url)

**Comment by pawanpraka1** [comment]
@goodidea-kp you need to use dynamic nfs provsioner if you want to use readwritemany (see this https://github.com/openebs/dynamic-nfs-provisioner). Cstor does not support readwritemany.
