### ISSUE TITLE
Tutorial not working as expected due to deprecated informatio n

### ISSUE THREAD

**Issue by koss822** [openebs/openebs#3577]
## Description
I was following tutorial https://openebs.io/docs/main/user-guides/localpv-device#optional-block-device-tagging and could not mount the volume.

```
  Warning  ProvisioningFailed    2s               openebs.io/local_openebs-localpv-provisioner-8967d765d-c5h5k_63f8aaab-053a-45c4-91f0-35f16a14525e  failed to provision volume with StorageClass "local-device": Cannot use deprecated "BlockDeviceTag" config option
```

## Expected Behavior
create volume or document how to create it correctly

## Current Behavior
deprecated function

## Possible Solution
better documentation

## Steps to Reproduce
follow https://openebs.io/docs/main/user-guides/localpv-device

## Your Environment
* OS (from `/etc/os-release`):
Ubuntu, Microk8s

**Comment by yuweni99** [comment]
Excuse me, have you solved this problem? I had the same problem

**Comment by lichensky** [comment]
In local provisioner logs you can find that `BlockDeviceTag` has been deprecated in favor of the `BlockDeviceSelectors`. The usage is described [here](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/device/blockdeviceselectors.md).

The website docs should be updated though.

**Comment by yuweni99** [comment]
> In local provisioner logs you can find that `BlockDeviceTag` has been deprecated in favor of the `BlockDeviceSelectors`. The usage is described [here](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/device/blockdeviceselectors.md).
> 
> The website docs should be updated though.



> 在本地供应商日志中，您可以发现`BlockDeviceTag`已弃用，取而代之的是`BlockDeviceSelectors`. 用法在[此处](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/device/blockdeviceselectors.md)描述。
> 
> 网站文档应该更新。

Thank you very much for your reply

**Comment by yuweni99** [comment]
> In local provisioner logs you can find that `BlockDeviceTag` has been deprecated in favor of the `BlockDeviceSelectors`. The usage is described [here](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/tutorials/device/blockdeviceselectors.md).
> 
> The website docs should be updated though.

Thank you very much for your reply

**Comment by koss822** [comment]
Thanks, seems to be working.
I will leave a ticket open since documentation needs to be updated.

**Comment by koss822** [comment]
Documentation is still deprecated

**Comment by MahmoodKamali** [comment]
I have the same problem and the documentation is deprecated and not working properly. other links are the same. Unfortunately, openEBS documentation is very weak.

**Comment by koss822** [comment]
Documentation is still deprecated, is it worked on this issue? It is stale for months.

**Comment by koss822** [comment]
the tutorial should be fixed

**Comment by niladrih** [comment]
Hi folks, I've updated the local-device guide on the website. Closing this one.
