### ISSUE TITLE
Upgrade instructions for getting to 1.12.0 has a dead link that prevents upgrading

### ISSUE THREAD

**Issue by ryanrolds** [openebs/openebs#3587]
## Description

I'm trying to upgrade from 1.9.0 to 1.12.0. I'm following the [kubectl upgrade instructions](https://github.com/openebs/openebs/tree/main/k8s/upgrades/1.x.0-1.12.x#upgrade-using-kubectl-using-openebs-operatoryaml) and the URL for the `openebs-operator.yaml` returns a 404.

## Expected Behavior

The 1.12.0 `openebs-operator.yaml` is returned.

## Current Behavior

A 404 is returned.

## Possible Solution

Don't know, unable to find valid URL to the 1.12.0 version.

## Steps to Reproduce

`kubectl apply -f https://openebs.github.io/charts/1.12.0/openebs-operator.yaml`

**Comment by shubham14bajpai** [comment]
Hi @ryanrolds I am not sure why the charts page is not picking up the yaml. The yamls are picked via automation from openebs/charts repo on the `gh-pages` branch. 
Meanwhile you can use this yaml to upgrade: https://github.com/openebs/charts/blob/gh-pages/versioned/1.12.0/openebs-operator.yaml

**Comment by ryanrolds** [comment]
Thank you. That is exactly what I needed. 

Would you be OK if I made a PR that updated the dead links? Or is the plan to fix what the dead URLs point to?
