### ISSUE TITLE
[CSTOR] after reboot issue on node, some pods can't attach volume.

### ISSUE THREAD

**Issue by allanian** [openebs/openebs#3589]
Hello, i get reboot issue on 1 of my CSTOR node, pods cant attach volumes.
I have cluster with 3 cstor nodes.
Was trying to restart pods:
1) cstor-disk-pool1
2) openebs-cstor-admission-server-588f985bc8-47gh5
3) openebs-cstor-csi-controller-0
4) openebs-ndm-6mp2k on node when pod trying to start
5) openebs-ndm-operator-69b5fcf66b-4brtn
6) openebs-cstor-csi-node-6zjk5 on node when pod trying to start
7) pvc-e91190f9-f453-475e-bb77-e886522b3070-target-7ff8b6fcf-dqcnv

# DESCRIBE POD
```
kubectl -n infra-allure describe po allure-ee-rabbitmq-0
Events:
  Type     Reason       Age                 From     Message
  ----     ------       ----                ----     -------
  Warning  FailedMount  11m (x20 over 95m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config-volume healthchecks data kube-api-access-27rjp]: timed out waiting for the condition
  Warning  FailedMount  30s (x48 over 97m)  kubelet  MountVolume.MountDevice failed for volume "pvc-d4d4cdaa-59c2-447a-832a-78d2d92d43d4" : rpc error: code = Internal desc = format of disk "/dev/disk/by-path/ip-10.107.207.51:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-d4d4cdaa-59c2-447a-832a-78d2d92d43d4-lun-0" failed: type:("ext4") target:("/data/k8s/plugins/kubernetes.io/csi/cstor.csi.openebs.io/0cfa738b104e1ec933a3895c59a47ec21a281e5da84ba0bce1ffed425dc0b8a5/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.44.1 (24-Mar-2018)
Could not open /dev/disk/by-path/ip-10.107.207.51:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-d4d4cdaa-59c2-447a-832a-78d2d92d43d4-lun-0: No such device or addres
```

### POD
```
kubectl -n infra-allure get po allure-ee-rabbitmq-0
NAME                   READY   STATUS              RESTARTS   AGE
allure-ee-rabbitmq-0   0/1     ContainerCreating   0          96m
```

### PVC
```
kubectl get pvc -n infra-allure
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-allure-rabbitmq-0                Bound    pvc-e91190f9-f453-475e-bb77-e886522b3070   8Gi        RWO            cstor-csi-disk1   285d
```

### CStorVolume
```
kubectl get CStorVolume -n openebs -l openebs.io/persistent-volume-claim=data-allure-rabbitmq-0
NAME                                       CAPACITY   STATUS    AGE
pvc-e91190f9-f453-475e-bb77-e886522b3070   8Gi        Healthy   285d

### CStorVolumeReplica
```
kubectl get CStorVolumeReplica -n openebs -l cstorvolume.openebs.io/name=pvc-e91190f9-f453-475e-bb77-e886522b3070   
NAME                                                             ALLOCATED   USED    STATUS    AGE
pvc-e91190f9-f453-475e-bb77-e886522b3070-cstor-disk-pool1-9r9x   7.93M       21.9M   Healthy   285d
pvc-e91190f9-f453-475e-bb77-e886522b3070-cstor-disk-pool1-hzg5   7.93M       21.9M   Healthy   285d
pvc-e91190f9-f453-475e-bb77-e886522b3070-cstor-disk-pool1-z9bb   7.93M       21.9M   Healthy   285d
```

**Comment by allanian** [comment]
fixed, recreated

**Comment by choyuansu** [comment]
Hi @allanian, I'm facing a similar problem. Can you elaborate on what you did to fix this? What did you recreate and how? Thanks!

**Comment by allanian** [comment]
[choyuansu](https://github.com/choyuansu) i dropped cva on this node and moved my pod to another node, also you can try with  
trying to remove pvc and recreating this, but be careful.
