### ISSUE TITLE
csTor invalid pool spec: block device has file system {ext4}

### ISSUE THREAD

**Issue by 631068264** [openebs/openebs#3605]
## Description
kubectl apply -f cspc.yaml

```
Error from server (BadRequest): error when creating "cspc.yaml": admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid pool spec: block device has file system {ext4}
```

all the disk are ext4
<img width="651" alt="image" src="https://user-images.githubusercontent.com/8144089/212648196-c8eeaabd-2d9e-4b35-a502-d1a49b54eeb1.png">

How to solve this problem  without delete any data?  

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`): Centos7
* Kernel (from `uname -a`):   Linux d-ecs-38357230 4.15.0-128-generic  x86_64 x86_64 x86_64 GNU/Linux
* Install tools:
* Others:  k8s v1.23.6

**Comment by elamaran11** [comment]
Im also getting issue on a K8s environment on vSphere.

**Comment by elamaran11** [comment]
Please keep this ticket open

**Comment by H-haonan** [comment]
Im also have the same question on talos environment
![image](https://github.com/openebs/openebs/assets/104190002/d3b4dabc-68dc-424f-ad5f-a21affcfff91)

**Comment by mkm29** [comment]
I am experiencing the same issue, any resolution?
