### ISSUE TITLE
cstor block device  Inactive  

### ISSUE THREAD

**Issue by 631068264** [openebs/openebs#3607]
## Description
helm install  3.3.1

```
kubectl get bd -n openebs
NAME                                           NODENAME       SIZE            CLAIMSTATE   STATUS     AGE
blockdevice-102253af77d45d264eaac2e2d5ba230b   A   2147482582528   Unclaimed    Active     28h
blockdevice-8dd07a04e59af42d034d81f4a20516ab   B    2147482582528   Unclaimed    Inactive   50s
```
in B
```
lsblk 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0    4G  0 disk 
sr0     11:0    1  492K  0 rom  
vda    253:0    0  200G  0 disk 
└─vda1 253:1    0  200G  0 part /
vdb    253:16   0    2T  0 disk 
└─vdb1 253:17   0    2T  0 part 
```

Follow this https://openebs.io/docs/troubleshooting/ndm  I have wipe the disk, restart ndm pod on Node B
```
wipefs -fa /dev/vdb1
wipefs -fa /dev/vdb

```

but the block device still Inactive
```
kubectl get bd -n openebs
NAME                                           NODENAME       SIZE            CLAIMSTATE   STATUS     AGE
blockdevice-102253af77d45d264eaac2e2d5ba230b   A   2147482582528   Unclaimed    Active     29h
blockdevice-a2368ea3ef3a21d2b67d18109f41c6cb  B    2147482582528   Unclaimed    Inactive   107s
```

I compare the pod log on between A and B
```
 eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=xxxxx
```
On A  log stop after success but B log will   `ndm.blockdevice.deactivate.success`   or  `ndm.blockdevice.update.success` constantly

[openebs-ndm-vl694.log.zip](https://github.com/openebs/openebs/files/10443634/openebs-ndm-vl694.log.zip)

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by pinghe** [comment]
me too

**Comment by pinghe** [comment]
watch kubectl get bd -A -o wide

You will see that the blockdevice status value is constantly changing between active and inactive.
