### ISSUE TITLE
return openebs-3.4.0.tgz 404 when helm  install 

### ISSUE THREAD

**Issue by liuziyuan** [openebs/openebs#3616]
when i use this command to install 
 `helm install openebs openebs/openebs --namespace openebs --create-namespace`
but ,then showed
`Error: INSTALLATION FAILED: failed to fetch https://github.com/openebs/charts/releases/download/openebs-3.4.0/openebs-3.4.0.tgz : 404 Not Found`

**Comment by sprat** [comment]
It seems that the 3.4.0 release disappeared from GitHub, not sure why!

**Comment by marthydavid** [comment]
It was up for some time because i've got a renovate PR:
https://github.com/marthydavid/homelab/pull/106

**Comment by avishnu** [comment]
We had to re-release OpenEBS 3.4, sorry for the trouble. Please check again.
