### ISSUE TITLE
Fix mixed indent in go files.

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#362]
There are some files which haven't been fixed by go's powerful formatting tools. Some files such as `maya/command/meta.go` have mix-indent.
- Understand why it doesn't get caught by the formatting tools.
- Fix some files which have mix-indent.

**Comment by mathagician** [comment]
`maya/command/meta.go` file is not present in the repo. please update the issue.

**Comment by vharsh** [comment]
@mathagician It is present in [openebs/maya](github.com/openebs/maya/)

**Comment by homuncculus** [comment]
Can i still contribute or is it assigned?

**Comment by vharsh** [comment]
It's yours @homuncculus :+1:
