### ISSUE TITLE
Notice of archiving process

### ISSUE THREAD

**Issue by RichiH** [openebs/openebs#3634]
As per https://github.com/cncf/toc/issues/1051 , CNCF TOC has moved forward with an archival proposal for the OpenEBS project.

Please see https://github.com/cncf/toc/issues/1051 for further details and discussion.

CNCF staff will reach out to all project maintainers and the CNCF end user community.

CC @gila @GlennBullingham @kmova @nconnolly1 @pawanpraka1 @vishnuitta

**Comment by kmova** [comment]
For those reading/following this issue. OpenEBS project and community are very much active. As it happens with any acquisitions, there was a bit of transition that was underway to have new maintainers of the project to get onboarded. Some of the original authors are projects like myself, @gila and @vishnuitta are working behind the scenes to shepherd the project move forward. 

The discussion to make a case to not archive the project is happening on: 
* https://github.com/cncf/toc/issues/905
* https://github.com/cncf/toc/issues/1051
