### ISSUE TITLE
Using Local PV Device, can one device support multiple sts app?

### ISSUE THREAD

**Issue by qiuwenxiang** [openebs/openebs#3646]
I want to use Local PV Device to support multiple sts app , such as : zookeeper ,kafka, cass .. and so on.
I add a device to my k8s node and success running first app kafka.
when I running my next app, the pvc is pending as notice "no devices found matching the criteria"

so I wonder if one device just support one app? I should add multiple device for my multiple sts app?

**Comment by avishnu** [comment]
The whole device is consumed as a PV for one application. It cannot be used for another application.
