### ISSUE TITLE
CrashLoopBackOff due to: Failed to set nvme_core io_timeout

### ISSUE THREAD

**Issue by sunnyPike** [openebs/openebs#3659]
I downloaded latest openebs/mayastor. Running ubuntu on VM.. v5.15 kernel. Three worker nodes and all three have mayastor-csi-node pods in either error or CrashLoopBackOff state. All the other pods are "running".  The full error log  message is:

CSI Driver (csi-node) revision a6902de86c6b (v2.4.0+0)
  2023-09-21T22:39:51.273345Z ERROR csi_node: Terminated with error, error: Failed to set nvme_core io_timeout: No such file or directory (os error 2)
    at control-plane/csi-driver/src/bin/node/main.rs:44

The describe on one of these csi-node pods output is below. I am new to openebs and not sure how to proceed here.  Any ideas ? thanks for any info

$ kubectl describe pod mayastor-csi-node-d5jt2 -n mayastor
Name:         mayastor-csi-node-d5jt2
Namespace:    mayastor
Priority:     0
Node:         worker21/10.130.0.5
Start Time:   Thu, 21 Sep 2023 22:36:10 +0000
Labels:       app=csi-node
              controller-revision-hash=648bbd4859
              openebs.io/logging=true
              openebs.io/release=mayastor
              openebs.io/version=2.4.0
              pod-template-generation=1
Annotations:  <none>
Status:       Running
IP:           10.130.0.5
IPs:
  IP:           10.130.0.5
Controlled By:  DaemonSet/mayastor-csi-node
Containers:
  csi-node:
    Container ID:  docker://b5b2d205492bb18bde3b783f9b7ddb0f31423049ec3678d0f1daf13714742593
    Image:         docker.io/openebs/mayastor-csi-node:v2.4.0
    Image ID:      docker-pullable://openebs/mayastor-csi-node@sha256:f000b5666796618765fe9b39064c2821a44cd08ac046bf026eb1f81d5407d80c
    Port:          <none>
    Host Port:     <none>
    Command:
      csi-node
    Args:
      --csi-socket=/csi/csi.sock
      --node-name=$(MY_NODE_NAME)
      --grpc-endpoint=$(MY_POD_IP):10199
      --nvme-core-io-timeout=30
      --nvme-ctrl-loss-tmo=1980
      --nvme-nr-io-queues=2
      --node-selector=openebs.io/csi-node=mayastor
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 22 Sep 2023 01:59:55 +0000
      Finished:     Fri, 22 Sep 2023 01:59:55 +0000
    Ready:          False
    Restart Count:  31
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      RUST_LOG:        info
      MY_NODE_NAME:     (v1:spec.nodeName)
      MY_POD_IP:        (v1:status.podIP)
      RUST_BACKTRACE:  1
    Mounts:
      /csi from plugin-dir (rw)
      /dev from device (rw)
      /run/udev from run-udev (rw)
      /sys from sys (rw)
      /var/lib/kubelet from kubelet-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dljbz (ro)
  csi-driver-registrar:
    Container ID:  docker://aacc18020bb228c7e9e7925b57298ea1fa79974b4332f5f897aab9006d36bbb0
    Image:         registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
    Image ID:      docker-pullable://registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:f6717ce72a2615c7fbc746b4068f788e78579c54c43b8716e5ce650d97af2df1
    Port:          10199/TCP
    Host Port:     10199/TCP
    Args:
      --csi-address=/csi/csi.sock
      --kubelet-registration-path=/var/lib/kubelet/plugins/io.openebs.mayastor/csi.sock
    State:          Running
      Started:      Fri, 22 Sep 2023 00:52:46 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 22 Sep 2023 00:20:03 +0000
      Finished:     Fri, 22 Sep 2023 00:51:39 +0000
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /csi from plugin-dir (rw)
      /registration from registration-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dljbz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  device:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  run-udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  Directory
  registration-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins_registry/
    HostPathType:  Directory
  plugin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins/io.openebs.mayastor/
    HostPathType:  DirectoryOrCreate
  kubelet-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet
    HostPathType:  Directory
  kube-api-access-dljbz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/arch=amd64
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  3m40s (x300 over 68m)  kubelet  Back-off restarting failed container

**Comment by tiagolobocastro** [comment]
Seems your node does not have the nvme kernel driver loaded?
https://mayastor.gitbook.io/introduction/quickstart/prerequisites

**Comment by sunnyPike** [comment]
yes.. forgot to update ..this was it .. had to add nvme controller ..thanks

**Comment by tiagolobocastro** [comment]
Cool, thanks for confirming
