### ISSUE TITLE
Multi-mount error after restarting pods

### ISSUE THREAD

**Issue by MichaelSL** [openebs/openebs#3660]
## Description
After I try to restart my database pod I get multi-mount error:
```
Warning  FailedMount  37s (x8 over 104s)  kubelet            MountVolume.MountDevice failed for volume "pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb" : rpc error: code = FailedPrecondition desc = volume {pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb} is already mounted at more than one place: {{/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/jiva.csi.openebs.io/e20aba1fed3e8ea51084c6b5a911cd185ce1c59038ff8a4e02fc4220c598e53c/globalmount  ext4 /dev/disk/by-path/ip-10.152.183.161:3260-iscsi-iqn.2016-09.com.openebs.jiva:pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-lun-0}}
```

similar issue was described in https://github.com/openebs/openebs/issues/2536

## Expected Behavior
The mount is removed from old pod and readded to the new one

## Current Behavior
New pod can't start because it can't obtain a volume mount

## Steps to Reproduce
Install MariaDb from mariadb Helm chart.
Update MariaDb image version and restart. Alternatively reboot the node where MariaDb pod is running.
Get the error.

## Your Environment
* `kubectl get nodes`:
```
k3s-m2   Ready    <none>   149d   v1.26.9
k3s-m3   Ready    <none>   149d   v1.26.9
k3s-m1   Ready    <none>   149d   v1.26.9
```
* `kubectl get pods -n openebs`:
```
NAME                                                              READY   STATUS      RESTARTS        AGE
init-pvc-380dab89-08bb-4f8b-af16-446ce297b8e3                     0/1     Completed   0               123d
init-pvc-3b78af1d-3dd4-4af5-a547-4c6ec57d97b3                     0/1     Completed   0               123d
init-pvc-f172ff33-fba8-4305-85f4-59d1af20f05b                     0/1     Completed   0               123d
init-pvc-634adc1a-1311-4cf2-87df-6aa7b14b291e                     0/1     Completed   0               123d
openebs-cstor-csi-controller-0                                    6/6     Running     196 (55m ago)   149d
openebs-jiva-csi-node-jmktp                                       3/3     Running     309 (55m ago)   149d
openebs-ndm-hs2lv                                                 1/1     Running     4 (55m ago)     149d
openebs-cstor-csi-node-cgwjt                                      2/2     Running     8 (55m ago)     149d
openebs-ndm-d4bmz                                                 1/1     Running     4 (54m ago)     149d
pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-1               1/1     Running     10 (55m ago)    10d
openebs-cstor-csi-node-g4bzd                                      2/2     Running     8 (54m ago)     149d
openebs-jiva-csi-node-s8bh9                                       3/3     Running     251 (54m ago)   149d
pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-1               1/1     Running     32 (55m ago)    149d
openebs-jiva-csi-controller-0                                     5/5     Running     178 (54m ago)   149d
pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-ctrl-d5f46758pvj7   2/2     Running     2 (54m ago)     3h14m
pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-ctrl-69fb47bb67zc   2/2     Running     2 (54m ago)     3h14m
openebs-cstor-admission-server-f5d57f788-sqv8p                    1/1     Running     5 (54m ago)     149d
openebs-ndm-operator-74fc47c6cc-xw5bk                             1/1     Running     5 (55m ago)     149d
openebs-cstor-cvc-operator-7946b467f5-22tbq                       1/1     Running     4 (54m ago)     149d
pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-2               1/1     Running     26 (54m ago)    149d
pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-ctrl-cff99457lgwx   2/2     Running     2 (54m ago)     3h14m
pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-0               1/1     Running     10 (54m ago)    10d
pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-ctrl-5cb74bdxqd7w   2/2     Running     2 (54m ago)     3h14m
openebs-localpv-provisioner-99449bb55-fk9zd                       1/1     Running     187 (52m ago)   149d
openebs-jiva-operator-594fdd69b9-wk875                            1/1     Running     4 (52m ago)     149d
openebs-cstor-csi-node-5878p                                      2/2     Running     8 (52m ago)     149d
pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-0               1/1     Running     16 (52m ago)    149d
openebs-ndm-rkk9g                                                 1/1     Running     4 (52m ago)     149d
openebs-jiva-csi-node-lgrf9                                       3/3     Running     246 (52m ago)   149d
pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-2               1/1     Running     5 (52m ago)     10d
openebs-cstor-cspc-operator-7dd775b4b8-msnvg                      1/1     Running     4 (52m ago)     149d
pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-1               1/1     Running     0               37m
pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-2               1/1     Running     1 (37m ago)     37m
pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-0               1/1     Running     2 (37m ago)     37m
pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-1               1/1     Running     0               35m
pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-0               1/1     Running     0               35m
pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-2               1/1     Running     1 (34m ago)     35m
```
* `kubectl get sc --all-namespaces`:
```
NAME                                 PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-hostpath                     openebs.io/local       Delete          WaitForFirstConsumer   false                  149d
openebs-device                       openebs.io/local       Delete          WaitForFirstConsumer   false                  149d
openebs-jiva-csi-default (default)   jiva.csi.openebs.io    Delete          Immediate              true                   149d
microk8s-hostpath                    microk8s.io/hostpath   Delete          WaitForFirstConsumer   false                  149d
```

* `kubectl describe pod mariadb-0 -n mariadb`:
``
Name:             mariadb-0
Namespace:        mariadb
Priority:         0
Service Account:  mariadb
Node:             k3s-m1/192.168.168.112
Start Time:       Sun, 08 Oct 2023 14:12:55 -0600
Labels:           app.kubernetes.io/component=primary
                  app.kubernetes.io/instance=mariadb
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=mariadb
                  controller-revision-hash=mariadb-84c9c744b6
                  helm.sh/chart=mariadb-12.2.2
                  statefulset.kubernetes.io/pod-name=mariadb-0
Annotations:      checksum/configuration: 5d6daf30c7b17e83aece199b3adee9a845e381749724e14a85ac5f9333ba71c7
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/mariadb
Containers:
  mariadb:
    Container ID:
    Image:          docker.io/bitnami/mariadb:10.11.3-debian-11-r0
    Image ID:
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:          false
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'mariadb'>  Optional: false
      MARIADB_DATABASE:       my_database
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-mariadb-0
    ReadOnly:   false
  config:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        mariadb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  2m26s (x33 over 53m)  kubelet  MountVolume.MountDevice failed for volume "pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec" : rpc error: code = FailedPrecondition desc = volume {pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec} is already mounted at more than one place: {{/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/jiva.csi.openebs.io/7e14797101153edccf1a6920cc0cc674b839024043f37b8f020927b1a7bfb042/globalmount  ext4 /dev/disk/by-path/ip-10.152.183.143:3260-iscsi-iqn.2016-09.com.openebs.jiva:pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-lun-0}}
```
* `kubectl get pv`:
```
NAME                                       CAPACITY     ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                 STORAGECLASS               REASON   AGE
pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb   10Gi         RWO            Delete           Bound    portainer/portainer                                                   openebs-jiva-csi-default            149d
pvc-b7df4c0f-afd2-4028-8bb9-f863f64d2a98   10Gi         RWO            Delete           Bound    openebs/openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-1   openebs-hostpath                    149d
pvc-459c791e-5789-419f-a543-d6a50b1d69aa   10Gi         RWO            Delete           Bound    openebs/openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-2   openebs-hostpath                    149d
pvc-8e0b4b9c-14c8-4967-afa8-ad90296088ad   10Gi         RWO            Delete           Bound    openebs/openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-0   openebs-hostpath                    149d
pvc-1ccb9e2f-c029-4be4-bcb3-915114710091   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-0   openebs-hostpath                    149d
pvc-278486e5-aa63-410a-a16b-99d160882193   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-1   openebs-hostpath                    149d
pvc-07356000-ec11-4ce6-841b-f3679e729f3b   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-2   openebs-hostpath                    149d
pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e   8Gi          RWO            Delete           Bound    mysql/data-mysql-0                                                    openebs-jiva-csi-default            149d
pvc-146ce705-90a3-4846-af82-08104f4a1ee5   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-0   openebs-hostpath                    149d
pvc-c870236c-cceb-4c97-a0ac-40a545c35edf   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-1   openebs-hostpath                    149d
pvc-29a9ca9c-9209-4b5d-b3ab-c547153598e5   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-2   openebs-hostpath                    149d
pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681   8Gi          RWO            Delete           Bound    pgsql/data-postgress-postgresql-0                                     openebs-jiva-csi-default            10d
pvc-4c642b4e-9dba-4d8d-8356-02e09bda5ef1   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-1   openebs-hostpath                    10d
pvc-400d8295-b1f9-40fb-866c-9fe964845906   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-0   openebs-hostpath                    10d
pvc-a57252c8-0f8d-4e5d-b7de-c573c022566b   8Gi          RWO            Delete           Bound    openebs/openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-2   openebs-hostpath                    10d
pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec   15625000Ki   RWO            Delete           Bound    mariadb/data-mariadb-0                                                openebs-jiva-csi-default            149d
```
* `kubectl get pvc --all-namespaces`:
```
NAMESPACE   NAME                                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
openebs     openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-1   Bound    pvc-b7df4c0f-afd2-4028-8bb9-f863f64d2a98   10Gi       RWO            openebs-hostpath           149d
openebs     openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-2   Bound    pvc-459c791e-5789-419f-a543-d6a50b1d69aa   10Gi       RWO            openebs-hostpath           149d
openebs     openebs-pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb-jiva-rep-0   Bound    pvc-8e0b4b9c-14c8-4967-afa8-ad90296088ad   10Gi       RWO            openebs-hostpath           149d
openebs     openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-0   Bound    pvc-1ccb9e2f-c029-4be4-bcb3-915114710091   8Gi        RWO            openebs-hostpath           149d
openebs     openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-1   Bound    pvc-278486e5-aa63-410a-a16b-99d160882193   8Gi        RWO            openebs-hostpath           149d
openebs     openebs-pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec-jiva-rep-2   Bound    pvc-07356000-ec11-4ce6-841b-f3679e729f3b   8Gi        RWO            openebs-hostpath           149d
mysql       data-mysql-0                                                  Bound    pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e   8Gi        RWO            openebs-jiva-csi-default   149d
openebs     openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-0   Bound    pvc-146ce705-90a3-4846-af82-08104f4a1ee5   8Gi        RWO            openebs-hostpath           149d
openebs     openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-1   Bound    pvc-c870236c-cceb-4c97-a0ac-40a545c35edf   8Gi        RWO            openebs-hostpath           149d
openebs     openebs-pvc-432f2c51-1db1-4e97-bdee-14c80297ef8e-jiva-rep-2   Bound    pvc-29a9ca9c-9209-4b5d-b3ab-c547153598e5   8Gi        RWO            openebs-hostpath           149d
pgsql       data-postgress-postgresql-0                                   Bound    pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681   8Gi        RWO            openebs-jiva-csi-default   10d
openebs     openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-1   Bound    pvc-4c642b4e-9dba-4d8d-8356-02e09bda5ef1   8Gi        RWO            openebs-hostpath           10d
openebs     openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-0   Bound    pvc-400d8295-b1f9-40fb-866c-9fe964845906   8Gi        RWO            openebs-hostpath           10d
openebs     openebs-pvc-25b29dd9-6b94-4d2f-84f2-5774ae7d4681-jiva-rep-2   Bound    pvc-a57252c8-0f8d-4e5d-b7de-c573c022566b   8Gi        RWO            openebs-hostpath           10d
mariadb     data-mariadb-0                                                Bound    pvc-8b5bdd02-2637-4ac2-a84c-0fd4d28a6cec   8Gi        RWO            openebs-jiva-csi-default   149d
portainer   portainer                                                     Bound    pvc-c4c96516-02a4-4bf6-8ed9-1e1d2667ffdb   10Gi       RWO            openebs-jiva-csi-default   149d
```
* OS (from `/etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Kernel (from `uname -a`):
Linux k3s-m1 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jannispl** [comment]
I'm getting the same issue on openebs v3.5.0

**Comment by jannispl** [comment]
I went as far as going through every node in the cluster and inspecting `/proc/mounts` (this is where `NodeMounter` should read the mounts from), grepping for my `pvc-...` ID - but getting no results at all. The volume is not mounted anywhere, and I don't know where else OpenEBS stores active mounts. Restarting the csi-node Pods and the csi-controller does not help.

**Comment by dpedu** [comment]
Could you try the workaround I wrote about here? https://github.com/openebs/openebs/issues/2536#issuecomment-1817232359

**Comment by avishnu** [comment]
Thanks for being a user of OpenEBS !!
I'd like to suggest Mayastor as the alternative to CStor.
Mayastor is a replicated storage solution (just like CStor) but it's very fast as compared to CStor.
Mayastor is under active development and support, unlike CStor.

https://github.com/openebs/mayastor
https://mayastor.gitbook.io/introduction/

**Comment by avishnu** [comment]
For the multi-mount, you can also check if there are any VolumeAttachments still present on any of the older nodes.

**Comment by dpedu** [comment]
@avishnu could you re-open this issue? This problem still affects Jiva volumes too - not just cStor - which involves Mayastor.

**Comment by avishnu** [comment]
@dpedu Mayastor is an independent engine similar to Jiva or CStor. Please re-open if the issue happens with Mayastor as we have stopped active development of Jiva.

We have documented steps for migration from CStor to Mayastor. The same steps should work with Jiva as well.
[Sample migration procedure for replicated DB](https://mayastor.gitbook.io/introduction/additional-information/replicateddb-overview)
[Sample migration procedure for distributed DB](
https://mayastor.gitbook.io/introduction/additional-information/distributeddb-overview)
