### ISSUE TITLE
block volumes

### ISSUE THREAD

**Issue by aep** [openebs/openebs#3661]
would it be possible to use openebs/mayastore as a block storage for vms?
maya is essentially a replicated block volume, but openebs doesnt appear to have a way to just expose the block volume on a host without making a filesystem on it. or did i miss that?

**Comment by tiagolobocastro** [comment]
I guess this was answered [here](https://github.com/openebs/mayastor/issues/1520) so we can close it?
Please feel free to reopen here or in mayastor if you need further information, thanks
