### ISSUE TITLE
How to configure the external ISCSI storage back-end as Storageclass

### ISSUE THREAD

**Issue by tengdagg** [openebs/openebs#3663]
How to configure the external ISCSI storage back-end as Storageclass

**Comment by hanqingwu** [comment]
https://github.com/kubernetes-csi/csi-driver-iscsi
maybe you need this csi .

**Comment by niladrih** [comment]
@tengdagg -- What are is your use-case for OpenEBS? Are you trying to use a specific storage engine?

**Comment by avishnu** [comment]
As per the latest comment, can this issue be closed?

**Comment by avishnu** [comment]
Also it doesn't look like it's related to OpenEBS. Please clarify.
