### ISSUE TITLE
PVC is not bound when using spec.nodeName

### ISSUE THREAD

**Issue by hznor** [openebs/openebs#3667]
Hello,

I encounter an issue with dynamic provisioning with localpv-hostpath : PVC will not bind to a PV if the pod is scheduled to a given node.

[CASE A]
This is working:
https://pastebin.com/WLPpcW3c
```
$ kubectl -n localpv-debug get pods -o wide
NAME        READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
pvc-debug   1/1     Running   0          11m   10.244.10.171   k8snode07u   <none>           <none>
```

[CASE B]
This is not working:
https://pastebin.com/YbmvKrYP
```
$ kubectl -n localpv-debug get pods -o wide
NAME        READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
pvc-debug   0/1     ContainerCreating   0          35m   <none>   k8snode07u   <none>           <none>
```

The only difference is the presence of the line:   "nodeName: k8snode07u"

Note:
- the node: k8snode07u exists in the cluster and in both case the pod is created/being created on this specific node.
- pod will run if "#volumeMounts:" is removed from the pod definition.
- By observing the logs of localpv-provisioner, it appears that in case B PVC will not trigger provisioner to create a new PV : nothing appears in localpv-provisioner's logs in case B

The output of kubectl describe on this pod:
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  119s (x10 over 6m36s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[pvc-debug], unattached volumes=[kube-api-access-n76s8 pvc-debug]: error processing PVC localpv-debug/pvc-debug: PVC is not bound
  Warning  FailedMount  91s (x16 over 6m49s)   kubelet  Unable to attach or mount volumes: unmounted volumes=[pvc-debug], unattached volumes=[pvc-debug kube-api-access-n76s8]: error processing PVC localpv-debug/pvc-debug: PVC is not bound
```
Why is it that provisioning will systematically fail when the pod nodeAffinity/nodeSelector/nodeName is specified?

**Comment by hanqingwu** [comment]
i think you should delete  yaml in  case A first, then create yaml in case B
because case B and case A have same pvc name ,
and  pvc has create in case A then can not migrate to new node k8snode07u

**Comment by niladrih** [comment]
Like @hanqingwu said, local volumes do not migrate if the application Pod moves to a different node. This is out of scope at the moment. If you want, you may create a feature request for this (https://github.com/openebs/dynamic-localpv-provisioner/issues), or contribute it yourself!

**Comment by radon-at-beeper** [comment]
> local volumes do not migrate if the application Pod moves to a different node

But this isn't what's described. The issue is that even a _newly created_ pod is not able to have the PVC provisioned. Not one that has migrated from a different node.

We observe the same behavior. I cannot think of any reason why PVCs would not be able to be provisioned when a pod is scheduled for a specific node, assuming that they were not previously scheduled to a different node.

A shitty workaround is to cordon every other node in the cluster (or instancegroup) temporarily, create the pod, and then uncordon everything else. This however shouldn't be necessary.
