### ISSUE TITLE
Warning ProvisioningFailed  ... context deadline exceeded

### ISSUE THREAD

**Issue by singaravelanaws** [openebs/openebs#3668]
Warning ProvisioningFailed   8s (x2 over 18s) [local.csi.openebs.io](http://local.csi.openebs.io/)_openebs-lvm-controller-0_76e07e7d-72d6-4005-862e-ae02318d4ae5 failed to provision volume with StorageClass "openebs-lvmpv": rpc error: code = DeadlineExceeded desc = context deadline exceeded

NAME           PROVISIONER                   RECLAIMPOLICY  VOLUMEBINDINGMODE     ALLOWVOLUMEEXPANSION  AGE
 local-storage  [kubernetes.io/no-provisioner](http://kubernetes.io/no-provisioner)  Delete         WaitForFirstConsumer  false                 404d
 openebs-lvmpv  [local.csi.openebs.io](http://local.csi.openebs.io/)          Delete         Immediate             true                  402d

kubernetes v1.24.6
[openebs.io/version=1.0.0](http://openebs.io/version=1.0.0)

Any one can face this issue.
when we try to create the new PVC, old PVC working fine

**Comment by avishnu** [comment]
Any information from the status/logs of the pods?

**Comment by orville-wright** [comment]
Hi @singaravelanaws - is this issue still affecting you. It's been around for a while and I'm trying to figure out if it requires more attention.
- Can you please provide and update from your end?

**Comment by singaravelanaws** [comment]
Yes, everything is fine.

**Comment by avishnu** [comment]
Based on the above comment, closing this issue.
