### ISSUE TITLE
No matches for kind "StoragePoolClaim" in version "openebs.io/v1alpha1"

### ISSUE THREAD

**Issue by lordk911** [openebs/openebs#3673]
Follow the documentation:[Managed database service like RDS](https://openebs.io/docs/stateful-applications/mysql) to install mysql
When I `Creating cStor storage pools`
Got Error: 
```
error: resource mapping not found for name: "cstor-disk" namespace: "" from "spc.yaml": no matches for kind "StoragePoolClaim" in version "openebs.io/v1alpha1"
ensure CRDs are installed first
```

k8s version: v1.25.6
openEBS version: 3.4.0

**Comment by niladrih** [comment]
Hi @lordk911. SPCs are pool resources from legacy-flavoured cStor. A modern cStor deployment makes use of CSPC pools. What is your use-case for OpenEBS storage @lordk911?

**Comment by avishnu** [comment]
Thanks for being a user of OpenEBS !!
In addition to what @niladrih suggested above, I'd like to suggest you try Mayastor as an alternative to CStor.
Mayastor is a replicated storage solution (just like CStor) but it's very fast as compared to CStor.
Mayastor is under active development and support, unlike CStor.

https://github.com/openebs/mayastor
https://mayastor.gitbook.io/introduction/
