### ISSUE TITLE
helm install mysql takes too long time when using CSPC

### ISSUE THREAD

**Issue by lordk911** [openebs/openebs#3674]
k8s version: v1.25.6
openEBS version: 3.4.0
OS：22.04.1-Ubuntu

mysql pod log :   The log says it took about 12 minutes

![企业微信截图_28fbef6f-0a02-4cc4-bc67-1bbe23eaadb7](https://github.com/openebs/openebs/assets/19989300/40c06a9b-014d-408f-a278-0c5dec84ecdf)

How do I find out why it's taking so long

**Comment by lordk911** [comment]
After mysql is installed successfully, deleting mysql Pods to simulate fault recovery will also take a long time

**Comment by avishnu** [comment]
Thanks for being a user of OpenEBS !!
I'd like to suggest Mayastor as the alternative to CStor.
Mayastor is a replicated storage solution (just like CStor) but it's very fast as compared to CStor.
Mayastor is under active development and support, unlike CStor.

https://github.com/openebs/mayastor
https://mayastor.gitbook.io/introduction/
