### ISSUE TITLE
Incorrect FS during CSPC expansion

### ISSUE THREAD

**Issue by TomYork1986** [openebs/openebs#3685]
## Description
Hello! I'm trying to expand my cStor pool by adding new block devices (I wiped FS on this disks before adding). For some reason some disks get "zfs_member" FS and some of them get "linux_raid_member" FS. CSPC expands normally, but when I try to add this CSPI to CVC (volume replica), there are a lot of errors in the log and CVR can't start.
```
2024-02-08T14:44:52+03:00 } {error exit status 1 invalid vdev specification
2024-02-08T14:44:52+03:00 use '-f' to override the following errors:
2024-02-08T14:44:52+03:00 /dev/disk/by-id/scsi-330000d1f010bd413-part1 contains a filesystem of type 'linux_raid_member'
2024-02-08T14:44:52+03:00 /dev/disk/by-id/scsi-330000d1f010bd412-part1 contains a filesystem of type 'linux_raid_member'
2024-02-08T14:44:52+03:00 /dev/disk/by-id/scsi-330000d1f010bd410-part1 contains a filesystem of type 'linux_raid_member'
2024-02-08T14:44:52+03:00 /dev/disk/by-id/scsi-330000d1f010bd411-part1 contains a filesystem of type 'linux_raid_member'
2024-02-08T14:44:52+03:00 }}
```
or
```
I0208 09:41:01.940676       8 import.go:73] Importing pool 283a4ef4-609a-42c7-aacf-0589aa7c1d02 cstor-644045c9-59da-4518-913a-1e2aa9cfb7ad
E0208 09:41:01.945221       8 import.go:94] Failed to import pool by reading cache file: failed to initialize libuzfs client
 : exit status 1
E0208 09:41:01.949346       8 import.go:114] Failed to import pool by scanning directory: failed to initialize libuzfs client
 : exit status 1
```

## Expected Behavior
All disks have **zfs_member** FS and CVR is created successfully..

## Current Behavior
Some of disks have **zfs_member** and some of the have **linux_raid_member** FS

## Your Environment

* OS (from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (from `uname -a`):
`Linux d01dc-k8s008.main.russianpost.ru 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Others:
OpenEBS version: 3.0.0

**Comment by orville-wright** [comment]
Please note: the **```cStor project```** is being deprecated and Archived in accordance with our notification #3701 and #3709.

This work is being undertaken with direction and guidance of CNCF Leadership and the CNCF TOC.

For cStor support, please post questions and issue into the **```OpenEBS CNCF Slack channel```**.

**Comment by orville-wright** [comment]
closed
