### ISSUE TITLE
support external mode like rook ceph external mode，visit openebs in another k8s cluster

### ISSUE THREAD

**Issue by 13567436138** [openebs/openebs#3686]
## Description

support external mode like rook ceph external mode，visit openebs in another k8s cluster

**Comment by orville-wright** [comment]
Hi @13567436138 
I feel that this Issue needs a lot more description and definition from you to help us understand what you're looking for here.
We in the OpenEBS team don't know what **ROOK/Ceph** ```External Mode``` is? 

```ruby
Can you help us understand what External Mode is and why you think it would be good addition to add to OpenEBS?
```

Also, we have 5 Storage  Engines in the OpenEBS project... **(Mayastor, Local PV-Hostpath, Local PV ZFS, Local PV LVM & Local PV RawDev)**; so how does your request relate to those? All of them? or only some of them?

Thanks, looking forward to hearing more from you.

**Comment by orville-wright** [comment]
No feedback from user @13567436138 
Will close in 7 days.

**Comment by avishnu** [comment]
Closing this as per the above comment.

**Comment by 13567436138** [comment]
\reopen

**Comment by 13567436138** [comment]
@avishnu reopen

**Comment by 13567436138** [comment]
I mean openebs installed in one k8s cluster,but I want to use in another cluster

**Comment by avishnu** [comment]
Ok, thanks for the detail.
OpenEBS Mayastor CSI currently supports in cluster provisioning. There's no external support.
Having said that, Mayastor has a fully functional REST API service. You could leverage that alongwith your own CSI.

**Comment by 13567436138** [comment]
do you mean I have to impliment my own csi according to using rest api？
@avishnu
