### ISSUE TITLE
upgrade failure 

### ISSUE THREAD

**Issue by 13567436138** [openebs/openebs#3689]
## Description

```
root@karmada-01-b:~/openebs# helm upgrade openebs .  -n openebs  --kubeconfig ~/.kube/135config 
Error: UPGRADE FAILED: cannot patch "volumesnapshotclasses.snapshot.storage.k8s.io" with kind CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io "volumesnapshotclasses.snapshot.storage.k8s.io" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update && cannot patch "volumesnapshotcontents.snapshot.storage.k8s.io" with kind CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io "volumesnapshotcontents.snapshot.storage.k8s.io" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update && cannot patch "volumesnapshots.snapshot.storage.k8s.io" with kind CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io "volumesnapshots.snapshot.storage.k8s.io" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update && cannot patch "openebs-localpv-provisioner" with kind Deployment: Deployment.apps "openebs-localpv-provisioner" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"localpv-provisioner", "component":"localpv-provisioner", "release":"openebs"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by sjerman** [comment]
I've got this as well.

Upgrade 
microk8s 1.26 -> 1.28

Then
openebs v3.7.1 -> 3.10.0

get the error above.

**Comment by devrushit** [comment]
having the same issue 👍🏼

**Comment by tiagolobocastro** [comment]
We have are moving the CR's to a separate chart dependency which can be disabled (will be released on next version).
@niladrih anything else to add here?

**Comment by devrushit** [comment]
Nice thanks for your reply, when is the release planned ?

**Comment by tiagolobocastro** [comment]
Sometime in April :)

**Comment by devrushit** [comment]
used a dirty workaround by adding the missing labels to run it over. Really dirty, but works. If someone is having the same issue.

**Comment by orville-wright** [comment]
I believe this issue was fixed with the v4.0.0 and v4.0.1 releases.
@tiagolobocastro  @niladrih @avishnu Please confirm? - and we can CLOSE this issue.

**Comment by niladrih** [comment]
@13567436138 -- hi, could try this upgrade user-guide here: https://openebs.io/docs/user-guides/upgrade

**Comment by orville-wright** [comment]
Hi @13567436138  Is this issue resolved for you?
If so, can you please let us know and we can close it.  - of you can close it if you want ?

- Will close in 7 days

**Comment by sjerman** [comment]
For me you can close. It’s resolved

**Comment by niladrih** [comment]
Closing this issue. Please re-open, if this persists.
