### ISSUE TITLE
Wishlist: ppc64le architecture support for OpenEBS

### ISSUE THREAD

**Issue by tidux** [openebs/openebs#3694]
With an increasing number of Docker images supporting POWER architecture servers, it has become reasonable to run Kubernetes on IBM or OpenPOWER hardware.  Many of these servers include high storage capacity/bandwidth, so OpenEBS would be a good fit.

**Comment by orville-wright** [comment]
Hi @tidux what Linux Distro runs on POWER arch?
We currently don't have any Eng/Dev/QA POWER Hardware, so do you know of any community members or Vendors that would consider donating time on their POWER infra so that we could test & QA ?

**Comment by tidux** [comment]
Red Hat is probably your best bet since IBM owns both Red Hat and the underlying hardware.  RHEL has supported ppc64 for a few releases.  Other than RHEL and its clones it's mostly Debian, Gentoo, and Alpine on ppc64.
