### ISSUE TITLE
Contributor not showing

### ISSUE THREAD

**Issue by bruwyn** [openebs/openebs#3696]
![Screenshot 2024-02-13 224407](https://github.com/openebs/openebs/assets/143020783/9d96ed7b-724a-4902-82ad-b4c4d0358ae3)

contributors are showing in github page but not showing in contrib rocks

**Comment by tiagolobocastro** [comment]
Did you create this against the wrong repo @paribeshdangal ? Shown img is not openebs?

**Comment by orville-wright** [comment]
of this is a mistaken post, it should be closed & removed.
