### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by keywinf** [openebs/openebs#3700]
Hi,

Friends told me that OpenEBS was one of the greatest tools for them. I would like to use it with Docker Swarm, for numerous projects which are not yet very big, but big enough to need tools like that.

What is the roadmap for this, as mentioned in the FAQ?

Would it be risky to wait for a release on 2024? Is it more reasonable to use Kubernetes right now?

Thank you in advance.

**Comment by orville-wright** [comment]
Hi @keywinf - We do build OpenEBS for **```Docker Swarm```**.
I'm not sure if its an officially released Helm installable config. 
- Maybe... @avishnu, @niladrih, @abhilashshetty04 or @tiagolobocastro can answer that question for you.

**Comment by niladrih** [comment]
Kubernetes is the only supported orchestrator at the moment. We do not support docker swarm at the moment.

**Comment by keywinf** [comment]
I don't suppose you can help me estimate, even roughly, how long it would take to get started on this work, or how big the work itself would be. Thank you for your reply!

**Comment by orville-wright** [comment]
@keywinf I just wanted to confirm that you are specifically talking about the Mayastor Storage-Engine here?

**Comment by keywinf** [comment]
I'm not as well-informed as you, of course, but I think that's right.

**Comment by niladrih** [comment]
@keywinf -- Docker Swarm is not really on our roadmap. I'd say that you'd be better off moving to kubernetes, if OpenEBS fits your workloads.

**Comment by keywinf** [comment]
Thank you.
