### ISSUE TITLE
Question about OpenEBS Local PV Hostpath and podSecurity.privileged

### ISSUE THREAD

**Issue by AichaDevOps** [openebs/openebs#3703]
Hello community,
I am currently working with OpenEBS and have a question regarding the usage of Local PV Hostpath. I want to understand whether setting `podSecurity.privileged=true `is necessary for pods using OpenEBS Local PV Hostpath.
I've gone through the documentation, but I couldn't find a clear answer. Can someone with experience in OpenEBS shed some light on this? 
Thank you in advance for your help!

**Comment by Abhinandan-Purkait** [comment]
@AichaDevOps The helper pod need to be launched in privileged mode. This is because on nodes, pods without privileged access cannot write to the host directory. Helper pods need to create and delete directories on the host.

**Comment by orville-wright** [comment]
Hi @AichaDevOps 
Looks like you have the answer here. I'm proposing closing this issue in 7 days.

**Comment by orville-wright** [comment]
Closing issue as done.
