### ISSUE TITLE
Deprecation announcement for legacy OpenEBS projects

### ISSUE THREAD

**Issue by orville-wright** [openebs/openebs#3709]
OpenEBS is deprecating a number of legacy projects. These legacy projects along with their repositories will be moved to a new CNCF-owned GitHub Org on 8 April 2024 (or soon after).

This should not come as a surprise; we began informing the community from Jan 2024 of our work with CNCF TOC to optimize and modernize the project structure. The legacy projects include older data engines, subprojects, unused repositories and build dependencies; and over the last 12 months we have only made minor changes to these projects. The deprecated repositories will move to a new GitHub organization named “openebs-archive”. As the projects are moved, some will be tagged as archived, some will not be marked as archived, but over time they all will be. 

The 47 repositories that will be moved into the new organization “openebs-archive” and will be deprecated from the parent project, are:
1.	openebs/cstor-operators
2.	openebs/jiva-operator
3.	openebs/upgrade
4.	openebs/cstor-csi
5.	openebs/istgt
6.	openebs/m-exporter
7.	openebs/jiva
8.	openebs/libcstor
9.	openebs/dynamic-nfs-provisioner
10.	openebs/api
11.	openebs/go-ogle-analytics
12.	openebs/node-disk-manager
13.	openebs/rust-git-version
14.	openebs/device-localpv
15.	openebs/mayastor-charts
16.	openebs/openSeaChest
17.	openebs/monitor-pv
18.	openebs/openebs-docs
19.	openebs/sts-pv-pvc-handler
20.	openebs/helm-operator
21.	openebs/e2e-tests
22.	openebs/openebs-k8s-provisioner
23.	openebs/external-storage
24.	openebs/community
25.	openebs/jiva-csi
26.	openebs/gotgt
27.	openebs/sparse-tools
28.	openebs/longhorn
29.	openebs/elves
30.	openebs/partition-identity
31.	openebs/blkid
32.	openebs/spdk-sys
33.	openebs/proc-mounts
34.	openebs/dbench
35.	openebs/opensea-transport
36.	openebs/opensea-common
37.	openebs/opensea-operations
38.	openebs/fbench
39.	openebs/sys-mount
40.	openebs/vhost-user
41.	openebs/client_model
42.	openebs/blkid-sys
43.	openebs/spl
44.	openebs/wingetopt
45.	openebs/libiscsi
46.	openebs/rawfile-localpv*
47.	openebs/mayastor-api

The reasoning as to why we are deprecating some projects is relatively straightforward.
The OpenEBS Maintainers team has been actively working with CNCF TOC to enhance the community experience of our project. Our long rich open-source history has resulted in too many legacy repo artifacts, sub projects and experimental products persisting over an extended period within the GitHub project structure. This has created a confusing landscape for our community & users. Under the guidance of the CNCF TOC, we agreed to execute a major restructuring of the entire OpenEBS project. The start of this is that; in Feb 2024, CNCF TOC changed the project status to “Archived”, which enables us to make major structural modifications. 

Below are the 7 Legacy Data-Engine projects that are being deprecated and moved to the GitHub organization “openebs-archive”:
1.	Jiva
2.	cStor
3.	Dynamic-NFS
4.	NDM
5.	Device-LocalPV (partition driver)
6.	LocalPV-Device (a non-CSI external provisioner)
7.	RawFile-LocalPV*

Moving forward, the new OpenEBS product architecture and Roadmap centers round 2 core storage services. ‘Local’ and ‘Replicated’. These include the following Data Engines:
1.	LocalPV-HostPath
2.	LocalPV-LVM
3.	LocalPV-ZFS
4.	Mayastor

For some time, our team has aspired to converge the above 4 Data-Engines into 1 core storage platform. These 4 Data Engines are the most popular, active and deployed OpenEBS projects. Together (going forward) they will be known as “OpenEBS”. Our new Modern Data Storage Platform carries forward 900,000 existing CNCF storage users, 8 million product installations and 49 million K8s storage volumes managing 35 PetaBytes of storage. All other legacy Data-Engines and project repo artifacts will be deprecated and migrated out to the new GitHub org named, “openebs-archive”. 

OpenEBS Product documentation is being unified, updated, revised, and modernized. See our docs site @ https://openebs.io/docs/main  This docs initiative will be completed on 8 April 2024 (or soon after).

FAQ’s
Is my project being archived into the new GitHub org?
-	See the list above.

What happens to my deployment if I am using it today?
-	Don’t worry, all archived projects will continue working, running and can be installed via openebs-archive; but not via the new OpenEBS Helm installer release (i.e. v4.0.0).

Should I move my deployment to a different product?
-	In most cases, users can migrate to the new OpenEBS project (v4.0.0)
-	Data Migration guidance will be provided to anyone who needs it. 
-	Please talk to us on our CNCF Kubernetes SLACK Support Channel (#openebs) @https://kubernetes.slack.com/archives/CUAKPFU78

*Project is under review by OpenEBS Maintainers.

**Comment by orville-wright** [comment]
Notice to community: 
- Intention to close this issue when CNCF Re-Apply to SANDBOX application has been submitted.

**Comment by avishnu** [comment]
As per the above comment, OpenEBS re-application to CNCF Sandbox has been submitted https://github.com/cncf/sandbox/issues/104
Closing this issue.
