### ISSUE TITLE
Chart repo https://openebs.github.io/charts is no longer available

### ISSUE THREAD

**Issue by twz123** [openebs/openebs#3718]
## Description

The chart repo https://openebs.github.io/charts is no longer available. Is that on purpose? This is breaking the OpenEBS integration in [k0s](https://github.com/k0sproject/k0s). I see there's https://openebs.github.io/openebs now, but that's only for new charts? 

## Expected Behavior

The (probably now legacy?) Chart repo https://openebs.github.io/charts remains available for legacy software.

## Current Behavior

https://openebs.github.io/charts gives a 404.

**Comment by antonblr** [comment]
Many users may have CD setup (Flux, Argo) with >= 3.10 version, that will start (and already started) failing with that Helm repo being archived.

**Comment by Lewisjmp** [comment]
Greetings @antonblr 
I am currently experiencing a problem deploying OpenEBS v.3.10.0 to a Kubernetes cluster version v1.26.15+rke2r1 using the official https://openebs.github.io/charts repo.
Apparently this file has been deleted from the repo related to helm or a file needed to deploy openebs chart as the error is 404 not found.
I have tried 2 methods to install (Fleet with Rancher CD, helm install )and 2 different versions (3.9.0 and 3.10.0) helm chart, but the error persists.
I tried what you mention in the comment above and in our case we don't use ArgoCD for this depsliegue or Flux. When trying to do the helm repo add from one it throws 404 not found.
Thanks :D

![image](https://github.com/openebs/openebs/assets/94019675/c70fcf1a-e7f1-4428-a38c-fec0061d8165)
![image](https://github.com/openebs/openebs/assets/94019675/1bf88158-6e47-4cd3-a3c9-33e731206644)
![image](https://github.com/openebs/openebs/assets/94019675/df5d177f-f88e-45c1-bb97-e5e9e5039311)

**Comment by antonblr** [comment]
@Lewisjmp the 3.10 charts are archived. Please read this issue description.

For new installation use https://github.com/openebs/openebs/tree/main/charts guide.

**Comment by f5-jay** [comment]
For Openshift I used to have to run this to get openebs to work: 

oc adm policy add-scc-to-user privileged -z openebs-maya-operator -n openebs


Is something similar needed with the new version?  I can't get epenebs to work now on Openshift.

**Comment by Abhinandan-Purkait** [comment]
Hi everyone,

As per the prior communication regarding OpenEBS re-structuring, (refer this [message](https://kubernetes.slack.com/archives/CUAKPFU78/p1712079300995919)), yesterday we migrated all OpenEBS legacy repositories to a CNCF GitHub [openebs-archive](https://github.com/openebs-archive) organization. In addition to the repositories, the parent Helm charts for the OpenEBS v3.10 release and below, were also moved.

This seems to have caused issues to the existing installations, and users have voiced their concerns.
We have decided to revert the legacy Helm chart repo back to it's earlier location to ensure things continue to run smoothly for a `deprecation notice period of SIX months`. Post this period (Oct 30), we will re-initiate the Helm repo transfer to the openebs-archive organization.

Hope these `SIX months` should suffice for users of legacy OpenEBS to plan their migration to the latest OpenEBS v4.x editions.

Please note that after completion of this period and the transfer, the legacy Helm charts will still continue to function only from the openebs-archive organization

**Comment by Ornias1993** [comment]
> This seems to have caused issues to the existing installations, and users have voiced their concerns.

This is another in the growing list of huge helm mistakes you're making here.
That where all *extremely* easy to forsee, yet you did not.

The way you  play-around with production helm releases, is not acceptable.

**Comment by orville-wright** [comment]
since we reverted the chart repo back to it original location/repo and resolved this problem, this issue can now be closed.

**Comment by avishnu** [comment]
As stated above, the legacy helm charts repo will get archived after Oct 30, 2024. Request existing users to make a note of this and accordingly plan the transition to the latest OpenEBS helm repo https://openebs.github.io/openebs.

**Comment by Ornias1993** [comment]
@avishnu Is there some place on the side of CNCF where the "sandbox rejoin" is tracked and/or open for comments?

**Comment by edrob999** [comment]
Hi @Ornias1993. The best place to put your positive or negative feedback is #3701.  This is our master tracking issue. We're working closely in partnership with CNCF.  I'm happy to talk offline if you'd like to discuss anything prior to commenting

**Comment by Ornias1993** [comment]
> Hi @Ornias1993. The best place to put your positive or negative feedback is #3701. This is our master tracking issue. We're working closely in partnership with CNCF. I'm happy to talk offline if you'd like to discuss anything prior to commenting

Thanks for the link, I was hoping there was a actual open thread over at the CNCF.
