### ISSUE TITLE
Enhance LocalPV Engine CI and testing

### ISSUE THREAD

**Issue by tiagolobocastro** [openebs/openebs#3726]
I'm not very familiar with the local engine infra, so please correct anything that I might have gotten wrong here.

## Description
Currently the testing for local engines seems to be lacking.
I'd like this issue to identify areas where we're lacking and steps we need to take to tackle this.

## Context

We've had a few bugs creep into the local engines, and test infra did not seem to help.
In general we'd like to be more confident any time we make some changes that we're not breaking anything.

1. It seems that the current helm chart testing is lacking as the existing tests were part of the operator deployment style but we're no longer supporting operator based installs, so this will need major overhaul, adding new kind of install tests.
2. Missing tests for some features (ex: zfs snapshot clone)
3. Lack of tests for existing features, ie not complete enough
4. E2E tests were moved to equinix, which we now don't have access to so we need to figure out how to handle this, ex: move to github actions or jenkins.  

## Possible Solution

- Helm chart tests for install, uninstall, upgrade (with various features)
- Feature Matrix testing
- CI tests for missing features
- E2E testing needs to migrate
- CI infrastructure refactoring and enhancements

**Comment by orville-wright** [comment]
Agree. We need a ``` LocalPV ``` **Testing strategy & plan** that aligns with the new v4.x Unified Local Roadmap Strategy.

---
Recommend Maintainers should discuss in the Weekly Maintainers mtg as a key agenda item.
- labeling & Tagging maintainers for visibility: @tiagolobocastro @avishnu @niladrih @Abhinandan-Purkait @edrob999 @semekh @orville-wright

**Comment by niladrih** [comment]
This change is required in the openebs/monitoring repo as well.
Ref: https://github.com/openebs/monitoring/pull/120

**Comment by avishnu** [comment]
An issue to track implementation of more CI tests is created for ZFS-LocalPV repo: https://github.com/openebs/zfs-localpv/issues/558

**Comment by avishnu** [comment]
The local pv ci and testing framework have now been enhanced and made extensible. Can we mark this as complete and track any pending tasks with new tickets?

**Comment by avishnu** [comment]
The framework has been implemented to augment the localpv ci and e2e.
