### ISSUE TITLE
block device  is in not in active state

### ISSUE THREAD

**Issue by zhegemingzimeibanquan** [openebs/openebs#3728]
## Description
i have a hdd device on my node ,called /dev/sdc .it swich on active and unactive in the bd 
![image](https://github.com/openebs/openebs/assets/56252858/39fce7e7-67e2-4dd4-ba42-667c0906e5fb)

where can i find the log and fix this 

for: "cstor-cspc.yaml": admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid pool spec: block device "blockdevice-1ac102847bc0adf6a765400b7104879f" is in not in active state

## Your Environment

* `kubectl get nodes`:
NAME      STATUS   ROLES                  AGE    VERSION
eb60246   Ready    node                   540d   v1.23.12
eb60247   Ready    node                   540d   v1.23.12
eb60248   Ready    node                   540d   v1.23.12
eb60249   Ready    node                   540d   v1.23.12
eb60250   Ready    node                   540d   v1.23.12
eb63218   Ready    <none>                 553d   v1.23.12
eb63221   Ready    control-plane,master   553d   v1.23.12
* `kubectl get pods --all-namespaces`:
NAME                                                              READY   STATUS    RESTARTS      AGE
cstor-disk-pool-hq68-544674d668-77rvs                             3/3     Running   0             63m
openebs-cstor-admission-server-57c895b649-6kf9r                   1/1     Running   0             3h37m
openebs-cstor-csi-controller-0                                    6/6     Running   0             3h41m
openebs-cstor-csi-node-294fs                                      2/2     Running   0             3h44m
openebs-cstor-csi-node-7cw4d                                      2/2     Running   0             3h44m
openebs-cstor-csi-node-fqmnf                                      2/2     Running   0             3h43m
openebs-cstor-csi-node-km2tz                                      2/2     Running   0             3h44m
openebs-cstor-csi-node-pbfzz                                      2/2     Running   0             3h44m
openebs-cstor-csi-node-pnxmx                                      2/2     Running   0             3h42m
openebs-cstor-cspc-operator-5bc489cbd7-29j68                      1/1     Running   0             3h46m
openebs-cstor-cvc-operator-78b57f5f88-5cf22                       1/1     Running   0             3h37m
openebs-localpv-provisioner-6dfd6d789d-kcp8h                      1/1     Running   0             3h46m
openebs-ndm-hs95c                                                 1/1     Running   0             12m
openebs-ndm-ncdzt                                                 1/1     Running   0             3h46m
openebs-ndm-operator-6fb8987ff7-95996                             1/1     Running   0             3h46m
openebs-ndm-pq6cr                                                 1/1     Running   0             12m
openebs-ndm-q2lsg                                                 1/1     Running   0             12m
openebs-ndm-vsnw5                                                 1/1     Running   0             12m
openebs-ndm-zwq7h                                                 1/1     Running   0             12m
* OS (from `/etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (from `uname -a`):
Linux eb60247 3.10.0-1160.el7.x86_64 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Install tools:
helm

**Comment by orville-wright** [comment]
Please note:  cStor is a ``` Legacy ``` project and has been archived.
This was done in May/April 2024 on guidance with CNCF TOC and CNCF leadership. 
cStor is no longer actively managed as a part of the openEBS project, and all cStor repo's have been migrated to the CCNF [ openEBS Archive org](https://github.com/openebs-archive)

You can get community support for cStor on the openEBS slack channel. The openEBS eng/dev/QA team are very active in that CNCF Slack support channel and may provide best effort to support you (with no guarantee).

We advise all cStor users to migrate to openEBS MayaStor.

**Comment by orville-wright** [comment]
This issue will be closed in 7 days.

**Comment by avishnu** [comment]
Closing this based on the above comments.
