### ISSUE TITLE
About OpenEBS supports shared storage feature

### ISSUE THREAD

**Issue by Nihao123451** [openebs/openebs#3733]
Does OpenEBS have plans to support shared storage functionality? If so, please list them. Thank you

**Comment by orville-wright** [comment]
Hi @Nihao123451 
openEBS is primarily designed as a Hyper-Converged storage system.
We prefer to see and manage storage media that...
1. Originates from inside the K8s cluster (not from the outside of the K8s cluster via a SAN fabric
2. that physically resides inside each server node (as PCIe, NVMe, SSD or HDD devices)
3.  We have a ```Software Defined Block-mode vSAN Fabric``` that allows us to access block devices from any node to any node

That being said... yes, you can map shared storage to openEBS and we will consume it, manage it
- openEBS consume any Block disk device. So any LUN that appears accessible to the node kernel, we can take a reservation on this, consume it into our SPDK kernel and manage it.

That being said... we ``` do not ``` develop a set of common Shared Storage CSI drivers & operators for vendor specific arrays. 
As, it would be a very difficult task for 1 neutral open-source vendor to manage a set of CSI drivers across many proprietary storage vendors platforms. (.e.g IBM, NetApp, HDS, PureStorage, HP, EMC etc, etc)... and all the unique proprietary specific features that those arrays provide.

OpenEBS provides a set of ```Enterprise Storage Data Mgmt features``` from within the K8s cluster via a Hyper-Converged Block-mode vSAN platform. All running natively within the K8s cluster as a First Class native K8s service (integrated into K8s).; running beside your K8s Applications... in User space.

Let me know if you have any more questions. I'm happy to help.

**Comment by avishnu** [comment]
Closing this as the response to user's query has been provided.
