### ISSUE TITLE
Merge M-apiserver to Maya as a Single project

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#374]
FEATURE REQUEST

**What happened**:
Right now M-apiserver and Maya are two different projects,merge these
to repo's to "Maya" as a single project.

**What you expected to happen**:
There will be "Maya"  as a single project, which makes easier to devlopers
to manage.

**Comment by kmova** [comment]
The movement of openebs/mayaserver to maya will be done in multiple stages using the following approach:
- Get both projects to use the same tools. 
   - glide for vendor management ( https://github.com/openebs/openebs/issues/376)
- Move packages to openebs/maya in the following order:
   - packages used as libraries or utilities will be moved first, openebs/mayaserver main can be changed to import the packages from openebs/maya. 
   - use the same cli tool for both maya and mayaserver
   - move the main package and the build scripts. 

(new issues will be created to track the individual items. this is to avoid checking in a huge change into maya, and also keep the mayaserver functional till the merge is completed)

**Comment by kmova** [comment]
#376 has been resolved to update openebs/mayaserver to use glide as a vendoring tool. 

The following source code remains in openebs/mayaserver (as of v0.4.0):
```
kiran@kmaya:~/go/src/github.com/openebs/mayaserver$ find . -name "*.go" | grep -v vendor | grep -v "_test.go"
./lib/flaghelper/flaghelper.go
./lib/config/config.go
./lib/config/config_parse.go
./lib/server/metadata_endpoint.go
./lib/server/http.go
./lib/server/volume_endpoint.go
./lib/server/server.go
./lib/loghelper/syslog.go
./lib/loghelper/log_levels.go
./lib/loghelper/log_registry.go
./lib/loghelper/gated_writer.go
./main.go
./version.go
./commands.go
./cmd/meta.go
./cmd/up.go
./cmd/version.go
kiran@kmaya:~/go/src/github.com/openebs/mayaserver$ ```

**Comment by kmova** [comment]
The above files are moved to openebs/maya via the PR : https://github.com/openebs/maya/pull/95

**Comment by kmova** [comment]
The mayaserver repo has been merged with openebs/maya. 

There is an ongoing effort to tirage and close the mayaserver open issues.
