### ISSUE TITLE
[ DOCS ] Installing Replicated Engine with non-default cluster domain

### ISSUE THREAD

**Issue by tiagolobocastro** [openebs/openebs#3741]
When using the non-default cluster.local domain, etcd needs to be configured as such.
Example:
helm install ..... --set mayastor.etcd.clusterDomain=xxxx

## Context

Otherwise etcd will not work properly, example: https://github.com/openebs/mayastor/issues/1421#issuecomment-1980269618

**Comment by orville-wright** [comment]
@balaharish7 
I think @tiagolobocastro is asking... 
- can you please add this to the ``` Replicated PV Mayastor ``` Install DOCs . 

Tag @avishnu for awareness

**Comment by balaharish7** [comment]
This issue is documented in the PR [#462](https://github.com/openebs/website/pull/462).

**Comment by avishnu** [comment]
Closing this as per the above comment.
