### ISSUE TITLE
Consolidate design documents

### ISSUE THREAD

**Issue by avishnu** [openebs/openebs#3744]
## Description

Project maintainers have decided to maintain the current and future architecture and design documents of the various OpenEBS engines/features in a single location in the current repository. Most of the component and feature design docs are scattered in individual repositories and some of them are missing. This effort is to consolidate all of them into a common location.

Example folder structure:
openebs / designs / replicated-pv / mayastor
openebs / designs / local-pv / hostpath | lvm | zfs | rawfile

**Comment by Abhinandan-Purkait** [comment]
Going with the suggested design. Thanks

```
openebs / designs / replicated-pv / mayastor
openebs / designs / local-pv / hostpath | lvm | zfs | rawfile
```

@avishnu @orville-wright @tiagolobocastro What about the design docs in the openebs/openebs repo, they seem to be very old and most them are for the deprecated engines? How about the below?

```
openebs / legacy(deprecated)/<here goes the dump?>
```

**Comment by avishnu** [comment]
IMO, we should move the legacy docs to another folder in one of the archive org repos. Maybe "community" repo in the archive org.

**Comment by niladrih** [comment]
Do we want to have an 'openebs' directory inside the `openebs/openebs` repo? Maybe we go with the suggested directory layout while stripping away the openebs prefix? E.g.:
1. `designs/replicated-pv/mayastor`
2. `designs/local-pv/hostpath`

On the legacy design docs. Maybe they should be moved to the openebs-archive org?

**Comment by Abhinandan-Purkait** [comment]
> Do we want to have an 'openebs' directory inside the `openebs/openebs` repo? Maybe we go with the suggested directory layout while stripping away the openebs prefix? E.g.:
> 
> 1. `designs/replicated-pv/mayastor`
> 2. `designs/local-pv/hostpath`
> 
> On the legacy design docs, IMO they should be moved to the openebs-archive org.

By openebs we meant the openebs repo.

**Comment by avishnu** [comment]
Design documents for the Local PV engines have been updated. Pending for Mayastor.

**Comment by tiagolobocastro** [comment]
Migration of confluence docs to mardown will be tracked in a separate ticket
