### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by Daxcor69** [openebs/openebs#3748]
You need to add 
allowVolumeExpansion: true

to the page that talks about the configuration for the storage class. I know it is mentioned in the resize page but I think it should also be included as a configurable element to the storage class.

https://openebs.io/docs/user-guides/replicated-storage-user-guide/replicated-pv-mayastor/rs-configuration

**Comment by tiagolobocastro** [comment]
@balaharish7 can we expand the docs on this?

**Comment by balaharish7** [comment]
This issue is documented in the PR [#474](https://github.com/openebs/website/pull/474).

**Comment by Abhinandan-Purkait** [comment]
Closing this as it's resolved.
