### ISSUE TITLE
helm: mayastor.enabled=false still installs its dependencies

### ISSUE THREAD

**Issue by aep** [openebs/openebs#3755]
the manual for *localpv now recommends installing the entire openebs helm,
however, it is not possible to do that without installing maya

`` mayastor.enabled=false``  actually only skips maya itself, but still installs all of mayas dependencies

**Comment by tiagolobocastro** [comment]
Hi @aep, you mean it still installs loki and etcd for example? Strange, I'll test this..

**Comment by aep** [comment]
Yes. But maybe it's just counterintuitive naming.  There is also `engines.replicated.mayastor.enabled = false` which does in fact disable it

**Comment by avishnu** [comment]
The section from the OpenEBS documentation website provides the information on the installation options: https://openebs.io/docs/quickstart-guide/installation#installation-via-helm

**Comment by avishnu** [comment]
Identified that there are stale values in the values.yaml that will be cleaned up.
