### ISSUE TITLE
Leverage Single vendor dependency tool (glide)

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#376]
FEATURE REQUEST

**What happened**:
There is 2 different depdency tools has been used in Maya and M-apiserver.
go-vendor for M-apiserver and glide for Maya.

**What you expected to happen**:
There should be only one tool after M-apiserver get merged to Maya.

**Comment by AmitKumarDas** [comment]
I have started using Gopkg for elves/e2e/<testcasename>

This is going to be the official go vendoring tool.
I find it to be Okay.

**Comment by prateekpandey14** [comment]
Every small project is moving on to dep  https://github.com/golang/dep.
And glide is no longer supported (after release 0.13.0) and has been advised (by core devs), converting to dep here https://github.com/Masterminds/glide/releases

**Comment by AmitKumarDas** [comment]
@prateekpandey14 dep has been good & it is the one used in elves/e2e.

Can you follow below steps:

```
$ dep init
This does the following:
```

- Look for existing dependency management files to convert
- Check if your dependencies use dep
- Identify your dependencies
- Back up your existing vendor/ directory (if you have one) to _vendor-TIMESTAMP/
- Pick the highest compatible version for each dependency
- Generate Gopkg.toml ("manifest") and Gopkg.lock files
- Install the dependencies in vendor/

Do check yourself if there are any unknowns or challenges.
If all works fine then first get maya use dep & 
make mayaserver use dep thereafter.

**Comment by kmova** [comment]
openebs/mayaserver - has been moved to glide and the code is available on the branch:
https://github.com/openebs/mayaserver/tree/dep-vendor-tool

dep is still in the very early stages, it seems like that moving to dep will be good, if all the dependent projects have already moved on to dep. The movement towards dep will be tracked under the a different issue https://github.com/openebs/openebs/issues/489
