### ISSUE TITLE
Unable to deploy Openebs via helmfile

### ISSUE THREAD

**Issue by Toasterson** [openebs/openebs#3767]
## Description
I am trying to deploy openebs via helmfile

## Current Behavior
The deployment aborts with:
```
in ./helmfile.yaml: in .helmfiles[5]: in charts/system/helmfile.yaml: [building dependencies of local chart: command "/usr/bin/helm" exited with non-zero status:
PATH:
  /usr/bin/helm
ARGS:
  0: helm (4 bytes)
  3: dependency (10 bytes)
  4: build (5 bytes)
  5: openebs (7 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: no repository definition for https://openebs.github.io/node-disk-manager, https://openebs.github.io/dynamic-localpv-provisioner, https://openebs.github.io/cstor-operators, https://openebs.github.io/jiva-operator, https://openebs.github.io/zfs-localpv, https://openebs.github.io/lvm-localpv, https://openebs.github.io/dynamic-nfs-provisioner, https://openebs.github.io/mayastor-extensions. Please add the missing repos via 'helm repo add'
```

## Possible Solution
Update Chart.yaml and Chart.Lock to point to https://openebs.github.io/openebs

## Your Environment
* Install tools: helm 3, helmfile 0.144.0

**Comment by niladrih** [comment]
Hi @Toasterson, the helm registry you're using is an older one. The new openebs helm registry lives at https://openebs.github.io/openebs. You'd have to run the commands
```
helm repo remove openebs
helm repo add openebs https://openebs.github.io/openebs
```

I'm curious as to where you found the older helm registry. I think we've updated the documentation for this. But if there's an older link going around, I'd like to know about it. Let me know how it goes.

**Comment by Toasterson** [comment]
@niladrih I have an implicit `helm dependency build` in my steps as that is what helmfile does in the background. Helm has dependencies thus you must also update https://github.com/openebs/openebs/blob/main/charts/Chart.yaml#L18-L34 In every helm chart. Updating the docs is not sufficient.

**Comment by niladrih** [comment]
I don't quite follow, @Toasterson. The new helm chart doesn't have dependencies linked to node-disk-manager, cstor-operators and jiva-operator.

**Comment by Toasterson** [comment]
Can you link me the sources for the new chart then? The one I found has dependencies.

**Comment by niladrih** [comment]
The new chart lives here: https://github.com/openebs/openebs/tree/main/charts
It too has dependencies, however, not all of the dependencies of the OpenEBS v3.x charts have made it into the v4 (v4.1.0 presently) chart.

**Comment by Toasterson** [comment]
Looks like my script pulled in an old version it's fixed now.
