### ISSUE TITLE
Move all documentation to rST format.

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#377]
FEATURE REQUEST

Currently some of our documentation are in markdown format scattered in some directories deep down.
Move all of them excluding `CONTRIBUTING.md` & `README.md` to the central place called [ReadTheDocs] (https://openebs.readthedocs.io)

Good starting points:
- Learn about documentations tools like docutils and format.

**Comment by riktimmondal** [comment]
can you explain what is the central place here?

**Comment by vharsh** [comment]
Central place is [ReadTheDocs](https://openebs.readthedocs.io/)

**Comment by manigandham** [comment]
Is there a reason to use rST over of markdown? I've encountered MD far more in documentation across open-source projects and find it to be much easier to deal with.

**Comment by kmova** [comment]
I agree @manigandham -- But openebs doc site is hosted by readthedocs with sphinx documentation builder. It supports rst better than md.

**Comment by kmova** [comment]
The docs have moved to https://github.com/openebs/openebs-docs in .md format.
