### ISSUE TITLE
Set post commit hooks to check for code formatting issues

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#378]
FEATURE REQUEST
   - Currently, we have to run go formatting tools after commit-ing our code. It'll be great if they can be run as soon as we commit our code.

**Comment by vharsh** [comment]
Okay, this might seem intimidating a bit, but honestly it's some of bit hack-slash scripting.
Good starting points
- https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by itaditya** [comment]
@vharsh I'll work on this one

**Comment by itaditya** [comment]
the hooks are placed in `.git/hooks` directory but this directory is not managed by git, means it's not sent to github so how do you suggest to share these hooks to others.

[This](https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/) looks like a good way

**Comment by kmova** [comment]
Thanks @itaditya for the above suggestions!
