### ISSUE TITLE
Add endpoint /metrics and some custom metrics to jiva replica

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#382]
## FEATURE REQUEST:
* As of now only few endpoints are created which are serving our purpose. But we want [prometheus](prometheus.io) to scrap the metrics from volume replica also. So add endpoint `/metrics` and add some custom metrics to it also. [Here](https://github.com/marselester/prometheus-on-kubernetes) is a starting link that you can follow.

**Comment by jfugate11377** [comment]
Repo

**Comment by vharsh** [comment]
@jfugate11377 https://github.com/openebs/jiva

**Comment by utkarshmani1997** [comment]
This issue is now part of PR [#124](https://github.com/openebs/maya/pull/124), all the custom metrics will be exported via openebs volume exporter (maya-agent)
