### ISSUE TITLE
Utilise the fields defined in prometheus Histogram

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#384]
# FEATURE REQUEST :
* Utilise the fields defined in [prometheus HistogramVec](https://godoc.org/github.com/prometheus/client_golang/prometheus#HistogramVec). It is a Collector that bundles a set of Histograms that all share the same Desc, but have different values for their variable labels. This is used if you want to count the same thing partitioned by various dimensions (e.g. HTTP request latencies, partitioned by status code and method).

**Comment by kmova** [comment]
@utkarshmani1997 - this could be useful for getting details on the latency and iops histograms. Is this being considered as part of the monitoring revamp work that is going on?
