### ISSUE TITLE
Push test logs into an S3 bucket instead of maintaining a local log repository

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#386]
## FEATURE REQUEST

Today, the test "logs" (which encompasses playbook logs, host syslog, container logs, I/O summary log/performance metrics, plots, application-specific logs etc..,) during the CI runs are either lost post the run OR maintained in local storage in case they are needed. A better way of managing this is to automate the collection of these at the end of the script/playbook run and push them to an AWS S3 bucket (We could have the requisite keys stored as ENV on the test harness machines).

Further, we can have a webserver running on an AWS EC2 instance consuming the above storage so that the logs can be referenced anytime, from anywhere.

**Comment by ksatchit** [comment]
Good reference : http://ansible-manual.readthedocs.io/en/v1.8.4-doc/s3_module.html

**Comment by kmova** [comment]
As part of implementing the openebs.ci, the logs are now stored in ElasticSearch and visualized through Kibana.
