### ISSUE TITLE
Change maya cli to use COBRA

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#388]
FEATURE REQUEST

**What happened**:
There is a need to enhance the CLI of Maya.
Cobra is a library providing a simple interface to create powerful modern CLI interfaces similar to git & go tools as well as a program to generate applications and command files.

**What you expected to happen**:
A awesome CLI and easy to use.

**Comment by AmitKumarDas** [comment]
I  had felt  cobra to be  complex.  Reason being  functional  coding
The solution should simplify the code.

Refer to these libraries as well:
- https://github.com/c-bata/kube-prompt

**Comment by kmova** [comment]
mayactl now has completely moved to COBRA. vendor package cleanup will be done as part of : https://github.com/openebs/openebs/issues/1152
