### ISSUE TITLE
Write an exporter for volumes

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#392]
## FEATURE REQUEST :
* We need to have an exporter that can pull metrics from OpenEBS volumes like latency, read/write etc....
 and it will push these metrics to prometheus. It will help in analysing and monitoring OpenEBS volumes.This [link](https://github.com/infinityworks/prometheus-rancher-exporter) will be helpful in implementing exporter.

**Comment by vharsh** [comment]
As of now we can get the metrics
`$ maya volume stats <volume-name>`

**Comment by utkarshmani1997** [comment]
merged via #656
