### ISSUE TITLE
Remove commented code from volumeprovisioner/profile.go file

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#403]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Details

There are a lot of commented code in the following file:
https://github.com/openebs/maya/blob/master/volumes/profile/volumeprovisioner/profile.go

- Exercise care not to remove valid comments. Just remove the commented code & comments of this commented code.

**Comment by divayprakash** [comment]
@AmitKumarDas Working on it!
