### ISSUE TITLE
Volume spec for OpenEBS volume should not say PVC

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#404]
**What happened**:

maya-apiserver allows for provisioning of volumes via an yaml file. The convention for the object used by maya-apiserver yaml file is called "PersistentVolumeClaim(PVC)", which can get confused with K8s PVC concept. This happened with me, while trying to customize the OpenEBS volume replica count setting, which can be done by spec passed to maya-apiserver. Instead of changing at the maya-apiserver spec, I was changing in the K8s PVC. 

More details are available at : https://github.com/openebs/openebs/pull/401

**What you expected to happen**:

The naming convention used by OpenEBS should not clash with concepts used by the outer CO layer. Especially, when the developer/user is expected to provide inputs or customize those objects.

**Comment by muratkars** [comment]
Resolved
