### ISSUE TITLE
Does OpenEBS need a separate metrics service ?

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#406]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Details

- Why has K8s chosen to go with this design than depend on Prometheus ?
  - https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/metrics-server.md

- Should OpenEBS think on these lines as well ?

**Comment by kmova** [comment]
We will have to revisit the way monitoring data is handled (stored) within a kubernetes cluster in the upcoming releases. For the current release, we will stick with the scarping via the prometheus. 

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/monitoring_architecture.md

Using OSS that works across multiple container orchestration platforms is also one of the design constraints for openebs/maya.

**Comment by muratkars** [comment]
See [m-exporter](https://github.com/openebs/maya/tree/master/cmd/maya-exporter) and [docs](https://docs.openebs.io/architecture.html#maya-volume-exporter) for details.
