### ISSUE TITLE
Technical writeups, blogs, docs leads to better community understanding & collaboration

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#41]
Let this be a placeholder, where anyone can write down some topics that is not well understood.
This in turn should be explained in form of docs, tutorial, blogs, etc by core members in various forms.

### Topics:

- Building blocks of distributed systems
- distributed file systems vs. distributed block systems
- zero-to-low-maintenance turn-key storage solution
- storage on a fault tolerant filesystem
- Need for a posix filesystem
- Linux sparse files

### You should be able to understand the stuff written below after reading above :1st_place_medal: 

- https://news.ycombinator.com/item?id=13678979
- https://news.ycombinator.com/item?id=11817387
- https://news.ycombinator.com/item?id=11818081

**Comment by muratkars** [comment]
Moved to marketing backlog
