### ISSUE TITLE
Changes to names of various OpenEBS types & their properties to align with OpenEBS naming

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#421]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Details

- Make changes to names of type & its properties if & only if they donot align with OpenEBS.
- Make changes to json names if & only if they do not align with OpenEBS
- Make change to protoBuf names if & only if they do not align with OpenEBS

### NOTE:

- This change should be done only after completion of #420 
- This might break functionalities
  - Please raise separate issues w.r.t component that breaks
- Refer: https://github.com/openebs/maya/blob/master/types/v1/types.go

**Comment by vharsh** [comment]
Good starting point
- https://github.com/openebs/openebs/issues/420#issuecomment-335561074
