### ISSUE TITLE
Discussions around Protobuf vs gRPC w.r.t code simplicity

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#423]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Why this issue ?

Maya has a set of issues raised for making maya component gRPC compliant.
However, this issue will try to get the associated tradeoffs & the design decisions that are taken in the process:

- It will be good to update the on-going work on gRPC &/ protobuf in this issue.
- It will also be great to extract reference quotes, ideas, phrases from below link & provide them in this issue in a very simplified manner.
  - Refer - https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md

### Related issues:

- https://github.com/openebs/openebs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20grpc

### Sample & Other References

- https://github.com/enricofoltran/hello-auth-grpc
- https://medium.com/@shijuvar/building-distributed-systems-and-microservices-in-go-with-nats-streaming-d8b4baa633a2

**Comment by kmova** [comment]
Closing this as stale for now. A new design doc or note can be updated when the details are available.
