### ISSUE TITLE
Go project related forks require additional steps w.r.t developer contribution git steps

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#433]
The missing steps and some amount of re-wording are done here

### Setting up Development Environment for OpenEBS projects

```bash
working_dir=$GOPATH/src/github.com/openebs
mkdir -p $working_dir
cd $working_dir
```

### The steps mentioned here are w.r.t contribution towards openebs/openebs project

```bash
git clone https://github.com/$user/openebs.git
cd openebs/
git remote add upstream https://github.com/openebs/openebs.git
git remote set-url --push upstream no_push
git remote -v
```

### Synchronizing your local master(i.e. your $user/openebs project) with upstream master(i.e. openebs/openebs)

```bash
git checkout master
git fetch upstream master
git rebase upstream/master
git status
git push origin master
```

### Create Branch (based on feature or bug name)

```bash
git branch <branch_name>
git checkout <branch_name>
git push --set-upstream origin <branch_name>
```

### Synchronizing (i.e Rebase) your local branch with upstream master

```bash
git checkout <branch-name>
git fetch upstream master
git rebase upstream/master
git status
git push
```

### Make change to your local branch

```bash
# make your changes
# keep fetching the commits from upstream master & rebase them here
git commit
git push

# submit the PR to upstream from browser link https://github.com/$user/openebs
```

### Delete Branch

```bash
git push origin --delete <branch_name>
git branch -d <branch_name>
```

Original - https://github.com/openebs/openebs/blob/master/contribute/process/pr-workflow-developer-doc.md

**Comment by brihijoshi** [comment]
Hi, I've started working on it :) Please assign this to me

**Comment by AmitKumarDas** [comment]
@brihijoshi Can you send the PR. I will get you added then.

**Comment by brihijoshi** [comment]
@AmitKumarDas Done!

**Comment by prateekpandey14** [comment]
@brihijoshi assigned to you.
