### ISSUE TITLE
include version details in the slack/ansible notifications

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#436]
The notifications on the slack channel from the e2e Ansible tests run from Jenkins are as shown below:

![image](https://user-images.githubusercontent.com/12488783/30997849-1ab79784-a4e8-11e7-99e8-c525298c749e.png)

While the above messages indicate pass/fail of the various runs, and to get additional details we need to click through the link. The link however can be from an on-premise setup, which user outside of the on-premise network will not have access. 

It will be helpful add more details like:
- version of the containers being used for the test
- branch on which the tests are being run
- commit or the pull request for which the test being run (etc)

**Comment by ksatchit** [comment]
:+1:

**Comment by ksatchit** [comment]
cc: @dargasudarshan @yudaykiran for guidance ! (added Hacktoberfest tag!)

**Comment by swapagarwal** [comment]
Can you point me to the codebase where the slack notifications are being sent? 😇

**Comment by kmova** [comment]
The e2e has moved to openebs.ci. This is no longer required.
