### ISSUE TITLE
Calculate the time taken updating a K8s Service from one K8s Deployment to another

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#438]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Why is this required ?

OpenEBS might want to use the concept of linking/labelling a K8s Service to K8s Deployment & subsequent update of the same K8s Service to a different K8s Deployment. This might be required to build one of the elements of HA component for OpenEBS volume.

NOTE: This feature looks similar to logic of building Blue Green CI Deployments.

### Elaborate on this logic ?

The logic will calculate the:
- time taken for update of K8s Service label (*K8s & the current setup dependent*) & 
- time taken to establish the broken communication (*not K8s dependent*) & 
  - NOTE: communication can be http, later-on it will iscsi connection
- time taken for other K8s internal updates (*K8s & the current setup dependent*)

### Other considerations:

- Initial implementation can be:
  - Tested on any given image that accepts http requests
  - Initial implementations can be tested on minikube
  - Initial implementations can be tested on less loaded setup
- Next set of implementation can be (can be a new issue altogether):
  - Tested for iscsi communication from iSCSI client to K8s service based OpenEBS Volume

### Similar issues:

- https://github.com/openebs/openebs/issues/206

**Comment by kmova** [comment]
With the movement to CAS templates for launching the volume and pool deployments, the K8s parameters can be easily configured. The comments/notes provided in this issue can be helpful to set the default values. However, closing this issue as stale for now and will revisit with new issues for specific aspects that need to be modified.
