### ISSUE TITLE
git scripts that can help setup/contribute to openebs

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#442]
The development or contributors work-flow requires the developer running multiple git commands for setting up forked repo, creating dev branches, syncing the dev branches with upstream master etc., 

The tools can be hosted under : *openebs/contribute/tools*

Some sample scripts can be like:

- setup_remote <reponame>
```
#reponame can be either provided as arugment or auto-detected from *git config remote.origin.url*
git remote add upstream https://github.com/openebs/$reponame
git remote set-url --push upstream no_push
git remote -v
```

- sync_with_master

```
git checkout master
git fetch upstream master
git rebase upstream/master
git status
git push origin master
```

**Comment by Logan1x** [comment]
@kmova  @vharsh  i would like to work on this issue.

**Comment by vharsh** [comment]
Yay @Logan1x give it a shot :+1:

**Comment by Logan1x** [comment]
is the task is going here `openebs/contribute/tools` and add those scripts? Are there any more scripts to add?

**Comment by Logan1x** [comment]
and do i have to make a new markdown file named `tools.md` and paste these into those?

**Comment by Logan1x** [comment]
CC: @kmova @vharsh

**Comment by vharsh** [comment]
Thanks @Logan1x for pitching in.
Create directory call `openebs/contribute/hack` and add those commands in a shell script.

**Comment by Logan1x** [comment]
ok.
