### ISSUE TITLE
Add label to Dockerfile

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#446]
**FEATURE REQUEST**

Currently our Docker Images aren't labeled, It's best to have some useful metadata. This way we can get some more information about the images.

Good reference points
- https://medium.com/@chamilad/lets-make-your-docker-image-better-than-90-of-existing-ones-8b1e5de950d
- https://microbadger.com/

Label ideas?
- http://label-schema.org/rc1/
- `maya version` should be a great addition :+1:

Prerequisites
- familiarity with docker

Where's the Dockerfile ? 
- In [maya repository](https://github.com/openebs/maya/)

**Comment by waseem18** [comment]
Can I please take this up @vharsh as a part of hacktoberfest?

I've got good command over docker!

**Comment by vharsh** [comment]
Sure @waseem18

**Comment by waseem18** [comment]
@vharsh What do you want the label to be?

**Comment by waseem18** [comment]
@vharsh You mean this docker file https://github.com/openebs/maya/blob/master/buildscripts/docker/Dockerfile ?

**Comment by vharsh** [comment]
@waseem18 Yes.
It'll be good to have 'maya v0.4' 
Besides that it'll also be good to have the most recent commit ID.

**Comment by waseem18** [comment]
Sounds good!

But when some commit merges into master, Wouldn't it create confusion? I mean, the recent commit id in docker file would be different right. In that case, one would need to manually update recent commit id every time something gets pushed.

**Comment by waseem18** [comment]
@vharsh Will put a PR soon!

**Comment by waseem18** [comment]
Here's PR for this issue @vharsh https://github.com/openebs/maya/pull/94

Let me know your review!

Thanks

**Comment by vharsh** [comment]
Vendor should be "OpenEBS"

**Comment by waseem18** [comment]
Will change it! @vharsh

**Comment by vharsh** [comment]
Wait for some time, we'll have more suggestions coming in.

**Comment by waseem18** [comment]
Sure!
