### ISSUE TITLE
Provide reference spec for  OpenEBS Volume containers. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#449]
OpenEBS Volumes are deployed in the container cluster (like Kubernetes) as a set of containers. These containers are using the docker image, called *jiva*. The code for *jiva* is under repo *openebs/jiva*. 

At a high-level, *jiva* containers have the functionality like:
- save the data onto direct attached disks of nodes
- replicate the data across disks in multiple nodes
- expose the data via standard protocols like iSCSI
- provide typical storage controller functionality like data-protection, backups, caching, encryption, compression, etc,. 

Since OpenEBS Volumes are run/deployed as containers, they can be run in any container orchestration platform like Kubernetes, Docker Swarm, Mesosphere, Rancher Cattle, etc., 

A reference spec needs to be created for these *jiva* containers that provide information on the various configurable options. This reference spec is intended to be used by the developers trying to automate the launching of OpenEBS volumes in various container orchestration platforms.

**Comment by vipulgupta2048** [comment]
@kmova I am not sure, I get you. What kind of reference spec do we need here. A tutorial? or some blog-post.

**Comment by kmova** [comment]
The idea was to get this into a spec that will help writing orchestration of openebs volumes in non-K8s environments. 

The spec is now recorded as part of the CAS templates under: https://github.com/openebs/maya/tree/master/pkg/install/v1alpha1

Also closing this issue as currently there are no active plans to orchestrate outside of K8s.
