### ISSUE TITLE
k8s demo setup failed

### ISSUE THREAD

**Issue by payes** [openebs/openebs#45]
The output of final stage of Vagrant Up:

`==> osh-01: Setting up the node using IPAddress: 172.28.128.6
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!`

`maya setup-osh -self-ip=172.28.128.6 -omm-ips=172.28.128.5`

`Stdout from the command:`

`Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
unzip is already the newest version (6.0-20ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Cleaning old maya boostrapping if any ...
Fetching utility scripts ...`

`Stderr from the command:`

`mesg: ttyname failed: Inappropriate ioctl for device
W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
Error executing cmd: exit status 35
Install failed: Error while bootstraping
OpenEBS Host setup failed`

Verification of the setup failed at:
```maya osh-status```
No output was shown for above command.

Vagrant version: Vagrant 1.9.1
Virtual box version: 5.1.14r112924

**Comment by kmova** [comment]
Vagrant boxes are packaged with the required software. During vagrant up, we no longer contact github to download.
