### ISSUE TITLE
Update travis.yml file to check for PEP8 compliance 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#450]
Once #220 if fixed for the existing files, make sure the new commits follow the PEP8 complaint. Run the following as part of the automated ci builds. 

```
flake8 . 
```

*flake8* can be setup in the build machine for python 2.7 using:
```
pip install flake8
```

The changes needs to be done:
https://github.com/openebs/openebs/blob/master/.travis.yml
https://github.com/openebs/openebs/blob/master/requirements.txt

**Comment by debojitkakoti** [comment]
@kmova I have raised PR #607 as part of this fix.

**Comment by vharsh** [comment]
@debojitkakoti it should be good to have the default option, i.e. not just errors, but also warnings, etc

**Comment by debojitkakoti** [comment]
@vharsh I have reset it to default options #607
