### ISSUE TITLE
Fix mix-indent in openebs/k8s/demo/Vagrantfile

### ISSUE THREAD

**Issue by lisaychuang** [openebs/openebs#456]
## BUG REPORT: Fix mix-indentation in [openebs/k8s/demo/Vagrantfile](https://github.com/openebs/openebs/blob/74aaee06d5b737b21145834958608150ecfa48df/k8s/demo/Vagrantfile)

**What happened**:
Refer to open issue #312 , this is a branch issue to fix mix indentation specifically for [openebs/k8s/demo/Vagrantfile](https://github.com/openebs/openebs/blob/74aaee06d5b737b21145834958608150ecfa48df/k8s/demo/Vagrantfile), as part of #hacktoberfest contribution.

**What you expected to happen**:
I will review the file and standardize indentation to 2 tabs, as noted by [@kmova](https://github.com/kmova)

**How to reproduce it (as minimally and precisely as possible)**:
Current file with mix indent: [openebs/k8s/demo/Vagrantfile](https://github.com/openebs/openebs/blob/74aaee06d5b737b21145834958608150ecfa48df/k8s/demo/Vagrantfile)

**Comment by lisaychuang** [comment]
@kmova just confirming the indentation again - in Ruby Style Guide - [Source Code Layout](https://github.com/bbatsov/ruby-style-guide#source-code-layout) it noted "two spaces per indentation level (aka soft tabs)."

Is this the standardization to adopt for this file?

**Comment by kmova** [comment]
yes @lisaychuang

**Comment by lisaychuang** [comment]
Thanks, just submitted PR #457 🙂
