### ISSUE TITLE
Explore K8s Pod restarts, failures, anomaly detections, handlers/hooks & remedial actions in Kubernetes

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#465]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Why this feature request ?

This should help us organize our thoughts into actionable tasks (issues that can be implemented & closed in couple of days or max a week's time) w.r.t OpenEBS volume's High Availability. One can expect lot of actionable tasks that will go on to form the HA implementation of OpenEBS.

### What this feature request should do ?

- Explore the various mechanisms of Pod & other K8s objects w.r.t this feature request
- Explore the various K8s components involved w.r.t this feature request
- Explore the various config options in these K8s components w.r.t this feature request
- Explore if custom failure detection logic/components can fit into the existing K8s components
- Explore the communication protocols used between the components w.r.t this feature request
- Explore the endpoints of these components w.r.t this feature request
- Build a workflow diagram that explains the life-cycle w.r.t this feature request.

**Comment by AmitKumarDas** [comment]
### Here are the summarized mechanisms:

- Failure Detection: liveness probes
  - Action: Kubelet uses liveness probes to know when to restart a Container
- Failure Detection: readiness probes
  - Action: Kubelet uses readiness probes to know when a Container is ready to start accepting traffic
  - Example: Acts as a signal to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.


### References

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by AmitKumarDas** [comment]
### Granular Tasks based on above comment

#### Implementation Specific:



#### Verification Specific:

- https://github.com/openebs/openebs/issues/438
- https://github.com/openebs/openebs/issues/206

**Comment by AmitKumarDas** [comment]
Since this issue acts as a reference point. Will update this issue as & when required even though it is marked as closed.

**Comment by loren-osborn** [comment]
Just some updated links for anyone arriving here late. The tickets above have new numbers:

**Implementation Specific Tasks:**
* #519 -> https://github.com/openebs/openebs-docs/issues/558

**Verification Specific Tasks:**
* #516 -> https://github.com/openebs/maya/issues/1003
