### ISSUE TITLE
go get maya shows wrong release version using `maya version` command

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#472]
BUG REPORT
**What happened**:
`go get github.com/openebs/maya` shows wrong version when using 
`maya version`  command.

**What you expected to happen**:
`maya version` should show the current latest release(taged) version. 
```
Maya v'0.4.0'-dev
Go Version: go1.9
OS/Arch: linux / amd64
M-apiserver: Unable to contact M-apiserver : http://127.0.1.1:5656
Provider : Unknown
```

**How to reproduce it (as minimally and precisely as possible)**:
do `go get github.com/openebs/maya` and use `maya version` which results as
below
```
Maya vnone
Go Version: go1.9
OS/Arch: linux / amd64
M-apiserver: Unable to contact M-apiserver : http://127.0.1.1:5656
Provider : Unknown
```

**Comment by kmova** [comment]
The version information is usually taken as an command-line argument via the "-ldflags -X main.Version='${GIT_TAG}'", where GIT_TAG is computed by build scripts using:
```
GIT_TAG="$(git describe --tags $(git rev-list --tags --max-count=1))"
```
One of the ways to fix this would be to, have the main.go - automatically compute the GIT_TAG value if the ldflags argument wasn't passed.

**Comment by ashishranjan738** [comment]
i want to work on this issue

**Comment by prateekpandey14** [comment]
Yes its already fixed. Closing now
