### ISSUE TITLE
Design proposal for expanding the capacity of openebs volume via yaml file

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#476]
Explain the workflow for expanding the capacity of the volume, that either an user or automated-operator can trigger via an update to the yaml files. For example:
- Prometheus can be configured to setup capacity threshold alert 
- As an action / playbook, the user can update the capacity of the volume either by : 
  - maya cli 
  - updating the yaml file (storage class or pvc )

**Comment by AmitKumarDas** [comment]
This requires volume update operations at maya-apiserver, jiva among other things.
