### ISSUE TITLE
Not able to exec inside the container for docker version 1.13.1

### ISSUE THREAD

**Issue by payes** [openebs/openebs#48]
Command issued: sudo docker exec -it <container id> ls
Error Message: rpc error: code = 2 desc = containerd: container not found
This is seen in k8s-demo inside osh-01 VM.

This seems to be an issue with docker release 1.13.1.
Can we fix the docker version to some stable one.

**Comment by payes** [comment]
Workaround: Restart the docker service

**Comment by kmova** [comment]
openebs depends docker installed on the customer environment. It is assumed that customers will have a stable docker version and also, we will have to make sure that vagrant boxes created by openebs will ensure that docker version is stable as part of the e2e tests.
