### ISSUE TITLE
Fix the date entry in docker image

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#480]
BUG REPORT
 
**What happened**:
- No date entry for `build-date` in maya docker image.

**What you expected to happen**:
-  valid date entry for `build-date`.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ docker inspect openebs/maya:ci
...
            "Labels": {
                "org.label-schema.build-date": "",
                "org.label-schema.description": "CLI for OpenEBS",
                "org.label-schema.name": "maya",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "http://www.openebs.io/",
                "org.label-schema.vcs-url": "https://github.com/openebs/maya",
                "org.label-schema.version": ""
            }
```

**Anything else we need to know?**:
- Why is this required?
It'll be a good helpful metadata in future.

Prerequisites:
- familiarity with docker and shell scripts

How to begin looking for possible solutions?
- **look for some scripts which are doing it.** Where? [maya repo](https://github.com/openebs/maya/)
- _check if some documentations outline this process_
- Try building the `maya` docker image locally using the `Dockerfile`

After solving it
- skim through some helpful stuff about continuous integration to get a bigger picture o what just happened

**Comment by waseem18** [comment]
Hi @vharsh 

I would like to look into this :)

**Comment by vharsh** [comment]
Hi @waseem18
Take a look as to how the docker image is getting build.
Happy Hacking! Happy Learning!

**Comment by pik4ez** [comment]
Feel free to merge [my PR](https://github.com/openebs/maya/pull/104).
