### ISSUE TITLE
Fix front page of documentation

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#482]
FEATURE REQUEST

**What happened**:
- Index is displayed twice on the sidebar & on the right side.

**What you expected to happen**:
- It'll be better to see the [main content](http://openebs.readthedocs.io/en/latest/getting_started/overview.html) instead of the content page.

**How to reproduce it (as minimally and precisely as possible)**:
- Visit the docs [online](http://openebs.readthedocs.io/en/latest)
or
- build them locally

**Comment by jennifer-kinsey** [comment]
Dibs!

**Comment by berviantoleo** [comment]
I think for this issue, need to change `index.rst` file. In the `index.rst` contain table of content, maybe need to change with a description or introduction looks like the [main content](http://openebs.readthedocs.io/en/latest/getting_started/overview.html).

**Comment by rahulbajaj0509** [comment]
I shall take care of this :)

**Comment by rahulbajaj0509** [comment]
@vharsh hey can you help me with setting up the project on my local instance so that i have access to all the files and folders ?

**Comment by vharsh** [comment]
Sure @rahulbajaj0509 find us on [slack](https://openebsslacksignup.herokuapp.com/)

**Comment by jennifer-kinsey** [comment]
@vharsh Thanks for your earlier tip. I thought I responded back to you. Sorry about that. I was able to set it up locally but not able to figure out how to customize the the content on my own with limited knowledge of Sphinx.  The index.rst file just looks like a table of contents to me. I don't see where the body of the page comes into play on this page.

**Comment by vharsh** [comment]
@jennifer-kinsey This issue is open for all, no need to feel sorry

**Comment by kmova** [comment]
This fixed in the latest docs: 
https://docs.openebs.io/
