### ISSUE TITLE
Add instructions to build docs locally on Windows

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#483]
FEATURE REQUEST
 
**What happened**:
- `make html` fails on windows, as windows does not ship build tools like Make.

Prerequisites
- A system with sphinx, docutils, etc

Why is it required?
- It's great to build the docs locally before sending a PR.
- Not everyone runs a GNU/Linux system with all the awesome tools
- Not everyone is super comfy with terminal commands 
- We didn't write a windows shell script to build the docs.

# TODO
1. Find a way to **build & clean** the docs
- on PCs with Windows 10 using the bash subsytem
- on older windows systems just having `git-bash`

HINT : 
* `sphinx-build` is your friend
* no `Makefile.bat` was generated in the beginning

2. Document your findings in [README.md](https://github.com/openebs/openebs/blob/master/documentation/README.md)

**Comment by daveloyall** [comment]
`git-bash` doesn't ship with `make`.

I'm not aware of anyone using the Ubuntu embedded in `WSL` for builds yet...  There are complications.

I recommend `cygwin`.  It has a package named `python-sphinx-1.2.3`.

**Comment by vharsh** [comment]
Great point, I had fewer hopes with WSL.
Is it easier to not go for a Windows batch script to generate the docs?
`sphinx-build` can be used directly, I wanted to know if having a windows batch file, makes it any easier.
There are lots of bottlenecks here too, viz are things in the `PATH`, etc..

**Comment by kmova** [comment]
The new documentation uses https://github.com/openebs/openebs-docs which is dependent on the npm install steps.
