### ISSUE TITLE
Update the Anaconda version in Dockerfile

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#484]
FEATURE REQUEST?
- Update the Dockerfile to download the newer version of Anaconda.

Prerequisites:
- Basic proficiency with shell scripts, some experience with `wget` will be helpful.

**Comment by vharsh** [comment]
Look [here](https://github.com/openebs/easy-jupyter/blob/master/Dockerfile#L12)

**Comment by Kurolox** [comment]
I'll take a look at it, just one question. Do you want me to just change the anaconda version to the newest one, or should I make it automatically fetch the newest version available?

**Comment by vharsh** [comment]
making it fetch the latest one would be nice :+1:

**Comment by Kurolox** [comment]
Done. https://github.com/openebs/easy-jupyter/pull/2

**Comment by satyamz** [comment]
Thanks @Kurolox, Looking forward to more contributions :slightly_smiling_face:  
Closing this issue! PR https://github.com/openebs/easy-jupyter/pull/2
