### ISSUE TITLE
Fix usage steps in README

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#487]
## BUG REPORT

**What you expected to happen**:
The usage instructions given in the repository should point to [this docker image](https://hub.docker.com/r/openebs/easy-jupyter/) instead of [this one](https://hub.docker.com/r/satyamz/docker-jupyter/)

**Comment by vharsh** [comment]
The project is [here](https://github.com/openebs/easy-jupyter)

**Comment by wdhif** [comment]
dibs

**Comment by wdhif** [comment]
The latest is ok or you would prefer a specific tag ?

**Comment by kmova** [comment]
@wdhif -- may be a good idea to attach - latest tag.

**Comment by wdhif** [comment]
Done :)
