### ISSUE TITLE
Migrate from glide to dep for openebs/maya - 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#489]
As noted, by the glide v 0.13.0, dep is being recommended as the preferred vendoring tool. openebs/maya, uses glide and needs to be migrated to using "dep".

**Comment by fortrieb** [comment]
Hi, i will grep this task unless somebody else is already working on this.

**Comment by kmova** [comment]
Thanks @fortrieb, will assign this task to you.

**Comment by fortrieb** [comment]
Pull Request https://github.com/openebs/maya/pull/96
