### ISSUE TITLE
Review and improve the FAQ about organizing the code in various repositories 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#491]
OpenEBS source code is split across multiple repositories. The following document explains the philosophy behind having different repositories and where new code can get added. 
https://github.com/openebs/openebs/blob/master/contribute/design/code-structuring.md

The document needs the following help:
- Review the content (english)
- Add links to the referenced repositories.

**Comment by nvzard** [comment]
@kmova  please close this issue.
