### ISSUE TITLE
Steps to install Docker should be mentioned in the prerequisites.

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#493]
BUG REPORT

  The steps regarding" how to install Docker" should be mentioned so that the person should not unnecessarily again need to check regarding installation of Docker.  

-->

**What happened**:
Steps to install Docker is missing on Pre-requisites

**What you expected to happen**:
The steps should be mentioned on how to install docker on the machine.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vharsh** [comment]
Please mention some details about your system
viz
- OS
- Kernel

**Comment by aj07** [comment]
Sent please check https://github.com/openebs/openebs/pull/681

If possible please, put hacktoberfest tag there :)

**Comment by mahebbar** [comment]
The following note has been added. Since we are specifying Kubernetes availability as a prerequisite, it comes with Docker already.

 Note: Container runtime such as Docker must be installed/available.
