### ISSUE TITLE
Convert the maya version command from mitchellh/cli to COBRA

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#495]
FEATURE REQUEST

**What happened**:
Needs to enhance the maya Cli commands as per the issue #388 
using Cobra pkg.

**Comment by eculver** [comment]
I just recently found this via Hacktoberfest. I see a few issues related to the CLI and cobra, namely #469 and this one. For someone completely new to the project, could you elaborate on the requirements and what is expected here? I have read through a tree of issues stemming from #388 and am a bit lost, but would love to work on this.

**Comment by prateekpandey14** [comment]
@eculver , i already worked on this issue and created a PR for this, can you review this PR and let us know.

**Comment by prateekpandey14** [comment]
@eculver if you want to add more, you are good to go.

**Comment by eculver** [comment]
Cool. Thanks for the heads-up @prateekpandey14. What threw me off was the fact that the issue was created in openebs/openebs, but the change actually needed to happen in openebs/maya. All is clear now. 👍

**Comment by prateekpandey14** [comment]
@eculver , There are some more issues has been raised which are related to CLI (using Cobra) #506 #505 #513 #514
give them a shot.
Looking forward to more contributions from your side :) .

**Comment by kmova** [comment]
maya version command has been moved to COBRA CLI. Closing this issue.
