### ISSUE TITLE
Review and enhance the readme of openebs/jiva

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#496]
Review the content of https://github.com/openebs/jiva/blob/master/README.md for correctness and styling.

**Comment by AliceWonderland** [comment]
Hello @kmova, I can take a look at this!

**Comment by kmova** [comment]
Thanks @AliceWonderland

**Comment by geekyd** [comment]
@kmova Can I take this up?

**Comment by mahebbar** [comment]
Closing this issue as README.md: Enhanced #27 is closed.
