### ISSUE TITLE
Add documentation for running mongodb under usecases. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#498]
The configuration files for running mongodb is available under https://github.com/openebs/openebs/tree/master/k8s/demo/mongodb

The usecases doc https://github.com/openebs/openebs/blob/master/documentation/source/install/install_usecases.rst, should be updated with content for running mongodb, like the other examples  - percona, crunchy and jupyter.

**Comment by mahebbar** [comment]
Resolved as part of PR #870
