### ISSUE TITLE
Documentation should include clear instruction on Prerequisites for various install guides. 

### ISSUE THREAD

**Issue by arn007** [openebs/openebs#5]
I feel that , the documentation still needs to be crisp .
 It lacks requirement specification such as required operation system is Linux in which Ubuntu is specific bundle of linux required, then the disk space consumed by the packages ,etc.. . Similarly, for end users , the product needs to be explained in detail and a promotional video or a video explaining complete functioning with audio explanation in the live demo will be further helpful for users.

**Comment by muratkars** [comment]
It's continuously improving, but we have better and enough documentation to address this issue. https://docs.openebs.io/docs/next/prerequisites.html
