### ISSUE TITLE
Provide vagrantbox for kubernetes 1.8

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#500]
Provide a new vagrant box for kubernetes 1.8 under https://github.com/openebs/openebs/tree/master/k8s/vagrant

The way to build new boxes is at : https://github.com/openebs/openebs/tree/master/k8s/lib/vagrant

**Comment by debojitkakoti** [comment]
I am into it

**Comment by ggarg2906sumo** [comment]
@kmova  made a PR https://github.com/openebs/openebs/pull/801
