### ISSUE TITLE
Enter symbol should be there after each command

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#507]
**What happened**:
Enter symbol is missing after each command to execute it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kmova** [comment]
@NisantaSahoo -- please update the issue with the links to the pages, where the modification is required.

**Comment by rahulbajaj0509** [comment]
I would like to work on this bug, @NisantaSahoo can you please mention the files that need this update ?

**Comment by kmova** [comment]
Please re-open this issue or raise a new issue with specific page that needs enhancements. The docs are now moved to https://github.com/openebs/openebs-docs
