### ISSUE TITLE
Verify that iSCSI is configured- Could have been explained little bit more

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#508]
Choose one: BUG REPORT or FEATURE REQUEST

<!--
If this is a BUG REPORT, please:
  It has mentioned that Verify that Iscsi is configured ,  just below that it asks to verify Check that initiator name is configured and iSCSI service is running using the following commands.. But the point is how can we get to know that iscsi is configured the commands that follow tells about the  initiator name configuration.
**What happened**:
 It has mentioned that Verify that Iscsi is configured ,  just below that it asks to verify Check that initiator name is configured and iSCSI service is running using the following commands.. But the point is how can we get to know that iscsi is configured the commands that follow tells about the  initiator name configuration.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mahebbar** [comment]
Please check the generalized page at  https://v05-docs.openebs.io/docs/next/installation.html.
