### ISSUE TITLE
Change the readthedocs theme's sidebar to orange colour.

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#509]
FEATURE REQUEST

**What happened**:
- Our docs and [website](https://openebs.io) should have the same or similar colour.

**What you expected to happen**:
- The docs are coloured blue, #2980B9 make them orange, #ee5a2b

**How to reproduce it (as minimally and precisely as possible)**:
- Visit the docs [online](http://openebs.readthedocs.io) or build them locally

**Comment by 007akk** [comment]
@vharsh  can i do this

**Comment by vharsh** [comment]
Sure @007akk :+1:

**Comment by vharsh** [comment]
Ref : https://github.com/rtfd/sphinx_rtd_theme#todo
