### ISSUE TITLE
Functionalities of Kubectl could be explained just as minikube is explained

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#510]
## Is this a BUG REPORT
 BUG REPORT 

**What happened**:
Download and setup Minikube and kubectl.
Here we got to know what  is minikube because it is explained in the beginning. But here what functionality will kubectl is missing , it's nowhere mentioned and why do we need to setup and install kubectl.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kmova** [comment]
Closing as stale issue.
