### ISSUE TITLE
Setup directories for storing minkube and kubectl configuration command not working

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#511]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT 

**What happened**:
In setup directories for storing minkube and kubectl configuration the command in the document  it shows no such a file or a directory

**What you expected to happen**:
Explain the correct command to created directry
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vharsh** [comment]
Changing `/home/vagrant` to $HOME shall set it right.
