### ISSUE TITLE
mkdir /home/vagrant/.kube || true here vagrant should be replaced with username to avoid confusion

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#518]
BUG REPORT

**What happened**:
Here instead of using vagrant username can be mentioned to avoid  confusion.
http://openebs.readthedocs.io/en/latest/install/dev_solutions.html

**What you expected to happen**:
vagrant word should be replaced

**Comment by prateekpandey14** [comment]
It will be better to change the steps as below:
```
mkdir $HOME/.kube || true
touch $HOME/.kube/config
```
