### ISSUE TITLE
Getting error while running  setup-ara.yml file using On-Premise Solutions documentation. 

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#526]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
root@rafi-virtual-machine:/home/rafi/openebs/e2e/ansible# ansible-playbook setup-ara.yml
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [ara : Install ara apt packages] ******************************************
changed: [localhost -> 127.0.0.1] => (item=[u'gcc', u'python-dev', u'libffi-dev', u'libssl-dev', u'python-pip', u'libxml2-dev', u'libxslt1-dev'])

TASK [ara : Install ara pip packages] ******************************************
changed: [localhost -> 127.0.0.1] => (item=tox)
changed: [localhost -> 127.0.0.1] => (item=ara)

TASK [ara : Get ara location] **************************************************
changed: [localhost]

TASK [ara : Create plugins folder in playbook directory if it doesn't exist] ***
ok: [localhost]

TASK [ara : Copy ara callback plugin to openebs custom plugins location] *******
changed: [localhost]

TASK [ara : Copy ara action plugins to openebs custom plugins location] ********
changed: [localhost]

TASK [ara : Copy ara modules to openebs custom plugins location] ***************
changed: [localhost]

TASK [ara : Update ansible.cfg with ara module library path] *******************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: path"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=6    unreachable=0    failed=1

root@rafi-virtual-machine:/home/rafi/openebs/e2e/ansible#

**Comment by debojitkakoti** [comment]
@rafihnl Which ansible version you are using?
This error likely to happen if it the ansible version < 2.3  
Prerequisite is Ansible > 2.3

**Comment by rafihnl** [comment]
I'm using anisble version 2.4

**Comment by kmova** [comment]
The e2e has been moved to openebs/litmus, where the dependencies are handled by the litmus container.
