### ISSUE TITLE
Add a step to verify the ARA with client IP and port number (9191)

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#527]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
![image](https://user-images.githubusercontent.com/22936421/31225202-96f5fdc6-a9ee-11e7-980a-ab2baf4b8fc2.png)

**Comment by ksatchit** [comment]
@rafihnl , do you mean you would like to see additional documentation mentioning steps to view ARA dashboard ?

**Comment by rafihnl** [comment]
Please add this in the documentation so that users can see the dashboard and verify is it working or not.

**Comment by ksatchit** [comment]
Sure, will do !

**Comment by kmova** [comment]
The ARA way of reporting the CI results has been depricated. The CI results are not available at https://openebs.ci
