### ISSUE TITLE
kubectl apply -f openebs-operator.yaml showing error

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#532]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 BUG REPORT

**What happened**:
In the documentation for setting up of OpenEBS the command mentioned is kubectl apply -f openebs-operator.yaml but it shows the following error
satis@satis-virtual-machine:~/openebs/k8s$ kubectl apply -f openebs-operator.yaml
error: error validating "openebs-operator.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ServiceAccount"}; if you choose to ignore these errors, turn validation off with --validate=false

The version of Kubectl is 1.8.
Running on Windows through mremoteng

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mahebbar** [comment]
The documentation is clear and doesn't require any updates. Hence, closing this issue.
