### ISSUE TITLE
"kubectl apply -f openebs-storageclasses.yaml" showing error while trying to add openebs related storage classes

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#533]
## Is this a BUG REPORT or FEATURE REQUEST? 
when I tried to apply  kubectl -f openebs-storageclasses.yaml this command after setting up of OpenEBS i got the following error
nishant@nishant-virtual-machine:~/openebs/k8s$ kubectl apply -f openebs-storageclasses.yaml
error: error validating "openebs-storageclasses.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"storage.k8s.io", Version:"v1", Kind:"StorageClass"}; if you choose to ignore these errors, turn validation off with --validate=false
  
The Kubectl version is 1.8
Used windows os and terminal is mremoteng

 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by prateekpandey14** [comment]
Kubectl 1.8 broken for minikube(https://github.com/kubernetes/minikube/issues/1996)

**Comment by kmova** [comment]
Resolved in the recent releases.
