### ISSUE TITLE
Kubernetes YAML files for running Redis using OpenEBS Volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#536]
OpenEBS v0.4.0 supports dynamically provisioning Kubrenetes PersistentVolumes - with access type "ReadWriteOnce".

The configuration files for running these applications are provided under:
https://github.com/openebs/openebs/tree/master/k8s/demo

This issue is raised to seek help to:
- add a new storage class definitions for running Redis under openebs-storageclasses.yaml
- add k8s configuration files for Redis - that uses PVCs referring to the above StorageClasses

**Comment by lxfontes** [comment]
👋  just to clarify: is this for cassandra or redis?
> add a new storage class definitions for running Cassandra under openebs-storageclasses.yaml

assuming redis: single node or primary + N replicas?

i can get it going 🤘

**Comment by kmova** [comment]
@lxfontes - this issue is for redis.. thanks for pointing out. I have updated the description. 

it will be great to have both examples:
- single node
- primary + N replicas.. 

You could raise multiple 2 PRs. it it makes sense.
