### ISSUE TITLE
Kubernetes YAML files for running Wordpress with MySQL using OpenEBS Volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#537]
OpenEBS v0.4.0 supports dynamically provisioning Kubrenetes PersistentVolumes - with access type "ReadWriteOnce".

The configuration files for running these applications should be placed under:
https://github.com/openebs/openebs/tree/master/k8s/demo

This issue is raised to seek help to:
- add a new storage class definitions for running MySQL and WordPress applications under openebs-storageclasses.yaml
- add k8s configuration files for MySQL and Wordpress - that uses PVCs referring to the above StorageClasses

**Comment by ksatchit** [comment]
The Wordpress + MySQL YAML spec references are available here : https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
