### ISSUE TITLE
Update the go version to 1.9.1 in the .travis.yml for openebs/maya

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#539]
## Is this a BUG REPORT or FEATURE REQUEST?
  FEATURE REQUEST

**What happened**:
Go Versions < 1.8.4, seem to have a couple of security vulnerabilities. 
https://golang.org/issue/22131
https://golang.org/issue/22133
It has been recommended by the Go Core Community to upgrade the version of Go to 1.9.1. 

**What you expected to happen**:
All new builds for maya will use the latest version of Go, thereby resolving the  security vulnerabilities.

**How to reproduce it (as minimally and precisely as possible)**:
https://golangweekly.com/link/26068/47a3e5168d

**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by prashant0598** [comment]
@yudaykiran in the .travis.yml contains only python2.7 not go

**Comment by yudaykiran** [comment]
@prashant0598 please look into openebs/maya repo, it is there. The issue has been raised in openebs/openebs for our tracking purposes.

**Comment by prashant0598** [comment]
@yudaykiran ya found it 😄. Do i just need to change the go version to 1.9.1?

**Comment by yudaykiran** [comment]
@prashant0598 , that should be enough :+1:
