### ISSUE TITLE
maya-apiserver fails to create replicas when the "size" attribute in volumeClaimTemplates is given in a format "Gi" and "Mi". 

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#541]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

**What happened**:
Most of the examples that Kubernetes has in its repo, uses the "Gi" or "Mi" notation to specify the volume size. If the same is provided for openebs, it fails to create the persistent storage as the replicas fail to launch.

**What you expected to happen**:
maya-apiserver must be able to also accept formats that are followed in the Kubernetes examples and not fail to provide persistent storage.

**How to reproduce it (as minimally and precisely as possible)**:
- Use and YAML having volumeClaimTemplates
- Provide openebs-basic (or any openebs storage class) as the storage class for persistent storage.
- For the size attribute, provide the size as 5Gi
- When the YAML is applied the replicas fail to create and end up in CrashloopBackof.
**Anything else we need to know?**:

**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kmova** [comment]
An iterm fix has been merged with https://github.com/openebs/jiva/pull/32

Keeping this open for the next release to resolve this with a cleaner solution.
