### ISSUE TITLE
Discover properties of local block devices

### ISSUE THREAD

**Issue by gkganesh126** [openebs/openebs#545]
FEATURE REQUEST

**What happened**:
The feature is about maya-agent runs on minions and provide the local block device information

**What you expected to happen**:
It is expected to provide the local block device information

**Comment by gkGaneshR** [comment]
As the block device discovery is only local, it is not required to implement protocols involving tcp/ip like scsi. fdisk -l displays the block device/partition info. This command returns the result in string format and manual processing of string. Using lsblk -J would be a good idea, as the result will be on json format and the necessary columns can be processed later

**Comment by kmova** [comment]
@gkGaneshR:

Check if there are any libraries that can be used, which can abstract the os-dependencies - similar to osquery ?

**Comment by gkGaneshR** [comment]
@kmova:
osquery exposes certain os related info, but block device info is not present there, since it is developed for the purpose of security related monitoring. The other alternatives provides even less features like process and ports exposure. I have gone through the internals of osquery and found out they do the same terminal commands but they are exposed as sql query. I have completed the code using os-exec lsblk. Can I raise a PR?

**Comment by kmova** [comment]
Yes @gkGaneshR -- go ahead.

**Comment by kmova** [comment]
This issue is the initial task towards implementing the usecase in https://github.com/openebs/openebs/issues/194

**Comment by gila** [comment]
Im a little puzzled about certain terms used in #194 but that's OK. The maya-agent needs to do a whole lot more (eventually) for us then the disks. The disks, however -- are the low hanging fruit. 

in #194 several things are mentioned that are needed for the disk, the list is a little short but a good start. Things that must be added to the list are -- in no particular order:

- physical location (ie enclosure slot number)
- fault led manipulation
- ok2rm led manipulation (if applicable) 
- extend log pages (read write errors etc, number of corrections etc)
- in case off SSD wear levers
- rotational speed 
- temperature
- FW revision level 
- what partition is being used by what OpenEBS volume 
- serial number
- manufacture 
- model 
 - state (online, removed, etc) 
- .... likely more things as we go

This information needs to be extracted by means of an API such that other consumers, be it tools, CLI k8s or what have you can make use of it.

Some (most) of the info can be abstracted via libudev and libmnt (which gets it from sys/proc interface) other require us to periodically -- send SCSI commands to devices.

**Comment by gila** [comment]
@gkGaneshR osquery was originally developed for this yes but has gained a more generic role. Your suggested approach of using lsblk and fdisk will not provide the level of detail we typically need, if we were to leverage osquery -- we can extend it easily. Also -- the other features it brings are useful for other things we need to maya agent to "know"

**Comment by gkGaneshR** [comment]
@gila @kmova lsblk will not only present the columns which we are currently showing but also the following fields:
 NAME  device name
       KNAME  internal kernel device name
     MAJ:MIN  major:minor device number
      FSTYPE  filesystem type
  MOUNTPOINT  where the device is mounted
       LABEL  filesystem LABEL
        UUID  filesystem UUID
    PARTTYPE  partition type UUID
   PARTLABEL  partition LABEL
    PARTUUID  partition UUID
   PARTFLAGS  partition flags
          RA  read-ahead of the device
          RO  read-only device
          RM  removable device
     HOTPLUG  removable or hotplug device (usb, pcmcia, ...)
       MODEL  device identifier
      SERIAL  disk serial number
        SIZE  size of the device
       STATE  state of the device
       OWNER  user name
       GROUP  group name
        MODE  device node permissions
   ALIGNMENT  alignment offset
      MIN-IO  minimum I/O size
      OPT-IO  optimal I/O size
     PHY-SEC  physical sector size
     LOG-SEC  logical sector size
        ROTA  rotational device
       SCHED  I/O scheduler name
     RQ-SIZE  request queue size
        TYPE  device type
    DISC-ALN  discard alignment offset
   DISC-GRAN  discard granularity
    DISC-MAX  discard max bytes
   DISC-ZERO  discard zeroes data
       WSAME  write same max bytes
         WWN  unique storage identifier
        RAND  adds randomness
      PKNAME  internal parent kernel device name
        HCTL  Host:Channel:Target:Lun for SCSI
        TRAN  device transport type
  SUBSYSTEMS  de-duplicated chain of subsystems
         REV  device revision
      VENDOR  device vendor

i couldn't find disk temperature on lsblk and the temperature_sensors column is not working on osquery as well. hddtemp is another package with gives temperature of disk specified. ok2rm is already present on lsblk, which we have removed later on our release(RM column).  Model, serial, vendor are also displayed. A column called 'STATE' in lsblk has status to be running /null. I think, to check if the device is connected in cluster or not, we will be using crd to watch crd/iscsi discover. Please confirm.

**Comment by gila** [comment]
There are typically 3 LEDs for a disk in an enclosure:

1) Identification (its me!)
2) fault (it's me and I have a problem)
3) Ok2RM

We need at least (1 and 2) which in some cases.  I doubt that lsblk shows ok2rm where did you find this @gkGaneshR 

Also as I've discussed with @gkGaneshR during several other discussions, i suggest we do not use lsblk and friends but write proper bindings to the underlying interfaces (i.e udev, libblk etc) for temperature and such we can use the syscall pkg directly from go.

**Comment by gkGaneshR** [comment]
@gila Yes,  We will not be using lsblk and we are considering this issue only as reference for the list of features. We are trying to find out alternatives the go pkg or k8s node problem detector or osquery.
