### ISSUE TITLE
Improvement over "Time taken for jiva controller rescheduling"-elves/e2e/tt-jctrl-resch/

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#546]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:
The main program uses sleep calls to synchronize between main program and goroutines.

**What you expected to happen**:
The objective is to minimize the time taken for execution by removing use of arbitrary sleep call duration and replacing with golang concurrent event handlers.

**Comment by gkGaneshR** [comment]
@AmitKumarDas, @kmova :
I could see the sleep statement on main function is not for synchronization of go function, but is being used only for no operation. Even after removing the sleep, i get similar log only.

**Comment by AmitKumarDas** [comment]
@gkGaneshR Can you post the logs?

**Comment by gkGaneshR** [comment]
Yes, I have said the same thing only. It is used for the purpose of no operation. So, this can be closed.
