### ISSUE TITLE
Suggestions for issue template optimization

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#547]
### FEATURE REQUEST
 
Suggested points of improvement

Current scene
* Every issue is either a *Feature request* or a *Bug report*.

Loose suggestions & random thoughts
1. I often try to delete the filler/suggestive text and double check if I deleted the one I shouldn't have.
     * Good to have Feature template & Bug report template **separated** so that folks can select up to some demarcated place and delete
2. Less is more.

**Comment by kmova** [comment]
Fixed with https://github.com/openebs/openebs/pull/2218
