### ISSUE TITLE
e2e should automate creation of minikube

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#548]
as

## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- It will help e2e to run testlogic (as Kubernetes Job, etc) in Minikube
- It helps in automating creation of Minikube as well as running the openebs operators.
- The rest of the automation is only creation of test logic in individual main.go file

## How to do this ?

- Take a look at elves/e2e project
- Build necessary scripts that creates Minikube & runs openebs operator
- Alternatively, It can be a Vagrantfile that creates a VM with Minikube & then runs openebs operator
- Any other intuitive solution will be highly appreciated

**Comment by kmova** [comment]
The travis integration tests use the Minikube. The tasks of setup and tear down of K8s clusters is now handled via the https://github.com/openebs/litmus.
