### ISSUE TITLE
elves/e2e project should move into maya repository

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#549]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required?

- The current elves/e2e started being an incubator project
- OpenEBS believes this can be graduated into maya repository

## Related Issues

- #517

**Comment by AmitKumarDas** [comment]
@nvzard Can you write down the steps that you will undertake ?
This is not just a cut & move.

**Comment by kmova** [comment]
e2e tests for openebs/maya repo are being added here: https://github.com/openebs/maya/tree/master/integration-tests
