### ISSUE TITLE
Update elves/e2e/tt-jctrl-resch test case to output results into either a success, or a failure

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#550]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- The current tt-jctrl-resch testcase logs the test results and expects manual intervention to determine the  success, failure of the test case
- It will be good to automate this into either a success or a failure
- Eventually, this output can be exported to monitoring libraries & thus helps in deeper analysis drawn out of these metrics.

**Comment by kmova** [comment]
The e2e approach mentioned in this issue has been deprecated.
