### ISSUE TITLE
Update elves/e2e/tt-jctrl-resch test case to output its result into Prometheus

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#551]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- It will be great to have Prometheus be the reporting tool for this as well as any e2e test case
- OpenEBS expects to use Prometheus for its monitoring. It will be better if Prometheus can be used to monitor the various OpenEBS e2e testcases as well.

## How to do it ?

- This seems to be a PUSH based design where e2e test case should push the result at the end of the execution.
- However, are there any intuitive approaches that can solve this problem ?
  - e.g. make the test case wait till the result has been scraped by Prometheus

## Related Issues ?

- #550 

## Any Concerns ?

- Does every test case need to expose a http endpoint to enable Prometheus scraping ?
- Is Prometheus the right tool for this ?

**Comment by kmova** [comment]
The e2e approach mentioned in this issue has been deprecated.
