### ISSUE TITLE
Optimize the performance of OpenEBS Volumes

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#552]
OpenEBS adds a additional layer on top of the disks attached to the kubernetes nodes. This layer needs to be optimized to minimize the performance degradation seen by the applications. This issue will act as an tracker for different techniques/ideas that will be added in the upcoming releases to optimize the performance. 

Some of the ideas are to use:
- Using Caching with Pre-fetch logic
- Optmizing the existing stack

**Comment by vitobotta** [comment]
As a follow up to our conversation on Slack about performance, here are for reference the results of some benchmarks done with volumes provisioned with OpenEBS Jiva engine, OpenEBS cStor engine, Longhorn and Rook (based on Ceph). As suggested, benchmarks have been run using [this YAML](https://github.com/kmova/openebs/blob/dbench-0.8.1/k8s/demo/dbench/dbench-cstor-sparse-1.yaml) template, adjusted for each storage class to test. The test cluster is made of three nodes in Hetzner Cloud with 4 cores, 16GB ram and 160GB SSD storage plus additional SSD volumes of 100GB to test cStor engine; the connection between the nodes is a bit over 2 Gb/sec. OpenEBS 0.8.2 was installed with Helm through Rancher and all the images in use were the default apart from the image for Jiva, which was the latest CI build.

Here's the results:

```
==================
cstor
==================
Random Read/Write IOPS: 1505/2182. BW: 14.3MiB/s / 41.7MiB/s
Average Latency (usec) Read/Write: 3591.09/2887.95
Sequential Read/Write: 4108KiB/s / 34.7MiB/s
Mixed Random Read/Write IOPS: 1256/428
```

```
==================
jiva
==================
Random Read/Write IOPS: 6341/2904. BW: 58.3MiB/s / 45.6MiB/s
Average Latency (usec) Read/Write: 2149.19/
Sequential Read/Write: 54.6MiB/s / 51.5MiB/s
Mixed Random Read/Write IOPS: 3716/1233
```

```
==================
longhorn
==================
Random Read/Write IOPS: 5323/2105. BW: 180MiB/s / 67.2MiB/s
Average Latency (usec) Read/Write: 1903.94/
Sequential Read/Write: 255MiB/s / 69.4MiB/s
Mixed Random Read/Write IOPS: 2860/965
```

```
==================
rook
==================
Random Read/Write IOPS: 12.1k/2637. BW: 263MiB/s / 71.5MiB/s
Average Latency (usec) Read/Write: 1320.95/
Sequential Read/Write: 273MiB/s / 80.4MiB/s
Mixed Random Read/Write IOPS: 5171/1709
```

I love OpenEBS's  and am looking forward to seeing improvements on performance!

Thanks for your hard work.
