### ISSUE TITLE
Optimize docker image for openebs/jiva - clear apt/cache

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#553]
The size of the openebs/jiva docker image is available at https://github.com/openebs/jiva/blob/master/package/Dockerfile 

The current size of the image is at 100+ MB. Check for optimizations, like cleaning up the apt cache. 

Refer: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#each-container-should-have-only-one-concern

**Comment by AmitKumarDas** [comment]
Have a look at concept of init containers in a Kubernetes Pod. It deals with moving the tooling aspects to this init container instead of the main container. It also deals with security aspects.

**Comment by BnMcG** [comment]
I'm happy to take a look at this today.

**Comment by circa10a** [comment]
[Dockerhub](https://hub.docker.com/r/openebs/jiva/tags/) shows a `26%` decrease in size. 
Was - 111mb
Now - 82mb

**Comment by kmova** [comment]
Thanks @circa10a!! Will close this issue.
