### ISSUE TITLE
Explore the possibility of init container in K8s Pod for openebs/jiva image

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#554]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Current jiva image might have a lot of tools installed which increases the overall size of the image
- It may not be appropriate w.r.t security to have some of these tools
- Kubernetes provides Init containers for these stuff.

**Comment by kmova** [comment]
No further refinements are planned for Jiva image at the moment.
