### ISSUE TITLE
Update slack badge on openebs/readme.md with users count

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#559]
Update the slack badge at [README.md](https://github.com/openebs/openebs/blob/master/README.md), to include user information. 

The badge can be changed to : https://openebsslacksignup.herokuapp.com/badge.svg
The link can still remain as : https://openebsslacksignup.herokuapp.com/

**Comment by dread-uo** [comment]
Can this badge source serve badges with the flat square style? I think that it might look with the other ones. What do you think?

**Comment by kmova** [comment]
It would good .. to have all the badges support the same style. The slack bagde is being rendered by https://github.com/rauchg/slackin

I am not sure, if it support the flat square style.

**Comment by dread-uo** [comment]
I took a look and they don't support it. The font used on the badge is different as well.

**Comment by kmova** [comment]
https://github.com/rauchg/slackin/pull/103

**Comment by ProZsolt** [comment]
Seems it's completly broken.(See: #604)

**Comment by Rupeshiya** [comment]
@kmova should i update slack badge with 1/821 users ?.
help please @utkarshmani1997 .
