### ISSUE TITLE
while network fails vagrant up suddenly quits without any warnings/report of failure

### ISSUE THREAD

**Issue by sripadaraj** [openebs/openebs#56]
this may lead to some of the issues like whlie getting pods from the kubemaster-01 will get loaded some of the pods like:
kubectl get pods --all-namespaces
NAMESPACE NAME READY STATUS RESTARTS AGE
kube-system etcd-kubemaster-01 1/1 Running 0 2d
kube-system kube-apiserver-kubemaster-01 1/1 Running 9 2d
kube-system kube-controller-manager-kubemaster-01 1/1 Running 0 2d
kube-system kube-scheduler-kubemaster-01 1/1 Running 1 2d
 [these are the only running files]
"couldn't find some of them"

**Comment by yudaykiran** [comment]
This was an earlier implementation of vagrant where kubeadm init was pulling the kubernetes images from google repos, with the new implementation of vagrant, we are using customized boxes which are pre-packaged with all the kubernetes images and the failure of vagrant up during these image pulls is taken care of.

**Comment by umamukkara** [comment]
Closing based on the comment above
