### ISSUE TITLE
Move all user documentation to a single folder 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#563]
The documentation how to use OpenEBS in Kubernetes is being moved to the following folder:
https://github.com/openebs/openebs/tree/master/documentation/source

The commit made to this folder are picked up by readthedocs and hosted on http://openebs.readthedocs.io/en/latest/

Before the readthedocs was setup, the documentation files were created in several file under the following directory: 
- https://github.com/openebs/openebs/tree/master/k8s/hyperconverged
- https://github.com/openebs/openebs/tree/master/k8s/dedicated

This issue is raised to do the following:
- pick a .md file from the above directories
- find the content of that file has already been moved to readthedocs
- if yes, you can raise a PR to delete the file. 
- if not yet moved, you can raise an issue to move it to readthedocs and also help with moving the content to readthedocs.

**Comment by csnktms** [comment]
happy to help to you with this one!

**Comment by kmova** [comment]
Thanks @csnktms. Feel free to raise new issue for the pages you would like to fix and link them to this issue. All those issues will be tagged with hacktoberfest. Thanks again for pitching into help.

**Comment by omi10859** [comment]
Not found with error docs not found
http://openebs.readthedocs.io/en/latest/

**Comment by kmova** [comment]
Thanks @omi10859 Would be great to have your help in cleaning up the files. The new documentation is available at https://docs.openebs.io

**Comment by omi10859** [comment]
https://github.com/openebs/openebs/pull/1576
