### ISSUE TITLE
Proxy in k8s fails to start

### ISSUE THREAD

**Issue by thasviya** [openebs/openebs#57]

**Comment by sripadaraj** [comment]
try to run the pods once again ..

**Comment by thasviya** [comment]
Hmmm..... ok I'll try to restart the file once again

**Comment by kmova** [comment]
If the issue persists, please re-open the issue with the following details:

Setup details

Steps performed before hitting the issue. 

kubectl get nodes
kubectl get pods

**Comment by thasviya** [comment]
Ok sir i will try
