### ISSUE TITLE
Improve the README related to maya's Vagrantfile

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#573]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- This is w.r.t updating the README once #568 gets checked in.
- The README should update how Vagrant VM can help a developer code, compile & unit test his changes.

## Related Issues

- #568

**Comment by muratkars** [comment]
We are no longer supporting the Vagrant based setup after minikube has become popular. The last supported version was with K8s 1.8.
