### ISSUE TITLE
Prerequisite: Enable Virtualization from BIOS before bringing up VMs

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#574]
FEATURE REQUEST in docs
 **What happened**:
```
$ vagrant up
...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "c4269ec0-a74d-466d-b9fd-116ac73a47df", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole


```
**What you expected to happen**:
- VMs booting normally.

**How to reproduce it (as minimally and precisely as possible)**:
- Try running any VM in a CPU which doesn't support virtualization or has it disabled.

**Anything else we need to know?**:
- Having a `NOTE` to enable virtualization would be nice.

**Comment by vharsh** [comment]
How to fix this on your local system?
- https://stackoverflow.com/a/10772672
