### ISSUE TITLE
Run OpenEBS Operator through Google Cloud Shell shows error: no context exists with the name: "demo-openebs03".

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#576]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT

**What happened**:
while installing Setting up OpenEBS with Kubernetes on Google Container Engine

Run OpenEBS Operator through Google Cloud Shell step i will give this command 
'''kubectl config use-context demo-openebs03''' 
but it shows the following error 
error: no context exists with the name: "demo-openebs03". 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by manigandham** [comment]
The documentation needs work, those are just demo context names used by someone else. If you already have `kubectl` authorized and connected to your cluster, you just need to run this to install the operator and storage classes:

```
kubectl apply -f openebs-operator.yaml
kubectl apply -f openebs-storageclasses.yaml
```
