### ISSUE TITLE
Setup travis build for different binaries/containers in openebs/maya

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#577]
openebs/maya repo now hosts multiple binaries that need to be added to create different container images like:
- maya-apiserver (which contains maya-ctl and maya-apiserver)
- maya (which contains maya-ctl)
- maya-agent (which contains maya-agent and maya-ctl )

The changes will have to be made in openebs/maya/.travis.yml. 

A related issue is to get the build scripts organized. https://github.com/openebs/openebs/issues/499

The scripts for building maya-apiserver can be found under openebs/mayaserver (the source code has been moved as part of https://github.com/openebs/openebs/issues/374)

**Comment by prateekpandey14** [comment]
Closing this issue which is resolved by https://github.com/openebs/maya/pull/116
