### ISSUE TITLE
weave-net-w8fdk and kube-proxy-2mc6t failed to run/restart in kubemaster-01

### ISSUE THREAD

**Issue by sripadaraj** [openebs/openebs#58]
[this is the status of the pods which are displayed after running the kubemaster-01]
some of the proxy and weave fails to start..and get connected. 
kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE
default       hello-world                             1/1       Unknown             0          9h
kube-system   dummy-2088944543-qphfc                  1/1       Running             4          13h
kube-system   etcd-kubemaster-01                      1/1       Running             4          13h
kube-system   kube-apiserver-kubemaster-01            1/1       Running             4          13h
kube-system   kube-controller-manager-kubemaster-01   1/1       Running             4          13h
kube-system   kube-discovery-1769846148-1zxv9         0/1       MatchNodeSelector   0          10h
kube-system   kube-discovery-1769846148-7zpvc         1/1       Running             1          9h
kube-system   kube-discovery-1769846148-w1pfb         0/1       MatchNodeSelector   0          13h
kube-system   kube-dns-2924299975-mbzbn               4/4       Running             16         13h
kube-system   kube-proxy-2mc6t                        1/1       NodeLost            2          13h
kube-system   kube-proxy-xrr45                        1/1       Running             4          13h
kube-system   kube-scheduler-kubemaster-01            1/1       Running             4          13h
kube-system   weave-net-cd2k4                         2/2       Running             8          13h
kube-system   weave-net-w8fdk                         2/2       NodeLost            4          13h

**Comment by kmova** [comment]
It looks like the kubeminon is down? Did you check the status for _"kubectl_ get nodes"

Please re-open the issue in case weave and proxy are not running, after the minion node is up.
