### ISSUE TITLE
Support for multiple versions under the documentation

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#580]
User should be able to switch between different versions of the documentation. Similar to https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational (right most top corner version selection)

**Comment by marceloabk** [comment]
Hi :),
Do you want some automatic thing or just keep it hard coded with the current version?

**Comment by kmova** [comment]
@marceloabk - yes, that will be great. You can use this issue for fixing that : https://github.com/openebs/openebs/issues/582

**Comment by mahebbar** [comment]
Drop down is available for the latest (0.6) and the older version 0.5. When you click on 0.5 it goes to https://v05-docs.openebs.io/ and when you click on Latest it goes to https://docs.openebs.io/
