### ISSUE TITLE
Documentation should set the right version automatically. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#582]
OpenEBS uses readthedocs and the source code is at : https://github.com/openebs/openebs/tree/master/documentation

The release version is hardcoded here: https://github.com/openebs/openebs/blob/master/documentation/source/conf.py

The version variable should automatically fetch the current version during the build time.

**Comment by MagnumOpus21** [comment]
Hi, I went through the conf.py file  and found that the version variable is hardcoded to 0.4 . Where should it fetch the version value from, when it is built?

**Comment by vharsh** [comment]
@MagnumOpus21 You can get the latest `git tag`.
Lets see if better solutions exists.

**Comment by kmova** [comment]
not exactly an helper for auto version detection, using an array of versions is one way stackstorm has handled: https://github.com/StackStorm/st2docs/blob/master/docs/source/conf.py

**Comment by kmova** [comment]
This issue doesn't exist any more. related to readthedocs.
