### ISSUE TITLE
Remove github.com/openebs/maya as a dependency from vendor pkg

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#585]
BUG REPORT 

**What happened**:
1. There is an issue with dependency management, since m-apiserver is merged to maya ,
is should not vendor `github.com/openebs/maya` dependency.
2. Adding any method causing `undefine errors` becuase it referring to maya packages which
 are in vendor folder.

**What you expected to happen**:
1. `github.com/openebs/maya`  should not be a part of vendor pkg (verify the Gopkg.lock file).
2. Can be ignored by mentioning `ignored` tag inside Gopkg.toml file.
` ignored = ["github.com/openebs/maya"] `

**Anything else we need to know?**:
`dep prune` can be a helpful command to remove the unused deps form vendor

**Comment by AmitKumarDas** [comment]
WIP
