### ISSUE TITLE
mayactl should have different deployment options

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#591]
FEATURE REQUEST

- mayactl requires to connect to maya api service or kubectl  for most of its operations
- If mayactl is running as a container inside maya api service Pod then there may not be any issues of broken communication
- NOTE - More thoughts need to be given around what all components should mayactl be communicating with & if these components are all residing in a single K8s Pod !!

**Comment by kmova** [comment]
- mayactl should be containerized to run as a pod within kubernetes 
  - mayactl can be installed using pre-built binaries for different platforms
  - mayactl can be built and used via go get

**Comment by kmova** [comment]
`mayactl` in 0.8.1 has been refactored to interact with K8s and maya-apiserver for getting all the details. (The dependency on jiva controller has been removed). 

However, this needs further improvement to interact with maya-apiserver via the K8s API extensions. 

The latest on running the mayactl and the information it provides is available here:
https://docs.openebs.io/docs/next/mayactl.html
