### ISSUE TITLE
Explore ways to remove the tools used in m-apiserver image

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#592]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Current m-apiserver image includes tools such as:
  - iproute2, curl, net-tools, watch etc
- This increases the size of the docker image
- These were added during the initial releases. Hence, it needs to be verified if these are required now.
- If these tools are required, then explore the possibility of K8s Init Container to meet these requriements

**Comment by kmova** [comment]
the image size of the maya-apiserver has been optimized, after shifting from ubuntu to alpine. The dependencies on the tools still remain as they are helpful for running `mayactl` commands and for troubleshooting. 

Adding this to the GA milestone to check for one final round of cleanup.
