### ISSUE TITLE
The generate-inventory.py script doesn't establish passwordless SSH if keys are not present on remote hosts

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#593]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
The passwordless SSH setup between client and kubernetes VMs when running script with --passwordless=True failed
**What you expected to happen**:
Passwordless SSH setup should be successful
**How to reproduce it (as minimally and precisely as possible)**:
Run inventory ansible role on freshly installed non-vagrant VMs without the .ssh folder for the sudo user

**Anything else we need to know?**:
No

**Comment by ksatchit** [comment]
This is caused by this :

**Comment by abhisheklakra007** [comment]
@ksatchit Can I take this one up?

**Comment by ksatchit** [comment]
Sure @abhisheklakra007 !
