### ISSUE TITLE
The inventory generation needs same username and password for the kubeminion hosts

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#594]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
The inventory generation needs same username and password for the kubeminion hosts. Currently it reuses the same username/password for both kubeminion hosts
**What you expected to happen**:
We need the flexibility to have different usernames and passwords
**How to reproduce it (as minimally and precisely as possible)**:
Run inventory generation with different username/password

**Anything else we need to know?**:
No

**Comment by ksatchit** [comment]
This is a known issue, we need to add code to be able to generate inventory with different username and password.  This will be addressed in subsequent releases. 

For now, the kubernetes nodes need to share the same credentials. If such a user is not already present, it has to be created. This needs to be documented until further enhancements.

**Comment by kmova** [comment]
The code for e2e has been deprecated. For latest please check https://github.com/openebs/litmus
