### ISSUE TITLE
While executing the kubernetes setup playbook is seen to hang indefinitely

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#595]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
setup-k8s hosts step while executing the kubernetes setup playbook is seen to hang indefinitely. 

**What you expected to happen**:
The task should complete and hosts should be added successfully to the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Run the kubernetes setup using ansible with k8s version 1.6.3 

**Anything else we need to know?**:
No

**Comment by ksatchit** [comment]
Fixed by #598 by @yudaykiran
