### ISSUE TITLE
Need to specify curl in pre-requisite package for ansible based openebs setup.

### ISSUE THREAD

**Issue by rafihnl** [openebs/openebs#596]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
The ansible playbook failed in the step where curl is used as shell command. 

**What you expected to happen**:
Curl should be added as a pre-requisite in the documentation
**How to reproduce it (as minimally and precisely as possible)**:
Run setup k8s-localhost role without installing curl package 

**Anything else we need to know?**:
No

**Comment by ksatchit** [comment]
Thanks for the catch ! We will add this in documentation

**Comment by ksatchit** [comment]
The dev docs now includes curl package to be added into list of pre-requisites. Closing this issue
