### ISSUE TITLE
[Troubleshooting] Known issue with minikube

### ISSUE THREAD

**Issue by vharsh** [openebs/openebs#602]
Is this a BUG REPORT or FEATURE REQUEST?
## Neither

**What happened**:
```
harsh@atlantis:~/.kube$ sudo -E minikube start --vm-driver=none
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
E1011 15:23:10.315176   21844 start.go:146] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E1011 15:23:10.315654   21844 start.go:152] Error starting host:  Error getting state for host: machine does not exist
```

**What you expected to happen**:
1. Things to work as documented in [here](http://openebs.readthedocs.io/en/latest/install/dev_solutions.html)

**How to reproduce it (as minimally and precisely as possible)**:
**not very sure**
1. Having an existing cluster with another vm-driver, in a stopped state.

**Anything else we need to know?**:
1. I worked around it by deleting my existing minikube vm(brought up with no flags, i.e. ) with 
`minikube delete`

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 
`Linux atlantis 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Others:
Minikube Version: `minikube version: v0.22.3`
RAM usage = 4240/7381 MiB

**Comment by vharsh** [comment]
Refs : 
1. https://github.com/kubernetes/minikube/issues/459 -> on Windows
2. https://github.com/kubernetes/minikube/issues/519

**Comment by ksatchit** [comment]
A troubleshooting section has to be added with these details here: https://docs.openebs.io/docs/devsolutions.html

**Comment by mahebbar** [comment]
Documentation available at https://staging-docs.openebs.io/docs/next/tsg_install.html#MinikubeStartError
