### ISSUE TITLE
Check if gox can be replaced with default go build tool in maya repo

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#605]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Currently maya uses gox to build the binaries for multi platform needs
- Check if gox can be replaced with default go build tool as gox is not the default choice among go developers

## References

- https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04

**Comment by benjaminmisell** [comment]
Done in PR #110

**Comment by AmitKumarDas** [comment]
Thanks @benjaminmisell for this quick feature. However, gox is still being used in other build.sh files.
I have created an issue https://github.com/openebs/openebs/issues/624

Do you mind taking a look at this ?

**Comment by benjaminmisell** [comment]
Will have a look. It didn't notice the other build scripts in my enthusiasm to make a PR. 😑
