### ISSUE TITLE
maya vsm-list command gives an error

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#614]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 BUG REPORT 

While trying to run OpenEBS in Percona DB  in the step View Performance and Storage Consumption Statistics Using mayactl ```maya vsm-list``` command will not be list the storage volume

**What happened**:
While trying to run OpenEBS in Percona DB  in the step View Performance and Storage Consumption Statistics Using mayactl ```maya vsm-list``` command will not be list the storage volume
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by prateekpandey14** [comment]
Seems like documention is not updated related to running percona DB.

**Comment by prateekpandey14** [comment]
#615 Issue will track this.
