### ISSUE TITLE
Update memory and cpu resources in hyperconverged CI vagrantfile

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#621]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

- The CI test suite for hyperconverged mode (https://github.com/openebs/openebs/blob/master/e2e/ansible/templates/hyperconverged/Vagrantfile.hyperconverged) needs increased resources to aid seamless/faster test execution

**Comment by abhisheklakra007** [comment]
@ksatchit Can I submit a PR for this one? I think un-commenting line#56 and doubling the VM memory will solve this one.

**Comment by vharsh** [comment]
@abhisheklakra007 Sure :+1:

**Comment by ksatchit** [comment]
It may be better to use environment variables to hold the values
