### ISSUE TITLE
gox needs to be replaced with go build for all maya components

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#624]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

## Details of the Bug

A bug has been injected due to fix of https://github.com/openebs/openebs/issues/605

gox tool is still used for building the apiserver component of maya.
buildscripts/apiserver/build.sh still uses gox.

## Fix

This can be fixed by replacing gox with go build in buildscripts/apiserver/build.sh file

**Comment by benjaminmisell** [comment]
Will look at

**Comment by benjaminmisell** [comment]
Done in openebs/maya#111
