### ISSUE TITLE
Make use of Docker to build maya components

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#625]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Details are summarized in a different Project / PR https://github.com/kris-nova/kubicorn/pull/116
- Have a look at its conversations.

It will be great to have Dockerfile that builds all the maya components using the makefile.
The intent here is to remove the OS as a hard requirement.
In fact we have Vagrantfile that can give the same results.
However, VirtualBox, etc & Vagrant installation might be complex vs. Docker installation.

We would definitely like to welcome coders using Windows OS as well.

## Similar issues related to Build

- #605 
- #624 
- #597

**Comment by Klowner** [comment]
I enjoy dockerizing things, I suspect I can get this done pretty quick. Is there an example of building the maya components?

**Comment by AmitKumarDas** [comment]
HI @Klowner , the entire build related stuff is composed in the GNUmakefile. 

This makefile makes use of buildscripts/ directory. 

- buildscripts/ consists of build files related to build of mayactl (the binary is called `maya`)
- buildscripts/apiserver/ contains the build stuff for apiserver component (a component of maya)
- GNUmakefile does the build of maya-agent in one of its targets

**Comment by SadPandaBear** [comment]
I enjoy dockerizing as well, maybe I can be of some help if you want to assign this @Klowner .

**Comment by Klowner** [comment]
Go for it, @SadPandaBear !

**Comment by SadPandaBear** [comment]
I did the all the Docker building for all the binaries generators, but I stuck with the test and cov rules for example. :cry:

**Comment by kmova** [comment]
@SadPandaBear - I like what you did for the binaries. Probably @Klowner has some ideas. 

Some enhancements I can think of is to:
- Makefile can invoke the maya-build container, which installs dependencies, builds and runs the tests. The maya-build-container can store the artifacts into an Volume that is not deleted once the maya-build-container stops. 
- On successful build, Makefile can invoke individual docker files to package the binaries into different containers like - maya-apiserver, maya-ctl, maya-agent etc,. 
- Makefile, can retain the current step of uploading the code-coverage data or docker images to docker hub. 

Do let me know what you think and how we could proceed with the PR. One of the ways we could approach is to merge the PR in the current state and raise enhancement issues for improving it further.

**Comment by AmitKumarDas** [comment]
The above comment from @kmova is really great to have. @SadPandaBear @Klowner it will be great to split them into multiple issues.

**Comment by SadPandaBear** [comment]
@kmova I think we can merge the PR at the current state as a "Dockerize starting point for maya" and then keep opening new issues for any Docker bug/enchacement/etc behavior.
