### ISSUE TITLE
Rename maya/cmd/apiserver -> maya/cmd/maya-apiserver

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#630]
It will be good if all the binaries at [openebs/maya/cmd](https://github.com/openebs/maya/tree/master/cmd) of openebs/maya will follow a standard convention. 

Similar to kubernetes binaries, it will be good to have apiserver as maya-apiserver. 

After renaming the binary name, the associated build scripts at this location also needs to be updated:
- https://github.com/openebs/maya/blob/master/GNUmakefile
- https://github.com/openebs/maya/tree/master/buildscripts/apiserver

**Comment by chentex** [comment]
Do you need cmd folder ```apiserver``` renamed to ```maya-apiserver```

**Comment by SadPandaBear** [comment]
Which tests can be run to make sure everything is ok after renaming the folder?

**Comment by chentex** [comment]
If you run ```make apiserver-image``` this will build an image to with the new command

**Comment by AmitKumarDas** [comment]
@SadPandaBear Test with the new apiserver binary that gets generated via make `apiserver-image` or even `make apiserver.`
This binary can also be run as its CLI. Just run it & post the various options it displays.

**Comment by SadPandaBear** [comment]
Should we rename the binary generated or just the **folder + build script** paths needed?

**Comment by prateekpandey14** [comment]
PR is merged for this issue openebs/maya#113
