### ISSUE TITLE
Explore if snapshot implementation should follow the interfaces exposed by volume

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#631]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Volume interface exposes various volume specific operations:
   - https://github.com/openebs/maya/blob/master/volumes/provisioner/volume.go
- This issue will explore if this is a good design to follow for volume snapshot as well
- The current snapshot implementation does not follow the volume interface.

**Comment by kmova** [comment]
A details design for creating snapshots and clone of OpenEBS (Jiva) Volumes is available at: https://docs.google.com/document/d/1okB86blZsFhrCkJQXnpN40UH6bucc6nDbtkv-ejyxAE/edit#
