### ISSUE TITLE
Reduce the number of OpenEBS StorageClasses to Two. One for applications requiring HA and another for applications not requiring replication.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#638]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:
The openebs-storageclasses.yaml is getting cluttered as more and more applications are being added to the demo applications. It is better to categorize the storage classes based on what type of storage the application needs. 

**What you expected to happen**:
The openebs-storageclasses.yaml must contain only 2 storage classes, named:
- openebs-no-replication (Examples: redis, ETCD...)
- openebs-ha (Example: Percona, MongoDB, Cassandra, Postgres, Jupyter...)

Also:
- For the storage class of type openebs-no-replication the replica count must be 1. 
- All the existing demo applications also have to be updated to reflect these changes in storage classes.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Merged with #652 

The new storage class ```openebs-standard``` has been tested by CI
