### ISSUE TITLE
vagrant kubernetes cluster should have a way to specify the required disk space

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#64]
By default, the vagrant VMs are configured with 10G root partition. Provide an option to either add additional disk or increase the size of the root partition.

**Comment by ksatchit** [comment]
Here are some steps to resize an existing hard drive: 

- https://medium.com/@phirschybar/resize-your-vagrant-virtualbox-disk-3c0fbc607817

Here are steps to add an additional *persistent* disk to the vagrant VM: 

- https://github.com/kusnier/vagrant-persistent-storage

**Comment by kmova** [comment]
We are no longer supporting the Vagrant based setup after minikube has become popular. The last supported version was with K8s 1.8.
