### ISSUE TITLE
OpenEBS Operator should auto-detect cluster capabilities and verify if pre-requisites are met 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#641]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

OpenEBS Operator when deployed should automatically detect the cluster capabilities and verify that the prerequisites are met - like having iSCSI initiator installed on the kubernetes node. All the nodes that satisfy the pre-requisites are the ones that should be considered for scheduling of the openebs volume containers.

**Comment by AmitKumarDas** [comment]
There was a discussion to detect iscsi via an init container within NDM daemonset. Ways are being looked at to report it back to users. Similarly once iscsi is installed, the same needs to be refreshed in the reports.
