### ISSUE TITLE
Travis CI must bring up a Kubernetes Environment and verify all Maya commits within that environment.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#642]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:
Most of the Maya changes require its Kubernetes integration to be verified, the current Travis CI build does not verify this integration. So in order to verify this integration Travis should be able to spawn up a Kubernetes Environment and Run Maya operator related integration related tests on the commits made.

**What you expected to happen**:
Travis should bring up a Kubernetes Environment for the changes in Maya to be verified in that environment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
A good reference to get started of with: https://kinvolk.io/blog/2017/10/running-kubernetes-on-travis-ci-with-minikube/

**Comment by ggarg2906sumo** [comment]
https://github.com/openebs/maya/pull/142 Can Please you review this ?

**Comment by kmova** [comment]
https://github.com/openebs/maya/pull/142 PR installs minkube to the openebs/maya build environment in travis. Need to extend it with test scripts that will launch the maya deployments.
