### ISSUE TITLE
maya should support "-i" option for periodic polling of status

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#643]
As part of the cleanup of dependent packages from container images -
 https://github.com/openebs/openebs/issues/592, one of the package used is "watch". Currently maya volume stats is run with:
```
watch -n 1 maya volume stats <volname>
```

To display the stats every second. The above should be supported inherently by maya. 

```
maya volume stats <volname> -i <duration in secs>
```

**Comment by nvzard** [comment]
@kmova do you need us to modify line 34: `$ maya volume stats <vol>`
 in [volume.go](https://github.com/openebs/maya/blob/1ea038626183cc0f2ecc0ddcb1d573a99903b681/command/volume.go) to `$ maya volume stats <vol> -i <duration in secs>` ?
