### ISSUE TITLE
Add "replica" property as configurable in openebs-storageclasses

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#645]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

**What happened**:
openebs-provisioner always creates two replicas, ignoring the value given for "replica" property inside the openebs-storageclasses yaml.

**What you expected to happen**:
openebs-provisioner must read the replica count assigned to the "replica" property in the openebs-storage classes and bring up the replicas as per the count mentioned in the storage classes.
 
**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the issue:
1. In the openebs-storageclasses.yaml change the "replica" value from "2" to "1".
2. Create a StatefulSet utilizing this storage class.
3. openebs-provisioner ends up creating "2" replicas rather than "1".

**Anything else we need to know?**:

**Comment by kmova** [comment]
@yudaykiran  -- can you change the storage class properties to define parameters using the new policy format as explained in https://github.com/openebs/openebs/issues/863

For example, the replica policy should be:
```
opebebs.io/jiva-replica-count: "1"
```
