### ISSUE TITLE
On premise install steps using Ansible : Update pre-requisites section with min system requirements for VM host

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#646]
BUG REPORT 

In setting up OpenEBS in ansible mention the minimum disk size required for kubemaster and nodes.

**What happened**:
In setting up OpenEBS using ansible, mention the minimum disk size required for kubemaster and nodes .
**What you expected to happen**:
In setting up OpenEBS using ansible, mention the minimum disk size required for kubemaster and nodes in  documentation prerequisites.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
The Vagrant VMs (ubuntu-xenial) that are used in the on-premise installation need a min of 10GB hard-disk space each (3 VMs are recommended for a hyperconverged deployment) and 1GB operating memory

A recommended configuration for the VM host would be to have at least the following specs : 

- 40GB Hard Disk 
- 4GB RAM
- At least 2 CPU cores / vCPUs (if host is a VMware/other guest box)
