### ISSUE TITLE
Simplify the folder structure of volumes directory in maya

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#647]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Current folder structure is as shown below:

```
volumes/
  |__ profile/
           |___ volumeprovisioner/
                      |__ profile.go
  |__ provisioner/
           |___ <some files & directories>

```

- Above folder structure  will be **better represented** with below:

```
volume/
  |__ profiles/
           |___ profiles.go
  |__ provisioners/
           |___ <same files & directories as above>
```

- The changes are:
  - rename `volumes/` to `volume/`
  - rename `volumes/profile/` to `volume/profiles/`
  - move `volumes/profile/volumeprovisioner/profile.go` to `volume/profiles/profiles.go`
  - removal of `volumes/profile/volumeprovisioner/` folder
  - rename `volumes/provisioner/` to `volume/provisioners/`
- NOTE: Mark the additions & removals of plurals in folder names

## Relevant Issues

- #409

**Comment by prateekpandey14** [comment]
Agreed !!! This will remove extra nesting of folder, and makes code structuring simple
