### ISSUE TITLE
Setting up OpenEBS with Kubernetes on Amazon Web Services - $ ./oebs-cloud.sh (this command is repeated twice)

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#649]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 BUG REPORT

If this is a BUG REPORT, please:
```$ ./oebs-cloud.sh```
this command is repeated twice in the doc Setting up OpenEBS with Kubernetes on Amazon Web Services
If the command is executed once it gives the desired output as shown in read the docs.

**Comment by adsrc** [comment]
Made a PR regarding this. Kindly review #650
