### ISSUE TITLE
user instructions for creating new storage class and using it in a target application

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#651]
OpenEBS Storage provides several features that can be customized for each volume. Some of features that could be customized per application are:
- number of replications
- zone or node affinity
- snapshot scheduling
- volume expansion policy
- replication policy 

OpenEBS ships with a set of storage classes that can be readily used (https://github.com/openebs/openebs/blob/master/k8s/openebs-storageclasses.yaml)

But, it is possible that user might want to create new storage classes. The documentation should provide options on how a user can:
- Add custom storage classes
- Use them with the target application
 
## Related Issues

- #409

**Comment by mahebbar** [comment]
The details are available as part of issue #863
