### ISSUE TITLE
Get Started links point to old Vagrantfile

### ISSUE THREAD

**Issue by iamkfred** [openebs/openebs#657]
Following get started links from http://openebs.readthedocs.io/en/latest/ > On-premise Solutions, Step 2 wget for vagrantfile needs to be updated with latest link, or made a relative link to get current version

**Comment by kmova** [comment]
The correct link for the Vagrantfile would be https://raw.githubusercontent.com/openebs/openebs/master/k8s/vagrant/1.7.5/Vagrantfile

**Comment by jameslave** [comment]
I can do that!
