### ISSUE TITLE
Update README.md with the required steps to build the binaries with Docker (Maya)

### ISSUE THREAD

**Issue by SadPandaBear** [openebs/openebs#661]
### Updating Documentation:

After Dockerizing the build process from Maya's binaries, we still need to update the README.md in order to provide to the developers the steps taken to build the project using Docker. 

Below, the step by step of Docker building process:

### Steps to build artifacts with Docker:

1. Build Docker image along with the binaries specified by the Makefile:

`$ docker build -t maya-build-image .`

2. After building and generating the binaries, run the image into a container:

`$ docker run --name maya-build-container maya-build-image`

3. Then you can retrieve the binaries from the Docker instance with `docker cp`:

`$ docker cp maya-build-container:/usr/local/go/src/github.com/openebs/maya/bin ./bin`

**OBS:** Notice you have to retrieve the maya-agent separately, since it's currently being generated in the project's root:

`$ docker cp maya-build-container:/usr/local/go/src/github.com/openebs/maya/maya-agent ./`

### Related Issues & PR's:
openebs/openebs/issues/625
openebs/maya/pull/118

**EDIT:** The approach for building with Docker is still under development so we are not accepting  any **PR** for this issue yet but you can check [here](https://github.com/openebs/openebs/issues/625)our progress and eventually contribute for its development.

**Comment by SiddharthMahapatra12** [comment]
Hello Sir,
I am interested in contributing to this project & I have a query.

Does this README.md belong to the main openEBS repo or any sub-directory?

**Comment by SadPandaBear** [comment]
Hey @SiddharthMahapatra12!

The file we want to update is currently located [here ](https://github.com/openebs/maya/blob/master/CONTRIBUTING.md)and is actually a **CONTRIBUTING.md** 😃. 

You can see there's already an example with Vagrant. What you're going to write is an optional Docker way to build the binaries.

You got it!

**Comment by SiddharthMahapatra12** [comment]
Yes sir,
Will be back with a PR.

**Comment by nvzard** [comment]
@SadPandaBear  I made a PR please review and suggest any changes if required :)
