### ISSUE TITLE
Icon for HELM charts doesn't load

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#670]
**What happened**:
Icon doesn't show up. Link needs to be replaced with a link from openebs.io, current links (https://github.com/openebs/chitrakala/blob/master/logo/png/logo-01.png) is not a direct link to the image. 

**What you expected to happen**:
Icon image link to display image file when you provide the link to the browser.

**How to reproduce it (as minimally and precisely as possible)**:
Add HELM chart to stackpointcloud cluster, if link is valid summary page should show OpenEBS logo.

**Anything else we need to know?**:

**Comment by kmova** [comment]
The correct link should be : https://raw.githubusercontent.com/openebs/chitrakala/master/logo/png/logo-01.png
