### ISSUE TITLE
Run codespell as part of the make and ci tests

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#671]
https://github.com/openebs/openebs/pull/668 fixed the current spellings using https://github.com/lucasdemarchi/codespell

It will be good to have this automated / included as part of the makefiles and automated builds. 

Add a new target to run codespell on the entire directory : https://github.com/openebs/openebs/blob/master/Makefile

As part of the travis CI flag an error if there are errors found. 
https://github.com/openebs/openebs/blob/master/.travis.yml

**Comment by ferhatelmas** [comment]
Another good alternative might be [misspell](https://github.com/client9/misspell) ?

**Comment by mhutter** [comment]
This issue was resolved #714 #714
