### ISSUE TITLE
provisioner should wait to create a PV - till iscsi target is initialized. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#674]
![image](https://user-images.githubusercontent.com/12488783/31822364-2d56842e-b5c6-11e7-88c7-453ab9751d60.png)

When openebs volume is first provisioned, it will have to download the openebs/jiva to the kubernetes node and it can take a few seconds to download. Meanwhile, provisioner is adding a PV with the iSCSI IP and portal details. Since the download is in progress, the PV attach fails and kubelet will log a warning / error before retrying. 

On the next attempt or the subsequent one - as the download finishes, the PV is successfully mounted. (This is seen in the above diagram)

Provisioner should wait to return the PV till the iSCSI portal is up and running.

**Comment by satyamz** [comment]
@AmitKumarDas  Does `maya-apiserver` provides any information on whether iSCSI target is initialized or not? If yes then which endpoint should `openebs-provisioner` consume to make sure this?

**Comment by kmova** [comment]
when we get list volume or volume/info -- maya-apiserver is contacting the kubernetes to get the controller and replica details. if all the controller and replicas are running -- then we should show "active" for the volume status, if one controller and replica are running -- may be degraded if the policy is to have more than one replica and so forth..

**Comment by satyamz** [comment]
@kmova I have one question here, Confirming replicas & controller of volume through `maya-apiserver` is enough to confirm that iSCSI target initialization?  

---
We have `volume/info` endpoint which returns empty `Status` (More here: https://github.com/openebs/mayaserver/blob/master/docs/maya_api_server_k8s.md#read-an-existing-vsm) . 
It would be helpful if maya-apiserver returns the status of the volume: 
`Status` : `active`     -->   If volume is created. Replicas & Controller are running. 
`Status` : `inactive`  -->   If volume is not created.

**Comment by AmitKumarDas** [comment]
@kmova @satyamz time to get the state diag into some implementation.

**Comment by prateekpandey14** [comment]
Maya Apiserver will be returning the following status as phase for PV:
```go
        // VolumePending - used for Volumes that are not available
	VolumePending VolumePhase = "Pending"
	// VolumeAvailable - used for Volumes that are not yet bound
	VolumeAvailable VolumePhase = "Available"
	// VolumeBound is used for Volumes that are bound
	VolumeBound VolumePhase = "Bound"
	// VolumeReleased - used for Volumes where the bound PersistentVol:syntime onumeClaim was deleted
	// released volumes must be recycled before becoming available again
	// this phase is used by the volume claim binder to signal to another process to reclaim the resource
	VolumeReleased VolumePhase = "Released"
	// VolumeFailed - used for Volumes that failed to be correctly recycled or deleted after being released from a claim
	VolumeFailed VolumePhase = "Failed"
```
if we do `curl https://172.17.0.2:5656/latest/volumes/info/<pv-name>` 

```json
{
  "metadata": {
    "annotations": {
      "vsm.openebs.io/replica-count": "1",
      "vsm.openebs.io/targetportals": "10.0.0.197:3260",
      "vsm.openebs.io/volume-size": "2G",
      "vsm.openebs.io/controller-ips": "172.17.0.4",
      "vsm.openebs.io/controller-status": "Running",
      "vsm.openebs.io/replica-ips": "172.17.0.5",
      "vsm.openebs.io/replica-status": "Running",
      "vsm.openebs.io/cluster-ips": "10.0.0.197",
      "vsm.openebs.io/iqn": "iqn.2016-09.com.openebs.jiva:pvc-23837c6a-d036-11e7-97b8-3c970e82da1e"
    },
    "creationTimestamp": null,
    "labels": {},
    "name": "pvc-23837c6a-d036-11e7-97b8-3c970e82da1e"
  },
  "status": {
    "Message": "",
    "Phase": "Bound",
    "Reason": ""
  }
}
```

**Comment by kmova** [comment]
This issue will be mentioned in the release notes for 0.5 as the PR is still under - work-in-progress and has not cut it into this release.
