### ISSUE TITLE
Remove too many CONTRIBUTING docs

### ISSUE THREAD

**Issue by ananya7** [openebs/openebs#685]
**BUG REPORT**
Too many CONTRIBUTING-*.md docs, with same content.

**What you expected to happen**:
- One CONTRIBUTING.md

https://help.github.com/articles/setting-guidelines-for-repository-contributors/
**Environment**:
- kubectl get nodes
- kubectl get pods --all-namespaces
- kubectl get services
- kubectl get sc
- kubectl get pv
- kubectl get pvc
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kmova** [comment]
We will need to merge all the content into this or link them from this single page. https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

**Comment by ananya7** [comment]
I'll do it thanks kmova

**Comment by nvzard** [comment]
@kmova Do you need us to merge the content of CODE_OF_CONDUCT.md and NOTICE.md into CONTRIBUTING.md and remove the two files?

**Comment by kmova** [comment]
@nvzard -- Nope. CODE_OF_CONDUCT and NOTICE are both ok. no change to that. 

Can you review the content in the https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md 

Check to see if it is helpful for new contributors - to find the areas they would like to contribute and the process of contributing. The different areas to contribute is:
- Raising Issues
- User Documentation
- Developer Documentation 
- Adding new examples showing the usage of openebs
- Enhancing the End-to-End testing
- Contributing to the source code

**Comment by Rupeshiya** [comment]
@kmova  What you are expecting from contributors to fix this issue?

**Comment by vipulgupta2048** [comment]
@NisantaSahoo I am taking this up seems simple enough. I have worked on improving documentation before.

**Comment by vipulgupta2048** [comment]
**Need Clarification**
In the contribute directory
1. Design - <still working on that>
2. General - A .gitkeep file is for empty directories, this directory isn't empty and I don't why is a pdf there.
3. Hack - I don't get the use of these shell scripts, a person contributing should know how to git, at least or should learn to while contributing why have shell scripts to do it.

**Comment by vipulgupta2048** [comment]
@prateekpandey14 @utkarshmani1997  please assign me to this issue and answer the questions.
