### ISSUE TITLE
Explore running Jenkins as a pod in a Kubernetes Cluster.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#688]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:
Currently jenkins runs as a standalone application in baremetal. This issue will track its implementation as a pod in kubernetes cluster.

**What you expected to happen**:
Have a containerized Jenkins setup.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Closing this as PR #741  has been merged
