### ISSUE TITLE
setting up OpenEBS in vagrant documentation steps confused

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#701]
BUG REPORT 

If this is a BUG REPORT, please:
 Setting up OpenEBS In Vagrant on premise solution steps two and three are confused
in the documentation

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by mahebbar** [comment]
Vagrant section has been updated as part of pull request #700
