### ISSUE TITLE
Should maya api server become a K8s CRD operator ?

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#705]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

Maya api server executes various openebs volume operations. It is also being coded to
implement volume snapshot related operations. In future, there will some operations related to 
disks etc that will be executed by api server. It might also be entrusted some periodic operations
on snapshots, restoration & verifications. Some or most of these might be available in K8s itself 
via the volume provisioners.

Among other things, all these entities that are being created needs to be managed as well.
OpenEBS has a maya CLI to manage these. It also has a maya UI to manage these. Some of 
these operations are automatically managed via the K8s-volume provisioner-openebs workflow.
However, there will be a need to manage &/ visualize openebs specific things via maya CLI &
maya UI.

Will it be desirable to have these openebs specific entities exposed as extended K8s Kind(s)
and maya api server itself becomes a CRD ? In case of legacy storages, they might be doing 
it in their software. However, in case of OpenEBS it makes sens to think in terms of CRD and 
make the storage operations synonymous with K8s operations. 

As an added benefit, it might be reduce or remove the efforts to maya CLI
as well as in UI. It will be seamlessly integrated with K8s.

NOTE: Having said this, it should work even without K8s in picture if there is such a need.

**Comment by kmova** [comment]
The current approach is to put the openebs specific objects into K8s by extending the schema using CRDs under the openebs.io qualifier. K8s api-server will be used to access/query as well the maya-apiserver or other components will also implement controllers that watch for the CRs.

**Comment by kmova** [comment]
As an example refer : https://github.com/openebs/openebs/pull/1297
