### ISSUE TITLE
Prerequisites are missing for Setting Up OpenEBS with Kubernetes on Local Machine

### ISSUE THREAD

**Issue by NisantaSahoo** [openebs/openebs#708]
BUG REPORT
Prerequisites or minimum requirements like machine type, RAM ,etc are missing in Setting Up OpenEBS with Kubernetes on Local Machine.

**Comment by Sarthakagarwal22** [comment]
What are the exact specifications that need to be updated

**Comment by mahebbar** [comment]
Prerequisites are available in the "Setting Up OpenEBS with Kubernetes on a Local Machine" section. Check http://openebs.readthedocs.io/en/latest/install/on_premise_solutions.html#using-vagrant
