### ISSUE TITLE
error while vagrant up while k8s

### ISSUE THREAD

**Issue by sivaramdinesh** [openebs/openebs#71]
![screenshot from 2017-03-16 22-19-57](https://cloud.githubusercontent.com/assets/25551393/24008249/1e502154-0a97-11e7-8996-9c3570ce1658.png)

**Comment by kmova** [comment]
Please provide the output of the following command:

```
cat /proc/cpuinfo | grep "svm\|vmx"
```

For virtualbox to be able to create VMs, the VT-x should be enabled in the BIOS. The above commands lets you check if it is enabled or not. 

Also, Is your ubuntu an VM or a Host OS (directly installed on laptop or server)?

**Comment by satyamz** [comment]
I got following while doing vagrant up 

```
cb@satyamz:~/containers/k8s-demo$ vagrant up kubemaster-01 
Bringing machine 'kubemaster-01' up with 'virtualbox' provider...
==> kubemaster-01: Importing base box 'openebs/k8s-1.6'...
==> kubemaster-01: Matching MAC address for NAT networking...
==> kubemaster-01: Checking if box 'openebs/k8s-1.6' is up to date...
==> kubemaster-01: Setting the name of the VM: k8s-demo_kubemaster-01_1495104505994_382
==> kubemaster-01: Clearing any previously set network interfaces...
==> kubemaster-01: Preparing network interfaces based on configuration...
    kubemaster-01: Adapter 1: nat
    kubemaster-01: Adapter 2: hostonly
==> kubemaster-01: Forwarding ports...
    kubemaster-01: 22 (guest) => 2222 (host) (adapter 1)
==> kubemaster-01: Running 'pre-boot' VM customizations...
==> kubemaster-01: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "91c21dd6-2613-4a3a-9267-474bfba2aabd", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'k8s-demo_kubemaster-01_1495104505994_382' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine 
```

**Comment by satyamz** [comment]
This issue produces when we have multiple versions of VirtualBox are installed on the machine. 
OpenEBS [needs](https://github.com/openebs/openebs/tree/master/k8s/lib/vagrant/test/k8s/1.6#prerequisites) following : 
``` 
vagrant  >= 1.9.1 
virtualbox >= 5.1 
```
You can resolve this issue by uninstalling old VirtualBox . You can do following :

```  
cb@satyamz:~/containers/k8s-demo$ sudo apt-get remove --purge virtualbox* 
cb@satyamz:~/containers/k8s-demo$ sudo rm ~/"VirtualBox VMs" -Rf 
cb@satyamz:~/containers/k8s-demo$ sudo rm ~/.config/VirtualBox/ -Rf
``` 
Again install VirtualBox 5.1 : 

```
sudo apt-get install virtualbox-5.1

```
More info on installing VirtualBox can be found [here](https://tecadmin.net/install-oracle-virtualbox-on-ubuntu/) 

Once your installation is done, check the versions of VirtualBox and Vagrant. 
It should look like :

``` 
cb@satyamz:~/containers/k8s-demo$ vboxmanage --version 
5.1.22r115126
cb@satyamz:~/containers/k8s-demo$ vagrant --version 
Vagrant 1.9.1 
```  
Finally do the 
```
cb@satyamz:~/containers$ vagrant up 
``` 
That's  all !

**Comment by priyeshwalunj** [comment]
One of solution which worked for me was shutting down the system & restarting it.It work's.

**Comment by ahmedohadi** [comment]
Any new solutions for this issue in the end of 2018?

**Comment by ahmedohadi** [comment]
I'm using vagrant on EC2 and getting same error above!

**Comment by davidnewhall** [comment]
Getting this error on a brand new mac (10.13.6) with a fresh install of vagrant 2.2.2 and virtual box 6.0.0. Have not yet identified a solution, but "removing the second copy of virtual box with apt" isn't going to fly here.

**Comment by wildapt01** [comment]
@davidnewhall 
I'm pretty new at it, so plz bear with me. 
My config: Ubuntu 18.04 on MSFT SB2 (dual boot) w/ custom kernel 4.19.19 - vagrant 2.2.3
Error: could not boot the VM after 'vagrant up', kept poping error 1(.... 
My solution: 
1 - Uninstall VirtualBox with the commands mentioned above by Satyamz.
2 - Restart then 'sudo apt update' then 'sudo apt upgrade -y' in CLI
3 - Install Virtual Box with the help of the following link: [Install VBox] on Ubuntu (https://tecadmin.net/install-oracle-virtualbox-on-ubuntu/), down to Step 3 where I replaced 5.2 by 6.0
4 - Restart then 'sudo apt update' then 'sudo apt upgrade -y' in CLI

After that, vagrant and VirtualBox were playing nice and I was able to spin up my box.

On MacOS, you should replace with the proper command I guess.

**Comment by AFKD98** [comment]
I am facing the same issue on Ubuntu 16.04. I tried everything above. I am using latest versions.
virtualbox version 6.0.8
vagrant version 2.2.5
I think I need to downgrade my versions ?
Help ??

**Comment by rafaa1994** [comment]
> I am facing the same issue on Ubuntu 16.04. I tried everything above. I am using latest versions.
> virtualbox version 6.0.8
> vagrant version 2.2.5
> I think I need to downgrade my versions ?
> Help ??

Try to run 'sudo /sbin/vboxconfig' command after the installing the newest VMBox. I fixed this issue for vagrant 2.2.5 and VM 6.0.8 (after the 5.2) with ubuntu 16.04

**Comment by Bonjunior** [comment]
Bonsoir, j'ai le même problème veillez m'aider.

$ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '9.4.0' is up to date...
==> homestead: Clearing any previously set forwarded ports...
==> homestead: Clearing any previously set network interfaces...
==> homestead: Preparing network interfaces based on configuration...
    homestead: Adapter 1: nat
    homestead: Adapter 2: hostonly
==> homestead: Forwarding ports...
    homestead: 80 (guest) => 8000 (host) (adapter 1)
    homestead: 443 (guest) => 44300 (host) (adapter 1)
    homestead: 3306 (guest) => 33060 (host) (adapter 1)
    homestead: 4040 (guest) => 4040 (host) (adapter 1)
    homestead: 5432 (guest) => 54320 (host) (adapter 1)
    homestead: 8025 (guest) => 8025 (host) (adapter 1)
    homestead: 9600 (guest) => 9600 (host) (adapter 1)
    homestead: 27017 (guest) => 27017 (host) (adapter 1)
    homestead: 22 (guest) => 2222 (host) (adapter 1)
==> homestead: Running 'pre-boot' VM customizations...
==> homestead: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "968c1f09-e707-440e-9c9e-589ae01bd124", "--type", "headless"]

Stderr: VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by AFKD98** [comment]
> > I am facing the same issue on Ubuntu 16.04. I tried everything above. I am using latest versions.
> > virtualbox version 6.0.8
> > vagrant version 2.2.5
> > I think I need to downgrade my versions ?
> > Help ??
> 
> Try to run 'sudo /sbin/vboxconfig' command after the installing the newest VMBox. I fixed this issue for vagrant 2.2.5 and VM 6.0.8 (after the 5.2) with ubuntu 16.04

Yes, sorry for the late reply, but it worked! Thanks a lot!

**Comment by liangchao88** [comment]
I am facing the same issue on windows 10.  I am using latest versions.
virtualbox version 6.1.26r14595
vagrant version 2.2.18
who can help me??

**Comment by mohkoma** [comment]
I had this issue after upgrading to macOS Monterey

The solution was:
Create a `/etc/vbox/networks.conf` (on your host computer, not in the vm) to let you go back to the original IP default range:

(I had to create the vbox folder and the conf file)

I put in the following contents:

`* 0.0.0.0/0 ::/0`

After that I did:

```
vagrant halt
vagrant up
```

And everything started working finally!

thanks to [rtpHarry](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2554#issuecomment-966361590)

**Comment by mohkoma** [comment]
@deepakgl 

I would advice you if you're using mac to check this:
`Go to System Preferences > Security & Privacy Then hit the "Allow" button to let Oracle (VirtualBox) load.`

Reason is that after the update, macOs reset the permission for the VirtualBox
if you find that access request there and allow it you might solve that problem 👆

**Comment by deepakgl** [comment]
Yes, Its working now

Thankyou
