### ISSUE TITLE
Multi-write support

### ISSUE THREAD

**Issue by rimusz** [openebs/openebs#711]
FEATURE REQUEST
Would be good to have multi-write support so apps e.g. Wordpress can share files between pods.
There are more apps which share files between pods.

**Comment by rimusz** [comment]
cc @kmova

**Comment by rimusz** [comment]
it is still on track to be included in v0.5? really looking forward for this feature.
btw when v0.5 is planned to be released?

**Comment by rimusz** [comment]
ping @kmova

**Comment by gila** [comment]
Thanks for your comments. If you want to share files for a blog of some sort, there are several options. One you can use today -- Minio. Secondly, we are working on native NFS support within openEBS but working on increasing performance first. 

HTH

**Comment by kmova** [comment]
We currently support using NFS on top of OpenEBS block volumes
- NFS ganesha using https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
- NFS (via kernel nfs) using https://github.com/openebs/dynamic-nfs-provisioner
