### ISSUE TITLE
Cleanup k8s.go file of maya repo

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#716]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

It is a good practice to remove commented code. It has been seen that the commented
code present in k8s.og at https://github.com/openebs/maya/blob/master/orchprovider/k8s/v1/k8s.go
is no longer relevant.

## How to do ?

- Remove the commented code in this k8s.go file
- Remove the unused imports in this k8s.go file
- Run `make` to test for any compilation errors

**Comment by Aerisu** [comment]
I'll take this, how can I be assigned to this issue?  Can I assign myself?

**Comment by prateekpandey14** [comment]
Sure @Aerisu !!!
Raise a PR and we assign this issue to you.

**Comment by Aerisu** [comment]
I'm having issues cloning the maya project to an IDE (IntelliJ).  Not all the project files appear.  Is there another IDE you would recommend?

**Comment by Aerisu** [comment]
At the moment I'm making my PR changes in Terminal.

**Comment by prateekpandey14** [comment]
Cool, Visual code is better to use.

**Comment by AmitKumarDas** [comment]
@Aerisu @prateekpandey14 I am doing it.

**Comment by Aerisu** [comment]
@AmitKumarDas My apologies, I have been unable to complete this, busy schedule for the next few days.

**Comment by AmitKumarDas** [comment]
Fixed as part of https://github.com/openebs/maya/pull/136
