### ISSUE TITLE
Update the best practices about versioning in contrib/design/code-structuring document

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#718]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## What should be updated w.r.t design ?

- the version folder e.g. v1, v2, etc should be present across all the packages in maya repo
  - current version & the only one available is v1
- apart from types/ other packages should have a logic to get the instance belonging to an exact version
- below sample folder structure will help in understanding version folders

```
types/
   |___ v1/
   |___ v2/
pkg/
   |___ volume/
     |____ policies/
         |_____ router.go
         |_____ v1/
         |_____ v2/
     |_____ provisioners/
         |_____ jiva/
            |___ router.go
            |___ v1/
         |_____ cstor/
            |___ router.go
            |___ v1/
     |_____ transformers/
         |___ k8s/
            |___ router.go
            |___ v1/
```

**Comment by kmova** [comment]
For backward compatibility and for working with different versions of external packages, this kind of structure is useful. 

For internal components, we could go with our own versioning .. v1, v2 etc., .. but when it comes to external dependencies, like k8s.. should we go with k8s versioning schema .. or do we maintain a compatibility table -- like k8s and k8s client..
