### ISSUE TITLE
List block devices using maya-agent

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#724]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
 Since maya-agent exposes local block devices of nodes, it needs to list the available block devices.

**What you expected to happen**:
 It should display the possible local devices on the node with necessary features.
e.g.,
maya-agent device list, should print
```
Name       Size  Type  Mountpoint
sda     931.5G   disk   null
|_sda2      1K   part   null
|_sda5   11.9G   part  [SWAP]
|_sda1  919.6G   part      /
```

**How to reproduce it (as minimally and precisely as possible)**:
 maya-agent device list should be the command.

**Anything else we need to know?**:

**Comment by AmitKumarDas** [comment]
@gkGaneshR Will it be possible to add examples to the statements ? It will help in understanding, testing & documenting better.

**Comment by gkGaneshR** [comment]
@AmitKumarDas added example
