### ISSUE TITLE
Move orchprovider/k8s/v1/util related classes to pkg/client/k8s/v1/ package

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#731]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

Util classes found in orchprovider/k8s/v1/ are related to http client making communications to Kubernetes API server. As this is related to client, it can be moved to pkg/client/k8s/v1/ to adhere
by the code conventions/structure.

**Comment by prateekpandey14** [comment]
fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
