### ISSUE TITLE
Restructure maya/types package

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#749]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- To move away from nested folder structure
- Easy to understand & comphrehend

## How will it look after restructuring

```
types/
 |__ v1/
  |__ doc.go
  |__ volumes.go
  |__ policies.go
  |__ types.go
```
- volumes.go will contain the volume related structure, constants
- profiles.go will contain the profile related structure, constants
- types.go will contain **generic** structure, constants

**Comment by prateekpandey14** [comment]
fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
