### ISSUE TITLE
Structure the volume/policies package

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#751]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- Policies will be a first class citizen in maya
- A policy can be related to below:
  - provisioning,
  - backup,
  - QoS,
  - placement,
  - etc
- The package structure should be easy to understand & comprehend

## How will it look after restructuring?

```
maya/
  |__ volume/
    |__ policies/
      |__ v1/
        |__ doc.go
        |__ policies.go
        |__ policies_k8s_sc.go
        |__ policies_mule_bot.go
        |__ policies_maya_io.go
        |__ policies_envs.go
        |__ policies_defaults.go
```

- policies.go will contain the common stuff related to policy operations

**Comment by prateekpandey14** [comment]
fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
