### ISSUE TITLE
Restructure the maya/orchprovider/k8s/ package

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#752]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- The package & files within it should be easy to understand & comprehend

## How will it look after restructuring?

```
maya/
  |__ orchprovider/
    |__ k8s/
      |__ v1/
        |__ doc.go
        |__ k8s.go
        |__ volume_add.go
        |__ volume_delete.go
        |__ volume_read.go
        |__ volume_list.go
        |__ volume_update.go
        |__ policy.go
        |__ policy_replica_count.go
        |__ policy_controller_count.go
```

- k8s.go will contain the common stuff related to jiva operations
- policy.go will have the common logic to transform the volume policies into a K8s Kind object

**Comment by prateekpandey14** [comment]
fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
