### ISSUE TITLE
Deprecate/Move the features of maya/types/profiles/v1/

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#753]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

- The logic present in maya/types/profiles/v1/ will either get moved or become unused with below fixes:
  - #749 
  - #750 
  - #751 
  - #752

**Comment by prateekpandey14** [comment]
fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
