### ISSUE TITLE
[GOREPORT] Fix linting issues maya/command/volume_list.go

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#760]
Goreport is showing several linting errors. Please see the report at
https://goreportcard.com/report/github.com/openebs/maya

This issue is to fix the errors in
https://github.com/openebs/maya/blob/master/command/volume_list.go
```
Line 33: warning: exported type ListStub should have comment or be unexported (golint)
Line 499: warning: exported function GetVsm should have comment or be unexported (golint)
Line 510: warning: exported function VsmListOutput should have comment or be unexported (golint)
Line 533: warning: exported function RestClient should have comment or be unexported (golint)
Line 574: warning: exported function Parser should have comment or be unexported (golint)
```

**Comment by kmova** [comment]
Hi @kiryteo, yes, the code was refactored to use COBRA based CLI and the new link is at https://github.com/openebs/maya/blob/master/cmd/mayactl/app/command/volumes_list.go

If you are looking at helping with fixing the linting issues, use the latest report here: https://goreportcard.com/report/github.com/openebs/maya

**Comment by kiryteo** [comment]
@kmova Thanks.!

**Comment by sourabh1031** [comment]
@nsathyaseelan @kmova i will work on this

**Comment by kmova** [comment]
Thanks @sourabh1031 - Please let us know if you need any help.
