### ISSUE TITLE
[GOREPORT] Fix linting issues maya/command/volume_update.go

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#772]
Goreport is showing several linting errors. Please see the report at
https://goreportcard.com/report/github.com/openebs/maya

This issue is to fix the errors in
https://github.com/openebs/maya/blob/master/command/volume_update.go
```
Line 8: warning: exported type VsmUpdateCommand should have comment or be unexported (golint)
Line 19: warning: exported method VsmUpdateCommand.Help should have comment or be unexported (golint)
Line 32: warning: exported method VsmUpdateCommand.Synopsis should have comment or be unexported (golint)
Line 36: warning: exported method VsmUpdateCommand.Run should have comment or be unexported (golint)
```

**Comment by mptap** [comment]
@nsathyaseelan: @prateekpandey14: Please could you review? https://github.com/openebs/maya/pull/191
