### ISSUE TITLE
[CODECOV] Write unit tests for maya-apiserver's app/command/error.go logic

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#786]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required

- It will be good to unit test & increase the code coverage
- It will reduce run time logic errors

File to be tested - maya/cmd/maya-apiserver/app/command/error.go file

**Comment by debojitkakoti** [comment]
@AmitKumarDas @prateekpandey14  Is this in https://github.com/openebs/maya repository?

**Comment by RajatVaryani** [comment]
@kmova Can you please assign it to me?

**Comment by gunjan01** [comment]
@AmitKumarDas Is this issue up for grabs? May I work on it ?
