### ISSUE TITLE
[CODECOV] Write unit tests for maya's orchprovider/detect.go logic

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#790]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required

- It will be good to unit test & increase the code coverage
- It will reduce run time logic errors

File to be tested - https://github.com/openebs/maya/blob/master/orchprovider/detect.go

**Comment by marcosinger** [comment]
hey @AmitKumarDas, can I start to work on this one?
