### ISSUE TITLE
[CODECOV] Write unit tests for maya/orchprovider/k8s/v1/util.go's getInClusterCS() logic

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#798]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required

- It will be good to unit test & increase the code coverage
- It will reduce run time logic errors

## Where is the source

- File to be tested - https://github.com/openebs/maya/blob/master/orchprovider/k8s/v1/util.go
- Function to be tested - func (k *k8sUtil) getInClusterCS() (*kubernetes.Clientset, error) {..}

**Comment by lpan** [comment]
@prateekpandey14 I would love to give it a shot :slightly_smiling_face:

**Comment by prateekpandey14** [comment]
Awesome, :+1:

**Comment by prateekpandey14** [comment]
Code has been refactored ..and has been fixed in https://github.com/openebs/maya/pull/812 and https://github.com/openebs/maya/pull/807
