### ISSUE TITLE
Send storage capacity as "openebs.io/capacity" from openebs provisioner

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#810]
## Is this a BUG REPORT 
  BUG REPORT
 

**What happened**:
Currently openebs provisioner is sending capacity as a `volumeprovisioner.mapi.openebs.io/storage-size`
**What you expected to happen**:
Send storage capacity as "openebs.io/capacity" from openebs provisioner

**Comment by kmova** [comment]
m-apiserver is made backward compatible to handle the old and new format for taking the capacity parameter. This needs to be updated though before the older labels are deprecated in the upcoming releases.

**Comment by kmova** [comment]
volume types have been introduced which should be used for exchanging the capacity.

**Comment by kmova** [comment]
As part of 0.7 refactoring to use CAS based provisioning, capacity is sent using the types structured shared between -- maya-apiserver and provisioner.
