### ISSUE TITLE
Set VolumeSpec as per version of maya-apiserver in openebs-provisioner

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#811]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 FEATURE REQUEST

**What happened**:
OpenEBS provisioner is not backward compatible. 
**What you expected to happen**:
openebs-provisioner should query the mapi-server to check what is the latest version supported and frame the struct accordingly.
for example: 
openebs provisioner should send size in older versions.
openebs provisioner should send size & capacity in new versions (deprecate size in favor of capacity).

**Comment by kmova** [comment]
Till 1.0 of openebs, we go with the assumption that both maya-apiserver and provisioner are in the same version.
