### ISSUE TITLE
Specify attached disks for openebs use

### ISSUE THREAD

**Issue by rimusz** [openebs/openebs#815]
Is it possible to use e.g. on GKE PVCs for openebs storage?
As right now it looks like it uses host volume from the node.

**Comment by kmova** [comment]
@rimusz  - this should be in the 0.5 release coming out end of nov.

From the usecase, which one do you prefer (or both):
- one PVC per OpeneEBS Volume Replica 
- one PVC - that can fit multiple OpenEBS Volume Replicas (depending on the IOPS and Storage capacity)

**Comment by rimusz** [comment]
I think this one makes more sense:
* one PVC - that can fit multiple OpenEBS Volume Replicas (depending on the IOPS and Storage capacity)

**Comment by AmitKumarDas** [comment]
@rimusz Have a look at #969 & narrow down to `Storage Pool Policy`
This is available as part of OpenEBS 0.5 release

**Comment by AmitKumarDas** [comment]
http://openebs.readthedocs.io/en/latest/Policies/storage_policy.html#storage-pool-policy
