### ISSUE TITLE
Create a toolset for visualizing various metrics for the OpenEBS repositories 

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#820]
Toolset to visualize GitHub activity using Grafana dashboards. we can refer to this https://github.com/cncf/devstats repo for further help.

**Comment by kmova** [comment]
Am exploring the setting up of devstats for openebs repo. The progress for this is currently being tracked under: https://github.com/kmova/bootstrap/blob/master/devstats/README.md

**Comment by kmova** [comment]
An early version of the devstats for openebs is available at https://devstats.openebs.io
