### ISSUE TITLE
OpenEBS Maya box throws: "Could not get lock /var/lib/dpkg/lock - open" error and exits VM creation.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#83]
Steps to Reproduce:
---------------------
1. Use the vagrant file provided in k8s/demo folder.
2. Do a vagrant up of maya master : vagrant up omm-01
3. Vagrant displays the following error:
    ```
       ==> omm-01: : Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
       ==> omm-01: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
       ==> omm-01: Error executing cmd: exit status 100
    ```

Recurrence:
------------
Intermediary

Workaround:
--------------
VM can be destroyed and recreated.

```
vagrant destroy omm-01
vagrant up omm-01
```

**Comment by kmova** [comment]
Closing this. Haven't seen this issue with the openebs 0.2 boxes.
