### ISSUE TITLE
OpenEBS deployment on Linode Cloud.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/openebs#834]
## Is this a BUG REPORT or FEATURE REQUEST?
   FEATURE REQUEST

**What happened**:

**What you expected to happen**:
Create workflow documentation and automation script for deploying OpenEBS on Linode cloud.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
References : https://github.com/kahkhang/kube-linode
