### ISSUE TITLE
Create proper route handling and mux for API handles

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#837]
FEATURE REQUEST

**What happened**:
better routing machinism for API-server http handles.
For example : gorilla mux can be used to achieve this.

The code which has related to this issue is in www.github.com/openebs/maya repo
And the actual codes specific to API's and server are here https://github.com/openebs/maya/tree/master/cmd/maya-apiserver/app/server

**Comment by dinukadesilva** [comment]
@NisantaSahoo could you help me to understand this issue a bit more.

1) i cannot find where the API exist and how should i get it up

**Comment by prateekpandey14** [comment]
@dinukadesilva sorry, my bad. Updated the issue description with code reference details.
