### ISSUE TITLE
Tutorial for Prerequisites 

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#838]
FEATURE REQUEST

**What happened**:

**What you expected to happen**:
Create tutorial for Prerequisites before going through the OpenEBS
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
OpenEBS installation/setup tutorials for the following categories are available here: https://docs.openebs.io/docs/ - these contain the pre-requisites for the setup along with the actual procedures/steps. 

- Developer solutions (Minikube) 
- On-premise solutions (Vagrant-based, ansible-based for baremetal) 
- Different-platforms (OpenShift) 
- Cloud (AWS, GKE, IBM private cloud) 

@nsathyaseelan , can you be specific about what pre-requisites are missing/needed in these docs ? Thanks !!

**Comment by umamukkara** [comment]
Prerequisites are documented now. Closing.
