### ISSUE TITLE
Tutorial for Use of OpenEBS communities 

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#846]
FEATURE REQUEST

**What happened**:

**What you expected to happen**:
Create the Tutorial for Usefulness of OpenEBS communities and how you can participate.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by 0x48piraj** [comment]
I'm on it :wink:

**Comment by kmova** [comment]
https://github.com/openebs/openebs/tree/master/community
