### ISSUE TITLE
Embed k8s controller into maya-agent and look for events RSA-CRDs

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#865]
FEATURE REQUEST
The feature is to embed k8s controller into maya-agent and look for events RSA-CRDs.
maya-agent should handle events of CRDs in case of new block device is found or removed.

Refer:
https://github.com/openebs/openebs/issues/194

**Comment by kmova** [comment]
This is not being moved to node-disk-manager along with refactored changes from https://github.com/openebs/maya/pull/224

Thank you @gkGaneshR for your efforts on this one.
