### ISSUE TITLE
policy - maya-apiserver should schedule the replica's on nodes where required host directory is present

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#867]
FEATURE REQUEST

Administrator can specify in the storage-class, the directory on which the openebs should store the information. The directory could be an host directory (default /var/openebs) or a new directory -- that is created using a maya-agent - SPC/SP Kinds (i.e. K8s CRDs objects)

- **SPC** - Storage Pool Claim is a template that asks the maya-agent on the nodes to look for a block device, format and mount it into a directory. 
- **SP** - Storage Pool is created corresponding to a node, where the block device is found and mounted. 
- `NOTE` - There can be multiple SPs bound to the same SPC. 
- `NOTE` - There can be multiple SPs created on the same node that are bound to the same SPC.

During a volume provisioning request, api service will extract the name of the SP from the provided
storage-class. API service will then get the SP details & do the following:

  - 1st CheckIn - set the host directory w.r.t container's volume spec
  - 2nd CheckIn - will fetch the list of nodes or node group, host directory that should be available in each of these nodes & finally will do the volume placement using these filtered values

Refer:

- https://github.com/openebs/openebs/issues/194

**Comment by AmitKumarDas** [comment]
@kmova What should be the name of this property ? HostDirectory ? PersistentPath ?

**Comment by AmitKumarDas** [comment]
PR - https://github.com/openebs/maya/pull/190/

**Comment by kmova** [comment]
ReplicaNodeSelector introduced in 0.7,  can be used to specify the nodes on which replicas will be scheduled.
