### ISSUE TITLE
Naming conventions to be used across openebs projects

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#87]
OpenEBS needs to put up a placeholder where various naming conventions are standardised.

e.g. use of the terms:

- `backend vs. replica`
- `frontend vs. frontend controller`
- `volume vs. persistent volume`
- `storage vs. volume`
- `backing storage vs. persistent location`
- `volume provisioner vs. volume provider`

The document should also standardise the use of namespaces for constants & property keys.
In addition, Name, UID, ID etc should be similar in spirit across OpenEBS projects.

**Comment by kmova** [comment]
The following convetions have evolved organically over the past one year and these needs to be documented under the Concepts/Glossary of docs.openebs.io 

- "openebs.io" namespace is used for all openebs related parameters and objects.
- OpenEBS Volume is mapped to a Persistent Volume
- OpenEBS Volume comprises of VolumeController and Volume Replicas. Volume Controller acts as the target to which the Application sends the Data. the Volume controller will then send the data synchronously to Volume Replicas. 
- OpenEBS Replicas write the data to StoragePools. StoragePools are logical objects created by OpenEBS, that are formed using one more Disks or a hostPath.

**Comment by kmova** [comment]
Add a terminology section in the contributor docs.
