### ISSUE TITLE
openebs provisioner should pass name of PVC to maya api service during volume operations

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#874]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

Details mentioned in #872

**Comment by kmova** [comment]
@AmitKumarDas I think the name passed to maya-apiserver -- may already be PVC name. @satyamz can confirm.

**Comment by satyamz** [comment]
We're already passing name of the PVC to maya-apiserver.

**Comment by AmitKumarDas** [comment]
@kmova @satyamz Should we continue using PVC as the name of the openebs volume?

**Comment by kmova** [comment]
yes @AmitKumarDas  Let us not change this for 0.5

Also, if this issue is resolved, please close this one.

**Comment by satyamz** [comment]
> @kmova @satyamz Should we continue using PVC as the name of the openebs volume?

Yes! @AmitKumarDas

**Comment by AmitKumarDas** [comment]
Apart from Name I find that CLAIM cannot be duplicated

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS      REASON    AGE
pvc-8c0dbc81-c534-11e7-aba4-080027a8df8b   5G         RWO            Delete           Bound     default/demo-vol1-claim   openebs-percona             19m
