### ISSUE TITLE
Review text associated with maya-agent commands

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#876]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST
The following are maya-agent cli:
./maya-agent iscsi discover --portal 10.107.180.120
10.107.180.120:3260,-1 iqn.2016-09.com.openebs.jiva:ganesh
For logging into multiple discovered devices,
./maya-agent iscsi login --portal all

 Login to [iface: default, target: iqn.2016-09.com.openebs.jiva:ganesh,
 portal: 10.107.180.120,3260] successful.

./maya-agent iscsi login --portal 10.107.180.120,

Login to [iface: default, target: iqn.2016-09.com.openebs.jiva:ganesh,
portal: 10.107.180.120,3260] successful.

./maya-agent iscsi logout --portal 10.107.180.120
To logout all logged in devices,
./maya-agent iscsi logout --portal all

./maya-agent device list
./maya-agent device format --disk sdd --type=ext4
./maya-agent device mount --disk sdd
./maya-agent device unmount --disk sdd

And the procedure is to build and run:
    It can be verified by docker pull openebs/m-agent:ci inside a kubeminion
    after travis build pass.
    Aliter:
    Or by building with make maya-agent and copying the binary via vagrant shared
    folder and then doing a docker cp to copy inside a docker container as:

On openebs/openebs/k8s/vagrant/1.7.5/,
vagrant up
vagrant ssh kubeminion-01
On openebs/maya,
make maya-agent
cp bin/agent/maya-agent ../openebs/k8s/vagrant/1.7.5/
docker pull openebs/m-agent:ci
docker run -it --entrypoint=/bin/bash --privileged --device=/dev:/dev --net=host openebs/m-agent:ci
Open a new terminal to get container id,
docker ps
copy the container id and copy the binary to /tmp location inside the docker,
docker cp :/tmp

**Comment by gkGaneshR** [comment]
@kmova  I have created new issue to review text associated with maya-agent cli. Please comment the changes required.

**Comment by kmova** [comment]
Need to cover this as part of the https://github.com/openebs/node-disk-manager/pull/1
