### ISSUE TITLE
terraform plan shows error in AWS

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#877]
BUG REPORT 

**What happened**:
while trying to run ``` terraform plan``` in aws it will show the following error
``` Error asking for user input: 1 error(s) occurred:
* provider.aws: dial unix /tmp/plugin367202256|netrpc: connect: no such file or directory ```

**Comment by yudaykiran** [comment]
`terraform init` downloads the latest version of the aws provider plugin. In this particular case the plugin that got downloaded was not backward compatible with the terraform version that was installed.

An issue for this is already logged: https://github.com/terraform-providers/terraform-provider-aws/issues/2121

There are a couple of workarounds:
1. Upgrade terraform to the latest version.
2. In the kubernetes.tf file search for `provider aws` and append `version = "1.1" ` to that section.

I will be raising a PR for the script where it will always download the latest version of terraform.

**Comment by kmova** [comment]
Resolved by https://github.com/openebs/openebs/pull/882
