### ISSUE TITLE
maya-agent iscsi discover panics if flag not passed

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#898]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT : 
maya-agent binary panics if you don't pass flags for iscsi discover.

**What happened**:
maya-agent binary gave run time error if flag `portal` not passed.

**What you expected to happen**:
it should display list of flags instead of generating error.

**How to reproduce it (as minimally and precisely as possible)**:
Run `maya-agent iscsi discover` and it will throw run time error.

**Comment by kmova** [comment]
This is deprecated. this will be take care in the node-disk-manager
