### ISSUE TITLE
Testing Couchbase Usecase Documentation

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#918]
Choose one: TESTING

**What happened**: Documentation requires testing for 0.5

**What you expected to happen**: Check if the procedures are working as expected

**Comment by nsathyaseelan** [comment]
Tested the Couchbase usecase Document in website the procedures are valid.
LGTM

**Comment by nsathyaseelan** [comment]
Tested the Document in openebs.readthedoc.io and the document steps mentioned for couchbase usecase  are  LGTM
