### ISSUE TITLE
Testing MongoDB Usecase Documentation

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#919]
Choose one: TESTING

**What happened**: Documentation must be tested for 0.5

**What you expected to happen**: Check if the documentation procedure works fine.

**Comment by nsathyaseelan** [comment]
- `kubectl apply -f mongo-S.yml` While using this command it shows error 
`error: the path "mongo-S.yml" does not exist`
-  There is no link available  for `Prerequisites`  in the section of Generate Load on the MongoDB Instance.Mention that steps..Once this prerequisites are done then only  able to do next steps
