### ISSUE TITLE
Update doc toc : OpenEBS readthedocs

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#933]
BUG REPORT 

If this is a BUG REPORT, please:
 In read the docs Quick Start there is no information about how to install kubernetes. While open the docs it confused how to setup OpenEBS

**What happened**:
In OpenEBS read the docs Quick start  will not have the instruction how to install kubernetes..
**What you expected to happen**:
Quick Start and SettingUp OpenEBs will comes after the Overview of Setup section  (or) Give the link how to install Kubernetes in Quick start section

**Comment by dungeonmaster18** [comment]
documentation

**Comment by dungeonmaster18** [comment]
label documentation
