### ISSUE TITLE
Update Doc :Setting up OpenEBS on Premise Solution Using Vagrant

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#935]
BUG REPORT 
  -In Setting up OpenEBS on-premise solution using vagrant there are prerequisites given how to install that prerequisites.

**What happened**:
In Setting up OpenEBS on-premise solution using vagrant there are prerequisites are there while trying to install by following the link given and Link given to install vagrant and VirtualBox is confused
**What you expected to happen**:
Please mention the steps how to install the new version of vagrant and VirtualBox.

**Comment by dungeonmaster18** [comment]
Hey thanks for raising this issue @nsathyaseelan , I have few comments on this,
1 The documentation considers users have basic level of knowledge about installation of tools using their website.
2 Even if we consider a completely noob is going to use this then also it will make vagrant documentation unnecessarily long which is not good.
So, I don't see any logic in adding this to docs.

**Comment by mahebbar** [comment]
Agreed to @dungeonmaster18 assuming documentation is for users who have basic knowledge.
