### ISSUE TITLE
Same host-dir & sparse file (disk) reused for every PV creation request

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#938]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

With the latest changes to OpenEBS maya/provisioner, the sparse files representing the data disks consumed by the LHC/LHR(Jiva) pods are created directly on the ```/var/openebs``` directory instead of placing them ```/var/openebs/<volname>```. 

```
test@Host01:/var/openebs$ ls -ltr
total 551212
-rw-r--r-- 1 root root         164 Nov 25 20:24 volume-head-004.img.meta
-rw-r--r-- 1 root root 10737418240 Nov 25 20:24 volume-snap-c27a42ca-2365-48fd-ad2c-8395e4611a12.img
-rw-r--r-- 1 root root         164 Nov 25 20:24 volume-snap-c27a42ca-2365-48fd-ad2c-8395e4611a12.img.meta
-rw-r--r-- 1 root root 10737418240 Nov 25 20:24 volume-snap-631f19f1-247c-49db-8901-0c882211ee97.img
-rw-r--r-- 1 root root         164 Nov 25 20:24 volume-snap-631f19f1-247c-49db-8901-0c882211ee97.img.meta
-rw-r--r-- 1 root root 10737418240 Nov 25 20:24 volume-snap-da007bf1-e2e4-40c8-9ab5-33147c659f32.img
-rw-r--r-- 1 root root         164 Nov 25 20:24 volume-snap-da007bf1-e2e4-40c8-9ab5-33147c659f32.img.meta
-rw-r--r-- 1 root root 10737418240 Nov 25 20:24 volume-snap-54b8c290-3f1c-4710-9987-aa5047214829.img
-rw-r--r-- 1 root root         112 Nov 25 20:24 volume-snap-54b8c290-3f1c-4710-9987-aa5047214829.img.meta
-rw-r--r-- 1 root root          42 Nov 25 20:25 peer.details
-rw-r--r-- 1 root root         184 Nov 25 20:25 volume.meta
-rw-r--r-- 1 root root 10737418240 Nov 25 20:27 volume-head-004.img
-rw------- 1 root root        4096 Nov 25 20:27 revision.counter
```

Since : 

- We don't have an automatic folder-deletion/space-reclamation policy currently where the volume folders are deleted, and also because, 

- Jiva treats ```kubectl delete pvc``` as just connection breaks b/w replicas and controllers for same-sparse files (disks), 

the above behaviour is causing the SAME disk to be reused for every application PVC creation request. 

This means : 

- Multiple application pods created on the kubernetes cluster with their own PVCs will try to reuse the same volume - causing multiple iscsi mounts - resulting in data corruption

- Even if older application is deleted and new one created, it will have access to older pod's data - resulting in a security issue.

**What you expected to happen**:

Volume requests should result in creation of unique directories. Application data should be isolated

**How to reproduce it (as minimally and precisely as possible)**:

Use the "latest" maya-operator and Jiva images to setup OpenEBS on the Kubernetes cluster and run one or more applications.

**Anything else we need to know?**:

The issue was identified by the automated integration tests, wherein, a the deployment of a percona app in the cluster post a libiscsi test resulted in the percona pod undergoing repeated restarts, i.e., entered CrashLoopBackOff state due to the following error, which is about presence of files other than "lost+found" folder on the mysql datadir, causing db initialize failure. 

```
test@Master:~$ kubectl logs -f percona-1869177642-3p1t6
Initializing database
2017-11-25T11:49:38.034151Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2017-11-25T11:49:38.034240Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
2017-11-25T11:49:38.036837Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2017-11-25T11:49:38.037178Z 0 [ERROR] Aborting

```

**Comment by AmitKumarDas** [comment]
HI @ksatchit https://github.com/openebs/maya/pull/202 should solve this issue.
