### ISSUE TITLE
Improve error handling in all openebs shell scripts

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#94]
A bash reference - http://linuxcommand.org/lc3_wss0140.php
Navigate to Errors And Signals And Traps (Oh My!) - Part 1

**Comment by AmitKumarDas** [comment]
Perhaps put it in some scripting guidelines

**Comment by Furinkazan33** [comment]
Can I contribute ?

**Comment by vharsh** [comment]
@Furinkazan33 Yes sure :+1:

**Comment by Furinkazan33** [comment]
@vharsh I need the permission to PR.

**Comment by vharsh** [comment]
@Furinkazan33 No permissions required :+1: 
PRs welcome

**Comment by Furinkazan33** [comment]
Can i contribute ? Where can I put an error handling function ?

**Comment by AmitKumarDas** [comment]
@Furinkazan33 Look out for scripts in openebs/openebs & openebs/maya projects. You can make the changes and provide separate PRs for the same.
