### ISSUE TITLE
Name change for maya-agent to maya-nodebot

### ISSUE THREAD

**Issue by gkGaneshR** [openebs/openebs#966]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

To avoid confusion with maya-io's maya-agent with our node storage manager, our application will have to be renamed to maya-nodebot, based on the voting conducted.

**Comment by kmova** [comment]
This is deprecated now. The node-bot is further changed to node-disk-manager
