### ISSUE TITLE
Update the design/workflow for S3 Backup/Restore

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#98]

**Comment by kmova** [comment]
Feasibility of using the existing longhorn S3 functionality was evaulated and shown to be working. The longhorn replicas where required to be provided with the S3 credentials in a ~.aws/credentials - secret_access_key, access_key_id. 

To the backup api should be passed with the bucket url.

**Comment by joshuacox** [comment]
can this be genericized to work witn [minio](https://www.minio.io/)?   I see that project as very much akin to this project in many ways and makes a lot of sense in attaining cloud agnosticity.

**Comment by kmova** [comment]
Yes @joshuacox Making this work with any S3 interface including minio sounds like the right approach.

**Comment by joshuacox** [comment]
I'd certainly like to pitch in and make this a reality.  I have another project where I've come to rely on openEBS.

[Kugash](https://kubash.org/)

As some future steps there I'd like to setup minio and then get backups running in a kubernetes [cronjob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)

**Comment by kmova** [comment]
This is being worked on by writing OpenEBS plugin to Ark (Valero)  https://github.com/heptio/velero

**Comment by muratkars** [comment]
Minio and other S3 compatible storage can be used for backup and restore. Instructions are here under OpenEBS docs https://docs.openebs.io/docs/next/backup.html
