### ISSUE TITLE
Is there failover feature between AZs? and does it support coreOS, CentOS?

### ISSUE THREAD

**Issue by jm7joo** [openebs/openebs#992]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

1
I want to know whether it's possible to implement openebs in multiple AZs like geo-replication of other sds (software defined storage). it's about failover feature between AZs.

2
I read about coreOS support. https://github.com/openebs/openebs/pull/328
Is it possible to run openebs in k8s cluster of coreOS, centOS, not ubuntu. If it's not, do you have plan for coreOS, centOS ?

thanks.

**Comment by yudaykiran** [comment]
@jm7joo OpenEBS works on CoreOS, but it needs the nodes to have the iscsi service running. Usually what has been observed is that, CoreOS by default does not start the iscsi services, they have to be started manually.

**Comment by epowell101** [comment]
@jm7joo thanks again for your comments.  To clarify - both 1 & 2 are definitely in scope.  1 - Yes, that is a good use case we have heard and are supporting.  How do you foresee the higher level application failing over?  2.  There was a bug in CoreOS support.
