### ISSUE TITLE
Doc : Mention the Prerequisites in MongoDB

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#999]
BUG REPORT 
 
- Mention the Prerequisites steps in MongoDB for installing sysbench

**Comment by mynktl** [comment]
@nsathyaseelan 
Steps for installing sysbench are already mentioned in mongodb prerequisites under k8s/demo and documentaion.

**Comment by nsathyaseelan** [comment]
@mynktl Thanks for the Information.
